### ISSUE TITLE
[BUG] Swiss cheese structures in `mne.viz.Brain.add_volume_labels`

### ISSUE THREAD

**Issue by alexrockhill** [mne-tools/mne-python#10023]
I'm getting structures that have a few holes in them when using the volume labels in `Brain`...
![example](https://user-images.githubusercontent.com/13473576/142739505-04811d66-c32d-43a3-ba21-6c7cac67166c.png)

I wonder if it wouldn't be too hard to implement a binary closing or something of the type but it's in VTK so I'm not really sure what's available there to close structures but I'd assume they would have something like that.

**Comment by agramfort** [comment]
it has holes in the 3D grid in the first place?

**Comment by alexrockhill** [comment]
It's made from marching cubes of the image so it shouldn't use a grid but it does look like the voxels of the image have hole in their segmentation

**Comment by agramfort** [comment]
marching cubes takes a grid as input. you can maybe see if you can add
parameter so
a dilation or something can be done before the marching cubes.

it seems vtk knows how to do things like that:

https://vtk.org/doc/nightly/html/classvtkImageDilateErode3D.html

https://vtk.org/doc/nightly/html/classvtkImageDilateErode3D.html
