### ISSUE TITLE
mne.datasets requires tqdm regardless of verbose

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-python#10022]
I've been experimenting a bit with GitHub actions on a different repository, and I am using the sample dataset from MNE inside the test. The action is failing because `tqdm` was not installed and is required by `pooch` even if `verbose` is set to None / False. 

```
@verbose
def data_path(path=None, force_update=False, update_path=True, download=True,
              verbose=None):  # noqa: D103

    return _download_mne_dataset(
        name='sample', processor='untar', path=path,
        force_update=force_update, update_path=update_path,
        download=download)
```

Shouldn't there be a mode in which we can download without any verbosity?

**Comment by drammock** [comment]
+1 to make it so that download progress bars are suppressed when verbose=False

**Comment by larsoner** [comment]
Agreed.

And while we're at it, if you already have the dataset, pooch shouldn't be required. Right now it will throw an error saying you need pooch even if you already have the dataset and don't need to do any downloading.
