### ISSUE TITLE
What does "as in nitime" refer to? 

### ISSUE THREAD

**Issue by guiomar** [mne-tools/mne-python#10029]
Hi! I see in many parts of the documentation there is this definition:

> **normalization:** str  
Either “full” or “length” (default). If “full”, the PSD will be normalized by the sampling rate as well as the length of the signal **(as in nitime)**.

What does "as in nitime" refer to? should it be "as in time" or does `nitime` has any special meaning? I've tried to do a search but it only drives me to the different fields were this is used.

**Comment by drammock** [comment]
http://nipy.org/nitime/

It's another python package
-------- Original Message --------

**Comment by guiomar** [comment]
Oh! Awesome! Thanks :)

**Comment by guiomar** [comment]
I have open a very minor PR to specify this. Please ignore it if you think it's obvious.
https://github.com/mne-tools/mne-python/pull/10030
