### ISSUE TITLE
ImportError: cannot import name '_check_pylsl_installed' from 'mne.utils'

### ISSUE THREAD

**Issue by Marou-c** [mne-tools/mne-python#10049]
Hi,

I am trying to use mne real-rime and I get this error:
_ImportError: cannot import name 'check_pylsl_installed' from 'mne.utils'
It is used in LSL_Client.py in https://github.com/mne-tools/mne-realtime/tree/main/mne_realtime

I checked mne/utils repo on github and there is no such a file, so it is not an issue with a missing file in my environment.

Was _check_pylsl_installed.py removed from mne/utils repo?

Thanks

**Comment by larsoner** [comment]
Closing for https://github.com/mne-tools/mne-realtime/issues/34
