### ISSUE TITLE
Inconsistency in behavior between concatenate_raws() and concatenate_epochs()

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#10043]
I just ran into an issue because I blindly assumed `concatenate_epochs()` would modify the first element in-place, just like `concatenate_raws()` does. Turns out, this is not the case.

The docstring of the `Returns` portion says:

> The result of the concatenation (first Epochs instance passed in).

The part in the parentheses is misleading.

## Proposed fix

Since we'll probably not find a consensus to change the API, I'd propose to change the docstring of `concatenate_epochs()`:

- The `Return` bit should drop the `(first Epochs instance passed in)` part.
- A `Note` should be added, clearly informing users of the behavior difference between `concatenate_epochs()` and `concatenate_raws()`

Thoughts?

**Comment by agramfort** [comment]
+1 to update the doc with maybe a " .. note:: " to make it obvious?

>
