### ISSUE TITLE
plotting: "bad_color": matplotlib vs pyqtgraph --> a doc issue or a bug?

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-python#10059]
When plotting raw data with the `matplotlib` backend, I can specify the `bad_color` parameter of `raw.plot()` using a tuple like `(1, 0, 0)` (bads are marked in red) ... specifying a tuple like `(255, 0, 0)` results in a ValueError:

> ValueError: RGBA values should be within 0-1 range

However, when plotting the same data with the `pyqtgraph` backend, it's (almost) the other way around: `(255, 0 ,0)` works, but `(1, 0, 0)` doesn't, which probably has to do with the fact that mne-qt-browser uses [pyqtgraph.mkColor](https://pyqtgraph.readthedocs.io/en/latest/functions.html#pyqtgraph.mkColor) which interprets `(1, 0, 0)` as an (practically) invisible line (mkColor is expecting vals in the range 0-255, not 0-1).

I think we could make our lives easy by doing a check of what users pass into `bad_color`, and by documenting that parameter better (i.e., what kinds of "colors" are accepted).

Currently it says ([raw.plot docs](https://mne.tools/stable/generated/mne.io.Raw.html?highlight=raw%20plot#mne.io.Raw.plot)):

```python
"""
bad_color : color object

    Color to make bad channels.
"""
```

cc @marsipu

**Comment by marsipu** [comment]
Yes you are right. We discussed this at [some point](https://github.com/mne-tools/mne-python/pull/9687#discussion_r741076127) but didn't go for a definitive solution.
I think if we change the accepted values for bad-channels, we should also change that for event-colors, annotation-colors, etc. for consistency.

I made a PR for this mne-tools/mne-qt-browser#32
