### ISSUE TITLE
Scaling label overplotting in Raw.plot()

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#10128]
MWE:
```python
# %%
from pathlib import Path
import mne


sample_dir = Path(mne.datasets.sample.data_path())
sample_fname = sample_dir / 'MEG' / 'sample' / 'sample_audvis_raw.fif'

raw = mne.io.read_raw_fif(sample_fname)
raw.plot(butterfly=True, start=0, duration=1)
```
Take a look at the scaling label of the `grad` channels:
![1](https://user-images.githubusercontent.com/2046265/145970298-30a26fcb-c0f6-4cfd-b6c7-1ea74bc53c20.png)

Interestingly, when only plotting MEG channels, this problem does not appear. Also the gray "background noise" is gone:
```
# %%
raw.pick_types(meg=True)
raw.plot(butterfly=True, start=0, duration=1)
```
![2](https://user-images.githubusercontent.com/2046265/145970393-9c527356-443b-46ff-b6bc-3f299a98cd7c.png)

cc @drammock 

```
Platform:       macOS-12.1-x86_64-i386-64bit
Python:         3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 20:33:18)  [Clang 11.1.0 ]
Executable:     /Users/hoechenberger/miniforge3/envs/mne/bin/python
CPU:            i386: 8 cores
Memory:         16.0 GB

mne:            1.0.dev0
numpy:          1.21.4 {blas=NO_ATLAS_INFO, lapack=lapack}
scipy:          1.7.3
matplotlib:     3.5.0 {backend=module://matplotlib_inline.backend_inline}

sklearn:        1.0.1
numba:          0.53.1
nibabel:        3.2.1
nilearn:        0.8.1
dipy:           1.4.1
cupy:           Not found
pandas:         1.3.4
pyvista:        0.32.1 {OpenGL 4.1 INTEL-18.3.5 via Intel(R) Iris(TM) Plus Graphics OpenGL Engine}
pyvistaqt:      0.5.0
ipyvtklink:     0.2.1
vtk:            9.0.3
PyQt5:          5.12.3
ipympl:         0.8.2
mne_qt_browser: 0.1.7
pooch:          v1.5.2
```

**Comment by drammock** [comment]
the "background noise" is a bad channel, and is missing in the second example because `pick_types` defaults to `exclude='bads'`.  The overplotted scale bars are indeed a problem though, will look into it.

**Comment by hoechenberger** [comment]
@drammock LMK if you could need a hand here!

**Comment by drammock** [comment]
> @drammock LMK if you could need a hand here!

if you have bandwidth to look at this, I don't currently; I might on friday?

**Comment by hoechenberger** [comment]
Sorry, I didn't have time to look into this either :(
