### ISSUE TITLE
Provide stand-alone MNE-Python installers

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#10148]
This is currently a WIP carried out at https://github.com/hoechenberger/mne-installers

Would be great to get this tested & ready for MNE-Python 1.0

**Comment by hoechenberger** [comment]
Related issue: https://github.com/conda/constructor/issues/471

**Comment by rob-luke** [comment]
I just tested the stand alone installer on my Intel Mac and it worked perfectly. I was able to run the fNIRS tutorial including obtaining the 3D plots.

**Comment by hoechenberger** [comment]
Windows installers are now also tested on CI, next step is to get a person to run this on their computer ;)

**Comment by hoechenberger** [comment]
Will test this with Guillaume on Wednesday

**Comment by larsoner** [comment]
@hoechenberger when you get a chance, could you open a PR to MNE-Python to show how you would change the installation docs? That way people can look at the updated instructions and try them out (substituting the current prerelease executable names for the final versions) and we can also work on getting the wording right.

**Comment by hoechenberger** [comment]
I will work on revised install docs tomorrow.

**Comment by larsoner** [comment]
@hoechenberger are we good to go here, other than Dipy + Python 3.10 if we can get it? I say we wait a few more days to see if they do cut a release, but ultimately the existing `dipy` + 3.9 works fine

**Comment by hoechenberger** [comment]
Yes, sorry, I'm behind schedule with the updated docs. But the installer seems to work. I do have a list of things I'd like to improve in the future but there are no blockers. I've tested it on Intel Macs and on Linux, and @GuillaumeFavelier has tested it on Windows 10. I'll test on an M1 Mac this Friday (yes, I know, I've promised to do this for weeks now), but I don't expect any issues.

**Comment by hoechenberger** [comment]
@larsoner If you want to give it a try: See the assets provided here: https://github.com/hoechenberger/mne-installers/releases/tag/v1.0.0-pre5

**Comment by larsoner** [comment]
@hoechenberger it looks like there has been some dipy activity moving them closer to release, so it would be good to work on the updated instructions soon

**Comment by hoechenberger** [comment]
on my todo for tomorrow!

**Comment by hoechenberger** [comment]
@larsoner Would you be available for a review on Monday? Still WIP at my end but I think Monday I will have something to share :)

**Comment by larsoner** [comment]
Yep

**Comment by larsoner** [comment]
FYI Dipy 1.5 is out! https://pypi.org/project/dipy/1.5.0/

**Comment by hoechenberger** [comment]
😱😱😱

**Comment by larsoner** [comment]
Just a reminder that, as part of this, we should update https://github.com/hoechenberger/mne-installers/blob/main/README.md to hopefully just point people to https://mne.tools/dev/install/index.html
