### ISSUE TITLE
Report.add_figure() should not close the passed figures

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#10169]
I think if MNE-report creates a figure, it should auto-close, but if user created the figure (as in `add_figure`), it should not close, by default.

_Originally posted by @jasmainak in https://github.com/mne-tools/mne-python/issues/10164#issuecomment-1004045549_

**Comment by agramfort** [comment]
+1

**Comment by larsoner** [comment]
@hoechenberger I can do this early next week unless you want to do it

**Comment by hoechenberger** [comment]
If you've got the time, please go ahead! I believe the fix should be simple – in `add_figure()`, pass `auto_close=False` to the function that converts figures to images
