### ISSUE TITLE
report.add_figure bad tags error not specific enough

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-python#10164]
#### Describe the bug
The report class complains about a bad tag but does not say what characters are bad. Furthermore, I think it should allow numeric characters. I get:

```py
ValueError: The following tags contained invalid characters: 'Subject 2002'
```

#### Steps to reproduce
Just do:

```py
import matplotlib.pyplot as plt
from mne.report import Report

rep = Report()
subject = '2002'
fig = plt.figure()
rep.add_figure(fig, title=f'Figure {i}', tags=(f'Subject {subject}',))
```

#### Expected results
Report is produced with tag "subject 2002"

#### Actual results
Numeric subjects are quite common and I'd imagine a common usecase would be to use numeric tags. I think they should work ... did work previously in `rep.add_figs_to_section`, so I'd consider this a regression.

#### Additional information
I'm on latest master branch

**Comment by jasmainak** [comment]
Also the docstring talks about "collection of str". I thought "collection" was a matplotlib object? It actually crosslinks to matplotlib. Is that what we mean? Shouldn't it be `tuple | list` or something like that?

**Comment by jasmainak** [comment]
Another issue is that the `rep.add_figure` closes the figure. I don't think this should happen as user may still like to interact with the matplotlib figure while having it in a report for easier digestion.

**Comment by agramfort** [comment]
can you give a try to the fix?

**Comment by hoechenberger** [comment]
> Also the docstring talks about "collection of str". I thought "collection" was a matplotlib object? It actually crosslinks to matplotlib. Is that what we mean?

We mean a Python [collection](https://docs.python.org/3/library/collections.html) / container type, i.e., `list`, `set`, `tuple`, `array`. In the dev docstring, this has already been changed to `array-like`: https://mne.tools/dev/generated/mne.Report.html

However we should adjust the error message as well.

We don't allow for [certain characters](https://github.com/mne-tools/mne-python/blob/fecf5411d28f47dcb4ff379976a1b4813edc45a9/mne/report/report.py#L304) in tags, including spaces.

[`_fig_to_img()`](https://github.com/mne-tools/mne-python/blob/fecf5411d28f47dcb4ff379976a1b4813edc45a9/mne/report/report.py#L344) has an `auto_close` parameter (defaults to `True`). We could expose this via the `add_figure()` API. WDYT?

**Comment by jasmainak** [comment]
no strong feelings about exposing `auto_close`. I think if MNE-report creates a figure, it should auto-close, but if user created the figure (as in `add_figure`), it should not close, by default.

**Comment by hoechenberger** [comment]
@jasmainak I think this makes sense, yes!
