### ISSUE TITLE
adding function to list in viz/topo.py

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#10194]
In working on another problem I noticed something is wrong with this line:

https://github.com/mne-tools/mne-python/blob/b7e8c7791b000258b2ba158ddd89eecbbb35af30/mne/viz/topo.py#L670

it's adding a list `['w']` to a function.  Probably should be

```py
        colors = ['w'] + _get_color_list()
```

but I don't have time to follow up at the moment.  I'm surprised this isn't caught by any of our tests.

**Comment by twang5** [comment]
Hi! I would like to look into this. However, this is my first time contributing to an open-source community and I'm not super familiar with the API in MNE yet, so I might need some time to figure out the contribution guidelines and how to test this.
