### ISSUE TITLE
`__init__()` got an unexpected keyword argument `'extract_dir'`

### ISSUE THREAD

**Issue by PABannier** [mne-tools/mne-python#10207]
When trying to get the data path of the `sample` dataset, a `TypeError` is thrown:
`TypeError: __init__() got an unexpected keyword argument 'extract_dir'`.

I run:

```
import mne
from mne.datasets import sample
data_path = sample.data_path()
```

Here's the full traceback:

![Screen Shot 2022-01-15 at 3 38 39 PM](https://user-images.githubusercontent.com/12958149/149625704-07ea404b-6666-466c-8b7f-5411b405e5a0.png)

#### Additional information
I tried the latest dev and stable versions. Same issue.

**Comment by agramfort** [comment]
can you try to update pooch?

pip install -U pooch

**Comment by PABannier** [comment]
Works like a charm. 

Thanks @agramfort !
