### ISSUE TITLE
close BakcGroundPlotter when closing IntracranialElectrodeLocator

### ISSUE THREAD

**Issue by BarryLiu97** [mne-tools/mne-python#10225]
Hi, @alexrockhill, I found the type of __IntracranialElectrodeLocator__ is __pyvistaqt.plotting.BackgroundPlotter__, if adding BackgroundPlotter to a GUI, I supposed we need to manually close it by rewriting the closeEvent with 
```
self._renderer.plotter.close()
self.close()
``` 
Or could directly use __pyvistaqt.QtInteractor__. However, MNE support multiple backends, I thought closing it manually might be easy.

**Comment by alexrockhill** [comment]
Hmm, it does look like the coregistration gui calls `self._renderer.close()` upon close. I'll open a quick PR.
