### ISSUE TITLE
Coreg GUI should suggest to save fiducials and trans if not saved during interactive session

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#10236]
@GuillaumeFavelier when closing the CoregistrationUI and if nothing was saved by the user I would suggest to load a dialog asking the user if he wants to save the fiducials and the trans before closing

cc @hoechenberger

**Comment by GuillaumeFavelier** [comment]
I updated #8833 with:

> - [ ] show a dialog to save trans is not saved
