### ISSUE TITLE
DOC: Description of picks in `ica.plot_properties` is incorrect

### ISSUE THREAD

**Issue by eort** [mne-tools/mne-python#10264]
With the `picks` keyword in `ica.plot_properties`, one can specify what ica sources to plot the properties of. So picks should code the ica source. However, at the moment, the description of picks is the [standard phrase](https://mne.tools/stable/generated/mne.preprocessing.ICA.html#mne.preprocessing.ICA.plot_properties): 

> Channels to include. Slices and lists of integers will be interpreted as channel indices. In lists, channel type strings (e.g., ['meg', 'eeg']) will pick channels of those types, channel name strings (e.g., ['MEG0111', 'MEG2623'] will pick the given channels. Can also be the string values “all” to pick all channels, or “data” to pick data channels. 

plus something specific to this plot: 

> None (default) will pick the first five sources. If more than one components were chosen in the picks, each one will be plotted in a separate figure.

#### Proposed documentation ehancement
The first part does not make sense here, and should be replaced by something like: 

> Sources to plot. None (default) will pick the first five sources. If more than one components were chosen in the picks, each one will be plotted in a separate figure.

**Comment by hoechenberger** [comment]
Good catch, wanna give it a shot?

**Comment by eort** [comment]
Sure, will do!
