### ISSUE TITLE
while i was plotting .nc file in python using cartopy the  error ValueError: DataArray must be 2d

### ISSUE THREAD

**Issue by haritha1022** [mne-tools/mne-python#10263]
###
 import xarray as xr
import cartopy.crs as ccrs
from cartopy import feature as cf
import matplotlib.pyplot as plt
import numpy as np

#Opening and reading data
data=xr.open_dataset("rain33.nc")
print(data)

lon=data.lon[:]
lat=data.lat[:]
#u=data.u[0]; 
#v=data.v[0,::5,::5]
#z=data.z[0]

#lev_2=data.lev_2[:]

rainnc=data.rainnc[0]
#time=data.time[0]

#Margins for the cartopy extent

east = 100
west = 60
north = 38
south = 0

ax = plt.axes(projection=ccrs.PlateCarree())
rainnc.plot.contourf(cmap="jet")
ax.set_extent([west, east, south, north])
ax.coastlines()
ax.add_feature(cf.BORDERS)
#ax.colorbar(cb, pad='2%',label='pa',extend='both',location='right')
#plt.colorbar(cb)

#ax.quiver(x,y,u,v, angles='xy', scale_units='xy', scale=5)
#plt.clim(28000,30000)

plt.savefig("rain3.jpg")
plt.show()

the data contains
Dimensions:    (time: 2, bnds: 2, lon: 378, lat: 351, lev_2: 1)
Coordinates:
  * time       (time) datetime64[ns] 2021-12-30T10:30:00 2021-12-31
  * lon        (lon) float64 77.43 77.45 77.46 77.47 ... 81.32 81.33 81.34 81.35
  * lat        (lat) float64 11.14 11.15 11.16 11.17 ... 14.65 14.66 14.67 14.68
  * lev_2      (lev_2) float64 1e+03
Dimensions without coordinates: bnds
Data variables:
    time_bnds  (time, bnds) datetime64[ns] ...
    rainnc     (time, lev_2, lat, lon) float32 ...

 the error i am getting
 raise ValueError("DataArray must be 2d")
ValueError: DataArray must be 2d

####

**Comment by larsoner** [comment]
@haritha1022 I think you opened this issue for the wrong repository, this does not appear to have anything to do with MNE-Python. It seems like this should be posted to some other repository's issue tracker, or perhaps StackOverflow
