### ISSUE TITLE
misalignment of source space in forward sol

### ISSUE THREAD

**Issue by dasdiptyajit** [mne-tools/mne-python#10308]
#### Describe the bug

Source space alignment in forward solution seems off.   

#### Steps to reproduce
code :
```python
# import parameters
from os.path import join
import mne
from mne import read_source_spaces, read_forward_solution

# get the data
root_dir = join('/', 'media', 'diptyajit', 'Ext_drive', 'MNE-sample-data', '')
subjects_dir = join(root_dir, 'subjects', '')

# read source space
src_fname = join(subjects_dir, 'sample', 'bem', 'sample-oct-6-src.fif')
src = read_source_spaces(src_fname)

# read forward sol
fwd_fname = join(root_dir, 'MEG', 'sample', 'sample_audvis-meg-eeg-oct-6-fwd.fif')
fwd = read_forward_solution(fwd_fname)

print('src output:', src)
print('forward_out:', fwd)

# 1st check source space alignment with original src
fig = mne.viz.plot_alignment(subject='sample', subjects_dir=subjects_dir,
                             surfaces='white', coord_frame='mri',
                             src=src)
mne.viz.set_3d_view(fig, azimuth=173.78, elevation=101.75, distance=0.30, focalpoint=(-0.03, -0.01, 0.03))

# 2nd check source space alignment with src in forward object
fig = mne.viz.plot_alignment(subject='sample', subjects_dir=subjects_dir,
                             surfaces='white', coord_frame='mri',fwd=fwd,
                             src=fwd['src'])
mne.viz.set_3d_view(fig, azimuth=173.78, elevation=101.75, distance=0.30, focalpoint=(-0.03, -0.01, 0.03))
```
#### Expected results
No difference in alignments 

#### Actual results
![origina_src](https://user-images.githubusercontent.com/43450258/153028054-6a272332-807c-4708-9379-e3819c01a66c.png)

![forward_src](https://user-images.githubusercontent.com/43450258/153028042-754e5403-3826-43ce-b8bd-b8ef167afa01.png)

I know that number of source points can different in original source space vs in forward sol.  But why do I get a different alignment? Not sure if its a visualization issue or am I missing something.

**Comment by larsoner** [comment]
This is probably a bug with `plot_alignment` -- after forward computation the `src` is actually in head coordinates. We need to deal with this properly but probably don't...
