### ISSUE TITLE
Inline links could be more visible in the documentation 

### ISSUE THREAD

**Issue by mmagnuski** [mne-tools/mne-python#10310]
Maybe my eyesight is not good, but I think the inline links in the docs could be a little more distinguishable:
![image](https://user-images.githubusercontent.com/8452354/153055180-e7af69e4-8586-4e0e-9d86-7e950efcd612.png)

when pasted here it actually looks better than on my screen because the dark font of main text is a little brighter in the example above (interpolation, I think).

**Comment by cbrnr** [comment]
Good old underline maybe?

**Comment by larsoner** [comment]
Is it the same as https://pydata-sphinx-theme.readthedocs.io/en/latest/ ? If so it would be good to open an issue there first, and address here with CSS overrides only if they reject the idea of making the links clearer somehow

**Comment by mmagnuski** [comment]
@larsonerYes, it looks the same. Ok, I'll try that next week!

**Comment by larsoner** [comment]
They have adjusted this so I'll close. If it's still a problem let's work upstream!
