### ISSUE TITLE
raw.plot() does not produce specified background color.

### ISSUE THREAD

**Issue by fishbacp** [mne-tools/mne-python#10314]
#### Describe the bug
*raw.plot resluts in a graph that does not use specified background color*

Example:

```python
raw.plot(bgcolor='y', color='r')
```

#### Expected results
Background of plot should be yellow and traces colored red.

#### Actual results
Background is white and traces are red.

#### Additional information
Experimentation with other background color options does not change the outcome.

**Comment by mmagnuski** [comment]
As stated on [MNE Discourse discussion](https://mne.discourse.group/t/unable-to-control-background-colors-for-raw-plot/4385/2) I can reproduce the problem. I can take a look at this in around 5 hours, unless someone looks first. :)

**Comment by mmagnuski** [comment]
I looked at this and `mne.raw.plot_raw()` ignores `bgcolor` (does not pass it down to lower-level functions)
I tried adding it to the parameters that are passed around but it seemed to have no effect either when added as `bgcolor` or `facecolor`. I didn't have time to fully trace it down, as the mne raw plotting code is quite complex now (at least comparing to what we had some time ago), but will try to take a look again this evening.
