### ISSUE TITLE
Update docs to reflect new MNE Installer menu entries

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#10446]
https://github.com/conda-forge/mne-feedstock/pull/86 changes the names of the menu entries. We need to update the docs accordingly. I think the only thing we mention explicitly is the `MNE Prompt`, which would be renamed to `Prompt (MNE)`, so we should probably refer to it just as `Prompt`.

cc @larsoner

**Comment by larsoner** [comment]
Agreed, `Prompt` is good enough no matter what else we have in the name (if anything), so in that sense it's nicely future compatible
