### ISSUE TITLE
Argument `theme` of `raw.plot()` or config key does not work on macOS

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-python#10486]
As spotted following the discussion here https://github.com/mne-tools/mne-qt-browser/issues/83 the argument `theme` does not change the theme on either my macOS or Windows computer.

Sample code:

```
import mne


folder = mne.datasets.sample.data_path() / 'MEG' / 'sample'
raw = mne.io.read_raw(folder / 'sample_audvis_filt-0-40_raw.fif', preload=True)
raw.plot(theme='dark')
```

**Comment by mscheltienne** [comment]
@larsoner can you re-open this one?
I am still getting a dark theme no matter the `theme` argument on my macOS with dark-mode enabled a the system-level.
Setting it in the MNE config with `mne.set_config('MNE_BROWSER_THEME', 'light')` does not fix it either.

**Comment by mscheltienne** [comment]
I don't think so. I can give it a shot with the latest version of `mne-qt-browser` later; but in my case, the UI stays in dark mode no matter what. The entire UI.

**Comment by mscheltienne** [comment]
Fresh environment with both `mne-python` and `mne-qt-browser` installed from `main`. No luck, there is something wrong here.

```
folder = mne.datasets.sample.data_path() / 'MEG' / 'sample'
raw = mne.io.read_raw(folder / 'sample_audvis_filt-0-40_raw.fif', preload=True)
raw.plot(theme='light')
```

<img width="1260" alt="Screenshot 2022-04-07 at 15 55 12" src="https://user-images.githubusercontent.com/73893616/162215777-26a2a15a-aeae-4798-a6b1-ac2ca6b27522.png">

**Comment by larsoner** [comment]
Can you investigate a bit? If not, I can try to look in a bit

**Comment by mscheltienne** [comment]
I can look at it tomorrow.
