### ISSUE TITLE
mne-report shows "None"

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-python#10494]
Script to reproduce: https://gist.github.com/jasmainak/483e68a5cb8f42bfe94d4cebe86cef05

Effect:

![image](https://user-images.githubusercontent.com/15852194/161772715-b3c86648-7e6f-4fe4-a040-32d7befbb617.png)

I'm on latest "main" branch

**Comment by agramfort** [comment]
just do `report = mne.Report(title='sub001')` and it works.
