### ISSUE TITLE
[ENH] Reject ICA components based on muscle artifact

### ISSUE THREAD

**Issue by alexrockhill** [mne-tools/mne-python#10514]
@AdoNunes wrote this code + example https://mne.tools/dev/auto_examples/preprocessing/muscle_detection.html to detect muscle artifacts in epochs but I think it's helpful to apply muscle classification to ICA components for EEG which I don't think is documented. The thought is to use `annotate_muscle_zscore` on ICA components. This is really important for TMS-EEG but also pretty important for just EEG, depending on how relaxed the subject's head and face is. Potentially we could use TMS-EEG data from OpenNeuro, there is one dataset. I think maybe not necessary though.

**Comment by alexrockhill** [comment]
Ok might need to be updated because the existing frequency range in MNE of 110-140 Hz doesn't match 

```
Spectral slope measures the gradient (straight line fit) of the log-log power spectrum of an IC between 7 and 75 Hz, a putative frequency range for muscle. ICs of muscular origin are expected to have positive slopes, whereas ICs of neural origin are expected to have negative slopes
```
from the second paper.

The other two criteria that they call for are distance from the vertex (since less muscle up there) and smoothness (topologically mixed ICs are probably mixed muscle and brain activity)

**Comment by alexrockhill** [comment]
Does anyone know if muscle artifact is a big component of MEG? Maybe @larsoner or @agramfort?

**Comment by AdoNunes** [comment]
> Ok might need to be updated because the existing frequency range in MNE of 110-140 Hz doesn't match
> 
> ```
> Spectral slope measures the gradient (straight line fit) of the log-log power spectrum of an IC between 7 and 75 Hz, a putative frequency range for muscle. ICs of muscular origin are expected to have positive slopes, whereas ICs of neural origin are expected to have negative slopes
> ```
> 
> from the second paper.
> 
> The other two criteria that they call for are distance from the vertex (since less muscle up there) and smoothness (topologically mixed ICs are probably mixed muscle and brain activity)

The 110-140 Hz range was based on fieldtrip's parameter. It seems that this frequency range is good enough for detecting muscle activity and not being confounded by other signals. For the most part, muscle artifacts are quite obvious, at least large ones like jaw clenching, and at that frequency range the algorithm does a good job in detecting them.  But as you mention, there might be better criteria to detect muscle activity.

**Comment by alexrockhill** [comment]
Thanks for chiming in @AdoNunes! Good to know that's from FieldTrip, maybe when I do the PR I will add that to the example because I think those sources are super helpful to include.

I think there's two separate problems that you alluded to, gross movements like jaw clenching that ruin epochs and should not try and be salvaged compared to postural muscle activity like that which is omnipresent in T8/9. I think the second type of movement is important to be compensated for by ICA and is not done currently. The gross movements I think are well accounted for by your example and I think `autoreject` does a good job picking that up too. The Journal of Clinical Neurophysiology reference claims there is more EMG than EEG signal based on paralyzing (i.e. on a ventilator!) experimenters in their lab so I think we should mention and try and account for this in the MNE tutorials.

**Comment by agramfort** [comment]
MEG is not too artifacted my EMG. At least much less than EEG and for most
common protocols

my 2c

**Comment by alexrockhill** [comment]
I've looked at the sample data and the muscle components are non-existent in MEG as far as I can tell.

One complication is that, for the default topomap, the properties plot for MEG and EEG data is magnetometers and, since the muscle artifacts don't show up pretty much at all on magnetometers and since the topography is the main confirmation, that makes it difficult to use. You can programmatically pass `topomap_args=dict(ch_type='eeg')` but it would be nice to add a keyboard shortcut to toggle the topomap type. I think pretty easy to do as well.

This is what typical muscle artifacts look like in my experience and in the paper cited above. They are very low ICA components with MEG so it would probably be better to split this out into a separate example with just EEG (although if I were analyzing simultaneous MEG and EEG, I would probably want to go through even these low components to remove them from the EEG or compute ICA separately by channel type).
 
<img width="790" alt="Screen Shot 2022-04-13 at 4 26 54 PM" src="https://user-images.githubusercontent.com/13473576/163285874-c9f7656b-6025-428a-8e34-3b9f6bd7413c.png">
<img width="1195" alt="Screen Shot 2022-04-13 at 4 44 55 PM" src="https://user-images.githubusercontent.com/13473576/163287394-1c6000a2-2db1-466d-a967-d7ca66085b48.png">
