### ISSUE TITLE
Dropdown menu on website is using the wrong theme

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#10553]
Light mode:
<img width="405" alt="Screen Shot 2022-04-20 at 18 38 01" src="https://user-images.githubusercontent.com/2046265/164280423-597ce778-a593-43b4-9505-fc3c18579c76.png">

Dark mode:
<img width="405" alt="Screen Shot 2022-04-20 at 18 38 20" src="https://user-images.githubusercontent.com/2046265/164280455-290a26fa-2429-496b-8d5b-064c30f0788e.png">

This is with Safari 15.4 on macOS.

cc @larsoner

**Comment by larsoner** [comment]
What's the problem with the drop-down? The colors are different and they should be depending on light/dark mode

**Comment by hoechenberger** [comment]
We used to have a blue dropdown in the Light Theme before and that's what I'd expect when using a light theme – the Bootstrap "primary" buttons are supposed to be blue-ish. Therefore I thought it's a bug.

If it's not, then I propose to revert the color change to the light-themed button, please :)

**Comment by hoechenberger** [comment]
But why did the color suddenly change? This button used to be blue until recently…

**Comment by larsoner** [comment]
Not sure, you could trace back in the `mne-tools.github.io` repo if you're really curious. But personally I would just look into fixing it by removing our customizations where possible...

**Comment by larsoner** [comment]
I think this is an intentional change at the pydata-sphinx-theme end as it now uses `var(--pst-color-active-navigation)` via `#version_switcher_button`. I think we should close this as I'd rather not deviate from their theme on this

**Comment by hoechenberger** [comment]
Thanks for investigating this!
