### ISSUE TITLE
 mne.datasets.fetch_fsaverage() throws error if directory does not exist

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#10550]
I just tried to download the fsaverage dataset, but running `mne.datasets.fetch_fsaverage()` throws an error:

    FileNotFoundError: subjects_dir does not exist: /Users/clemens/Documents/mne_data/MNE-fsaverage-data

I have set `MNE_DATA` to `/Users/clemens/Documents/mne_data` in my config – maybe that's why? The `SUBJECTS_DIR` config key is only created after successfully downloading the dataset once.

I don't think this is intended behavior, or is it?

**Comment by larsoner** [comment]
It seems like it should create this folder for you, so probably a bug

**Comment by cbrnr** [comment]
Hm. I can't reproduce it anymore. I created the folder manually, which triggered the download. Now it works even after I delete the folder and the config key.
