### ISSUE TITLE
Web based viz

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#1056]
a suggestion of feature towards a web based interface.

I propose a light python server that would allow you to explore
a database with fif files colored by types (raw.fif, ave.fif, cov.fif etc...)
and with nice tooltips when you move the mouse over the file.
By double click there would be a plot / summary of the content of the file.

any pros or cons? or simpler suggestion to start with?

any technology or existing code to start with?

**Comment by larsoner** [comment]
Closing since @GuillaumeFavelier has made some progress with Jupyter integration
