### ISSUE TITLE
[ENH] visualize "adjacency" for cluster-based permutation tests

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-python#10602]
FieldTrip has "neighbor plots", see https://www.fieldtriptoolbox.org/example/neighbours/ and this screenshot:

![image](https://user-images.githubusercontent.com/9084751/166915453-e75b9180-dc5b-4756-9a76-0b25ee2debc1.png)

I think this would be nice to have for the "adjacency" that we have as a parameter for MNE-Python's cluster permutation tests. Right now I trust [`mne.channels.find_ch_adjacency`](https://mne.tools/stable/generated/mne.channels.find_ch_adjacency.html?highlight=find_ch_adjacency#mne.channels.find_ch_adjacency) to do the right job, ... but it'd be super nice to:

1. check the results via something like a "neighbor plot"
2. maybe even "tweak" what's considered a neighbor (i.e., manipulate a distance threshold)

I have seen one visualization of "adjacency" [here](https://mne.tools/stable/auto_tutorials/stats-sensor-space/75_cluster_ftest_spatiotemporal.html#find-the-fieldtrip-neighbor-definition-to-setup-sensor-adjacency): 

![image](https://user-images.githubusercontent.com/9084751/166915861-3010e2a1-8e95-4c0e-8818-708250f7f60c.png)

But it's not very intuitive to use.

What do you think?

xref https://github.com/mne-tools/mne-python/issues/4859

**Comment by agramfort** [comment]
A plot_ch_adjacency function in mne.viz would be useful yes 👍

**Comment by alexrockhill** [comment]
Definitely!

**Comment by hoechenberger** [comment]
Yes sounds good! Although for many sensors, I'm not sure how useful it will be?

**Comment by sappelhoff** [comment]
> Although for many sensors, I'm not sure how useful it will be?

True, for > 64 sensors I expect this to become more and more crowded ... perhaps useless starting from 100. We'll have to see :eye:

**Comment by sappelhoff** [comment]
cc @mmagnuski --> you seem to already have something like this in your "sarna" repo :-) --> https://github.com/mmagnuski/sarna/blob/2bdc6d9da8c8b72b4baf0473ace1ddb89e55e2aa/sarna/cluster.py#L48

**Comment by mmagnuski** [comment]
@sappelhoff Haha, yes, I do. :) I was thinking of moving it over to mne long time ago, I can try next (upcoming) week.
