### ISSUE TITLE
Add mne-icalabel to sys_info

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-python#10609]
#### Describe the new feature or enhancement
Reference: https://github.com/mne-tools/mne-icalabel/issues/35#issuecomment-1119876806

**Comment by hoechenberger** [comment]
Nice, wanna give it a shot, @adam2392?

Also I need to prepare the conda-forge package, include it in the installers, and announce it on twitter!

**Comment by hoechenberger** [comment]
… or do you require MNE dev?

**Comment by adam2392** [comment]
Good question. I think mne-stable is sufficient(?) for now at least

**Comment by hoechenberger** [comment]
You should add stable to your CI tests if you haven't done so yet:)
