### ISSUE TITLE
Use spatial_colors by default in Evoked.plot()

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#10612]
When using Evoked.plot(), in fact I **always** want to use `spatial_colors=True` as this feature is so simple, yet extremely helpful.

Problem is, on the first try I almost always **forget** to pass the respective parameter, so then I need to amend my code and re-run it.

Also I believe that many users are probably not aware of the feature, as … well, as it's not the default.

Could we not make it such that if we have sensor locations, we use `spatial_colors=True` by default?

We'd still keep the parameter to allow for manual adjustment, of course.

WDYT?

cc @sappelhoff @cbrnr @alexrockhill @adam2392

**Comment by cbrnr** [comment]
Fine with me!

**Comment by sappelhoff** [comment]
Fine with me as well :+1:

**Comment by alexrockhill** [comment]
Definite +1

**Comment by agramfort** [comment]
No objection but make sure no warning is raised by default if no channel locations are present 

This maybe suggests a spatial_colors=‘auto’ by default

**Comment by mmagnuski** [comment]
+1 from me too.

**Comment by drammock** [comment]
reopened by #11151
