### ISSUE TITLE
Geodesic Head Web sensor layouts

### ISSUE THREAD

**Issue by ephathaway** [mne-tools/mne-python#10625]
I would like to add two new sensor layout files for Geodesic Head Web 130 and Geodesic Head Web 280 as resources to mne. These sensor layouts belong to the two EEG recording devices offered by [BEL](https://belco.tech/products/geodesic-head-web), whose technology uses the MFF format.

This addition would simply mean adding the two .lout files to mne/channels/data/layouts directory. This would allow users to call up and apply these sensor layouts when plotting topoplots.

**Comment by larsoner** [comment]
Sounds good to me!
