### ISSUE TITLE
Use scipy.special.expit in Infomax

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#10650]
To avoid an overflow when manually calculating `y = 1.0 / (1.0 + np.exp(-u))`

Suggested by @agramfort in https://mne.discourse.group/t/warning-overflow-encounter-with-infomax/4904/2

**Comment by drammock** [comment]
this would be a nice, small issue to address at the sprint at the end of June. Is it urgent enough to do before then? If not then let's tag as `sprint-2022`

**Comment by hoechenberger** [comment]
It's not at all urgent!

**Comment by drammock** [comment]
this was closed by #10839
