### ISSUE TITLE
Add BrainVision export via pybv

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-python#10678]
Just announcing that I plan to add export capabilities for BrainVision to the MNE-Python export suite. I thought we had discussed this in other issues already, but I can't find them or they have been closed.

I recently added a feature to pybv to write more complex events, so that mne.Annotations can now be properly written, see: https://github.com/bids-standard/pybv/pull/86

In the future I'd also like to be able to export electrode coordinates ("channel locations"), but I think that can come as an add on slightly later: https://github.com/bids-standard/pybv/issues/44

One feature apart from making this available to MNE-Python users would also be that we can refactor what we currently have in mne-bids: https://github.com/mne-tools/mne-bids/blob/fa7a94bb0ef03691aa881f39c90b23a7aa69a923/mne_bids/write.py#L963

Let me know if you have thoughts on this :-)

**Comment by larsoner** [comment]
Yes feel free! I think the idea is to have as much export code as possible live in the downstream lib (in this case, pybv), so that the code in MNE-Python is something simple like:
```
if ext in ('.vhdr', ...):
    pybv = _whatever_our_safe_importer_is('pybv')
    pybv.export_raw(raw)
```
and then you add `pybv` to the `-testing` requirements (and maybe also `environment.yml` and `requirements.yml`), and write one small test here in `test_export.py` or whatever we call it.

**Comment by sappelhoff** [comment]
Sounds good to me! I'd then keep `pybv._export_raw_mne` (for example) a private function in pybv :+1:

**Comment by sappelhoff** [comment]
Is there a reason why [export_evokeds_mff](https://mne.tools/stable/generated/mne.export.export_evokeds_mff.html) is in the public API, instead of being private and users getting to it via `export_evoked`?

**Comment by larsoner** [comment]
Yes because it has extra options, see discussion in and around https://github.com/mne-tools/mne-python/pull/9406#issuecomment-845221655

**Comment by sappelhoff** [comment]
Thanks, I was wondering about that, because [export_raw](https://mne.tools/stable/generated/mne.export.export_raw.html) also has extra options that are only used for EDF :thinking: is that simply an inconsistency due to the way the module recently "grew"?

**Comment by larsoner** [comment]
Can't recall if it was intentional or not, but it would be nice to be consistent
