### ISSUE TITLE
ENH: New mode for plot_dipole_locations

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#10690]
Would other people find it useful if I adapted some plotting code from https://www.sciencedirect.com/science/article/pii/S221315822100022X?via%3Dihub to produce plots like this?

![Screenshot from 2022-05-31 13-06-14](https://user-images.githubusercontent.com/2365790/171233009-f3603ef6-864b-420d-9ef5-16edfbb00890.png)

It could be a new mode for `plot_dipole_locations` for example. I find it a bit more readable than the 3D one with MRI slices when there are multiple dipoles, e.g., this with multiple becomes harder to see immediately the X/Y/Z relationships I think:

![image](https://user-images.githubusercontent.com/2365790/171233466-411364c8-202f-4d9a-b5bc-f4e4c28559cb.png)

**Comment by agramfort** [comment]
I love it ❤

**Comment by mmagnuski** [comment]
@larsoner Cool! How are the slices chosen when there are multiple dipoles?

**Comment by mmagnuski** [comment]
Makes sense, that would be a great addition!
