### ISSUE TITLE
bad indentation in docstring of AverageTFR.plot()

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#10695]
Two of the `versionadded` admonitions are indented when they shouldn't be.

![Screenshot 2022-06-01 at 10-15-47 mne time_frequency AverageTFR — MNE 1 1 dev0 documentation](https://user-images.githubusercontent.com/1810515/171439459-fae01e08-ad0d-4241-b662-7d20fa4eff6c.png)

**Comment by cgohil8** [comment]
I'm happy to work on this.

**Comment by cgohil8** [comment]
Resolved in https://github.com/mne-tools/mne-python/pull/11069.
