### ISSUE TITLE
n_jobs=-1 returns a zero array when computing cross spectral density

### ISSUE THREAD

**Issue by StanSStanman** [mne-tools/mne-python#10696]
#### Describe the bug
Hi, I'm using the mne.time_frequency.csd_multitaper() function to compute the CSD on MEG data, and I realized that the resulting array was a type complex128 filled with zeros. Same when I tried the csd_morlet() function. 
Then I noticed that the bug was present only if I used as argument n_jobs=-1.

Checking inside the code, the bug comes from this line:
https://github.com/mne-tools/mne-python/blob/9e4a0b492299d3638203e2e6d2264ea445b13ac0/mne/time_frequency/csd.py#L1153
where n_jobs should be returned instead of _, in order to set the number of threads according to multiprocessing.cpu_count(), as stated in the control function:
https://github.com/mne-tools/mne-python/blob/9e4a0b492299d3638203e2e6d2264ea445b13ac0/mne/parallel.py#L138

#### Steps to reproduce
To reproduce the error you can replicate the [Compute a cross-spectral density (CSD) matrix](https://mne.tools/dev/auto_examples/time_frequency/compute_csd.html#sphx-glr-auto-examples-time-frequency-compute-csd-py) in the documentation, changing the line `n_jobs = 1`
to 
`n_jobs = -1`

#### Expected results
A [CrossSpectralDensity](https://mne.tools/dev/generated/mne.time_frequency.CrossSpectralDensity.html#mne.time_frequency.CrossSpectralDensity.plot) object containing the CSD array filled with type complex128 values.

#### Actual results
A [CrossSpectralDensity](https://mne.tools/dev/generated/mne.time_frequency.CrossSpectralDensity.html#mne.time_frequency.CrossSpectralDensity.plot) object containing an array filled with type complex128 zeros.

#### Additional information
No additional information.
I can make a pull request if needed.

Thank you in advance!

**Comment by drammock** [comment]
I'm struggling to reproduce; if I run 

```console
$ ipython -i ./examples/time_frequency/compute_csd.py
```

after changing to `n_jobs=-1`, the plots look normal to me  and none of `csd_fft`, `csd_wav`, `csd_mt` are "all zeros".

**Comment by drammock** [comment]
(though at a quick glance, it does seem you're right that we should be capturing the returned `n_jobs` from `parallel_func` rather than using the user-passed value)

**Comment by StanSStanman** [comment]
I don't know why it is working for you, I copied-pasted the example in a notebook and for me it doesn't (it happens the same as with my data), I'll copy paste here a visual proof:
![Schermata da 2022-06-01 18-14-06](https://user-images.githubusercontent.com/26648765/171451214-ac332112-0873-4542-a446-c29e180a2c1f.png)
![Schermata da 2022-06-01 18-14-21](https://user-images.githubusercontent.com/26648765/171451233-2a460df6-b59a-442d-84ff-c4eb8588f193.png)
As you can see, the output says that the computation is done, but no loop is performed.

**Comment by larsoner** [comment]
It looks like the binary blob you linked to is behind `main`:

https://github.com/mne-tools/mne-python/blob/6c15f996b53996534ebbcc0ef8d5fc8ec27d825e/mne/time_frequency/csd.py#L1153-L1155

I think this bug has already been fixed there. Are you on 1.0.3?

**Comment by StanSStanman** [comment]
Oh, my bad, I actually installed the last version from pip and I got the mne version 0.23.4.
I confirm that the bug seems to be solved in the latest version!

Thanks again!
