### ISSUE TITLE
Enable blank GH issue templates

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#10708]
I just wanted to open an issue that wouldn't fit into any of our existing categories:

<img width="1284" alt="Screen Shot 2022-06-03 at 19 36 52" src="https://user-images.githubusercontent.com/2046265/171917262-5f456761-7797-484a-b5f3-b6662187ff3b.png">

So I was looking for something like I've seen on other repositories: a link that allows you to create a blank issue without a template, e.g. like this on conda-forge:

<img width="1284" alt="Screen Shot 2022-06-03 at 19 37 11" src="https://user-images.githubusercontent.com/2046265/171917605-fd9934eb-a8e3-41a1-b2ef-cb324183fdec.png">

Can we please enable this?

**Comment by agramfort** [comment]
I don't know how to do this

**Comment by hoechenberger** [comment]
No need to, @drammock already figured it out!
