### ISSUE TITLE
Changed color scheme?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#10767]
Hello, I'm not sure if this was introduced upstream in our theme or we did that ourselves, but I don't really like the new colors here:

<img width="753" alt="Screen Shot 2022-06-15 at 14 19 50" src="https://user-images.githubusercontent.com/2046265/173825494-1ef55386-cbf7-47aa-8b6e-c0ae7dcbd566.png">

Aside from the reduced contrast compared to what we had before for headlines, now links and headlines have the same color, so I caught myself actually clicking on headlines a few times, believing that's some sort of hyperlink. I don't think this is a great choice of colors.

**Comment by drammock** [comment]
It was an upstream change and I didn't want to executively change it, and I also didn't want to open that can of worms just before the 1.1 release 😆

**Comment by hoechenberger** [comment]
So am I correct in assuming you're not too fond of this change either?

**Comment by drammock** [comment]
> So am I correct in assuming you're not too fond of this change either?

I'd like to change a lot of our colors, actually. The syntax highlighting colors of our code blocks changed sometime between stable and current dev docs, but it happened when I was away on leave and I haven't gone digging yet to figure out what caused it. I liked the way it was on the 1.0 docs.  But yeah, I agree the new primary color is a bit low-contrast on light backgrounds (though looks good on dark) and I can see the point about different colors for headings and links.  Also those colors are pydata "brand" colors so there's an argument that we probably *should* overwrite them.

**Comment by hoechenberger** [comment]
> The syntax highlighting colors of our code blocks changed sometime between stable and current dev docs, but it happened when I was away on leave and I haven't gone digging yet to figure out what caused it. I liked the way it was on the 1.0 docs

Same! The new layout looks quite "dated" to me!

Is the color scheme something we could try to attack during the sprint?

**Comment by drammock** [comment]
> Is the color scheme something we could try to attack during the sprint?

I think it's something you and I should work out, and then in theory anyone could implement it (but it would be easier for one of us to do it).  So possibly, depends on how much time is needed supporting the participants. Maybe I'll tag it for the sprint and assign it to you, to keep it on our radars.
