### ISSUE TITLE
Add demo of Report.add_html() for adding custom HTML or simple text to the report

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#10766]
cc @SophieHerbst

**Comment by sappelhoff** [comment]
I recently added something like that: https://mne.tools/dev/auto_tutorials/intro/70_report.html?highlight=report#adding-custom-html-e-g-a-description-text

#10603

**Comment by hoechenberger** [comment]
Oooooh so **this** is where we saw it before, @SophieHerbst!!

@sappelhoff We were both like, "hum, I thought this was demo'd somewhere!" but couldn't find it anymore. Turns out we should've looked in the dev docs instead of browsing only the stable ones… 🤦
