### ISSUE TITLE
support callable in event_id like trialfun in Fieldtrip

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#1077]
Fieldtrip supports trial/epoch definition using a function that can be used to select good epochs but also return the trialinfo field that can include more details on the trial eg. presence of another marker in the trial, how long after the first event etc.

I propose something like this

```
def fun(events, idx):
    if events[idx, 2] != 1:
          return None
    else:
          return event_info

event_id = dict(cond=fun)
```

this would mimic `event_id = dict(cond=1)` ie. if return None then don't take use new epoch else take it and store info about the event in something like epochs.events_info

you would be able to define an epoch only if marker 1 is followed by 2 or anything you have in mind.

clear?

thoughts?

**Comment by Eric89GXL** [comment]
@agramfort I'm going to close this for now, since we're dealing with events quite a bit now, and apparently haven't needed this for over a year...
