### ISSUE TITLE
trans parameter in make_field_map() should accept Path; docstring needs fixing

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#10784]
Currently only accepts a str, which can be a path or `'auto'`; the behavior of the latter is not documented.

Path should not be a str either, but `path-like`, so this needs fixing too.

**Comment by hoechenberger** [comment]
Turns out the docstring is wrong … is DOESN'T work with a path, it expects a `Transform`. So this is a bug, I suppose…

**Comment by hoechenberger** [comment]
Argh ok it's more complicated than that. The docstring is outdated.

- It does work with a str containing a path
- It **does not** work with a `Path`
- If does work with a `Transform`

**Comment by larsoner** [comment]
To me this is a pretty simple fix to use `_get_trans` like we do elsewhere. It should automatically support everything you want. And then the docstring should be deduplicated / use `%(trans)s`. The function just came way before this helper and hasn't been updated
