### ISSUE TITLE
ENH: Split whats_new

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#10789]
https://mne.tools/dev/whats_new.html is super long. It would probably be nicer to just show the changes from the previous version, but have links to the others in one of the sidebars if possible.

@drammock is this sort of thing possible with a hidden toctree or something?

**Comment by larsoner** [comment]
That would be fine, too!

**Comment by sappelhoff** [comment]
just saying: I like the super-long changelog that has everything in it. It makes searching quite easy while the sidebar with its links still makes the length manageable.
