### ISSUE TITLE
remap evoked/epochs to virtual magnetometers to avoid the ugly combine of planar grads

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#1080]
we should create a new coil type if needed and it would be the best way to interpolate bad MEG or EEG channels....

that would be a killer feature :)

**Comment by mainakjas** [comment]
I just discussed this with @Anevar. Here is the API we chalked out:
```py
surface = 'head'  # can be 'helmet' or 'both' also
from mne import make_virtual_evoked
evoked = make_virtual_evoked(subject=subject, subject_dir=subject_dir, surface=surface)
evoked.plot_topomap()
```
All the other stuff should be hidden from the users. We can create fiff constants for a new coil type. @Anevar can start hashing out the code now that she is familiar with git :) Thoughts @agramfort ?

**Comment by agramfort** [comment]
sounds good but don't forget to pass evoked to make_virtual_evoked :)
