### ISSUE TITLE
ENH: add nilearn-style caching options to certain instance methods

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1087]
It'd love to have caching options for `raw.filter`, the forward model functions and `ICA.decompose_*`. To achieve this we would internally use `joblib.Memory.cache` with input filtering, basically to avoid undesired recomputation triggered by `self`.

I'd like to be able to write:

`ica.decompose_raw(raw, cache=True)`

We would then print the default cache directory and maybe provide  a top-level function to clear cache.

What would people think?

**Comment by Eric89GXL** [comment]
@dengemann this one's a couple years old, still want/need it?
