### ISSUE TITLE
ENH: Comply with ECoG/sEEG best practices where possible

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#10905]
@alexrockhill have you seen https://www.sciencedirect.com/science/article/pii/S1053811922005559 ? When you get a chance, can you make a list here of what we should add / change to comply with what they recommend? Might be worth discussing at the next dev meeting. Or if we already comply, feel free to close!

**Comment by larsoner** [comment]
Okay then let's close, but feel free to reopen if you find we missed anything else

**Comment by alexrockhill** [comment]
It's 200+ pages long so I can't say for sure we are in complete agreement but I did read through more of it and I didn't see anything obvious that we should change. The tone to me seems more of general guidelines from experience/intuition that are fairly open to different approaches and not really data-driven comparisons of results so it's almost hard to run afoul of as long as things make sense practically. There's also a lot of stuff that's not specific to iEEG like cross-frequency coupling which we could add some of but I like how we do it in MNE splitting that stuff outside of the clinical tutorials section.
