### ISSUE TITLE
Version menu is getting too long

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#10932]
Somewhat related to #10789, our version menu is getting pretty long (and if we don't do anything about it, it will get too long rather soon):
<img width="1381" alt="Screen Shot 2022-07-17 at 14 58 42" src="https://user-images.githubusercontent.com/4377312/179399557-aaa5c746-74c4-4a7e-b3a7-7bed43014081.png">

I propose that in addition to *devel* and *stable*, we only show *five* previous versions and then maybe a link to a page with older versions. Alternatively, we might just drop older versions altogether – or is there a particular reason why someone would want to use the documentation for MNE-Python that's over 3 years old?

**Comment by larsoner** [comment]
Another option might be a little CSS fix like
```
.whatever_drop_down
{
   height: 50px;
   overflow: auto;
}
```
I'm also okay with making the list shorter. Happy to defer to @drammock on this

**Comment by larsoner** [comment]
(the above or some similar variant would add a scroll bar to the dropdown)

**Comment by cbrnr** [comment]
A scrollbar would also work, but at some point it too will get unwieldy. I'm fine with a short-term and medium-term solution though.
