### ISSUE TITLE
Add time_unit kwarg to plot_compare_evokeds()

### ISSUE THREAD

**Issue by isabelceo** [mne-tools/mne-python#10948]
I suggets that in Evoked.plot(), plot_compare_evokeds() has time_unit (ms) because it is easier for doctor and neurologists to interpret the resuls.
I hope you have this consideration

**Comment by agramfort** [comment]
you mean add time_unit param to plot_compare_evokeds?

evoked.plot(time_unit='ms') should already does what you want?

**Comment by hoechenberger** [comment]
> you mean add time_unit param to plot_compare_evokeds?

Yes, that's what's being requested here

**Comment by isabelceo** [comment]
Yes, that's I suggets, add time_unit param

**Comment by drammock** [comment]
`Evoked.plot()` *already has* a `time_unit` parameter, since version 0.16. Scroll down a bit you'll see it's highlighted yellow:

https://mne.tools/stable/generated/mne.Evoked.html?highlight=time_unit#mne.Evoked.plot

**Comment by drammock** [comment]
oh, sorry, I misunderstood. You want `time_unit` added to `plot_compare_evokeds`.  Sure, I can do that.
