### ISSUE TITLE
Duplicate function check:check_version and _testing:check_version with 2 slightly different behaviors

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-python#10941]
I was trying to figure out why running with `main` (1.1.0.dev):

```
from mne.utils import check_version, requires_version

check_version("mne", "1.1")  # returns True
requires_version("mne", "1.1")  # marks to skip, i.e. check_version returned False
```

And it turns out there is both https://github.com/mne-tools/mne-python/blob/c6a86f15b8ace3758443f392ba8bfe5a9a0c2878/mne/utils/check.py#L69-L120

and https://github.com/mne-tools/mne-python/blob/c6a86f15b8ace3758443f392ba8bfe5a9a0c2878/mne/utils/_testing.py#L170-L197

Which don't exactly do the same thing, but maybe they should?

**Comment by larsoner** [comment]
Yes the second one should behave like the first where `1.1.dev0` is acceptable when requiring `1.1`. A PR to fix this would be great!

**Comment by mscheltienne** [comment]
Thanks for the confirmation, PR opened, 🤞 for green CIs.
