### ISSUE TITLE
Subject weight & height info keys are not documented

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#10964]
We support `info['subject_info']['weight']`:
https://github.com/mne-tools/mne-python/blob/c12a02000776adb9df18da55ea60c50cbf83827d/mne/io/meas_info.py#L1694

but the `weight` key is not documented at:
https://mne.tools/dev/generated/mne.Info.html

**Comment by sappelhoff** [comment]
What does it even do? Is it "1" in normal cases and can be set to more or less than that when averaging wicth other subjects?

**Comment by hoechenberger** [comment]
I don't think I understand your question … it's just the weight in an unspecified unit, e.g., in kg or lb, stored as a float.

**Comment by hoechenberger** [comment]
Just figured that height isn't documented either.

https://github.com/mne-tools/mne-python/blob/c12a02000776adb9df18da55ea60c50cbf83827d/mne/io/meas_info.py#L1697

**Comment by sappelhoff** [comment]
>  it's just the body weight 

oh, ... okay.

> in an unspecified unit

O.o

**Comment by larsoner** [comment]
Units are kg and m

https://github.com/mne-tools/fiff-constants/blob/30d89d420d50c9e465f46524d4901795dac66741/DictionaryTags.txt#L378-L379

**Comment by sena-neuro** [comment]
Hello! May I take this as my first issue?

**Comment by agramfort** [comment]
Sure ! 🙏
