### ISSUE TITLE
Update theme pin and check docs build

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#10977]
**About a week before a new release**, make a PR that updates our pin of `pydata-sphinx-theme` to the theme's current `HEAD` commit, and do a full docs build (`[circle full]`).  If anything looks awry, do some combination of 

1. working backwards on the theme's tree until you find a commit that works/looks good on our site
2. reporting bugs to the theme (and ideally fixing them and updating the commit hash accordingly)

When you're satisifed that our dev site looks good, merge the PR with the new pin, but **DO NOT CLOSE THIS ISSUE!**  Instead, just bump its milestone so that the process will repeat at the next release.

Places to update the pin:

- `requirements_doc.txt`
- sometimes in the past we've done something different in `tools/circleci_dependencies.sh` so double-check if a change is needed there

**Comment by drammock** [comment]
No I agree that this was dealt with for 1.1 by #10973

**Comment by larsoner** [comment]
@drammock how feasible would it be to pin to a released version? It looks like ~4 minutes is spent in every SphinxWindows Azure build to `pyproject.toml` build the pinned commit hash, which we should be able to skip if we use a wheel on PyPI

**Comment by drammock** [comment]
Should be ok. A new release is due in a week or two, if that matters.
