### ISSUE TITLE
Is the ica.fit function compatible with GPU?

### ISSUE THREAD

**Issue by xiaohao-lin1** [mne-tools/mne-python#10981]
#### Describe the new feature or enhancement
Hi currently the ica.fit function takes 15min to run for a 4GB raw data type. May I know if it is run-able on a GPU?

 

#### Describe your proposed implementation
*Describe how you think the feature or improvement should be implemented (e.g., 
as a new method on an existing class? as new capability added to an existing
method?) If you're not sure, please delete this section and the next section.*

#### Describe possible alternatives
*If you've suggested an implementation above, list here any alternative
implementations you can think of, and brief comments explaining why the chosen
implementation is better.*

#### Additional comments
*Add any other context or screenshots about the feature request here.*

**Comment by larsoner** [comment]
No, currently it's CPU-only. My only thought is that you could consider using `decim` to speed things up -- in principle you shouldn't need to fit all 4GB worth of samples to get a good ICA decomposition. For further optimization questions, feel free to post to https://mne.discourse.group/
