### ISSUE TITLE
multiple annotations into one event

### ISSUE THREAD

**Issue by irmakoz1** [mne-tools/mne-python#10995]
I have a Brainvision data that for each 3 condition have four annotation markers. How can I combine these 4 annotations and categorize as one event, then be able to compare these 3 events? I am quite new to MNE, so if it does not make sense sorry

**Comment by drammock** [comment]
For questions about analysis and usage, please use the MNE Forum (https://mne.discourse.group). The GitHub issues are for bug tracking and feature requests.
