### ISSUE TITLE
test_export_epochs_eeglab failing on main

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#11010]
test_export_epochs_eeglab is failing on windows 3.9 pip and windows 3.10 pip pre

https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=21054&view=logs&j=dded70eb-633c-5c42-e995-a7f8d1f99d91&t=6a33d698-56da-505a-4bdd-64e49791e9d1&l=3242

#11006 may be the culprit?  @cbrnr do you have time to look?

**Comment by cbrnr** [comment]
All tests passed in #11006, so I doubt that this is the culprit. But I'll take a look anyway.

**Comment by cbrnr** [comment]
I think it's related to a recent update in eeglabio, which will hopefully be fixed by #11000?
