### ISSUE TITLE
plot function get error? 

### ISSUE THREAD

**Issue by 1358467720** [mne-tools/mne-python#11026]
#### Describe the bug
Hi! I just load my data from edf file to plot it! It does not look like normal? Have  my data something wrong or the plot function is wrong ？
```
        
raw = mne.io.read_raw_edf(file_name)
        raw.resample(128)
        print(raw.info)
        raw.load_data()
        raw.filter(l_freq=1, h_freq=30) 
        raw.notch_filter(freqs=50)  


        raw.plot()
```
![issue](https://user-images.githubusercontent.com/48643755/184055937-a96251a1-e303-4389-b56c-04573780a002.png)

**Comment by cbrnr** [comment]
Can you open and view your file with [EDFbrowser](https://www.teuniz.net/edfbrowser/) to verify that it's not the data?

**Comment by 1358467720** [comment]
> Can you open and view your file with [EDFbrowser](https://www.teuniz.net/edfbrowser/) to verify that it's not the data?
emm.. It does not look good with EDFbrowser. Does it mean that my data have got something wrong ?

**Comment by 1358467720** [comment]
> Can you open and view your file with [EDFbrowser](https://www.teuniz.net/edfbrowser/) to verify that it's not the data?

emm.. It does not look good with EDFbrowser. Does it mean that my data have got something wrong ?

**Comment by cbrnr** [comment]
If it looks the same in EDFbrowser, then yes, something's wrong with your data and not with our import or plotting functions.
