### ISSUE TITLE
Simplify auto legend from evoked. comment in plot_compare_evokeds

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#11042]
I am thinking of simplifying the `nave` proportions algebra in `evoked. comment` for the results from `plot_compare_evokdes` to make a more informative legend. Here is an, e.g., output **screenshot**

<img width="1994" alt="Screen Shot 2022-08-02 at 5 09 25 PM" src="https://user-images.githubusercontent.com/4381290/182497475-4d3a64d1-7788-4f27-9db2-047cd4aa8ed1.png">

The text in `evoked.comment` renders unusable image file formats unless figure legends are dealt with on the fly. If that's the intended usage, then disregard this. Otherwise, I am curious if a fix is a suitable task to piggyback here?

Resulting `.png`
![compare-evokeds](https://user-images.githubusercontent.com/4381290/182498000-b9508dd4-c5e0-452b-883d-c6ad04541c87.png)

_Originally posted by @ktavabi in https://github.com/mne-tools/mne-python/issues/10467#issuecomment-1203342652_

**Comment by ktavabi** [comment]
My bandwidth is limited right now, if this isn't pressing, assign it to me, and I'll get it done.
