### ISSUE TITLE
"Temperature" and "Galvanic skin response" channel types

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#11055]
We just recently encountered BIDS data containing temperature and GSR/EDA channels, and it would be great if we could properly map those to MNE, instead of using the `'misc'` type.

Temperature is typically measured in °C (i.e., relative to 273.15 K) or in Kelvin.

GSR/EDA is, to my knowledge, typically measured as conductance and thus in the unit Siemens (the inverse of Ω).

BIDS spec:
https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html#channels-description-_channelstsv

Issue was discovered & discussed here:
https://github.com/mne-tools/mne-bids/issues/1046

MWE to retrieve & load a BIDS dataset with GSR & temperature channels:
```python
# %%

import openneuro
import mne_bids

bids_root = '/tmp/ds003061'

openneuro.download(
    dataset='ds003061',
    include=['sub-001'],
    target_dir= bids_root,
)
bp = mne_bids.BIDSPath(
    root= bids_root,
    subject='001',
    task='P300',
    run='1',
    datatype='eeg',
    suffix='eeg',
    extension='.set',
)
raw = mne_bids.read_raw_bids(bp)

for ch_name in raw.ch_names:
    ch_type = raw.get_channel_types(ch_name)[0]
    ch_idx = raw.ch_names.index(ch_name)
    print(f'{ch_idx:<5} {ch_name:<6} {ch_type}')
```

cc @agramfort

**Comment by agramfort** [comment]
+1 although I would stick to storing the values in SI units so S and Ohm

**Comment by hoechenberger** [comment]
> +1 although I would stick to storing the values in SI units so S and Ohm

I just updated my initial post and changed the units to S and Ohm to avoid confusion
