### ISSUE TITLE
Event functions are deprecated in Matplotlib 3.6

### ISSUE THREAD

**Issue by QuLogic** [mne-tools/mne-python#11062]
#### Describe the bug

Matplotlib 3.6 [deprecated the event functions on the canvas](https://matplotlib.org/devdocs/api/next_api_changes/deprecations/16931-AL.html). This causes some number of tests that use fake events to fail.

#### Steps to reproduce
1. Install `mne` dependencies
2. Update matplotlib to 3.6.0rc1
3. Run `pytest`

#### Expected results
Tests pass.

#### Actual results
[See build log against Matplotlib 3.6](https://download.copr.fedorainfracloud.org/results/qulogic/matplotlib-3.6.0:pr:8/fedora-rawhide-x86_64/04752284-python-mne/builder-live.log.gz)
```
______________________ test_plot_epochs_basic[matplotlib] ______________________
mne/viz/tests/test_epochs.py:62: in test_plot_epochs_basic
    fig._fake_keypress('escape')
mne/viz/_mpl_figure.py:1964: in _fake_keypress
    fig.canvas.key_press_event(key)
/usr/lib64/python3.11/site-packages/matplotlib/_api/deprecation.py:199: in wrapper
    emit_warning()
/usr/lib64/python3.11/site-packages/matplotlib/_api/deprecation.py:193: in emit_warning
    warn_deprecated(
/usr/lib64/python3.11/site-packages/matplotlib/_api/deprecation.py:96: in warn_deprecated
    warn_external(warning, category=MatplotlibDeprecationWarning)
/usr/lib64/python3.11/site-packages/matplotlib/_api/__init__.py:363: in warn_external
    warnings.warn(message, category, stacklevel)
E   matplotlib._api.deprecation.MatplotlibDeprecationWarning: The key_press_event function was deprecated in Matplotlib 3.6 and will be removed two minor releases later. Use callbacks.process('key_press_event', KeyEvent(...)) instead.
```
and similar for `button_press_event`, `resize_event`

#### Additional information
Sorry, don't have this in a non-interactive package build, but you can check the top of the above-linked file for installed dependencies.

**Comment by larsoner** [comment]
Also FYI we're updating for `.join` deprecation: https://github.com/matplotlib/matplotlib/pull/21584

Thanks for the heads up on these @QuLogic !
