### ISSUE TITLE
MAINT: Add category of discouraged but non-deprecated functions

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#11087]
Increasingly it seems like we are keeping old APIs available by keeping tiny wrappers around new, better APIs. To give an example from https://github.com/mne-tools/mne-python/pull/10184, `epochs.plot_psd_topomap(...)` is kept around to avoid breaking code, but we really want people to use `EpochsSpectrum` methods.

I propose we add a new `@deprecated`-like decorator that marks such code as... something. Maybe "legacy" is a good term? And instead of the `.. warning::` that `@deprecated` produces, it could be a `.. info::` or so that says something like:

> This function is provided to support legacy code. New code should use the more complete API provided by {0}

**Comment by drammock** [comment]
+1, I can add this
