### ISSUE TITLE
FIX: py3k testing environment is messed up

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1108]
Running py3k locally to investigate build issues in #1091 it turns out that things seem quite messy with the build environment.

The output is full of things like

```
ResourceWarning: unclosed file <_io.BufferedReader name='/Users/dengemann/python/mne-python/examples/MNE-sample-data/subjects/sample/bem/sample-oct-6-src.fif'>
```

Which seem to inflate the warnings buffers, which in turn is known to be a common source for warning related bugs, failures, issues ...

**Comment by Eric89GXL** [comment]
pretty sure I fixed this at some point
