### ISSUE TITLE
Wrong dB normalization for TFR plots

### ISSUE THREAD

**Issue by Martin2Constant** [mne-tools/mne-python#11091]
#### Bug description
When using the plot() method on an AverageTFR object with the dB argument set to True, the dB normalization applied is `20*log10(data)` instead of `10*log10(data)` (which is what is specified in the documentation). 
If I'm not mistaken, `20*log10(data)` dB normalization is for amplitude data, not power data. I spotted this problem with this function, but it probably applies to other functions where the dB argument can be specified.

I suppose the problem lies here: https://github.com/mne-tools/mne-python/blob/fb80e1163ef1f89479ca7f07cb0e09e996b23cd8/mne/time_frequency/tfr.py#L2464-L2465 from the recent commit https://github.com/mne-tools/mne-python/commit/4a1bf6bb7b5b1f384ac3b1bc21fc1a660cf6f3d2

**Comment by drammock** [comment]
I took a quick look, it appears that we need to keep track of whether data *was* complex so we can conditionally change the coef from `10` to `20` only in that case. @Martin2Constant are you up for making a PR to fix this?
