### ISSUE TITLE
DOC: add cookbook

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1109]
Something like:

http://pandas.pydata.org/pandas-docs/dev/cookbook.html

Listing common idioms, one liners, FAQ ...

**Comment by Eric89GXL** [comment]
From @dengemann:

"We should somewhere write down some of our local style preferences in some contrib file. - return self - single quotes - generator / list comprehension instead of filter et al - explicit functional constructors for builtin containers, dict() et al - avoid nested functions if not necessary"

**Comment by dengemann** [comment]
We should somewhere write down some of our local style preferences in some contrib file: 
- return self
- single quotes
- generator / list comprehension instead of filter et al
- explicit functional constructors for builtin containers, dict() et al
- avoid nested functions if not necessary and use private functions instead
- when addinv viz methods, add public functions to the mne.viz package and link them
- if not otherwise required, methods should deal with state while functions should return copies. Threre are a few justified excpetions though, e.g. equalize_channels, for memory reasons for example
- update whats_new at the end, otherwise merge conflicts are garuanteed to occur
- address one and only one issue per PR.
- avoid **kwargs and *args in function signatures, they are not user friendly (inspection)
- ...

**Comment by dengemann** [comment]
added some updates.

**Comment by Eric89GXL** [comment]
You got the above comment in your current PR @dengemann, and I added the residual "cookbook" idea to #1495
