### ISSUE TITLE
RuntimeError: No valid channel positions found

### ISSUE THREAD

**Issue by Aminur1981** [mne-tools/mne-python#11109]
Dear all,

I ran in a little problem here and could not figure out how to solve it.

after running:
raw.plot_sensors(ch_type='eeg');
I get the error message:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [30], in <cell line: 1>()
----> 1 raw.plot_sensors(ch_type='eeg')

File <decorator-gen-42>:12, in plot_sensors(self, kind, ch_type, title, show_names, ch_groups, to_sphere, axes, block, show, sphere, verbose)

File ~\Anaconda3\lib\site-packages\mne\channels\channels.py:499, in SetChannelsMixin.plot_sensors(self, kind, ch_type, title, show_names, ch_groups, to_sphere, axes, block, show, sphere, verbose)
    429 """Plot sensor positions.
    430 
    431 Parameters
   (...)
    496 .. versionadded:: 0.12.0
    497 """
    498 from ..viz.utils import plot_sensors
--> 499 return plot_sensors(self.info, kind=kind, ch_type=ch_type, title=title,
    500                     show_names=show_names, ch_groups=ch_groups,
    501                     to_sphere=to_sphere, axes=axes, block=block,
    502                     show=show, sphere=sphere, verbose=verbose)

File <decorator-gen-93>:12, in plot_sensors(info, kind, ch_type, title, show_names, ch_groups, to_sphere, axes, block, show, sphere, pointsize, linewidth, verbose)

File ~\Anaconda3\lib\site-packages\mne\viz\utils.py:966, in plot_sensors(info, kind, ch_type, title, show_names, ch_groups, to_sphere, axes, block, show, sphere, pointsize, linewidth, verbose)
    963     raise ValueError('Could not find any channels of type %s.' % ch_type)
    965 if not _check_ch_locs(info=info, picks=picks):
--> 966     raise RuntimeError('No valid channel positions found')
    968 dev_head_t = info['dev_head_t']
    969 chs = [info['chs'][pick] for pick in picks]

RuntimeError: No valid channel positions found

**Comment by agramfort** [comment]
This appears to be a question about usage, not a bug report or a new feature request. Please use the [MNE forum](https://mne.discourse.group/) for usage questions.
