### ISSUE TITLE
BUG: Example broken on main

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#11100]
@wmvanvliet I think #11080 broke `tutorials/clinical/30_ecog.py`:

https://app.circleci.com/pipelines/github/mne-tools/mne-python/16047/workflows/321560de-8d55-44f2-be22-e68382086eff/jobs/48440

Can you take a look?

**Comment by wmvanvliet** [comment]
Narrowed it down to MNE-BIDS trying to apply the montage, even though no fiducials are there yet. Before, the mri->head transform silently failed and channel positions were applied in MRI space (a situation we don't want). Then later in the example, this is fixed. I'll see if I can make MNE-BIDS be more clever about applying montages.
