### ISSUE TITLE
ValueError for set_log_level('WARN') in example

### ISSUE THREAD

**Issue by JuliusWelzel** [mne-tools/mne-python#11117]
https://github.com/mne-tools/mne-python/blob/fb80e1163ef1f89479ca7f07cb0e09e996b23cd8/mne/utils/_logging.py#L232

Example should read set_log_level('WARNING') instead of set_log_level('WARN')

**Comment by agramfort** [comment]
Indeed ! Can you send us a PR to fix it? 🙏

**Comment by JuliusWelzel** [comment]
Opened PR see #11118
