### ISSUE TITLE
[ENH] Use Sphinx-Gallery API Usage Map in Documentation

### ISSUE THREAD

**Issue by alexrockhill** [mne-tools/mne-python#11114]
Related to https://github.com/mne-tools/mne-python/pull/10999.

It would be nice to link the output in `doc/sg_api_usage.html` somewhere in the documentation, maybe near the roadmap. This might help new contributors find where the software is not heavily documented as far as example usage and fix that. Or even reduce build time and find redundant examples or how to refactor examples to show things more logically.

**Comment by larsoner** [comment]
To me this is a "developer option" and shouldn't be exposed / linked to in the docs. The right place for these in general I think is a contributor's page or something. I'd rather make a recommendation like this than add any option (or by default with no option) add these to the docs automatically
