### ISSUE TITLE
switch our DeprecationWarnings to FutureWarnings

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#11111]
Python silences DeprecationWarnings when running in user code. 

It is therefore recommended to use FutureWarnings if we want to ensure that users see the warnings by default. 

We could remove
`warnings.filterwarnings('always', category=DeprecationWarning, module='mne')` from `mne/utils/docs.py`  and change our Deprecation- to FutureWarnings

_Originally posted by @hoechenberger in https://github.com/mne-tools/mne-python/pull/11097#discussion_r956784748_

**Comment by hoechenberger** [comment]
hands down best issue number ever! 🎈
