### ISSUE TITLE
no digitization points found

### ISSUE THREAD

**Issue by Aminur1981** [mne-tools/mne-python#11110]
I am trying to plot topo map, it says no digitization points found. Here attached my channel location file. I need to know how read this channel location  file to solve the issue. Thank you.
[location.xlsx](https://github.com/mne-tools/mne-python/files/9443232/location.xlsx)

**Comment by agramfort** [comment]
@Aminur1981 This appears to be a question about usage, not a bug report or a new feature request. Please use the [MNE forum](https://mne.discourse.group/) for usage questions.
