### ISSUE TITLE
Add __eq__ and __ne__ to Projection

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-python#11137]
### Describe the new feature or enhancement

Add the `==` and `!=` method to the `Projection` class defined [here](https://github.com/mne-tools/mne-python/blob/aef49669fe1bdf19221e03e85cf961671508e0bb/mne/io/proj.py#L24-L103).

For now, comparing projectors raises:

```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by larsoner** [comment]
Sure, seems like an easy one when someone is motivated!
