### ISSUE TITLE
Release v1.2

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#11158]
Our milestone 1.2 is overdue, and we would like to cut a release this week or next. There are already a lot of open PRs and issues tagged with 1.2, but please mark any additional PRs/issues that you would like to see included in 1.2. Also, please remove the 1.2 milestone from any PRs/issues that won't make it into 1.2 and change their tag to 1.3.

**Comment by larsoner** [comment]
I went through and marked a ton of issues (50?) for 1.3, and marked issues+PRs I think we could get in this week or next if we make a push:

https://github.com/mne-tools/mne-python/milestone/23

So other folks when you look through, feel free to look through the 1.3 milestone to see what I pushed back (and/or look through the plain issues list for what you want to keep)

**Comment by larsoner** [comment]
In addition to https://github.com/mne-tools/mne-python/milestone/23 in prep for release we need to:

- [x] Wait for mne-realtime https://github.com/mne-tools/mne-realtime/pull/43 + release + feedstock update
- [ ] Wait for mne-connectivity https://github.com/mne-tools/mne-connectivity/pull/107 + release + feedstock update
- [ ] Wait for mne-nirs https://github.com/mne-tools/mne-nirs/pull/491 + release + feedstock update
- [ ] Build installers

**Comment by larsoner** [comment]
Okay I think now we're just waiting for mne-bids and autoreject releases so we can build installers. I'm building them with `dev` versions in https://github.com/mne-tools/mne-installers/pull/151 now just to get everything green. Hopefully we can release on Monday or Tuesday!

**Comment by drammock** [comment]
closed by #11236
