### ISSUE TITLE
Extend `mne.get_config("")` to return a dict

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#11164]
`mne.get_config("")` is mostly there for informational/interactive purposes, it's only used twice in the codebase in ways that should be compatible with `dict` too:

```console
$ git grep "get_config('')"
mne/utils/tests/test_config.py:24:    assert (len(get_config('')) > 10)  # tuple of valid keys
tutorials/intro/50_configure_mne.py:84:assert 'MNEE_USE_CUUDAA' not in mne.get_config('')
```

_Originally posted by @drammock in https://github.com/mne-tools/mne-python/issues/11159#issuecomment-1247095986_

Therefore, `mne.get_config("")` should return a `dict` with config values as keys and their descriptions as values (instead of a tuple of just config values without any descriptions).

**Comment by drammock** [comment]
I see no downside to always returning the `dict`
