### ISSUE TITLE
mne.source_space.add_source_space_distances not correctly populating some attributes

### ISSUE THREAD

**Issue by nugenta** [mne-tools/mne-python#11170]
### Description of the problem

There is a problem with the values added by mne.source_space.add_source_space_distances.  I've run this on the sample data, using the oct-6 forward model, which contains (for the left hemisphere) 155407 vertices in the dense mesh with 3732 vertices in the subsampled mesh. 

According to the documentation, the attribute 'patch_inds' should represent, "for each vertex in the subsampled surface, the indices of the vertices in the dense surface that it represents." It is supposed to be a list of arrays. However, after running mne.source_space.add_source_space_distances, src[0]['patch_inds'] is not a list of arrays, it is a single array with length 3732. The values in the array don't even correspond to the single nearest vertex in the dense space, because the values in the array only range from 13 - 4097.

Similarly, the documentation states that 'nearest' represents, "for each vertex on the dense surface, the vertex index on the subsampled surface that its closest to." So 'nearest' should be an array with length 155407, with values between 0 and 3731. While it is an array of length 155407, the values range from 59 to 153933. 

### Steps to reproduce

```Python
import mne
from mne.datasets import sample, fetch_fsaverage
import numpy as np
# Paths to example data
sample_dir_raw = sample.data_path()
sample_dir = sample_dir_raw / 'MEG' / 'sample'
subjects_dir = sample_dir_raw / 'subjects'
fname_stc = sample_dir / 'sample_audvis-meg'

# Read the raw data
raw = mne.io.read_raw_fif(raw_fname)
fwd_fname = meg_path / 'sample_audvis-meg-oct-6-fwd.fif'
forward = mne.read_forward_solution(fwd_fname)
mne.source_space.add_source_space_distances(src,dist_limit=0.01)

# the contents of patch_inds - a single array
src[0]['patch_inds']
# if patch_inds gives the corresponding vertex in the original dense mesh, these 
# numbers should go up to the total number of vertices in the dense mesh; 155407. 
# But they max out at 4097
np.max(src[0]['patch_inds'])

# the contents of nearest. This is supposed to be the nearest vertex on the 
# subsurface for every vertex on the dense surface. So these values should only
# go up to the number of vertices on the subsurface - 3732
np.max(src[0]['nearest']
```

### Expected results

The attribute 'patch_inds' should be a list of arrays (of length nuse), where each array contains the nearest vertices in the dense mesh - thus the range of values should be from 0 to np. 

The attribute 'nearest' should be an array with shape (np,) with values representing the nearest vertex in the subsampled mesh - thus the values should range from 0 to use

### Actual results

In [37]: np.shape(src[0]['patch_inds'])
Out [37]: (3732,)
In [38]: np.max(src[0]['patch_inds'])
Out [38]: 4097
In [39]: np.max(src[0]['nearest'])
Out [39]: 155330

### Additional information

Platform:         macOS-10.15.7-x86_64-i386-64bit
Python:           3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:03:09) [Clang 13.0.1 ]
Executable:       /Users/nugenta/opt/anaconda3/envs/mne2022/bin/python
CPU:              i386: 4 cores
Memory:           16.0 GB

mne:              1.1.0
numpy:            1.22.4 {blas=NO_ATLAS_INFO, lapack=lapack}
scipy:            1.9.0
matplotlib:       3.5.3 {backend=module://matplotlib_inline.backend_inline}

sklearn:          1.1.2
numba:            0.55.2
nibabel:          4.0.1
nilearn:          0.9.1
dipy:             1.5.0
cupy:             Not found
pandas:           1.4.3
pyvista:          0.36.1 {OpenGL 4.1 INTEL-14.7.28 via Intel(R) UHD Graphics 617}
pyvistaqt:        0.9.0
ipyvtklink:       0.2.2
vtk:

**Comment by larsoner** [comment]
@nugenta thanks for the clear bug report! Fortunately it's not the code that seems to be wrong but rather the docstring (that I wrote -- sorry about that!) -- can you see if #11171 makes more sense?
