### ISSUE TITLE
Deprecate mne.epochs.add_channels_epochs()

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#11172]
Working on #11168, I found that we have a function [`add_channels_epochs()`](https://mne.tools/stable/generated/mne.epochs.add_channels_epochs.html), which apparently only does a subset of what `Epochs.add_channels()` does, and is used nowhere in our code (it only appears in tests).

Since

- this function is redundant (one could use the method instead),
- it only exists for Epochs and we don't have anything similar for other data types,
- it is more limited than the method

I suggest deprecating it and marking it for removal.

Thoughts?

**Comment by drammock** [comment]
Based on your summary I'd say yes, but I haven't looked at the code yet. One other thing I usually check is the blame, to see how old the code is.

**Comment by hoechenberger** [comment]
> One other thing I usually check is the blame, to see how old the code is.

I did that and forgot to include it in my original posting: apparently hasn't been touched for 6–9 years :)

**Comment by larsoner** [comment]
Yes please, let's do this for 1.2. Let me know if you want to do it or I should @hoechenberger

**Comment by hoechenberger** [comment]
Please do go ahead @larsoner
