### ISSUE TITLE
ENH: Improve usability with scaled MRIs

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#11184]
I have some data for which a scaled infant MRI was used (but the same arguments go for scaling fsaverage for example). If I do a dipole fit, I get coordinates in the subject's head frame. Then `mri_pos = mne.head_to_mri(head_pos, trans)` gives me the MRI position in the *scaled* subject's MRI. **It would be nice to get it back in the original/surrogate subject's MRI frame** for example to use with `plot_dipole_locations`.

I see at least two potential ways:

1. New param with default `unscale=False` where if you pass `True`:
    ```
    mri_pos_orig = mne.head_to_mri(head_pos, subject, trans, unscale=True)
    ```
    It will look for the `mri scaling parameters.cfg` (or whatever it's called) for `subject` and apply the opposite transform to get it back to the original surrogate MRI's position (and raise an error if the `.cfg` is not found).
2. New function `mne.mri_to_unscaled_mri(mri_pos, subject)` so the use would be:
    ```
    mri_pos_orig = mne.mri_to_unscaled_mri(mne.head_to_mri(head_pos, subject, trans), subject)
    ```

I think I lean toward (1) since it is shorter, and a little bit less redundant / only need to specify `subject` once.

**Comment by agramfort** [comment]
option 1 works for me. 👍
