### ISSUE TITLE
read .egg file (UnicodeDecodeError)

### ISSUE THREAD

**Issue by RRaphaell** [mne-tools/mne-python#11195]
### Description of the problem

I'm trying to read .eeg file that I've recorded myself using brainvision. I'm using read_raw_nihon method but getting UnicodeDecodeError. I have also loaded header data (".vhdr") using  mne.io.read_raw_brainvision and annotation data (".vmrk") using mne.read_annotations successfully but was not able to read .eeg data as I have mentioned above.

### Steps to reproduce

```Python
I'm using kaggle
and here is the code

import mne
eeg = mne.io.read_raw_nihon("test.eeg")
```

### Link to data

https://drive.google.com/file/d/1IKyFTpQOIR06mWOo9wu4ih5sQnpUrld8/view?usp=sharing

### Expected results

read eeg data

### Actual results

UnicodeDecodeError: 'ascii' codec can't decode byte 0x86 in position 1: ordinal not in range(128)

### Additional information

Platform:         Linux-5.15.65+-x86_64-with-debian-bullseye-sid
Python:           3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53)  [GCC 9.4.0]
Executable:       /opt/conda/bin/python
CPU:              x86_64: 4 cores
Memory:           17.6 GB

mne:              1.1.1
numpy:            1.21.6 {blas=openblas, lapack=openblas}
scipy:            1.7.3
matplotlib:       3.5.3 {backend=module://matplotlib_inline.backend_inline}

sklearn:          1.0.2
numba:            0.55.2
nibabel:          4.0.2
nilearn:          0.9.2
dipy:             1.5.0
cupy:             Not found
pandas:           1.3.5
pyvista:          Not found
pyvistaqt:        Not found
ipyvtklink:       Not found
vtk:              9.1.0
qtpy:             2.1.0 {None=None}
ipympl:           0.7.0
pyqtgraph:        Not found
pooch:            v1.6.0

mne_bids:         Not found
mne_nirs:         Not found
mne_features:     Not found
mne_qt_browser:   Not found
mne_connectivity: Not found
mne_icalabel:     Not found

**Comment by drammock** [comment]
```py
raw = mne.io.read_raw_brainvision(vhdr_fname)
```
is the correct pattern.  If the `vhdr` file is structured correctly, it will have links inside it to the `vmrk` and the `eeg` files and you don't need to load them separately.

If you have further difficulty with this, please provide a link to the problematic files so we can check if maybe the files are corrupted.
