### ISSUE TITLE
Incorrect raw duration displayed in HTML repr

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#11202]
_Originally posted by @hoechenberger in https://github.com/mne-tools/mne-python/issues/11196#issuecomment-1257090412_

btw there's a bug in the HTML repr that is not present in the text repr:

<img width="492" alt="Screen Shot 2022-09-25 at 02 29 36" src="https://user-images.githubusercontent.com/2046265/192123297-c30445cf-061f-4a52-b497-0465ecd136d7.png">

```python
import numpy as np
import mne

n_seconds = 1
sfreq = 100
ch_names = ['1']
data = np.ones((len(ch_names), sfreq*n_seconds))
info = mne.create_info(ch_names=ch_names, sfreq=sfreq)
raw = mne.io.RawArray(data, info)
```

**Comment by cbrnr** [comment]
I think that's another argument for having just one repr. I don't like treating stuff separately for notebooks. At the very least, the HTML repr should take the normal repr and extend it when it makes sense, but duplicating what's already in the text repr is prone to such bugs.

**Comment by hoechenberger** [comment]
Yes but I think we've agreed that your point is valid many times before, no? It's just someone has to go ahead and start implementing it already.

**Comment by cbrnr** [comment]
I just wanted to make sure 😄.

**Comment by agramfort** [comment]
The floor is yours Clemens

**Comment by cbrnr** [comment]
Gotta find the time, but I will do it!
