### ISSUE TITLE
Problem with mne.io.read_epochs_eeglab 

### ISSUE THREAD

**Issue by cmphil13** [mne-tools/mne-python#11227]
*Sorry if I am doing this wrong, this is my first time posting on github!* 

I am running into an error when importing my data with read_epochs_eeglab. On line 150 of eeglab.py (within the function get_montage_information):

    for item in list(zip(*eeg.chaninfo['nodatchans'].values())):

I get the error: "TypeError: 'float' object is not iterable".

![image](https://user-images.githubusercontent.com/56241482/194353966-f1219d20-4154-446a-944d-27c363d6c93f.png)

 It looks like the format of the reference channel within the data file is incorrect somehow, but I am just directly importing the .set with read_epochs_eeglab so I am not sure where I could be making a mistake. eeg.chaninfo['nodatchans'] looks like: 

![image](https://user-images.githubusercontent.com/56241482/194354676-5b5502b8-7f42-4e3e-b233-707d9ccce88b.png)

Any help would be greatly appreciated!

**Comment by agramfort** [comment]
can you run eeg_checkset on your EEG structure in matlab and save it back
to check the reader in mne?

just to check if you changed manually something

Alex

**Comment by cmphil13** [comment]
Will do, thank you for the prompt response!

**Comment by INRING** [comment]
I also have the problem, do you solve it?

**Comment by drammock** [comment]
> I also have the problem, do you solve it?

@INRING please read [my previous response on this issue](https://github.com/mne-tools/mne-python/issues/11227#issuecomment-1270304591).  To get help with problems like this one:

1. use our forum, not our GitHub issue tracker
2. include a link to the problematic file
