### ISSUE TITLE
Mismatch of coord systems between electrodes and channels/events 

### ISSUE THREAD

**Issue by laemtl** [mne-tools/mne-python#11239]
### Description of the problem

Channel//Epoch data are exported in the ALS/CTF coord system to follow the EEGLAB specs.
On the other hand, electrode data are exported in the head/captrak coord space.

Is there any reason to not export the electrode data in the same space?

### Steps to reproduce

```Python
Exporting an EEGLAB dataset using
write_raw_bids(..., allow_preload=False, overwrite=False, verbose=False)
```

### Expected results

Electrode data in the CTF space

### Actual results

Electrode data in the Captrak space

### Additional information

Platform:         Windows-10-10.0.19041-SP0
Python:           3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
Executable:       C:\Users\Lae\Documents\hbcd-eeg2bids\Scripts\python.exe
CPU:              Intel64 Family 6 Model 142 Stepping 9, GenuineIntel: 4 cores
Memory:           Unavailable (requires "psutil" package)
mne:              1.2.0
numpy:            1.20.3 {OpenBLAS 0.3.13.dev with 4 threads}
scipy:            1.9.2
matplotlib:       3.6.1 {backend=TkAgg}

sklearn:          1.1.2
numba:            0.56.2
nibabel:          Not found
nilearn:          Not found
dipy:             Not found
openmeeg:         Not found
cupy:             Not found
pandas:           1.5.0
pyvista:          Not found
pyvistaqt:        Not found
ipyvtklink:       Not found
vtk:              Not found
qtpy:             Not found
ipympl:           Not found
pyqtgraph:        Not found
pooch:            v1.6.0

mne_bids:         0.10
mne_nirs:         Not found
mne_features:     0.2.1
mne_qt_browser:   Not found
mne_connectivity: Not found
mne_icalabel:     Not found

**Comment by agramfort** [comment]
this questions should be asked here
https://github.com/mne-tools/mne-bids/issues
it's an mne-bids question. Can you open the issue there and I will answer
there. ok?

thanks a lot
