### ISSUE TITLE
find_bads_muscle() can't find sensor positions

### ISSUE THREAD

**Issue by skjerns** [mne-tools/mne-python#11299]
### Description of the problem

When using the newly introduced `ica.find_bads_muscle` it seems like the function cannot find the sensor positions, even though they should be included in the file and/or be accessible to MNE generally by default.

```Python
ValueError: The following electrodes have overlapping positions, which causes problems during visualization: [... list of all 306 channels]
```

### Steps to reproduce

```Python
import os
import mne
from mne.preprocessing import ICA

sample_data_folder = mne.datasets.sample.data_path()
sample_data_raw_file = os.path.join(sample_data_folder, 'MEG', 'sample',
                                    'sample_audvis_raw.fif')
raw = mne.io.read_raw_fif(sample_data_raw_file,  preload=True)
raw.resample(100)
ica =ICA(40, method='picard')
ica.fit(raw)

ica.find_bads_muscle(raw)
```

### Expected results

MNE automatically finds the channel montage, as is done when plotting the sensor positions via `raw.plot_sensors("3d")`

But may I'm also not applying the function correct. In this case, please let me know.

### Actual results

```Python

  File "Ü:\analysis\untitled1.py", line 19, in <module>
    ica.find_bads_muscle(raw)

  File "<decorator-gen-571>", line 12, in find_bads_muscle

  File "Ü:\\anaconda3\lib\site-packages\mne\preprocessing\ica.py", line 1790, in find_bads_muscle
    pos = _find_topomap_coords(inst.info, picks='data', sphere=sphere)

  File "Ü:\anaconda3\lib\site-packages\mne\channels\layout.py", line 677, in _find_topomap_coords
    pos = _auto_topomap_coords(

  File "Ü:\anaconda3\lib\site-packages\mne\channels\layout.py", line 776, in _auto_topomap_coords
    raise ValueError('The following electrodes have overlapping positions,'

ValueError: The following electrodes have overlapping positions, which causes problems during visualization: [... list of all 306 channels]
```

### Additional information
```
Platform:         Windows-10-10.0.19043-SP0
Python:           3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
Executable:      Ü:\anaconda3\python.exe
CPU:              AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD: 24 cores
Memory:           31.9 GB

mne:              1.2.1
numpy:            1.23.3 {OpenBLAS 0.3.20 with 24 threads}
scipy:            1.9.2
matplotlib:       3.5.1 {backend=Qt5Agg}
```

**Comment by mscheltienne** [comment]
Hello, I could reproduce the issue and I've pushed a fix in #11300.

**Comment by skjerns** [comment]
Thanks for the fast fix!

However, I'm a bit surprised. Using your fix `ICA.find_bads_muscle` finds zero components in all of my files. My dataset of 30 participants with each 7 different recordings (rangin from 5-30 minutes), recorded with a MEGIN-Trilux with 306 sensors, no component gets marked as belonging to muscle artefacts. Is that to be expected (as MEG suffers less from muscle artefacts)?

**Comment by drammock** [comment]
if they're adults, they're reasonably good at sitting still, and you allowed them to move in between trials/blocks to make it easier to be still during the blocks, it doesn't seem that surprising to me.
