### ISSUE TITLE
Non-helping Error message for methods on empty epochs

### ISSUE THREAD

**Issue by marsipu** [mne-tools/mne-python#11305]
### Description of the problem

This is an issue I saw often with beginner users of mne-python:
When an `Epochs`-instance is created and for some reason all epochs are marked as bad (reject/flat-parameter, annotations), the following methods (among others) throw error messages, which are especially for beginners not really helpful:

- `average`
- `plot`
- `plot_image`
- `plot_psd`
- `plot_topo_image`

When epochs are manually dropped with `Epochs.drop_bad()` or when they are dropped when data is loaded, there is no warning message indicating that all available epochs have been dropped. The only part I found with a warning is when `Epochs.save()` is used on an empty Epochs-instance.

### Solution
I would suggest to warn when all epochs are about to be dropped and to capture the exceptions due to empty Epochs-instances inside the relevant methods with more expressive messages.

### Steps to reproduce

```Python
import os

import mne

sample_data_folder = mne.datasets.sample.data_path()
sample_data_raw_file = (sample_data_folder / 'MEG' / 'sample' /
                        'sample_audvis_raw.fif')
raw = mne.io.read_raw_fif(sample_data_raw_file, verbose=False)

sample_data_events_file = os.path.join(sample_data_folder,
                                       'MEG', 'sample',
                                       'sample_audvis_raw-eve.fif')
events = mne.read_events(sample_data_events_file)
epochs = mne.Epochs(raw, events, tmin=-0.3, tmax=0.7, reject={'eog': 1e-10},
                    reject_by_annotation=False)

# All epochs dropped, no warning message
epochs.drop_bad()

# ZeroDivisionError: float division by zero
epochs.average()

# ZeroDivisionError: float division by zero
epochs.plot()

# ValueError: zero-size array to reduction operation maximum which has no identity
epochs.plot_image()

# ValueError: zero-size array to reduction operation minimum which has no identity
epochs.plot_psd()

# ValueError: zero-size array to reduction operation maximum which has no identity
epochs.plot_topo_image()
```

### Expected results

More concisive warnings and error messages helping especially beginners with finding the problem.

### Actual results

`ZeroDivisionError: float division by zero`

`ValueError: zero-size array to reduction operation maximum which has no identity`

### Additional information

Platform:         Windows-10-10.0.22000-SP0
Python:           3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 06:57:19) [MSC v.1929 64 bit (AMD64)]
Executable:       \anaconda3\envs\mnedev\python.exe
CPU:              Intel64 Family 6 Model 158 Stepping 9, GenuineIntel: 8 cores
Memory:           15.9 GB
mne:              1.3.dev0
numpy:            1.22.4 {unknown linalg bindings}
scipy:            1.9.0
matplotlib:       3.5.2Backend QtAgg is interactive backend. Turning interactive mode on.
 {backend=QtAgg}
sklearn:          1.1.2
numba:            0.55.2
nibabel:          4.0.1
nilearn:          0.9.1
dipy:             1.5.0
openmeeg:         Not found
cupy:             Not found
pandas:           1.4.3
pyvista:          0.36.1 {OpenGL 4.4.0 - Build 21.20.16.4526 via Intel(R) HD Graphics 630}
pyvistaqt:        0.9.0
ipyvtklink:       0.2.2
vtk:              9.1.0
qtpy:             2.1.0 {PyQt5=5.15.4}
ipympl:           0.9.1
pyqtgraph:        0.12.4
pooch:            v1.6.0
mne_bids:         0.11.dev0
mne_nirs:         Not found
mne_features:     Not found
mne_qt_browser:   0.4.dev0
mne_connectivity: Not found
mne_icalabel:     Not found

**Comment by agramfort** [comment]
+1

PR welcome 🙏
