### ISSUE TITLE
info['subject_info']['birthday'] should support a datetime object

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#11327]
### Describe the new feature or enhancement

Working on https://mne.discourse.group/t/minor-priority-issue-with-converting-mne-raw-into-bids-with-mne-bids-age-birthday-info-of-subject/5922, I realized that a subject's birthday must be specified as a tuple of ints. I believe this is inconsistent with the way we allow to specify the measurement date (datetime object).

### Describe your proposed implementation

It should be possible to specify `Info['subject_info']['birthday']` as a `datetime.datetime` object. 

### Describe possible alternatives

–

**Comment by hoechenberger** [comment]
@larsoner Any opinion on that?

**Comment by larsoner** [comment]
Agreed this makes sense. We can gradually transform these tuple-of-two-int into `datetime` as we find them.
