### ISSUE TITLE
fontawesome icons not displaying correctly

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#11320]
https://mne.tools/dev/install/installers.html

<img width="669" alt="Screenshot 2022-11-12 at 16 01 25" src="https://user-images.githubusercontent.com/2046265/201480264-47d32a2a-2f70-4da3-b7de-91c29bec6340.png">

**Comment by larsoner** [comment]
Argh, it's broken on dev and stable. Maybe some pydata-sphinx-theme bug -- @drammock can you look?
