### ISSUE TITLE
Default arguments of `raw.plot_psd()` changed

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#11343]
### Description of the problem

It seems like the default arguments of `raw.plot_psd()` changed in MNE 1.2 (see example below).

### Steps to reproduce

```Python
import mne
from mne.datasets import sample

fname = sample.data_path() / "MEG" / "sample" / "sample_audvis_raw.fif"
raw = mne.io.read_raw(fname).pick_types(eeg=True).load_data()
raw.plot_psd(fmax=60)
```

### Expected results

Result from MNE < 1.2:

![raw-plot_psd-1 1](https://user-images.githubusercontent.com/4377312/204534595-54a35167-ba05-4365-8fcb-b5b582d689d6.png)

### Actual results

Result from MNE >= 1.2 (including `main`):

![raw-plot_psd-main](https://user-images.githubusercontent.com/4377312/204534677-6130f0bf-fb33-4e64-afcc-c8fd0eefabee.png)

### Additional information

Platform:         macOS-11.7.1-x86_64-i386-64bit
Python:           3.10.8 (main, Oct 13 2022, 10:18:28) [Clang 13.0.0 (clang-1300.0.29.30)]
Executable:       /Users/clemens/Projects/mne-python/.direnv/python-3.10.8/bin/python
CPU:              i386: 8 cores
Memory:           Unavailable (requires "psutil" package)
mne:              1.3.dev0
numpy:            1.23.5 {unknown linalg bindings (threadpoolctl module not found: No module named 'threadpoolctl')}
scipy:            1.9.3
matplotlib:       3.6.2 {backend=MacOSX}

**Comment by drammock** [comment]
on `main` I see `Effective window size : 0.426 (s)` and on 1.1 I see `Effective window size : 3.410 (s)`.  Should be fairly easy to track down, I'll work on it.

**Comment by cbrnr** [comment]
Unfortunately, this is still not fixed on `main` (the minimal example still reproduces the issue). Did something go wrong with merging #11345? @drammock do you have time to investigate?

**Comment by drammock** [comment]
> Unfortunately, this is still not fixed on `main` (the minimal example still reproduces the issue). Did something go wrong with merging #11345? @drammock do you have time to investigate?

@cbrnr Are you sure?  I just ran 

```console
git switch main
git fetch upstream
git merge upstream/main
```
followed by
```python
import mne
from mne.datasets import sample

fname = sample.data_path() / "MEG" / "sample" / "sample_audvis_raw.fif"
raw = mne.io.read_raw(fname).pick_types(eeg=True).load_data()
raw.plot_psd(fmax=60)
```

and I get this figure:

![Figure_1](https://user-images.githubusercontent.com/1810515/212194661-58ee3e86-d856-4666-aaf7-5499ec719d11.png)

**Comment by cbrnr** [comment]
That works, but

```python
raw.compute_psd(fmax=60).plot()
```

doesn't. Since the note explicitly recommends to switch to this new variant, I'd expect them to yield identical results.

**Comment by drammock** [comment]
OK, now I see the problem. Next time when you say 

> the minimal example still reproduces the issue

please check first. The code that is problematic for you is not in the minimal example at the top of this issue.

**Comment by cbrnr** [comment]
Sorry about that, I missed that line.
