### ISSUE TITLE
API: allow to choose / morph subject in source induced power

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1137]
currently there's no straight-forward support for the subject in minimum norm source induced power. I'm wondering whether there might be a way of morphing / transforming the inverse operator instead of the stc (which we don't get in this case). Any thoughts?

Also relevant for GSOC-topic-4

**Comment by larsoner** [comment]
In practice nowadays you can morph the labels to the subject rather than morph the activation to fsaverage. It should be faster (you only morph the labels once) and be functionally very similar, so I think we can close this
