### ISSUE TITLE
ENH/API: add cropping  / tmin-tmax paramters to time_frequency functions to avoid edge artifacts

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1138]
... like fieldtrip does.  Also related to GSOC-topic-4

**Comment by dlsrnsi** [comment]
@dengemann Is it finished? If not, can I take it?

**Comment by dengemann** [comment]
> Is it finished? If not, can I take it?

I thinkt this is not done yet. It should be consistently implmented for `tfr_*` functions.

**Comment by agramfort** [comment]
@dlsrnsi go for it !

**Comment by dlsrnsi** [comment]
@agramfort Thanks sir!
