### ISSUE TITLE
Missing API documentation for sample dataset's data_path() (and possibly others)

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#11396]
### Proposed documentation enhancement

To figure out what the parameters of `datasets.sample.data_path()` do, I had to dig into the source code. This is … not great, especially since we constantly ask users to provide MWEs based on `sample`. I assume this affects other datasets as well, but I only checked `sample`.

<img width="748" alt="Screenshot 2022-12-30 at 20 20 44" src="https://user-images.githubusercontent.com/2046265/210105340-1b5f43f9-3235-4365-9682-dc8934304015.png">

**Comment by drammock** [comment]
is this the old issue of "vscode doesn't render doccer-based docstrings"? Here's what I see in ipython, no source-code-digging required:

![data_path](https://user-images.githubusercontent.com/1810515/210108066-151e5f85-9491-47ce-b086-0e33c2736da2.png)

**Comment by hoechenberger** [comment]
It seems to be caused by this post-hoc injection of the docstring into the function:
https://github.com/mne-tools/mne-python/blob/e5086fcb20e891ef1c4ddc2ce2ae16047b496c5f/mne/datasets/sample/sample.py#L20-L21

And you're right, seems to be limited to Pylance.

**Comment by larsoner** [comment]
Closing as wontfix dup of #8863 #8218
