### ISSUE TITLE
 IndexError: index 0 is out of bounds for axis 0 with size 0 for plot_topomap based on only one channel

### ISSUE THREAD

**Issue by Farzaneh-Taleb** [mne-tools/mne-python#11428]
### Description of the problem

If the EpochsSpectrum array contains only one channel, we get this error for plot_topomap() method:
 IndexError: index 0 is out of bounds for axis 0 with size 0

### Steps to reproduce

```Python
epochs = epochs.pick_channels( ['Fz'])
  band= {'Delta (0-4 Hz)': (0, 4), 'Theta (4-8 Hz)': (4, 8),
     'Alpha (8-12 Hz)': (8, 12), 'Beta (12-30 Hz)': (12, 30),
     'Gamma (30-45 Hz)': (30, 45),
           'High Gamma (50-80 Hz)': (50, 80)

           }
fig= epochs_selected.compute_psd().plot_topomap(bands={band['Alpha (8-12 Hz)']},show=False)
```

### Expected results

..

### Actual results

..

### Additional information

..

**Comment by drammock** [comment]
you cannot plot a topomap based on only one channel. By definition a topomap is a spatially interpolated representation of the electromagnetic field on the scalp surface; you cannot interpolate between sensors if you only have one sensor.
