### ISSUE TITLE
Documentation for interpolations could be wrong

### ISSUE THREAD

**Issue by vladdez** [mne-tools/mne-python#11443]
### Proposed documentation enhancement

I am using the function mne.viz.plot_topomap(fake_evoked.data[:, 0], fake_evoked.info, axes=ax,
                     image_interp='linear', show=false)

I want to change the interpolator: image_interp argument. 

The documentation for version 1.3 says: image_interp[str](https://docs.python.org/3/library/stdtypes.html#str)
The image interpolation to use. The options are 'cubic' (default) to use [scipy.interpolate.CloughTocher2DInterpolator](https://scipy.github.io/devdocs/reference/generated/scipy.interpolate.CloughTocher2DInterpolator.html#scipy.interpolate.CloughTocher2DInterpolator), 'nearest' to use [scipy.spatial.Voronoi](https://scipy.github.io/devdocs/reference/generated/scipy.spatial.Voronoi.html#scipy.spatial.Voronoi) or 'linear' to use [scipy.interpolate.LinearNDInterpolator](https://scipy.github.io/devdocs/reference/generated/scipy.interpolate.LinearNDInterpolator.html#scipy.interpolate.LinearNDInterpolator).

However, when I write 'cubic' or 'linear' as an argument, I get this error: 
ValueError: 'cubic' is not a valid value for interpolation; supported values are 'antialiased', 'none', 'nearest', 'bilinear', 'bicubic', 'spline16', 'spline36', 'hanning', 'hamming', 'hermite', 'kaiser', 'quadric', 'catrom', 'gaussian', 'bessel', 'mitchell', 'sinc', 'lanczos', 'blackman'

So how can I use CloughTocher2DInterpolator interpolator?

**Comment by agramfort** [comment]
can you send us a PR to fix the doc?

thanks

**Comment by vladdez** [comment]
Hi! If you asked about link to the documentation it is here: https://mne.tools/stable/generated/mne.viz.plot_topomap.html

**Comment by mmagnuski** [comment]
Hi @vladdez, I think this is related to discussion we had here some time earlier about the distinction between 1) interpolating the channel data to get a topomap image (which is done in mne) and then 2) interpolating this image futher (in matplotlib) to get a nicer visual representation. I think there were two arguments for this some time ago, but now it seems there is only one - `image_interp`, which used to be controlling the second step, but the docs indicate it controls the first.

**Comment by vladdez** [comment]
Thanks for reply! So how then I can plot [CloughTocher2DInterpolator](https://scipy.github.io/devdocs/reference/generated/scipy.interpolate.CloughTocher2DInterpolator.html#scipy.interpolate.CloughTocher2DInterpolator)? Which argument should I choose for it?

**Comment by mmagnuski** [comment]
I think that at this point in time: #10617 it worked as described in the docs. But your error seems to imply that it no longer works this way. But `image_interp` worked differently on older mne versions, so could you please check the mne version you are using?

> So how then can I plot [CloughTocher2DInterpolator](https://scipy.github.io/devdocs/reference/generated/scipy.interpolate.CloughTocher2DInterpolator.html#scipy.interpolate.CloughTocher2DInterpolator)? Which argument should I choose for it?

That should be the default, so you don't have to change `image_interp` for it to work.

**Comment by mmagnuski** [comment]
I'm on mne 1.3.0 and image_interp works fine for me:
```python
import numpy as np
import mne

montage = mne.channels.make_standard_montage('biosemi64')
info = mne.create_info(ch_names=montage.ch_names, sfreq=500, ch_types='eeg')
info = info.set_montage(montage)

# %%
data = np.random.random(64)
mne.viz.plot_topomap(data, info, image_interp='nearest')
```
![obraz](https://user-images.githubusercontent.com/8452354/216340134-4b3b7aa7-32a2-41ef-822b-f6c10c33c3e9.png)

so I think you are using an older version of mne.

**Comment by vladdez** [comment]
Well, nearest works for me too, but cubic and linear are not working
![image](https://user-images.githubusercontent.com/33777074/216341461-4c9af5dc-3aab-4fbe-84d7-9030eec43be6.png)
![image](https://user-images.githubusercontent.com/33777074/216341563-87141471-78a0-4545-a9e4-99d3306ccb7e.png)

**Comment by mmagnuski** [comment]
Could you paste what `mne.sys_info()` shows?
Did you try running the example I pasted and get the error?

**Comment by mmagnuski** [comment]
Ah, you are on 1.0.3, could you update to current version then?

**Comment by vladdez** [comment]
Updated to 1.3.0. Error is gone.
Thank you!
