### ISSUE TITLE
Cannot view PRs in PyCharm (OAuth restrictions)

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#11462]
I'd like to set up PR integration in PyCharm, but this doesn't work because this repo seems to have OAuth restrictions enabled. Would it be possible to approve PyCharm (it's probably called "JetBrains IDE Integration") as described [here](https://docs.github.com/en/organizations/managing-oauth-access-to-your-organizations-data/approving-oauth-apps-for-your-organization)? I'm not sure how it works and if the request is already visible.

**Comment by agramfort** [comment]
not sure how to do this. It was setup to avoid having a developper blindly
giving access to the org private data.

Typically for me at work now I don't want to give access to these repos via
SSO.

**Comment by cbrnr** [comment]
Yes, the idea is to only allow access that maintainers explicitly grant, because blindly giving access is not a good idea. As to how it's done, it is described in the link in my top post. So if you agree that this app isn't harmful (it should list all permission it requests, probably just a bunch of read-only things) it would be great if you could enable it (so everyone using PyCharm can benefit).

**Comment by agramfort** [comment]
can you at least request it and we can approve?

I see only
 
<img width="1124" alt="Screenshot 2023-02-09 at 11 09 54" src="https://user-images.githubusercontent.com/161052/217782879-4647ac56-c012-4017-aa7c-d7a9faa6cefa.png">

**Comment by cbrnr** [comment]
I tried again – does it show up now?

**Comment by drammock** [comment]
request still does not show up :(

**Comment by cbrnr** [comment]
Thanks for checking. Then I guess something's wrong either with what I'm doing or with PyCharm, and I will try to find out.

**Comment by cbrnr** [comment]
I'm closing this because there is not really anything we can do I think.
