### ISSUE TITLE
mne.gui.locate_ieeg is great! (but I had a few issues)

### ISSUE THREAD

**Issue by mmagnuski** [mne-tools/mne-python#11484]
Sorry, the title of the issue is not very descriptive, but I tried the GUI lately to locate inracranial electrodes, and had some comments. But first of all I have to say it works great! Thanks @alexrockhill for this awesome contribution!

I had just a few minor issues that I wanted to raise:
* in my case, for some reason, freesurfer creates `surf\lh.pial.T1` and `surf\rh.pial.T2` which `mne.gui.locate_ieeg` couldn't find and throws error. When I renamed the files to what is expected by `mne.gui.locate_ieeg` - they were found. This is not specific to the iEEG GUI though - the same happens when trying to create `Brain`, so it might be a difference in how some freesurfer versions now operate? I'm using freesurfer 7.2.0 on Windows Subsystem for Linux (Ubuntu on wsl2) and  I'll paste the errors later as I am on a different computer now.
* I am not sure if "snap to center" works, and if it does how to verify that - I turned it on and off and didn't see a difference. Also it might be a tiny bit counterintuitive: when it says "off" on the push button it may also be interpreted that the option is on but pressing the button will turn it off (as the button says) - when I wasn't sure if it works or not this added to my confusion.
**UPDATE**: OK, I think I understand how "Snap to Center" works now, it does not affect cursor movement, but *only* mark placement.
* I tried pressing `'b'` on the keyboard to turn the brain on and off (as the help mentions) but it didn't do anything for me. Only pressing the GUI button turned brain mri on and off. I'll test other buttons soon and report.

I'll be happy to do more testing etc. :)

**Comment by mmagnuski** [comment]
Also with `verbose=False` I get lots of printed info like:
```
Clicked Z (2) axis at pos (89.74758620689654, 167.50617283950618)
Clicked X (0) axis at pos (165.58203490847166, 126.42592592592591)
Clicked Z (2) axis at pos (94.71310344827585, 164.98944231587905)
Clicked Y (1) axis at pos (98.94450840695353, 121.68518518518516)
Clicked X (0) axis at pos (164.12875266070662, 122.27777777777776)
Clicked Y (1) axis at pos (98.81227700199486, 121.68518518518516)
```

**Comment by drammock** [comment]
> Also with `verbose=False` I get lots of printed info like:

those should probably be `logger.debug` messages, only someone debugging would care about the clicked coordinates I think.

**Comment by alexrockhill** [comment]
I made a PR to fix the first issue in `Brain` but I didn't fix it for the `ieeg_locate` GUI. I can make a PR.

For the second one, yes it only effects the placement and when it says "On" it's on. If you want to make a PR to clarify the documentation for that in the tutorial, that would be great.

I can also fix the `b` shortcut and the logging now.

**Comment by alexrockhill** [comment]
Hmmm, I was not able to replicate the `b` keyboard shortcut not working. Perhaps you just needed to click on the window. It's also possible that the focus was on a widget that hadn't had it's keyboard event overridden. I think I fixed one or two of those here: https://github.com/mne-tools/mne-python/pull/11352 but it isn't merged yet.

**Comment by mmagnuski** [comment]
Thanks for quick fix @alexrockhill, I will try to replicate the keyboard shortcuts issue and maybe I'll come up with clarifications for snap to center.
