### ISSUE TITLE
Broken link in GSoC ideas

### ISSUE THREAD

**Issue by Dev-satish** [mne-tools/mne-python#11494]
### Proposed documentation enhancement

# Problem Area
- Broken link in [GSoC ideas page](https://github.com/mne-tools/mne-python/wiki/GSoC-Ideas#mne-python)
  - I discovered a broken link `https://mne.tools/dev/install/mne` for the **Installation instructions** on the [GSoC ideas page](https://github.com/mne-tools/mne-python/wiki/GSoC-Ideas) that needs to be updated with a properly functional one.

**Comment by mscheltienne** [comment]
Thank you for the report, since the wiki page can't be edited by everyone as the code can be through a pull request, I fixed it.

**Comment by Dev-satish** [comment]
> Thank you for the report, since the wiki page can't be edited by everyone as the code can be through a pull request, I fixed it.

Alright! Shall I close this issue then?

**Comment by mscheltienne** [comment]
Yes, you can :)

**Comment by larsoner** [comment]
Thanks for the report @Dev-satish and quick fix @mscheltienne !
