### ISSUE TITLE
Some times right click do not erase the annotations.

### ISSUE THREAD

**Issue by datsu28** [mne-tools/mne-python#11504]
### Description of the problem

I have a question regarding deleting interactive annotation during "raw.plot()".
When you try to delete the annotation,  a thin line remains...(orange annotation in this case)
I though it would be helpful if I can delete it easily using right click.

### Steps to reproduce

```Python
matplotlib.use('Qt5Agg')
fig=raw.plot(start=2,duration=15, highpass=.5, lowpass=40)
fig.fake_keypress("a")

open the eeg using this code and annotate some data and try to erase it.
```

### Expected results

the annotations are deleted(orange line disappears)

### Actual results

![Capture](https://user-images.githubusercontent.com/125303091/221031020-61132493-ed63-49ba-9827-9fb0f2918fe8.PNG)

### Additional information

Platform:         Windows-10-10.0.19045-SP0
Python:           3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
Executable:       [c:\Users\ADaida\Anaconda3\python.exe](file:///C:/Users/ADaida/Anaconda3/python.exe)
CPU:              Intel64 Family 6 Model 165 Stepping 5, GenuineIntel: 20 cores
Memory:           63.7 GB

mne:              1.3.0
numpy:            1.21.6 {OpenBLAS 0.3.17 with 20 threads}
scipy:            1.9.1
matplotlib:       3.5.2 {backend=Qt5Agg}

sklearn:          1.0.2
numba:            0.55.1
nibabel:          Not found
nilearn:          Not found
dipy:             Not found
openmeeg:         Not found
cupy:             Not found
pandas:           1.4.4
pyvista:          Not found
pyvistaqt:        Not found
ipyvtklink:       Not found
vtk:              Not found
qtpy:             2.2.0 {PyQt5=5.9.7}
ipympl:           Not found
pyqtgraph:        Not found
pooch:            [c:\Users\ADaida\Anaconda3\lib\site-packages\paramiko\transport.py:219](file:///C:/Users/ADaida/Anaconda3/lib/site-packages/paramiko/transport.py:219): CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
v1.6.0

mne_bids:         Not found
mne_nirs:         Not found
mne_features:     Not found
mne_qt_browser:   Not found
mne_connectivity: 0.5.0
mne_icalabel:     Not found

**Comment by cbrnr** [comment]
This issue has already been fixed in #11491.
