### ISSUE TITLE
raw.compute_psd().plot() output a blank figure with black background

### ISSUE THREAD

**Issue by impPie** [mne-tools/mne-python#11520]
### Description of the problem

raw.compute_psd().plot() output a blank figure with black background in my win10 computer.
But when I ran the same codes in google colab, it shows the correct figure.

### Steps to reproduce

```Python
psd=raw.compute_psd()
print(psd)
psd.plot()
```

### Expected results

![image](https://user-images.githubusercontent.com/116446314/222362704-53d8c40c-115e-425e-ab40-e0ece7427ab8.png)

### Actual results

![ca172691-f925-4949-a51e-7f5e0eafd9f2](https://user-images.githubusercontent.com/116446314/222362784-cf4d6925-1e26-44c9-91ad-80befcbe4c0e.png)

### Additional information

when I use the raw.plot(). It can show a proper result

**Comment by agramfort** [comment]
can you try psd.plot(color="white")?

it seems your machine has a dark background setup

**Comment by impPie** [comment]
![image](https://user-images.githubusercontent.com/116446314/223076120-3ece3809-a0ae-4e4b-99f7-61efa93869b5.png)

I tried but it still not work.

**Comment by impPie** [comment]
This was a vscode jupyter issue, just close the `Jupyter: Theme Matplotlib Plots
`  in VScode settings can fix it.

**Comment by drammock** [comment]
Thanks for reporting back the solution! I never would have found that since I didn't even know about that vscode setting 😅
