### ISSUE TITLE
Replace Flake8 with Ruff?

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#11534]
I recently discovered [Ruff](https://github.com/charliermarsh/ruff), a replacement for Flake8 written in Rust (but available on PyPI), which is 10x–100x faster. Do you think we can/should use it in our CI?

**Comment by agramfort** [comment]
have you tried to run it locally on mne? does it lead to many different errors than flake8?

**Comment by cbrnr** [comment]
I managed to provide our config, and now the errors are down to 13:

```
doc/conf.py:225:5: F601 [*] Dictionary key literal `'SourceMorph'` repeated
doc/conf.py:227:29: F601 [*] Dictionary key literal `'Forward'` repeated
mne/beamformer/tests/test_resolution_matrix.py:89:13: E741 Ambiguous variable name: `l`
mne/chpi.py:1217:28: E741 Ambiguous variable name: `l`
mne/io/base.py:579:34: E741 Ambiguous variable name: `l`
mne/viz/evoked.py:914:12: E713 [*] Test for membership should be `not in`
mne/viz/topo.py:661:12: E713 [*] Test for membership should be `not in`
tutorials/time-freq/10_spectrum_class.py:139:89: E501 Line too long (129 > 88 characters)
tutorials/time-freq/10_spectrum_class.py:141:89: E501 Line too long (129 > 88 characters)
tutorials/time-freq/10_spectrum_class.py:143:89: E501 Line too long (129 > 88 characters)
tutorials/time-freq/10_spectrum_class.py:145:89: E501 Line too long (129 > 88 characters)
tutorials/time-freq/10_spectrum_class.py:147:89: E501 Line too long (129 > 88 characters)
tutorials/time-freq/10_spectrum_class.py:149:89: E501 Line too long (129 > 88 characters)
Found 13 errors.
[*] 4 potentially fixable with the --fix option.
```

I still don't know how many rules that we use are not checked.

**Comment by agramfort** [comment]
ok it seems it's a doable transition. Feel free to give it a try in a PR

**Comment by larsoner** [comment]
> Is it possible to get a list of rules that Flake8 checks with our config?

Don't know offhand, IIRC somewhere in the flake8 docs it say what the defaults are

**Comment by drammock** [comment]
crossref to https://github.com/mne-tools/mne-bids-pipeline/issues/686 and https://github.com/mne-tools/mne-bids-pipeline/pull/688 in case it's helpful

**Comment by drammock** [comment]
I'm especially keen on adding Ruff as a pre-commit hook, so that style errors (once they're supported) are caught *before* pushing to the remote

**Comment by cbrnr** [comment]
Thanks for the crossrefs, I didn't know that you had already discussed this! I'm also a fan of precommit, and because we're already using black we don't even have to wait for Ruff to support style checks. Black, Ruff, and Codespell should be all we need, right?

**Comment by cbrnr** [comment]
See #11541.

**Comment by larsoner** [comment]
> I didn't know that you had already discussed this! I'm also a fan of precommit, and because we're already using black we don't even have to wait for Ruff to support style checks. Black, Ruff, and Codespell should be all we need, right?

Keep in mind those links are to mne-bids-pipeline where we have black+pre-commit IIRC. MNE-Python itself does not. We plan to go to black, but haven't done it yet: #10641

It would be good to use black for 1.4, maybe now is the time...

**Comment by cbrnr** [comment]
Yes, in #11541 only Codespell and Ruff are currently working, and I can only enable Black once someone has gone over the entire codebase.
