### ISSUE TITLE
Support `~` in config

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#11533]
It seems like we currently do not support `~` in our config, e.g.

```python
import mne

mne.set_config("MNE_DATA", "~/Data")
mne.datasets.sample.data_path()
```

raises a `FileNotFoundError: Download location ~/Data as specified by MNE_DATA does not exist. Either create this directory manually and try again, or set MNE_DATA to an existing directory.` (the directory exists).

Is there a reason why we would not want to expand the tilde? This would be useful to store MNE data in the same location within a user's home directory across operating systems.

**Comment by agramfort** [comment]
that's a bug. We should expand the ~

can you open a PR? thx
