### ISSUE TITLE
BUG: no sensor information after importing elp and hsp data

### ISSUE THREAD

**Issue by onelyn** [mne-tools/mne-python#11553]
Hello all! I'm looking for help with meg data preprocessing.

My raw data is .con file, and I have .mrk file (marker) and also .pos file (elp and hsp data).

If I read the data using `mne.io.read_raw_kit(data_raw_file)`, then there is correct sensor information. But as the headshape is not digitized, the following analysis can not be applied.

However, if I read the data using `mne.io.read_raw_kit(data_raw_file, mrk=marker_data, elp=elp_data, hsp=hsp_data)`, then there will be no sensor information. And I can plot only one dot when calling `raw.plot_sensors()`.

I'm wondering what's wrong with this process. Why there's a lack of sensor information if I import elp and hsp data? 

I'd appreciate it if anyone could help. Thanks a lot!

![image](https://user-images.githubusercontent.com/64457213/225012770-3de69a44-6bb8-4c52-9508-0a726005d042.png)
![image](https://user-images.githubusercontent.com/64457213/225012904-afddd6af-0e00-4ffb-9574-e4a01a523e61.png)

**Comment by onelyn** [comment]
And here are the marker, elp, and hsp data. They are all in array format. The marker is (5,3) array. The elp is (8,3) array. The hsp is (4299,3) array. 

![image](https://user-images.githubusercontent.com/64457213/225013405-5258cf6a-82d2-4f64-8107-9540c5fc5ed7.png)

**Comment by drammock** [comment]
> If `mrk`, `hsp` or `elp` are :term:`array_like` inputs, then the
> numbers in xyz coordinates should be in units of meters.

Exactly right. In fact, the plot that shows "one dot" actually shows all the sensors very tightly clustered together, I think, because HSP and ELP were given in mm but MNE treats it as m so the head outline is 1000 times too big
