### ISSUE TITLE
Remove `jinja2` from core dependencies?

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#11559]
Currently, we require `jinja2` even though it is imported in only one location (`mne/html_templates/_templates.py`). Although this is a lightweight package (it only depends on `MarkupSafe`), I'd argue that it should not be a core requirement.

**Comment by larsoner** [comment]
AFAIK It's lightweight, pure python, well supported, and hasn't caused us any maintenance issues in the years we've had it as a core dependency. So I don't see much gain to making it optional. I do see some drawbacks, like I think Report week no longer just work, as well as possibly some `_repr_html_`, and we need to protect imports and add more test decorators. So overall -1 on making optional.

I'd rather gradually go on the opposite direction, e.g., add things like nibabel that also fit the above description/ attributes. It'll simplify our codebase not to have to nest the import.

> Also, does [our test to detect nested imports](https://github.com/cbrnr/mne-python/blob/8b9baebdf1bb9d476e949262e594250132ef2189/mne/tests/test_import_nesting.py#L30) need to be updated?

No I don't think so. That mostly has to do two things 1) check that only required dependencies are imported and 2) that slow parts of required ones are not imported. I don't think importing jinja2 takes long so no need to nest it

**Comment by larsoner** [comment]
> why would we test that its import is nested (even though it's not imported with import mne)?

We must nest it to help ensure that `import mne` stays fast.

Okay to close?

**Comment by cbrnr** [comment]
OK. Then I'll add a bit of an explanation to this test.

**Comment by larsoner** [comment]
(I think the import nesting is effectively achieved one level higher, when the templates themselves are loaded to be used)

**Comment by cbrnr** [comment]
It's still hard to understand which packages we are allowed to import directly (and which ones not), and how all of this is related to our core and optional dependencies.

**Comment by cbrnr** [comment]
If you have time, can you clarify this in the docstring of the test? I have too many questions about this to do it myself, but I think it would be helpful for (future) developers.
