### ISSUE TITLE
Unable to use RawEDF normally

### ISSUE THREAD

**Issue by myh1041893567** [mne-tools/mne-python#11552]
### Description of the problem

During the model experiment, the first prompt is that the channel read from the edf file is different from the setting. This query found that a RawEDF cannot be used normally. The data file can be opened with the EDFbrowser file.
2023-03-14 11:26:59,598 INFO : 29 files in total.
2023-03-14 11:26:59,598 INFO : Read recording lengths...
2023-03-14 11:26:59,616 INFO : Load 1 of 29
2023-03-14 11:26:59,848 INFO : Load data...
Reading 0 ... 301249  =      0.000 ...  1204.996 secs...
Traceback (most recent call last):
  File "E:\EEG\eeg1\auto-eeg-diagnosis-example-master\auto_diagnosis.py", line 348, in <module>
    exp = run_exp(
  File "E:\EEG\eeg1\auto-eeg-diagnosis-example-master\auto_diagnosis.py", line 168, in run_exp
    X,y = dataset.load()
  File "E:\EEG\eeg1\auto-eeg-diagnosis-example-master\dataset.py", line 201, in load
    x = load_data(fname, preproc_functions=self.preproc_functions,
  File "E:\EEG\eeg1\auto-eeg-diagnosis-example-master\dataset.py", line 126, in load_data
    assert np.array_equal(cnt.ch_names, selected_ch_names)
AssertionError

Unable to get repr for <class 'mne.io.edf.edf.RawEDF'>
'RawEDF' object has no attribute '_annotations'
'RawEDF' object has no attribute 'info'

### Steps to reproduce

```Python
Recurrence model link：https://github.com/robintibor/auto-eeg-diagnosis-example
```

### Link to data

https://isip.piconepress.com/projects/tuh_eeg/html/downloads.shtml

### Expected results

You want to get the response

### Actual results

D:\Anaconda\python.exe E:/EEG/eeg1/auto-eeg-diagnosis-example-master/auto_diagnosis.py
2023-03-14 11:26:59,580 INFO : Read file names
2023-03-14 11:26:59,580 INFO : Reading E:\EEG\file\text\edf\train\...
2023-03-14 11:26:59,598 INFO : .. 29 files.
2023-03-14 11:26:59,598 INFO : 29 files in total.
2023-03-14 11:26:59,598 INFO : Read recording lengths...
2023-03-14 11:26:59,616 INFO : Load 1 of 29
2023-03-14 11:26:59,848 INFO : Load data...
Reading 0 ... 301249  =      0.000 ...  1204.996 secs...
Traceback (most recent call last):
  File "E:\EEG\eeg1\auto-eeg-diagnosis-example-master\auto_diagnosis.py", line 348, in <module>
    exp = run_exp(
  File "E:\EEG\eeg1\auto-eeg-diagnosis-example-master\auto_diagnosis.py", line 168, in run_exp
    X,y = dataset.load()
  File "E:\EEG\eeg1\auto-eeg-diagnosis-example-master\dataset.py", line 201, in load
    x = load_data(fname, preproc_functions=self.preproc_functions,
  File "E:\EEG\eeg1\auto-eeg-diagnosis-example-master\dataset.py", line 126, in load_data
    assert np.array_equal(cnt.ch_names, selected_ch_names)
AssertionError

### Additional information

<details>
Microsoft Windows [版本 10.0.22000.1574]
Python 3.9.12
AMD Ryzen 7 5800H with Radeon Graphics

Package                       Version
----------------------------- --------------------
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
anaconda-client               1.9.0
anaconda-navigator            2.4.0
anaconda-project              0.10.2
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.2
astroid                       2.6.6
astropy                       5.0.4
asttokens                     2.0.5
async-timeout                 4.0.1
atomicwrites                  1.4.0
attrs                         21.4.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
beautifulsoup4                4.11.1
binaryornot                   0.4.4
bitarray                      2.4.1
bkcharts                      0.2
black                         19.10b0
bleach                        4.1.0
bokeh                         2.4.2
boto3                         1.21.32
botocore                      1.24.32
Bottleneck                    1.3.4
Braindecode                   0.6
brotlipy                      0.7.0
cachetools                    4.2.2
certifi                       2022.12.7
cffi                          1.15.0
chardet                       4.0.0
charset-normalizer            2.0.4
click                         8.0.4
cloudpickle                   2.0.0
clyent                        1.2.2
colorama                      0.4.4
colorcet                      2.0.6
comtypes                      1.1.10
conda                         23.1.0
conda-build                   3.21.8
conda-content-trust           0+unknown
conda-pack                    0.6.0
conda-package-handling        1.8.1
conda-repo-cli                1.0.4
conda-token                   0.3.0
conda-verify                  3.4.2
constantly                    15.1.0
cookiecutter                  1.7.3
coverage                      5.5
cryptography                  3.4.8
cssselect                     1.1.0
cycler                        0.11.0
Cython                        0.29.28
cytoolz                       0.11.0
daal4py                       2021.5.0
dask                          2022.2.1
datashader                    0.13.0
datashape                     0.5.4
debugpy                       1.5.1
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20200713
distributed                   2022.2.1
docutils                      0.17.1
entrypoints                   0.4
et-xmlfile                    1.1.0
executing                     0.8.3
fastjsonschema                2.15.1
filelock                      3.6.0
flake8                        3.9.2
Flask                         1.1.2
fonttools                     4.25.0
frozenlist                    1.2.0
fsspec                        2022.2.0
future                        0.18.2
gensim                        4.1.2
glob2                         0.7
google-api-core               1.25.1
google-auth                   1.33.0
google-cloud-core             1.7.1
google-cloud-storage          1.31.0
google-crc32c                 1.1.2
google-resumable-media        1.3.1
googleapis-common-protos      1.53.0
greenlet                      1.1.1
grpcio                        1.42.0
h5py                          3.6.0
HeapDict                      1.0.1
holoviews                     1.14.8
huggingface-hub               0.10.1
hvplot                        0.7.3
hyperlink                     21.0.0
idna                          3.3
imagecodecs                   2021.8.26
imageio                       2.9.0
imagesize                     1.3.0
imbalanced-learn              0.10.1
importlib-metadata            4.11.3
incremental                   21.3.0
inflection                    0.5.1
iniconfig                     1.1.1
intake                        0.6.5
intervaltree                  3.1.0
ipykernel                     6.9.1
ipython                       8.2.0
ipython-genutils              0.2.0
ipywidgets                    7.6.5
isort                         5.9.3
itemadapter                   0.3.0
itemloaders                   1.0.4
itsdangerous                  2.0.1
jdcal                         1.4.1
jedi                          0.18.1
Jinja2                        2.11.3
jinja2-time                   0.2.0
jmespath                      0.10.0
joblib                        1.1.0
json5                         0.9.6
jsonschema                    4.4.0
jupyter                       1.0.0
jupyter-client                6.1.12
jupyter-console               6.4.0
jupyter-core                  4.9.2
jupyter-server                1.13.5
jupyterlab                    3.3.2
jupyterlab-pygments           0.1.2
jupyterlab-server             2.10.3
jupyterlab-widgets            1.0.0
keyring                       23.4.0
kiwisolver                    1.3.2
lazy-object-proxy             1.6.0
libarchive-c                  2.9
llvmlite                      0.38.0
locket                        0.2.1
lxml                          4.8.0
Markdown                      3.3.4
MarkupSafe                    2.0.1
matplotlib                    3.5.1
matplotlib-inline             0.1.2
mccabe                        0.6.1
menuinst                      1.4.18
mistune                       0.8.4
mkl-fft                       1.3.1
mkl-random                    1.2.2
mkl-service                   2.4.0
mne                           1.3.1
moabb                         0.4.6
mock                          4.0.3
mpmath                        1.2.1
msgpack                       1.0.2
multidict                     5.1.0
multipledispatch              0.6.0
munkres                       1.1.4
mypy-extensions               0.4.3
navigator-updater             0.2.1
nbclassic                     0.3.5
nbclient                      0.5.13
nbconvert                     6.4.4
nbformat                      5.3.0
nest-asyncio                  1.5.5
networkx                      2.7.1
nltk                          3.7
nose                          1.3.7
notebook                      6.4.8
numba                         0.55.1
numexpr                       2.8.1
numpy                         1.21.5
numpydoc                      1.2
olefile                       0.46
openpyxl                      3.0.9
packaging                     21.3
pandas                        1.4.2
pandocfilters                 1.5.0
panel                         0.13.0
param                         1.12.0
paramiko                      2.8.1
parsel                        1.6.0
parso                         0.8.3
partd                         1.2.0
pathspec                      0.7.0
patsy                         0.5.2
pep8                          1.7.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.0.1
pip                           21.2.4
pkginfo                       1.8.2
plotly                        5.6.0
pluggy                        1.0.0
pooch                         1.6.0
poyo                          0.5.0
prometheus-client             0.13.1
prompt-toolkit                3.0.20
Protego                       0.1.16
protobuf                      3.19.1
psutil                        5.8.0
ptyprocess                    0.7.0
pure-eval                     0.2.2
py                            1.11.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycodestyle                   2.7.0
pycosat                       0.6.3
pycparser                     2.21
pyct                          0.4.6
pycurl                        7.44.1
PyDispatcher                  2.0.5
pydocstyle                    6.1.1
pyerfa                        2.0.0
pyflakes                      2.3.1
Pygments                      2.11.2
PyHamcrest                    2.0.2
PyJWT                         2.1.0
pylint                        2.9.6
pyls-spyder                   0.4.0
PyNaCl                        1.4.0
pyodbc                        4.0.32
pyOpenSSL                     21.0.0
pyparsing                     3.0.4
pyreadline                    2.1
pyriemann                     0.2.7
pyrsistent                    0.18.0
PySocks                       1.7.1
pytest                        7.1.1
python-dateutil               2.8.2
python-lsp-black              1.0.0
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.2.4
python-slugify                5.0.2
python-snappy                 0.6.0
pytz                          2021.3
pyviz-comms                   2.0.2
PyWavelets                    1.3.0
pywin32                       302
pywin32-ctypes                0.2.0
pywinpty                      2.0.2
PyYAML                        6.0
pyzmq                         22.3.0
QDarkStyle                    3.0.2
qstylizer                     0.1.10
QtAwesome                     1.0.3
qtconsole                     5.3.0
QtPy                          2.0.1
queuelib                      1.5.0
regex                         2022.3.15
requests                      2.27.1
requests-file                 1.5.1
rope                          0.22.0
rsa                           4.7.2
Rtree                         0.9.7
ruamel.yaml                   0.17.21
ruamel.yaml.clib              0.2.6
ruamel-yaml-conda             0.15.100
s3transfer                    0.5.0
scikit-image                  0.19.2
scikit-learn                  1.0.2
scikit-learn-intelex          2021.20220215.102710
scipy                         1.7.3
Scrapy                        2.6.1
seaborn                       0.11.2
Send2Trash                    1.8.0
service-identity              18.1.0
setuptools                    61.2.0
sip                           4.19.13
six                           1.16.0
skorch                        0.11.0
smart-open                    5.1.0
sniffio                       1.2.0
snowballstemmer               2.2.0
sortedcollections             2.1.0
sortedcontainers              2.4.0
soupsieve                     2.3.1
Sphinx                        4.4.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.1.5
spyder-kernels                2.1.3
SQLAlchemy                    1.4.32
stack-data                    0.2.0
statsmodels                   0.13.2
sympy                         1.10.1
tables                        3.6.1
tabulate                      0.8.9
TBB                           0.2
tblib                         1.7.0
tenacity                      8.0.1
terminado                     0.13.1
testpath                      0.5.0
text-unidecode                1.3
textdistance                  4.2.1
threadpoolctl                 2.2.0
three-merge                   0.1.1
tifffile                      2021.7.2
tinycss                       0.4
tldextract                    3.2.0
tokenizers                    0.11.4
toml                          0.10.2
tomli                         1.2.2
toolz                         0.11.2
torch                         1.8.0+cu101
torchvision                   0.9.0+cu101
tornado                       6.1
tqdm                          4.64.0
traitlets                     5.1.1
transformers                  4.24.0
Twisted                       22.2.0
twisted-iocpsupport           1.0.2
typed-ast                     1.4.3
typing_extensions             4.1.1
ujson                         5.1.0
Unidecode                     1.2.0
urllib3                       1.26.9
w3lib                         1.21.0
watchdog                      2.1.6
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              0.58.0
Werkzeug                      2.0.3
wheel                         0.37.1
widgetsnbextension            3.5.2
win-inet-pton                 1.1.0
win-unicode-console           0.5
wincertstore                  0.2
wrapt                         1.12.1
xarray                        0.20.1
xlrd                          2.0.1
XlsxWriter                    3.0.3
xlwings                       0.24.9
yapf                          0.31.0
yarl                          1.6.3
zict                          2.0.0
zipp                          3.7.0
zope.interface                5.4.0
</details>

**Comment by cbrnr** [comment]
Can you please post code which shows the problem using MNE functions only? I.e. `raw = mne.io.read_raw_edf("which-file-name.edf")`.

**Comment by myh1041893567** [comment]
> 您能否发布仅使用MNE函数显示问题的代码？即.`raw = mne.io.read_raw_edf("which-file-name.edf")`
![1678786631621](https://user-images.githubusercontent.com/49837682/224959302-fd7cd4d5-c520-4b54-a13d-8c7edb63b607.png)
Thank you very much for your timely response
import mne

# 加载EDF文件
raw = mne.io.read_raw_edf("E:\\EEG\\file\\text\\edf\\train\\abnormal\\000\\00000077\\s003_2010_01_21\\00000077_s003_t000.edf")

# 打印一些数据信息
print(raw.info)

Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.2.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 8.2.0
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)] on win32
runfile('E:/EEG/eeg1/auto-eeg-diagnosis-example-master/texi1.py', wdir='E:/EEG/eeg1/auto-eeg-diagnosis-example-master')
Extracting EDF parameters from E:\EEG\file\text\edf\train\abnormal\000\00000077\s003_2010_01_21\00000077_s003_t000.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
<Info | 7 non-empty values
 bads: []
 ch_names: EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-REF, EEG C3-REF, ...
 chs: 36 EEG
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 125.0 Hz
 meas_date: 2010-01-21 13:58:36 UTC
 nchan: 36
 projs: []
 sfreq: 250.0 Hz
>

**Comment by cbrnr** [comment]
Can you also share the data file you are using in your example?

**Comment by myh1041893567** [comment]
> 您还可以共享您在示例中使用的数据文件吗？
Sorry, I just went out. You can turn to this link
https://isip.piconepress.com/projects/tuh_eeg/downloads/tuh_eeg/v2.0.0/edf/000/aaaaaaaa/s001_2015_12_30/01_tcp_ar/

**Comment by cbrnr** [comment]
It asks me for a username and password.

**Comment by myh1041893567** [comment]
> It asks me for a username and password.
Sorry, could you provide me with an email? My email is sent to you

**Comment by cbrnr** [comment]
The license agreement explicitly states that "The data recipient will not release data to a third party. Please have the third party contact us directly by sending an email to help@nedcdata.org". So unless you are knowingly going to violate that agreement, I guess we have to find a different way to solve this issue.

**Comment by myh1041893567** [comment]
> The license agreement explicitly states that "The data recipient will not release data to a third party. Please have the third party contact us directly by sending an email to [help@nedcdata.org](mailto:help@nedcdata.org)". So unless you are knowingly going to violate that agreement, I guess we have to find a different way to solve this issue.

Thank you for your reply and help. If you have any need, please register. It's very simple. Thank you very much

**Comment by myh1041893567** [comment]
> > 感谢您的回复和帮助。如果您有任何需要，请注册。这很简单。谢谢
> 
> 我真的不想用我的签名向他们发送此表单，也不想注册他们的邮件列表服务器（自动发生）。我不知道任何其他解决方案，也许可以编写它们并解释您需要私下共
[data.docx](https://github.com/mne-tools/mne-python/files/10980948/data.docx)
享一个数据集，以便我们可以调试问题？

[data.docx](https://github.com/mne-tools/mne-python/files/10980947/data.docx)
Do you think you can use this?

**Comment by myh1041893567** [comment]
> 对不起，这不起作用。

I put an edf file in this document

**Comment by cbrnr** [comment]
Yes, I can see it, but I don't know how to save/export it.

**Comment by myh1041893567** [comment]
> Yes, I can see it, but I don't know how to save/export it.

After downloading the document, can't the EDF file in it be pulled out?

**Comment by cbrnr** [comment]
> After downloading the document, can't the EDF file in it be pulled out?

No, it doesn't work for me (maybe because I have a Mac).

**Comment by myh1041893567** [comment]
> > 下载文档后，里面的EDF文件不能拉出来吗？
> 
> 不，它对我不起作用（也许是因为我有一台 Mac）。

How do you usually upload a small number of edf files

**Comment by cbrnr** [comment]
Can you share a Google Drive (or OneDrive, DropBox) link?

**Comment by myh1041893567** [comment]
Recurrence model：https://github.com/robintibor/auto-eeg-diagnosis-example

**Comment by myh1041893567** [comment]
> 好的，我可以读取文件：
> 
> ```python
> raw = mne.io.read_raw_edf("/Users/clemens/Downloads/00000077_s003_t000.edf", preload=True)
> ```
> 
> 问题出在哪里？
"I am reproducing a simple model that always prompts me to select channels. The channels read from the edf file are inconsistent, and RawEDF cannot be used during debugging."

**Comment by cbrnr** [comment]
Can you post code that lets me reproduce this issue? What are the values of `cnt.ch_names` and `selected_ch_names` in your example?

**Comment by drammock** [comment]
> ![1678977371261](https://user-images.githubusercontent.com/49837682/225651379-4aa82157-aa26-4df5-b62e-1288d994f25b.png)

this entire traceback is within the `auto-eeg-diagnosis-example` namespace. None of the error is coming from within MNE-Python nor does it involve MNE functions or methods. After a quick look at that repo, I suspect (but I'm not sure) that there's a difference between how your channels are named, and the channel names that they hardcode here:

https://github.com/robintibor/auto-eeg-diagnosis-example/blob/9c9b130a3bc724fb74133cff8ce834a9972ba56a/dataset.py#L105-L107

If you want additional support I suggest you reach out to the authors of that repo.

**Comment by myh1041893567** [comment]
> 
Thank you very much for your answer, and I will try to contact the repository author

**Comment by myh1041893567** [comment]
> > ![1678977371261](https://user-images.githubusercontent.com/49837682/225651379-4aa82157-aa26-4df5-b62e-1288d994f25b.png)
> 
> 整个回溯都在命名空间内。这些错误都不是来自MNE-Python内部，也不涉及MNE函数或方法。快速浏览该存储库后，我怀疑（但我不确定）您的频道的命名方式与他们在此处硬编码的频道名称之间存在差异：`auto-eeg-diagnosis-example`
> 
> https://github.com/robintibor/auto-eeg-diagnosis-example/blob/9c9b130a3bc724fb74133cff8ce834a9972ba56a/dataset.py#L105-L107
> 
> 如果您需要其他支持，我建议您联系该存储库的作者。
However, a prompt indicating that the method is not available appears during debugging
![224959302-fd7cd4d5-c520-4b54-a13d-8c7edb63b607](https://user-images.githubusercontent.com/49837682/225792204-40f67e81-d8f0-47c7-b09f-a0cfdc12e5b7.png)

**Comment by myh1041893567** [comment]
> 你能发布让我重现这个问题的代码吗？在您的示例中，和的值是什么？`cnt.ch_names``selected_ch_names`
https://github.com/robintibor/auto-eeg-diagnosis-example/tree/9c9b130a3bc724fb74133cff8ce834a9972ba56a
This is the case with the code because the RawEDF method is unavailable. I did not find the channel name extracted from the data file during debugging, but the channel names extracted separately are consistent. My only change is this
![2](https://user-images.githubusercontent.com/49837682/225793394-ba8b0234-b36a-44d1-af56-c4aee5f63d1b.png)

**Comment by drammock** [comment]
As I said before, the traceback occurs entirely within the `auto-eeg-diagnosis-example` namespace. More concretely, the traceback starts here:

https://github.com/robintibor/auto-eeg-diagnosis-example/blob/9c9b130a3bc724fb74133cff8ce834a9972ba56a/dataset.py#L126

The part where MNE is involved is when the file is loaded, about 25 lines earlier:

https://github.com/robintibor/auto-eeg-diagnosis-example/blob/9c9b130a3bc724fb74133cff8ce834a9972ba56a/dataset.py#L99-L102

I can't tell just by looking at your screenshots what the real problem is, but all signs indicate that this is not an MNE-Python bug: as @cbrnr [indicated above](https://github.com/mne-tools/mne-python/issues/11552#issuecomment-1472090959), the file is readable by MNE.  If you're convinced that MNE is doing something incorrectly, please open a new issue that *does not use the `auto-eeg-diagnosis-example` code, only MNE-Python commands* and shows that the RawEDF object is somehow problematic.
