### ISSUE TITLE
ENH: Aligning CT to MRI and running iEEG GUI without CT downsampling 

### ISSUE THREAD

**Issue by mmagnuski** [mne-tools/mne-python#11561]
Hi,
currently when transformation matrix is applied to CT scans they are interpolated to match the MRI voxel space. However, when original CT has higher resolution then downsampling it to the MRI can make the task of locating contacts harder. More specifically, we are looking for microelectrodes in the CT, and their position is not as vivid as the macro contacts. So locating microelectrodes even in the original CT can be not trivial, and after CT downsampling it can often be challenging.
My general question is if it would be possible to align the CT to MRI without resampling / interpolation and handle both scans in their original resolution in the iEEG GUI?
An easy work-around seems to be just upsampling the MRI so that CT wouldn't be downsampled, but maybe this use case could be handled in mne without such workarounds.

@alexrockhill

**Comment by alexrockhill** [comment]
Actually this is currently supported, you just don't pass any freesurfer surface information and pass the full resolution CT as aligned CT. I have been using macro electrodes so I haven't tested it thoroughly but I did think that this would be a nice use-case to support and it was enabled in some recent-ish refactoring. The only thing is that you'll have to handle the coordinate transforms to the MRI on the backend. Would you have time to make an example and I can review (using the sample seeg data)? (You could use micro electrodes at some point as well but that would involve adding another dataset).

**Comment by alexrockhill** [comment]
I have a minute, I'll give the example a first pass.

**Comment by alexrockhill** [comment]
Ah actually there were a few things that need to be changed in the GUI in order to support this.
