### ISSUE TITLE
ENH/VIZ: convenient plot method for labels 

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1157]
to do plots like in this example more conveniently / interactively.

http://martinos.org/mne/dev/auto_examples/inverse/plot_label_from_stc.html#example-inverse-plot-label-from-stc-py

**Comment by Autodidact24** [comment]
Hi @dengemann ,

What interactive features do we want to see in this plot ?
Currently, the output that we get is:
![image](https://cloud.githubusercontent.com/assets/5631503/6035656/5643d424-ac5d-11e4-985e-a37eacb98e4f.png)

Thanks,
Shubham

**Comment by PRRvalli** [comment]
Is the issue about adding x,y labels and legends to the plots ? It can be made better by add point for peaks of the signal. I wish to work on this issue . How do I start ?

**Comment by jaeilepp** [comment]
The issue is about cortical [parcellation labels](https://surfer.nmr.mgh.harvard.edu/fswiki/CorticalParcellation), but to me it's unclear what the API would look like for this. I assume @dengemann wants the ``plot`` method to have a kwarg for adding a label more conveniently.

**Comment by dengemann** [comment]
I think it was more for the part related to showing conveniently a label on the brain surface, it is not related to stcs.

``label.plot()```

```
...
# show both labels
brain.add_label(anat_label, borders=True, color='k')
brain.add_label(func_label, borders=True, color='b')
```

**Comment by jaeilepp** [comment]
So in essence, add a ``plot`` method for [Label](https://github.com/mne-tools/mne-python/blob/master/mne/label.py#L140). @PRRvalli you can start by opening a pull request along [these](http://martinos.org/mne/stable/contributing.html) guidelines.

**Comment by PRRvalli** [comment]
Will this method plot be sufficient enough, or should I make some changes 
```
def plot(self,borders=True,color='b')    
    '''
    Parameters
    ----------
    borders : bool 
        Border of the label. Default border = True       	
    color  : str
    	Color used to represent the Border. Default border = 'b' (blue) 
    '''
    brain.add_label(self, borders, color)
```

**Comment by larsoner** [comment]
@dengemann do we still need this? To me it falls into the "use matplotlib" category

**Comment by jona-sassenhagen** [comment]
I want `stc["banks-sts"].plot()` to work :|

**Comment by larsoner** [comment]
Any idea for an API?

The problem as I see it is that what you want is some variant of `read_labels_from_annot` followed by `extract_label_time_course` followed by a plotting operation, but there are many options for `read_labels_from_annot` and `extract_label_time_course`.

**Comment by jona-sassenhagen** [comment]
>Any idea for an API?

Nope. I may have noted before I'm utterly clueless concerning all things source space.

**Comment by larsoner** [comment]
Okay I'll close for now but if someone can think of an API let's reopen and discuss
