### ISSUE TITLE
bad dark mode CSS for HTML tables

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#11571]
every other line is almost unreadable. This is from 
https://mne.tools/dev/auto_tutorials/preprocessing/10_preprocessing_overview.html

![Screenshot 2023-03-17 at 17-30-06 Overview of artifact detection — MNE 1 4 0 dev74 g6384a8901 documentation](https://user-images.githubusercontent.com/1810515/226063967-ac43fdf0-c4fe-48b9-b49a-c23664216fa6.png)

**Comment by britta-wstnr** [comment]
I have noticed something similar on the output:

![image](https://user-images.githubusercontent.com/20129119/227893076-2bf05997-1a34-48b7-b4a8-ef6e8c09a04b.png)

from https://mne.tools/mne-connectivity/stable/auto_examples/cwt_sensor_connectivity.html
