### ISSUE TITLE
Avoid emojis that don't render well on older systems

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [mne-tools/mne-python#11589]
### Proposed documentation enhancement

Avoid recent emojis that do not render on older but still maintained systems. Here are examples from an Ubuntu 18.04 machine with Google Chrome.

<details>
<summary>Screen capture of the “New issue” page</summary>

![new_choose](https://user-images.githubusercontent.com/3234522/227150644-d6a84386-3c8f-4e1e-86c1-fb0f74395523.png)
</details>

* [U+1F41B Bug](https://codepoints.net/U+1F41B) from [`.github/ISSUE_TEMPLATE/bug_report.yml`](https://github.com/mne-tools/mne-python/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml)
* [U+1F4C4 Page Facing Up](https://codepoints.net/U+1F4C4) from [`.github/ISSUE_TEMPLATE/documentation.yml`](https://github.com/mne-tools/mne-python/blob/main/.github/ISSUE_TEMPLATE/documentation.yml)
* [U+1F6E0 Hammer and Wrench](https://codepoints.net/U+1F6E0) from [`.github/ISSUE_TEMPLATE/feature_request.yml`](https://github.com/mne-tools/mne-python/blob/main/.github/ISSUE_TEMPLATE/feature_request.yml)
* [U+1F4AC Speech Balloon](https://codepoints.net/U+1F4AC) from [`.github/ISSUE_TEMPLATE/config.yml`](https://github.com/mne-tools/mne-python/blob/main/.github/ISSUE_TEMPLATE/config.yml)

<details>
<summary>Screen capture of the “Documentation” issue page </summary>

![new_template_documentation yml](https://user-images.githubusercontent.com/3234522/227151305-0d59dfa9-f4e2-46c4-9f75-a909e94bf65f.png)
</details>

* [U+1F4C4 Page Facing Up](https://codepoints.net/U+1F4C4) from [`.github/ISSUE_TEMPLATE/documentation.yml`](https://github.com/mne-tools/mne-python/blob/main/.github/ISSUE_TEMPLATE/config.yml)

**Comment by cbrnr** [comment]
I'm fine with removing these emojis.

**Comment by agramfort** [comment]
👌

**Comment by drammock** [comment]
Yes please remove them. cc @hoechenberger: this is why I'm often pushing against adding emoji everywhere

**Comment by hoechenberger** [comment]
Do what you must, but I'd argue that system is **not** being properly maintained if it cannot even display Unicode characters correctly 🤷‍♀️

**Comment by cbrnr** [comment]
You are not wrong. In addition, this Ubuntu release is EOL in May, so we should not have to care.

**Comment by larsoner** [comment]
None of NumPy, pandas, or scikit-learn use emojis in this context, either, so +1 for removing from me

**Comment by DimitriPapadopoulos** [comment]
I must stress that my Ubuntu Ubuntu 18.04 machine fails to render _some_ emojis (mostly the 4 codepoints I had listed above), not all emojis. While I am supposed to be working on a properly configured Ubuntu 18.04 workstation, I certainly cannot vouch for the IT subcontractor in charge of installing these workstations.

That said, we are in the process of moving to Ubuntu 22.04. Hopefully I won't mind very soon.

But wait! After reading [Emoji can not show in Ubuntu 18.04](https://askubuntu.com/questions/1219407/emoji-can-not-show-in-ubuntu-18-04) and installing the [`fonts-noto-color-emoji`](https://packages.ubuntu.com/bionic/fonts-noto-color-emoji) package, it works for me.

![fonts-noto-color-emoji](https://user-images.githubusercontent.com/3234522/227262654-5f8cc8cf-bde9-426f-a52d-64a09c62cbcf.png)

**Comment by cbrnr** [comment]
Nice, so let's leave them in then. Again, 18.04 will be EOL in May, and we normally don't support deprecated platforms.

**Comment by DimitriPapadopoulos** [comment]
Just nitpicking, but Ubuntu 18.04 won't be totally EOL before 2028. Extended Security Maintenance (ESM) will remain available until April 2028.

**Comment by cbrnr** [comment]
Only if you pay.
