### ISSUE TITLE
Add short documentation for `RawEDF`?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [mne-tools/mne-python#11588]
### Proposed documentation enhancement

Function [`mne.io.read_raw_edf()`](https://mne.tools/stable/generated/mne.io.read_raw_edf.html) returns an instance of **`RawEDF`**, but as far as I can see this class is not documented.

Since **`RawEDF`** inherits base class **`BaseRaw`**, it might be sufficient to point to the [`mne.io.BaseRaw`](https://mne.tools/stable/generated/mne.io.BaseRaw.html#mne-io-baseraw) documentation.

**Comment by DimitriPapadopoulos** [comment]
Class **`RawEDF`** is actually documented in the source code:

https://github.com/mne-tools/mne-python/blob/603a96da58ddba3c2c05d3a01639abd669cc9543/mne/io/edf/edf.py#L47-L54

But I cannot find the actual documentation using the search function:

![search](https://user-images.githubusercontent.com/3234522/227146340-4ad3272c-9f52-4c02-84b5-58e7844ba204.png)

**Comment by DimitriPapadopoulos** [comment]
Also:
* The class is missing from the [Python API Reference](https://mne.tools/dev/python_reference.html).
* The URL that should in theory display the **`RawEDF`** documentation returns a 404:
  https://mne.tools/dev/generated/mne.io.RawEDF.html

**Comment by larsoner** [comment]
Yes that's why -- people should look at `Raw` or `BaseRaw` for methods, so I'll close

**Comment by larsoner** [comment]
I guess we could. I'd go for something like `The raw instance. See :class:`mne.io.BaseRaw` for details.` or something

**Comment by DimitriPapadopoulos** [comment]
I suggest:

> The raw instance. See base class [`mne.io.BaseRaw`](https://mne.tools/stable/generated/mne.io.Raw.html#mne.io.Raw) for documentation of attribute and methods.

This would match the [`mne.io.BaseRaw`](https://mne.tools/stable/generated/mne.io.BaseRaw.html) documentation itself:
![mne io BaseRaw](https://user-images.githubusercontent.com/3234522/227238020-24400b71-de24-47b3-867a-6476fd967ef7.png)

Perhaps also add a link in the **See also** section of [`mne.io.read_raw_edf()`](https://mne.tools/stable/generated/mne.io.read_raw_edf.html)?

**Comment by larsoner** [comment]
Yes but `BaseRaw` doesn't actually document any of the methods, just lists them. I'd rather link to `Raw` directly since it contains the method docs

**Comment by DimitriPapadopoulos** [comment]
Will do.

But then, the detailed documentation of methods could be moved from `Raw` to `BaseRaw`, couldn't it? I mean, does `Raw` contain the detailed documentation for historical reasons, or for real design reasons?

**Comment by larsoner** [comment]
Historical mostly I think. Probably not worth changing it to `BaseRaw` for now
