### ISSUE TITLE
Strange Unicode characters in `.github/config.yml`

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [mne-tools/mne-python#11593]
### Proposed documentation enhancement

File [`.github/config.yml`](https://github.com/mne-tools/mne-python/blame/main/.github/config.yml) contains some strange Unicode characters. While my browser or editor do not display them, they do appear with a `cat` in the console:

![cat](https://user-images.githubusercontent.com/3234522/227303697-d6fab05b-aafc-4b3e-99e6-0c7f12bc3690.png)

I don't think the last 2 characters were inserted on purpose. Is it OK to remove them, keeping 🚴?

**Comment by drammock** [comment]
those are unicode combining characters. They are supposed to render as a single glyph (in this case "man riding bicycle" probably).  I see no harm in making these emoji gender-unspecified.

**Comment by drammock** [comment]
you can look up the codepoints:

```py
In [1]: glyph = "🚴🏽‍♂️"
In [2]: glyph.encode('raw_unicode_escape').decode()
Out[2]: '\\U0001f6b4\\U0001f3fd\\u200d\\u2642\\ufe0f'
```
