### ISSUE TITLE
Rename "Discourse" link in top navigation to "Forum" or "User Forum"

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#11637]
### Proposed documentation enhancement

When hovering over the Discourse icon in our navigation, the alt / link text that pops up is "Discourse". Now, if one doesn't know that this is meant to be a forum, one will only find out after clicking on it (if one dares to click). I'd like to propose renaming the link to "Forum" or "User Forum" for clarity.

**Comment by cbrnr** [comment]
👍 for "Forum".

**Comment by drammock** [comment]
I'm fine with "Forum" or "User Forum". Slight preference for "Forum" because we also want Discourse to be a place for *contributors* to ask questions.
