### ISSUE TITLE
ENH: Warn for within-ch-type large singular value difference during inversion

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#11661]
### Describe the new feature or enhancement

Working with @SophieHerbst, we frequently forget to pass `rank='info'` to the various functions that offer this parameter. MNE then tries to empirically estimate the rank of our Maxwell-filterted data and is always wrong (assumes full rank), and stuff just explodes.

Since we literally **always** have to ensure we pass `rank='info'` after Maxwell-filtering, I was wondering if we could change the default behavior `rank=None` such that if the `info` object indicates that Maxwell-filtering was performed, `rank='info'` will be used?

### Describe your proposed implementation

Change the default behavior of `rank=None` to behave like `rank='info'` if Maxwell-filtered data was passed. To continue allowing empirical rank computation in that case, we add a new parameter value, `rank='empirical'`. Potentially breaks existing analysis code.

### Describe possible alternatives

Leave as is.

But it's inconvenient and odd that things don't work as expected out-of-the-box.

**Comment by agramfort** [comment]
can you paste lines that use default parameters and than obviously don't do
the right thing? I am not sure it's the origin of the issue here but more
the noise cov and whitening step that screw up by making the data full rank

**Comment by hoechenberger** [comment]
@SophieHerbst If you have time, could you provide a few example lines as requested by @agramfort? Thanks!

**Comment by SophieHerbst** [comment]
> I am not sure it's the origin of the issue here but more
> the noise cov and whitening step that screw up by making the data full rank

Yes, exactly. I did pass the rank='info' but the wrong info to make_inverse_operator. 
This happens easily if the noise-cov is computed on empty room or resting state data, even through it is in the documentation.

**Comment by hoechenberger** [comment]
Oh, I'm sorry, that means I misunderstood and mis-reported the issue here, no? 🤔

**Comment by larsoner** [comment]
> Yes, exactly. I did pass the rank='info' but the wrong info to make_inverse_operator... Would there be a way to check the distribution of stc.data values and issue warning if the distribution is off?

I agree we should be able to detect for example when the smallest MEG singular value retained is enough orders of magnitude (4? 5?) smaller than the largest. I think this is almost always going to be problematic and result in the behavior you've observed.

**Comment by hoechenberger** [comment]
@larsoner Feel free to rename this issue and collapse my initial comment – it appears I got things mixed up in my initial report.
