### ISSUE TITLE
Fix docstrings in notch_filter functions

### ISSUE THREAD

**Issue by chapochn** [mne-tools/mne-python#11688]
### Proposed documentation enhancement

Written:

> trans_bandwidth: float
>     Width of the transition band in Hz. Only used for method='fir'.

Should be (according to the code):

> trans_bandwidth: float
>     Width of the transition band in Hz. Only used for method='fir' and method='iir'.

**Comment by larsoner** [comment]
I think you're right, @chapochn would you be up for fixing this?

**Comment by chapochn** [comment]
Thanks for checking. I think I could, not immediatly though. Another lack in the documentation is that the parameter:

> freqs[float]
>     Frequencies to notch filter in Hz, e.g. np.arange(60, 241, 60). None can only be used with the mode ‘spectrum_fit’, where an F test is used to find sinusoidal components.

can only take a range of frequencies when the method is 'fir' or 'spectrum_fit' (which is not specified). When one put the method 'iir', I get the error:

> ValueError: Multiple stop-bands can only be used with FIR filtering

If I understood correctly 'spectrum_fit' uses a method of substraction to get rid of the component, and not a filter per se? So the error message should also be updated?

**Comment by larsoner** [comment]
> If I understood correctly 'spectrum_fit' uses a method of substraction to get rid of the component, and not a filter per se? So the error message should also be updated?

How would you update this part? To me it's okay to say that "multiple stop-bands can only be used with FIR filtering" even if whatever method you're calling isn't itself doing filtering

**Comment by itsdivya1309** [comment]
> I think you're right, @chapochn would you be up for fixing this?

I want to start contributing to open source.
And if the issue is still open, I would like to fix it

**Comment by chapochn** [comment]
@itsdivya1309 I haven't work on it, so please feel free to fix!

@larsoner :
> How would you update this part? To me it's okay to say that "multiple stop-bands can only be used with FIR filtering" even if whatever method you're calling isn't itself doing filtering
I would propose to write (in the documentation of `freqs` and in the above-mentionned error message) "Multiple stop-bands can only be used with method='fir' or method='spectrum_fit'."

**Comment by itsdivya1309** [comment]
Sir, I'm new to open source. I've been using mne library for my research
internship and thought of this issue as one related to documentation only.
Please let me know if I'm wrong.

**Comment by larsoner** [comment]
Yes I think it's a doc-only update

**Comment by itsdivya1309** [comment]
Ok, thank you. Will do it by this week.
