### ISSUE TITLE
mne.io.read_raw_fil should support datasets without sensor positions

### ISSUE THREAD

**Issue by RCTimms** [mne-tools/mne-python#11706]
### Describe the new feature or enhancement

It would be great to generalise mne.io.read_raw_fil so that it would read in data which didn't have channel positions, or the documentation should reflect that the positions.tsv file is required to use this method.

### Describe your proposed implementation

The existing method can be used, but should have a case to handle an instance of this file missing.

### Describe possible alternatives

n/a

**Comment by RCTimms** [comment]
@georgeoneill

**Comment by larsoner** [comment]
Maybe a new `on_pos_missing='raise'` would be good. Then set the loc to nan if no positions provided

**Comment by georgeoneill** [comment]
This should be pretty easy to implement. The code already assumes there is [no position information for any sensors](https://github.com/mne-tools/mne-python/blob/4ce984f4458652551e2997da3749c2cbdb92a64e/mne/io/fil/fil.py#LL102C39-L102C39), but for some reason I forgot to get to check if position files exists in the current iteration of the code.

**Comment by RCTimms** [comment]
Thanks for looking into this
