### ISSUE TITLE
Baseline must be a tuple?

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#11711]
I was wondering if forcing the `baseline` argument to be a tuple is necessary and/or added on purpose in #9210 (https://github.com/mne-tools/mne-python/blob/main/mne/baseline.py#L178). I usually tend to use lists, and this used to work before this change. Now, a tuple is required. @hoechenberger? cf https://github.com/cbrnr/mnelab/issues/381

**Comment by hoechenberger** [comment]
We always explicitly requested `baseline` to be a tuple as per the API docs, so I suppose this change you mentioned is just to ensure that the output (in the `.baseline` attribute) equals the input provided by the user. I think it'd be good to support `array-like of length 2` as input and cast to a tuple internally

**Comment by cbrnr** [comment]
Yes, I'd also prefer list-like with two elements if there is no strong reason to require a tuple. If everyone agrees I can submit a PR.

**Comment by agramfort** [comment]
Works for me
