### ISSUE TITLE
Tutorial for EEG-Eyetracking integration

### ISSUE THREAD

**Issue by scott-huberty** [mne-tools/mne-python#11759]
### Proposed documentation enhancement

I would like to update the current eye-tracking tutorial to demonstrate integrating an eyetracking `RawEyelink` object with EEG  (in this case, a `RawMFF` object).

We don't need to add any new functions to MNE for this. We can use `mne.preprocessing.realign_raw`, passing in the photo-diode DIN events that were sent to both the Eyetracking and EEG acquisitions, to align the EEG and eye-tracking signals. I've been doing this for a study we're currently running and it works well!

I have an updated recording from the Pupillary Light Reflex task (including both the eyelink and EGI files) that we can use for this.

**Comment by larsoner** [comment]
Awesome, this would be a good thing to work on next! We need to add a new dataset for this, too, right?

**Comment by scott-huberty** [comment]
> Awesome, this would be a good thing to work on next! We need to add a new dataset for this, too, right?

Yeah! I think our  tutorial's current PLR dataset is downloaded from OSF - so I can update it there (IIRC, My EEG file for the updated dataset is like 200mb.. So probably better to keep it on OSF and not in `mne-sample-datasets`?)

**Comment by larsoner** [comment]
OSF is fine to use for datasets, feel free to just update the dataset there and we can add it as a new `mne.datasets.<something>`
