### ISSUE TITLE
mne_logo.svg bottom text hard to read in dark mode

### ISSUE THREAD

**Issue by pllim** [mne-tools/mne-python#11791]
### Description of the problem

https://mne.tools/stable/_static/mne_logo.svg is not really made for dark mode. Bottom text is hard to read.

### Steps to reproduce

Look at the rendered README file on GitHub when browser set to dark mode. I used Chrome but it should not matter which one.

### Expected results

Bottom text to be lighter color in dark mode.

### Actual results

Bottom text remains black, so very hard to read in dark background.

### Additional information

I happened to view the README here. I always have dark mode on.

**Comment by drammock** [comment]
indeed it is!  Maybe we should replace with https://mne.tools/dev/_static/mne_logo_small.svg instead, which works equally well on light and dark...  I'm not sure if/how we could make an `.rST` readme show different images depending on browser (or GH?) light/dark settings. Do you know if this is even possible @pllim ?

**Comment by pllim** [comment]
AFAIK there is no if-else in RST, so if you have one image that works in both, that would be great!

**Comment by pllim** [comment]
Hmm still hard to read for me. 🤷 

![Screenshot 2023-11-07 165042](https://github.com/mne-tools/mne-python/assets/2090236/c55416ce-f7e0-407c-bd45-6206c9ca50a2)

**Comment by larsoner** [comment]
Was closed slightly prematurely -- should be fixed tomorrow morning after CircleCI deploys and I open a quick PR to change it to use the `_gray.svg` variant

**Comment by larsoner** [comment]
All better

![Screenshot from 2023-11-08 08-56-16](https://github.com/mne-tools/mne-python/assets/2365790/651a2c14-c979-4956-9ab4-52b6e33ab908)

**Comment by pllim** [comment]
Indeed. Thanks!
