### ISSUE TITLE
mne.io.read_raw() should add mapping to read_raw_curry()

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#11813]
### Describe the new feature or enhancement

I wanted to read a Curry (.cdt) file via `read_raw()` instead of `read_raw_curry()`. However, it appears this is currently not supported.

### Describe your proposed implementation

`read_raw()` should add a mapping to `read_raw_curry()` for the respective Curry filename extensions.

### Describe possible alternatives

–

### Additional context

Currently, I receive:

```python
ValueError: Unsupported file type (.cdt). Consider using a dedicated reader function for more options.
```

**Comment by cbrnr** [comment]
Do you have time to add it? It's basically only two additional lines. Are there any other readers that should be integrated while we're at it?

If you don't have time I can do it.
