### ISSUE TITLE
Problem in mne.preprocessing.ica._find_max_corrs

### ISSUE THREAD

**Issue by Wana999** [mne-tools/mne-python#11848]
**Line 3178 in the ica.py file**
‘’‘
_mean_of_maps = np.std(np.asarray(maxmaps))_
‘’’

I think it should be
'''
_mean_of_maps = np.mean(np.asarray(maxmaps))_
'''

**Comment by larsoner** [comment]
https://github.com/mne-tools/mne-python/blame/b5a9a25d3fac7e4058b91efcadf6561b85aa45a3/mne/preprocessing/ica.py#L3177-L3178

Yes that looks like a bug. I'm surprised it's working properly!

Would you be up for making a PR to fix it?

**Comment by hoechenberger** [comment]
What are the implications of touching this? This piece of code is used for automated artifact detection, right? So if we change this, we may break existing z-score thresholds, yes? We should be very careful here. Even though it's a bug that needs to be fixed, I would treat this like a heavy API change that should not be introduced without a sufficiently long deprecation cycle (2 to 4 releases).

just my 2 ct

@agramfort WDYT?

**Comment by Wana999** [comment]
I just discovered this question when I was learning how to analyze the correlation of the components of ICA. I don't really understand the algorithm flow of corrmap, so I hope this bug can be fixed as soon as possible.



At 2023-08-02 18:03:24, "Richard Höchenberger" ***@***.***> wrote:

What are the implications of touching this? This piece of code is used for automated artifact detection, right? So if we change this, we may break existing z-score thresholds, yes? We should be very careful here. Even though it's a bug that needs to be fixed, I would treat this like a heavy API change that should not be introduced without a sufficiently long deprecation cycle (2 to 4 releases).

just my 2 ct

@agramfort WDYT?

**Comment by hoechenberger** [comment]
It seems my assumption was incorrect and the EOG and ECG detection methods don't rely on `ICA.corrmap()`, so all should be good with fixing this asap.

**Comment by hoechenberger** [comment]
You can try making a pull request with a fix if you want

**Comment by larsoner** [comment]
The fix ended up being a littly bit bigger, PR in https://github.com/mne-tools/mne-python/pull/11858

**Comment by larsoner** [comment]
Fixed by #11858, closing!
