### ISSUE TITLE
Inconsistent splits naming between `Raw` and `Epochs` when using `BIDS` schema

### ISSUE THREAD

**Issue by dmalt** [mne-tools/mne-python#11870]
### Description of the problem

Not really a bug, more of an inconsistent behaviour.
Saving large `Raw` and `Epochs` data with `split_naming='bids'` uses different naming schema. 

When I save large `Raw`, I get suffixes `split-01` and `split-02`, etc. but when saving `Epochs`, the first split is saved without suffix, while the second one has `split-01`. See the code snippet below for details. All asserts pass for me.

Is there a reason for such difference?

### Steps to reproduce

```Python
import mne
from pathlib import Path

sample_data_folder = mne.datasets.sample.data_path()
sample_data_raw_file = sample_data_folder / "MEG" / "sample" / "sample_audvis_raw.fif"
raw = mne.io.read_raw_fif(sample_data_raw_file, verbose=False).crop(tmax=60)
ev = mne.find_events(raw)
epochs = mne.Epochs(raw, ev, tmin=-0.3, tmax=0.7)

raw.save("raw_meg.fif", split_naming="bids", split_size="50MB")
epochs.save("epochs_epo.fif", split_naming="bids", split_size="50MB")

# all these asserts pass
assert not Path("raw_meg.fif").is_file()
assert Path("raw_split-01_meg.fif").is_file()
assert Path("raw_split-02_meg.fif").is_file()

assert Path("epochs_epo.fif").is_file()  # this should fail though
assert Path("epochs_split-01_epo.fif").is_file()
assert not Path("epochs_split-02_epo.fif").is_file()  # this should fail as well
```

### Expected results

These two asserts should fail
```python
assert Path("epochs_epo.fif").is_file()
assert not Path("epochs_split-02_epo.fif").is_file()
```

### Actual results

All asserts pass

### Additional information

Platform             macOS-13.4.1-arm64-arm-64bit
Python               3.11.3 (main, May 15 2023, 18:01:31) [Clang 14.0.6 ]
Executable           /Users/dmalt/Applications/miniconda3/envs/mne_cli_tools/bin/python3
CPU                  arm (8 cores)
Memory               Unavailable (requires "psutil" package)
Core
├☑ mne               1.4.2
├☑ numpy             1.25.2 (OpenBLAS 0.3.23.dev with 8 threads)
├☑ scipy             1.9.3
├☑ matplotlib        3.7.2Installed osx event loop hook.
 (backend=MacOSX)
├☑ pooch             1.7.0
└☑ jinja2            3.1.2

Numerical (optional)
├☑ sklearn           1.3.0
├☑ pandas            1.5.3
└☐ unavailable       numba, nibabel, nilearn, dipy, openmeeg, cupy

Visualization (optional)
└☐ unavailable       pyvista, pyvistaqt, ipyvtklink, vtk, qtpy, ipympl, pyqtgraph, mne-qt-browser

Ecosystem (optional)
└☐ unavailable       mne-bids, mne-nirs, mne-features, mne-connectivity, mne-icalabel, mne-bids-pipeline

**Comment by sappelhoff** [comment]
Thanks for the report! I agree, this looks like a bug.

Furthermore, a minor point: the indexes (01, 02, ... ) do not really need to be prefixed with a 0 if they never exceed 9 -- and I guess we can know that before writing the files and adjust the behavior accordingly.

**Comment by dmalt** [comment]
Thanks for such a quick response from both of you!

Frankly, now that I think of it, I like the behaviour of `Epochs` better than that of `Raw`, although I suspect it was a conscious design choice in case of `Raw`.  

Picture this. You have to write a data processing pipeline for a new experiment for which only part of the data were recorded. So far all the recorded data are under 2GB, so you don't have to worry about splits. Then the new data arrive and for one subject the file size is above 2GB, so when you save the intermediate preprocessed copy, the saved file will have the `split-` suffix.  Now all the other scripts that are trying to access this file are broken and should be changed. If the intermediate steps don't reduce the file size, like filtering, the result for those steps will also have the `split-` suffix after saving, and so on. The situation gets even worse if you're using some sort of text-based templating framework for the filenames (like hydra). This actually happened to me once and it was really annoying to fix.

One way to avoid this would be to use the old "neuromag" split naming, but in this case I think BIDS checkers start complaining.

Instead if the main split didn't change its name, like for `Epochs` now,  everything would have worked the same way.
I'm not sure though, what BIDS specification has to say about this matter and what was the original thinking process behind the splits behaviour for `Raw` as it is now.

What do you guys think?

**Comment by dmalt** [comment]
BTW, is it possible to modify saving raw files in `.fif.gz` so all the splits live inside the same archive to avoid this altogether?

I think "parse, not validate" rule applies here: it might be better to convert to a format that doesn't use splits once than to think about this corner case each time. Just a thought.

**Comment by agramfort** [comment]
>
> BTW, is it possible to modify saving raw files in .fif.gz so all the
> splits live inside the same archive to avoid this altogether?
>
it's not what .gz (gzip) does. It only compresses one file in mne (to make
it smaller).

> I think "parse, not validate" rule applies here: it might be better to
> convert to a format that doesn't use splits once than to think about this
> corner case each time. Just a thought.
>
it's a trade off. Using .fif guarantees that all measurement info /
metadata  are not lost for MEG data. I don't know any other
format that guarantees this and that already has readers for most
programming languages and will likely be readable in > 10 years.

I would say we need to fix the way we handle split files to make it
painless even if it involves a bit of magic.

**Comment by dmalt** [comment]
> it's not what .gz (gzip) does. It only compresses one file in mne (to make it smaller).

I see. Somehow I thought gzip was like zip archives.

I'm definitely not suggesting moving away from `.fif`. Merely having an option to wrap it into archive as a potential solution to splits. You already do the compression/decompression in io functions, when filename ends in `.fif.gz`. The same way you could wrap/unwrap split files (or a single file) in a tarball, when the extension is `.fif.tar.gz` or `.fif.tar`.  It's not gonna solve the splits problem completely, because you can't really drop the support for  the vanilla `.fif`, so the splits bugs will reappear from time to time. But if tarballs are advertised in the docs as a recommended way of dealing with splits, a lot of these bugs will go away for the end user. `.fif` splits are not meant to be treated as separate files: any time you move them apart or even rename them, everything breaks. It won't happen if they are inside an archive. 

I realise there are issues with this approach but still thought it was worth suggesting.  Don't know. Maybe it's all nonsense and will only complicate things further.

**Comment by agramfort** [comment]
>
> I'm definitely not suggesting moving away from .fif. Merely having an
> option to wrap it into archive as a potential solution to splits. You
> already do the compression/decompression in io functions, when filename
> ends in .fif.gz. The same way you could wrap/unwrap split files (or a
> single file) in a tarball, when the extension is .fif.tar.gz or .fif.tar.
> It's not gonna solve the splits problem completely, because you can't
> really drop the support for the vanilla .fif, so the splits bugs will
> reappear from time to time. But if tarballs are advertised in the docs as a
> recommended way of dealing with splits, a lot of these bugs will go away
> for the end user. .fif splits are not meant to be treated as separate
> files: any time you move them apart or even rename them, everything breaks.
> It won't happen if they are inside an archive.
>

the issue with tarball idea is that you would need to decompress the data
in memory  to be able to start loading data. So I fear it will be heavy
both in computation and memory.

**Comment by dmalt** [comment]
Yes, that's true, this will break `preload=False` since there's no way to know where the second split starts in a tar archive without unarchiving the whole thing. Maybe with `zip` it's possible, since it has index. I'm not sure.
