### ISSUE TITLE
MAINT: deprecate mne maxfilter command line tool

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#11938]
I'm actually inclined to deprecate this instead and remove it after 1.6. We have had `mne.preprocessing.maxwell_filter` for some time which should be more fully featured and it's what we want to support going forward. If people want to use the command-line `maxfilter` from MEGIN I think it's okay nowadays to have them do it from the command line directly -- `mne maxwell_filter` does not actually do much for people, so the workaround for deprecation is actually pretty straightforward -- use `maxfilter` directly with nearly identical args. The only extra thing it does is write out an `origin` and this can be done pretty easily with minimal MNE code already I think.

_Originally posted by @larsoner in https://github.com/mne-tools/mne-python/pull/11937#pullrequestreview-1603222289_

**Comment by larsoner** [comment]
I'll do this quickly now
