### ISSUE TITLE
brain.add_annotation from a file fails when hemi='both'

### ISSUE THREAD

**Issue by wmvanvliet** [mne-tools/mne-python#11945]
### Description of the problem

When adding a parcellation to a brain render, you can specify a filename to read it from. Since there's two files, one for each hemisphere, there is some code that reads the file for the other hemisphere automatically. Only, this is currently broken.

### Steps to reproduce

```Python
import mne
subjects_dir = mne.datasets.sample.data_path() / 'subjects'
brain = mne.viz.Brain('fsaverage', subjects_dir=subjects_dir, hemi='both')
brain.add_annotation(str(subjects_dir / "fsaverage" / "label" / "lh.PALS_B12_Lobes.annot"))
```

### Expected results

Parcellation is shown correctly.

### Actual results

`RuntimeError: To add both hemispheres simultaneously, filename must begin with "lh." or "rh."`

### Additional information

There is a unit-test verifying the above actually fails. This seems odd. Isn't this supposed to work?
https://github.com/mne-tools/mne-python/blob/99acd07823dc7018a09ccc8f1fa58a9e7ab884c2/mne/viz/_brain/tests/test_brain.py#L527

**Comment by larsoner** [comment]
Maybe it should say "must **not** begin with"? But that would be weird. I would expect it just to add both so agree this is probably a bug.

While we (you?) are in there fixing things, you also shouldn't need to use a `str` cast as we nowadays try to accept `Path` everywhere. A `fname = _check_fname(fname, overwrite="read", must_exist=False)` inside that function should probably do it (including nice things like type checks)
