### ISSUE TITLE
BUG: brain.set_view(**brain.get_view()) not no-op

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#11941]
> I've run into a problem: if I get the camera parameters from `brain.get_view()` and assign them back into the proper parameters of `brain.show_view()`, the camera angle has changed. Same for going one level deeper with `brain._renderer.get_camera()` and `brain._renderer.set_camera()`. It seems that whatever the `set_camera()` is doing is not lining up with what `get_camera()` returns (other than having a different order of the parameters)

_Originally posted by @wmvanvliet in https://github.com/mne-tools/mne-python/issues/11891#issuecomment-1700516503_

**Comment by wmvanvliet** [comment]
Furthermore: using the arrow keys in a `Brain` figure to rotate the camera around gives strange results, as in that the camera also zooms in and out. There seems to be a problem with the translation of azimuth and elevation to the camera position and view direction.
