### ISSUE TITLE
MAINT: Add steering committee members to CODEOWNERS

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#11973]
Hey @mne-tools/mne-python-steering-committee, could each of you please take a moment to open a PR to add yourself to [CODEOWNERS](https://github.com/mne-tools/mne-python/blob/main/.github/CODEOWNERS) in this repo? We would like to start using this as a way to triage issues, PR reviews, and forum posts to people with relevant domain expertise.

Feel free to use as fine-grained or coarse file patterns as you want following the [gitignore syntax](https://git-scm.com/docs/gitignore#_pattern_format) (see also [cheatsheet](https://gist.github.com/jstnlvns/ebaa046fae16543cc9efc7f24bcd0e31)). To make an example, I've opened a PR on behalf of @rob-luke in https://github.com/mne-tools/mne-python/pull/11972. (And @sappelhoff if you're happy with your current set of files, no need to update anything!)

Progress:

- [x] agramfort
- [x] wmvanvliet
- [x] rob-luke
- [x] drammock
- [x] dengemann
- [x] hoechenberger
- [x] larsoner
- [x] adam2392
- [x] cbrnr
- [x] bloyl
- [ ] mmagnuski
- [x] sappelhoff
- [x] alexrockhill
- [x] jasmainak
- [x] GuillaumeFavelier
- [x] britta-wstnr
- [x] mscheltienne

**Comment by larsoner** [comment]
Ping @dengemann @mmagnuski @jasmainak do you want to be added somewhere?

**Comment by jasmainak** [comment]
please add me here:

https://github.com/mne-tools/mne-python/blob/8051f6ddf68a797ec0c9e1801aea3c73808bba03/.github/CODEOWNERS#L84

I'll make a PR to add myself if something else crops up in the future

**Comment by drammock** [comment]
> please add me here:
> 
> https://github.com/mne-tools/mne-python/blob/8051f6ddf68a797ec0c9e1801aea3c73808bba03/.github/CODEOWNERS#L84
> 
> I'll make a PR to add myself if something else crops up in the future

Please do this PR yourself. Can be your first contribution to this week's sprint :)

**Comment by drammock** [comment]
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#about-code-owners

> Code owners are automatically requested for review when someone opens a pull request that modifies code that they own.

**Comment by mmagnuski** [comment]
Sorry for missing this, I'll take a look and add myself here and there (separate PR then).

**Comment by larsoner** [comment]
Still some left to add, reopening

**Comment by jasmainak** [comment]
okay I went ahead and added myself to codeowners [here](https://github.com/mne-tools/mne-python/pull/12089/files)

practically speaking though, I watch all the discussions on mne-python and pitch in when necessary ... everything goes through a filter in the mailbox and is checked periodically. I don't think it's easy to create separate filters for codeowner-triggered notifications vs rest of github.

**Comment by hoechenberger** [comment]
@jasmainak be aware that whenever a PR touching one of the parts of the project that you signed up as a code owner for, a review request will be triggered, as @cbrnr mentioned above
This might totally spam your GH Notification center

**Comment by sappelhoff** [comment]
cc @mmagnuski @GuillaumeFavelier @bloyl friendly ping --> you're still missing from the file :-)

**Comment by larsoner** [comment]
@mmagnuski happy new year! Do you have a minute to add yourself to CODEOWNERS?

**Comment by larsoner** [comment]
Closing since this is complete enough I think
