### ISSUE TITLE
ENH: twitter visibility + quality of content

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1200]
Hi folks,

@mluessi and I just had a quick mne-storm on how to improve our twitter visibility.
- get rid of messages for each commit. let's admit that this is rather noise to us and our followers
- instead parse updates of the what's new file on a nightly base and add mentions if the contributors have twitter accounts and an `#MEG` or `#neuroscience` hashtag
- this should help disseminating news + make sure the news are both, relevant and digestible 
- finally use url-shorters to allow for addition user mentions + hashtags

WDYT, folks?

@Eric89GXL @agramfort @christianmbrodbeck @t3on @mainakjas @dgwakeman @joewalter @rgoj  @adykstra ...

**Comment by agramfort** [comment]
@mainakjas still up for this?

**Comment by mainakjas** [comment]
sure, why not

**Comment by Eric89GXL** [comment]
@jasmainak still interested in this? It's marked for 0.12, so roughly one month out

**Comment by jasmainak** [comment]
I am interested but I need a hackathon / hacking session to do this ;)

**Comment by Eric89GXL** [comment]
I'll push to 0.13, then, and if it gets in before it, that's great

**Comment by jasmainak** [comment]
sounds great
