### ISSUE TITLE
`mne.io.read_raw_edf()` raises an error in `mne==1.5.1`, but works correctly in `mne==1.5.0`

### ISSUE THREAD

**Issue by tomasdominik** [mne-tools/mne-python#12007]
### Description of the problem

Using `mne.io.read_raw_edf(input_fname)` in `mne==1.5.0` works correctly. The file is loaded with no apparent issues. However, calling the same function with the same file in `mne==1.5.1` returns:

`ValueError: At least one channel name in annotations missing from info: Fp1`

### Steps to reproduce

```Python
# the bug did not occur with the eegbci sample data
# this is the code I use to load my own .edf data
# (using identical code in mne==1.5.0 where it works
# and in mne==1.5.1 where it returns the error)

subject = pilot5.01
mne.io.read_raw_edf(subject + "_eeg.edf", preload=True, verbose=True)
```

### Link to data

I can share the data file upon personal request.

### Expected results

```
Extracting EDF parameters from _[DIRECTORY]_\pilot5.01_eeg.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 3583568  =      0.000 ...  3583.568 secs...
```

### Actual results

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
(...)\eeg_analysis.ipynb Cell 58 line 2
      1 # Load EEG data
----> 2 raw_eeg = mne.io.read_raw_edf(subject + "_eeg.edf", preload=True, verbose=True)

File c:\Users\[USER]\anaconda3\envs\Analysis\lib\site-packages\mne\io\edf\edf.py:1686, in read_raw_edf(input_fname, eog, misc, stim_channel, exclude, infer_types, include, preload, units, encoding, verbose)
   1684 if ext != "edf":
   1685     raise NotImplementedError(f"Only EDF files are supported, got {ext}.")
-> 1686 return RawEDF(
   1687     input_fname=input_fname,
   1688     eog=eog,
   1689     misc=misc,
   1690     stim_channel=stim_channel,
   1691     exclude=exclude,
   1692     infer_types=infer_types,
   1693     preload=preload,
   1694     include=include,
   1695     units=units,
   1696     encoding=encoding,
   1697     verbose=verbose,
   1698 )

File <decorator-gen-251>:10, in __init__(self, input_fname, eog, misc, stim_channel, exclude, infer_types, preload, include, units, encoding, verbose)

File c:\Users\[USER]\anaconda3\envs\Analysis\lib\site-packages\mne\io\edf\edf.py:213, in RawEDF.__init__(self, input_fname, eog, misc, stim_channel, exclude, infer_types, preload, include, units, encoding, verbose)
    199     tal_data = self._read_segment_file(
    200         np.empty((0, self.n_times)),
    201         idx,
   (...)
    206         None,
    207     )
    208     onset, duration, desc, ch_names = _read_annotations_edf(
    209         tal_data[0],
    210         encoding=encoding,
    211     )
--> 213 self.set_annotations(
    214     Annotations(
    215         onset=onset,
    216         duration=duration,
    217         description=desc,
    218         orig_time=None,
    219         ch_names=ch_names,
    220     )
    221 )

File <decorator-gen-233>:12, in set_annotations(self, annotations, emit_warning, on_missing, verbose)

File c:\Users\[USER]\anaconda3\envs\Analysis\lib\site-packages\mne\io\base.py:725, in BaseRaw.set_annotations(self, annotations, emit_warning, on_missing, verbose)
    723 delta = 1.0 / self.info["sfreq"]
    724 new_annotations = annotations.copy()
--> 725 new_annotations._prune_ch_names(self.info, on_missing)
    726 if annotations.orig_time is None:
    727     new_annotations.crop(
    728         0, self.times[-1] + delta, emit_warning=emit_warning
    729     )

File c:\Users\[USER]\anaconda3\envs\Analysis\lib\site-packages\mne\annotations.py:495, in Annotations._prune_ch_names(self, info, on_missing)
    493 if name not in keep:
    494     if not warned:
--> 495         _on_missing(
    496             on_missing,
    497             "At least one channel name in "
    498             f"annotations missing from info: {name}",
    499         )
    500         warned = True
    501 else:

File c:\Users\[USER]\anaconda3\envs\Analysis\lib\site-packages\mne\utils\check.py:1153, in _on_missing(on_missing, msg, name, error_klass)
   1151 on_missing = "warn" if on_missing == "warning" else on_missing
   1152 if on_missing == "raise":
-> 1153     raise error_klass(msg)
   1154 elif on_missing == "warn":
   1155     warn(msg)

ValueError: At least one channel name in annotations missing from info: Fp1
```

### Additional information

Platform             Windows-10-10.0.19045-SP0
Python               3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)]
Executable           [c:\Users\_[USER]_\anaconda3\envs\Analysis\python.exe](file:///C:/Users/kinim/anaconda3/envs/Analysis/python.exe)
CPU                  Intel64 Family 6 Model 165 Stepping 2, GenuineIntel (12 cores)
Memory               15.9 GB

Core
├☑ mne               1.5.0
├☑ numpy             1.25.2 (unknown linalg bindings (threadpoolctl module not found: No module named 'threadpoolctl'))
├☑ scipy             1.11.2
├☑ matplotlib        3.7.2 (backend=QtAgg)
├☑ pooch             1.7.0
└☑ jinja2            3.1.2

Numerical (optional)
├☑ pandas            2.1.0
└☐ unavailable       sklearn, numba, nibabel, nilearn, dipy, openmeeg, cupy

Visualization (optional)
└☐ unavailable       pyvista, pyvistaqt, ipyvtklink, vtk, qtpy, ipympl, pyqtgraph, mne-qt-browser

Ecosystem (optional)
└☐ unavailable       mne-bids, mne-nirs, mne-features, mne-connectivity, mne-icalabel, mne-bids-pipeline

**Comment by larsoner** [comment]
@paulroujansky I suspect this is from https://github.com/mne-tools/mne-python/pull/11960, can you look?

**Comment by mscheltienne** [comment]
Probably a `self.set_annotations(annotations, on_missing="ignore")` in `RawEDF.__init__(...)`?

**Comment by paulroujansky** [comment]
I suspect that an annotation exists for a channel that is not actually present in the data and hence the info (Fp1). What you suggest @mscheltienne would do the work, yet I'd be happy to have a look in your file @tomasdominik to confirm, if you are okay with it of course

**Comment by mscheltienne** [comment]
> As a general question, does it make sense to have channel-specific annotations for channels that don't actually exist in the data?

Exactly. For me, it sounds like there was an issue with that file. It should not contain an annotation channel-specific for non-existing channels. `on_missing="warn"` would probably be more appropriate.

**Comment by paulroujansky** [comment]
I agree, I can make a PR reflecting that if you'd like

**Comment by tomasdominik** [comment]
@paulroujansky I am OK sharing the data privately with you. Please, visit my GitHub profile. You should find my my email address there.

I agree that the problem seems to be due to channel-specific annotations. It is probably because by default, my EEG device records bipolar channels referenced to CPz, so the default name for the Fp1 channel, for example, is "EEG Fp1-CPz".

**Comment by paulroujansky** [comment]
Oh I see, well then it actually makes sense to keep the original annotations.
