### ISSUE TITLE
Add mne.Forward.save and enable saving large Forward solution > 2 GB

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-python#12022]
### Description of the problem

Surprisingly, there is no method `Forward.save` to shortcut `mne.write_forward_solution`.
Also, I got a fairly large forward solution (don't ask..), and it does not fit in a single FIFF file, limited to 2 GB. The current writer is not able to write this forward solution.

**Comment by larsoner** [comment]
We could work out splitting but it would be a pain. Would HDF5 be okay like we added for source spaces in https://github.com/mne-tools/mne-python/issues/4831 ?

**Comment by mscheltienne** [comment]
HDF5 sounds good!
