### ISSUE TITLE
ENH: misc 5D beamforming improvements

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1203]
Here's an incomplete list:
- add parallelization support via joblib
- improve examples (no unit in colorbars, upper gamma is way too broad to be considered instructive)
- statistics example that shows how to define connectivity for cluster permutation tests
- differences between LCMV and DICS example (maybe filtering?, Dalal et al used a 200th order bandpass filter ...)

I just put this here so we don't forget.

cc @rgoj

**Comment by agramfort** [comment]
closing as too old. @britta-wstnr will do better soon
