### ISSUE TITLE
MNE edf exportation is very slow 

### ISSUE THREAD

**Issue by withmywoessner** [mne-tools/mne-python#12034]
### Describe the new feature or enhancement

Hello! I am using MNE to export some files to the edf format and I discovered that MNE's current implementation of edf exportation (using [EDFlib](https://www.teuniz.net/edflib_python/)) is very slow. I tested reading a file and exporting it to edf in MNE and using another library: [PyEDFlib](https://pyedflib.readthedocs.io/en/latest/). PyEDFlib was much faster. 
MNE:
<img width="485" alt="image" src="https://github.com/mne-tools/mne-python/assets/20428109/e219730c-6889-459b-bf68-aaf675a990cf">

PyEDFlib:
<img width="500" alt="image" src="https://github.com/mne-tools/mne-python/assets/20428109/83972cbf-96bc-4df6-9a68-aab897a5dc32">

### Describe your proposed implementation

I think I could rewrite the _edf.py module to use PyEDFlib. It shouldn't be too difficult as the project says it uses [EDFlib ](https://www.teuniz.net/edflib/)already.

### Describe possible alternatives

I could also try and make the current implementation of EDFlib more efficient so minimal changes are made. This may be a bit more time-consuming.

**Comment by cbrnr** [comment]
I've already noted this in #9883, please use that issue to continue the discussion. In general, I'm 👍 for either (1) replacing `edflib-python` with `pyedflib` or (2) adding `pyedflib` as a second backend for EDF export (which should be the default, and `edflib-python` could be the fallback if `pyedflib` is not available).
