### ISSUE TITLE
Lazy loading makes working with MNE-Python scripts in VS Code very awkward

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#12048]
Hello, I'm using VS Code with Pylance, and since lazy loading was introduced, using MNE is no fun at all anymore. It appears that Pylance doesn't know about any of those "lazy" imports, providing a subpar development experience:

<img width="656" alt="Screenshot 2023-10-02 at 13 49 07" src="https://github.com/mne-tools/mne-python/assets/2046265/67ce4bc1-b366-4415-a480-ad8d42ef9894">

Pylance is the default Python type & syntax checker in VS Code, which also provides completion suggestions etc.

A workaround could be to distribute (type) stubs via `typeshed`, which is [what TensorFlow does](https://github.com/microsoft/pylance-release/issues/3174) to deal with this exact same problem.

**Comment by hoechenberger** [comment]
Potential alternative approach:
https://github.com/microsoft/pylance-release/issues/474#issuecomment-706719841

**Comment by larsoner** [comment]
Closing as a dup of #12047 since I am pretty sure it will solve this problem (but we should definitely reopen this if it doesn't)

**Comment by hoechenberger** [comment]
Thanks @larsoner, I didn't realize you'd just opened this issue :)
