### ISSUE TITLE
ecog functionality?

### ISSUE THREAD

**Issue by choldgraf** [mne-tools/mne-python#1206]
hey folks - not sure if this is the right space to post this, so I apologize if it's not, but I wonder how you all feel about including electrocorticography analysis under the scope of this project. It's quite similar to EEG / MEG, so I imagine that it could mostly entail adding extra functions that do things ECoG people may care more about. 

Nothing concrete in mind yet, just want to know how you all feel about this, as I think this project looks great and would love to help out however I can.

**Comment by Eric89GXL** [comment]
I'm going to close this for now, @choldgraf I trust you will make issues and PRs now for the specific things of interest :)

**Comment by choldgraf** [comment]
Good idea - I still like all of these ideas and will work on them as the
semi-random process of my mind finds use :)

Chris
