### ISSUE TITLE
Sort imports?

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#12088]
I don't think we're currently sorting our imports. Black doesn't support sorting, but Ruff does when the `I` rule is enabled. Should we enable it (as part of our pre-commit hooks)?

**Comment by hoechenberger** [comment]
U don't see a reason that would speak against it! +1 from my side

**Comment by larsoner** [comment]
As long as we can preserve our current sorting order (standard libraries, other libraries, internal) and the CI solution is good (pre-commit in `ruff` or adding `isort` assuming it's fast enough) then sure. Any volunteer to work on this?

**Comment by cbrnr** [comment]
> As long as we can preserve our current sorting order (standard libraries, other libraries, internal)

Yes, that's what isort and ruff do.

> (pre-commit in ruff or adding isort assuming it's fast enough)

I'd use ruff since we already have it inspect the code anyway.

> Any volunteer to work on this?

I can submit a PR.
