### ISSUE TITLE
The name of functional label display

### ISSUE THREAD

**Issue by dongqunxi** [mne-tools/mne-python#1211]
Hi all,
After I made several labels with the help of freesurfer, I run kind of 
```ruby
brain.add_label()
```
to add them on the cortex, I want to display the name of them corresponding. How to do, Thanks.

**Comment by Eric89GXL** [comment]
You would use `src['rr']['vertno'][ii']` to get the 3D position.

**Comment by Eric89GXL** [comment]
or `src[0]['rr']['vertno'][ii']` for the left hemi and `src[1][...]` for the right
