### ISSUE TITLE
RFC: should we add raw.rescale() ?

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#12111]
On [the forum](https://mne.discourse.group/t/troubles-in-show-bdf-files/7670/2) today, @cbrnr noted that for users whose data files aren't in Volts,

> Unfortunately, there is no easy-to-find rescale method, but you can use:
> `raw.apply_function(lambda x: x * 1e-6, picks="eeg")`

This seems a common enough need that I wonder if we should make it easier via a public method. Possible APIs:

1. `raw.rescale(scaler: float, picks=None)`
2. `raw.rescale(from: str = 'uV', to:str = 'V', picks='eeg')`

open to other API ideas (assuming folks think it's a good addition in the first place)

**Comment by cbrnr** [comment]
Good idea. I like both APIs, so why not support both? Do we store the unit associated with a `Raw` object somewhere though? Then we could support a change of units. If not, we're stuck with the defaults (e.g. V for EEG), and in that case a rescaling factor makes more sense than from/to.

**Comment by scott-huberty** [comment]
> Do we store the unit associated with a `Raw` object somewhere though?

AFAIK I think Units are stored for each channel but only based off their channel type (i.e. yes EEG will always be Volts) ?:

https://github.com/mne-tools/mne-python/blob/875df8285e25ca4964566f2b900b808be65845d7/mne/_fiff/constants.py#L880-L931

From what I've seen on the forum, users usually want/need to rescale their data _to_ one of our default units (i.e. microvolts _to_ volts, etc), not the other way around?

**Comment by drammock** [comment]
On reflection it doesn't make sense to let users specify `to` parameter. So a better API would be

```py
raw.rescale(scaler: float|dict)
```
where float will error out if there is more than one channel type

**Comment by larsoner** [comment]
If we want to get (maybe too) clever about it we could make the values of the `scaler` dict not just float (multiply directly) but also possible string, so if you pass `scaler=dict(eeg='uV')` it's a way of saying "my EEG channels are currently in µV, convert them to SI units", i.e., the same thing as passing `scaler=dict(eeg=1e-6)`.

**Comment by drammock** [comment]
> If we want to get (maybe too) clever about it we could make the values of the `scaler` dict not just float (multiply directly) but also possible string, so if you pass `scaler=dict(eeg='uV')` it's a way of saying "my EEG channels are currently in µV, convert them to SI units", i.e., the same thing as passing `scaler=dict(eeg=1e-6)`.

That seems very usable, but a little too magic?  Or maybe just the right amount of magic. I think we already have the machinery to convert unit strings to float multiplier values, so it's not a very big lift in terms of coding / maintenance. Maybe a good candidate for the Nov sprint if nobody picks it up before then.

**Comment by mscheltienne** [comment]
It might be better to allow a per-channel setting, e.g. by using a syntax similar to `.set_channel_types` with a mapping dictionary `dict(ch_name=scaling)`.

**Comment by drammock** [comment]
> It might be better to allow a per-channel setting, e.g. by using a syntax similar to `.set_channel_types` with a mapping dictionary `dict(ch_name=scaling)`.

Do you mean different scales for individual _channels_? or just for each channel _type_? If you meant channel type, that's what I was trying to suggest above https://github.com/mne-tools/mne-python/issues/12111#issuecomment-1764995471

**Comment by hoechenberger** [comment]
@drammock I'd love to see auch a method implemented. @cbrnr talked about this actually just last week and we both thought it could make things easier for some users.

**Comment by hoechenberger** [comment]
Also I believe we'd only need to support EEG channels

I can't remember support requests for other types of data

**Comment by hoechenberger** [comment]
> If we want to get (maybe too) clever about it we could make the values of the `scaler` dict not just float (multiply directly) but also possible string, so if you pass `scaler=dict(eeg='uV')` it's a way of saying "my EEG channels are currently in µV, convert them to SI units", i.e., the same thing as passing `scaler=dict(eeg=1e-6)`.

It might just be be but I find the string syntax confusing

**Comment by cbrnr** [comment]
> It might just be be but I find the string syntax confusing

I agree, it's probably too much. We're setting us up for questions like does it convert *from* or *to* µV. Also, applying this more than once will also be confusing (there is an issue about something similar here, which might or might not be relevant).

**Comment by mscheltienne** [comment]
I was suggesting individual channels, but I agree that simplicity is better. The syntax `scaler=dict(eeg=1e-6)` is sufficient and any unsupported use case can use `apply_function`.

**Comment by drammock** [comment]
OK consensus seems to be around
 
> ```python
> raw.rescale(scaler: float|dict)
> ```

- passing a float will error out if there is more than one channel type
- if passing a dict, keys are channel type strings

if there is more than one channel type and `scaler=dict(eeg=1e-6)` I think we should *not warn/error* but rather leave non-EEG channels unchanged.

**Comment by larsoner** [comment]
Agreed @drammock

**Comment by mscheltienne** [comment]
> Good idea. I like both APIs, so why not support both? Do we store the unit associated with a Raw object somewhere though? Then we could support a change of units. If not, we're stuck with the defaults (e.g. V for EEG), and in that case a rescaling factor makes more sense than from/to.

@cbrnr Also, if you want to, you could use the FIFF unit multiplier which at the moment we always set to 0: https://github.com/mne-tools/mne-python/blob/b3eb56cf1e8993940daa1df68d5220f3110ecdbb/mne/_fiff/constants.py#L970-L1011
