### ISSUE TITLE
Small error in interpolation tutorial

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#12158]
### Proposed documentation enhancement

https://mne.tools/dev/auto_tutorials/preprocessing/15_handling_bad_channels.html#interpolation-in-mne-python

Says:

> Note that we used the exclude=[] trick in the call to [pick_types()](https://mne.tools/dev/generated/mne.io.Raw.html#mne.io.Raw.pick_types) to make sure the bad channels were not automatically dropped from the selection.

But `pick_types()` isn't used anymore (we switched to `inst.pick()`)

**Comment by btkcodedev** [comment]
@hoechenberger  i am a newbie for this repo, could i work on this issue :)

**Comment by hoechenberger** [comment]
Absolutely! Feel free to ask if you have any questions 👌

**Comment by btkcodedev** [comment]
Hi, @hoechenberger, I've raised MR https://github.com/mne-tools/mne-python/pull/12326
