### ISSUE TITLE
error code for example

### ISSUE THREAD

**Issue by PhD-GOAT** [mne-tools/mne-python#12170]
### Proposed documentation enhancement

https://mne.tools/stable/auto_tutorials/clinical/60_sleep.html#design-a-scikit-learn-transformer-from-a-python-function

```
a=eeg_power_band(epochs)
a.shape
```

This is shown to return the shape of (n, 5). 5 is probably the frequency band. Here, 5 bands are defined, but I come up with 10.

![image](https://github.com/mne-tools/mne-python/assets/93689515/32f64c82-e94a-41d4-9610-3648d1a4b859)

**Comment by agramfort** [comment]
fixed in https://github.com/mne-tools/mne-python/pull/12171
