### ISSUE TITLE
Add Star History to readme?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#12180]
### Proposed documentation enhancement

I just came across this:
https://star-history.com/#mne-tools/mne-python&Date

I think it could be fun to showcase in our readme. WDYT?

<img width="728" alt="Screenshot 2023-11-07 at 13 27 08" src="https://github.com/mne-tools/mne-python/assets/2046265/72af12d1-7ace-4cd3-8842-7c01dafe1ad0">

**Comment by cbrnr** [comment]
Looks fun, but without comparing to another (similar) project, it isn't really that informative. Or why would anyone (except us devs) be interested in the time course of our stars?

**Comment by hoechenberger** [comment]
I thought it shows continuing popularity :)

**Comment by drammock** [comment]
to me this conveys information more similar to what is on the "insights" tab of the repo. I don't think it's appropriate for the README
