### ISSUE TITLE
Pylance doesn't know about datasets.sample.data_path()

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#12241]
### Description of the problem

Pylance claims that `mne.datasets.sample.data_path()` is an unknown entity:
![signal-2023-11-25-144641_002](https://github.com/mne-tools/mne-python/assets/2046265/cd44f243-d55c-4d16-8d4f-8e5b2053a5c6)

### Steps to reproduce

```Python
import mne
mne.datasets.sample.data_path()
```

### Expected results

Editor would offer auto-completion and docstrings

### Actual results

Editor doesn't know about `data_path()`

### Additional information

This is on `main`. Problem has existed already before we moved to lazy loading. I tried getting to the bottom of this but I really don't understand what's going on here. No problems at runtime. Applies to all datasets, not only `sample`.

**Comment by hoechenberger** [comment]
I'm seeing something similar for `mne.io.read_raw_fif()`, but not for `mne.io.read_raw()`:
<img width="773" alt="Screenshot 2023-11-25 at 15 48 52" src="https://github.com/mne-tools/mne-python/assets/2046265/97291a0a-920a-4732-b0c3-63c562ff627f">

**Comment by hoechenberger** [comment]
Can only be reproduced if working in a VS Code workspace that doesn't have the `mne-python` folder open. E.g., do `code /tmp/mwe.py`

**Comment by cbrnr** [comment]
As we've just discussed, this works for me... even in a different workspace.

**Comment by hoechenberger** [comment]
It seems the problem was in fact related to some type stubs floating around somewhere, so most probably not a bug in MNE or VS Code per se!
