### ISSUE TITLE
Starting iPython with ipython -pylab -qt

### ISSUE THREAD

**Issue by Mensen** [mne-tools/mne-python#1225]
In the tutorial it advises the user to start iPython using 

`$ ipython -pylab -qt`

However, this no longer works and should be (at least on a linux machine)

`$ ipython --matplotlib=qt`

Correct me if I'm wrong :)

**Comment by jona-sassenhagen** [comment]
pylab mode is disprefered anyways isn't it?

**Comment by agramfort** [comment]
yes the recommended way now is --matplotlib
