### ISSUE TITLE
missed deprecation changes

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#12273]
I stumbled upon this today, which should have changed between 1.5 and 1.6:

https://github.com/mne-tools/mne-python/blob/7bf1b4ab70404a9f0b3cf00783a06e1ce9e0c272/mne/_fiff/pick.py#L310-L337

change probably should be backported. I've tweaked the release wiki's deprecation section to include a reminder about searching for `FutureWarning`s

**Comment by hoechenberger** [comment]
I don't think we should ever backport a forgotten API change. This violates semantic versioning.
