### ISSUE TITLE
Using an automated approach to coregistration，How to use my own MEG data and fsaverage template for automatic registration?

### ISSUE THREAD

**Issue by Sarahsus** [mne-tools/mne-python#12328]
### Proposed documentation enhancement

This tutorial gives an example, but when I use this code, I cannot use it for matching MEG data and fsaverage templates. This code does not support reading bem of fsaverage templates. I want to get a tutorial on automatic matching of MEG and fsaverage, which is very grateful！

**Comment by agramfort** [comment]
@Sarahsus this is not a bug report but a user question. You should use the user forum https://mne.discourse.group to get help here.
