### ISSUE TITLE
Wrong latest version on mne.tools?

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#12365]
Why does [mne.tools](https://mne.tools/stable/index.html) state that 1.6.1 is the latest version, when the latest release on GitHub and PyPI is 1.6.0?

![image](https://github.com/mne-tools/mne-python/assets/4377312/06d6eea0-5356-4efe-959f-55e14b1044ec)

**Comment by larsoner** [comment]
I pushed a version bump in anticipation of cutting a 1.6.1. @drammock okay to release it? It contains a fix for PyVista removing a kwarg without deprecation (so 1.6.0 can't work with latest pyvista release at the moment).

**Comment by drammock** [comment]
> I pushed a version bump in anticipation of cutting a 1.6.1. @drammock okay to release it? 

sure
