### ISSUE TITLE
Consider removing jinja2 from `mne.sys_info()`

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#12387]
We've had many discussions on how we should handle dependencies, but given that we currently only include absolutely essential packages as core dependencies, I was wondering why we include `jinja2`. In my opinion, it would be better (more consistent) to make it an optional dependency. In addition, it is only imported in one location (`mne/html_templates/_templates.py`), and even there it is a nested import.

**Comment by drammock** [comment]
I'm pretty sure this has been discussed before, can you provide a cross ref to the past discussion(s)?

**Comment by cbrnr** [comment]
😄 yes, it was me who asked this question before in #11559. Apparently, it still bothers me, but I guess your opinions won't have changed, so feel free to close.

**Comment by cbrnr** [comment]
I think I know what bothers me: listing `jinja2` and `pooch` in the "Core" section of the output of `mne.sys_info()`. This doesn't really make sense, so what about removing these two packages from the section? We don't include `lazy-loader` either (which makes sense).

**Comment by hoechenberger** [comment]
Good idea to make the core deps section smaller by narrowing it down to the essentials  👍

**Comment by drammock** [comment]
I'm open to that. Where should they go instead if not in "core"?

-------- Original Message --------

**Comment by cbrnr** [comment]
Nowhere, or to a new section called "infrastructure" or something like that.
