### ISSUE TITLE
read should have mne.io.read_raw_fif

### ISSUE THREAD

**Issue by PN20** [mne-tools/mne-python#12395]
At this link 
https://mne.tools/stable/auto_tutorials/io/10_reading_meg_data.html#sphx-glr-auto-tutorials-io-10-reading-meg-data-py

Now 
original_data = mne.io.read_raw_fiff('original_data.fif', preload=False)

Correct
original_data = mne.io.read_raw_fif('original_data.fif', preload=False)

May be a typo

**Comment by drammock** [comment]
The text mentioned does not l occur on the linked page. Also the suggested correction is the same as the alleged problem.
