### ISSUE TITLE
Add more numerical measures to quantify Event Related Potentials 

### ISSUE THREAD

**Issue by withmywoessner** [mne-tools/mne-python#12406]
### Describe the new feature or enhancement

I would like to add the following measures for ERP analysis:

- Mean amplitude
- Area amplitude (all positive, numeric integration)
- Fractional area latency
- Fractional peak latency

I also plan on add documentation for this to:
https://mne.tools/dev/auto_tutorials/evoked/30_eeg_erp.html

### Describe your proposed implementation

I would like to implement these as new functions within `evoked.py`

### Describe possible alternatives

Maybe these can be implemented easily using existing API??

**Comment by drammock** [comment]
relevant cross-refs:

- #7848 
- #10647
