### ISSUE TITLE
ENH: add current density distribution CSD laplace transform

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1240]
Useful for improving accuracy of topomaps in EEG + improves decoding results

**Comment by agramfort** [comment]
@dengemann any progress here?

**Comment by agramfort** [comment]
@dengemann any progress here?

**Comment by dengemann** [comment]
nope. no fix in sight.

**Comment by agramfort** [comment]
can you share some code? Maybe someone can help...

**Comment by eort** [comment]
A year ago I was working on a python implementation of a CSD (based on Perrin, 1987). For that, I orientated myself at a Matlab version of it, written by Mike X. Cohen (University of Amsterdam) described in his book [Analyzing neural time series data](http://www.mikexcohen.com/). Unfortunately, thesis-related time pressure forced me to quit before I could finalize it. As far as I remember, it worked up to the point where the G and H matrix were calculated. After that funny things started happening, to the end that the algorithm did rotate the layout by 90°. 
If interested, I could share what I have so far. I was also planning to resume working on it within a couple of months, but it doesn't have highest priority right now, so it could take quite a while.

**Comment by dengemann** [comment]
@eort I have a working and tested CSD version which I did not contribute here becasue it depends on the lookuptables provided by the original toolbox. I initially wanted to add it here but decide not to do so as I did not find a way to replace the lookup table approach with actually computing the spherical coordinates from the sensors. The annoying thing is to get the coordinates into the coordinate system used by the original code that is defined by a particular montage.

**Comment by eort** [comment]
I might miss here something, but isn't possible to use the coordinates in  `raw.info` for that matter? At least that's what I thought I was doing. But I have to admit I'm not very familiar with different coordinate system and such things.

**Comment by dengemann** [comment]
> I might miss here something, but isn't possible to use the coordinates in raw.info for that matter? At least that's what I thought I was doing. But I have to admit I'm not very familiar with different coordinate system and such things.

No it's in fact more complicated. See documentaiton of the matlab toolbox on the coordinate system. And just projecting the sensors on spherical coordinates is not enough. Currently we're simply using the lookup tables to get the expected coordinates for a sensor. But this is of course not satisfying for MNE-Python standards as this limits the use of this code to certain EEG montages.

**Comment by eort** [comment]
Ah, too bad. Never mind then.

**Comment by dengemann** [comment]
We could make the code availble though. MNE-Python currently ships the EGI
sensor CSD tables:

https://github.com/mne-tools/mne-python/blob/master/mne/channels/data/montages/EGI_256.csd

So that would work out of the box. Which system are you using?


2015-07-06 11:10 GMT+02:00 eort <notifications@github.com>:

**Comment by eort** [comment]
Biosemi with 128 channels.

**Comment by dengemann** [comment]
You neet to look into the lookuptable from the original toolbox to see if you can get a mapping (or find a way to compute the coordinates ;)

**Comment by eort** [comment]
Thanks, I'll try that (at some point in the distant future...)

**Comment by kazemakase** [comment]
Hey, guys! Long time no see :)

I found a rather neat way to warp any EEG layout to a sphere, as required by the CSD splines.
It takes the XYZ-Coordinates of the sensors and transforms them to the surface of a unit sphere (while minimizing displacement in the original coordinate space).

When testing is done I'll put it into the SCoT repo sooner or later. If you're interested I'll put it up sooner :)

**Comment by agramfort** [comment]
L
> Hey, guys! Long time no see :)
> 

Indeed ;)
> I found a rather neat way to warp any EEG layout to a sphere, as required by the CSD splines.
> It takes the XYZ-Coordinates of the sensors and transforms them to the surface of a unit sphere (while minimizing displacement in the original coordinate space).
> 
> When testing is done I'll put it into the SCoT repo sooner or later. If you're interested I'll put it up sooner :)
> 
Sooner is always better

**Comment by kazemakase** [comment]
> Sooner is always better

Right. See here: https://github.com/scot-dev/scot/pull/60

**Comment by agramfort** [comment]
looks clean and simple !

Let's wait for @dengemann to come back from his summer break.

**Comment by jona-sassenhagen** [comment]
@dengemann you still on this? :)

**Comment by dengemann** [comment]
@jona-sassenhagen nothing changed here, with @fraimondo  I maintain code for our team which unfortunately does not support other EEG caps than the ones supported by the CSD toolbox. If there is some interest in moving on from there, maybe taking into account @mbillingr 's recent developments, I'm happy to open a WIP PR.

**Comment by Eric89GXL** [comment]
@dengemann do we still need CSD?

**Comment by dengemann** [comment]
Not for me. And we have it locally. The problem was about recomputing the
CSD tables if you don't have the right coordinates. Fine with me to close
this for now.
