### ISSUE TITLE
MNE Recreations of EEGLAB processing pipelines 

### ISSUE THREAD

**Issue by withmywoessner** [mne-tools/mne-python#12435]
### Proposed documentation enhancement

A while ago I was trying to recreate an EEGLAB Time-Frequency analysis pipeline in MNE and was having trouble getting my results to match. I made a forum post related to one of the MNE TFA parameters as well. See [link](https://mne.discourse.group/t/help-understanding-tfr-n-cycles/7257). The answer was very helpful, but I still had trouble getting my results to match.

I was wondering if I (and others if anyone who is well versed in EEGLAB wants to help) could create some examples of showing how to recreate results from EEGLAB step-by-step.

**Comment by drammock** [comment]
crossref: #10750. Anyone interested in advancing this effort should comment there, not here.
