### ISSUE TITLE
Test on Apple Silicon via GH-hosted runner

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#12449]
GitHub Actions now provides a runner on Apple Silicon via the `macos-14` platform specifier, see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

**Comment by larsoner** [comment]
Indeed 🙂 

https://github.com/mne-tools/mne-python/blob/614424718fa911cc0cfacc0df85652b3efaee358/.github/workflows/tests.yml#L65
