### ISSUE TITLE
ENH: Add tutorial on narrowband filters using real data

### ISSUE THREAD

**Issue by alexrockhill** [mne-tools/mne-python#12458]
### Describe the new feature or enhancement

I think it would be nice to have an example or tutorial looking at filters on real data in order to look at task-based differences, not just preprocessing.

### Describe your proposed implementation

I think people might really benefit from seeing FIR vs IIR and the parameters and their effect on something well documented like movement-related beta in the bci dataset.

### Describe possible alternatives

There are other datasets, maybe visual alpha or an auditory biomarker that could make sense.

### Additional context

Does this exist anywhere and I'm just missing it? And do others think this would be useful?

I know there is a lot of background on constructing filters and the properties like ringing but as far as I know, I haven't seen that put to a practical example use case.

**Comment by agramfort** [comment]
maybe a great blog post first?

**Comment by alexrockhill** [comment]
Sounds good, will link to it in this issue and then we can decide whether to add it to documentation
