### ISSUE TITLE
DOC: Show documentation for inherited methods in derived classes

### ISSUE THREAD

**Issue by mluessi** [mne-tools/mne-python#1245]
When using derived classes, only the methods of the child class, not the parent class are documented. An example is `Epochs`, which is derived from `_BaseEpochs` :

http://martinos.org/mne/dev/generated/mne.Epochs.html#mne.Epochs

The sphinx doc should show all the inherited methods.

**Comment by teonlamont** [comment]
i think this has been addressed from what i've checked. @mluessi, can you confirm?

**Comment by Eric89GXL** [comment]
Looks good in the dev docs
