### ISSUE TITLE
EDF reader intermittent CI failure

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#12468]
We have a test failure happening that can only fail on Feb 29 of a leap year 😂 

https://github.com/mne-tools/mne-python/blob/f2fa901ca6f87eaadca6acd45f4c460f1c92f8fe/mne/io/edf/edf.py#L1269-L1272

We're using `datetime.now()` and then trying to change the year to a non-leap year a few lines down.

cc @nbara and @SveaMeyer13 --- I'll handle fixing it but I thought you might get a chuckle out of this since you're the last two folks to have touched the relevant lines

**Comment by nbara** [comment]
Haha, leap day bug making its quadrennial appearance! Thanks for fixing @drammock 😄
