### ISSUE TITLE
BUG: EpochsTFR bug popping up in MNE-BIDS-Pipeline

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#12512]
@drammock see https://app.circleci.com/pipelines/github/mne-tools/mne-bids-pipeline/4395/workflows/4c871947-2971-4fca-8d92-b7a2892c91db/jobs/62041

To reproduce you can `pip install -e .` mne-bids-pipeline and do (it will download some GB of data to `~/mne_data`):
```
pytest --download mne_bids_pipeline/ -k 247 --pdb
```

**Comment by drammock** [comment]
I think I found the issue. will open a PR shortly.
