### ISSUE TITLE
Complete uninstall documentation missing 

### ISSUE THREAD

**Issue by sreekarchigurupati** [mne-tools/mne-python#12528]
### Proposed documentation enhancement

For installations on linux using "sh ./MNE-Python-1.6.1_0-Linux.sh", there is no documentation to uninstall the application completely. doing "pip uninstall mne" only removes the package and not the conda environment auto created.

**Comment by larsoner** [comment]
Cross-ref https://github.com/mne-tools/mne-installers/issues/89

The short version is that deleting the installation directory, possibly modifying your `.bashrc` (or equivalent for your shell), and deleting some `~/.local/share/applications/mne-python-*.desktop` files should do it.

**Comment by larsoner** [comment]
... but yes +1 for adding this to https://github.com/mne-tools/mne-python/blob/main/doc/install/installers.rst which renders to https://mne.tools/dev/install/installers.html#installers
