### ISSUE TITLE
Incorrect rendering of embedded HTML title (?)

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#12553]
### Proposed documentation enhancement

See e.g. https://mne.tools/dev/auto_tutorials/intro/70_report.html

<img width="1352" alt="Screenshot 2024-04-19 at 16 01 20" src="https://github.com/mne-tools/mne-python/assets/2046265/d0da57b2-7de1-4303-929e-0c653a512c46">

**Comment by drammock** [comment]
bug is there in stable docs too 😢

**Comment by hoechenberger** [comment]
Changing the `flex-direction` of `p.rubric` from `column` to `row` fixes the problem for me:

<img width="819" alt="Screenshot 2024-04-28 at 16 11 25" src="https://github.com/mne-tools/mne-python/assets/2046265/872ff24d-3699-43fc-ab05-99941923a2af">

**Comment by hoechenberger** [comment]
When I simply drop the `p.rubric` styling altogether it looks as intended:

<img width="819" alt="Screenshot 2024-04-28 at 16 13 34" src="https://github.com/mne-tools/mne-python/assets/2046265/225d153f-38a5-4c4e-97f7-f715d1fa2f83">

**Comment by hoechenberger** [comment]
That may need fixing in pydata-sphinx-theme
