### ISSUE TITLE
Can we disable the "Back to top" button in the docs?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#12685]
It's constantly obstructing part of the content I want to read – I like reading lines close to the bottom of my screen, don't ask me why, I assume my vision is slightly better in this area. Anyway, it's super irritating this thing constantly appears and disappears, based on if and how and in which direction I'm scrolling. FYI I've not used a mouse in like 15 years, I do everything with a trackpad, because it makes pixel-precise scrolling so easy – so I tend to scroll a lot, often in tiny increments. The "Back to top" link is super not great for me. And I've never ever used it – if I want to scroll to the top, I do a swift swipe on my trackpad and voila, top of the page.

Alternative proposal if we want to keep it:
Do not display it conditionally (i.e., always show it, never hide it), and ensure it doesn't overlap with content.

Thoughts on this?

<img width="667" alt="Screenshot 2024-06-26 at 20 04 04" src="https://github.com/mne-tools/mne-python/assets/2046265/f9b5f21d-769e-4150-aeac-fdc0b51abe6d">

**Comment by cbrnr** [comment]
I find this annoying too, 👍 to remove it.

**Comment by drammock** [comment]
It's configurable, can be disabled in conf.py

Also on my list of things to tweak about how we use the theme. Will do when back from holidays; feel free to do it yourselves first if you don't want to wait
