### ISSUE TITLE
Dozens of symbols in `mne.utils` are unknown to my static type checker, probably due to an issue with lazy loading

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#12715]
### Description of the problem

Lots of functions imported from `mne.utils` allegedly don't exist according to Pylance; however, they **are** there, but obviously the static type checker cannot find them. For example here's what I see for a bunch of functions imported from `utils.check` and `utils.numeric`:
<img width="761" alt="Screenshot 2024-07-15 at 11 54 27" src="https://github.com/user-attachments/assets/087d81ef-7bd5-46fd-a88f-7b1fe5cb0ee9">

Red lines – Import not found

I took a look at `utils.pyi` and here, a large portion of imports is just black (i.e., not linked to the imported object because it couldn't be found):

<img width="669" alt="Screenshot 2024-07-15 at 11 51 21" src="https://github.com/user-attachments/assets/800cf476-3b94-450d-b175-6efdac9ab2ed">

### Steps to reproduce

```Python
See above
```

### Expected results

Static type checker should be aware of the imported objects

### Actual results

Static type checker cannot find the imported objects

### Additional information

This is with `main` and latest VS Code, VS Code Python, and Pylance extensions.

It's super difficult for me to do dev work when things are like this.

I didn't check any other modules.

**Comment by cbrnr** [comment]
This might be an issue related to your particular setup/config, because it works for me...

**Comment by hoechenberger** [comment]
How did you install MNE and from what directory are you working / invoking VS Code?

**Comment by cbrnr** [comment]
MNE is installed from my up-to-date local clone via `pip install -e .`, and I've set my project directory to the root of the MNE clone.

**Comment by hoechenberger** [comment]
Thanks for checking this, @cbrnr!
I completely re-created my env and now it's working again, so not an MNE bug after all – great! Sorry for the noise.
