### ISSUE TITLE
Bug reading raw BrainVision data 

### ISSUE THREAD

**Issue by meszabi** [mne-tools/mne-python#12745]
### Description of the problem

Got this error randomly:

"RuntimeError: Incorrect number of samples (0 != 36566600), please report this error to MNE-Python developers"

Second time I tried opening the same dataset it worked. Decided to report it anyway because the error message told me to...

### Steps to reproduce

```Python
raw = mne.io.read_raw_brainvision(vhdr_file, preload=True)
```

### Expected results

0

### Actual results

0

### Additional information

0

**Comment by larsoner** [comment]
Thanks for the report! That's odd behavior. If it comes up again feel free to share the file and hopefully someone else can reproduce the issue. For now I'm going to close because it sounds like it might already be fixed/working.
