### ISSUE TITLE
interpolate_blinks docstring should mention the method of interpolation

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-python#12753]
### Proposed documentation enhancement

https://mne.tools/stable/generated/mne.preprocessing.eyetracking.interpolate_blinks.html currently says:

> Interpolate eyetracking signals during blinks. This function uses the timing of blink annotations to estimate missing data. Operates in place.

and 

> If False, only apply interpolation to 'pupil channels'. If True, interpolate over 'eyegaze' channels as well. Defaults to False, because eye position can change in unpredictable ways during blinks.

Under the hood, https://numpy.org/doc/stable/reference/generated/numpy.interp.html is being used. So I would assume fixing the status quo is as easy as specifying "linear interpolation".

I think it's important to mention this, because there are many different eye-tracking interpolation methods out there.

**Comment by scott-huberty** [comment]
Thanks for bringing this to attention @sappelhoff ! Yes, we just used a linear interpolation (my bad for forgetting to document that...). I can open a PR on Monday if no one else beats me to it.
