### ISSUE TITLE
ENH: add plotting method / function for global field power

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1276]
Since we're polishing our sensor space / EEG edge I thought it would be time for it.
Like here: https://gist.github.com/dengemann/deb5e011d7d6b0c60fa9

cc @agramfort

**Comment by agramfort** [comment]
ping @teonlamont

**Comment by teonlamont** [comment]
haha, I had the same idea and forgot about it. seems like this could address https://github.com/mne-tools/mne-python/issues/1939. It could be combined with @jona-sassenhagen's suggestion for auto plotting predefined rois, etc.

**Comment by Eric89GXL** [comment]
Do we need this even though we have the GFP? (We have the GFP right?) If it's about selecting a subset of sensors, can't they do `evoked.pick_types(...)` or `evoked.pick_channels(...).plot_white()` now?

**Comment by teonlamont** [comment]
ideally, I would like to have some very simple ways to plot contrasts in sensor space. in the way of ERP analysis, it is useful to be able to do one of the following, for a given set of contrasts, e.g. evoked a, and evoked b:
1. select a single channel and plot the contrast of evoked a and evoked b
2. select a region of interest (pick several channels) and plot the contrast. for ERP, plot the average over the channels, for ERF, plot the RMS of the channels.
3. split the channels into pre-defined regions and plot the contrast. ERP, average, ERF, RMS.
(minor addition, the ability to flip the axes for ERPs to be à la mode)

This would be a simple but pretty use addition. it doesn't have to be wrapped in the `plot_gfp`.  it could be something like `plot_contrasts`. It's very useful with teaching, and it is still useful with ERP-related research.

**Comment by agramfort** [comment]
GFP is independent of noise cov for the common use case.

**Comment by Eric89GXL** [comment]
@teonlamont can you open a different issue for that, then? The title and most of the discussion of this one is a bit confusing. 

@agramfort so you're saying we still need a separate function to plot the GFP?

**Comment by teonlamont** [comment]
ok, i just reopened the one I closed. this topic is mostly about gfp, but there were mentions of a general plotting function. so it seemed like this might be a relevant topic

**Comment by agramfort** [comment]
>
> @agramfort <https://github.com/agramfort> so you're saying we still need
> a separate function to plot the GFP?
>
I would add it to plot evoked method. A green line like brainstorm does it.

http://neuroimage.usc.edu/brainstorm/Tutorials/TutSourceEstimation?action=AttachFile&do=get&target=sources1.gif

**Comment by Eric89GXL** [comment]
Does anyone have time for this one?

**Comment by dengemann** [comment]
I'm +0 on this ... We should mark it 0.10, my 2 cents.

**Comment by Eric89GXL** [comment]
Done, if someone feels passionately about it, let them be the one to implement it for 0.9 :)

**Comment by adykstra** [comment]
What would this entail?  Just a gfp trace at the bottom of <code>evoked.plot()</code> and/or a separate gfp plotting method for <code>Evoked</code> objects?  Are we talking the traditional definition from Lehmann and Skrandies using spatial variance?  I've been computing this a lot recently, so it would be relatively straight forward to implement I think.  I would propose the following:

1. An option to <code>evoked.plot()</code> called <code>gfp</code>, defaulted to <code>False</code>.  So the call <code>evoked.plot(gfp=True)</code> would produce the brainstorm-like plot that @agramfort mentions.

2. An <code>Evoked</code> method called <code>plot_gfp</code>, so that the call <code>evoked.plot_gfp()</code> would return only the gfp and not the butterfly.  Perhaps also an optional <code>cov</code> arg, defaulted to <code>None</code> that, if passed, would whiten the <code>Evoked</code> first?  I guess that's maybe not necessary since we already have <code>mne.whiten_evoked()</code>.

**Comment by teonlamont** [comment]
+1 for 1.

**Comment by dengemann** [comment]
We have 2 already, `evoked.plot_white`

**Comment by adykstra** [comment]
> We have 2 already, evoked.plot_white

I was wondering about that,  but wouldn't it make sense to have a basic method for <code>Evoked</code> objects for plotting just the gfp?

**Comment by adykstra** [comment]
@teonlamont, are you indifferent or -1 on suggestion 2?

**Comment by dengemann** [comment]
I wanted to say that would be complementary.

**Comment by agramfort** [comment]
+1 for 1

plot_white is using a noise cov which makes it different.

**Comment by teonlamont** [comment]
how about gfp = True/False/'only'

**Comment by agramfort** [comment]
I'd start with True/False but whatever

**Comment by dengemann** [comment]
Do we really need to keep adding stuff just shortly before releasing?
We used to have a 2 week feature addition stop and usually many bugs
emerged and were fixed after that point.
Would it make sense to release in one or two weaks but stop with
implementations of whatever in 2 days?

2015-04-23 14:51 GMT+02:00 Alexandre Gramfort <notifications@github.com>:

**Comment by agramfort** [comment]
+1000

this was not suggested for 0.9

**Comment by dengemann** [comment]
Ah ok. Sorry then. Anyways. We should stop pushing features and spend more days on bug search and fixing.

**Comment by adykstra** [comment]
> Do we really need to keep adding stuff just shortly before releasing?

Doesn't matter to me whether this goes into 0.9 or not - just thought that since no one was picking it up I could.  

I'm gathering that folks are -1 on creating separate gfp plots?  That would actually be my main use case, as opposed to including it at the bottom of an evoked butterfly plot.

**Comment by teonlamont** [comment]
@adykstra that's why I suggesting an option to gfp that if it is 'only', then it would plot just the gfp and not the butterfly plot. since it's in evoked.plot, it would save on a separate method.

**Comment by Eric89GXL** [comment]
Would `gfp=True | False | 'only'` work for your case @adykstra?

**Comment by adykstra** [comment]
Definitely, but a separate method to accomplish it seems cleaner and more explicit to me.  I'd be happy with either though.

**Comment by Eric89GXL** [comment]
I think the push to avoid more functions will make it easier just to have a param. @adykstra you up for making a PR? It may or may not make it into 0.9 depending on what we decide regarding a feature freeze, but it sounds like we want it eventually regardless.

**Comment by adykstra** [comment]
> you up for making a PR?

Sure.

**Comment by adykstra** [comment]
@dengemann, regarding rank, is <code>estimate_rank</code> from <code>mne.utils</code> sufficient?  For the example data, it returns 67 (65) for grads (mags), and 58 for eeg.  Also, if I understand correctly, the rank of SSS'd MEG data should be estimate jointly for grads and mags?  So ... <code>estimate_rank(evoked.pick_types(meg=True).data)</code>?

**Comment by dengemann** [comment]
Rread the source code of evoked.plot_white and find the answers :)
We have special private functions.
