### ISSUE TITLE
Typo in SSD documentation 

### ISSUE THREAD

**Issue by SHEscher** [mne-tools/mne-python#12807]
### Proposed documentation enhancement

Instead of "Spectro-Spatial Decomposition" it should be "spatio-spectral decomposition" 

https://mne.tools/dev/auto_examples/decoding/ssd_spatial_filters.html#compute-spectro-spatial-decomposition-ssd-spatial-filters

**Comment by larsoner** [comment]
@SHEscher would you be up for making a PR to fix it?
