### ISSUE TITLE
DOC: docstr for `raw.get_montage` does not make sense

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-python#12824]
https://github.com/mne-tools/mne-python/blob/ac2c4c0d72f9843690aad70e63b48269f5269a0f/mne/_fiff/meas_info.py#L317

see: https://mne.tools/stable/generated/mne.io.Raw.html#mne.io.Raw.get_montage

![image](https://github.com/user-attachments/assets/576fbb6f-fb15-4e95-8e24-47857e3c5c29)

☝️ The description is as if this were a parameter, not a return value. Furthermore, it should specify that this returns a copy of a montage, so modifying this in any way won't have an impact on the raw instance from which it is obtained.

**Comment by larsoner** [comment]
Agreed!
