### ISSUE TITLE
How to cancel the labeling of trigger channel

### ISSUE THREAD

**Issue by baili-b7ack** [mne-tools/mne-python#12876]
I was using Curry 8 along with E-Prime 3, and was trying to add customized labels to eeg scroll. But it seems that with trigger channel, it has its own way of labelling events, and those labels overlapped with the label I set up and the scroll looks messy. (like the pic given)
![eeg-scroll](https://github.com/user-attachments/assets/2de4965f-1bc7-41ca-9a9e-9a04533cf25d)
PS: Thinking that I was just doing trial so I didn't really take the scroll under real experiment scene, just letting it run without a human head under (?

Is there a way to stop the automatic labelling of trigger channel?

**Comment by mscheltienne** [comment]
Hello, I do not understand what you mean by automatic labeling, or how you got this plot.

**Comment by mscheltienne** [comment]
This plot is not related to MNE-Python? Neither is any of the parts you are mentionning so far?

**Comment by baili-b7ack** [comment]
Oops, I'm sorry, I don't know where to submit this and while googleing for answer I found issues seemingly related to Curry software in this project, so I submitted this issue. Sorry for interrupting. ><

**Comment by baili-b7ack** [comment]
> This plot is not related to MNE-Python? Neither is any of the parts you are mentionning so far?

Oops, I'm sorry, I don't know where to submit this and while googleing for answer I found issues seemingly related to Curry software in this project, so I submitted this issue. Sorry for interrupting. ><

**Comment by drammock** [comment]
If your plot is generated by the curry reader package, try submitting the issue here: https://github.com/neuroscan/curry-python-reader

**Comment by baili-b7ack** [comment]
> If your plot is generated by the curry reader package, try submitting the issue here: https://github.com/neuroscan/curry-python-reader

Thanks, I'll try
