### ISSUE TITLE
mne.viz _plot_topo ylim

### ISSUE THREAD

**Issue by mattjerhart** [mne-tools/mne-python#1290]
I couldn't set the ylim in some cases because they were being turned into something like [(-50,),(,100)] and abs() doesn't work on tuples. I added: 
import numpy as np
ylim_ = np.squeeze(ylim_).tolist();

to _plot_topo and it seems to work now.

**Comment by Eric89GXL** [comment]
Closing, I'm assuming this one has been resolved. Feel free to re-open if not.
