### ISSUE TITLE
Add `psd_args` parameter to `mne.preprocessing.ICA.plot_sources`

### ISSUE THREAD

**Issue by scholzri** [mne-tools/mne-python#12905]
### Describe the new feature or enhancement

Add a `psd_args` parameter to `mne.preprocessing.ICA.plot_sources` that gets passed to the plot we get when clicking on an IC source name. This would allow customization of the PSD plot that appears when interacting with the `plot_sources` output, similar to how `psd_args` works in `mne.preprocessing.ICA.plot_components`.

### Describe your proposed implementation

The implementation would pass the psd_args parameter through to plot_properties when a user clicks on a source name in the plot_sources output.

### Describe possible alternatives

I think the proposed implementation is optimal and superior compared to for example creating a new method.

It maintains consistency with how plot_components handles psd_args
It provides immediate, intuitive access to PSD customization within the plot_sources method
It doesn't require additional methods or global configurations, keeping the API simple and flexible

**Comment by larsoner** [comment]
Seems straightforward and useful, feel free to open a PR if you're up for it!
