### ISSUE TITLE
Overlapping Sensor Positions for OPM Data - Topoplots

### ISSUE THREAD

**Issue by neurofractal** [mne-tools/mne-python#12934]
### Description of the problem

Where OPM systems (e.g. Cerca) have the same sensor position but different sensor orientations (X,Y,Z) this causes issues when plotting topoplots. 

### Steps to reproduce

```Python
For example...

ica.plot_components()
```

### Expected results

Ideally topoplots should be produced using data projected though only one axis, rather than splitting up the data beforehand. To be more explicit - ICA should be run on all axes but topoplots should be produced using (for example) the Z-axis

### Actual results

Error - ValueError: The following electrodes have overlapping positions, which causes problems during visualization:

### Additional information

.....

**Comment by larsoner** [comment]
Closing as dup of https://github.com/mne-tools/mne-python/issues/11579 which has some ideas, feel free to look and comment @neurofractal !
