### ISSUE TITLE
Units in `mne.utils.sizeof_fmt()` incorrect

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#12961]
The helper function `mne.utils.sizeof_fmt()` creates a string of a given number of bytes in a human-readable format (with appropriate prefixes). However, it uses base 2, so the units should be kiB, MiB, GiB, ... and not kB, MB, GB, ... (which are base 10).

We should either change the displayed units or the base. Which one would you prefer?

**Comment by drammock** [comment]
Personal preference for MiB etc but I don't really care as long as it's accurate
