### ISSUE TITLE
Misleading note in legacy method `.pick_channels`

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-python#12969]
https://github.com/mne-tools/mne-python/blob/00c0e219a371bae8fadb2ccfe268d8a6317d4ab5/mne/channels/channels.py#L467-L469

Not entirely sure, but isn't this note a little misleading, as the order of `ch_names` **does** matter when `ordered=True` is passed?

I think the note should at least mention the `ordered` parameter.

https://mne.tools/stable/generated/mne.io.Raw.html#mne.io.Raw.pick_channels

**Comment by larsoner** [comment]
Yes I think this is a holdover from back when the default was `ordered=False` (and even before that when the `ordered` kwarg didn't even exist!)
