### ISSUE TITLE
Question: how to validate data obtained from mne._apply _forward? 

### ISSUE THREAD

**Issue by Anevar** [mne-tools/mne-python#1300]
step1) MEG data (original data)-> compute the forward solution-> compute the inverse solution( obtain source estimates )
step2) With the forward solution and the source estimates obtained, I use mne._apply_forward command -> MEG data(reconstructed data). 

The MEG data in the Step1 should be same as the MEG data obtained from step2. How can I validate it? 

what I've done: Compared the waveform of data from the original and reconstructed sensors, they look almost similar.  I tried to compare the power of the sensors, but I don't have comprehensible answers for it. Is there another way to validate it?

**Comment by Eric89GXL** [comment]
Closing, @Anevar feel free to reopen if this isn't clear
