### ISSUE TITLE
Bug in PSD Plotting: Incorrect dB Scaling for Amplitude in MNE

### ISSUE THREAD

**Issue by DingkunLiu** [mne-tools/mne-python#13034]
## Description
When plotting the Power Spectral Density (PSD) using mne.time_frequency.Spectrum.plot() or related functions with dB=True and amplitude=True, the decibel scaling appears to be incorrect. This issue arises because the conversion between power and amplitude dB follows different logarithmic relationships, and amplitude requires a factor of 20 in the scaling, whereas power uses a factor of 10 ([implement here](https://github.com/mne-tools/mne-python/blame/00c0e219a371bae8fadb2ccfe268d8a6317d4ab5/mne/viz/utils.py#L2400)).

## Example to reproduce
```python
import mne
import numpy as np

# Generate sample data
sfreq = 1000  # Sampling frequency
times = np.linspace(0, 2, 2 * sfreq)
data = np.sin(2 * np.pi * 10 * times)  # 10 Hz sine wave
info = mne.create_info(ch_names=['sin_wave'], sfreq=sfreq, ch_types='eeg')
raw = mne.io.RawArray([data], info).load_data()

# Plot PSD with dB=True
raw.plot_psd(dB=True, amplitude=True)
```
## Expected result
The peak at 10Hz is expected to be $120=20 * log(10^6)$, but the plot returns 60.

**Comment by drammock** [comment]
thanks for the very clear example @DingkunLiu! Fix is in #13036
