### ISSUE TITLE
ENH: replace Delaunay triangulation by some other interpolation

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1308]
... the triangles are not beautiful. Would be great to have something more smooth and contour like. Also @kingjr was complaining, maybe even suggesting to take a stab on it ;-)

**Comment by Yerzhan19** [comment]
Is there any interpolation already implemented in MNE similar to Matlabs "Biharmonic spline interpolation"("v4" method in Matlab's griddata)?

**Comment by agramfort** [comment]
maybe https://docs.scipy.org/doc/scipy/reference/tutorial/interpolate.html
helps.

**Comment by yjmantilla** [comment]
> Yes, this triangulation may not be the best, as it incorrectly suggests edges on the topography.
> 
> In Fieldtrip, they use Matlab 'V4' (c) interpolation, adapted from <a, href=[http://topex.ucsd.edu/sandwell/publications/021_GRL_biharmonic_1987.pdf>David](http://topex.ucsd.edu/sandwell/publications/021_GRL_biharmonic_1987.pdf%3EDavid) T. Sandwell, Biharmonic spline interpolation of GEOS-3 and SEASAT altimeter data, Geophysical Research Letters, 2, 139-142, 1987
> 
> You can have a look at their [griddata](http://www.mathworks.fr/fr/help/matlab/ref/griddata.html) function.
> 
> In your case a 'cubic' interpolation would probably smoothen the topography.
> 
> PS: I'm not complaining. I'm just noticing ;).

I have an early stage translation of it here, if anyone is interested in that:

https://github.com/yjmantilla/gdatav4
