### ISSUE TITLE
FIX/ENH: equivalence between induced_power and single_trial_power

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1312]
to me `single_trial_power(**kwargs).mean(0)` should be the same as `induced_power(**kwargs)[0]` but it's not. 

@agramfort ?

**Comment by mmagnuski** [comment]
`single_trial_power` will be deprecated and `induced_power` is gone, so, although not resolved, this can be closed.

**Comment by agramfort** [comment]
thanks @mmagnuski for doing the bookkeeping :)
