### ISSUE TITLE
getting_started

### ISSUE THREAD

**Issue by dgwakeman** [mne-tools/mne-python#1327]
These instructions don't work (at least for Ubuntu) (Thanks to @chdinh for pointing this out). We need some better instructions. Are any of you good with VM? We should test the install process. It should be very easy. Unfortunately, canopy is terrible with instructions pip doesn't have an install thing at all. Any help would be good. Thanks, see #1140 for a start.

**Comment by Eric89GXL** [comment]
This has been updated recently, hopefully it works better now
