### ISSUE TITLE
Example on creating MNE data objects from arrays

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#1382]
we need an example

"Creating MNE data objects from arrays"

to point people to.

**Comment by Autodidact24** [comment]
Hi @agramfort,

I would like to take this up. Can you point me to a case where we do this (create MNE data objects from arrays) ?

**Comment by mainakjas** [comment]
@Autodidact24 : you should grep for `RawArray`, `EpochsArray` and `EvokedArray` in the repository. You can also look through the mailing list archives to see the most relevant use cases.

**Comment by Autodidact24** [comment]
Thanks @mainakjas 
That helped !

**Comment by jaeilepp** [comment]
I'll take it.

**Comment by Eric89GXL** [comment]
We have this now
