### ISSUE TITLE
Query on forward/source_spaces

### ISSUE THREAD

**Issue by dgwakeman** [mne-tools/mne-python#1383]
@Eric89GXL, I was confused today by the behavior of read_forward_solution. I expected it not to provide the geometry information in the ['src'] field due to ``mne.read_forward_solution`` utilizing ``add_geom=False`` in it's call to ``mne.read_source_spaces_from_tree``. However, following down the rabbit hole, I found that ``add_geom`` doesn't just add it from the tree, but actually calculates it, so in the case that the information is already in the source space used to calculate the forward model it will exist even though ``add_geom=False``. 

Was there a motivation for changing the naming to be ``add patch`` and ``add_geom`` from the upstream ``--cps``? 

I find add_geom more confusing than cortical patch statistics or cps especially given that the logger.info etc. all say patch statistics.

I already regret asking this (after all of my trouble last week)...

**Comment by Eric89GXL** [comment]
@dgwakeman do you have time to work on this?

**Comment by dgwakeman** [comment]
Yeah, I will do it this weekend/end of this week
