### ISSUE TITLE
Loading evoked data when proj was applied to the average fif file

### ISSUE THREAD

**Issue by joewalter** [mne-tools/mne-python#1389]
When loading evokeds from the MNE sample data set, all proj are already active. So loading the evoked with proj=False has no effect. 

However in both cases (with proj=False and proj=True), evoked.proj = False after loading the evoked, as in apply_proj all projections will be recognized to be active and the user receives the info: 'Projections have already been applied. Doing nothing.'

One solution for this might be to check if all projections are active after loading an evoked and if so, set evoked.proj = True and inform the user that the loaded data already has active projections.

Any comments or other ideas?

**Comment by agramfort** [comment]
this is fixed by my recent cleanup of proj attribute.
