### ISSUE TITLE
ENH/FIX: allow for reject API  that is more consistent with MNE C

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1452]
In MNE-C it is possible to specify epoching parameters using a config file like this:
```
average {
outfile __OUTFILE__
eventfile __EVEFILE__
logfile __LOGFILE__
grdReject 200e-12
magReject 4e-12
eegReject -1
eogReject -1
emgReject -1
name "WordOnsets"

category {
name "VerbNP"
event 71 
tmin -0.3
tmax 1.2
}
}
```

MNE-Python new comers might be tempted to construct a reject dict like this:

```Python

reject = dict(mag=4e-12, grad=200e-12, eog=-1, ecg=-1)

# or

reject = dict(mag=4e-12, grad=200e-12, eog=None, ecg=None)
```

Which can / will lead to unexpected results, e.g. in Python comparisons None is always smaller than any numerical value ...

I would suggest to either allow for the MNE C style API or throw nice + concise errors once values like -1 or None are passed.

cc @agramfort @Eric89GXL 

Thanks to @bmaess to bringing this to my awareness

**Comment by agramfort** [comment]
any action needed here?

do we allow reject keys for absent channels?

**Comment by Eric89GXL** [comment]
Moving to 0.10, haven't heard responses or found volunteer
