### ISSUE TITLE
SNR in source space

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#1453]
@dengemann pointed me to:

http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2882168/

any interest getting this in MNE-Python?

@mshamalainen any opinion?

**Comment by Eric89GXL** [comment]
I actually started working on translating the C code for SNR calculations last week, hopefully I'll have something working soon. Then we can just have a `method` argument.

**Comment by dengemann** [comment]
@Eric89GXL cool!

**Comment by Eric89GXL** [comment]
@agramfort do we still need this?

**Comment by dengemann** [comment]
Yes. It would be a nice complementary to the CFC functions. But no high
priority.

**Comment by agramfort** [comment]
yes it would be "nice to have"
