### ISSUE TITLE
FIX? functional label extraction for subjects morphed to fsaverage

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1477]
@agramfort @Eric89GXL @mluessi @christianbrodbeck @t3on it seems to me that using mne.stc_to_label does not behave as expected when applied to fsaverage. It seems it considers all the vertices and not the n_used. As a consequence, stc.in_label(func_label) will only return the subset of n_used. This is not terrible but it makes it difficult to precompute the size of arrays for groupt analysis from the functional label's vertices. I'm not sure what would be the best fix here. Suggestions welcome.

**Comment by larsoner** [comment]
Closing since this hasn't seen activity in 3+ years, feel free to reopen if you still hit this need
