### ISSUE TITLE
ENH: generic mass-univariate function

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1506]
I feel the time has come to add more API to our mass-univariate stats.

I have already done some work on that, but it needs a cleanup and some API-rethinking because I'm still hitting new / additional use cases.

Anyways not too early to start a discussion.

@agramfort @Eric89GXL @mluessi @christianbrodbeck @maedoc

**Comment by Eric89GXL** [comment]
@dengemann still interested in this? Been ~1.5 years, maybe you don't need it :)
