### ISSUE TITLE
mne.preprocessing.compute_proj_ecg filter options

### ISSUE THREAD

**Issue by dgwakeman** [mne-tools/mne-python#1530]
As this function stands you cant really use many useful highpass filtering (e.g. anything below 0.6 or so Hz). The problem boils down to you can modify the ``filter_length``, but this doesn't help if you want a lower highpass filter, because it the bandpass transition doesn't dynamically shift based on the other factors

mne.preprocessing.compute_proj_ecg(raw, n_grad=4, n_mag=4, n_eeg=4, l_freq=0.25,h_freq=50,average=False, filter_length='20s', n_jobs=1, ch_name=None, reject={'eog':0.00025,'eeg':5e-05, 'grad':2e-10, 'mag':3e-12}, flat=None, bads=[],avg_ref=False, no_proj=False, ecg_l_freq=0.25, ecg_h_freq=50, tstart=0.0)

produces:

ValueError: Filter specification invalid: Lower stop frequency too low (-0.2Hz). Increase Fp1 or reduce transition bandwidth (l_trans_bandwidth)

What is the best way to deal with this? expose l_trans_bandwidth or make l_trans_bandwidth dynamic?

**Comment by agramfort** [comment]
closing?
