### ISSUE TITLE
ENH/API: cluster stats

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1534]
For reporting it would be good to have quick access to the statistic used. While we have the H0 that can be used to plot a histogram of the test-statistic, it seems currently there is not convenient way to extract the test-statistic of each clusrer itself. Since it will depend on many parameters it would be nice to just return it togther with the other return parameters. This would break peoples code however (iterable unpacking expects 4 values currently) but we could make it options. While we're at it I think it would be nice to have light weight class for the cluster_stats return values. For example a named tuple. Alternatively we could have an object that keeps the iterable behaviour we currently have but is equipped with summary methods, e.g. to compute the the statistic post-hoca and to generate informative hist plots. What would people think? @Eric89GXL @agramfort @mluessi @christianbrodbeck @t3on and all the other cluster-junkies out there, e.g. @introspection.

**Comment by larsoner** [comment]
Closing for more complete discussion in #4859
