### ISSUE TITLE
Question: multiple events per trial

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#1562]
Hello,
I'm trying to import some data from fieldtrip to MNE-Python.

However, my data contains multiple events per trial: e.g. (visual or auditory) x (left or right) x (relevant or distractor).

What do you think is the best way to keep these various information in the events, and how can I then some interaction (e.g. visual x left x relevant; e.g. visual left OR auditory right)?

Thanks!

**Comment by agramfort** [comment]
ok suggestion. Let's say event_id can be 

event_id = {'left/auditory': 1, 'right/auditory':2, 'left/visual':3, 'right/visual':4}

and epochs['visual'] returns all visual epochs?

**Comment by agramfort** [comment]
or maybe more readable

event_id = {'left__auditory': 1, 'right__auditory':2, 'left__visual':3, 'right__visual':4}

**Comment by jona-sassenhagen** [comment]
From a linguistics perspective and in a regression context, I agree with @kingjr continuous predictors would be very cool.

**Comment by kingjr** [comment]
If that's of any help, with @dengemann, we now use panda.DataFrame so as to easily deal with multiple discrete and continuous conditions.

**Comment by agramfort** [comment]
can you be more explicit how you do this within epochs in mne?

**Comment by kingjr** [comment]
I do it outside..
```
events = pd.DataFrame({cond1='foo', cond2=0.10}, {cond1='bar', cond2=3.})
selection = np.where(events['cond1']=='foo' & events['cond2']>1)[0]
epochs[selection].average()```

**Comment by agramfort** [comment]
if it's 3 lines of code why making the MNE code more complex???

**Comment by dengemann** [comment]
> if it's 3 lines of code why making the MNE code more complex???

+1

**Comment by kingjr** [comment]
> if it's 3 lines of code why making the MNE code more complex???
I agree. The only minus is that keeping the two objects separated increases the risk of breaking their link. 
```
# sub selection of epochs
epochs_vis = all_epochs[events[modality=='visual']]
# keep cond2 in events for further processing
epochs_vis.events[:, 2] = events['left_right'][events[modality=='visual']]   # whoo, careful what you do here boy
```
as opposed to
```
epochs_vis = all_epochs[modality=='visual']
print epochs_vis.events['left_right']  # Ooh yeah! neat
```

But obviously, changing the mne.events into a pd.dataframe is rather expensive, so may be let's forget about this.

**Comment by agramfort** [comment]
nobody thinks my:

event_id = {'left__auditory': 1, 'right__auditory':2, 'left__visual':3, 'right__visual':4}
epochs['visual']

would solve a practical problem?

**Comment by mainakjas** [comment]
I'm +1 on this

**Comment by Eric89GXL** [comment]
It would be useful, yeah. I am had not been pushing for it because I have built a system to take care of this in my own analysis pipelines already, as I imagine others have, too. That being said, thinking about it now, it would be *really* nice to just get rid of that code and would probably simplify things at my end, actually, so +1 from me, too. If we got it in for 0.9 we could get feedback on it, too. Anybody have the bandwidth to implement it? If not, I might be able to squeeze it in next week.

**Comment by Eric89GXL** [comment]
Why use `__` instead of `/`, just because you expect people might have used `/` but not `__`? We could have a `condition_separator` argument that defaults to `/` that people could change -- I think `/` is a more natural choice. It naturally lends itself to the interpretation "or" or "hierarchy" (like a filesystem), which is nice.

**Comment by agramfort** [comment]
No strong feeling. __ is used in django and scikit-learn but / is the
Eeglab way apparently.

**Comment by jona-sassenhagen** [comment]
It's a really new EEGLAB thing though, I doubt many people would expect it. Though I agree with @Eric89GXL 's reasoning - / looks like hierarchy more.

**Comment by agramfort** [comment]
ok but when you do visual__left  it's not a hierarchy but more multi labels.

**Comment by Eric89GXL** [comment]
I think that `/` is what I'd expect to be the separator as a user, as it can actually be interpreted either way. In fact I'd probably do `visual/left` or `/visual/left` depending if I wanted to think of it as multi labels or hierarchy...

**Comment by agramfort** [comment]
Whatever on my side. As long as we document it.

**Comment by jona-sassenhagen** [comment]
Would this be as simple as inserting this

```
if (any(["/" in key for key in self.event_id.keys()]) 
       and key not in self.event_id.keys()):
    key = [k for k in list(self.event_id.keys()) if key in k.split("/")]
```

in Epoch's ``` __getitem__``` method? Or am I missing something?

**Comment by Eric89GXL** [comment]
Pretty much, I was thinking something similar, plus a bunch of tests to make sure it actually works as intended :) If you have time (and no other PRs pending for release!), please implement. I guess you have https://github.com/mne-tools/mne-python/pull/1795 but you're not the blocker there.

**Comment by Eric89GXL** [comment]
...also the seperator should be configurable via a property.

**Comment by agramfort** [comment]
I think we have 50% of the PR here ;) the rest is a test ;)

**Comment by Eric89GXL** [comment]
...or more like 1-5% of the PR if we're counting by lines :)

**Comment by jona-sassenhagen** [comment]
I have another somewhat ready PR but it's not for 0.9, so I guess I'll try making a PR today or tomorrow.

**Comment by jona-sassenhagen** [comment]
@Eric89GXL specify separator string when the Epochs object is constructed? Like,
```epochs = mne.Epoch(raw, events, event_id, event_sep="__")```
With it defaulting to "/"

**Comment by Eric89GXL** [comment]
Let's not add yet another an argument to the constructor, people can just set it after the fact if they want like `epoch.event_sep = '__'`

**Comment by agramfort** [comment]
-1 on allowing an option to set the separator. It seems like a YAGNI to me.
We should agree and stick to it.

**Comment by Eric89GXL** [comment]
Fair enough. I feel like `/` is more natural, so that gets my +1.

**Comment by agramfort** [comment]
fair enough too

any other thought?

**Comment by jona-sassenhagen** [comment]
I'm setting it up so that for multiple matching, you can pass either a single string, or a list. If a list, it selects every event id that contains all items in the list. So epochs[['audio', 'left']] matches 'audio/left' and 'audio/left/loud' and also 'audio/loud/left', but not 'audio/right'.

This also means the linear order of '/'-separated items in the event ids is ignored.

Good?

**Comment by agramfort** [comment]
Good

**Comment by kingjr** [comment]
My feeling is that it s not non scalable ehn. More and more of the people I interact with have >2 potentially nested factors which would require a really different approach .

**Comment by agramfort** [comment]
so maybe we need both __ and /. __ would mean "tags" and "/" hierarchy? or
maybe I am missing the point @kingjr is trying to make...

**Comment by dengemann** [comment]
KISS ... power users wil probablyl use pandas or something else to subset their data. The question is not whether this approach solves all problems but whether it has a future, i.e., will we deprecate it in one year from now?

**Comment by agramfort** [comment]
my strategy would be write the documentation of this feature before
implementing it to see if it's convoluted or not.
