### ISSUE TITLE
[FEATURE] filter.py with method 'fft' should optionally return a frequency domain array

### ISSUE THREAD

**Issue by kevinjos** [mne-tools/mne-python#1576]
I am using MNE for data processing and feature extraction. Some features will be on the time domain and others derived from the frequency domain. I would like to only have to calculate the fft in one place, during filtering. What do folks think of adding an optional argument to _filter() to return the results of the fft in addition to the time domain?

**Comment by Eric89GXL** [comment]
I suspect this can / should be done in `NumPy` land now that we have refactored our filtering functions. Closing.
