### ISSUE TITLE
Import micromed .TRC raw data

### ISSUE THREAD

**Issue by Lx37** [mne-tools/mne-python#1605]
Hi MNE :)

I would like to analyze micromed raw EEG data (.TRC) using MNE.
Is there already a way to import this format (that I missed)?
So far, I'm using NEO to import the data on python environment, and this leads me to the #870 issue, talking about interoperability between NEO and MNE.
What would be the best way to carry on my analysis and how could I help solving this issue ?

Thanks!
best

cc @samuelgarcia

**Comment by Eric89GXL** [comment]
We now have an example of how to integrate NEO and MNE, feel free to open a new issue if it is unclear or there seems to be a better way

**Comment by adam2392** [comment]
Does mne-python support (or plan to) reading in .TRC files (couldn't find anything in API), or is the recommended approach rn to use what @agramfort 's gist does?

https://gist.github.com/agramfort/7fc27a18fcdc0e8cff3f

**Comment by agramfort** [comment]
it's not supported in MNE as nobody really needed it among the core
developers.

>
