### ISSUE TITLE
filter.py _1d_overlap_filter DeprecationWarning on dtype conversion

### ISSUE THREAD

**Issue by kevinjos** [mne-tools/mne-python#1613]
Hi all. I am getting the following WARN:
filter.py:175: DeprecationWarning: Implicitly casting between incompatible kinds. In a future numpy release, this will raise an error. Use casting="unsafe" if this is intentional. 
x_filtered[seg_idx * n_seg:seg_idx * n_seg + n_fft] += prod
AND
filter.py:178: DeprecationWarning: Implicitly casting between incompatible kinds. In a future numpy release, this will raise an error. Use casting="unsafe" if this is intentional.
x_filtered[seg_idx * n_seg:] += prod[:n_x - seg_idx * n_seg]

Please note that I call two filter functions, band_stop_filter and high_pass_filter, in a loop, but I only see the two DeprecationWarning print outs once each. I did some looking into this and it seems that x_filtered is and array of 16-bit integers and prod is an array of 64-bit floating point numbers. I also see that x_filtered is cast above to be an array of zeros with the dtype of the filter input. If I set cast my input arrays of 16-bit integers to a larger array of 64-bit fps, then I don't see any of the warnings.

What's the intended behavior? Should x_filtered always be explicitly up cast to np.float64?

**Comment by Eric89GXL** [comment]
I figured that all readers would up the dtype to `float64` like `RawFIF` does. We should either have them all read in as `float64`, or not. Otherwise there would have been no point in making `RawFIF` do recasting in the first place... @dengemann if you're okay with it, I'll change the reader to convert the data to `float64`.
