### ISSUE TITLE
Q: neural mass source simulation

### ISSUE THREAD

**Issue by maedoc** [mne-tools/mne-python#1625]
Is there interest in having neural mass models to generate source estimates?

**Comment by Eric89GXL** [comment]
@maedoc feel free to implement if you have time. In the meantime I'll close this issue since it's a bit stale

**Comment by maedoc** [comment]
thx, had forgotten about this issue. I'm currently writing a lib for Bayesian inference for these sorts of models w/ neuroimaging data. When it's ready I'll be back.

**Comment by Eric89GXL** [comment]
Excellent, looking forward to the PR!
