### ISSUE TITLE
Abstract base class

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#1633]
In ref to https://github.com/mne-tools/mne-python/pull/1632. there are attributes that shared between different raw classes that would be better allocated to an abstract base class. we currently have base_raw which is the basis for non-neuromag systems.

**Comment by Eric89GXL** [comment]
@teonlamont do you have time to do this for 0.9 (in the next week or so)?

**Comment by teonlamont** [comment]
tbh, i don't even know what "this" is...

-teon

**Comment by Eric89GXL** [comment]
Maybe not making it a pure ABC, but at least make it clear in `_BaseRaw` what attributes the subclasses need to assign in order for everything to work properly. Maybe in `_BaseRaw.__init__` check to see if things have been assigned properly, and if not, throw and error.

If we make a pure ABC, then we'll immediately have to subclass it to add the functionality already in `_BaseRaw`, and every actual class (like `RawFIFF` or `RawKit`) would end up subclassing the intermediate class.

**Comment by Eric89GXL** [comment]
I might have time to do this today.

**Comment by Eric89GXL** [comment]
@agramfort why does `EpochsArray` inherit from `Epochs` instead of `_BaseEpochs`? This is strange to me.

**Comment by Eric89GXL** [comment]
Or I guess `git blame` says that I should ask you @dengemann -- why does `EpochsArray` inherit from `Epochs` instead of `_BaseEpochs`? `RtEpochs` inherits from `_BaseEpochs`, as I expected.

**Comment by agramfort** [comment]
Naughty  @dengemann ;)

**Comment by Eric89GXL** [comment]
Pretty sure there are some things in `Epochs` that belong in `_BaseEpochs`, e.g. `resample`, `crop`, `copy`... I hope it doesn't end up being a mess to move them.

**Comment by Eric89GXL** [comment]
Argh, I think I realized why the subclassing was done on `Epochs` instead of `_BaseEpochs`... I think most of the methods don't make sense for the `RtEpochs` object. Not 100% sure though. @agramfort @mainakjas any idea?

**Comment by teonlamont** [comment]
is there a reason why `_BaseEpochs` doesn't have an `events` attribute?

**Comment by mainakjas** [comment]
On Sat, Apr 11, 2015 at 11:28 PM, Teon <notifications@github.com> wrote:

> is there a reason why _BaseEpochs doesn't have an events attribute?
>
I think it's because in real-time the events are tuple but in Epochs, they
are a list. The reason for tuple is that it's more efficient that way.

**Comment by Eric89GXL** [comment]
@teonlamont let's kick the `Epochs` / `_BaseEpochs` unification down the road until later, I have a feeling it's going to be a huge pain. If you're feeling super bored I won't stop you, though.

The `_BaseRaw` refactoring seems like it will be simpler, and is going well.

**Comment by Eric89GXL** [comment]
@teonlamont for now I guess you should subclass `Epochs` instead of `_BaseEpochs`, since `Epochs` has a lot more functionality.

**Comment by mainakjas** [comment]
On Sat, Apr 11, 2015 at 11:08 PM, Eric Larson <notifications@github.com>
wrote:

> Argh, I think I realized why the subclassing was done on Epochs instead
> of _BaseEpochs... I think most of the methods don't make sense for the
> RtEpochs object. Not 100% sure though. @agramfort
> <https://github.com/agramfort> @mainakjas <https://github.com/mainakjas>
> any idea?
>
I suppose a lot of methods for Epochs don't make sense in RtEpochs but they
are fine for EpochsArray. You have to do everything differently in
real-time.

**Comment by Eric89GXL** [comment]
...and all that `EpochsArray` does is override `__init__`, so @teonlamont switching `Epochs` in for `EpochsArray` as your super class shouldn't require any other changes.
