### ISSUE TITLE
FIX: deprecate add_eeg_ref=True

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1635]
This default in most cases *not* the desired behavior as I have painfully learned while processing many EEG datasets over the last monthss. You typically do the common referencing when you're done with preprocessing, e.g. computing ICA and dropping epochs. It's really tedious to always spell this longish argument name at every step (Raw, Epochs) and pay a high price when forgetting it. Also funky things may happen such as including the stim channel in the common ref.

What do people think?
cc @fraimondo @wmvanvliet @christianbrodbeck @t3on @kazemakase

**Comment by Eric89GXL** [comment]
@dengemann did the referencing PRs take care of this one? If not, could you try to succinctly specify what needs to be done?

From my end, I don't think we want to break anyone's C-standard pipelines, so getting source estimates using raw / epochs / evoked should "just work" by default without having to manually specify that an average EEG ref should be added.

**Comment by wmvanvliet** [comment]
I feel the referencing issues have been mostly addressed.
When a custom reference has been specified, the `add_eeg_ref` param will not override this reference any more.
