### ISSUE TITLE
ENH: freezing dependencies for ICA

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1678]
I figured that subtle changes in the sklearn sources tend to render exact results using ICA unreproducable. I would not like to bother about that. I'd suggest to put copy sklearn/decoposition/pca.py and sklearn/decoposition/ica.py to mne-python and update them in a controlled fashion once a year or so. 

@agramfort

**Comment by Eric89GXL** [comment]
@dengemann do you still see this issue?

**Comment by agramfort** [comment]
don't think so
