### ISSUE TITLE
mne report parallel processing error

### ISSUE THREAD

**Issue by ktavabi** [mne-tools/mne-python#1684]
For some reason the `n_jobs` argument for parallelizing `Report.parse_folder()` generates the following error. This is the only use case of mne-python parallel processing that I've encountered this error. After several recursions of the error message the interpreter hangs. Has anyone else seen this, or knows how to deal with this?

> [xcb] Unknown sequence number while processing queue
> [xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
> [xcb] Aborting, sorry about that.
> python: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.

**Comment by riwave** [comment]
Thank you! I had the same problem. It is an ipython problem!
