### ISSUE TITLE
egi compatibility

### ISSUE THREAD

**Issue by dgwakeman** [mne-tools/mne-python#1687]
cc @dengemann I have discovered that our code does not properly read binary EGI data from NetStation 5. This is likely due to incompatibility of both our code as well as some issues with EGI's conversion (for example the ECG channel is called u'TR' after the conversion). It also seems that the new files use unicode (as highlighted in the above example). I am going to work on this, but I wanted it documented somewhere so people know. I will explore what the best option is for reading EGI data (I am leaning toward trying to make it so we can read the raw mff files and can avoid dealing with converting the files).

**Comment by teonlamont** [comment]
hey @dgwakeman, let me know if you need a hand with this.

**Comment by Eric89GXL** [comment]
@dgwakeman any progress here?

**Comment by Eric89GXL** [comment]
I am in the midst of modifying the EGI code currently, so this would be a great time to tackle this issue again. There has been no response, though, so I'm going to close for now. @dgwakeman feel free to reopen if it's still broken and you can provide samples.

**Comment by mshamalainen** [comment]
Is there any help we need from EGI? I can be in touch with Don Tucker about this, if necessary.

- Matti


> On Dec 4, 2015, at 5:06 PM, Eric Larson <notifications@github.com> wrote:
> 
> I am in the midst of modifying the EGI code currently, so this would be a great time to tackle this issue again. There has been no response, though, so I'm going to close for now. @dgwakeman <https://github.com/dgwakeman> feel free to reopen if it's still broken and you can provide samples.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/mne-tools/mne-python/issues/1687#issuecomment-161988829>.
> 



The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.

**Comment by Eric89GXL** [comment]
@mshamalainen not at the mne-python end yet I don't think. First we'd want to get our hands on a troublesome file and try it with our reader. Then probably look up file specs and see if we can figure out how to fix our reader -- you know, RTM :) Then if that fails, bother other folks.

**Comment by mattboggess** [comment]
I'm curious as to the current status of supplying IO support for EGI MFF files? I had started translating the fieldtrip MATLAB code for reading in mff files, but realized it might be more beneficial if these efforts were officially incorporated into MNE. Is this being worked on or planned to be worked on by anyone? If not, I'd be willing to put in the time.

**Comment by Eric89GXL** [comment]
We have support for some EGI files, but not MFF AFAIK.

@SherazKhan you have some Python code to read MFF, right? Any chance you can convert it to an MNE reader in the next week or two?

**Comment by mattboggess** [comment]
Just wanted to follow up on this discussion to see if there was any update?

**Comment by SherazKhan** [comment]
@mattboggess @Eric89GXL Lets do it, @mattboggess do you some sample mff file I can test the reader ?
@Eric89GXL do we have a mff file in testing data ?

**Comment by Eric89GXL** [comment]
No test file. Does anyone have access to a system where they could record a short segment (1 sec?) of data to add to mne-testing-data?

**Comment by jona-sassenhagen** [comment]
Our EGI person literally broke her back this weekend ... I could do it next year :D 

I only have a bunch of very long ones. MFF reader would be very cool!

**Comment by SherazKhan** [comment]
@jona-sassenhagen may be a segment with multiple events ?

**Comment by dengemann** [comment]
@Mensen do you mind if I share the code you once showed to me? We have a few people who would love to skip the silly conversion step to EGI .raw data.

**Comment by SherazKhan** [comment]
This is the API I have, please let me know, if you have any-more specific for the IO APIS

`from .io import read_mff_data,read_mff_header,read_mff_events

class mff:

    def __init__(self, filename):
        self.filename = filename
        self.hdr = self.get_hdr()

    def get_hdr(self):
        return read_mff_header(self.filename)

    def get_data(self):
        return read_mff_data(self.filename, 'epoch', 1, self.hdr['nTrials'], self.hdr)

    def get_events(self):
        return read_mff_events(self.filename, self.hdr)`

**Comment by dengemann** [comment]
@SherazKhan it should be exposed in the same way as other readers in mne.io; but this is not a problem, we can handle this here. @fraimondo any chance we have silly little mff netstation file to play with?

**Comment by Eric89GXL** [comment]
We have a specific API, most recently worked through here:

https://github.com/mne-tools/mne-python/pull/3754

Basically you need to populate the measurement info in a Neuromag-like way, and provide a function to read arbitrary time segments of the data.

**Comment by SherazKhan** [comment]
Thanks @Eric89GXL , excellent very detailed, let me work on the API.

**Comment by fraimondo** [comment]
I have netstation mff files. But not for the latest net station. In any case, it would be great to be able to read mff files without converting to raw. RAW files don't support non-eeg channels data. I have to go through matlab files. And synthesising the trigger channel for that is painful

[Test File Here](https://www.dropbox.com/s/xqjbtxphkdg26g4/test_data?dl=0)

**Comment by mattboggess** [comment]
@SherazKhan @Eric89GXL  I have a 2 min 45 second recording with multiple events I could share now. This recording does not have any non-EEG channels through the Physio16 nor does it have an associated digitization file, both of which would be nice to support.

I have access to a system and could record something shorter if desired. I also potentially could get access to a longer recording that has Non-EEG channels or record a shorter version with the Physio16 (though this might take more time to acquire since we don't currently plan to use the Physio16).

**Comment by Eric89GXL** [comment]
How big is the file? 1MB is okay but 10 or 100 is probably not, and a shorter file would be better.

**Comment by mattboggess** [comment]
Oh no then it's too big (160 MB).

**Comment by fraimondo** [comment]
Tomorrow I can edit the file and cut only a few epochs. First thing in the
morning. Need access to and old Mac and a hasp key.

**Comment by mattboggess** [comment]
@fraimondo Were you able to obtain a smaller file?

I recorded a 2.1 MB file today that has multiple events that I could share for testing just in case . It's hard for me to get smaller since we only have high density caps. Notably, it does not contain non-EEG channels and does not have an associated digitization file, though it should be from the latest net station version.

**Comment by fraimondo** [comment]
[Here's](https://www.dropbox.com/s/3awaktm0skdzr64/short_test_data?dl=0) a 2 mb files with a couple of seconds of EEG + PSG data with digital triggers.

**Comment by ramonapariciog** [comment]
Hi guys,
I just starting to use mne, and i have some questions: How can i use the code of SherazKhan to read an egi file directly without the conversion to raw egi, is it possible to do?. Sorry for reopen the thread but i didn't understand if you could solve the problem. I have access to a geodesic Hidrocel, and i can facilitate the data. Thanks.

**Comment by agramfort** [comment]
ping @SherazKhan 

any chance to have your help to integrate a good EGI reader in mne-python ?

**Comment by fraimondo** [comment]
Same here… I’m in coding mood

**Comment by SherazKhan** [comment]
Sorry Guys for being sparse in my appearances, @ramonapariciog do you have a good sample mff file which can be put into testing dataset ?

**Comment by Eric89GXL** [comment]
@SherazKhan can you make use of this data that @fraimondo posted?

https://www.dropbox.com/s/xqjbtxphkdg26g4/test_data?dl=0

If you can get it working with your reader, we can add it to mne-testing-data. It's a bit unfortunate that it's 50MB, though, so if someone can get a smaller file (~1 sec?) that would be ideal.

**Comment by Eric89GXL** [comment]
Oh wait in a later comment he posted a smaller version

https://www.dropbox.com/s/3awaktm0skdzr64/short_test_data?dl=0

**Comment by mattboggess** [comment]
On a related note, is there existing functionality to read in EGI digitization files?
