### ISSUE TITLE
Q: Making movies

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#1690]
It might be nice to expose a simple UI for creating movies. There is a package called MoviePy we might be able to use with PySurfer and/or other viz functions, e.g.:

See related PySurfer PR:

https://github.com/nipy/PySurfer/pull/79
http://zulko.github.io/blog/2014/11/29/data-animations-with-python-and-moviepy/

The thing I'd first want to see movie-able would be brain movies (PySurfer). We should decide if we want to leave that entirely up to PySurfer, or if we want to provide some convenience wrapper.

Are there other applications people have in mind? Maybe field map movies for sensor-space-ish plots?

**Comment by aestrivex** [comment]
Looks like this is done in pysurfer, I think the easiest/correct approach is what was done of calling ffmpeg.

It should be very straightforward to add relevant API calls to save_movie, similar to mne_analyze, or to do something similar.

**Comment by aestrivex** [comment]
Does this also work when ffmpeg is installed on windows or on OS X running quartz? The call to ffmpeg is a bit different than what is done in my program which figures out where the correct X window is positioned, and record from it. I think that is faster than repeatedly saving frames, but if it works across platforms with decent performance then it is probably smarter.

**Comment by Eric89GXL** [comment]
It should work on Windows/OSX so long as the command-line encoder call works there. But I haven't tested it...

That's one nice thing that would be nice about using moviepy -- it automatically pulls down its own version of ffmpeg for each platform it needs to.

@christianbrodbeck recently put a PR into PySurfer that saves movies, so the functionality in mne-python is effectively available once a user has done `stc.plot()`. We should probably put a good example in the repo, probably in one of the inverse operator examples. We could also change it (in PySurfer) to use MoviePy to ensure it works on all major platforms.

**Comment by wronk** [comment]
Here are a few scripts I wrote to:
1) convert a surface into a `.ply` file, 
https://gist.github.com/wronk/c2333f9cb6c9f8b0ab05
A script like this that also saved the color information for a particular time point as one of the properties in the `.ply` file would be a useful first step for loading brains with activity maps into Blender. It would allow a user to make still images just by manipulating the camera angle, lighting, and textures.

2) compute source estimates and save as an array for loading into blender and 
https://gist.github.com/wronk/593bfc29687e61e72cde

3) Python script meant to be run in Blender. It loads a matrix of data and plot multiple time points of cortical activity on a pre-loaded brain surface (like something obtained from 1.)
https://gist.github.com/wronk/84c029c91ca11ff14498


This is really hacked together as I didn't have much success getting a clean pipeline going between MNE-python and Blender's python API, so sorry for the mess :p

**Comment by Eric89GXL** [comment]
PySurfer has some movie stuff in it now, so people can use that hopefully. Closing, feel free to open another issue if someone has ideas for enhancement
