### ISSUE TITLE
ENH: add scikit.cuda support for fft and ifft

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1691]
ping @Eric89GXL what would you think about a weak dependency? Is it worth the the effort? I'm doing heavy TFR analyses over many trials and sensors ....

**Comment by Eric89GXL** [comment]
Closing for now since I took a look a while back and couldn't speed up the Stockwell code using CUDA. But we can open more specific targeted issues for slowdowns that people have (e.g., tfr_morlet) and tackle those.
