### ISSUE TITLE
Creating Montage from Polhemus points

### ISSUE THREAD

**Issue by christianbrodbeck** [mne-tools/mne-python#1703]
I have brain vision data and digitized electrode positions. This now means I have to create a Montage file with my digitized points in order to convert my data, right? Is there a tool for creating a montage from a Polhemus Points file? If not should I add one?

Also there seems to be something wrong at https://github.com/mne-tools/mne-python/blob/master/mne/channels/layout.py#L764, the scale parameter in the function signature is never used in the function...

**Comment by teonlamont** [comment]
closed for #1846

**Comment by christianbrodbeck** [comment]
I left this open because of proposed modifications to the documentation after the importing issue has been settled

**Comment by christianbrodbeck** [comment]
I assigned myself to do the API refactor discussed in here as soon as #1846 is done

**Comment by Eric89GXL** [comment]
I'm going to move this to 0.10, @christianbrodbeck if you can take care of it in the next day or two for 0.9 feel free

**Comment by christianbrodbeck** [comment]
This shouldn't take too long, but looking through the dev I/O reference section I came up with 2 questions:

- what is the long term plan for data formats. Is fiff still the standard and other systems should go into an "other systems" section? Or should other formats basically receive equal treatment as fiff? (in which case it might be more appropriate to structure the file I/O section according to the kind of information to load)
- A lot of objects can be saved with `mne.write_x()` as well as `x.save()`, I would suggest to remove the write_() functions that duplicate functionality with `x.save()` from the function reference list, that would make it a lot shorter

**Comment by agramfort** [comment]
> This shouldn't take too long, but looking through the dev I/O reference section I came up with 2 questions:
>
> what is the long term plan for data formats. Is fiff still the standard and other systems should go into an "other systems" section? Or should other formats basically receive equal treatment as fiff? (in which case it might be more appropriate to structure the file I/O section according to the kind of information to load)

fif is still good for now. I think. No rush.

> A lot of objects can be saved with mne.write_x() as well as x.save(), I would suggest to remove the write_() functions that duplicate functionality with x.save() from the function reference list, that would make it a lot shorter

be careful as some offer more features eg. write_evokeds can save
multiple evoked data in one file.

**Comment by christianbrodbeck** [comment]
- How do you feel about double listing? (E.g. `read_proj` under File I/O as well as under Preprocessing)
- the read_raw functions stand out in that they are the only readers that are actually in the `io` module. You don't want them in the `mne` namespace?

**Comment by agramfort** [comment]
>
>
>    - How do you feel about double listing? (E.g. read_proj under File I/O
>    as well as under Preprocessing)
>
> why not

>
>    - the read_raw functions stand out in that they are the only readers
>    that are actually in the io module. You don't want them in the mne
>    namespace?
>
>
i wanted mne.io to be for IO of raw data. We could have named it mne.raw_io
but it seemed too long

**Comment by Eric89GXL** [comment]
> How do you feel about double listing? (E.g. read_proj under File I/O as well as under Preprocessing)

I have been tripped up by this sort of thing before, as it hurts code readability. I'd prefer to change one of the names if it's not too difficult. In this case, something like `read_proj` and `_read_proj` would be fine. I think it would even make sense since one is meant to be publicly used and the other does the low-level reading IIRC.

**Comment by christianbrodbeck** [comment]
@Eric89GXL I did not mean that there are two functions with the same name, just that the same function is listed multiple times in the function reference, under different sections.

**Comment by Eric89GXL** [comment]
Ahh, that's okay with me too then

**Comment by dengemann** [comment]
@christianbrodbeck which problem is left here? Can we close and open new issues with 0.11 tag?

**Comment by christianbrodbeck** [comment]
Hm, I think the idea that was left was to create a "importing data from other systems"  section in the function reference. "Reading raw data" lists the relevant functions now, so I doubt it would change much. Maybe what would be useful for the future would be a re-writing of the "data conversion" section of the Manual, I think in many points the Python data conversion is already improved over the C utilities. I'm closing this here.
