### ISSUE TITLE
reorganize examples

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#1706]
we start to have too many examples with some of them being really for advanced users. We should make first examples more accessible.

I propose to put in a separate folder the advanced ones

**Comment by Eric89GXL** [comment]
This is really a bunch of `git mv` commands. @agramfort I'm sure you have time for this one...?

**Comment by agramfort** [comment]
it's a bit more as I want to take the opportunity to simplify some examples
and make them more entry level

could have a bit of time next week during my holidays...

**Comment by Eric89GXL** [comment]
Same thing with this one @agramfort, I'm moving this to 0.10 for now
