### ISSUE TITLE
Add support for AMICA (modern ICA distributed as binary)?

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#1715]
[AMICA](http://sccn.ucsd.edu/~jason/) is a successor to Infomax. In my experience, it's significantly better than Infomax or fastica. I've started writing a Python wrapper for AMICA, and begun integrating it into MNE, as another possible method besides fastica and infomax when calling ```ica.fit()```.

AMICA probably won't become part of sklearn any time soon though. It's GPL'd, but primarily distributed as a ~5, 10 MB binary (which I'm calling from python), and reimplementing it is far beyond my meagre skills.

Would this wrapper have any chances of becoming integrated into MNE?

**Comment by jona-sassenhagen** [comment]
I have a prototype running. It's very hacky for now, but it works. See http://nbviewer.ipython.org/gist/jona-sassenhagen/752c21f59ca27605ae29

Here, AMICA already delivers many more dipolar (=possibly neurogenic) components than FASTICA, and less component splitting.

**Comment by agramfort** [comment]
@jona-sassenhagen thanks heaps for sharing ! did you make this wrapper public? can you open a PR?

**Comment by jona-sassenhagen** [comment]
It's on my fork, but I have to do some major cleaning up before I'll open a PR. Internally, it's quite messy, as I haven't quite figured out git/github yet. I hope to be able to share it within a week.

**Comment by agramfort** [comment]
my advice is make it public early.

Also we have so far a policy to ship only pure python code to make
packaging "almost" painless on all systems. Relying on an external binary
is a big decision
for the future and I'd much prefer see a python reimplementation of amica.
Experience with infomax rewriting is that our code is now much faster than
the C code / binary from eeglab. And we have no packaging pb...

**Comment by jona-sassenhagen** [comment]
I have submitted a pull request: #1796

**Comment by dengemann** [comment]
> for the future and I'd much prefer see a python reimplementation of amica.
Experience with infomax rewriting is that our code is now much faster than
the C code / binary from eeglab. And we have no packaging pb...

I agree with @agramfort.
