### ISSUE TITLE
ENH: add parameter to ICA to prametrize by rank and take into account SSS

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1717]
If someone feels bored ;-)

**Comment by souravsingh** [comment]
I wish to do this.How do I start?

**Comment by souravsingh** [comment]
@dengemann I wish to work on the siiue.How do I start?

**Comment by souravsingh** [comment]
I wish to work on the issue.How do I start?

**Comment by dengemann** [comment]
Hi @souravsingh take a look here https://github.com/dengemann/meeg-preprocessing/blob/master/meeg_preprocessing/preprocessing.py#L137

you can copy the logic from there, I would call it 'auto' though, then you need a test.

**Comment by jaeilepp** [comment]
And if you haven't already, you might want to check http://martinos.org/mne/stable/contributing.html

**Comment by agramfort** [comment]
this should be easy with the new compute_rank function. Maybe it's even already done

**Comment by larsoner** [comment]
With our new `n_components=0.999999` default I don't think we need this anymore / it's implicitly taken care of.
