### ISSUE TITLE
FIX: Deprecate `method='empirical'` for covariance estimation

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#1722]
Based on #1671, the `'auto'` mode should really work better. @dengemann I think there was some confusion on this point: I don't mean we should remove `'empirical'` as an available method, just deprecate having it as the default method. So for the next release (0.9), we could do the following:

1. Make the default `method=None`.

2. If `method is None`, then use `'empirical'` but warn people that the default will switch to `'auto'` in 0.10.

This way if people truly want to use empirical, they can and avoid warnings by explicitly doing `method='empirical'`. Other people who want to use the newer methods would do `method='auto'`.

**Comment by Eric89GXL** [comment]
I don't think I mind having an `sklearn` dependency for this function / feature by default, given that a user can get back the original behavior by explicitly doing `method='empirical'`.

So what do people think? Should we deprecate? Speak now or forever hold your peace...

**Comment by agramfort** [comment]
you suggest to toggle 'auto' by default and raise an error if sklearn is
not available asking to use "empirical"?

did you try the auto mode? are you happy with it on your data? I don't want
to rush the transition.

**Comment by Eric89GXL** [comment]
I haven't tried it out with my data yet. I am trusting you guys to have tested it extensively :)

I'll give it a shot and let you know.

**Comment by dengemann** [comment]
Note. remove regularize from examples.

**Comment by Eric89GXL** [comment]
I'm going to close this for now, we can re-open later if we decide to move on it
