### ISSUE TITLE
ENH: add GridSearchCV to _RegCovariance

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1727]
... for the sake of completeness.

**Comment by souravsingh** [comment]
I wish to work on this.How do I start?

**Comment by agramfort** [comment]
before digging into these issues can you build the doc and run all the
tests?

**Comment by Eric89GXL** [comment]
@agramfort might be worth doing this one at the same time as #2687

**Comment by Eric89GXL** [comment]
@dengemann @kingjr @jona-sassenhagen any of you want to work on this in the next month for 0.12? I'll move to 0.13 but feel free to change to 0.12 if someone is up for it

**Comment by jona-sassenhagen** [comment]
I'll be busy with rerps I hope.

**Comment by kingjr** [comment]
nope

**Comment by Eric89GXL** [comment]
Do we still need this? It has been open for a long time with no action.
