### ISSUE TITLE
ENH: show whitening in Report if cov and evoked are found

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1730]
cc @mainakjas

**Comment by agramfort** [comment]
+1

**Comment by Eric89GXL** [comment]
Sometimes multiple covariance matrices (empty room, baseline) and evoked
files (multiple files with multiple conditions collapsed differently) can
be included in a report, so we have to figure out how to handle that
gracefully. +1 with that caveat in mind

**Comment by agramfort** [comment]
I would add a --cov param like with we have a --info to specify the cov to
use.

**Comment by mainakjas** [comment]
ok, noted. I will take care of this slightly later :)

**Comment by Eric89GXL** [comment]
@mainakjas do you have time for 0.9?

**Comment by agramfort** [comment]
@mainakjas arrives on friday in Paris for his PhD so he will soon have more
time :)

**Comment by mainakjas** [comment]
indeed :)

**Comment by Eric89GXL** [comment]
@mainakjas do you have time for this now?

**Comment by mainakjas** [comment]
tomorrow!

**Comment by Eric89GXL** [comment]
Cool, will leave marked as 0.9, then. Thanks for helping push us toward release.
