### ISSUE TITLE
FIX/STY: avoid overwriting inbuilt python functions

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1734]
In many places we've got things like `format` inside functions or elsewhere. We should avoid overwriting builtins alltogether.

**Comment by wmvanvliet** [comment]
`format`'s a build-in? I though it was just a method of the base libs (as opposed to `print`, which is a build-in).

**Comment by dengemann** [comment]
Yes it is :) you can try it :) it's the functional equivalent of the method. And it's indicated in -- guess -- all Python syntax schemes accordingly. Compare colors between e.g. `format`, `str` and `np.array`.

**Comment by wmvanvliet** [comment]
so it is… learn something new every day :)

Yeah, we should not overwrite build-in names...

> On 08 Jan 2015, at 13:13, Denis A. Engemann <notifications@github.com> wrote:
> 
> Yes it is :) you can try it :) it's the functional equivalent of the method. And it's indicated in -- guess -- all Python syntax schemes accordingly. Compare colors between e.g. format, str and np.array.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/mne-tools/mne-python/issues/1734#issuecomment-69166074>.
> 

--
Marijn van Vliet
w.m.vanvliet@gmail.com

**Comment by dengemann** [comment]
PR welcome :)

2015-01-08 13:08 GMT+01:00 Marijn van Vliet <notifications@github.com>:

**Comment by TanayGahlot** [comment]
So, What do you propose to use instead?

**Comment by agramfort** [comment]
format -> fmt 

fmt is used in numpy

**Comment by TanayGahlot** [comment]
To resolve this issue i would have to change all the format occurrence to fmt in the source code, can i take it up?

**Comment by agramfort** [comment]
go for it.

**Comment by TanayGahlot** [comment]
can you please elaborate on "fmt in numpy"?

**Comment by mainakjas** [comment]
I think what @agramfort is referring to is the conventions followed in numpy. For example, here: https://github.com/numpy/numpy/blob/master/numpy/core/records.py#L275, they use `fmt` instead of `format`. We should do similarly in our repository. Makes sense?

**Comment by TanayGahlot** [comment]
okay, i get it. Thanks :-)

**Comment by TanayGahlot** [comment]
So if its 
```python 
'{0} ({1})'.format(event_id_rev[ev], np.sum(ev_mask))
```
I have to convert it to
```python 
'%s (%s)'%(event_id_rev[ev], np.sum(ev_mask))
```

**Comment by agramfort** [comment]
you did not get it. It's otherway around. Sometimes we use format not for
string fomatting. See in bti/read.py for example. It's these usage of
format that are wrong.

**Comment by TanayGahlot** [comment]
oh! right coz it overrides the inbuilt.So wherever format is used in similar context as read.py, i have to change that to fmt. Hopefully now i get it.

**Comment by TanayGahlot** [comment]
I have sent PR #1800. Kindly review.
