### ISSUE TITLE
ENH: maybe add pytoolz to externals

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1738]
https://github.com/pytoolz/toolz/tree/master/toolz

https://toolz.readthedocs.org/en/latest/api.html#itertoolz

nice functional iterator patterns that help keeping the utils.py small.

**Comment by agramfort** [comment]
what would you take from it?

**Comment by dengemann** [comment]
Need to explore it a bit further. But almost everything it has seems pretty beautiful. Almost a bit sad this is not the standard library :(

**Comment by dengemann** [comment]
certainly a few things that would help cleaning up control flows and container manipulations:
- concatnenation of sequences `concat` instead of the sum trick or comprehension tricks, also `mapcat`
- `groupby` seems pretty useful, maybe also for channel-wise iteratation
- `sliding_window`
- `partition_by`
- `pipe`, `compose` and `juxt`
- `do` for explicitly handling inplace modifcations
- `get` would also save many checks and apply to any python container

**Comment by agramfort** [comment]
ok some maybe but beware of magic for new contributors.

**Comment by dengemann** [comment]
not urgent but we should keep this in mind and see where it can save us lines and help make our code even more boring :) (wich is good)

**Comment by Eric89GXL** [comment]
I'm -0.5 on using these for now. Perhaps we have to put in a little bit more effort currently to get things done, but it may be slightly more explicit / less magical (instead of having to look into what some function does to really understand). I'm going to go ahead and close, feel free to re-open if you find a compelling use case :)
