### ISSUE TITLE
FIX?  why is ref_meg=False by defaylt for LCMV?

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1739]
should be fixed I guess

**Comment by dengemann** [comment]
It seems LCMV is really broken for CTF data. Just replaced minimum_norm with lcmv in the SPM example --> booom. Ref MEG channels ...

**Comment by agramfort** [comment]
please share a gist to reproduce the pb.

**Comment by dengemann** [comment]
https://gist.github.com/dengemann/d0f385608a1f3d058762

**Comment by dengemann** [comment]
I'm on it.

**Comment by agramfort** [comment]
fixed by #1820
