### ISSUE TITLE
FIX: mayavi imports tend to produce x server crashes on some mashines.

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1741]
would be good to avoid trying mayavi imports by option

cc @fraimondo @mainakjas @agramfort

**Comment by agramfort** [comment]
how come it crashes?

**Comment by dengemann** [comment]
segfaults via SSH

2015-01-13 14:10 GMT+01:00 Alexandre Gramfort <notifications@github.com>:

**Comment by fraimondo** [comment]
It's not a segfault. It simply prints an error: "X server not found" or
something like that and then quits python.

And that happens when mayavi is imported. So all the code in one report
that tries to import mayavi does not work if mayavi is installed on the
system but the x server is not running.

It's a huge deal for distributed processing.
Le 13 janv. 2015 14:21, "Denis A. Engemann" <notifications@github.com> a
écrit :

**Comment by dengemann** [comment]
This should be fixed -- because it will lead to crahses irrespective of
whether you want use Mayavi at all

2015-01-13 14:43 GMT+01:00 Federico Raimondo <notifications@github.com>:

**Comment by agramfort** [comment]
why not doing "ssh -X" ?

**Comment by fraimondo** [comment]
Cause on a distributed environment you don’t have X servers. And sometimes you don’t want to have an X server running. That will increase too much the time to setup the environment.

Simple test to see the error:

In [1]: from mayavi import mlab
ipython: cannot connect to X server

**Comment by agramfort** [comment]
see :

https://github.com/mne-tools/mne-python/blob/debian/debian/rules

for debian we use xvfb to fake the x-server.

would that help?

**Comment by dengemann** [comment]
No it does not help, especially with xvfb-run this poses problems

2015-01-13 15:07 GMT+01:00 Alexandre Gramfort <notifications@github.com>:

**Comment by fraimondo** [comment]
We are currently using that, although it seems that it has some huge memory leaks.


https://bugs.eclipse.org/bugs/show_bug.cgi?id=322108 <https://bugs.eclipse.org/bugs/show_bug.cgi?id=322108>
https://bugzilla.redhat.com/show_bug.cgi?id=498357 <https://bugzilla.redhat.com/show_bug.cgi?id=498357>
https://issues.apache.org/ooo/show_bug.cgi?id=105191 <https://issues.apache.org/ooo/show_bug.cgi?id=105191>

Workarounds that I need to test:
http://blog.jeffterrace.com/2012/07/xvfb-memory-leak-workaround.html <http://blog.jeffterrace.com/2012/07/xvfb-memory-leak-workaround.html>

Nevertheless, if we don’t really need mayavi it would be great not to use xvfb-run.

**Comment by agramfort** [comment]
can you uninstall mayavi on the cluster? or have a venv without mayavi?

**Comment by dengemann** [comment]
We'll subclass Report and overwrite the methods that are a problem.

2015-01-13 15:37 GMT+01:00 Alexandre Gramfort <notifications@github.com>:

**Comment by fraimondo** [comment]
I’m currently doing some tests on that, to see if I can uninstall mayavi and everything works… will keep you updated.

**Comment by fraimondo** [comment]
without mayavi:

Traceback (most recent call last):
  File "/opt/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/opt/cpype/cpype/pipeline/tests/test_pipeline.py", line 219, in test_local_global_persistence
    pipeline.preprocess(raw, notch_filter=False, use_ctps=False, min_events=6)
  File "<string>", line 2, in preprocess
  File "/opt/anaconda/lib/python2.7/site-packages/mne/utils.py", line 526, in verbose
    return function(*args, **kwargs)
  File "/opt/cpype/cpype/pipeline/pipeline.py", line 481, in preprocess
    self._safe_figure(fig, 'Paradigm', section=section)
  File "/opt/cpype/cpype/pipeline/pipeline.py", line 354, in _safe_figure
    self.report.add_figs_to_section(figs, names, section, scale=scale)
  File "/opt/anaconda/lib/python2.7/site-packages/mne/report.py", line 785, in add_figs_to_section
    image_format=image_format)
  File "/opt/anaconda/lib/python2.7/site-packages/mne/report.py", line 720, in _add_figs_to_section
    if isinstance(fig, mayavi.core.scene.Scene):
UnboundLocalError: local variable 'mayavi' referenced before assignment

**Comment by Eric89GXL** [comment]
That should be a fairly easy fix, just need to prepend a check for whether `mayavi` exists before moving on to the `isinstance` conditional, PR welcome :)

**Comment by mainakjas** [comment]
mayavi is used only for rendering `-trans.fif` files. Why not use the pattern matching capabilities in report to render the `-trans.fif` files on a machine with X server capability and the rest of the files without the X server?

**Comment by dengemann** [comment]
The problem is that even if you don't want mayavi at all you still deal
with it. It's imported in add figs to section to check for the type of
object. Maybe that can be avoided.

2015-01-14 18:26 GMT+01:00 mainakjas <notifications@github.com>:

**Comment by mainakjas** [comment]
yeah, we just need a check as @Eric89GXL says

**Comment by agramfort** [comment]
+1 for the check. Report should work without mayavi installed.

**Comment by Eric89GXL** [comment]
@dengemann would it be enough to just require that users for which `mayavi` will crash not have it installed, or do you still need a config option? Not a big deal either way, but it's simpler the former way.

**Comment by tiandiao123** [comment]
may I ask how did you fix this problem? I has same issue.too.

**Comment by fraimondo** [comment]
I don’t really remember.

I think I uninstalled mayavi, or commented out the problematic line in the server source code.

**Comment by Eric89GXL** [comment]
You can uninstall, or edit `mayavi/__init__.py`` or `vtk/__init__.py` to have a `raise ImportError` as their first line if you for some reason don't want to delete them.
