### ISSUE TITLE
ENH: improve epochs.plot (EEGLAB style plots)

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1749]
Actuallys similar to plot raw, only show datasegments from epochs.

**Comment by agramfort** [comment]
do you have a screen shot to illustrate?

On Tue, Jan 20, 2015 at 4:47 PM, Denis A. Engemann <notifications@github.com

**Comment by dengemann** [comment]
Here (from the FASTER paper) used to select bad epochs.

![screenshot 2015-01-20 17 15 09](https://cloud.githubusercontent.com/assets/1908618/5820836/0306151a-a0c8-11e4-9382-644b6a0fbbf3.png)

Would be pretty easy and another conrtrib that removes more lines than it adds (recycling the plot_raw) ;-)

**Comment by agramfort** [comment]
so just calling plot_raw on np.concatenate(epochs.get_data(), axis=0) ?
and adding the red colors?

**Comment by dengemann** [comment]
... just adding the event markers instead. From the current  epochs.plot we still have the bad epoch slection tool. We should somehow transplant it then.

**Comment by agramfort** [comment]
hum... so it's a plot_raw with highlighted bad segments? plot_raw can
already show events.

**Comment by dengemann** [comment]
But this one only shows the epochs. not the rest. Epochs can be pretty remote from another. I think this is  better for data browsing than raw.plot with EEG data, which are often only viewable at that later stage, and it would be a nicer behavior for epochs.plot

**Comment by agramfort** [comment]
ok sounds like a plan. PR welcome :)

**Comment by Eric89GXL** [comment]
@dengemann do you still want this, or were the enhancements to Epochs plotting enough? I guess we could deal with this alongside #2665 potentially.

**Comment by dengemann** [comment]
this was the GSOC with @jaeilepp !!
