### ISSUE TITLE
ENH: support joblib backend API and allow for 'threading'

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1761]
Depending on the python setup and the data inputs spawning / forking may not be the best choice.
We should allow for Parallel(backend='threading').

**Comment by dengemann** [comment]
We should explore this a bit before implementing it. As far as I can tell we gain substantial speedups. However, so far only tested in a context where increasing the number of nobs actually slows things down ...

**Comment by Eric89GXL** [comment]
Where can I read about this? Does it allow sharing memory instead of
serializing it to each worker?

**Comment by agramfort** [comment]
yes but for best efficiency you need cython gil free code.

**Comment by Eric89GXL** [comment]
Do we have any code that releases the GIL? Maybe something that uses `sklearn` somewhere, like the machine learning code? Even then I'm not sure we'd release it enough to be effective. I think we can probably close this.
