### ISSUE TITLE
eliminate_stim_artifact for evoked

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#1773]
eliminate_stim_artifact only accepts raw objects. It makes more sense to remove the artifact on evoked.

eliminate_stim_artifact should accept evoked object.

any taker?

**Comment by dlsrnsi** [comment]
I think its solution is that copy notch_filter method in .io.base.py to evoked.py.

**Comment by agramfort** [comment]
what do you mean the solution?

**Comment by dlsrnsi** [comment]
If you copy notch_filter method in .io.base.py to evoked.py, you can eliminate stim_artifact for evoked, I think.

**Comment by agramfort** [comment]
? stim artifact is not corrected with notch_filter. See how it is done with
raw files.

**Comment by dlsrnsi** [comment]
Oops.. Sorry for my mistake.. I have misunderstood about this issue..

**Comment by agramfort** [comment]
issue should be simpler than dealing with notch filter

**Comment by mainakjas** [comment]
It's `eliminate_stim_artifact` not eliminate stim_artifact :)

Take a look here: https://github.com/mne-tools/mne-python/search?utf8=%E2%9C%93&q=eliminate_stim_artifact

**Comment by dlsrnsi** [comment]
@agramfort Now we can close this issue.
