### ISSUE TITLE
BUG: picks parameter of create_ecg_epochs ignored

### ISSUE THREAD

**Issue by wmvanvliet** [mne-tools/mne-python#1774]
https://github.com/mne-tools/mne-python/blob/master/mne/preprocessing/ecg.py#L268

Surely that should read:

    if picks is None:

instead of

    if picks is not None:

**Comment by dengemann** [comment]
@wmvanvliet oh boy. Fix welcome.

**Comment by wmvanvliet** [comment]
See PR #1776
