### ISSUE TITLE
BUG: Epochs.interpolate_bads_eeg fails when there are also bad MEG channels

### ISSUE THREAD

**Issue by wmvanvliet** [mne-tools/mne-python#1775]
If one or more MEG channels are marked bad, `Epochs.interpolate_bads_eeg` generates a very cryptic error. It should either just ignore MEG channels marked as bad or give a descriptive error message. (maybe both)

**Comment by wmvanvliet** [comment]
See PR #1776

**Comment by agramfort** [comment]
can we close this?
