### ISSUE TITLE
plot events label is incorrect

### ISSUE THREAD

**Issue by mainakjas** [mne-tools/mne-python#1784]
Try running `examples/plot_extract_events_from_raw.py`

![plotev_legend](https://cloud.githubusercontent.com/assets/3817535/6096265/d17aed22-af90-11e4-93dd-8fec8fc14e4b.png)

**Comment by agramfort** [comment]
what's wrong?

**Comment by mainakjas** [comment]
Look at the legend. The numbers in the brackets. Aren't they supposed to reflect the event-id value?

**Comment by agramfort** [comment]
no the number events for each event_id

**Comment by mainakjas** [comment]
woops, makes sense. Sorry.
