### ISSUE TITLE
Deprecate Brainvision internal referencing

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#1790]
Brainvision reader has a separate internal referencing method. This should be deprecated in favor of the new referencing method in  `mne.io.reference`.

**Comment by agramfort** [comment]
any taker?

@wmvanvliet ?

**Comment by wmvanvliet** [comment]
> Brainvision reader has a separate internal referencing method
It does? As far as I can see, it just adds an all-zeros channel, which is useful for re-referencing later. This re-referencing is then done with the methods in `mne.io.reference`.

**Comment by agramfort** [comment]
do we have now 2 ways to do EEG referencing with BrainVision data?

**Comment by teonlamont** [comment]
Could we add the adding the all-zero channels to the reference module? This would make a clean separation of reading module from the referencing one. Also it would make it consistent and easier to maintain.

**Comment by wmvanvliet** [comment]
adding a channel (being zero or not) to a dataset should be implemented at a higher level. An operation that concatenates two datasets along the first (=channels) dimension.

Something vaguely like this:

    raw = mne.io.read_raw_brainvision(...)
    ref_channel = mne.RawArray(np.zeros((1, n_samples)),
                               mne.create_info(ch_names=['REF'], ch_types=['eeg']))
    raw = mne.concatenate_channels([raw, ref_channel])

Perhaps it already exists.

**Comment by wmvanvliet** [comment]
Or another approach: the `set_eeg_reference` function could take an optional `prev_ref` parameter:

    reref, _ = mne.io.set_eeg_reference(raw, ['A1', 'A2'], prev_ref=['Fz'])

which would first add an all-zeros channel 'Fz' and then re-reference the entire thing to the mean of 'A1' and 'A2'.

**Comment by agramfort** [comment]
the raw object should have a state that says the previous reference applied.

any array concat logic should be hidden from the user.

**Comment by wmvanvliet** [comment]
> any array concat logic should be hidden from the user.

Ok. We could store `prev_eeg_reference` as a field in the info dict and make `set_eeg_reference` take this into account. I would still opt to additionally provide a `prev_ref` parameter to deal with the cases in which the info structure does not have the `prev_eeg_reference` field (older raws read from disk, RawArray's created by the user, etc.)

**Comment by agramfort** [comment]
if you use RawArray it's your responsibility to define the eeg_ref in the
info. I'd like to keep the info simple and prefer not to address all crazy
usecases.

**Comment by Eric89GXL** [comment]
Deprecation would be good to get in before 0.9 release if this seems doable.

**Comment by teonlamont** [comment]
closing for #1858.
