### ISSUE TITLE
Create slider for bem

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#1793]
Hey @mainakjas, is it possible to make the bem html sliders if you want to script your own report? currently, it is returning only an array of bem images in my html file.

**Comment by mainakjas** [comment]
mmm ... the function that makes the slider is private: https://github.com/mne-tools/mne-python/blob/master/mne/report.py#L1392. So, no

**Comment by dengemann** [comment]
I'm having the same use case + question:)

**Comment by mainakjas** [comment]
Maybe we should make the function public then :) How about:

```python
html = report.render(subject, subjects_dir, decim, n_jobs)
report.add_html_to_section(html, caption, section)
```

That way, we have maximum flexibility so that any arbitrary html text can be added

**Comment by teonlamont** [comment]
+1. that way we could later extend it so that if we wanted add some text to
the section, we could write a function that writes the html object.

-teon


Teon Brooks, Pre-hD
NSF Fellow, Chateaubriand Fellow
PhD Candidate
Department of Psychology
New York University

**Comment by teonlamont** [comment]
closing for #1859.
