### ISSUE TITLE
Include a 'label' parameter to apply_inverse(). 

### ISSUE THREAD

**Issue by howarth** [mne-tools/mne-python#1797]
Looking at the code I think it is an easy fix. Right now apply_inverse assumes that the 'label' is 'None' when it calls _assemble_kernel. So if a parameter 'label=None' was included in the apply_inverse function then the call to _assemble_kernel could be changed to: 

 K, noise_norm, _ = _assemble_kernel(inv, label, method, pick_ori)

**Comment by Eric89GXL** [comment]
That sounds reasonable. Feel free to open a PR, don't forget to add some tests. I'd look at whatever tests we have for `apply_inverse_epochs` that use the `label=` parameter and adapt those to make tests for the new functionality.

**Comment by teonlamont** [comment]
closing for #1860.
