### ISSUE TITLE
circular stats

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#182]
here is just a gist on circular (phase) data analysis:

https://gist.github.com/4052007

I don't think it's ready for mne-python but at least you're aware it exists.

**Comment by kingjr** [comment]
On this topic: there's a library available here: https://github.com/circstat/pycircstat

and for circular linear correlations, you may use this: https://gist.github.com/kingjr/83b59b518cd1546d2d00

**Comment by agramfort** [comment]
thx

why did you use this gist for?

**Comment by kingjr** [comment]
> why did you use this gist for?

I needed to test whether my sensors/sources vary as a function of the angle of a Gabor patch. That's pretty specific...

But the function is generic; for instance, you can use it to test if the amplitude/the power of a sensor/source is correlated with the phase of another.

**Comment by choldgraf** [comment]
On this note, I was actually chatting with Brad the other day (he used to be in my lab) and he mentioned that a post-doc in their lab had written up a bunch of python functions to do phase-amplitude coupling w/ various methods (phase-locking value, glm, etc). I spoke with the post-doc and he seemed friendly to contributing the code. Let me know if there's interest in that and I can follow up.

**Comment by dengemann** [comment]
Yes sounds good of course!

2015-07-08 11:51 GMT+02:00 Chris Holdgraf <notifications@github.com>:

**Comment by choldgraf** [comment]
From the guy:

> Great idea! I didn't know about MNE-python, so thanks for bringing that to my attention. Keep me updated after your meeting, and I'd like to help incorporate PAC in this repo.

I'll ask him how he feels about working on this next week, or if he's cool with us implementing it. Circular stats aren't my specialty though something that I'm going to be doing more of in the coming months, so perhaps I can help.

Here's what he's got:
https://github.com/srcole/neurosrc/blob/master/spectral/signal_pac.py

**Comment by agramfort** [comment]
cross ref with #1388

**Comment by agramfort** [comment]
see 

http://www.mathworks.com/matlabcentral/fileexchange/10676-circular-statistics-toolbox--directional-statistics-

the topic was brought up again on the fieldtrip mailing list.

**Comment by choldgraf** [comment]
Think it'd be good to have more general "circular stats" functions on top of the PAC stuff?

**Comment by Eric89GXL** [comment]
I'm going to remove the milestone for this since it was originally set for 0.6 (!) and hasn't seen action or volunteer

**Comment by choldgraf** [comment]
I think that's a good idea, but also think circular stats should still be implemented in python somewhere. Does anyone know of a good package for it? We had a lab meeting on this the other day and it seemed that the python world was lacking something similar to the matlab circstats package.

**Comment by kingjr** [comment]
https://github.com/circstat/pycircstat but it's not optimized for matrix operations...

**Comment by larsoner** [comment]
There are some circular stats in `scipy` that look like the `circular_meanangle` in the gist above:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.circmean.html
https://github.com/scipy/scipy/blob/v1.3.0/scipy/stats/morestats.py#L3158-L3199

Let's close for now but if someone is motivated please do try to use these newer functions and see if they are usable
