### ISSUE TITLE
ENH: anatomy + meg script in python

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1821]
We should have a funciton that runs all these steps we usually do via the shell scripts `run_anatomy_tutorial.sh` and `run_meg_tutorial.sh`. Ideally it would also reimplement the bem scripts in python to avoid the weaknesses with respect to path and environment variables. Ideall it would just take the subejcts dir and run everything for eachs subject.

cc @Eric89GXL @agramfort @LauriParkkonen @mainakjas

**Comment by agramfort** [comment]
@lorenzo-desantis might be able to help

**Comment by kambysese** [comment]
@dengemann what do these shell scripts do? Where can I find them?I am working on a script that runs the <i>anatomy</i> routines for a given subject that I just recently sent to @Eric89GXL for comment--that is how I ended up here. It's a [WIP](https://gist.github.com/kambysese/4bdaec63fb6e12b84150) and a rather crude first pass at pythonizing a boat load of shell commands. LMK if it can be of any use, unless @agramfort or @lorenzo-desantis have something more elegant in the works, I can work on improving this.

**Comment by agramfort** [comment]
please share the gist so we can see what you started

**Comment by kambysese** [comment]
Here it is in my dropbox folder (https://www.dropbox.com/s/nsp6gocbbxufhoc/FSrecon.py?dl=0)
btw what happens when you follow the above WIP hyperlink to the gist? it should take you to a public gist, no? :confused:

**Comment by agramfort** [comment]
thx for sharing

**Comment by Eric89GXL** [comment]
I think we have all of the functionality in Python now. @dengemann do you still see a need for a unified script / command?

**Comment by larsoner** [comment]
This is now out of scope here and is the goal of `mne-study-template` and similar efforts
