### ISSUE TITLE
Bug: EDF reader crashes for my file

### ISSUE THREAD

**Issue by ZYROz** [mne-tools/mne-python#1826]
@teonlamont 
Hi,
I was trying to read the following file but it crashes with the error: 
"ValueError: could not broadcast input array from shape (4960) into shape (160)"

File: http://physionet.nlm.nih.gov/pn4/eegmmidb/S001/S001R01.edf

Thanks!

**Comment by teonlamont** [comment]
found it. the structure of the code changed but one line didn't get changed properly. closing for pr #1827.
