### ISSUE TITLE
[ENH] release MNE-Python 0.9

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1837]
@christianbrodbeck @teonlamont @joewalter @wmvanvliet @agramfort @mluessi @Eric89GXL @mainakjas @rgoj .......

We should make a release, it's overdue. Can we please tackle the open issues and PRs that are close to merge? Any reviewing or coding contrib is welcome.
Please list what you want for MNE-Python 0.9.

I think for met it's only #1629, #1795 and #1637.

**Comment by Eric89GXL** [comment]
Instead of listing, I made a 0.9 milestone and will tag the appropriate issues/PRs.

**Comment by dengemann** [comment]
Thanks Eric!

**Comment by teonlamont** [comment]
also, let's try to close any open issue that has been resolved or no longer applicable.

**Comment by Eric89GXL** [comment]
Closing this one so it's not in the list of things to finish for 0.9
