### ISSUE TITLE
BUG: MNE-C 

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1867]
mne_process_raw does not seem to be very strict about what is a data channel.
Data labeled as FIFFV_RESP_CH or FIFF_EVENT_CHANNEL should not be included in filtering.
This is what mne_process_raw seems to do however.

cc @mshamalainen

**Comment by Eric89GXL** [comment]
I'm closing this since hopefully the emphasis is on `raw.filter` now
