### ISSUE TITLE
mne.io.read_raw_fif function?

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#1880]
I was wondering why we don't have a proper `read_raw_fif` function instead of subclassing the Raw.

**Comment by agramfort** [comment]
I guess historical reasons...

**Comment by teonlamont** [comment]
i thought that too but the io module is relatively new, like within the
last two release cycle (I think). would it make sense to add such a
function. it would give a unified io look. We could leave the Raw object
subclassing to prevent breaking backwards compatible. just a thought.

-teon

**Comment by agramfort** [comment]
fine with me :)

**Comment by Eric89GXL** [comment]
+0.5 for me, sounds reasonable

**Comment by teonlamont** [comment]
closing for #1881
