### ISSUE TITLE
FIX: MNE-Report makes unrequested copies of section and memory blows up if integers are used in sections

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1887]
@mainakjas 

```
import matplotlib.pyplot as plt
from mne.report import Report
report = Report()
fig1 = plt.figure()
plt.plot(1, 4)
fig2 = plt.figure()
plt.plot(2, 3)
fig3 = plt.figure()
plt.plot(4, 5)
report.add_figs_to_section(fig1, 'test-figure', '2347')
report.add_figs_to_section(fig2, 'test-figure2', '2722')
report.add_figs_to_section(fig3, 'test-figure4', '1735')
report.save('test-report.html')
```

In this case self._sectionvars will be a dict of sections pointing to an empty string. This probably creates all the trouble. The problem is in _clean_varnames:

In [39]: _clean_varnames('1334')
Out[39]: ''

This is not really desirable. Can we avoid this or is there a reason integer strings are not allowed? Often subjects just have such integer codes.

**Comment by dengemann** [comment]
If it cannot be changed it should be handled either with an error or by adding characters to the string ...

**Comment by dengemann** [comment]
I think the evil comes when section labels are a list of empty strings... then the labels are not unique any more and figures get added everywhere on saving.

**Comment by mainakjas** [comment]
okay, got it. I could reproduce the problem. I'll work on it tomorrow. Maybe we should reconsider @agramfort 's idea of using python's hash function?

**Comment by agramfort** [comment]
whatever works !
