### ISSUE TITLE
plot_topo cosmetics

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#1888]
mne.viz.plot_topo seems a bit half-assed right now, unless I'm missing something. However, when suggesting to a student of mine to use MNE for a basic ERP analysis, I realised for people who'd use MNE mainly for plain old boring ERPs, this is probably an essential feature. I'm currently adding all the minor cosmetic things necessary for basic usage:

- a legend
- an option to set linewidth so plots don't look like crayon drawings
- plot tickmarks and spines
- auto set complimentary label and background color
- channel names

And so on. Is this a good idea, or am I just duplicating stuff already done better elsewhere? I'll submit a PR if you think it's a good idea.
Example of status quo of my additions:

![unknown](https://cloud.githubusercontent.com/assets/4321826/6769484/db92344a-d09d-11e4-8231-2332868f71a6.png)

**Comment by agramfort** [comment]
a very welcome contribution !

**Comment by mainakjas** [comment]
yep, I have wanted the legends too :) I write my custom scripts for that but it would be great if it can be integrated into MNE

**Comment by dengemann** [comment]
Sounds great!

2015-03-22 14:53 GMT+01:00 mainakjas <notifications@github.com>:

**Comment by teonlamont** [comment]
closing for pr https://github.com/mne-tools/mne-python/pull/1890.
