### ISSUE TITLE
Importing bdf files greater >2gb

### ISSUE THREAD

**Issue by brauner** [mne-tools/mne-python#1892]
Hello,

is there any way to import `*.bdf` files which are greater than `2gb`. On the data conversion page on the homepage it is stated:

>Warning

>The data samples in a BDF file are represented in a 3-byte (24-bit) format. Since 3-byte raw data buffers are not presently supported in the fif format these data will be changed to 4-byte integers in the conversion. Since the maximum size of a fif file is 2 GBytes, the maximum size of a BDF file to be converted is approximately 1.5 GBytes

Is there a way that `mne-python` can import it an split it automatically into separate `*.fif` files that all get loaded together whenever one of them gets imported?

**Comment by teonlamont** [comment]
hey @brauner I think that is what is currently implemented in mne-python. Could you try reading in a .bdf and saving the raw file? Our saving function should take care of this automatically.

**Comment by brauner** [comment]
Cheers, @teonlamont I'll try it now and report back.

**Comment by teonlamont** [comment]
@brauner I just noticed that it was a warning for MNE command line tools. That warning as well as the uneven sampling rate are no longer a problem with mne-python.

**Comment by brauner** [comment]
@teonlamont, ok. But I got a strange problem. I cannot find the function `mne_edf2fiff()`. I'm on `Ubuntu` with python-mne installed from the package manager. I updated it with `pip` and even changed to the `git` version with `pip`. Still no luck. Any hints?

**Comment by teonlamont** [comment]
in mne-python, it's `mne.io.read_raw_edf()`

**Comment by brauner** [comment]
d1a1_raw = mne.io.read_raw_edf('/home/ubuntu/E/d1a1.bdf')
    Extracting edf Parameters from /home/ubuntu/E/d1a1.bdf...
    Setting channel info structure...
    Creating Raw.info structure...
    Ready.

`d1a1.bdf` is `2.9gb` and is processed in under a second (`8gb RAM` on my system)... Expected speed or suspicious?

**Comment by teonlamont** [comment]
by default, we set `preload=False`. This loads all of the data header information but not the data themselves. if you would like to load the data, there are two options.

```
raw = mne.io.read_raw_edf(..., preload=False)
raw.preload_data()
```

or 
```
raw = mne.io.read_raw_edf(..., preload=True)
```

**Comment by brauner** [comment]
Thanks, @teonlamont. How can I save

    raw = mne.io.read_raw_edf(..., preload=False)

to a `*.fiff` file. I'm having a hard time finding this in the manual.

**Comment by teonlamont** [comment]
no prob! to save to disk, you can use the method,
raw.save('filename-raw.fif'). this is typically the format that we use to
name files.

Unfortunately, the mne-manual doesn't have any of the python capabilities
listed.

-teon

On Mon, Mar 23, 2015 at 6:00 PM, Christian Brauner <notifications@github.com

**Comment by teonlamont** [comment]
if there are no other problems, I am going to close this issue.

**Comment by brauner** [comment]
Cheers, @teonlamont but I cannot find a `raw.save('filename-raw.fif')` method. Is it called differently?

**Comment by brauner** [comment]
Quick feedback, `mne-python` correctly reads in `*.bdf` files greater than `2gb`, splits them up into multiple `*.fif` files when saving, and reads all of them in together. Thanks again, @teonlamont.

**Comment by teonlamont** [comment]
@brauner i'm glad to hear it! :) and no prob!
