### ISSUE TITLE
apply_reject

### ISSUE THREAD

**Issue by mainakjas** [mne-tools/mne-python#1893]
We should have an `apply_reject` method to `Epochs` that lets you apply peak-to-peak rejection post-hoc. This is useful if you want to apply `fix_stim_artifact` on epochs without preloading the data and then apply rejection.

cc @agramfort

**Comment by dengemann** [comment]
@mainakjas cf.

```Python
class Epochs(mne.Epochs):

    __doc__ = mne.Epochs.__doc__

    def drop_bad_epochs(self, reject=None, flat=None):
        """Drop bad epochs later

        Watchout! This method sets epochs.reject and epochs.flat

        Parameters
        ----------
        reject : dict | None
            The rejection parameters.
        flat : dict | None
            The flat-rejection parameters.
        """
        self.reject = reject
        self.flat = flat
        self._reject_setup()
        drop_inds = list()
        if self.reject is not None or self.flat is not None:
            for i_epoch, epoch in enumerate(self):
                is_good, chan = self._is_good_epoch(epoch,
                                                    verbose=self.verbose)
                if not is_good:
                    drop_inds.append(i_epoch)
                    self.drop_log[i_epoch].extend(chan)
        if drop_inds:
            select = np.ones(len(self.events), dtype=np.bool)
            select[drop_inds] = False
            self.events = self.events[select]
            self._data = self._data[select]
            self.selection[select]

```

**Comment by dengemann** [comment]
I wrote this for myself to do exactly that.

**Comment by mainakjas** [comment]
sounds like you just saved me 2 hours of work ;)

**Comment by dengemann** [comment]
Also useful to first apply ICA and then the reject. ICA is less memory intense on epochs.

**Comment by mainakjas** [comment]
good thing I raised an issue first :)

**Comment by dengemann** [comment]
> sounds like you just saved me 2 hours of work ;)

Feel free to make a joint PR and change the name accordingly

**Comment by dengemann** [comment]
> good thing I raised an issue first :)

you should always do this. I have more of these ....

**Comment by dengemann** [comment]
@teonlamont why close, where's the PR?

**Comment by teonlamont** [comment]
oh, i thought that this was addressed. we thought that this was already in
the repo...

-teon

On Tue, Mar 24, 2015 at 2:32 PM, Denis A. Engemann <notifications@github.com

**Comment by dengemann** [comment]
@teonlamont no someone has to take my code and make a PR :)
