### ISSUE TITLE
tmin and tmax for iter_evoked?

### ISSUE THREAD

**Issue by mainakjas** [mne-tools/mne-python#1898]
Currently, there is no way to crop the real-time epochs. I was thinking that adding a `tmin` and `tmax` parameter to `rt_epochs.iter_evoked()` would address the use case.

**Comment by agramfort** [comment]
can't you do

for ev in rt_epochs.iter_evoked():
   ev.crop(tmin, tmax)

?

**Comment by mainakjas** [comment]
woops, how did I miss that :) works like a charm, thanks!
