### ISSUE TITLE
function _time_gen_one_fold() in mne.decoding.time_gen.py

### ISSUE THREAD

**Issue by cmoutard** [mne-tools/mne-python#1903]
There is an auxiliaire function _time_gen_one_fold() in mne.decoding.time_gen.py (line 890) which seems to be only used by the deprecated functions.
I may be wrong, but maybe it should be added to the deprecated part of the code ?
Not of tremendous importance but I prefer to mention it.

**Comment by agramfort** [comment]
don't need to deprecate private functions

**Comment by cmoutard** [comment]
Ok, good to know, thanks
