### ISSUE TITLE
more sophisticated peak detection

### ISSUE THREAD

**Issue by mainakjas** [mne-tools/mne-python#1905]
c.f. https://github.com/mne-tools/mne-python/pull/984 and http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.signal.find_peaks_cwt.html

cc @Anevar @dengemann

**Comment by Eric89GXL** [comment]
@jasmainak do we still want this? Are there cases where our peak detection functions are failing?

**Comment by jasmainak** [comment]
we can close. I don't have a pressing need.
