### ISSUE TITLE
bug IO with evoked.

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#1906]
use this file

https://dl.dropboxusercontent.com/u/2140486/toto-ave.pkl

and run

```
import cPickle as p
a = p.load(open('toto-ave.pkl', 'r'))
a.save('pouet-ave.fif')
mne.read_evokeds('pouet-ave.fif')
```

can somebody have look?

@Eric89GXL maybe?

**Comment by Eric89GXL** [comment]
I can't even load the file in Python3. Perhaps it is a unicode issue -- was this created on latest master with the unicode fixes, or no?

**Comment by agramfort** [comment]
I can load it on python 2 with current master

**Comment by Eric89GXL** [comment]
Do you know if it was created before or after the unicode fixes?

**Comment by agramfort** [comment]
no idea

**Comment by agramfort** [comment]
ok it's again a problem of IO of sparse data.

If I do

```
import cPickle as p
a = p.load(open('toto-ave.pkl', 'r'))
del a.info['proc_history'][0]['max_info']['sss_ctc']['decoupler']
a.save('pouet-ave.fif')
import mne
mne.read_evokeds('pouet-ave.fif')
```

a.info['proc_history'][0]['max_info']['sss_ctc']['decoupler'] is a CSR sparse matrix.

@mluessi any chance you can have a look?

**Comment by agramfort** [comment]
looks like the a bad file from MNE-C slips through our reading fix.

I have need to have access to the raw file obtained with mne_process_raw...

**Comment by virvw** [comment]
that is strange, the file was NOT processed with mne_process_raw but I do use mne_browse_raw or xfit or ... to visualize

**Comment by agramfort** [comment]
hum... how can I get access to the initial raw file?

**Comment by virvw** [comment]
you can find one exemple of "run2" but the ave is drawn fom several such
runs

https://drive.google.com/folderview?id=0B7AsPwL-EHVlYWY0Nzc5OGQtYjY2MC00YThmLThjNWItMTBmNTJhN2JhN2E4&usp=sharing




On Tue, Mar 31, 2015 at 1:30 PM, Alexandre Gramfort <
notifications@github.com> wrote:

> hum... how can I get access to the initial raw file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mne-tools/mne-python/issues/1906#issuecomment-88053657>
> .
>



-- 
Virginie van Wassenhove
+33(0)1.69.08.1667
Virginie.van.Wassenhove@gmail.com
https://sites.google.com/site/virginievanwassenhove/

**Comment by agramfort** [comment]
@virvw should be fixed with

https://github.com/mne-tools/mne-python/commit/4529854f0518e2393e666e7fc5b0aef33edc8c38

reopen the issue if not

**Comment by virvw** [comment]
@agramfort  I confirm it is fixed. Generated files readable back in python and mne gui suite.

**Comment by agramfort** [comment]
awesome !
