### ISSUE TITLE
ENH/FIX: dealing with huge effect sizes in linear regression

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1917]
In some cases if you encounter t-values around 17 the scipy cdf estimator yields values of 1. This leads to infs in then -log10(p value) computation. I'm wondering whether we should deal with this internally somehow.

**Comment by Eric89GXL** [comment]
perhaps you should regularize your estimates e.g. by using the "hat" option in the t-test calculation

**Comment by dengemann** [comment]
> perhaps you should regularize your estimates e.g. by using the "hat" option in the t-test calculation

we could do that inside our regression function maybe ...
On the other hand I'm wondering what it tells you if your intercept estimate has such crazy t-values ... maybe some offset or baselining issue.

**Comment by Eric89GXL** [comment]
Yeah, either the means are way off (maybe baselining or offset) or the standard deviation estimate is too small to be realistic (could be fixed by "hat")
