### ISSUE TITLE
auto gen layouts

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#1926]
I'm trying to use `plot_topo` with KIT data from our new system that has more sensors than the 157 one but it gives an error because there's no predefined layout. is there a way for one to be generated using the coordinates? I know that `plot_ica_components` renders the channel positions automatically, maybe something like that?

**Comment by dengemann** [comment]
> I know that plot_ica_components renders the channel positions automatically, maybe something like that?

so spot the differences in the :)

I know that it can do so if the sensor positions from the info['chs'] are considered and projected onto 2d, we have code to do that.

**Comment by teonlamont** [comment]
haha, ok, yeah, I was just making sure that there wasn't a function that didn't already do this. I feel like i'm a new function everyday ;) 

how should we handle the fix? maybe we should have a function that's responsible for flattening 3d surfaces that other functions can pull from instead of copying code?

**Comment by dengemann** [comment]
@teonlamont we have all this. Please just look it up and make a PR.

**Comment by teonlamont** [comment]
ok, that's cool with me, it was just that I couldn't tell whether this was
a viz function or a layout because they both do similar things for
different purposes. i wanted to make sure I was needlessly reproducing code.

i guess the most fitting would be make_eeg_layout but it seems like this
title is a bit restricting. i'll make a pr.

-teon

On Fri, Apr 3, 2015 at 12:30 AM, Denis A. Engemann <notifications@github.com

**Comment by dengemann** [comment]
@teonlamont sorry I'm hacking on other stuff at this point. Once I finde a break I'll share a pointer with you. Just see how it's done in the ICA function.

**Comment by agramfort** [comment]
See eg in fieldtrip if there is no existing .lay file for your system

I would work to have this .lay file

**Comment by wmvanvliet** [comment]
the `make_eeg_layout` function does what you want, but for EEG channels. It may be desirable to generalise this function to work on any channel type.

**Comment by wmvanvliet** [comment]
but constructing a proper .lay file is probably the better approach.

**Comment by agramfort** [comment]
for MEG we have a few possible layouts but let's use template files.

**Comment by agramfort** [comment]
+100

**Comment by teonlamont** [comment]
I tired using one of the built-in templates that's in fieldtrip for yokogawa system (KIT) but I don't think these are designed for our system. The layout turned out very strange. what would be the disadvantages of using an automated layout from the sensor info similar to what we do for the eeg?

**Comment by agramfort** [comment]
Generate once for you system and create the lay file. Maybe ask on fieldtrip ml if this file exists somewhere and if not offer to share yours with them

My 2c

**Comment by wmvanvliet** [comment]
The disadvantage is that auto generated layouts are usually not optimal. I find it often beneficial to tweak the location of the plots a little so there is less whitespace between them.

**Comment by teonlamont** [comment]
but there should be an option for an auto layout when the `.lay` or `.lout` are not available. Then the `find_layout` would then just default to `make_eeg_layout` when the optimal layout is not available.

**Comment by agramfort** [comment]
isn't it the case already?

**Comment by teonlamont** [comment]
not for MEG, it just returns none. It works like this for EEG.

**Comment by agramfort** [comment]
for MEG we should have a layout for each system. There are not so many.

**Comment by teonlamont** [comment]
for some reason, I can't find the proper layout for the new KIT in Abu Dhabi. The one in fieldtrip has layout constructed of 440 and our system only has 208. I tried taking a selection of the channels but it rendered a very unusable layout. maybe I need to dig more into how the plots are laid out in fieldtrip and try to port a proper one that way.

**Comment by agramfort** [comment]
+1

generate one and we can improve it afterwards

**Comment by teonlamont** [comment]
I just remembered why I originally made the pr. I can plot my topomaps with `evoked.plot_topomap` without a layout b/c there is a `_find_topomap_coords`. with `plot_topo`, it needs a layout. I will work on the layout and make a pr.
