### ISSUE TITLE
viz/raw.py plot_raw issue

### ISSUE THREAD

**Issue by natalieklein** [mne-tools/mne-python#1928]
Line 596 has: 
if show:
        plt.show(block=block)

It should be:
if show:
        plt.show(block=True)

 (currently it will not block even if option show is set to True)

**Comment by wmvanvliet** [comment]
`block` is a parameter to the function.

    mne.viz.plot_raw(raw, block=True)

will show the plot and block.

**Comment by natalieklein** [comment]
Ah of course... sorry about that, I didn't see that parameter! Thanks!
