### ISSUE TITLE
Documentations TODOs

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#1934]
a WIP list of FAQ / common pitfalls using MNE

- basic Python issues (e.g., paths #2052)
- +/- in Evoked
- the use of Montage
- working with a template brain
- integrate IPython notebooks?

please expand

**Comment by Eric89GXL** [comment]
Also moving this to 0.10 unless @agramfort can bribe someone

**Comment by agramfort** [comment]
bribe with what? beers? :)

**Comment by Eric89GXL** [comment]
I seem to remember you having an office full of people working with you -- maybe you can convince one of them that creating effective documentation is critical in scientific software development, and therefore important for their training and career development.

On second thought -- yeah, let's go with beers.

**Comment by agramfort** [comment]
hehe @mainakjas @yousrabk @teonlamont what do you think? beers or career argument? :)

**Comment by teonlamont** [comment]
do we have an intended date for 0.9 release?

**Comment by Eric89GXL** [comment]
Planning for Friday or earlier, unless there is a compelling reason to wait. @mainakjas's interpolation would have been one for me, but he seems to have just about finished that. I think the issues and PRs currently tagged as 0.9 can be done by then. Making the docs better could also be a potential reason to delay release if someone is willing to tackle it.

**Comment by Eric89GXL** [comment]
Added the idea of having IPython notebooks linked to / in docs from @mainakjas

**Comment by agramfort** [comment]
having a way to have people contributing to the doc via tutorials notebooks
and rendering them in the main doc could facilitate documentation
contributions...

**Comment by Eric89GXL** [comment]
Rolled this into #1495
