### ISSUE TITLE
FIX: Doc building

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#1966]
Some of our references to functions `whats_new.py` use single backticks, some are double. The single get rendered as italic, and the double get rendered as code literals. We could think about getting the single backticks to properly refer to links, but that seems hard. I'm fine just using doubles everywhere. @agramfort WDYT?

**Comment by agramfort** [comment]
+1 for 2 back ticks everywhere

**Comment by teonlamont** [comment]
closing for #1930
