### ISSUE TITLE
API: Epochs classes

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#1982]
Our epochs classes are a bit of a mess. `RtEpochs` subclasses `_BaseEpochs`, and most other classes like `EpochsArray` and the upcoming `EpochsKit` will subclass `Epochs` because `Epochs` has a ton of functions that `_BaseEpochs` has. I propose that `Epochs`, `EpochsArray`, and `EpochsKit` should all subclass `_BaseEpochs`, and `Epochs` should only have the bits of code necessary to load and save the `FIF` version of `Epochs`. (This would make `Epochs` a very small class.) It would separate the FIF-specific functionality from the generally useful baselining/rejecting/etc. functionality.

The problem is that we need to take care of what methods `RtEpochs` cannot handle from the improved base class `_BaseEpochs`, which might take some thinking.

**Comment by Eric89GXL** [comment]
It's probably better to wait until after 0.9 release to do this, so that we can gradually discover any subtle bugs that we introduce from these changes instead of including them in a release.

This should also be coupled with a documentation of what all you can do with Epochs, possibly in table format: preload True/False, proj=True/False/delayed, etc.

**Comment by agramfort** [comment]
+1
