### ISSUE TITLE
FIX: some TFR examples seem broken on master

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1986]
stockwell and multitaper.

cc @agramfort @Eric89GXL

**Comment by dengemann** [comment]
No idea what's wrong here ... might be a blocker. We need to understand what's wrong.

**Comment by Eric89GXL** [comment]
Yeah we should definitely make sure all examples work and the doc builds, and not release until they do so. Hopefully we can take care of this and #1780 in the same pass.

**Comment by agramfort** [comment]
broken? crash or weird output?

**Comment by dengemann** [comment]
The outputs look wrong, see dev exapmles on webpage.

2015-04-20 12:58 GMT+02:00 Alexandre Gramfort <notifications@github.com>:

**Comment by agramfort** [comment]
we have a blocker here. Something went wrong maybe when refactoring
baselining or something

**Comment by Eric89GXL** [comment]
Any idea when it last looked okay? What is it supposed to look like? Is it supposed to look like the non-dev-docs version? If so, I can probably find time tomorrow to bisect and find the problem.

**Comment by dengemann** [comment]
@Eric89GXL maybe before your cuda refacoting? Also didn't you also recently refactor some of this code. Maybe let's git praise (blame).

**Comment by Eric89GXL** [comment]
Can you describe briefly what it's supposed to look like?

**Comment by dengemann** [comment]
![screenshot 2014-12-10 16 12 08](https://cloud.githubusercontent.com/assets/1908618/7309336/acd6f728-ea1d-11e4-87d3-bfd236189f99.png)

for the stockwell roughly

**Comment by dengemann** [comment]
I think this was one original screenshot from the example:

![screenshot 2014-11-20 15 41 55](https://cloud.githubusercontent.com/assets/1908618/7309350/cfaf6dfc-ea1d-11e4-9032-e5f06f256339.png)

**Comment by dengemann** [comment]
Here some info on the original MTM implementation, also plots.

https://github.com/mne-tools/mne-python/pull/1639

**Comment by Eric89GXL** [comment]
bisected the offending commit, naturally it's mine :)

https://github.com/dengemann/mne-python/commit/a19a954b3fbd5a38f5659ba5d294064129c2ea0a

working on it now

**Comment by dengemann** [comment]
We're not good yet ... TF examples are stil broken down here.

**Comment by Eric89GXL** [comment]
This is what I get for stockwell...?
![figure_1](https://cloud.githubusercontent.com/assets/2365790/7484607/6874ad20-f33f-11e4-960e-bad10bec7ddd.png)

![figure_2](https://cloud.githubusercontent.com/assets/2365790/7484609/6b1be8fe-f33f-11e4-9d22-49aee79f4659.png)

**Comment by dengemann** [comment]
Damn it. I don't get that.
What about multi-taper?


2015-05-06 0:57 GMT+02:00 Eric Larson <notifications@github.com>:

**Comment by dengemann** [comment]
rebuilding after cleaning all.

2015-05-06 0:58 GMT+02:00 Denis-Alexander Engemann <denis.engemann@gmail.com

**Comment by Eric89GXL** [comment]
plot_time_frequency_multitaper_sensors I assume you mean:

![figure_1](https://cloud.githubusercontent.com/assets/2365790/7484655/ebefaf1a-f33f-11e4-9e2b-e480caa3c629.png)

![figure_2](https://cloud.githubusercontent.com/assets/2365790/7484656/ee79fc2c-f33f-11e4-8592-bce4ac7d1185.png)

**Comment by dengemann** [comment]
we're good. apologies for the nois, a make clean wa missing.
