### ISSUE TITLE
ENH: future API development for cov methods and behavior of 'auto' option

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#1989]
To be discussed.

I'd like to get rid of `regularize` in our examples. We could do this by shipping a precomputed regularized covariance.

The second thing to consider is the fine tuning of 'auto'. When would it include more than 'shrunk' and 'empirical', and so on.

Finally it would be nice to have an example that shows the impact of the noise cov on the leadfield, similar to SSS sensitivity.

**Comment by Eric89GXL** [comment]
For 0.9 or 0.10?

**Comment by dengemann** [comment]
... we need to at least act upon the `regularize` instances. Either exaplain why they are used or implement my proposed fix for 0.9. The rest might be rather 0.10

**Comment by Eric89GXL** [comment]
If we deprecate `regularize` then we need to allow `compute_raw_data_covariance` to accept a `method` parameter as well...

**Comment by dengemann** [comment]
Not necessariyl, I'm not sure you would need to regularize if you have 50k samples.

**Comment by dengemann** [comment]
The difference will be neglegible.

**Comment by Eric89GXL** [comment]
Ahh, okay. I guess that would mean even a 1-minute empty room @ 1 kHz would be enough, assuming enough epochs are kept. Maybe we just update the docstring of `compute_raw_data_covariance` to say that you shouldn't need to regularize in most cases...?

**Comment by dengemann** [comment]
Yep.

**Comment by dengemann** [comment]
And on top of that you only have grads and mags.

**Comment by dengemann** [comment]
We can see later if a method param could make sense.

**Comment by agramfort** [comment]
sounds like a plan

**Comment by Eric89GXL** [comment]
@dengemann would it be enough for now to replace the `cov` w/regularize in examples with a new cov comptutation that just uses `shrunk`?

**Comment by Eric89GXL** [comment]
...that seems to add ~50 seconds of computation on my machine just for using `method='shrunk'`, so maybe it's not such a great plan.

**Comment by Eric89GXL** [comment]
I'm going to close this, but feel free to reopen if anyone feels we should reconsider `mode` option for `compute_covariance`
