### ISSUE TITLE
plot_lcmv_beamformer.py isn't working

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#1995]
I ran the examples `plot_lcmv_beamformer.py` but it fails with this error:
```python
RuntimeError: label and stc must have same subject names, currently "lcmv-free-lh.stc" and "sample"
```
@yousrabk also got the same error.

**Comment by teonlamont** [comment]
I think @yousrabk has found the solution.

**Comment by yousrabk** [comment]
Ow nothing huge... we were changing the subject name for the label but not for stc (done only in save)
