### ISSUE TITLE
Report, toggle mode

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#1996]
It would be nice to have the behavior of the toggle buttons changed. Instead of being subtracting from the initial state, it should be additive after first click.

init: all the buttons are toggled on.
behavior change: click a button, and it selects the given button.
-click other buttons to add additional sections.

I think it is the case that users typically want to focus on a particular section when it is clicked. currently you have to remove all section but the one you're interested.

**Comment by dengemann** [comment]
Yeah something is not really good with this. But then I also do not want to click any thing to see a figure.

**Comment by Eric89GXL** [comment]
We could have a button that showed all or hid all, then it would only be two clicks to get your isolated plot

**Comment by dengemann** [comment]
I was thinking the same. That would be nice.

**Comment by Eric89GXL** [comment]
Might be safer to have two buttons, `Show all` and `Hide all` just to be clear about what happens in all situations (e.g., if it were one button and half the things were shown, it's unclear what the behavior should be)

**Comment by teonlamont** [comment]
yeah, that was my initial idea but we were brainstorming ways without add'l buttons. I am totally +1 for the additional buttons.

**Comment by agramfort** [comment]
bootstrap has nice ways to make tooltips and dropdown menus if we start to
have too many buttons...

**Comment by mainakjas** [comment]
@teonlamont gave up so fast? ;)

First question, why would you want to see 3 out of 7 sections if all of them are in the report? I don't understand the reason.

If I understand correctly, we need a faster way to navigate to certain sections right? how about a collapsible section wise table of contents? Like this: http://www.w3schools.com/jquerymobile/tryit.asp?filename=tryjqmob_lists_collapsible. We probably don't even need the buttons on top then (I know people like features that are already there but just throwing ideas :)

**Comment by teonlamont** [comment]
@mainakjas I won't have google to teach me javascript on the plane. for the number of buttons, it would be a matter of focusing on particular sections in the report. are you sure you don't want to make that for 0.9, imagine how accomplished you would feel after it was released knowing the world could toggle on and off as many buttons as it would like ;)

**Comment by mainakjas** [comment]
On Wed, Apr 22, 2015 at 12:19 AM, Teon L Brooks <notifications@github.com>
wrote:

> @mainakjas <https://github.com/mainakjas> I won't have google to teach me
> javascript on the plane.
>
:) Enjoy your trip!

> for the number of buttons, it would be a matter of focusing on particular
> sections in the report. are you sure you don't want to make that for 0.9,
> imagine how accomplished you would feel after it was released knowing the
> world could toggle on and off as many buttons as it would like ;)
>
I'll let @agramfort decide that :)

**Comment by agramfort** [comment]
not for 0.9

**Comment by teonlamont** [comment]
@jaeilepp if you need a break from epochs.plot, and are bored, here's something cool to work on ;)

**Comment by dengemann** [comment]
@teonlamont I think the butterflies are really exciting ;)

**Comment by mainakjas** [comment]
what was the consensus here? what do we want? do we want to keep things as it is or do we want some changes?
