### ISSUE TITLE
plot_projs_topomap

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#1999]
`plot_projs_topomap` defaults to the Vectorview-all if a layout isn't specified. `plot_ica_components` uses a neat little helper function `_prepare_topo_plot` to get the position information. I think this would be a good alternative, but the downside is that the `proj` objects don't have an info attribute. if it had this, it would make it easy for non-Vectorview systems.

**Comment by agramfort** [comment]
we could add an info to proj...
