### ISSUE TITLE
ICA label inconsistency

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2000]
There's an inconsistency in how the ICs are labeled in the `ica.plot_components` (index starts at 0) and how they labels when you use `ica.get_sources` (index starts at 1). Is there a reasoning behind this? This was driving me crazy for a bit when I was computing the time course to the topography.

**Comment by teonlamont** [comment]
@agramfort should we keep this behavior?

**Comment by dengemann** [comment]
??? Really?

**Comment by teonlamont** [comment]
https://www.dropbox.com/s/i7eotj4ljhq7sg3/A0129_OLDT1_ica-report.html?dl=0

**Comment by agramfort** [comment]
really ??? ** 2

**Comment by dengemann** [comment]
Ah @teonlamont  you mean the channel names ... Yes, it's like with raw data, channel index 0 : MEG001

**Comment by teonlamont** [comment]
then shouldn't the IC in the topomap have the same name as the channels, it makes it really inconsistent. if i am looking at the time course to determine say, the ecg component, I could easily exclude the wrong IC because of it by being one off.

**Comment by dengemann** [comment]
> if i am looking at the time course to determine say, the ecg component, I could easily exclude the wrong IC because of it by being one off.

just don't select things manually ;)

**Comment by dengemann** [comment]
Not sure, I think it's the same with regular channels right? In the other plots we use the indices, but plot.raw shows channel names. And we never had a channel name with 000.

**Comment by teonlamont** [comment]
> just don't select things manually ;)

lol, unfortunately no ecg channel.

with regular channels you have to specify the channel name, not an index. I feel that the exclude behavior should be the IC name, starting at one `ica.exclude=['IC 001']`  rather than the index, which would mean, the topo plots should start with one. that would be consistent to how we mark bad channels `raw.info['bads']  = ['MEG 001']`

**Comment by dengemann** [comment]
> lol, unfortunately no ecg channel.

but you have magnetometers, ICA will compute a nice ECG from that internally

**Comment by dengemann** [comment]
> I feel that the exclude behavior should be the IC name, starting at one ica.exclude=['IC 001'] rather than the index, which would mean, the topo plots should start with one. that would be consistent to how we mark bad channels raw.info['bads'] = ['MEG 001']

please don't do this to me.

**Comment by dengemann** [comment]
> that would be consistent to how we mark bad channels raw.info['bads'] = ['MEG 001']

It would really be a pain to make it nam-based inside the ICA code. You really should not select ICA components manually for other than exporative purposes.

**Comment by teonlamont** [comment]
> but you have magnetometers, ICA will compute a nice ECG from that internally

yes, but I would remove the wrong component if I were looking at the ic time sources which is marked `IC 003` but has the topography of `IC #002`.


> It would really be a pain to make it nam-based inside the ICA code. You really should not select ICA components manually for other than exporative purposes.

but then the selection of the heart beat is circular if you don't have an ecg channel to correlate with.

**Comment by dengemann** [comment]
> but then the selection of the heart beat is circular if you don't have an ecg channel to correlate with.

can we talk? hangout?

**Comment by teonlamont** [comment]
yeah, sure :)

**Comment by dengemann** [comment]
So maybe we can relax our channel naming here a bit and call on exporting the ICA time courses into Evoked,Epochs,Raw match the channel names with the indices.

I'd not be opposed. cc @agramfort @fraimondo

**Comment by teonlamont** [comment]
I think this is now resolved with the new plotting
