### ISSUE TITLE
Extrapolated MEG field on scalp surface

### ISSUE THREAD

**Issue by BushraR** [mne-tools/mne-python#2002]
Is there a possibility to get projected field maps on scalp surface in MNE-python
make_field_map currently is projecting MEG field maps on helmet surface only

Thank you

**Comment by agramfort** [comment]
As far as I know not yet sorry

**Comment by BushraR** [comment]
in the file 
mne-python/mne/forward/_field_interpolation.py
in the definition of  make_field_map

on line 383          _make_surface_mapping(evoked.info, this_surf, this_type,
                              trans, n_jobs=n_jobs)
Do you think if this function is called with head surface instead of helmet surface for MEG evoked data, then that would solve my problem and give extrapolated MEG fields to scalp instead of helmet?

**Comment by agramfort** [comment]
that's worth trying !

**Comment by yousrabk** [comment]
Yes actually I was using this function to plot the MEG fields to the scalp, you just need to give the surface you want and it will do a re-mapping to that surf.

Do you need the code?
Or I can open a PR with the changes, if we want to add this option the make_field_map.

**Comment by mainakjas** [comment]
beware though with using a private function. There's no guarantee that we will support it or that it will be available in future `mne` versions. It can be a temporary workaround for now. The more permanent solution is what yousra suggests with a PR

**Comment by BushraR** [comment]
It would be great if I can have a code even if it is a temporary workaround. I need those extrapolated values for my current analysis. Thank you

**Comment by yousrabk** [comment]
@BushraR hope the PR #2005 is doing what you wanted.

**Comment by BushraR** [comment]
Thank you so much
