### ISSUE TITLE
mne report scaling broken

### ISSUE THREAD

**Issue by mainakjas** [mne-tools/mne-python#2014]
@teonlamont reported that scaling is broken. He gets reports with figures that have rotated figures like this one: https://plus.google.com/photos/albums/psjtfo8thlrdqa88m7qqn37ldkt235u54?pid=6140987061440567634&oid=108662407417175145691

@dengemann seems like git praise points to you :) https://github.com/mne-tools/mne-python/commit/011511b6846e5e76c8edf661f33e2bc35993c37c 

Also, I tried briefly and I got this: 

```py
RuntimeError: Could not set the fontsize
```
when `scale` was less than 1.0.

**Comment by dengemann** [comment]
Could you please provide a minmal report examples to reproduce this?

I cannot:

https://gist.github.com/dengemann/e24941a27bc77056461d

**Comment by mainakjas** [comment]
weird, I can't reproduce it any more too. I'll let @teonlamont post a script to reproduce the other bug while I try to figure out what I did to reproduce that.

**Comment by mainakjas** [comment]
ok, this does it:

```py
from mne.report import Report
from mne.datasets import sample
from mne import read_evokeds
report = Report(verbose=True)

path = sample.data_path()
fname = path + '/MEG/sample/sample_audvis-ave.fif'
evoked = read_evokeds(fname, condition='Left Auditory', baseline=(None, 0),
					  verbose=True)
fig = evoked.plot(show=False)
fig.set_size_inches(3, 2)
report.add_figs_to_section(fig, captions='Left Auditory', section='evoked',
						   scale=0.9)
report.save('report.html', overwrite=True)
```

**Comment by dengemann** [comment]
Well this is not really a bug ... you cannot scale this smaller than the smallest fontsize. It just does not throw a nice error.

**Comment by dengemann** [comment]
see for scaling 0.5 with this example:

https://www.dropbox.com/s/oi7y927vk5jioif/Screenshot%202015-04-24%2003.24.14.png?dl=0

**Comment by mainakjas** [comment]
okay, point taken. A nicer error would be good to have.

@teonlamont could you reproduce the other problem?

**Comment by Eric89GXL** [comment]
If this is a release blocker it would be good to sort it out.

**Comment by dengemann** [comment]
Teon, can you share a script to trigger the second issue? The scaling issue is not a release blocker.

**Comment by teonlamont** [comment]
```python
p = epochs.plot_drop_log(show=False)
r.add_figs_to_section(p, 'Drop log of the events', 'Summary',
                      image_format='png', scale=.25)
```

**Comment by Eric89GXL** [comment]
Can you add the necessary boilerplate before those lines using the sample dataset to make it cut-and-paste runnable? It is more DRY for you to do it instead of all of the rest of us who want to test it :)

**Comment by teonlamont** [comment]
```python
import os.path as op
import mne
from mne.report import Report 
from mne.utils import _TempDir


r = Report()
tempdir = _TempDir()
data_path = op.join(mne.datasets.sample.data_path(), 'MEG', 'sample')
raw_file = op.join(data_path, 'sample_audvis_raw.fif')
event_file = op.join(data_path, 'sample_audvis_raw-eve.fif')

raw = mne.io.read_raw_fif(raw_file)
events = mne.read_events(event_file)
epochs = mne.Epochs(raw, events, None, tmin=-.1, tmax=.4,
                    reject={'grad': 1e-10}, preload=True)
p = epochs.plot_drop_log(show=False)
r.add_figs_to_section(p, 'Drop log of the events', 'Summary',
                      image_format='svg', scale=.25)
r.save(op.join(tempdir, 'test.html'))
```

**Comment by Eric89GXL** [comment]
I actually see two bugs -- if the window is big, I see the one I assume you've reported:

![screen shot 2015-04-28 at 11 23 25 pm](https://cloud.githubusercontent.com/assets/2365790/7385586/a93d817a-edfd-11e4-99fb-323a727df41b.png)

But if I shrink the window, for some reason the top bar wraps and screws up the rendering further:

![screen shot 2015-04-28 at 11 23 35 pm](https://cloud.githubusercontent.com/assets/2365790/7385589/b81cff0e-edfd-11e4-9f6c-a3fc6b3f97a5.png)

**Comment by agramfort** [comment]
these are CSS issues we've always had right?

if it's the case it's not a blocker to me.

you can click on blue arrow in progress bar to go around the second bug.

**Comment by dengemann** [comment]
Not a blocker, at these low values of scale I'm surprised it works at all.
And normally you should not need to downscale things. Rather upscale.

2015-04-29 9:32 GMT+02:00 Alexandre Gramfort <notifications@github.com>:

**Comment by agramfort** [comment]
I agree.

**Comment by mainakjas** [comment]
This script does not run for me and I get the error that I was getting earlier. Changing the scale to a larger value, I don't see inverted fonts. @teonlamont can you reproduce this error for larger scales? If not, we just need to add a more explicit error which checks against the current font size and warns the user if it's too low.

**Comment by teonlamont** [comment]
ok. if it's easy to add a warning that would be nice, or even a note to say this only scales up images/figs.

**Comment by Eric89GXL** [comment]
On it in #2039, see if you're happy @teonlamont @mainakjas
