### ISSUE TITLE
'Opt' button doesn't do anything in plot_raw

### ISSUE THREAD

**Issue by choldgraf** [mne-tools/mne-python#2020]
When I plot a Raw object with `plot`, there is a little box in the bottom left called `Opt`. Whenever I click it, nothing seems to happen. I looked into the code and it seems like this is supposed to bring up an options box of some kind. Does this work for other people? Maybe it's because I'm calling the function from an ipython notebook? Does it only work on certain graphics engines?

**Comment by Eric89GXL** [comment]
It might only work for the Qt backend, not sure

**Comment by choldgraf** [comment]
Hmm, I believe that I'm using Qt...

**Comment by Eric89GXL** [comment]
you might need to be in "interactive mode", can you try from a standard Python terminal with `plt.ion()` called?

**Comment by choldgraf** [comment]
Hmm, I've tried calling `plt.ion` both in the ipython notebook, as well as from an ipython session in the terminal. These are after calling `plt.switch_backend('Qt4Agg')`. If I put the code into a python script and run it, then a window pops up but immediately closes...

**Comment by Eric89GXL** [comment]
I just ran this on OSX 64-bit Anaconda Python, and it worked fine:
```
>>> import matplotlib.pyplot as plt
>>> plt.ion()
>>> import mne
>>> data_path = mne.datasets.sample.data_path()
>>> raw = mne.io.Raw(data_path + '/MEG/sample/sample_audvis_raw.fif')
>>> raw.plot()
<matplotlib.figure.Figure object at 0x105f457d0>
>>>
```
Clicking "opt" brought up another window with a SSP selection. I can try it on Linux system Python on Monday, but I'm pretty sure it works there, too.

**Comment by Eric89GXL** [comment]
Maybe the window that appears is falling behind the original one for you?

**Comment by choldgraf** [comment]
Ah - do you need to have MEG information in there in order for that button
to work? I've just been creating Raw objects from random data using
RawArray.

**Comment by Eric89GXL** [comment]
You might need projectors, yeah. It would be great to have a PR that greys out the button text if no projs are available!

**Comment by Eric89GXL** [comment]
(FWIW projectors can be for MEG or EEG data, but using the `*Array` functions you'd probably end up with them only by using our preproc functions.)

**Comment by choldgraf** [comment]
OK cool - at some point I'd like to improve the raw plotting anyway, so
maybe that's something to put on the to-do list. If there's ever an MNE
code sprint that I can attend, that'd be a fun thing to work on. I really
like how EEG-lab lets you change the scales of things on the fly, change
window size, etc.

**Comment by Eric89GXL** [comment]
Yeah, I think there's an issue for that. The problem with waiting for an `mne` sprint is that @agramfort is in Europe so he tends to host them over there :)

**Comment by choldgraf** [comment]
Fair enough... Maybe we can have a mne West sprint!

**Comment by agramfort** [comment]
>
> Yeah, I think there's an issue for that. The problem with waiting for an
> mne sprint is that @agramfort <https://github.com/agramfort> is in Europe
> so he tends to host them over there :)
>
if you take my role i.e. write the grants to host them in the US I'd be
happy to join :)

**Comment by dengemann** [comment]
@choldgraf the EEGLAB scaling stuff is btw. something we plan to implement in this year's google summer of code, also an improved epoch viewer.

**Comment by choldgraf** [comment]
sounds good @dengemann, this would certainly be helpful. Perhaps I can do something to help when I am visiting in July!

**Comment by choldgraf** [comment]
@Eric89GXL what kind of MNE userbase do you guys have up in Seattle? I wonder if there are pots of money at the UW / UCB institutes for Data Science for stuff like this...

**Comment by Eric89GXL** [comment]
There are a number of people using it at ILABS, but I haven't really looked into getting money from the data science centers. If you have time to look, I'm happy to help out or talk to people locally.

**Comment by choldgraf** [comment]
Cool - I will keep an eye open here at Berkeley. I know that the Berkeley
Institute for Data Science (BIDS) has a physical space w/ lots of breakout
rooms etc. It's pretty nice and they're pretty open to people utilizing it
for open source projects (e.g., the ipython team hangs out there pretty
frequently).

**Comment by agramfort** [comment]
@Eric89GXL you should have a chat with @jakevdp at UW

@choldgraf you should do the same with @fperez at UCB

just doing data science match making on github... :)

**Comment by Eric89GXL** [comment]
Actually -- @jakevdp or @fperez do you know of a good resource for hosting a ~2GB public dataset? We need to allow maintainers from multiple institutions (UW, Telecom ParisTech, MGH, etc.) to have ownership / modification permissions, and up-time is important. Do you have any experience with hosting services at UW or elsewhere (e.g., Amazon)? We would strongly prefer a free solution :)

**Comment by choldgraf** [comment]
Didn't github just release a "Large File Storage" service [1]? I think 1GB
is free so this would be higher than that, but might be relevant.

Chris

[1] https://git-lfs.github.com/

**Comment by choldgraf** [comment]
Random followup - I just chatted with some folks at BIDS here at UC Berkeley and they said that we could almost certainly get a room for a few days for a code sprint, possibly funding for some food etc as well but we'd need to look into that further.

@agramfort in your experience what kinds of resources are necessary in order to put on a code sprint? Perhaps having something over here on the west coast is more possible than thought.

**Comment by agramfort** [comment]
if you fly people over you need travel money and housing.

FYI for the sprint this summer we asked for 15k€ and we hope to be able to
fly people from europe and a few from the US

**Comment by choldgraf** [comment]
OK cool, that was my main question (about travel + lodging). I think something like BIDS can easily help with the lighter side of things, but stuff like lodging (unless that means staying on friends' couches) and stuff like travel (unless that means walking up and down the west coast ;) ) would take more to set up. 

Still might be possible, but maybe @Eric89GXL and I can just keep it in mind in the coming months. If flights across the Atlantic are an issue we could always do a simulcast or something, and conduct two sessions separately.

**Comment by agramfort** [comment]
ok. Let's hope the french economy allows us to travel you guys over here :)
