### ISSUE TITLE
plotting bug with `plot_components` with EEG montage

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2026]
I am currently working with some biosemi data and I noticed one bug and one enhancement that should be addressed before the release.

the first is the bug: when plotting the IC for the EEG data, only one topo plot is currently being plotted while the rest are left empty.

![figure_1](https://cloud.githubusercontent.com/assets/1578674/7339415/bc648712-ec3b-11e4-8c5a-f645092ad2c5.png)

the second is a feature enhancement: when using `ica.plot_components`, the plotting function should not default to `meg` especially when there are no meg channels present in the data. the default ch_type should be None. we should inspect the channel types, and if there are no meg channels, we should plot the EEG, if we have meg only, then plot meg, then if we have both, probably the default should be meg but that can be discussed.

**Comment by dengemann** [comment]
bug fix yes, enhancement time is over. please noe new ENH requests.

**Comment by dengemann** [comment]
@teonlamont I'm plotting ICs for EEG data almost every day. Can you share a snippet of code to reproduce this?

**Comment by agramfort** [comment]
it's a backend pb I suspect. Try starting ipython with --gui=qt or
something along these lines

**Comment by teonlamont** [comment]
how do you do that from a PC...? lol

**Comment by dengemann** [comment]
@teonlamont what do you mean? On a PC ipython is supposed to work.

**Comment by teonlamont** [comment]
with the flag --gui=qt. there's a separate application that is loaded for ipython

**Comment by dengemann** [comment]
@teonlamont with anaconda there should be a linux terminal emulator.

**Comment by teonlamont** [comment]
ok, @dengemann, I will make a separate issue for the `ch_type`. i think it would be a broader plotting feature to look at for any plot that requires a ch_type as input.

**Comment by dengemann** [comment]
>  i think it would be a broader plotting feature to look at for any plot that requires a ch_type as input.

yes, I suggested that already a few times during seprate discussions. We should implement it once, carefully and consistently.

**Comment by teonlamont** [comment]
@dengemann I will give it a look tomorrow and report back wrt to the linux terminal emulator. I just left the lab. I didn't know if it was our problem or a backend one.

**Comment by teonlamont** [comment]
> yes, I suggested that already a few times during seprate discussions. We should implement it once, carefully and consistently.

yeah, I remembered it being discussed and i had thought it had been addressed.

**Comment by dengemann** [comment]
open an issue and we'll re-discuss it.
