### ISSUE TITLE
ENH ch_type = None should default to channel types presented

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2027]
when using ica.plot_components, the plotting function should not default to meg especially when there are no meg channels present in the data. the default ch_type should be None. we should inspect the channel types, and if there are no meg channels, we should plot the EEG, if we have meg only, then plot meg, then if we have both, probably the default should be meg but that can be discussed.

this should also be considered for other plotting functions that uses the `ch_type` argument.

**Comment by dengemann** [comment]
My porposal would be:

- defalut to 'mag' if it has mags
- default to 'eeg' if does not have 'meg'

**Comment by dengemann** [comment]
comment updated.

**Comment by agramfort** [comment]
Sounds good

**Comment by teonlamont** [comment]
+1

**Comment by jona-sassenhagen** [comment]
This would be cool to have, I remember I was very confused by this a few times when I was starting out with MNE (as an EEG person).

**Comment by teonlamont** [comment]
@jona-sassenhagen totally agree. I think it is because before MNE used to have a predominate MEG leaning since it's default filetype is FIF from Elekta. I think it is now coming around to be extremely powerful for EEG as well. This is why I would like to do away with blanket MEG defaults.

**Comment by Eric89GXL** [comment]
I think @dengemann's proposal should work for this particular case, @teonlamont do you agree?

**Comment by agramfort** [comment]
PR welcome

**Comment by teonlamont** [comment]
@Eric89GXL i agree with the proposal

**Comment by Eric89GXL** [comment]
I'm on this one
