### ISSUE TITLE
Montage __repr__

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2042]
Since some montages have the fiducials in the file, the `__repr__` is incorrect.

for instance `biosemi-64` displays the following:

``<Montage | biosemi-64 - 67 Channels: Fp1, AF7, AF3 ...>``

**Comment by agramfort** [comment]
PR on the way?

**Comment by teonlamont** [comment]
I can do it tomorrow afternoon. preparing for my department talk tomorrow :/ and noticing things as I am powering through.

**Comment by teonlamont** [comment]
I think to fix this, we need to have point_types, the fiducials are being counted as channels in the representation

**Comment by agramfort** [comment]
Improve the doc and message is easier
