### ISSUE TITLE
ICA labeling

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2043]
to keep track of #2019

there's a discrepancy between labels in `plot_components` and the labels from `get_sources`.

one possibility: `ica.plot_sources` could use the raw viewer when passed raw inst. That would
avoid the conversion to raw instance with get_sources

**Comment by dengemann** [comment]
it could have a viewer argument or so ... for now it also allows you to non-interactively plot time series, which in itself can be useful.

**Comment by teonlamont** [comment]
closed for #2251
