### ISSUE TITLE
EHN: report save when error?

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#2050]
@dengemann Do you know whether it would be feasible to automatically save the report if there's an error and catch the latter without having to explicitly put the report.save() in a try/except condition?

**Comment by dengemann** [comment]
Sounds like that would take some hacking ... for example via with statements. I'm not sure we want to untroduce a syntax like that:

```Python

with Report() as report:
    # do stufff

```

**Comment by dengemann** [comment]
Leaving the with block-- whether due to a crash or whether due to success-- the report would then be saved for eaxmple ...

**Comment by Eric89GXL** [comment]
that looks like a decent syntax

are the errors in the report code or your local code?

**Comment by dengemann** [comment]
> that looks like a decent syntax

just a bit more elegant than wrigin try/catch blocks in your script.

**Comment by kingjr** [comment]
these are for my error, but yes I'm indeed trying to find a way to avoid doing
```
try:
   launch()
   a()
   very()
   long()
   pipeline()
report.save()
```
in all my scripts

**Comment by dengemann** [comment]
You would the write instead:

```
with Report as report:
   launch()
   a()
   very()
   long()
   pipeline()
```

**Comment by dengemann** [comment]
1 line saved ...

**Comment by kingjr** [comment]
Ok, I need to think more. Maybe there's a better way of setting the report than what we're doing in the current pipeline form.

**Comment by kingjr** [comment]
How about having an automatic saving + overwrite everytime the report is modified?
```
report, run_id, results_dir, logger = setup_provenance(script=__file__, results_dir=results_dir, continuous_saving=True)
```

**Comment by dengemann** [comment]
Maybe let's move this discussion to meeg-preprocessing. We could subclass report inside and overwrite the save method to allow fo such things if requested.

**Comment by kingjr** [comment]
ok

**Comment by dengemann** [comment]
To make this work at the MNE-Python level we would need to find a scalable
way of updatting HTML +  dumping to files incrementally. The brute way
(overwriting) might be less performant.

2015-05-01 18:32 GMT+02:00 J-R King <notifications@github.com>:

**Comment by kingjr** [comment]
It's less performant, but most HTML are not that heavy, so overwriting wouldn't be a major issue, should it? (But yes, ideally, it would be incremental,  but IMO that'd be a big piece of work, for a small feature)

**Comment by dengemann** [comment]
let's check it out in our meeg-preprocessing playground sandbox

2015-05-01 18:56 GMT+02:00 J-R King <notifications@github.com>:
