### ISSUE TITLE
Naming consistency for montages/neighbors

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2067]
There should be some consistency between the montage name and the corresponding neighborhood file. For `biosemi-32.txt` but `biosemi32_neighb.mat`. We should have either both hypenated or neither.

**Comment by agramfort** [comment]
these files are the same as fieldtrip. let's try to keep it this way to
avoid confusion

**Comment by teonlamont** [comment]
ok, the neighbor files are from fieldtrip indeed but the montage files were generated from the biosemi site and they were recently added.

**Comment by Eric89GXL** [comment]
Ahh, so we could change the montage files to match FieldTrip. I'm fine with that.
