### ISSUE TITLE
identify channels in butterfly plot

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2071]
It would be great if there would be a way to identify a bad channel in the topo butterfly plot. sometimes you just don't know how bad a channel is until you plot it among the others.

**Comment by agramfort** [comment]
You mean click a line in evoked plot and get channel name?

**Comment by dengemann** [comment]
> It would be great if there would be a way to identify a bad channel in the topo butterfly plot

for that just don't pick it away don't plot with exclude='bads', and it will be displayed.

**Comment by teonlamont** [comment]
@agramfort yes, that.

**Comment by Eric89GXL** [comment]
http://matplotlib.org/1.4.0/users/event_handling.html#object-picking

I might try getting it working this morning, and also making it so that our `raw` plotting uses this instead. IIRC right now it does something with display ranges, which doesn't seem as elegant.
