### ISSUE TITLE
Q: Dataset versions

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#2074]
Have we gotten any useful information from embedding dataset versions in our tarballs? As far as I can tell it has just led to a bunch of warnings when doing imports (see e.g. Mainak's recent notebook examples). I propose we get rid of them for now, and replace them with a new system in the future if need be. But for now I think it's beyond YAGNI and into the adding-annoyance category...

**Comment by agramfort** [comment]
I agree it's nice but I personally hack it manually...

fine with removing the check/warning but we should keep it accessible

sample.version ?

**Comment by Eric89GXL** [comment]
Yeah that makes sense, I'll keep it there but remove warning
