### ISSUE TITLE
Examples take too long to run

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#2088]
A few of our examples take a very long time to run. This includes `plot_covariance_whitening_dspm.py` and especially `plot_spm_faces_dataset.py`. We should probably fix these before release.

**Comment by dengemann** [comment]
Well it's the nature of some examples that they take longer, especially these two.

**Comment by Eric89GXL** [comment]
There are two problems with it, though:

1. Users will not understand why the examples are taking so long, and might not like it. This we could probably deal with using comments.

2. It makes testing docs a big pain.

I wonder if there is some way we can get them to run faster.

**Comment by agramfort** [comment]
In sklearn the very long examples are put in a different folder called
applications but it's different here...

**Comment by Eric89GXL** [comment]
It makes it really difficult to test doc building when the spm-faces example takes so long. Is it okay if I tag a couple of the really slow examples such that we can do something like `make html_dev-noslow` or so?

**Comment by dengemann** [comment]
Good idea!
