### ISSUE TITLE
ENH/DOC: more structure to and cleanup examples in the general section

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#2099]
- section on data io
- Unify reading and plotting examples,
e.g. read vs estimate copvariance
- MEG processing
- advanced processing
- forward / MRI stuff

**Comment by Eric89GXL** [comment]
I'm pretty sure we have an issue for this open already, can you deduplicate with that one?

**Comment by agramfort** [comment]
I am doing a pass on it now
