### ISSUE TITLE
FIX? sample.data_path(force_update=True, download=True) does not seem to download the newest dataset

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#2105]
Am I missing something?

@Eric89GXL @agramfort

**Comment by dengemann** [comment]
On manual download I get version 0.7, the shrunk cov files are missing.

**Comment by dengemann** [comment]
Build november 2013

**Comment by Eric89GXL** [comment]
The shrunk cov files haven't been added yet. It probably is re-downloading fine, and we just need to update the dataset.

**Comment by Eric89GXL** [comment]
If you do it with `verbose=True` you should see the status update as it downloads to confirm it's updating.

**Comment by dengemann** [comment]
> The shrunk cov files haven't been added yet. It probably is re-downloading fine, and we just need to update the dataset.

we should do that because otherwise the example will be broken on mne stable.

**Comment by Eric89GXL** [comment]
For now we'll have to work with Martin or Hari to get that done. I might know more on Wednesday that will allow us to do it ourselves, which is why I've been waiting.

**Comment by dengemann** [comment]
> For now we'll have to work with Martin or Hari to get that done. I might know more on Wednesday that will allow us to do it ourselves, which is why I've been waiting.

**Comment by Eric89GXL** [comment]
I haven't considered it a blocker because I think we can get it working in short order, and the probability of someone hitting the issue in the couple of days there is a discrepancy should be small

**Comment by dengemann** [comment]
> and the probability of someone hitting the issue in the couple of days there is a discrepancy should be small

Well, a bunch of examples won't work without the update.

**Comment by Eric89GXL** [comment]
True, I think there are three or four that need it. I think the probability of someone hitting those in the intervening days is small, but if you disagree we can wait

**Comment by Eric89GXL** [comment]
...and you should work with Hari and Martin about getting it included

**Comment by Eric89GXL** [comment]
The file is here:

http://staff.washington.edu/larsoner/sample_audvis-shrunk-cov.fif

**Comment by Eric89GXL** [comment]
Never mind, I'll take care of it

**Comment by Eric89GXL** [comment]
All better
