### ISSUE TITLE
indexing Dipole

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#2108]
it would be great to be able index instances of Dipole e.g. to do:

`dipole[dipole.gof > 0.8].plot_locations()`

we should be able to do:

```
dipole[dipole.gof > 0.8]
dipole[:5]
```

as if we had 1d numpy array of dipoles.

@jmontoyam It would simplify your scripts.

**Comment by Eric89GXL** [comment]
@agramfort how urgently is this needed? It should be fairly straightforward so I could do it, but it might be good for a new contributor if they want to take it

**Comment by agramfort** [comment]
I think @jmontoyam should give it a try as a first contrib.

**Comment by jmontoyam** [comment]
@agramfort, @Eric89GXL 

What do you think about this solution?
https://github.com/jmontoyam/mne-python/blob/fix-issue-2108-Dipole/mne/dipole.py#L193

**Comment by agramfort** [comment]
Open a PR please

Thx
