### ISSUE TITLE
Potential bug with concatenate_raws

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2121]
I tried to concatenate two `RawKIT` objects with `preload=True` for each and this worked fine. Then I tried `preload=False` and this gave an error when I tried `raw.preload_data()`. I get a 
`ValueError: total size of new array must be unchanged` so I delved down in the code and found in `_read_segment`, the code isn't being told where file1 is stopping and file2 is beginning, it tries to read it all from file1.

Are we supposed to be able to do `preload_data` for concatenated unpreloaded files. Also, for naming purposes, should it be called `load_data()` instead of `preload_data()` since it's not being preloaded

**Comment by agramfort** [comment]
> I tried to concatenate two RawKIT objects with preload=True for each and this worked fine. Then I tried preload=False and this gave an error when I tried raw.preload_data(). I get a
> ValueError: total size of new array must be unchanged so I delved down in the code and found in _read_segment, the code isn't being told where file1 is stopping and file2 is beginning, it tries to read it all from file1.

can you reproduce the pb with the test kit file we have in the repo?

> Are we supposed to be able to do preload_data for concatenated unpreloaded files. Also, for naming purposes, should it be called load_data() instead of preload_data() since it's not being preloaded

-1 we should avoid API changes unless there is a clear API issue.

**Comment by teonlamont** [comment]
```python
import mne
from mne.io.kit.tests.test_kit import sqd_path


raw = mne.io.read_raw_kit(sqd_path, preload=False, verbose=False)
raw2 = mne.io.read_raw_kit(sqd_path, preload=False, verbose=False)

mne.concatenate_raws([raw, raw2])
raw.preload_data()
```

**Comment by Eric89GXL** [comment]
We also should check this for `EDF`, it probably suffers from the same issue.

**Comment by agramfort** [comment]
we need a generic test for Raw objects...

**Comment by teonlamont** [comment]
just confirmed that it does work for RawFIF. 

does not work for RawEDF
```
import os.path as op
import mne
from mne.io.edf.tests.test_edf import bdf_path


raw = mne.io.read_raw_edf(bdf_path, preload=False, verbose=False)
raw2 = mne.io.read_raw_edf(bdf_path, preload=False, verbose=False)

mne.concatenate_raws([raw, raw2])
raw.preload_data()
```

**Comment by agramfort** [comment]
that's a release blocker to me... :(

can you have a look?

**Comment by Eric89GXL** [comment]
I might have time this morning, unless @teonlamont you're on it already?

**Comment by teonlamont** [comment]
@Eric89GXL feel free to take the lead. I was only able to identify where it was working in fif.raw
https://github.com/mne-tools/mne-python/blob/master/mne/io/fiff/raw.py#L389. I can't get to it at the moment.

**Comment by Eric89GXL** [comment]
cool, I'm on it
