### ISSUE TITLE
DOC: MNE tutorial outdated

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#2130]
We should make the tutorial such that it reflects recent APIs.

**Comment by dengemann** [comment]
see http://martinos.org/mne/dev/python_tutorial.html

@mainakjas @teonlamont @Eric89GXL

**Comment by Eric89GXL** [comment]
So hold off on release until someone has time to do this? I *might* have time today.

**Comment by dengemann** [comment]
I'm tired I can do it now if someone can review.

2015-05-21 18:06 GMT+02:00 Eric Larson <notifications@github.com>:

**Comment by Eric89GXL** [comment]
sure, I can review
