### ISSUE TITLE
BUG: Doc buliding has white space / ENH: Use sphinx-build

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2137]
Is it intended to have different fonts between the stable and the development websites?

**Comment by Eric89GXL** [comment]
No, they should be the same. @agramfort did something go wrong with your builds?

**Comment by Eric89GXL** [comment]
Oh, wait -- yes for just right now because the stable website hasn't been updated. @agramfort can you update it?

**Comment by Eric89GXL** [comment]
http://martinos.org/mne/stable/ does not reflect http://mne-tools.github.io/stable/

**Comment by mainakjas** [comment]
Also, is this gap / whitespace intentional?

![gap](https://cloud.githubusercontent.com/assets/3817535/7774443/cc77c95a-00ab-11e5-970c-ca5eedf93752.png)

**Comment by Eric89GXL** [comment]
No -- it might be some bug with `sphinx`

**Comment by agramfort** [comment]
the white gap will be fixed later. We'll switch to sphinx-gallery soon.

**Comment by Eric89GXL** [comment]
I'll change the title to be about that

**Comment by Eric89GXL** [comment]
I'm also going to make a new tag "Sprint 2015" and move this and some other doc issues there

**Comment by agramfort** [comment]
fixed by #2279
