### ISSUE TITLE
Whats New feature

### ISSUE THREAD

**Issue by dgwakeman** [mne-tools/mne-python#2138]
Idea for What's new page. Add link to the function page for each new feature. e.g.

Add SourceSpaces.save_as_volume method by Alan Leggitt 
 would link here
http://martinos.org/mne/stable/generated/mne.SourceSpaces.html

Note, curiously, this is a bad example as the SourceSpaces does not describe a function titled save_as_volume

**Comment by Eric89GXL** [comment]
+1, I hope `sphinx` makes it easy. @dgwakeman have you used this feature before or know how hard it is to implement?

**Comment by agramfort** [comment]
See how sklearn does it
