### ISSUE TITLE
mne.pick_info clean bads

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#2140]
mne.pick_info should clean info['bads'] ie remove bad channels if not picked

cc @jmontoyam

**Comment by jmontoyam** [comment]
@agramfort 

What do you think about this?
https://github.com/jmontoyam/mne-python/blob/fix-issue-2140/mne/io/pick.py#L299

**Comment by Eric89GXL** [comment]
@jmontoyam can you open as a PR? It's much easier to see what is original code and what has been changed. Plus then we get feedback from the automated testing services (Travis CI, AppVeyor)

**Comment by Eric89GXL** [comment]
This has been fixed in the meantime by some PR, see:

https://github.com/mne-tools/mne-python/blob/master/mne/io/pick.py#L318
