### ISSUE TITLE
use sphinx-gallery for example page generation

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#2141]
see https://github.com/jcrudy/py-earth/pull/77/files for a project that recently switched too.

I added support for mayavi. We to add support for slow example.

any volunteer?

**Comment by Eric89GXL** [comment]
I can do it at the sprint if not before. I don't think there's any rush.

**Comment by agramfort** [comment]
sure. I want to make sure we don't forget

**Comment by Eric89GXL** [comment]
marked as 0.10, that's an easy way to make sure it gets done in the next 4 months :)

**Comment by agramfort** [comment]
closes for #2279
