### ISSUE TITLE
Discrepancy between docstring and code for GeneralizationAcrossTime

### ISSUE THREAD

**Issue by choldgraf** [mne-tools/mne-python#2161]
Hey all - I was looking into the default behavior of the GAT class, and there seems to be a difference between the docstring and the code for when the user does not provide their own fitting class:

From the docstring:

    clf : object | None
        An estimator compliant with the scikit-learn API (fit & predict).
        If None the classifier will be a standard pipeline including
        StandardScaler and a linear SVM with default parameters.

The code:

        if clf is None:
            scaler = StandardScaler()
            estimator = LogisticRegression()
            clf = Pipeline([('scaler', scaler), ('estimator', estimator)])

Shouldn't `estimator` be an instance of `LinearSVC`?

**Comment by choldgraf** [comment]
(I am happy to fix with a quick PR but let me know if the docstring should read LogisticRegression, or if the code should be changed to LinearSVC)

**Comment by agramfort** [comment]
Indeed PR welcome

**Comment by choldgraf** [comment]
So which would you like? Should the docstring match the code, or the code match the docstring? I don't know what the original plan was.

**Comment by agramfort** [comment]
Update docstring

**Comment by choldgraf** [comment]
Check out #2164
