### ISSUE TITLE
API for mixed source space inverses

### ISSUE THREAD

**Issue by haribharadwaj** [mne-tools/mne-python#2163]
So with Alan's work, we now have support for mixed source spaces. The forward modeling once you have a mixed source space seems straightforward (already in place). However, with the inverse, there are some use cases that need to be sorted out: Ideally, orientation constraints should be supported for the cortical surface source space and loose solutions for the deep structure(s). What should the API be?

Thoughts?

**Comment by agramfort** [comment]
Indeed 

Dict for loose param

**Comment by Eric89GXL** [comment]
we could have it be a list the same length of the source spaces, that way if you wanted free for one volume and loose or fixed for another you could... but maybe that's YAGNI

**Comment by Eric89GXL** [comment]
in which case I guess the entries would be `surf`, `volume`, and `discrete` for the three types of source spaces? I guess we could always also add list support later.

**Comment by agramfort** [comment]
Yes

**Comment by Eric89GXL** [comment]
@haribharadwaj you up for implementing?

**Comment by haribharadwaj** [comment]
Yes.. I'll start playing with this :).. I have been separately trying to figure out the differences between gradiometers and magnetometers in terms of subcortical sensitivity.. I'm sure I'll ping you guys again with questions soon.

**Comment by agramfort** [comment]
sounds great !
