### ISSUE TITLE
FIX: io.bti coverage

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#2170]
@teonlamont any ideas on how to improve this?

https://coveralls.io/builds/2689771/source?filename=mne%2Fio%2Fbti%2Fbti.py

For example, `_read_ch_config` is about 50 lines (including comments) and isn't tested at all.

Do you know of any small files we could add to the testing dataset that would improve our coverage? It looks like a MAGNES2500 file might help?

There is also a section with `if False:  # XXX reminds us to support this as we go` can you elaborate on that, and preferably comment out those lines instead of using `if False`?

**Comment by dengemann** [comment]
I can look into this next week, I know this code well ;)
We have a config file there that  can be used.

2015-05-31 7:16 GMT+02:00 Eric Larson <notifications@github.com>:

**Comment by Eric89GXL** [comment]
@dengemann if you can provide the files, I can probably make the tests for this. Can it be tested against the C tools?

**Comment by dengemann** [comment]
@Eric89GXL the C tools are incomplete, this converter is special. We test it against the small test files. Btw. please don't touch I'm currently working on this code.

**Comment by Eric89GXL** [comment]
Cool, just wanted to make sure someone was on this for 0.10

**Comment by Eric89GXL** [comment]
@dengemann any ideas on this one? It's been pushed back quite a while

**Comment by Eric89GXL** [comment]
@dengemann do you have a small file we can add to the `testing` dataset to make our coverage here better?

**Comment by dengemann** [comment]
We should have a small bti files in our testing folder.

**Comment by Eric89GXL** [comment]
I don't think we have the proper config file to hit the lines of the
private function mentioned above. You previously mentioned having such
files...?

**Comment by dengemann** [comment]
We have a config there too. The problem might be that we don't have all
files needed to write all tests. I cannot fix this currently. We'd need
some active BTI sites with someone producing a bunch of files.
