### ISSUE TITLE
Q: `epochs_` in evoked name

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#2175]
I used to create epochs from a bunch of event types, then do multiple manipulations on them ending with:
```
evoked = epochs['condition_1'].average()
```
This used to give me an evoked instance where `evoked.name == 'condition_1'`, but now I get `evoked.name == 'epochs_condition_1'`. This seems like a backward-incompatible change, but somehow it has been around for over a year (`git blame` around line 1280 in `epochs.py` traces it back to @agramfort in January 2014). Is this intended behavior, or a bug? Should I just manually get rid of the `epochs_` prefix for my use case?

**Comment by agramfort** [comment]
looks like a bug to me. This epochs_ should not be there :(

**Comment by Eric89GXL** [comment]
Do you remember the logic you were going for? It basically sets the name of the selected object based on whether or not the orginal object had a name != 'Unknown' (but not incorporating the original name at all). I'll go ahead and fix it. Should we backport to 0.9?

**Comment by agramfort** [comment]
yes please backport.

**Comment by Eric89GXL** [comment]
@agramfort done

**Comment by agramfort** [comment]
Thx
