### ISSUE TITLE
ENH: Regression

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-python#2177]
A few enhancements to the regression module:

- [ ] add `picks` param and auto pick MEG and EEG when `picks=None`

**Comment by teonbrooks** [comment]
can be solved by picking before calling the stats function

**Comment by jona-sassenhagen** [comment]
Everything has a picks kwarg, it's a bit surprising that this one shouldn't right?

**Comment by teonbrooks** [comment]
I looked through and saw that none of the stats funcs do.

**Comment by jona-sassenhagen** [comment]
Mne.stats.regression is more like mne.stats.linear_regression_raw imo, and should have a similar syntax ... (Not volunteering :D)
