### ISSUE TITLE
FIX: saving RawEDF

### ISSUE THREAD

**Issue by leggitta** [mne-tools/mne-python#2180]
Trying to use the save method in a RawEDF object creates the following error ...
![screenshot from 2015-06-01 16 34 00](https://cloud.githubusercontent.com/assets/1099867/7941636/7f7d2b9e-090d-11e5-82b0-489967625512.png)

**Comment by teonlamont** [comment]
if you debug here, what's the value of stim_channel?

**Comment by leggitta** [comment]
For me its 72

**Comment by Eric89GXL** [comment]
Can you upload a sample file somewhere for us to try it, and give a minimal script?

**Comment by leggitta** [comment]
Sure. The files I'm analysing are about 1 GB each, but I'll find a smaller one to work with.

**Comment by leggitta** [comment]
I've uploaded a sample .bdf with a short code that reproduces the error to the following repo

https://github.com/leggitta/SampleBDF

**Comment by teonlamont** [comment]
@leggitta it seems to work with you preload the data. with the stim_channel, by default, it automatically detects the channel, which is the Status so you don't need to specify it.

@Eric89GXL do you have any clue why save breaks with `preload=False`

**Comment by Eric89GXL** [comment]
No, I don't know why that would break it. I guess our tests aren't comprehensive enough.

**Comment by agramfort** [comment]
:( :(

**Comment by leggitta** [comment]
@teonlamont Thanks! I hadn't tried using ```preload=True```. Initially,

**Comment by leggitta** [comment]
sorry, accidentally hit close and comment. 

Initially, I was worried about memory since I'm working with large files (I was trying to read them as .bdfs, crop them, and then save the smaller chunks as .fif files), but it turns out I have enough memory on my machine to read each file using ```preload=True```.

**Comment by agramfort** [comment]
so there is only a pb with preload=False?

**Comment by leggitta** [comment]
yes. I also tried a ```preload=tmp.txt``` and it worked

**Comment by agramfort** [comment]
did someone reproduce?

**Comment by Eric89GXL** [comment]
I can try it

**Comment by Eric89GXL** [comment]
Reproduced and fixed (I think). @leggitta can you see if #2184 fixes it?

**Comment by leggitta** [comment]
Yes, that fixed it for me.

**Comment by Eric89GXL** [comment]
Thanks for the quick check @leggitta
