### ISSUE TITLE
legend as a subplot

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2185]
I was noticing in the new tutorial (thanks @dengemann) that we have a rather large legend. I was wondering if we should make an option for the legend to be a subplot of the figure, or a separate figure. That would be ideal when using figures in papers or posters to be able to retrieve separate handle

**Comment by agramfort** [comment]
can you provide a pointer to what your talking about?

**Comment by teonlamont** [comment]
http://martinos.org/mne/stable/auto_examples/io/plot_epochs_to_data_frame.html

![plot_epochs_to_data_frame_001](https://cloud.githubusercontent.com/assets/1578674/7987058/74fe57a4-0adb-11e5-8398-396cfdc19552.png)

**Comment by Eric89GXL** [comment]
We should get rid of the legend. With that many lines it is not
particularly useful.

**Comment by dengemann** [comment]
This is not a good example, it does not use any mne viz API.

2015-06-04 17:02 GMT+02:00 Teon L Brooks <notifications@github.com>:

**Comment by teonlamont** [comment]
closing because issue was a non-MNE related problem. all and all, the legends of our plots are placed appropriately.
