### ISSUE TITLE
FIX/ENH: picking channels should update the info['bads']

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#2186]
But it does not.
This can lead to bugs.
The culprit is `pick_info`, it does not look at the bads.
Only the picked bads should remain.

cc @mainakjas @teonlamont @Eric89GXL

**Comment by agramfort** [comment]
see https://github.com/mne-tools/mne-python/pull/2148 :)

@jmontoyam needs to finish. Or take over of you're in a hurry.

**Comment by dengemann** [comment]
Ahh this was it. Closing then.
