### ISSUE TITLE
plot_topo image in ipython is small and clicking on a plot doesnt open a bigger image.

### ISSUE THREAD

**Issue by ImmanuelSamuel** [mne-tools/mne-python#2187]
How to rectify?
![image](https://cloud.githubusercontent.com/assets/7865018/8010732/a9ff4620-0b80-11e5-8408-1335a4abe344.png)

**Comment by ImmanuelSamuel** [comment]
Right now using this to make it large. Is there a better way?
fig = plt.gcf()
fig.set_size_inches(50,50)

Its still not nice
![image](https://cloud.githubusercontent.com/assets/7865018/8016187/30e2782e-0bae-11e5-8f2a-c01df1b8df7e.png)

**Comment by jona-sassenhagen** [comment]
If you can wait a bit - I'm working on improvements to plot_topo that include better determination of scale.

For now, you want to play around with the layout_scale parameter.

**Comment by ImmanuelSamuel** [comment]
That is awesome! Looking forward to it.

**Comment by Eric89GXL** [comment]
I assume @jona-sassenhagen has fixed this now, but @ImmanuelSamuel feel free to reopen if not
