### ISSUE TITLE
ENH: tutorials / special doc needed

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#2191]
We should have a few extended docs/ tutorials, maybe in the FAQ section on at least the following topics:

- epochs selection and event handling (see #1963)
- artefact removal
- group statistics (make explicit 2 (spatial /  no spatial prior) X 2 (F/T-test) API, clarify TFCE (it's not another test, but an enhancement method)), clarify that despite t-test inputs, spatio-temporal permutation clustering is not parametric and alos it does not give a multiple comparison corrected t-map, which means it's not just a thresholding to a parametric stat. Also add recent insights on decoding stats. Discuss repeated measure designs and options (hierarchial subtraction with t-test, rANOVA, etc.)
- ...

cc @wmvanvliet @kingjr @mainakjas @jona-sassenhagen @teonlamont

**Comment by Eric89GXL** [comment]
Rolling into #1495
