### ISSUE TITLE
Question: Putting a plot in an axes

### ISSUE THREAD

**Issue by ImmanuelSamuel** [mne-tools/mne-python#2195]
How do I put the plot coming from the following

power.plot([0], baseline=(-0.1, 0), mode='mean', title='MEG 1142 - Power')

on to a subplot axes 
fig, axes = plt.subplots(nrows=2, ncols=1)

**Comment by agramfort** [comment]
if there is no axis param in the plot method it should be added.

you can hack and copy the code for your particular use case.

**Comment by jasmainak** [comment]
looks like this was addressed. Closing issue
