### ISSUE TITLE
Coverage went down by 10%, build label says "failing"

### ISSUE THREAD

**Issue by mmagnuski** [mne-tools/mne-python#2201]
I am sure you are aware of this - I report it just in case. Feel free to close.
Last time I checked (about 2 days ago) you were "green" 91% and now code coverage went down to 81% and Travis is sad. One of recent merges introduced this but I did not check which one.

**Comment by agramfort** [comment]
yes it's a pb we need to fix. Some test take too much memory and randomly fails on travis
