### ISSUE TITLE
ENH: full size viewing mode with MacOSX backend

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#2207]
it would be nice for the browse viz functions to have an options for maximizing the window.
For reviewing in block = True mode this is very handy as it saves you one (annoying) step.

cc @jaeilepp @mainakjas 

EDIT by Eric89GXL: This has now been implemented, but doesn't seem to work for OSX.

**Comment by Eric89GXL** [comment]
From [here] (http://stackoverflow.com/questions/12439588/how-to-maximize-a-plt-show-window-using-python) it seems like the best solution is to add something like this to our keypress functions:
```
mng = plt.get_current_fig_manager()
mng.full_screen_toggle()
```
@jaeilepp can you give it a try in your next round of changes?

**Comment by Eric89GXL** [comment]
My vote is for this to be tied to F11

**Comment by dengemann** [comment]
Sounds good, also an option at call time would be great to let it start like that.

**Comment by agramfort** [comment]
I'd rather remember the size of the window in the config rather than
default to full screen.

**Comment by Eric89GXL** [comment]
@agramfort I don't think we want to default to full screen, either, it should default to `False` if we add a kwarg.

**Comment by Eric89GXL** [comment]
Leaving this one open, but changing the title to reflect it's now an issue with OSX

**Comment by Eric89GXL** [comment]
Closing as MPL bug (if it's still happening for OSX backend)
