### ISSUE TITLE
bugs with report.add_htmls_to_section()

### ISSUE THREAD

**Issue by mainakjas** [mne-tools/mne-python#2212]
- `caption` goes only to the table of contents but does not show up above the actual html
- It does not tie itself to the `section` argument and hence breaks the toggle button.

I am willing to live with the first problem but the second one is more serious to me. cc @teonlamont

**Comment by teonlamont** [comment]
Consolidating from #2213:
These are html visualizations/interactions with MNE-Report that could be improved upon:

MNE-Report toggle button #1996
MNE-Report html issue #2212
