### ISSUE TITLE
difference between fwd['sol']['row_names'] and fwd['info']['ch_names']

### ISSUE THREAD

**Issue by cjayb** [mne-tools/mne-python#2223]
Hiya, full disclosure first: the following is **not** reproducible on the sample dataset, which is why I've placed a minimal (250 MB) dataset on:

https://dl.dropboxusercontent.com/u/14937634/fwd_sol_vs_info_ch_ordering.tar.gz

The script `demo_fwd_sol_vs_info_ch_ordering.py` illustrates the situation on an MEG+EEG dataset (Triux 306 + 75ch EEG). I've included 1 sec of raw data (both "true" raw with IAS on and the tSSS'd version with IAS-effects removed), a trans-file, a standard pre-computed 3L-BEM and an ico-6 source space.

I've tracked the bizarre exception thrown by `sensitivity_map` to a call to `proj.py#302: fwd = pick_types_forward(fwd, meg=False, eeg=True`, which gets the channel names screwed up. Specifically, I found that `fwd['sol']['row_names']` and `fwd['info']['ch_names']` have a different ordering!? The code in `pick_types_forward` assumes the ordering to be the same, however, using the same `sel`-parameter to slice both `'sol'` and `'info'`.

The data is acquired as usual---I cannot think of a step which would have been performed differently. Is there any reason why the `'sol'` and `'info'` dicts should be allowed to have a different ordering? I'll gladly debug further, but could use some pointers on how to proceed. /Chris

**Comment by Eric89GXL** [comment]
I think the forward solution code is structured so that the forward solution gets ordered as MEG then EEG channels. Is that how your data are organized originally? (I don't have time right now to look myself, but I can check later today or Monday.)

In any case, it does sound like there is a bug because if e.g. EEG data come before MEG data, the orders will be mismatched.

**Comment by cjayb** [comment]
The `raw.info['ch_names']` is in the usual order
`['EOG001',
 'ECG002',
 'EOG003',
 'EEG001',
 'EEG002',
 'EEG003',
 'EEG004', ...]`, _i.e._, "BIO", followed by EEG, followed by MEG-chans. This is the order in `fwd['info']`. But in `fwd['sol']` the order seems to have been switched to MEG followed by EEG (BIO dropped, of course).

I'm sure you're right about the non-bug status, but if you do get the chance to take a look, I'd greatly appreciate it.

**Comment by Eric89GXL** [comment]
I mean that there definitely is a bug... `fwd['info']` and `fwd['sol']` orders do not have to match -- we should use different selections for each, as you suggest. Do you want to try making a fix?

**Comment by dgwakeman** [comment]
A good place to try things out would be to see what happens when you use the C code to deal with these files in each place (are the outputs ordered the same?)

**Comment by Eric89GXL** [comment]
I suspect they will be since I tried to follow the C code closely with the forward code, but the C code probably does a better job with the picking after the fact :)

**Comment by cjayb** [comment]
Sorry, I should learn to read _every_ word people write to me ;)

If it's safe to use separate selections, then at least for `pick_forward_types`, this  seems to work: 04bf94c104c7210352df5d0a04b39588164620ef 

I can't judge if it's "safe", though, any thoughts?

**Comment by Eric89GXL** [comment]
This is about what I would expect. Does this work for your data? If so, please open a pull request.

We should also add some test, though. I think we can do it by loading a sample file, reordering the data and entries in `info`, and using that to create the forward. Are you up for writing that? If you don't have time or don't know how, I can do it.

**Comment by cjayb** [comment]
It works to the extent that 1) the `sensititivity_map` is calculated and 2) the map "makes sense". I'd like to give this a go, I'll `@` you if/when need be (most likely in the test-phase). Expect a PR during next week. Have a good one!

**Comment by Eric89GXL** [comment]
Great, thanks @cjayb.

In your PR on GitHub, please put `Closes #2223` so this issue gets auto-closed when me merge your PR.
