### ISSUE TITLE
BUG/API issue with multi_comp.bonferroni_correction

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#2227]
Do people agree that this is a bug, at least a very unexpected output:
https://github.com/mne-tools/mne-python/blob/master/mne/stats/multi_comp.py#L101

`pval_corrected` should instead be used for creating the output mask.

@agramfort @Eric89GXL @mainakjas

**Comment by mainakjas** [comment]
indeed, looks like a bug to me

**Comment by dengemann** [comment]
probably one of @agramfort 's early experiments on how to impvrove the sensitivity of MEG group analyses ... ;)

**Comment by agramfort** [comment]
oh my goodness... it's a horrible bug that has been there for ages ... :-/

PR more than welcome...

**Comment by dengemann** [comment]
Ok, I'm on it.
