### ISSUE TITLE
plot_topo should be a method of evoked?

### ISSUE THREAD

**Issue by mainakjas** [mne-tools/mne-python#2240]
Silly question, but I was expecting to do:

```py
evoked.plot_topo()
```

instead of 

```py
from mne.viz import plot_topo
plot_topo(evoked)
```
anything against this? cc @jaeilepp interactive visualization is your department ;-)

**Comment by teonlamont** [comment]
that would be useful

**Comment by agramfort** [comment]
why not

**Comment by dengemann** [comment]
The plot topo takes lists of evokeds too. I think that's why we kept it like that.

**Comment by mainakjas** [comment]
I see, that makes sense but I guess it shouldn't be too hard to add a modified version of this function as a method to `evoked`. I use it all the time to look at my data.

**Comment by agramfort** [comment]
it should not be too much lines of code indeed.

**Comment by dengemann** [comment]
@mainak you could also subclass Evoked from list to make it work more
flawlessly ;)

2015-06-26 9:12 GMT+02:00 Alexandre Gramfort <notifications@github.com>:

**Comment by Eric89GXL** [comment]
This one's done by #2241
