### ISSUE TITLE
Help with make_forward_solution

### ISSUE THREAD

**Issue by ImmanuelSamuel** [mne-tools/mne-python#2243]
mne.make_forward_solution(info, trans, src, bem, fname=None, meg=True, eeg=True, mindist=0.0, ignore_ref=False, overwrite=False, n_jobs=1, verbose=None, mri=None)

I am doing this on a EEG dataset. I have the info instance. I am using the 128 Biosemi system. How to get trans, src and bem instances?

Thanks

**Comment by Eric89GXL** [comment]
Have you looked through the MNE manual? The topics of what a trans is (coregistration matrix for head digitization and structural), src is (source space for neural currents), and what a BEM is (conductor model for forward calculation) are covered in there.

**Comment by ImmanuelSamuel** [comment]
I have been looking into all of the above and it seems to be linux heavy in getting all the files necessary to do an analysis. Is it possible to have a standard source space, BEM and trans obtained from a standard T1? I don't have individual T1 so I was initially planning on running getting the files based on a standard T1 as used in MRIcron. Is it possible to have some standard defaults making it easier for users to run source connectivity?

**Comment by dengemann** [comment]
If you don't have a coregistration I doubt source connectivity is a great
idea ...
You can coregister to fsaverage if this is what you want using the coreg
gui in python.
It would be better to have t1 if you want to make claims about source
connectivity, my 2 cents.

2015-07-07 15:59 GMT+02:00 ImmanuelSamuel <notifications@github.com>:

**Comment by ImmanuelSamuel** [comment]
Hmmm ok. I followed LORETA tutorials and they seem to do the same with a standard T1. That is why I asked if there is a default template that I we can use. I mean if people accept that method I am hoping they should accept this also. Although that is just my opinion.

**Comment by Eric89GXL** [comment]
@ImmanuelSamuel you should be able to use `mne coreg` to create a surrogate from an existing subject by scaling the MRI as necessary. I'll close this, but if it doesn't make sense, please reopen
