### ISSUE TITLE
histogram of peak-to-peak thresholds

### ISSUE THREAD

**Issue by mainakjas** [mne-tools/mne-python#2248]
For each epoch, we can get the peak-to-peak value for all channels (separately for eeg, mag and grad) and make a histogram out of it. Based on this histogram, you can judge if the epoch should be dropped or not.

Idea discussed with @agramfort over mne-lunch. cc @jaeilepp it would be cool to integrate this into the epochs viewer. Thoughts?

**Comment by agramfort** [comment]
+1 that would be very useful I think.

**Comment by wmvanvliet** [comment]
this should work well together with the FASTER rejection functions, since epochs are discarded based (among other metrics) on standard deviation of the channels.

**Comment by agramfort** [comment]
fixed
