### ISSUE TITLE
All plots should have axes parameter

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2255]
I think that we should make sure all of our plotting functions have the `axes` parameter.

Most of them do but some don't, e.g. plot_projs_topomap. It would be great for added flexibility with creating figures.

cc: @mainakjas @jaeilepp

**Comment by ImmanuelSamuel** [comment]
power.plot() needs axes parameter.

**Comment by teonlamont** [comment]
related pr #2195

**Comment by teonlamont** [comment]
evoked.plot mentioned in https://github.com/mne-tools/mne-python/pull/2241#issuecomment-116621986

**Comment by teonlamont** [comment]
TFR.plot

**Comment by jaeilepp** [comment]
``evoked.plot`` actually has an axes param.
``plot_projs_topomap`` creates multiple axes instances. Their positioning rely on the layout. I don't see the point in positioning them yourself.

**Comment by teonlamont** [comment]
what about in the case of just one proj being plotted. that is the use case that I was thinking of. for instance, I want to make a figure that has the waveform with the proj applied on the left, and then the topography of that projection on the right.

**Comment by jaeilepp** [comment]
Oh yeah. You're right. I must have looked at something else...

**Comment by teonlamont** [comment]
you were right that if you have projs > 1, plot_projs_topomap will make subplots of all of the figures. I was thinking there should be an option when projs = 1, then you can use axes.

**Comment by teonlamont** [comment]
closed for #2281
