### ISSUE TITLE
write_labels_to_annot fails if labels have no name defined

### ISSUE THREAD

**Issue by aestrivex** [mne-tools/mne-python#2256]
File "/space/truffles/2/users/rlaplant/anaconda/lib/python2.7/site-packages/mne-0.9.dev0-py2.7.egg/mne/label.py", line 1865, in write_labels_to_annot
    msg = "%s: %s (%s)" % (color, ', '.join(names), hemi)
TypeError: sequence item 0: expected string, NoneType found

This bit of code is blocked off by `if len(names) > 0`.
But I encountered the case names is `[None, None, None ...]` so it can't join them.

I can fix this but I don't want to do it right this moment.

**Comment by agramfort** [comment]
fix it when you can
