### ISSUE TITLE
find_layout doesn't work for KIT system if a channel is dropped

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2258]
Is there a way to preserve the original number of channels in a system after doing inst.pick_types. The two KIT systems differ in layout and they are distinguished based on the number of channels.

**Comment by Eric89GXL** [comment]
Is there a more robust way too distinguish them, e.g. by coil type? Using
number of channels seems fragile. How does it work for Neuromag systems?

**Comment by teonlamont** [comment]
unfortunately, they have the same coil type. I agree that using the number of channels is a weak assertion. Neuromag looks for particular channel types

**Comment by agramfort** [comment]
can you hack something?

**Comment by teonlamont** [comment]
I think the solution would be to do any layout getting before doing picking, e.g. `epochs.pick_types(meg=True, exclude='bads')`. since there is no distinguishing attribute between the two, that would be no elegant solution
