### ISSUE TITLE
__repr__ for Epochs when read from disk

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2259]
the __repr__ of an Epochs objects read from disk is `_BaseRaw`. should this be `Epochs`? I guess we can't distinguish between Epochs and EpochsArray saved to disk and that is why the generic basename is being used.

cc: @Eric89GXL

**Comment by Eric89GXL** [comment]
What we should really do is rename Epochs to something else (like
EpochsFromRaw but a less crappy a name) and change _BaseEpochs to Epochs,
but that will break people's code if they have subclassed. So I'm not sure
what a good solution is.

**Comment by teonlamont** [comment]
sorry, that was supposed to saw `_BaseEpochs`, not `_BaseRaw`. but actually, nvm. I just loaded epochs from disk and it says `Epochs` now. I think I am ok with how things are now without any changes

**Comment by teonlamont** [comment]
actually, i was wrong. i think it is still there.

**Comment by Eric89GXL** [comment]
Yeah, it should still be there. I don't have a good solution in mind. We could just make `BaseEpochs` public.

**Comment by teonlamont** [comment]
what do you think about doing this in the read_epochs:

```python
epochs = _BaseEpochs(info, data, events, event_id, tmin, tmax,
                             baseline, name=name, on_missing='ignore',
                             verbose=verbose)
epochs.__class__.__name__ = 'Epochs'
```

**Comment by Eric89GXL** [comment]
BOOO HISSS monkey patch :) I think I'd actually prefer making `BaseEpochs` public instead.

**Comment by teonlamont** [comment]
hahaha, but then what would make people use `EpochsArray` instead of `BaseEpochs`, they look similar? or simply, what's the use of making it public other than the repr?

**Comment by Eric89GXL** [comment]
There isn't really a purpose. We can tell people they shouldn't instatiate it directly, and link to the other classes. To actually answer your question, EpochsArray has a few checks in it, otherwise it is a very thin wrapper around BaseEpochs.

**Comment by agramfort** [comment]
I am lost. Can you paste a gist to reproduce the issue?

**Comment by Eric89GXL** [comment]
When you read any `-epo.fif` file and look at the `__repr__`, the class name is `<_BaseEpochs : ...>`

**Comment by agramfort** [comment]
see https://github.com/mne-tools/mne-python/pull/2272
