### ISSUE TITLE
STC iterator over time

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-python#2260]
To save on memory and processing, it would be useful to have the stc generator compute over time. Currently it iterates over epochs. The use case is computing regressions in source space, or other parameter maps of source estimates over time.

**Comment by Eric89GXL** [comment]
Would an iter_time method work for your use case?

**Comment by dengemann** [comment]
@teonlamont FYI you can compute betas from a linear regression and map them to source space using MNE, it's valid cf. @olafhauk work.
I guees you want to do it for your ridge though and I bet it won't be valid for the ridge coefs.

**Comment by teonlamont** [comment]
@Eric89GXL yeah, something like that is what I was thinking about.

there was a long discussion over the listserv a while back about using beta maps generated in sensor space then using them in source space https://mail.nmr.mgh.harvard.edu/pipermail//mne_analysis/2014-February/001841.html. @dengemann I agree that it should be ok for MNE, but what about for dSPM

**Comment by Eric89GXL** [comment]
DSPM is linear too so I think it should be okay

**Comment by teonlamont** [comment]
but what about using free orientation, I guess the transformation would be ok, but then the x, y, z values are combined

**Comment by Eric89GXL** [comment]
Oh you mean loose or free orientation, yeah that combination of terms is
nonlinear

**Comment by Eric89GXL** [comment]
@teonbrooks do we still need this?

**Comment by teonbrooks** [comment]
I think we can close it for now. if anyone needs in the feature, we can reopen it. still think it could be useful
