### ISSUE TITLE
Q: Baseline for power.plot_topo

### ISSUE THREAD

**Issue by ImmanuelSamuel** [mne-tools/mne-python#2267]
my data epoch is from -0.5s to 1.5s

I run the following
power = mne.time_frequency.AverageTFR

Then, when I do power.plot_topo(baseline=???) ...

Should the baseline be (-0.5,0) or (-0.5,-0.25) because the time frequency analysis should give a power at 0 based on a window from -0.25 to +0.25 right?

**Comment by agramfort** [comment]
the baseline with TFR needs to be shorter eg -0.3 and -0.1 as you have
edges and a freq/time resolution trade-off.

**Comment by jona-sassenhagen** [comment]
@ImmanuelSamuel can this be closed?
