### ISSUE TITLE
ENH: more datasets for mne-python

### ISSUE THREAD

**Issue by mainakjas** [mne-tools/mne-python#2280]
I am opening a new issue to avoid cluttering gitter. Here's what I could find till now. Edit this comment to add more datasets
- [Fieldtrip datasets](http://www.fieldtriptoolbox.org/faq/what_types_of_datasets_and_their_respective_analyses_are_used_on_fieldtrip). They have a couple of examples, we could try to reproduce. For example: [beamforming](http://www.fieldtriptoolbox.org/tutorial/beamformingextended), [artifact rejection](http://www.fieldtriptoolbox.org/tutorial/automatic_artifact_rejection). So, we could get the corresponding datasets
- [UCSD EEG datasets](http://headit-beta.ucsd.edu/studies)
- http://crcns.org/data-sets/vc/pvc-5 - it would be great to identify / negociate the licence if we see that a dataset could be used in an example. (#3585)
- MMN dataset (http://www.fil.ion.ucl.ac.uk/spm/data/eeg_mmn/ ) used for tutorial/publications applying DCM for ERP analysis using SPM. 

- ~~Human Connectome Project Datasets (http://www.humanconnectome.org/data/ )~~ see mne-hcp
- Kymata Datasets (https://kymata-atlas.org/datasets). Current and archived EMEG measurement data, used to test hypotheses in the Kymata atlas. The participants are healthy human adults listening to the radio and/or watching films, and the data is comprised of (averaged) EEG and MEG sensor data and source current reconstructions.
- http://www.brainsignals.de/ A website that lists a number of MEG datasets available for download.

**Comment by agramfort** [comment]
artifact rejection one seems doable. Dics uses mat files.

how about brainstorm?

**Comment by mainakjas** [comment]
For brainstorm, you need to register and then you can download. But they have dropbox links as well for all the files. Interestingly, they have median nerve data (tutorial [here](http://neuroimage.usc.edu/brainstorm/DatasetMedianNerveYokogawa) and [here](http://neuroimage.usc.edu/brainstorm/Tutorials/TutMindNeuromag)) -- might be cool to demonstrate our stim artifact interpolation, resting state data (tutorial [here](http://neuroimage.usc.edu/brainstorm/Tutorials/Resting)). Also auditory data but maybe that's not so interesting.

Brainstorm has GPL license and so has Fieldtrip. How do we deal with that? Maybe you need to talk to your friends there ;-)

**Comment by agramfort** [comment]
+1 for mind somato data

for resting we need more stuff in mne to make it useful.

regarding license there should be no pb.

can we download them from a script?

**Comment by dengemann** [comment]
> Dics uses mat files.

**Comment by alexandrebarachant** [comment]
There is also the [BNCI data repository](http://bnci-horizon-2020.eu/database/data-sets)
It's mainly EEG / BCI but there is a couple of interesting one (including a fNIRS dataset).
File are all in matlab format, but they are more or less standardized.

**Comment by agramfort** [comment]
cool !

what type of cool example would you do with it?

**Comment by alexandrebarachant** [comment]
It is probably a good source to feed the decoding section.
the fNIRS data would be interesting to look at. There is also one with joint recording of EEG and EMG data. But i don't have any cool stuff to do with it (yet).

Ultimately, having a generic wrapper for all these dataset will allow easy multi-dataset evaluation of algorithms.

**Comment by agramfort** [comment]
>
> It is probably a good source to feed the decoding section.
> the fNIRS data would be interesting to look at. There is also one with
> joint recording of EEG and EMG data. But i don't have any cool stuff to do
> with it (yet).
>
> Ultimately, having a generic wrapper for all these dataset will allow easy
> multi-dataset evaluation of algorithms.
>
I like that !

**Comment by mainakjas** [comment]
yeah, one related issue that I don't like having to do is:

```py
data_path = sample.data_path()
raw_fname = data_path + '/MEG/sample/sample_audvis_filt-0-40_raw.fif'
```
Instead if we could save it as a dict and do:
```py
raw_fname = datapath['raw_fname']
```
that would be nice. Just an idea ...

**Comment by dengemann** [comment]
isn't this done now?

**Comment by Eric89GXL** [comment]
@dengemann we have brainstorm, but not FieldTrip or UCSD, I think

@mainakjas is it a realistic target to get these done in the next two weeks?

**Comment by mainakjas** [comment]
hmmm ... two weeks might not be enough. I can take a look in the Dec holidays if there is no rush. We can shift the milestone.

**Comment by Eric89GXL** [comment]
done

**Comment by Akshay0724** [comment]
I would like to work in this issue for GSOC, please tell me how do I start working and what exactly needs to be done here.

**Comment by agramfort** [comment]
@Akshay0724 see how data downloaders are setup in mne.datasets and then you need to write a tutorial. Basically take any tutorial that you want in:

http://www.fieldtriptoolbox.org/faq/what_types_of_datasets_and_their_respective_analyses_are_used_on_fieldtrip

make the downloader and make an example / tutorial to see how to analyze this data.

**Comment by Akshay0724** [comment]
Hello @agramfort <https://github.com/agramfort>,
For loading FieldTrip data in our data structures, we can either first
convert data into format compatible with mne.io.read_raw_fif and then make
the converted data available for download
or
we make downloader to get data from FieldTrip and make it responsible for
the conversion.

Please correct me if I'm wrong.
Thanks

**Comment by agramfort** [comment]
find a dataset that is in native format eg. .ds, .edf or .fif

**Comment by choldgraf** [comment]
another idea is to add in an API to connect with the CRCNS database. It's super simple, see https://github.com/neuromusic/crcnsget

**Comment by jasmainak** [comment]
What sort of example do you have in mind @choldgraf ? For the simple use case of getting more datasets, you can use [datalad](http://datalad.org/)

**Comment by sappelhoff** [comment]
@jasmainak is this dead? Or related to the generalized openneuro fetcher?

**Comment by jasmainak** [comment]
I am not sure. It was related to my mission doctoral and I implemented the Brainstorm fetchers already. There are many other indexes of datasets online, so I'm fine closing this.

**Comment by agramfort** [comment]
let's keep this open as a source of new datasets and analysis examples. But yes we should progressively move towards BIDS formatted data.

**Comment by larsoner** [comment]
I'm going to close since I don't think we need to implement anything at the MNE end for this at the moment. Let's open issues about specific datasets that people are motivated to add / think MNE needs nowadays
