### ISSUE TITLE
ENH: allow for spatial connectivity between two hemispheres

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#2286]
In volumetric source spaces you can get bi-lateral ROIs, blobs, and  connected clusters, not that easily with Freesurfer surfaces. However, it's an unphysiological prior to not allow bihemispheric connections in permutation clustering tests. With @banilo and @yuval-harpaz we were wondering about ways to connect medial vertices across hemispheres, maybe based on a minimum distance criterion. As an intermediate step it would be cool to support FS xhemi registrations to support mapping vertices between hemispheres. Input and ideas are welcome.

cc @Eric89GXL @mainakjas @agramfort

**Comment by yuval-harpaz** [comment]
Hi
I used fsaverage_sym from:
https://surfer.nmr.mgh.harvard.edu/fswiki/Xhemi
I read the spheres surfaces with matlab and looked for min distance there,
which made more sense than on pial.
I then looked for each of these pairs of dots (in lPair and rPair vectors
below) for their closes points on individual sphere surfaces.
The result seems reasonable but I did not validate it yet.

This is my code for looking for LR pairs on the template

sphere.lh=mne_read_surface('/usr/local/freesurfer/subjects/fsaverage_sym/surf/lh.sphere.left_right');
sphere.rh=mne_read_surface('/usr/local/freesurfer/subjects/fsaverage_sym/surf/rh.sphere.left_right');
for srci=1:10242

[~,lPair(srci)]=min(sum(abs(sphere.lh-repmat(sphere.rh(srci,:),length(sphere.lh),1)),2));
    prog(srci)
end
rPair=1:10242;

here is how I looked for pairs for individuals

       sub
*Sphere.lh=mne_read_surface(['/usr/local/freesurfer/subjects/',subj,'/surf/lh.sphere']);*
*
subSphere.rh=mne_read_surface(['/usr/local/freesurfer/subjects/',subj,'/surf/rh.sphere']);*
*        clear li ri*
*
%[v,i]=min(sum(abs(sphere.rh-repmat(subSphere.rh(1,:),length(sphere.lh),1)),2));*
*        for srci=1:10242*
*
[~,ri(srci)]=min(sum(abs(subSphere.rh-repmat(sphere.rh(srci,:),length(subSphere.rh),1)),2));*
*
[~,li(srci)]=min(sum(abs(subSphere.lh-repmat(sphere.lh(lPair(srci),:),length(subSphere.lh),1)),2));*
*            prog(srci)*
*        end*
*        disp(' ');*
*        if length(unique(li))<10242*
*            disp([subj,' has ',num2str(10242-length(unique(li))),'
repeting matches for LH'])*
*        end*
*        if length(unique(ri))<10242*
*            disp([subj,' has ',num2str(10242-length(unique(ri))),'
repeting matches for RH'])*
*        end*


On 14 July 2015 at 10:47, Denis A. Engemann <notifications@github.com>
wrote:

> In volumetric source spaces you can get bi-lateral ROIs, blobs, and
> connected clusters, not that easily with Freesurfer surfaces. However, it's
> an unphysiological prior to not allow bihemispheric connections in
> permutation clustering tests. With @banilo <https://github.com/banilo>
> and @yuval-harpaz <https://github.com/yuval-harpaz> we were wondering
> about ways to connect medial vertices across hemispheres, maybe based on a
> minimum distance criterion. As an intermediate step it would be cool to
> support FS xhemi registrations to support mapping vertices between
> hemispheres. Input and ideas are welcome.
>
> cc @Eric89GXL <https://github.com/Eric89GXL> @mainakjas
> <https://github.com/mainakjas> @agramfort <https://github.com/agramfort>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mne-tools/mne-python/issues/2286>.
>



-- 
Yuval




Dr .Harpaz

BIU MEG lab <http://faculty.biu.ac.il/~goldsa/index.html>

**Comment by Eric89GXL** [comment]
A while back I used Euclidean distance for the medial wall labels, it's
pretty easy to combine that with the existing surface distances. Just
compute the distances between medial left vertices and medial right
vertices, and populate the correct entries in the existing distance matrix.

**Comment by Eric89GXL** [comment]
I think this can be done in a few lines with e.g. `cdist`. Okay to close this one as an mne-python issue, or do you think the API should live in mne-python?

**Comment by dengemann** [comment]
> do you think the API should live in mne-python?

it should once we're confident that his does the job.

**Comment by Eric89GXL** [comment]
Can you come up with the desired API call? `get_euclidean_inter_hemi_neighbors(src, limit)` or so? Then your connectivity matrix would just be the surface one union the euclidean one.

**Comment by dengemann** [comment]
Maybe ```mne.connect_hemis(connectivity, src, limit)```

**Comment by yuval-harpaz** [comment]
by the way, I played with corregistering left to right hemispheres some
more a while ago. I found that the simplest way is to corregister one
hemisphere of a subject to the other, and then on the inflated overlaping
surfaces (say the real LH and the flipped RH) to find nearest nodes

On 25 November 2015 at 16:03, Denis A. Engemann <notifications@github.com>
wrote:

> Maybe mne.connect_hemis(connectivity, src, limit)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mne-tools/mne-python/issues/2286#issuecomment-159615566>
> .
>



-- 
Yuval




Dr .Harpaz

BIU MEG lab <http://faculty.biu.ac.il/~goldsa/index.html>
