### ISSUE TITLE
document related functions by populating "See Also"

### ISSUE THREAD

**Issue by mainakjas** [mne-tools/mne-python#2289]
We should list related function in the documentation of all functions a la numpy/scipy. cc @dengemann @agramfort

**Comment by Eric89GXL** [comment]
That's kind of what our main api page does, right? Maybe we can just make
it better.

We should start populating See Also in docstrings, which would also help.

**Comment by mainakjas** [comment]
I think I meant populating the `See Also` :) I'll edit the description of the PR

**Comment by mainakjas** [comment]
I am taking this.

**Comment by dengemann** [comment]
YEAHH great call!
