### ISSUE TITLE
AssertionError / read_raw_brainvision 

### ISSUE THREAD

**Issue by tomekwielek** [mne-tools/mne-python#2294]
cc @teonlamont 

I get an AssertionError while loading binary file from BrainVision - Version 2.0.   

```py
 398         # extract the first section to resemble a cfg
    399         l = f.readline().strip()
--> 400         assert l == 'Brain Vision Data Exchange Header File Version 1.0'
    401         settings = f.read()
    402
AssertionError:

```

Any idea about the reason?

**Comment by teonlamont** [comment]
because when I wrote it, I didn't know if the header would be different across the version. I wasn't sure if I could make it general. If they have the same pattern, then I could lax the requirement.

**Comment by Eric89GXL** [comment]
This has been fixed
