### ISSUE TITLE
Scale MRI is broken

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-python#2308]
Scaling subject is currently not working. At first, I thought it was related to my pr #2239 but it isn't working on master either. This may be a problem with the gui interaction with qt (at least this error message shows up on qt listservs).

```
2015-07-16 15:03:43.080 python[21563:3737877] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
```

Pseudo-way to make it happen:
mne.gui.coregistration()
scale a subject without MRI to template using their headshape info
try to save

cc: @christianbrodbeck

**Comment by christianbrodbeck** [comment]
Is it working with mne 0.8/0.9? Or is it a problem of another library's update?

**Comment by Eric89GXL** [comment]
I'm going to move this to 0.11, let me know if you have time for it in the next couple of days @teonlamont and we can move it back

**Comment by Eric89GXL** [comment]
@teonbrooks any updates on this? It has been open for a while with no updates.

**Comment by Eric89GXL** [comment]
Closing due to non-response, @teonbrooks feel free to reopen if you hit the issue again
