### ISSUE TITLE
ENH: Epochs vectorizer

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#2313]
To elegantly pipe mne.Epochs through sklearn.pipeline.Pipelines

cc @trachelr @kingjr @agramfort ...

**Comment by trachelr** [comment]
Epochs vectorizer is here as ConcatenateChannels.
We just need to rename the class ConcatenateChannels and make deprecation warning.
I can do it in PR #2292

**Comment by jasmainak** [comment]
closing issue as it seems this is already addressed
