### ISSUE TITLE
Possible bug in _setup_connectivity in cluster_level.py

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2314]
@awjamison just pointed out to me that in _setup_connectivity, it's checking for whether a spatiotemporal connectivity has the appropriate number of time points: https://github.com/mne-tools/mne-python/blob/master/mne/stats/cluster_level.py#L521

should this actually be `round(float(connectivity.shape[0]) / n_vertices) == n_times` instead?

**Comment by Eric89GXL** [comment]
Look at where it is used:

https://github.com/mne-tools/mne-python/blob/master/mne/stats/cluster_level.py#L708

`X` has just gotten reshaped as `(X.shape[0], -1)` and then `X.shape[1]` is passed into the function, so the `n_vertices` argument to that function is actually more like `n_tests` (and it's called this in the calling code). So the line looks correct but the `n_vertices` shape looks like a misnomer, it should probably be renamed to `n_tests`.

**Comment by agramfort** [comment]
closing?
