### ISSUE TITLE
ENH ICA plot_sources

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2316]
@jaeilepp is there to recycle `topo` figures in the `ica.plot_sources()`? For instance, if I click the same IC twice, it generates two figures.

**Comment by jaeilepp** [comment]
What do you mean by recycling? You mean that each channel is in separate
figure? That should be easy to do...

**Comment by teonlamont** [comment]
actually, that's the current behavior already. what I am suggesting is that when the first figure for an IC is generated, it creates a reference to that figure, so if you click on it again, instead of creating a new figure, it just brings that one back. it would only create a new copy of the topo if it were previously closed.

**Comment by agramfort** [comment]
please keep it simple.

**Comment by teonlamont** [comment]
closing for now
