### ISSUE TITLE
ENH: Disable gaussian smoothing in mne.viz.plot_topo_image_epochs

### ISSUE THREAD

**Issue by leggitta** [mne-tools/mne-python#2321]
Hello,

I'd like to disable the gaussian smoothing when plotting image epochs, so I can clearly identify which trials have artifacts in them. I thought that the user could set ```sigma=None```, in which case the smoothing step is skipped. Would anyone else be interested in this option?

Alan

**Comment by agramfort** [comment]
what if you set sigma=0. ? does it do the job?

**Comment by leggitta** [comment]
This is with sigma=0, but I was hoping for something more pixellated so I can see where the edges are.

![screenshot from 2015-07-20 14 51 00](https://cloud.githubusercontent.com/assets/1099867/8788385/d79e0f12-2eee-11e5-95cc-617790c26c10.png)

**Comment by Eric89GXL** [comment]
What does it look like with nearest-neighbor interpolation (instead of bilinear) on the `imshow` with different sigmas? It would make sense to me to have NN interp on by default, since the sigmas should take care of the smoothing for you.

**Comment by leggitta** [comment]
Here's the same image with nearest

![screenshot from 2015-07-20 15 12 47](https://cloud.githubusercontent.com/assets/1099867/8788802/d2150e58-2ef1-11e5-8120-4f3656382d83.png)

**Comment by agramfort** [comment]
looks good no?

**Comment by Eric89GXL** [comment]
That is what I would expect from `sigma=0.` and nearest-neighbor interpolation. The smearing on the temporal axis is due to the overlapping of the windows used.

What does it look like for the default sigma value? Is it very different from how it is with bilinear interp on?

**Comment by leggitta** [comment]
Ok, here it is with ```interpolation='nearest'``` with the default sigma value.

![screenshot from 2015-07-20 15 30 41](https://cloud.githubusercontent.com/assets/1099867/8789086/4f986094-2ef4-11e5-8120-a575822855cd.png)

**Comment by leggitta** [comment]
so the smoothing is happening in the temporal domain, not across trials?

**Comment by agramfort** [comment]
It should happen across trials. We have a bug???

**Comment by leggitta** [comment]
It is smoothing across trials, I just tried out a few different sigmas. But if I wanted to look at the trials without blurring, I need to change both sigma and the interpolation argument.

**Comment by Eric89GXL** [comment]
try sigma=2, it should make it smooth vertically

Maybe we should change the default to something like that. I think in any case we should set the interpolation to nearest. It is a bit silly to have two forms of interpolation going on like that.

**Comment by agramfort** [comment]
+1 for smoothing vertically and use nearest.

volunteer?

**Comment by Eric89GXL** [comment]
@leggitta you find that it's broken you buy it? :)

**Comment by leggitta** [comment]
Sounds fair. The vertical smoothing seems to be working fine. The below plot is with sigma=2 and interpolation='nearest'.

Should I make interpolation='nearest' for all functions that use imshow?

![screenshot from 2015-07-21 09 47 39](https://cloud.githubusercontent.com/assets/1099867/8806851/8b2307b0-2f8d-11e5-8f45-84184a56b30c.png)

**Comment by Eric89GXL** [comment]
The smoothing type probably needs to be decided on a case-by-case basis. Are there other ones where you think it would make sense?

**Comment by leggitta** [comment]
Not of the top of my head, but I'll look around for ones that also apply some kind of gaussian smoothing.
