### ISSUE TITLE
bug in mne_browse_epochs

### ISSUE THREAD

**Issue by mainakjas** [mne-tools/mne-python#2324]
@jaeilepp if I click on the lower right corner of the epochs browser (below the scroll bar), I get an error which says:

```py
In [2]: Floating point exception
```
Ipython closes and everything crashes. Maybe I should do more science to discover such corner cases ;)

**Comment by mainakjas** [comment]
I think the scrollbar has to be at the bottommost position for this error to occur. So, scroll to the bottom and then click on the bottom left corner. @yousrabk couldn't reproduce this on her computer but I can reproduce it on the example. If anyone else can reproduce it, maybe that's useful info

**Comment by jaeilepp** [comment]
I can't reproduce.

**Comment by mainakjas** [comment]
I can show you on my computer :)

**Comment by Eric89GXL** [comment]
@jasmainak you still having this issue?

**Comment by jasmainak** [comment]
yes, this is not fixed and @jaeilepp has been able to reproduce it on my computer

**Comment by jaeilepp** [comment]
This is solved. Closing...
