### ISSUE TITLE
implement draw_sensors

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#2330]
implement draw_sensors

https://github.com/mne-tools/mne-matlab/blob/master/matlab/mne_load_coil_def.m#L160

in plot_trans function.

**Comment by Eric89GXL** [comment]
We have to be careful because that was translated from BrainStorm code, which I think is GPL'ed. So we'll have to ask permission to relicense, right @agramfort?

**Comment by agramfort** [comment]
hum... @ftadel what do you say?

**Comment by ftadel** [comment]
I don't think we can even trace back who wrote that function...
I think you can just re-use whatever you need to :)

**Comment by agramfort** [comment]
ok cool.

any volunteer?

**Comment by Famguy** [comment]
@agramfort I would like to volunteer for this (in case nobody's working on it).

**Comment by agramfort** [comment]
go for it.

#2599 or #2598 might be a little easier though

**Comment by jasmainak** [comment]
This one might be easy too: https://github.com/mne-tools/mne-python/issues/2770
