### ISSUE TITLE
Optimize linear_regression_raw: sparse matrices, partial fits

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#2331]
Currently, either many predictors, or long time windows, or high sampling rates w/o decim, or especially any combination of these can lead to very memory-intensive models in rER[F/P]s that overload even powerful computers, and laptops may struggle even with smaller problems.

In response,
- profile mem usage
- predictor matrix X should be made sparse
- fitting can be done iteratively/on non-overlapping subsets

See #2304, especially @njsmith's last comment (Thanks for the insight!).

I will try, unless somebody better at numpy/scipy/linear algebra wants to.

**Comment by mainakjas** [comment]
I think the first step is to profile, to figure out what needs to be optimized.

**Comment by jona-sassenhagen** [comment]
Yup, edited. Though really, creating, and then inverting, the pred matrix is definitely the culprit of at least most of the problems, I've already found that while writing the function.

I actually managed to overload our 256GB server a few times by accidentally giving a transpose of a matrix, leading to a gigantic inversion.

**Comment by dengemann** [comment]
However, +1 for profiling

On Thu, Jul 23, 2015 at 12:02 PM, jona-sassenhagen <notifications@github.com

**Comment by jona-sassenhagen** [comment]
Even though iterative fitting isn't done yet, maybe we could for now close this for #2382 as it has brought decent performance improvements and I'd rather do other stuff before turning to iterative fitting.

**Comment by agramfort** [comment]
Fine with me

**Comment by jona-sassenhagen** [comment]
close for #2382 for now
