### ISSUE TITLE
Make ylim and scalings play nicely in Evoked.plot

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2344]
Currently, ylim and scaling are not playing nicely with each other. If you set 
`ylim = dict(mag=[-300e-15, 300e-15])` and scalings=None, the ylim is not adjusted for the default scaling `mag=1e15`. we should fix it so that `ylim` is in regular units but is scaled internally with the `scalings` param. other option is to explain the behavior, but I feel like no one would expect this behavior.

**Comment by agramfort** [comment]
well the rationale for the current behavior is that the ylim look similar
between sensors and you don't need to think about the exponent for each
channel type

**Comment by teonlamont** [comment]
oh ok, i understand the rationale. maybe I should add a note that the ylim should take the scaling into consideration.

**Comment by agramfort** [comment]
Go for the note

**Comment by teonlamont** [comment]
closing because it only seemed to catch me off guard
