### ISSUE TITLE
Add event_id to read_epochs or selectively read

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2345]
If you only want to load a subset of your epochs from disk, suppplying an event_id could save on memory. currently, it loads all the epochs, and then you can do a selection. for long experiments, and large numbers of epochs, this is not ideal. the event id would find the indices in the events and from there, it can index and load just those epochs. 

one thing that I am not certain of is whether all the epochs would still be temporarily stored in memory. if that's the case, is there any way to read only select epochs?

cc: @Eric89GXL

**Comment by Eric89GXL** [comment]
This would be solved by the more general solution of adding general
on-access reads, so that's my preferred solution. I might be able to do it
next week.

**Comment by teonlamont** [comment]
are we planning to deal with the epochs reading on demand in this cycle?

**Comment by Eric89GXL** [comment]
I might be able to do it. Would that supercede this?

**Comment by teonlamont** [comment]
yeah, i believe so, on-demand then event_id capability.

**Comment by teonlamont** [comment]
closing for #2466
