### ISSUE TITLE
Scaling of EEG data not 10e-6?

### ISSUE THREAD

**Issue by cle1109** [mne-tools/mne-python#2347]
In my EEG data, I get inconsistent results when I look at the raw data in two ways:

1. I access the data directly using `eeg, _ = raw[:, :]`.
2. I convert to a data_frame using `df = raw.as_data_frame()`.

Now when I compare the actual data values, I get a ratio of 10e5. This is somewhat unexpected, because I thought the original EEG data is measured in volts and gets converted to microvolts (i.e. 10e-6) when converting to a data frame.

**Comment by agramfort** [comment]
have a look at the as_data_frame code. It's not much used so likely to be a
bit broken.

**Comment by cle1109** [comment]
Nevermind, I accidentally used `10e6` instead of `1e6`, so everything is fine :-).
