### ISSUE TITLE
epochs.drop_bad_epochs stops kernel

### ISSUE THREAD

**Issue by mattjerhart** [mne-tools/mne-python#2360]
Unless I do:
new_ep = epochs.copy() ;
new_ep.drop_bad_epochs(...). 

#preload=True when I created epochs.

**Comment by Eric89GXL** [comment]
What do you mean it stops the kernel? As in it crashes, or it hangs? Can you make a minimal example (preferably with EpochsArray if possible) that has this problem?

**Comment by Eric89GXL** [comment]
@mattjerhart I'm going to go ahead and close since we haven't heard anything in a few weeks about this, feel free to reopen if it's still going on and you can get us more information
