### ISSUE TITLE
BUG: Can't make forward solution anymore

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#2368]
If I have a data file with only MEG channels, I get an error in `make_forward_solution` that I didn't used to get. The `_prep_channels` used to work if either MEG or EEG was present, even with `meg=True, eeg=True` in the call. Now I get an error, which is a regression, due to the logic being changed to this:
```
    if meg:
        megcoils, compcoils, megnames, meg_info = \
            _prep_meg_channels(info, ignore_ref=ignore_ref, verbose=verbose)
    if eeg:
        eegels, eegnames = _prep_eeg_channels(info, verbose=verbose)
```
@wronk can you change the conditional to something functionally equivalent to `if eeg and len(pick_types(info, meg=False, eeg=True)) > 0:`?

**Comment by wronk** [comment]
Ya, will do. SBT
