### ISSUE TITLE
Noticed redundancy on decoding example: plot_decoding_time_generalization.py

### ISSUE THREAD

**Issue by leggitta** [mne-tools/mne-python#2370]
I just noticed that in ```examples/decoding/plot_decoding_time_generalization.py```, there's an events file name that points to the wrong dataset, but nothing breaks because the events are read using find_events

https://github.com/mne-tools/mne-python/blob/master/examples/decoding/plot_decoding_time_generalization.py#L32-L39

**Comment by mainakjas** [comment]
indeed, can you make a PR?

**Comment by agramfort** [comment]
fixed in master

thakns @leggitta for the bug report

**Comment by kingjr** [comment]
My bad thanks !
