### ISSUE TITLE
Should pick_channels throw an error if you give a string?

### ISSUE THREAD

**Issue by choldgraf** [mne-tools/mne-python#2371]
I say this because it seems to assume that you're passing it an iterable, so if you pass a string then it will break it up into individual letters, which accidentally caused some problems for me earlier.

Another strange behavior is that it will not throw an error if you supply incorrect channel names, so long as at least one of the channel names supplied does match.

E.g., two examples of strangeness:

1. If my actual channel names are ['G1', 'G2', 'G3'] and I supply ['G1', 'MNERULES', 'YESITDOES'] as the channels, then it simply ignores the last two values and returns a `Raw` object with only 'G1' pulled out.

2. If my actual channels names are ['1', '2', '3'] and I supply 'ISTHISA2CHANNELNAME' to pick_channels (note it's a string not a list), then it will silently return a Raw copy with '2' as the picked channel.

It seems like one, or both, of these behaviors is undesirable, no?

**Comment by agramfort** [comment]
PR welcome to check that we get a list as input and not a str

**Comment by choldgraf** [comment]
OK cool. Will do.

**Comment by Eric89GXL** [comment]
this one's done
