### ISSUE TITLE
add i/o for ctf

### ISSUE THREAD

**Issue by mainakjas** [mne-tools/mne-python#2372]
In PR https://github.com/mne-tools/mne-python/pull/2358, I was trying to read in CTF data only to realize we don't have readers for CTF. I'm just raising this issue so that it's not forgotten. For now I'll just convert them to `fiff` using our C utilities.

**Comment by kingjr** [comment]
Where are we on this?

**Comment by agramfort** [comment]
not started but planned by @jasmainak

I am sure he would appreciate help :)

**Comment by Eric89GXL** [comment]
I might have time to take a look

**Comment by Eric89GXL** [comment]
started working on it, hopefully it won't take too long

**Comment by jasmainak** [comment]
@Eric89GXL : unless you already finished it, I can take over from where you feel like leaving it off :)
