### ISSUE TITLE
reference channel positions and brainvision

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#2390]
When I import BV data with the reference keyword set, the reference channel is at position 0,0,0 even though it is specified in the montage file.
(I don't understand that part of the BV code, sorry.)

@teonlamont

**Comment by Eric89GXL** [comment]
@jona-sassenhagen can you share a code snippet and data that you're using to get this behavior? I'm currently dealing with related issues (#2700, #2714) and could probably fix this simultaneously.

**Comment by teonlamont** [comment]
@jona-sassenhagen the reference argument was deprecated in place of the `mne.io.add_reference_channels`.

**Comment by teonlamont** [comment]
sorry for the severely delayed response :(

**Comment by jona-sassenhagen** [comment]
Had forgotten about this :)
