### ISSUE TITLE
Container for DICS solution..

### ISSUE THREAD

**Issue by haribharadwaj** [mne-tools/mne-python#2403]
Looks like regardless of the type of source space in the forward, `_apply_dics(.)` is trying to use a surface `SourceEstimate` container for the result.. I think figuring out the right container based on the `src` type in the `forward` input should fix it? Is there any other catch?

ping @rgoj

**Comment by agramfort** [comment]
indeed. PR welcome.

**Comment by Eric89GXL** [comment]
Looks like this can now return `VolSourceEstimate`, but feel free to reopen if I'm mistaken
