### ISSUE TITLE
Q: concatenating epochs objects

### ISSUE THREAD

**Issue by wmvanvliet** [mne-tools/mne-python#2405]
I have an experiment that is split into two parts. After extracting trials I have two Epochs objects. Now I wish to concatenate them, so that all epochs are in a single Epochs object. Is there a function to do so?

**Comment by mainakjas** [comment]
Take a look at `concatenate_epochs`.

`from mne.epochs import concatenate_epochs`

that does it for you?

**Comment by wmvanvliet** [comment]
exactly what I was looking for, tnx!
