### ISSUE TITLE
ENH Website

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2416]
The website looks great. I just noticed a few things when I was browsing. Feel free to address as you see fit.

In mobile browsing:
- [ ] there's an overlap in the widget containing the number of lines of code and the documentation section
- [ ] the university logos are off-centered with the package logo
- [ ] red bar about dev version is hidden by the toolbar

In general:
- [x] missing sections from reference: ``read_dig_montage`` and ``linear_regression_raw``.

**Comment by Eric89GXL** [comment]
I actually don't think they're off-centered, I think it's a visual thing due to the fact that the logos aren't rectangular. At least according to the HTML they should be centered

**Comment by Eric89GXL** [comment]
I don't see the hiding or the overlap, either, this is what mine looks like:

![screenshot from 2015-08-17 17 37 47](https://cloud.githubusercontent.com/assets/2365790/9316989/b3dc7838-4506-11e5-97bd-f747bc6d8c3d.png)

![screenshot from 2015-08-17 17 38 39](https://cloud.githubusercontent.com/assets/2365790/9317010/d1918a94-4506-11e5-9f05-d9f0c0eb058a.png)

What browser are you using?

**Comment by teonlamont** [comment]
@Eric89GXL I meant browsing on iPhone and other mobile devices. I think it's just how bootstrap is set up to the wrap.

**Comment by teonlamont** [comment]
![unnamed-1](https://cloud.githubusercontent.com/assets/1578674/9317101/627995f6-4507-11e5-81ed-dfe29c2c7569.jpg)

![unnamed](https://cloud.githubusercontent.com/assets/1578674/9317097/602470fa-4507-11e5-8a29-529a18969645.jpg)

**Comment by Eric89GXL** [comment]
Ahh, sorry, missed the mobile bit

**Comment by agramfort** [comment]
reference fixes are more than welcome

**Comment by Eric89GXL** [comment]
Fixed by https://github.com/mne-tools/mne-python/commit/632e49f0470fc9526936dbb474fd6aa46501fe4d. I didn't fix the logo centering, though, because I didn't see an easy way to do it, and it's a minor point. If someone else knows how or wants to do it, feel free.
