### ISSUE TITLE
Spinning off the _hdf5 module?

### ISSUE THREAD

**Issue by choldgraf** [mne-tools/mne-python#2420]
There was just a discussion on the scikit learn listserv where the _hdf5 module in MNE came up. I feel like we've chatted about this here and there in the past, but wanted to open it up more formally.

That _hdf5 module is pretty darn useful, and I think it's too bad that it currently exists hidden to the user. Does anyone think it would be better if that was either a module that you could find more easily (e.g., mne.io.hdf5), or even spun off into its own mini package or something?

**Comment by dengemann** [comment]
@Eric89GXL agreed on releasing it as a separate package as we need this functionality outside of MNE. This would also help reducing maintenance efforts. Now we just have to do it.

**Comment by agramfort** [comment]
I would still keep a copy in mne to avoid another dependency.

**Comment by dengemann** [comment]
The idea was to move it to externals.

**Comment by agramfort** [comment]
Fine with me

**Comment by Eric89GXL** [comment]
What should we call it? If we can come up with a name, I can start a repo and make it in an hour or two.

**Comment by Eric89GXL** [comment]
I propose `pooh`, because it's a funny name (pooh bear) is the spirit of Python, and can stand for Python Objects Onto HDF5

`from pooh import write_hdf5, read_hdf5`

**Comment by Eric89GXL** [comment]
cc @drammock @rkmaddox we need to choose a name to spin off our generic HDF5 writing routines, speak now or forever hold your peace

**Comment by choldgraf** [comment]
lol, I really like pooh for pooh bear, though I also like it because of the
15 year old boy in me, which worries me for that particular name :) maybe
it's fine though? It is catchy...

**Comment by drammock** [comment]
what about a riff on "high five", like `hifive` or similar?

**Comment by Eric89GXL** [comment]
I like it, but it conflicts with at least one existing name:

https://pypi.python.org/pypi/hifive/1.0.3

**Comment by drammock** [comment]
Dang. Other ideas: `pyfive`, `reedwright`

**Comment by choldgraf** [comment]
I like pyfive...it sounds like a startup that lets you order high-fives
with your smartphone

**Comment by Eric89GXL** [comment]
I like pyfive (not really reedwright), but again:

https://testpypi.python.org/pypi/PyFive/1.0a1

**Comment by drammock** [comment]
dammit.  well, `pooh` then.  Or `eeyore`.  I can't think of a pithy name that conveys heirarchical organization, data, and snakes all at once.  Except maybe `IRS`.

**Comment by choldgraf** [comment]
lol, bravo Daniel McCloy, that got a good chuckle out of me

**Comment by dengemann** [comment]
seriously, why not one of these:

- h5io
- h5ext
- h5api
- pyio
- pydump
- h5pickle


it should a) somehow refer to h5py but point out that it's an extensnion or
API or b) refer to serialization

**Comment by Eric89GXL** [comment]
FYI @drammock Python actually refers to Monty Python (not the reptile), but I see your point :)

If only @choldgraf and I like `pooh`, then I can probably live with `h5ext` or `h5io`. `hfive` is also available.

@agramfort you're always good for an opinion, WDYT?

**Comment by agramfort** [comment]
I would go for h5io as it's explicit

**Comment by choldgraf** [comment]
I like h5io, though:

It is a bit redundant...I mean, the whole point of HDF5 is io, right? Just
calling it h5io makes it sound like it could be an *alternative* to h5py,
not an extension...

**Comment by Eric89GXL** [comment]
I agree it's a bit redundant, but it seems like the best non-`pooh` option

**Comment by choldgraf** [comment]
fair enough, I like it if people don't think it'll be confusing

**Comment by Eric89GXL** [comment]
Done, now we just need to incorporate it:

https://github.com/h5io/h5io

**Comment by agramfort** [comment]
let's move this to externals then now.

**Comment by Eric89GXL** [comment]
I'm on it
