### ISSUE TITLE
Possible bug in Bonferroni correction?

### ISSUE THREAD

**Issue by gsudre** [mne-tools/mne-python#2423]
hey all,

Is this a bug in the Bonferroni correction code? Shouldn't line 101 of multi_comp.py (0.9.0) be:

reject = pval_corrected < alpha

instead of:

reject = pval < alpha

?

Thanks,

Gus

**Comment by dengemann** [comment]
@gsudre this bug is fixed on the current master branch.

**Comment by dengemann** [comment]
We should have backported it to 0.9 maint but apprently I missed that. Anyway, if you use the development version it will be fixed.
