### ISSUE TITLE
EpochsArray constructor is broken if len(times) == 1

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#2434]
This is useful for EEG/MEG measures which reduce the time dimension in each trial. It used to work with the last release. Tried to find a fix but it seems to be deeper than I assumed.

cc @Eric89GXL @agramfort

**Comment by dengemann** [comment]
we cuttently have this one in epochs.py:

https://github.com/mne-tools/mne-python/blob/master/mne/epochs.py#L277

It won't play nicely if shape[-1] == 1

as round((tmax - tmin) can be 0

**Comment by dengemann** [comment]
cc @fraimondo

**Comment by dengemann** [comment]
sorry parsed the code incorrectly, so if only 1 time sample exists, the conditional breaks.

**Comment by agramfort** [comment]
can you share a gist that reproduces the bug?

**Comment by agramfort** [comment]
provide a tiny test and we'll make it pass

**Comment by dengemann** [comment]
> provide a tiny test and we'll make it pass

How about this PR instead ? #2435 ;)
