### ISSUE TITLE
FIX/ENH: Xdawn does not regularize by default when fitting epochs

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#2448]
As a result the signal cov can end up not being positive definite, which required by the tanh.
I would suggest to use mne.compute_coveriance with shurnk if epochs are passed.

**Comment by dengemann** [comment]
cc @alexandrebarachant

**Comment by kingjr** [comment]
Just encountered the issue, so +1 for the shrunk as default.

**Comment by kingjr** [comment]
Related to this, shall we pass a `method` arg to `compute_raw_covariance`, to make it work with the [example](http://martinos.org/mne/dev/auto_examples/preprocessing/plot_xdawn_denoising.html#sphx-glr-auto-examples-preprocessing-plot-xdawn-denoising-py)?

**Comment by dengemann** [comment]
For raw we don't have / need the method param...

**Comment by larsoner** [comment]
I think the error message is clear enough (about semidef, telling you to use reg) as is the solution (pass reg param) so that the deprecation cycle necessary to fix this is not worth it. Closing, but feel free to reopen if you disagree
