### ISSUE TITLE
ENH/VIZ: better default colors for EOG in epochs butterfly plot

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#2450]
They're black as EEG and it can be difficult to understand what's going on in cases where the EOG channels have some problem with offsets.

**Comment by jona-sassenhagen** [comment]
How about
![unknown-57](https://cloud.githubusercontent.com/assets/4321826/9662075/2cc2c1bc-525e-11e5-980b-756ee216b27c.png)

The hard part is actually the topomaps on top, the spatial colors for the channels are 2 lines and the bottom left legend is not that complicated.

**Comment by dengemann** [comment]
Ahh --- epochs butterfly --- the epochs viewer, when you hit 'b' to look at single trial butterflies, the EOG and the EEG are both black.

**Comment by jona-sassenhagen** [comment]
Oh yes, I was thinking of evokeds ... (I never use any of the interactive functions.) But couldn't you do the same thing still?

**Comment by dengemann** [comment]
> Oh yes, I was thinking of evokeds ... (I never use any of the interactive functions.) But couldn't you do the same thing still?

It's a different problem. I think you'll better understand it once you start looking at your data using epochs.plot ;-)

**Comment by agramfort** [comment]
@dengemann can we close this?

**Comment by larsoner** [comment]
Closing due to non-response
