### ISSUE TITLE
numpy.power in TFR code

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#2457]
We use `np.power` in our TFR code, and `np.power(x, 2, x)` doesn't produce `nan` values whereas `x *= x` does. This suggests `power` is doing something extra, and we should investigate what it is. We should also figure out if leaving or masking the `nan` values with zero (which is probably what `power` does) is the proper thing to do.

**Comment by Eric89GXL** [comment]
see #2456

**Comment by dengemann** [comment]
My bad. A typo on my end made me believe we had an issue with nans. pow *= pow actually works. Fix is coming.
