### ISSUE TITLE
FIX?: vague user reports, raw.resample destroys trigger channels 

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#2465]
and generate massiv rejections of epochs with "TOO_SHORT" flag in the drop log.

cc @Eric89GXL @mainakjas ...
cc @cmoutard

**Comment by agramfort** [comment]
cc @wmvanvliet 

it was changed during the sprint AFAIK

**Comment by wmvanvliet** [comment]
@dengemann details please?

**Comment by dengemann** [comment]
> @dengemann details please?

people around here resample their data and script that used to run cras how as 90% of the epochs get rejected. See above. I did not have the problem so far.

**Comment by agramfort** [comment]
can they share a file + gist?

**Comment by wmvanvliet** [comment]
The new version of the code is less likely to drop event markers. Depending on how the epochs are cut, TOO_SHORT epochs could maybe arise when a buggy stimulus channel shows an on-off-on-off pattern of the event marker?

I'm sorry without any sort of details, there's no way I can debug this.

**Comment by jona-sassenhagen** [comment]
Should probably close this. It's likely it was the thing @wmvanvliet fixed during the sprint.
