### ISSUE TITLE
BUG: parts of our MNE-C forward workflow are missing in Python

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#2478]
Someone must have forgotten to implement this ;)
It's perfect for a lazy sunday hack, basiclaly convert a shell script to Python.

**Comment by agramfort** [comment]
It's

mne_setup_forward_model

**Comment by dengemann** [comment]
> mne_setup_forward_model

I wanted to keep it interesting ;)

**Comment by agramfort** [comment]
@lorenzo-desantis are you up for it?

**Comment by lorenzo-desantis** [comment]
Yes, but I don't think I'll be able to start right away!
