### ISSUE TITLE
evoked.plot_topomap auto mode for GFP peaks

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#2490]
if would be great if evoked.plot_topomap could automatically set the times of interest eg. by finding the peaks for the global field power.

I would do something like:

evoked.plot_topomap(times='auto')

there might be a bit of work with peak finding though...

**Comment by jona-sassenhagen** [comment]
Maybe as simple as

    if times == "auto":
        gfp = evoked.data.std(axis=0)
        times = argrelmax(gfp, order=int(evoked.info["sfreq"] / 5))

I've also played around with find_peaks_cwt a bit, but this one actually works better for e.g. the examples.

**Comment by jona-sassenhagen** [comment]
Also maybe the key should be "peaks" and not "auto" because you probably also want an explicit way of calling the dumb sequence (like it is right now). Not `None | "auto" | array`, but `"auto" | "peaks" | array`
And make it default to `auto` and produce the current behavior.

**Comment by agramfort** [comment]
I like that

Thanks for the suggestion

**Comment by jona-sassenhagen** [comment]
Should I make a PR?

**Comment by agramfort** [comment]
Go for it if you have some time

**Comment by jona-sassenhagen** [comment]
Closed by #2526, #2506?

**Comment by Eric89GXL** [comment]
Agreed, @agramfort reopen if we're wrong
