### ISSUE TITLE
click on evoked.plot to get butterfly plot

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#2491]
currently one can click on a line of evoked.plot to get channel name.

it would be great to be able to click on an empty region to plot the topomap of this time instant.

A more advanced used case could be to be able to select a time interval in which data is averaged to produce the topomap

**Comment by agramfort** [comment]
maybe for @jaeilepp

**Comment by dengemann** [comment]
> A more advanced used case could be to be able to select a time interval in which data is averaged to produce the topomap

I like this! +1

**Comment by Eric89GXL** [comment]
Sounds good, but maybe trigger it by something other than a left click in
empty space. It's pretty easy to accidentally click in space when trying to
click a line/channel, and it would be annoying to have a plot pop up due to
such a minor click miss. So maybe middle or right click instead.

**Comment by agramfort** [comment]
fine with me
