### ISSUE TITLE
Bug mne.cov.compute_covariance + multiprocessing

### ISSUE THREAD

**Issue by LaetitiaG** [mne-tools/mne-python#2497]
Hi,
I just want to mention that I used the mne.cov.compute_covariance function and it works with n_jobs =1 (as in the example) but if I put more jobs, I have the following error message:

File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
raise self._value

PicklingError: Can't pickle <class 'mne.cov._ShrunkCovariance'>: it's not found as mne.cov._ShrunkCovariance

**Comment by dengemann** [comment]
Ah that's annoying. We did not have that before. Cannot take a look right
now. We should bisect and see when this came up. Laetita btw. you can use
MKL + Anaconda. In my experience it will be faster than using joblib here.

**Comment by agramfort** [comment]
denis can you reproduce?

**Comment by Eric89GXL** [comment]
I'm going to go ahead and close this as an isolated upstream bug (probably `multiprocessing`), but if it comes back up or is still happening, let's reopen
