### ISSUE TITLE
FIX: Check magnetometer type in SSS

### ISSUE THREAD

**Issue by wronk** [mne-tools/mne-python#2502]
The geometry of the sensors is important for SSS processing. At least at UW, our MEG marks gradiometer with the wrong geometry type (T2 instead of the T3). The Elekta coil geometry is only defined for T3 right now, so the SSS functions should check that that the magnetometers are T3, which I'll probably add in the tSSS PR #2400. If they're not T3, we might want to warn the user and then prompt them to use a (yet to be written) function that will update the mag types if appropriate.

**Comment by Eric89GXL** [comment]
I can write a little function tomorrow to allow us to update it.

**Comment by Eric89GXL** [comment]
Assuming #2503 gets merged quickly, @wronk you rebase #2374 and add a check there. Basically if fine cal is not used, and T1/T2 type magnetometers are detected, give a `warnings.warn(...)` that they probably need to use `fix_mag_coil_types` on their data.

**Comment by wronk** [comment]
This is addressed now. If any T1/T2 channels are present when `maxwell_filter` is called (regardless of fine-cal or other params), they are warned to use `fix_mag_coil_types`.

Should we wait to close until the (oversized) fine-cal PR is merged?

**Comment by Eric89GXL** [comment]
Yeah this should auto-close
