### ISSUE TITLE
IOError when plotting source locations

### ISSUE THREAD

**Issue by bam54** [mne-tools/mne-python#2519]
I'm trying to run plot_spm_faces_dataset.py on Ubuntu 14 with Python 2.7.6.  At the end of the script, stc.plot(hemi='both', clim='auto') is called.  At first, an error was thrown in io.py when trying to initialize a Surface instance: it looked like the program was looking in os.environ for a value (SUBJECTS_DIR) defined earlier in plot_spm_faces_dataset.py that hadn't been added, so I simply added this value.  After this, another error was thrown from io.py in read_geometry: 

    IOError: [Errno 2] No such file or directory: u'~/mne_data/MNE-spm-face/subjects/spm/surf/both.inflated'

Is this file supposed to be located on my system or is there a bug somewhere?

**Comment by Eric89GXL** [comment]
Try upgrading `PySurfer`, I suspect you are using an outdated version

**Comment by agramfort** [comment]
and yes these files should be on your system.

**Comment by bam54** [comment]
Upgrading PySurfer did the trick, I was using 0.4.  Thank you!
