### ISSUE TITLE
evoked.plot_topomap multiple masks

### ISSUE THREAD

**Issue by ImmanuelSamuel** [mne-tools/mne-python#2530]
Is there a way for multiple masks and mask params in evoked.plot_topomap?

**Comment by agramfort** [comment]
I don't understand the question. Can you explain more what you want to do?

**Comment by ImmanuelSamuel** [comment]
I want to highlight two sets of channels in two different colors.

**Comment by agramfort** [comment]
like two clusters? do you have an example image eg in a paper?

**Comment by ImmanuelSamuel** [comment]
![image](https://cloud.githubusercontent.com/assets/7865018/10527969/6dd464ca-7361-11e5-84c9-0ecfd0e09409.png)

**Comment by ImmanuelSamuel** [comment]
Okay I got it. I just plot it twice with different masks
