### ISSUE TITLE
BUG: TimeDecoding

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#2535]
There's a bug in `TimeDecoding` when `n_jobs=-1`. Please wait before release.

**Comment by dengemann** [comment]
Confirmed, I remember we had this in BA with n_jobs=2.

**Comment by kingjr** [comment]
It's because of the way I chunk the data to avoid the memory duplicates. 

However, the preindexing option you mentioned last time should eventually get rid of this kind of issues, and greatly clarify the code. 

I'm on this in the meantime :/

**Comment by dengemann** [comment]
while you are at it checkout the line_rofiler -- it will make you understand.
Also checkout the first steps we took with @fraimondo : https://github.com/fraimondo/mne-python/commit/973c7d5623cfa3d0ff143af5861fa826482e7ef6

**Comment by dengemann** [comment]
... and the 2 previous commits.

**Comment by kingjr** [comment]
Ok, let's take things in order. First fix, then improve in next PR?

When fixing I realized that the predictions cannot be currently parallelized in `TimeDecoding` (because the parallel runs across testing time points).

**Comment by dengemann** [comment]
Yes, sounds good. 

> When fixing I realized that the predictions cannot be currently parallelized in TimeDecoding (because the parallel runs across testing time points).

Refactoring is keeping you busy ;)

**Comment by kingjr** [comment]
> Refactoring is keeping you busy ;)

oh dear, a never ending story
