### ISSUE TITLE
`decimate` method for `Evoked`

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2547]
I just noticed that `Evoked` doesn't have a `decimate` method. Should we add it?

**Comment by Eric89GXL** [comment]
YAGNI?

**Comment by kingjr** [comment]
I agree with Eric, decimate is only useful for heavy datasets, evokeds shouldn't be in this category.

**Comment by teonlamont** [comment]
that's fine with me, just stumbled across a usecase in the example. simple index is sufficient.
