### ISSUE TITLE
EHN: #Easy add pick_type to epochs.average()

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#2548]
If anyone have some free time..

**Comment by agramfort** [comment]
I don't get it. What is it you cannot do currently?

**Comment by kingjr** [comment]
we can do `epochs.average(picks=picks)` but not `epochs.average(pick_types='eeg')`.

Also, IIRC, you can't do `epochs.average()` for `seeg` data (because seeg is not part of the default picks)

**Comment by agramfort** [comment]
> we can do epochs.average(picks=picks) but not epochs.average(pick_types='eeg').

write one more line to get the picks or do

epochs.pick_types(meg=False, eeg=True).average()

> Also, IIRC, you can't do epochs.average() for seeg data (because seeg is not part of the default picks)

this is a bug. PR welcome

**Comment by kingjr** [comment]
> write one more line to get the picks or do 
> epochs.pick_types(meg=False, eeg=True).average()

Sure, my feeling was that it'd be more consistent to have a pick_types param if you have a picks. But I won't fight for this.

> this is a bug. PR welcome
all right then
