### ISSUE TITLE
Epochs.plot load epochs on the fly

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2556]
In `raw.plot`, raw data are loaded on demand when `preload=False`, is it possible to do the same when for epochs when `preload=False` too instead of loading them all.

**Comment by agramfort** [comment]
good idea

how come you have so big epochs?

**Comment by Eric89GXL** [comment]
It should be possible. @jaeilepp?

**Comment by jaeilepp** [comment]
I'll look into it.

**Comment by teonlamont** [comment]
@agramfort I expanded time windows to get a fuller understanding. came with a cost
