### ISSUE TITLE
auto build of dev doc

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#2557]
we should have a nightly build of the dev doc.

sklearn is planning to use circle CI https://github.com/scikit-learn/scikit-learn/pull/5578

any other opinion?

**Comment by agramfort** [comment]
cc @jaeilepp

**Comment by Eric89GXL** [comment]
We can probably do it with CircleCI and I trieid a couple months ago, but it would be a lot easier if they would disable autodetection of type. See issue I opened here:

https://discuss.circleci.com/t/disable-autodetection-of-project-or-application-of-python-venv/235

If they don't move on it in a couple months, I might try using system Python, but suspect it will be too difficult for the effort given how many dependencies we have.

**Comment by jasmainak** [comment]
yeah, this would be great to have and it would also encourage more contributions to the docs.

**Comment by jasmainak** [comment]
By the way, it would be cool to have a way to build only one file / directory in the examples selectively. Currently, I do it by moving the folders outside the examples/ dir except the one I need to process (it's a bit less involved as I know sphinx processes the files alphabetically). And then move it back once it's built. It's useful for cross-linking the examples and examples images ...

**Comment by Eric89GXL** [comment]
@jaeilepp has done this now. @agramfort do we need to do something to trigger an upload from `circleci` to `github`?

**Comment by agramfort** [comment]
>
> @jaeilepp <https://github.com/jaeilepp> is working on it.
>
I am dreaming of a working nightly build of the doc ...

**Comment by Eric89GXL** [comment]
Oh right, it dosen't quite work fully yet. I'll leave this open. Do we have a plan for how to upload it once the CircleCI artifact is correct (i.e., once Mayavi works)?

**Comment by agramfort** [comment]
yes mayavi is the "only" pb ...

**Comment by Eric89GXL** [comment]
I think this one is good, @jaeilepp feel free to reopen if I'm wrong
