### ISSUE TITLE
Cluster Statistics Multi cluster problem

### ISSUE THREAD

**Issue by ImmanuelSamuel** [mne-tools/mne-python#2563]
I have the following topo and a number of observations of the same

![image](https://cloud.githubusercontent.com/assets/7865018/10742831/9f176bfc-7c05-11e5-880c-62f5cdc3f87c.png)

```
T_obs, clusters, cluster_pv, H0  = mne.stats.permutation_cluster_test(X, threshold=None, n_permutations=1024, tail=0,
                                   connectivity=connectivity, verbose=None, n_jobs=1, seed=None, max_step=1, exclude=None, 
                                   step_down_p=0, t_power=1, out_type='mask', check_disjoint=False, buffer_size=1000)
```

This gives me only one cluster but from the topo we can see that there are two clusters.
What am I doing wrong here?
![image](https://cloud.githubusercontent.com/assets/7865018/10742543/15fdbd72-7c04-11e5-84f0-d7e6d4177904.png)

**Comment by ImmanuelSamuel** [comment]
Is there a way to set max cluster size?

**Comment by Eric89GXL** [comment]
I wonder if the sensors on the right are close enough to be considered "neighbors" by the algorithm...?

No way to set max cluster size, but changing the preliminary threshold to be more restrictive will effectively shrink the cluster sizes because it will reduce the number of clusterable points.

**Comment by ImmanuelSamuel** [comment]
Interesting. Do you know where was the algorithm obtained from?

**Comment by Eric89GXL** [comment]
It's a general algorithm, see e.g.  Maris/Oostenveld (2007), "Nonparametric statistical testing of EEG- and MEG-data" Journal of Neuroscience Methods, Vol. 164, No. 1., pp. 177-190. doi:10.1016/j.jneumeth.2007.03.024. You can set the connectivity however you like, can't remember who did our specific implementation for sensor space. You could try using `git blame` (or GitHub's equivalent) to figure it out if you're really curious.

**Comment by Eric89GXL** [comment]
I'm going to close this since the method seems to work properly as implemented.
