### ISSUE TITLE
Enlarge ERP plots in plot_evoked_topo

### ISSUE THREAD

**Issue by cle1109** [mne-tools/mne-python#2579]
I was wondering if it is possible to enlarge the ERP plots in `plot_evoked_topo` (and thereby reducing the space between the single plots). Right now, there's a lot of black space between my plots, which are really small and difficult to interpret.

**Comment by agramfort** [comment]
I agree that our plot topo overfits the neuromag setup and is not great
besides for data exploration (not good for paper figures)

**Comment by jona-sassenhagen** [comment]
I used to have code for that, but wasn't good enough of a coder to actually finish it. I probably will finish that eventually, but I can't promise when.

**Comment by cle1109** [comment]
OK, thanks for the heads up - I'm closing this for now since there is a clear answer to my question.
