### ISSUE TITLE
ENH: finding bem surfaces

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#2592]
is currently very instable,
it assumes certain hardcoded names, not naming pattenms, and expects head coordinates in some functions. I forgot detail but it's recently been a constant mess to work with different. Who wants to do something good while feeling bored should investigate it and simplify things.

**Comment by dengemann** [comment]
It's also a pain that we expcect people do do the linking trick as suggested by the old manual. We should not do that. It should just work. I think we should more adopt the principle of least surprise to make our users more happy.

**Comment by agramfort** [comment]
I have add similar issues in the past. But how did this pb show up for you?

**Comment by dengemann** [comment]
> I have add similar issues in the past. But how did this pb show up for you?

processign somato data

**Comment by Eric89GXL** [comment]
There is a more specific discussion in #3406, feel free to write there as specific examples come up
