### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by ahibahi** [mne-tools/mne-python#2594]
Hi,
I've been using MNE-python for a month with no issues.
Suddenly there's an http error when I try to load the sample dataset
I've tried upgrading and downgrading python as well.still no luck.

This is the code,
from mne.datasets import sample
data_path = sample.data_path() //throwing error at this point

![error](https://cloud.githubusercontent.com/assets/6408125/10965495/4d749ace-83d3-11e5-8876-ee0a38f47c53.PNG)

please help me 
thank you very much

**Comment by agramfort** [comment]
can you see if you can download the file directly:

https://s3.amazonaws.com/mne-python/datasets/MNE-sample-data-processed.tar.gz

?

**Comment by ahibahi** [comment]
Thank you for the reply.
I'm not able to access it directly as well
Is there any other settings that I should do?

![acces_denied](https://cloud.githubusercontent.com/assets/6408125/10965899/0066e2f2-83d6-11e5-9418-b84cb1ee7d5f.PNG)

**Comment by agramfort** [comment]
@Eric89GXL did you do something?

**Comment by ahibahi** [comment]
I tried installing mayavi library which gave me some errors.So I uninstalled python and reinstalled it.
Now its giving me this 403 error.

**Comment by agramfort** [comment]
yes I have the same download problem.

**Comment by Eric89GXL** [comment]
Yeah I updated the dataset and probably broke it, will fix soon

**Comment by ahibahi** [comment]
It would be really helpful if you can notify me once its fixed.
Thank you very much.

**Comment by Eric89GXL** [comment]
Should be all better, feel free to reopen if it still doesn't work
