### ISSUE TITLE
chdir when watershed

### ISSUE THREAD

**Issue by yuval-harpaz** [mne-tools/mne-python#2598]
Hi MNEers
I noticed that when I run mne.bem.make_watershed_bem I finish in the subject's directory/watershed
This could be comfortable for certain purposes but I generally find it confusing.
what do you think?

**Comment by agramfort** [comment]
yes I agree if should bring you back to initial dir

PR welcome

**Comment by dgwakeman** [comment]
or better yet, not change directory ever, so that there is no chance if an error occurs of being in a different dir.

**Comment by agramfort** [comment]
If that can work +1

PR welcome

**Comment by Eric89GXL** [comment]
It can be done safely with a try/except if the commands require being in a
specific directory, too, but I prefer that only if complete paths won't work
