### ISSUE TITLE
fix filename and directory of inner_skull after watershed

### ISSUE THREAD

**Issue by yuval-harpaz** [mne-tools/mne-python#2599]
Hi
since now watershed is nicely wrapped in mne  it is an opportunity to stop this issue of creating a link  bem/watershed/inner_skull_surf > bem/inner_skull.surf
I suggest cpoying rather than linking because links may break when moved from folder to folder or from PC to PC.
now I run
shutils.copyfile(subjects_dir + "/" + subject + "/bem/watershed/" + subject +
         "_inner_skull_surface", subjects_dir + "/" + subject + "/bem/inner_skull.surf")

**Comment by agramfort** [comment]
fine with me.

PR welcome

**Comment by dgwakeman** [comment]
maybe making this copy an option instead of the default (I like symbolic links), it saves unnecessary wastes of disk space, and is less confusing when one has multiple BEM types. For example, if I generate both a watershed and MEFLASH BEM, I can tell from a simple ls -l, which surface I am using here, while if one copies the files you cannot easily tell.

**Comment by yuval-harpaz** [comment]
a link is also fine with me if disk space is an issue
or even 'move' for default behaviour if nobody uses the original ones

On 9 November 2015 at 00:25, dgwakeman <notifications@github.com> wrote:

> maybe making this copy an option instead of the default (I like symbolic
> links), it saves unnecessary wastes of disk space, and is less confusing
> when one has multiple BEM types. For example, if I generate both a
> watershed and MEFLASH BEM, I can tell from a simple ls -l, which surface I
> am using here, while if one copies the files you cannot easily tell.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mne-tools/mne-python/issues/2599#issuecomment-154881873>
> .
>



-- 
Yuval




Dr .Harpaz

BIU MEG lab <http://faculty.biu.ac.il/~goldsa/index.html>

**Comment by agramfort** [comment]
I see one argument for copying:

- windows users that copy freesurfer files to work later from windows.

but I agree that symlinks are useful to know from what bem type file are
coming from.

if there is no consensus or blocker, let's focus on more urgent matters.

my 2c

**Comment by Eric89GXL** [comment]
This has been open for a year with no action. I'll go ahead and close but if this is a needed/wanted feature we can come back to it
