### ISSUE TITLE
Unbundle libs

### ISSUE THREAD

**Issue by ignatenkobrain** [mne-tools/mne-python#2600]
- [ ] `six`
- [ ] `jdcal`
- [ ] `decorator`
- [ ] `h5io`
- [ ] `tempita`

I think we should use system libs for because those are ready for system-installing

**Comment by ignatenkobrain** [comment]
I can make patches for you, it will take few hours, but before I want to ensure that you are interested to accept patches.

**Comment by dengemann** [comment]
Not sure what you are proposing. To minimize installation issues we have keep them in externals, I don't see any strong reason to change this, it save's us a lot trouble I think.

**Comment by ignatenkobrain** [comment]
But when we're talking about packaging into distros (I'm packaging for Fedora) it *causes* troubles because bundled libraries isn't allowed.

**Comment by agramfort** [comment]
for debian there are some patches that are applied to remove these from the
repo and use system versions. I think you should do the same for fedora.

See :

https://packages.debian.org/sid/python/python-mne

**Comment by agramfort** [comment]
see

http://anonscm.debian.org/cgit/debian-med/python-mne.git

**Comment by ignatenkobrain** [comment]
For Fedora I did unbundling, but I'd want to send to upstream. That's why I created this issue and ask developers if they interested.

**Comment by Eric89GXL** [comment]
In `ext` we could first try to load the system version and fall back to our bundled version. Then the only thing the patch needs to do is exclude certain files from `mne/externals/`.

**Comment by agramfort** [comment]
I would not change anything to master but apply patches during packaging
for the different distributions. As we do for debian

**Comment by dengemann** [comment]
+100

**Comment by Eric89GXL** [comment]
Closing as we've decided to use the patch-and-package method instead
