### ISSUE TITLE
Hash for sample download seems to be wrong?

### ISSUE THREAD

**Issue by ARudiuk** [mne-tools/mne-python#2609]
When I try to do a fresh download of the sample data set it tells me the hash is incorrect once downloaded. I have tried this on my home and my work computer, both times the hash of the downloaded file was ccf5cbc41a3727ed02821330a07abb13. 

It seems strange to keep getting the same wrong hash, which leads me to believe that the hash to check against in the source code is wrong.

**Comment by Eric89GXL** [comment]
Argh, yes it is wrong in the source code. I updated the file on Amazon but didn't update the hash. Feel free to make a PR to fix it, otherwise I can get to it later today or tomorrow.

**Comment by ARudiuk** [comment]
I'll put in a quick PR then.
