### ISSUE TITLE
plot_topomap, using `title` messes up the colorbar

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#2615]
This is the plot_topomap example.

Without title, it looks fine:
![screen shot 2015-11-13 at 19 24 02](https://cloud.githubusercontent.com/assets/4321826/11153906/474ea102-8a3c-11e5-89ea-fa9fd6ffe356.png)
But if you give an argument to the `title` kwarg, this happens:
![screen shot 2015-11-13 at 19 23 48](https://cloud.githubusercontent.com/assets/4321826/11153910/4a857832-8a3c-11e5-911c-5244dcd7317a.png)

Both with interactive plotting, and in the notebook.

**Comment by agramfort** [comment]
PR welcome

**Comment by jona-sassenhagen** [comment]
Close for #2621
