### ISSUE TITLE
matplotlib 1.5 changes how lines can be colored

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#2616]
`axis._get_lines.color_cycle` has been replaced by `axis.set_prop_cycle` plus `cycler.cycler` in matplotlib 1.5 (see [here](http://matplotlib.org/examples/color/color_cycle_demo.html)). This impacts plotting e.g. bad channels in a different color; for example, `plot_read_evoked.py` looks like this now:

![screen shot 2015-11-13 at 21 27 40](https://cloud.githubusercontent.com/assets/4321826/11156702/ce78be86-8a4d-11e5-9806-59aca15531c9.png)

Is simultaneous support for matplotlib 1.5 and earlier the goal?

**Comment by agramfort** [comment]
We should support older versions too
