### ISSUE TITLE
read_raw_bti without headshape

### ISSUE THREAD

**Issue by yuval-harpaz** [mne-tools/mne-python#2619]
Hi
I was trying to compute noise cov with empty room measurement (no headshape of course) and I couldn't read it with mne.io.bti.read_raw_bti because of the absence of a headshape
please change the error into a warning

 ValueError: Could not find the head_shape file "hs_file". You should check whether you are in the right directory or pass the full file name.

Thanks

**Comment by agramfort** [comment]
ping @dengemann

**Comment by dengemann** [comment]
@yuval-harpaz you need to pass None in that case, it will then skip the hs part.

**Comment by yuval-harpaz** [comment]
I see , thanks

On 15 November 2015 at 12:25, Denis A. Engemann <notifications@github.com>
wrote:

> @yuval-harpaz <https://github.com/yuval-harpaz> you need to pass None in
> that case, it will then skip the hs part.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mne-tools/mne-python/issues/2619#issuecomment-156799298>
> .
>



-- 
Yuval




Dr .Harpaz

BIU MEG lab <http://faculty.biu.ac.il/~goldsa/index.html>
