### ISSUE TITLE
Thoughts on xray data structures?

### ISSUE THREAD

**Issue by choldgraf** [mne-tools/mne-python#2622]
Have you guys looked into xray at all? It seems pretty nifty, though probably too early to say if it'll be widely adopted or not:

http://xray.readthedocs.org/en/stable/data-structures.html

Right now we have methods like to_dataframe, but it sounds like to_dataarray would make more sense for something like epochs data. Just bringing this up to see what people think about it.

**Comment by agramfort** [comment]
write a blog post to convince us? :)

seriously I've used xray in the past and it's cool but I am not sure we are
willing to add more code to mne for this. We moved back on pandas...

my 2c

**Comment by jona-sassenhagen** [comment]
I think it'd be really cool cause I'm an idiot who always forgets what the dimensions are and it would be simpler if I could do something like .mean("time") or .mean("sensors") instead.

**Comment by jona-sassenhagen** [comment]
Maybe minimally there could be an xray equivalent of `.get_data` (which returns pandas data frames).

**Comment by dengemann** [comment]
Sorry to crash the party. Do we really need this here in MNE? A nice blog
post would do it too. It's Python, everyone can assemble his pipeline by
putting together elements from different libraries. We already have Pandas.
And we had enough effort maintaining it so far.
If you want more sophisticated labled access to data let's maybe improve
our API. A core task that I see there is an internal abstraction that
handles time and frequency. E.g. it's confusing to abuse .times for
frequencies all over the place. We have enough open tasks on this end.

**Comment by choldgraf** [comment]
Agreed that there are bigger fish to fry first. I think that having an EpochTFR-style object would be useful just because there are functions that assume the kind of data that an EpochTFR object would have, whereas the functions for decomposing a signal into a TFR tend to automatically average across trials, so it's a bit clunky in that sense. Maybe one day xray will be fully-featured enough to be worth implementing as a basic component of a neural analysis package, but probably that day is not today :P

**Comment by choldgraf** [comment]
I'm gonna close this so that it's not cluttering up the issues, but maybe it can pop back up in the future :)

**Comment by jona-sassenhagen** [comment]
>I think that having an EpochTFR-style object would be useful just because there are functions that assume the kind of data that an EpochTFR object would have, whereas the functions for decomposing a signal into a TFR tend to automatically average across trials
FWIW @choldgraf I want to extend linear_regression_raw to the time-frequency domain eventually.

**Comment by choldgraf** [comment]
Cool - I think this would be great as well. Check out #2024 where we discussed this a bit a while ago, and I believe I posted some code for something like an "EpochTFR" analysis. I've been meaning to take a look at the linear_regression code too, as all of my work is using regression for encoding models in ECoG :)

**Comment by jona-sassenhagen** [comment]
Note an EpochTFR thing would be, if at all, for linear_regression. linear_regression_raw circumvents epochs. linear_regression_raw with a TF option would directly return AverageTFR objects per condition estimated from a continuous (raw?) file.

**Comment by jona-sassenhagen** [comment]
EpochTFR would still be cool for example if we want to do something like decoding in the time-frequency domain.

**Comment by choldgraf** [comment]
Agreed - I just meant that as an aside, not as directly related to EpochTFR. The challenge with the full TFR decomposition is just that it tends to combinatorially explode analysis time, but would be very cool to be able to keep that information for decoding purposes etc. One issue I've run into with this object is the I/O can be expensive depending on how much precision you want in the numbers. If you store them as higher-bit numbers, then the size of files can get up to like 5-6GB and it was making our sysadmin unhappy with me...

**Comment by jona-sassenhagen** [comment]
Ah right- I'm thinking 30 channel EEG from 1 to 30 Hz here :)
