### ISSUE TITLE
v0.11

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#2639]
Do we want to make a `maxwell_filter`-themed holiday release in a month? If so, I'll start pushing existing issues marked v0.11 to v0.12.

**Comment by agramfort** [comment]
would be good.

what are the list of things we want to complete before?

**Comment by dengemann** [comment]
Great idea.
On my side some more ICA edits, e.g. components  by rank and probably #2586.

**Comment by Eric89GXL** [comment]
CTF reading and maybe raw test refactoring would be good. I'll get marking.

**Comment by agramfort** [comment]
once we have CTF support we should update the SPM examples are work with
the native format. Not the converted fif files.

**Comment by Eric89GXL** [comment]
Sure. You want me to do that as part of the PR? I suspect you're already avoiding reviewing it because of the number of lines changed, so maybe a subsequent PR is better :)

Also the FIFF constants PR should go in release, I've marked it.
