### ISSUE TITLE
Saving raw object converts highpass and lowpass from None to nan, and filter cannot handle it afterwards

### ISSUE THREAD

**Issue by Teekuningas** [mne-tools/mne-python#2652]
Hi,

It seems you can do this:
```python
>> raw = mne.io.read_raw_egi('file-with-no-highpass-and-lowpass-information')
>> raw.info['highpass'] is None
True
>> raw.save('temp.fif')
>> raw = mne.io.Raw('temp.fif')
>> raw.info['highpass']
nan
>> raw.filter(l_freq=1, h_freq=40)
>> raw.info['highpass']
nan
```

So saving a raw object load from egi with highpass and lowpass set to zero has highpass and lowpass converted to nan, and after reread for example filtering assumes that "no information" is coded as None, and is not willing to update highpass and lowpass information, if otherwise. Data changes ok, though. As a workaround I am at the moment converting None's to 0 and sfreq/2 before saving, but it might not should be necessary.

**Comment by agramfort** [comment]
see https://github.com/mne-tools/mne-python/pull/2655

**Comment by Teekuningas** [comment]
Yes, that does the trick. Thanks.
