### ISSUE TITLE
Type problem mne.read_epochs vs. mne.io.set_eeg_reference

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#2677]
When I read epochs with `mne.read_epoch`, their type is `EpochsFIF`. `set_eeg_reference` does a check if the target is an `Epochs` object. This leads to a `ValueError: operands could not be broadcast together` because the function tries to treat the EpochsFIF file as an Evoked file in line 116 of mne/mne-python/mne/io/reference.py.

**Comment by Eric89GXL** [comment]
It should probably check for _BaseEpochs, PR welcome if you have time

**Comment by agramfort** [comment]
PR welcome. It should be one line to change in reference.py (L 113)

**Comment by jona-sassenhagen** [comment]
Closed by #2678
