### ISSUE TITLE
Where is $MNE_ROOT/bin/mne_setup_sh

### ISSUE THREAD

**Issue by ImmanuelSamuel** [mne-tools/mne-python#2679]
I am trying to get C API working. Seems as though I need to source the mne_setup_sh file. It is supposed to be in bin but it is not.

**Comment by dengemann** [comment]
> It is supposed to be in bin but it is not.

where do you look for it?
It is supposed to be in the bin of the MNE-C tools.

**Comment by ImmanuelSamuel** [comment]
I was looking for it in path/mne-python/bin. Where is the MNE-C tools folder?

**Comment by agramfort** [comment]
http://martinos.org/mne/dev/getting_started.html#downloading-and-installing-the-unix-commands

**Comment by ImmanuelSamuel** [comment]
I was following that page but thought it was for mne-python. Didn't see the download link.Thanks @agramfort and @dengemann
