### ISSUE TITLE
Surface inner skull is not completely inside surface outer skull

### ISSUE THREAD

**Issue by ImmanuelSamuel** [mne-tools/mne-python#2683]
I used the ch2 image from mricron to run recon-all and then used mne.make_bem_model(). I get a very obvious error. I tried doing the same with the MNI152_1mm template and I get the same error. It works for a normal t1 image.
How to get a BEM for a standard template?

**Comment by jona-sassenhagen** [comment]
Hey @ImmanuelSamuel , have you constructed a BEM model for a standard brain?
