### ISSUE TITLE
Sklearn warnings for cov

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#2687]
I'm running latest `sklearn` and I get this when doing `mne.compute_covariance`:
```
/home/larsoner/.local/lib/python2.7/site-packages/sklearn/cross_validation.py:42: DeprecationWarning: This module has been deprecated in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/home/larsoner/.local/lib/python2.7/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module has been deprecated in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
```
@agramfort @dengemann any time to look into how to fix this before 0.11 release (in the next week probably), or should we push to 0.12?

**Comment by agramfort** [comment]
git grep cross_validation

then rename cross_validation to model_selection

and make sure tests pass and updated examples also

however we should support both versions for some time but just in the code
(not in examples)

**Comment by Eric89GXL** [comment]
Not that simple unfortunately, just spent half an hour trying to fix `time_gen.py` but it's not trivial. There are API changes from `cross_validation` to `model_selection` in terms of how iteration is done, and when different parameters are passed. So @dengemann or @kingjr (most recent authors in that vicinity) will probably have to take a look. Moving to 0.12.

**Comment by agramfort** [comment]
do you have a WIP PR I could take over during we?

**Comment by Eric89GXL** [comment]
No, I only had one or two good lines and a bunch of not-working junk after that so I `reset --hard`. Your idea was a good start, though. You can run `mne/tests/test_cov.py` and `mne/decoding/tests` to see the warnings.
