### ISSUE TITLE
mne watershed

### ISSUE THREAD

**Issue by ImmanuelSamuel** [mne-tools/mne-python#2692]
Hey guys, Is it possible to get a BEM for a t1 template? I tried to used watershed on mni template and it didn't work. It works on a standard t1.

**Comment by agramfort** [comment]
I am sure their already exist good BEM surfaces for MNI template if it is
what you have in mind

**Comment by dgwakeman** [comment]
you can rip the one out of SPM, I generated that based on the colin 27 scan. it isn't good the scans on most templates don't cover the whole head, and thus don't work well for BEMs. Generally, I just discourage people from using templates for source recon

**Comment by ImmanuelSamuel** [comment]
I see .. Unfortunately I don't have the T1 for my participants. I was thinking of doing something like eLORETA. But then if I can get MNE to work then I can try multiple source recon methods and DICS. How about the 3T 18yo Schwartz ReactN32 that is in freesurfer?

**Comment by dgwakeman** [comment]
I would just use the one from SPM, it is in their code somewhere. The weakness of the shape is unlikely to cause bigger problems than mapping data from one person to another.

**Comment by ImmanuelSamuel** [comment]
@dgwakeman if you have time and since you already extracted the surfaces ... can you point me where to look in SPM and how to integrate with MNE. I following the tutorial and am at the point where I need the .surf files. Currently searching the SPM folder for clues.

**Comment by ImmanuelSamuel** [comment]
OK I think I got it.

**Comment by agramfort** [comment]
please share any insights here in case someone else has the goal

**Comment by ImmanuelSamuel** [comment]
The surf files are in spmX/canonical/. I am testing them now. Freesurfer also has the same BEM data but they are in mat format. Dont know the surf format to convert time. Apparently they have a better estimate of the data by correcting for anti-aliasing.

**Comment by ImmanuelSamuel** [comment]
However they are in .gii format need to convert them to surf. @dgwakeman Any ideas?

**Comment by ImmanuelSamuel** [comment]
mris_convert does not support converting to .surf format.

**Comment by agramfort** [comment]
nibabel can read gii and mne can save .surf files

**Comment by ImmanuelSamuel** [comment]
```mris_convert <SPMfile> <surf file>
