### ISSUE TITLE
BUG: Instability of gamma_map tests

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#2702]
We have had problems in the past with `gamma_map` tests being sensitive to changes in packages (e.g., Anaconda updates) and they cropped up again recently. Specifically there are now two skipped checks in `test_gamma_map.py` that should be fixed at some point.

**Comment by wmvanvliet** [comment]
Travis is failing. Is that related to this?

**Comment by Eric89GXL** [comment]
Yeah, I'm trying to fix it in #2708 but no luck so far.
