### ISSUE TITLE
[BUG?] Write ICA to file: n_samples_ not serializable

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#2715]
With some ICA files, when I use `ica.save(...)`, I get ```TypeError: 59947 is not JSON serializable```
where 59947 is `ica.n_samples_`. I haven't done anything special with the files.

When I do `ica.n_samples_ = int(ica.n_samples_)`, I can save the file. The type of `ica.n_samples_` in these cases is `numpy.int64`.

Is this a bug? Should I make a PR to enforce `n_samples_` always being `int`? Or am I doing something wrong?

**Comment by agramfort** [comment]
the serialization should be more robust. that's the proper fix.

**Comment by dengemann** [comment]
@jona-sassenhagen are you using Python 3? Just out of curiousity. Numpy types are more strictly handled there.

**Comment by jona-sassenhagen** [comment]
You've corrected a lot of my py3 specific syntax in my mne code @dengemann :) yes, always py3. I'll submit a pr once I'm at a computer.

**Comment by dengemann** [comment]
You basically need to convert to python ints. I think ther'es already an example for this in the serialization code, I had fixed this already for other cases.

**Comment by jona-sassenhagen** [comment]
closed for #2716

**Comment by Eric89GXL** [comment]
FYI if you put `Closes #XXX` in your PR, it will auto-close the related issue with GitHub magic so you don't have to manually close.

**Comment by jona-sassenhagen** [comment]
Oh that's nice.
