### ISSUE TITLE
Evoked.get_peak

### ISSUE THREAD

**Issue by jean-didier** [mne-tools/mne-python#2724]
Hi
I think there is a bug in Evoked.get_peak() function, when using ch_type :
In    : ev.get_peak('mag',tmin=tmin,tmax=tmax)
Out : ('MEG0122',0.178999)
ch_idx is related to data[picks] instead of self.data and the function should return 
self.ch_names[picks[ch_idx]] instead of self.ch_names[ch_idx]

**Comment by agramfort** [comment]
see

https://github.com/mne-tools/mne-python/pull/2725

thanks for the bug report.

**Comment by jean-didier** [comment]
I think it's
ch_names = [ch_names[k] for k in picks]
instead of 
ch_names = [ch_names[k] for k in ch_names]
