### ISSUE TITLE
GFP in evoked.plot does not play along with ylim kwarg

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#2742]
The GFP yaxis is set based on the auto limits, but if a user defines y lims themselves with the ylim kwarg, the GFP can float or disappear.

@jaeilepp 

![unknown-60](https://cloud.githubusercontent.com/assets/4321826/11979975/c888834e-a997-11e5-902f-191b94bd5124.png)
![unknown-61](https://cloud.githubusercontent.com/assets/4321826/11979976/ca55d7da-a997-11e5-85ea-8b206b9159e5.png)

**Comment by jasmainak** [comment]
do you have a quick fix?

**Comment by Eric89GXL** [comment]
I think it should be pretty to fix -- check for ylim kwarg and use that as bounds instead of the `get_ylim()` bounds instead, hopefully.

**Comment by jona-sassenhagen** [comment]
Or this code
```
            if ylim is not None and t in ylim:
                if plot_type == 'butterfly':
                    ax.set_ylim(ylim[t])
                elif plot_type == 'image':
                    im.set_clim(ylim[t])
```
in viz evoked lines 350ff could be split up and put in the parts of the code where BF and image plots are dealt with, and the one for BF before the GFP part.
I think.

I can try later, unless Jakko wants to do it on the quick, but I can't promise I'll get to do it before xmas.
