### ISSUE TITLE
CUFFT library 

### ISSUE THREAD

**Issue by kambysese** [mne-tools/mne-python#2744]
I am running current dev master on OS X 10.11.2 with CUDA toolkit 7.5, pycuda, and scikits-cuda, `mne.cuda.init_cuda()` returns `OSError: cufft library not found`. Never encountered this one, and it appears that the CUDA toolkit installation should've included this lib. Any seasoned MACOS users have any ideas how to solve this?

**Comment by Eric89GXL** [comment]
Is that on init of `scikits.cuda`? If so, you could try pinging them, too. Please tag me if you do because I'd like to follow.

**Comment by kambysese** [comment]
I don't see any mention of "cufft" in the file `scikits.cuda.__init__.py` Is that what you meant?

**Comment by Eric89GXL** [comment]
Nah, I meant where are you getting the error in mne-python? It's possible we're catching it and the traceback isn't so useful, in which case we should improve the error message to say which library import fails (e.g., a `from scikits.cuda import fft` call or something).

Can you try this on your system and see if you get that error?
```
from skcuda import fft
```
or if you're running and older version,
```
from scikits.cuda import fft
```
If it is indeed a problem with scikits-cuda as I suspect, you will probably need to ask [over there] (https://github.com/lebedov/scikit-cuda).

**Comment by Eric89GXL** [comment]
Closing as an issue with other lib. Did this ever end up working?

**Comment by kambysese** [comment]
Nope.
