### ISSUE TITLE
Make `pics` mandatory for mne.viz.plot_epochs_image

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#2750]
`mne.viz.plot_epochs_image` plots all channels if `picks=None`. `None` is the default. So if you're stupid like me and naively call this function, you may get 256 figures cluttering up your screen. @jasmainak suggested it may be worth considering making `picks` a mandatory argument.

**Comment by agramfort** [comment]
or show just the first 5 or something.

I like default parameters.

**Comment by jona-sassenhagen** [comment]
Sounds good to me. So if `picks=None`, plot `inst.ch_names[:5]`? I don't assume this breaks anything.

**Comment by agramfort** [comment]
yes something like this.

**Comment by jona-sassenhagen** [comment]
Closed by  #2751
