### ISSUE TITLE
ENH: Drop old numpy, Python support

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#2759]
It looks like the scipy folks are moving toward dropping Python 2.6, 3.2, 3.3 and Numpy < 1.7.1 support. I vote we do the same. Thoughts?

**Comment by agramfort** [comment]
@dengemann would it create a problem at neurospin?

@yarikoptic what would be the consequence on debian packaging?

**Comment by dengemann** [comment]
Not sure, honestly. I can check next week. What is with jenkins at inria? Is it still on python 2.6?

**Comment by agramfort** [comment]
yes. It's running an old ubuntu stable.

**Comment by yarikoptic** [comment]
I just will not provide recent mne for those older releases of Debian and Ubuntu

**Comment by Eric89GXL** [comment]
Looks like Ubuntu 14.04 and Debian stable (Jessie) are on 1.8.x, and 12.04 and oldstable (Wheezy) are on 1.6.x.

**Comment by jona-sassenhagen** [comment]
At least Mac OSX El Capitan has Python 2.7 now.

**Comment by agramfort** [comment]
ok thanks

@Eric89GXL I would say that next time we need to backport something we'll drop the support. Presently it works so let's keep it like this.

**Comment by Eric89GXL** [comment]
Sounds good to me, I'll close for now then
