### ISSUE TITLE
cHPI positions

### ISSUE THREAD

**Issue by kambysese** [mne-tools/mne-python#2766]
`get_chpi_positions` generated RunTime error in line 78 of chpi.py on several of my datasets, as well as:

`raw = mne.io.Raw(mne.datasets.sample.data_path() + '/MEG/sample/sample_audvis_raw.fif')`
`trans, rot, t = mne.get_chpi_positions(raw)`

Can't figure out what is happening here; pre-loading doesn't help and I can't seem to explicitly find "chpi" channels in the dataset info with `show_fiff` or `raw.info['ch_names']`.

**Comment by Eric89GXL** [comment]
That function can only extract positions from files that have already been
processed by MaxFilter with movement compensation on, because it stores the
computed positions in the FIF file
