### ISSUE TITLE
a little typo in event.py Line:521

### ISSUE THREAD

**Issue by zuxfoucault** [mne-tools/mne-python#2780]
report typo

<code>        
For output =
'onset' or 'step', the second column contains the value of the stim
channel immediately before "the the" event/step. 
</code>

**Comment by agramfort** [comment]
you can fix this your self by editing the file on github

https://github.com/mne-tools/mne-python/edit/master/mne/event.py

can you give it a try?

**Comment by zuxfoucault** [comment]
My pleasure! PR has been sent!
