### ISSUE TITLE
Python bug when use of gat.predict

### ISSUE THREAD

**Issue by romquentin** [mne-tools/mne-python#2789]
Hello, 
I am using the function gat.predict for decoding analyses with MEG data. When I run the function with n_jobs=-1, my python crashes. But it works with n_jobs=1. Attached the screenshot of the bug and the problem details. I am running under OS X El Capitan (10.11.2) and python 2.7. Thanks for your help! 

[error python details.txt](https://github.com/mne-tools/mne-python/files/91022/error.python.details.txt)

<img width="1209" alt="screen shot 2016-01-14 at 4 08 03 pm" src="https://cloud.githubusercontent.com/assets/16289774/12337705/84fd5160-bad9-11e5-8f47-682320a9a20c.png">

**Comment by kingjr** [comment]
@dengeman, @alexgramfort

I tried to debug it with him, but it seems to come from the parallel.
There's no python error thrown. Not sure what to do from there...

**Comment by dengemann** [comment]
I think this is a problem with joblib and numpy. What kind of numpy setup
do you have? And JR, what was your impression, After our vectorization to
me any benefit of parallel processing was lost. Not even when running
n_jobs = number of physical cores. I have Anaconda with MKL optimization,
and this makes sense, our new code will trigger more intelligent
multiprocessing at a lower level. Maybe we need to poll a bit for whom it
actually works / and for whom it brings any benefit.

**Comment by agramfort** [comment]
use anaconda with mkl on mac os. Ask for the academic license

it's related to a bug in the apple accelerate framework.

**Comment by kingjr** [comment]
> I think this is a problem with joblib and numpy. What kind of numpy setup do you have? And JR, what was your impression, After our vectorization to me any benefit of parallel processing was lost. Not even when running n_jobs = number of physical cores. I have Anaconda with MKL optimization, and this makes sense, our new code will trigger more intelligent multiprocessing at a lower level. Maybe we need to poll a bit for whom it actually works / and for whom it brings any benefit.

I haven't checked, I generally don't use MKL as I had not installed it on my aws image... Is it worth it IYO?

In any case we'll need to keep joblib 1) for those who don't have it 2) for `window_size > 1` as we don't vectorize then.

@romquentin Let us know how it goes with anaconda & mkl.

**Comment by romquentin** [comment]
Thanks. It works with anaconda & mkl ! The numpy version was 1.10.1 and
turn to 1.10.2 when I installed mkl.

2016-01-15 9:11 GMT-05:00 Jean-Rémi KING <notifications@github.com>:

**Comment by kingjr** [comment]
Great, you may close the issue.
