### ISSUE TITLE
BUG: linear_regression_raw

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#2790]
@jona-sassenhagen when decimating, some events may become duplicated and generate an offset error. Would be great to add a warning after the decimation.

**Comment by jona-sassenhagen** [comment]
Yup, that should never happen. I think a warning isn't enough - we should instead fix the problem within the function and eliminate fake doubles.

**Comment by jona-sassenhagen** [comment]
Well, or warn that n events will be dropped because the decimation is too strong for events that are this tightly spaced.

**Comment by kingjr** [comment]
> Well, or warn that n events will be dropped because the decimation is too strong for events that are this tightly spaced.

+1

**Comment by jona-sassenhagen** [comment]
Close for #2791 @kingjr ?

**Comment by kingjr** [comment]
yes thanks
