### ISSUE TITLE
local path in HTML?

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#2799]
@Eric89GXL 

Is [this](http://martinos.org/mne/dev/manual/c_reference.html#mne-redo-file) intended?

```
mne_redo_file

Usage: /home/larsoner/custombuilds/mne/current/bin/mne_redo_file file-to-redo
mne_redo_file_nocwd

Usage: /home/larsoner/custombuilds/mne/current/bin/mne_redo_file_nocwd file-to-redo
```

**Comment by dengemann** [comment]
We had this before, I think there was some sphinx option to avoid this.

**Comment by Eric89GXL** [comment]
Hah! No that's not intended. I don't remember fixing it previously, but it would be great if we could find it. Perhaps @agramfort remembers more

**Comment by agramfort** [comment]
I have no idea... :( :(

**Comment by Eric89GXL** [comment]
I had actually put in the full path at some point. Fixed here:

https://github.com/mne-tools/mne-python/commit/47cc50a80ae6c6920d9a216678bc137587e09f36

**Comment by kingjr** [comment]
It's still online though (dev + stable). But I'm not sure when / how the docs are compiled, so my comment may not be appropriate.

**Comment by agramfort** [comment]
@jaeilepp any chance you can update the dev doc?
