### ISSUE TITLE
HTML Typo?

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#2800]
@agramfort, maybe I'm missing something, but I think [this](http://martinos.org/mne/stable/manual/source_localization/forward.html) is not correct?

```
The coil types fall in two general categories:
    Axial gradiometers and planar gradiometers and
    Planar gradiometers.
```

Shouldn't it be axial grads and magnetometers?

(also, there's a space missing after the next dot)

**Comment by dengemann** [comment]
Yep, the second bullet point should be magnetometers.

**Comment by agramfort** [comment]
+1
