### ISSUE TITLE
mne.epochs.equalize_epoch_counts do not return self

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2801]
This works in-place, which is fine but it should also return `self`.

**Comment by teonlamont** [comment]
sorry, typo in title, corrected above

**Comment by jasmainak** [comment]
I think it does return `self` if `copy=False`. You have `epochs` pointing to `self`

**Comment by dengemann** [comment]
Let's always return self. My vote.

**Comment by Eric89GXL** [comment]
+1 for that it's what we do most places and it's really convenient

**Comment by jasmainak** [comment]
Fix welcome for both `equalize_epochs_counts` and `equalize_events_counts`

**Comment by kaichogami** [comment]
I would like to work on this issue, if no one else is on it.

**Comment by teonlamont** [comment]
I think that this has already been resolved
