### ISSUE TITLE
Tutorials should be cross-referenced in the examples

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-python#2803]
Tutorials are also examples with more explanation. It would be great if they also filled the gallery for ease of searching in one common space.

**Comment by Eric89GXL** [comment]
Thinking about how `sphinx-gallery` works, I have a feeling that this will be more work than it's worth. But if we want to do it, we should implement it there. I'll close this for now, and if there is interest in doing it, I'd say open a `sphinx-gallery` issue and get feedback there.
