### ISSUE TITLE
BUG: pick_types with KIT

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#2805]
In `pick_type()` when there's a bad channel:

```
from mne.channels import find_layout
from mne.io import read_raw_kit
fname = 'mne-python/mne/io/kit/tests/data/test.sqd'
raw = read_raw_kit(fname, preload=True)
print('raw', find_layout(raw.info))
raw.pick_types(meg=True)
print('raw pick_type', find_layout(raw.info))
raw.info['bads'] += ['MEG 002']
print('raw bad', find_layout(raw.info))
raw.pick_types(meg=True)
print('raw bad pick_type', find_layout(raw.info))
```

gives:

```
('raw', <Layout | KIT-157 - Channels: MEG 001, MEG 002, MEG 003 ...>)
('raw pick_type', <Layout | KIT-157 - Channels: MEG 001, MEG 002, MEG 003 ...>)
('raw bad', <Layout | KIT-157 - Channels: MEG 001, MEG 002, MEG 003 ...>)
('raw bad pick_type', None)
```

This makes the whole plotting function incompatible once a sensor is rejected.

@Eric89GXL @teonlamont

**Comment by teonlamont** [comment]
Yeah, I came across this problem too...temp workaround is to interpolate bad channels then the layout will work. The problem I had when working on a patch is dealing with the sparse matrix operations like removing a channel are not easy

**Comment by agramfort** [comment]
the find_layout function should be robust to a small fraction of bad channels

**Comment by kingjr** [comment]
I didn't to fix it. @teonlamont are you up for it?

**Comment by teonlamont** [comment]
@kingjr unfortunately I can't. I'm swamped :( can't really make contributions (just more issues) until after D-Day :sweat_smile:

**Comment by jaeilepp** [comment]
I could make a simple fix. You'll have to see what you think about it...

**Comment by jaeilepp** [comment]
Fixed.
