### ISSUE TITLE
can't set attribute epochs.tmin

### ISSUE THREAD

**Issue by cmoutard** [mne-tools/mne-python#2806]
After having pulled the last master branch, I cannot read anymore my epochs :

```python
from mne import read_epochs

read_epochs('ac150022/150122/e_sss_SHInEa_ac150022_P1R1_1-30.fif')
```
and then got:

![capture du 2016-01-21 13 40 43](https://cloud.githubusercontent.com/assets/7878675/12480726/c3b16b4c-c044-11e5-8f87-96410f5d5c05.png)

**Comment by cmoutard** [comment]
Solved (wrong version of mne)

**Comment by jaeilepp** [comment]
Are you sure this is using the latest master? I can't find this in my code...

**Comment by Eric89GXL** [comment]
Indeed it's not in `master`:

https://github.com/mne-tools/mne-python/blob/master/mne/epochs.py#L410

**Comment by cmoutard** [comment]
My bad, sorry
