### ISSUE TITLE
meas_date consistency + filenames as a list to Raw constructor

### ISSUE THREAD

**Issue by jaeilepp** [mne-tools/mne-python#2808]
I'll open an issue instead of clogging https://github.com/mne-tools/mne-python/pull/2783

1) I noticed that most of the readers populate the ``info['meas_date']`` with an int instead of a list of ints as it is documented in http://mne-tools.github.io/stable/generated/mne.io.Info.html#mne.io.Info

2) If you pass a list of filenames to Raw constructor it concatenates the data together, but is using different methods to ``mne.io.concatenate_raws``. This means that I have to implement annotation combining in two places. Is there a reason for having these in two places or is this an opportunity for refactoring?

**Comment by Eric89GXL** [comment]
> 1) I noticed that most of the readers populate the info['meas_date'] with an int instead of a list of ints

Sure, we can turn it into a list with the second element 0 in that case.

> 2) If you pass a list of filenames to Raw constructor it concatenates the data together, but is using different methods to mne.io.concatenate_raws. This means that I have to implement annotation combining in two places. Is there a reason for having these in two places or is this an opportunity for refactoring?

I suspect there was a reason for it, but I don't remember unfortunately. You could try refactoring it and see if you run into some test that breaks.
