### ISSUE TITLE
ENH: report should have a delete method for particular captioned entry/section

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-python#2811]
There should be a way to modify the report, specifically delete an image or section after being added. Method could take two args: `section`, `caption` where `section` deletes the whole section, and `selection` and `caption` both specified delete a particular entry.

**Comment by jasmainak** [comment]
+1 from my end. It will have to work on saved reports too

**Comment by kingjr** [comment]
+1

**Comment by teonbrooks** [comment]
@jasmainak maybe you'll like to add this in your free time ;) i'm closing my outstanding issues and what better way to do it than delegation 🙃

**Comment by jasmainak** [comment]
lol thanks, now I'll just have to find a moment when I'm bored ...

**Comment by jasmainak** [comment]
I think this can be closed as it's addressed by #5531
