### ISSUE TITLE
add_proj should also take Proj object. pick_channels too

### ISSUE THREAD

**Issue by teonlamont** [mne-tools/mne-python#2813]
currently the `add_proj` only takes list of projections, it should also take the individual projection by just checking the type for Projection or list.

**Comment by teonlamont** [comment]
`pick_channels` should take an individual str in additional to list

**Comment by agramfort** [comment]
why ? can't you just put [] ???

**Comment by teonlamont** [comment]
I didn't know if there was a reason behind not taking the object and requiring a list. making a list is fine, just thought this was an oversight
