### ISSUE TITLE
add IO support of .cnt file from Neuroscan

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#2815]

**Comment by jaeilepp** [comment]
I can take this. I found a ``TEST.CNT`` from the internet, but if anyone has more data in cnt, it would definitely help. I think there are some different formats of cnt data.

**Comment by jasmainak** [comment]
Here is 4GB of neuroscan data: http://sccn.ucsd.edu/~arno/fam2data/publicly_available_EEG_data.html ;)

**Comment by massich** [comment]
@jaeilepp All links I find to this `test.cnt` are down. Do you have a backup of it?


cross reference #5493, #6025, #3911
