### ISSUE TITLE
FIX: report too many sections hides page

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#2816]
@mainakjas @dengemann 

When there's a too many section button for one line, the button start to hide the top of the page.

here's an extreme example

![report](https://cloud.githubusercontent.com/assets/4881164/12525459/68cd2060-c132-11e5-942f-9dcc47bad26b.png)

**Comment by jasmainak** [comment]
I suspect this line needs to be fixed: https://github.com/mne-tools/mne-python/blob/master/mne/report.py#L533. Basically change it to percentage. @kingjr do you want to give it a try? You can reproduce the problem better than me.

**Comment by kingjr** [comment]
ok

**Comment by kingjr** [comment]
... actually no; I don't know. The margin should change according to the number of line used;

**Comment by jasmainak** [comment]
can you give me a gist to reproduce? I'll fix it then.

**Comment by jasmainak** [comment]
By the way, do you notice the `>` on the top left? You can use it to hide the section buttons. I think it was meant to fix this exact issue. That doesn't do it for you?

**Comment by kingjr** [comment]
> By the way, do you notice the > on the top left? You can use it to hide the section buttons. I think it was meant to fix this exact issue. That doesn't do it for you?


Aaah! nice. It's good enough, I'll close it :)
