### ISSUE TITLE
Is there a list of mne config options?

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#2817]
`mne.set_config()` or `get_config` doesn't tell you what the possible keys are. I know you can set CUDA there and some file dirs, but is there an overview somewhere?

**Comment by Eric89GXL** [comment]
It's buried in the code somewhere. But we should make set_config with no
args print all options and get_config print all current options that are
actually set. I can do it Monday unless you want to.

**Comment by dengemann** [comment]
+1

**Comment by jona-sassenhagen** [comment]
@Eric89GXL it's not pressing, but if you can find the time to do it, that'd be nice.

**Comment by jaeilepp** [comment]
It's actually a constant list in ``mne.utils``.
``mne.utils.known_config_types``
