### ISSUE TITLE
ENH: support new version of cross validation objects in GAT

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#2820]
See https://github.com/mne-tools/mne-python/pull/2739

I'm a bit busy right now, but I'm opening up the issue to remind myself of doing it..

**Comment by Eric89GXL** [comment]
Also see original issue #2687

**Comment by kingjr** [comment]
TODO: 
* incorporate `cv.split()` to allow passing non initialized `cv ` objects @laurawilliams
* Use KFold by default (or if y is continuous ?) to prevent bug with regressions @teonlamont

**Comment by kingjr** [comment]
closed by https://github.com/mne-tools/mne-python/pull/2856
