### ISSUE TITLE
maxwell_filter does not remove MEG projectors

### ISSUE THREAD

**Issue by mdclarke** [mne-tools/mne-python#2827]
Hi
The mne.preprocessing.maxwell_filter function does not remove the initial Acquisition MEG projectors from the data like the Elekta MaxFilter does. Could this be implemented?

Thanks,
Maggie

**Comment by Eric89GXL** [comment]
Yeah, we should get rid of the MEG projectors in `info` when applying `maxwell_filter`. I can take care of it this week.
