### ISSUE TITLE
BUG: deprecation bug

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#2835]
https://github.com/mne-tools/mne-python/blob/master/mne/time_frequency/multitaper.py#L556

this calls the private function with verbose, but it doesn't take that parameter.

**Comment by jasmainak** [comment]
So, we should just remove the decorator?

**Comment by Eric89GXL** [comment]
leave the decorator on and just don't pass it to the underlying function and it should all work properly (there's no need to pass it)

**Comment by Eric89GXL** [comment]
Fixed in https://github.com/mne-tools/mne-python/commit/cd4feaffb811640a1ba730972d8255587546cae5
