### ISSUE TITLE
DOC: connectivity module

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#2847]
Public mental note:
- better document the input data API, e.g. how tuples of (array, stc) are combined and what this does to the indices parameter
- document the output API, depending on the method the need to be reshaped. 

For later: write high-level object.

**Comment by Eric89GXL** [comment]
Moved to 0.13, feel free to close if you get it done before 0.12 comes out

**Comment by Eric89GXL** [comment]
Removing milestone label

**Comment by AdoNunes** [comment]
@dengemann Is this still necessary to fix?

**Comment by dengemann** [comment]
yes I think nothing has changed.

**Comment by agramfort** [comment]
can you clarify what is needed? assuming you want someone else to do the
job ;)

>

**Comment by dengemann** [comment]
You should do a for loop over parameters for the connectivity function and see if you understand what it takes to reassemble a proper square matrix. This is what needs to be documented.

**Comment by mmagnuski** [comment]
I think this can be closed with connectivity being moving to `mne-connectivity`.
