### ISSUE TITLE
Value error no EOG key in rejection dict  

### ISSUE THREAD

**Issue by kambysese** [mne-tools/mne-python#2858]
`epochs._reject_setup` returns a ValueError because the `eog` value in the `idx` [dict](https://github.com/mne-tools/mne-python/blob/master/mne/epochs.py#L465) returns an empty list for Vectorview MEEG dataset with 60 EEG channels and EOG61 & EOG62. Debugger shows `idx` contains 60, 102, and 204 elements for `eeg`, `mag`, and `grad` keys. The EOG channels don't appear anywhere in `idx`.

Here is the trace:
 

>  File "/home/ktavabi/Projects/mne-python/mne/utils.py", line 551, in verbose
>     return function(*args, **kwargs)
>   File "/home/ktavabi/Projects/mne-python/mne/epochs.py", line 1863, in __init__
>     on_missing=on_missing, preload_at_end=preload, verbose=verbose)
>   File "/home/ktavabi/Projects/mne-python/mne/epochs.py", line 299, in __init__
>     self._reject_setup(reject, flat)
>   File "/home/ktavabi/Projects/mne-python/mne/epochs.py", line 471, in _reject_setup
>     "%s." % (key.upper(), key.upper()))
> ValueError: No EOG channel found. Cannot reject based on EOG.

**Comment by jasmainak** [comment]
you forgot to post the trace

**Comment by kambysese** [comment]
Sorry @jasmainak I am editing. Unsure if `epochs` likes the particular rejection dict I am using.

**Comment by jasmainak** [comment]
is it possible that you have to set the channel type of your EOG channels? You can use `raw.set_channel_type`

**Comment by kambysese** [comment]
It's possible, I've not had to do this before but I also don't recall every using the `eog` arg in rejection dicts, and for some reason `eog=np.inf` is making something unhappy. @Eric89GXL have you ever had to use `set_channel_types` for MEEG data collected at ILABS?

**Comment by jasmainak** [comment]
If you don't want to reject based on EOG, just don't add it in the reject dict. If `eog=np.inf` throws an error, it might need fixing though.

**Comment by Eric89GXL** [comment]
@kambysese you should not need to use `set_channel_types` unless something went wrong during acquisition. Can you upload the file somewhere on UW servers for me to have a look?

@jasmainak I think right now if the key is in the dict we will throw an error even if it is `np.inf`. I suppose we could change it so that it'll only error if the key is there and finite.
