### ISSUE TITLE
ENH/IO?: ICAArray

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#2866]
Sometimes it is important to to read ICA solutions from different packages. To simplify this we probably need some new abstraction. I still have to think about it but the idea would be to write an ICAArray class or a function that simplifies this tasks by accepting unmixing matrices, preprocessing weights, etc. scalings etc. and whatever and returns a ready-to-use ICA object.

cc @jasmainak @jona-sassenhagen @jmontoyam

**Comment by dengemann** [comment]
cc @agramfort

**Comment by jasmainak** [comment]
the two AA in ICAArray hurt my eyes :)

**Comment by dengemann** [comment]
> the two AA in ICAArray hurt my eyes :)

I thought the same.

**Comment by jona-sassenhagen** [comment]
Also, maybe we want to keep it open to other forms of decomposition/BSS..?

**Comment by dengemann** [comment]
> Also, maybe we want to keep it open to other forms of decomposition/BSS..?

yes good idea as long as we can assume a common API.

Maybe `DecompositionArray`?

**Comment by jona-sassenhagen** [comment]
`SpatialFilterArray`?

Although that in principle should include e.g. CSP.

**Comment by dengemann** [comment]
Maybe simply `SpatialFitler` or `Decomposition` as we don't store data here. CSP is a bit different thought, it is, so to say, a cross-decomposition.

**Comment by agramfort** [comment]
Why is the current ICA object not enough?

**Comment by dengemann** [comment]
> Why is the current ICA object not enough?

it might be enough, but maybe we could have a constructor function that takes the essential data and sets all the required attributes. Imagine you reade an ICA that does not use PCA etc. so you will be happy if the function sets for you the pca attributes to identity. Another potential issue might be related to the ordering of channels, etc. Can you feel where this is going?

**Comment by jona-sassenhagen** [comment]
I see it like Denis - it would be useful to have a constructor that can create proper Ica objects from arbitrary (un)mixing matrices. 






On Wed, Feb 10, 2016 at 1:26 AM -0800, "Denis A. Engemann" <notifications@github.com> wrote:













Why is the current ICA object not enough?




it might be enough, but maybe we could have a constructor function that takes the essential data and sets all the required attributes. Imagine you reade an ICA that does not use PCA etc. so you will be happy if the function sets for you the pca attributes to identity. Another potential issue might be related to the ordering of channels, etc. Can you feel where this is going?

**Comment by agramfort** [comment]
let's see if we can make it work sticking to a single ICA object.

**Comment by dengemann** [comment]
I think it will work, but we need a function.

**Comment by dengemann** [comment]
`assemble_ica`

`construct_ica`

....

**Comment by agramfort** [comment]
draft something. We'll argue about the name after :)

**Comment by dengemann** [comment]
Yeah will draft something based on a current problem I want to solve.

**Comment by jona-sassenhagen** [comment]
This one still on the menu?

**Comment by dengemann** [comment]
Not that easy, dev time is rather high if you want to get it right. Foreign ICAs can be very different ...

**Comment by Eric89GXL** [comment]
Given the technical difficulties, should we close?

**Comment by dengemann** [comment]
Yes for now.
