### ISSUE TITLE
DeprecationWarning in pandas after importing mne

### ISSUE THREAD

**Issue by cle1109** [mne-tools/mne-python#2870]
Whenever I

    import mne
    import pandas as pd

I get the following warning:

```
/Users/test/anaconda/lib/python3.5/site-packages/pandas/__init__.py:7: DeprecationWarning: bad escape \s
  from pandas import hashtable, tslib, lib
```

Importing `pandas` in a clean session works. This is a fresh Anaconda install where I added MNE via `pip install mne`.

**Comment by dengemann** [comment]
not an MNE issue ... maybe different pandas versions on your system?

**Comment by cle1109** [comment]
I just installed a fresh Anaconda on a different Windows machine and I get the same warning. I only see this message if I first import `mne`. So MNE is at least part of the problem.

**Comment by agramfort** [comment]
mne is maybe affecting a global setting on warnings ...

is this recent on mne master?

**Comment by Eric89GXL** [comment]
Oh right. Yes we do:

https://github.com/mne-tools/mne-python/blob/master/mne/utils.py#L463

**Comment by Eric89GXL** [comment]
(and we've had that line for a *long* time, so it's more likely that Pandas has some recent change that now elicits a DeprecationWarning than it is that we changed something)

**Comment by cle1109** [comment]
So - is changing the warning state necessary? And I don't quite understand the warning anyway, what's wrong with the Pandas code? Should they change anything?

**Comment by Eric89GXL** [comment]
It's necessary if we want users to see Deprecation messages, which are pretty useful. So I think we should keep it. The warning is probably due to some change in Pandas code, but they might not see they are using some deprecated behavior because they don't have them enabled by default.

**Comment by Eric89GXL** [comment]
...but before bothering them about it, you might want to verify that replacing `import mne` with some suitable `warnings` call before the `import pandas` does indeed elicit the same warning.

**Comment by cle1109** [comment]
Yes. The following minimal example triggers the warning:

    import warnings
    warnings.simplefilter("default")
    import pandas as pd

I'll let the Pandas devs know.

However, I'm still not convinced that changing the warnings filter is a good idea. As we saw, it might trigger a whole lot of warnings in other packages. Since DeprecationWarnings are ignored by default, there must be a way to show these to the user other than changing the global warnings filter (I think scikit-learn is showing DeprecationWarnings to users, but without changing the global warnings state).

**Comment by Eric89GXL** [comment]
Indeed:

```
warnings.filterwarnings('always', category=DeprecationWarning,
                        module='^{0}\.'.format(re.escape(__name__)))
```
I'll open a PR
