### ISSUE TITLE
Plot the sensor array or layout of MEG/EEG data

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-python#2871]
It would be super useful if there were a simple viz plotting function for showing the sensor array. It would just be the layout plot that we currently have but it would be without data and labels for the different sensors

**Comment by Eric89GXL** [comment]
I wonder if we can integrate this with the existing function somehow. Maybe add a `title_color=None` kwarg that you could set to e.g. `'w'` that would overlay the channel name above the plotting axis like a small title. Then to get what you want, you could just set the channel colors to zero for an `evoked` file, but we also get some nicer functionality when there is data present. WDYT?

**Comment by jona-sassenhagen** [comment]
This is one of the functions I'm constantly patching together on the fly myself. The necessary components are in the MNE code, but there should be a convenience function.

**Comment by jasmainak** [comment]
yeah, we should have this function.

**Comment by agramfort** [comment]
inst.plot_sensors_3d ?

**Comment by jona-sassenhagen** [comment]
Intuitively, I'd like to see only one function (plot_layout? plot_montage?) with a keyword to set 2d vs 3d.

**Comment by agramfort** [comment]
good idea

**Comment by jasmainak** [comment]
yes, +1 :)

**Comment by dengemann** [comment]
I had something like this somewhere ...

**Comment by dengemann** [comment]
Well anyways it's simple a few lines of matplotlib. My +1 too.
