### ISSUE TITLE
Adding an option to plot norm values of the grads in plot_evoked_topo?

### ISSUE THREAD

**Issue by mmittag** [mne-tools/mne-python#2884]
Hi,
It would be great if an option to plot norm values of combined gradiometer pairs (sqrt of (grad12 + grad22)) could be added in plot_evoked_topo. Brain storm does that automatically in its gui (http://neuroimage.usc.edu/brainstorm/Tutorials/TutMindNeuromag) and various groups seem to publish such timecourses of the combined grads.
Much thanks for your help!
Maria

**Comment by agramfort** [comment]
can you point to the figure you are referring to?

**Comment by mmittag** [comment]
Hi, sorry for the confusion. I did not refer to a figure on the link I provided. The link shows implementation of grad norms with Brainstorm, not the figure I wish to create. I wish to create a figure similar to the one attached, with the difference that norm values of combined gradiometers are illustrated. Plot_evoked_topomap already does a similar norm (RMS feature) by adding `ch_type='grad'`, but I cannot find such element for plot_evoked_topo. thanks!

![sphx_glr_plot_topography_001](https://cloud.githubusercontent.com/assets/8051992/13062181/74f5c140-d3f1-11e5-8503-a6ac117d7fd2.png)

**Comment by agramfort** [comment]
ok that seems like a legitimate use case and an easy PR.

for a new contributor?

**Comment by mmittag** [comment]
That's great. This implementation will be very useful, thank you. It would be an honorable task to contribute, but I have to pass on this one since I'm not that familiar with creating new codes for mne-python.

**Comment by dengemann** [comment]
Maybe something for @cjayb ;) all the ingredients needed can be found in plot_topomap which already does the norm remapping once grads are encountered.

**Comment by cjayb** [comment]
@dengemann hehe, I'll take a crack at it :)

**Comment by mmittag** [comment]
thank you! @cjayb

**Comment by cjayb** [comment]
ugh, just took a closer look: not trivial, have to think about layout & possible delayed SSP. Have little time until next week, won't take it personally if someone else solves this in the mean time ;) Certainly a nice to have feature, this.

**Comment by cjayb** [comment]
see #2898, help needed
