### ISSUE TITLE
Writing error

### ISSUE THREAD

**Issue by kambysese** [mne-tools/mne-python#2900]
@Eric89GXL did you happen to check #2869 against the data segment I provided. After merging the fix worked for the missing channels during `maxwell_filter` but the writing process generates following trace for the trouble file as well as other...
 
> File "/home/ktavabi/Projects/mne-python/mne/utils.py", line 596, in verbose
> return function(args, *kwargs)
> File "/home/ktavabi/Projects/mne-python/mne/io/base.py", line 1284, in save
> drop_small_buffer, split_size, 0, None)
> File "/home/ktavabi/Projects/mne-python/mne/io/base.py", line 1942, in _write_raw
> reset_range)
> File "/home/ktavabi/Projects/mne-python/mne/io/base.py", line 2085, in _start_writing_raw
> write_meas_info(fid, info, data_type=data_type, reset_range=reset_range)
> File "/home/ktavabi/Projects/mne-python/mne/io/meas_info.py", line 1248, in write_meas_info
> write_ch_info(fid, c)
> File "/home/ktavabi/Projects/mne-python/mne/io/write.py", line 325, in write_ch_info
> fid.write(np.array(ch['loc'], dtype='>f4').tostring()) # writing 12 values
> KeyError: 'loc'

**Comment by Eric89GXL** [comment]
Fixed by #2902
