### ISSUE TITLE
block parameter in epoch_plot doesn't work as intended

### ISSUE THREAD

**Issue by ualsbombe** [mne-tools/mne-python#2909]
Dear Developers

The block argument in plot_epochs doesn't work as intended. It keeps evaluating the code, and thus, in this particular code (see below), the saved output is the same as the input. I am using mne version 0.11.0 and running from Spyder in an Anaconda-environment.

Best

Lau

```#==============================================================================
# MANUALLY CLEAN EPOCHS
#==============================================================================
epochses = []

for i in range(len(positions)):
    input_file = './3_epochs/' + positions[i] + '_eog_auto_cleaned-epo.fif'
    epochs = mne.read_epochs(input_file)
    mne.epochs.plot_epochs(epochs, picks=[0], block=True) ## only MISC010
    epochses.append(epochs)
    output_file = './4_cleaned_epochs/' + positions[i] + \
                '_manually_cleaned-epo.fif'
    epochs.save(output_file) ```

**Comment by jaeilepp** [comment]
This seems to work for me. What is the issue actually? How do you expect the saved epoch to differ?

**Comment by agramfort** [comment]
I suspect its a matter of marking bad epochs visually

I suspect a spyder issue

**Comment by ualsbombe** [comment]
Sorry, that wasn't explicit. I want to be able to mark bad epochs and drop them before it saves it (agramfort's suspicion is thus right)

**Comment by jaeilepp** [comment]
I tried running it in spyder, but I still can't reproduce the problem. Could you try turning interactive mode on by
```
import matplotlib.pyplot as plt
plt.ion()
```
and see if it works for you. It works with both modes for me though.

**Comment by ualsbombe** [comment]
Tried both plt.ion() and plt.ioff(). I still get the same kind of behaviour. I'm running it in ipython, which seems to be making the difference. When running it from a normal python console, it works as intended, I just realized.

**Comment by jasmainak** [comment]
can you tell us what is the version of matplotlib you are using?

```py
import matplotlib
matplotlib.__version__
```

**Comment by ualsbombe** [comment]
It's 1.5.1

**Comment by ualsbombe** [comment]
All relevant versions:
Anaconda: 2.5.0
Python: 2.7.11
IPython: 4.0.3
Spyder: 2.3.8
mne: 0.11.0
matplotlib: 1.5.1

**Comment by agramfort** [comment]
it's a config thing in spyder.

it's unrelated with mne

**Comment by ualsbombe** [comment]
Ok, that's comforting. Do you where exatcly in the config?

**Comment by agramfort** [comment]
sorry I don't use spyder

**Comment by Eric89GXL** [comment]
It might be worth asking over on the Spyder repo issues to see what they say. FWIW I use Spyder but always use Python interpreters instead of IPython ones, and ioff / block is respected there.

**Comment by ualsbombe** [comment]
Ok, will do that!
Thanks!
