### ISSUE TITLE
FIX: warning_once for raw edf with interpolated chans

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#2922]
@Eric89GXL https://github.com/mne-tools/mne-python/commit/e0cec488bd67451ccfa8c14d9267353472f109ef introduces a warning, which can be overwhelming
![warnings](https://cloud.githubusercontent.com/assets/4881164/13222164/b3a72b44-d94c-11e5-8084-72438c391c19.png)

I guess we'd need a warning_once in this case.

I actually don't understand what going on, nor why this interpolation is needed.

**Comment by Eric89GXL** [comment]
The warning should be emitted elsewhere in the code (outside of whatever looping is being done). Do you have time to look into it?

**Comment by kingjr** [comment]
> The warning should be emitted elsewhere in the code (outside of whatever looping is being done). 

What do you mean?

**Comment by Eric89GXL** [comment]
The warning is emitted somewhere inside a loop, as evidenced by how many times it gets printed. It should instead only be emitted once, preferably when the file is initially read from disk with `read_raw_edf`, at a level *outside* the loop that it's currently in.
