### ISSUE TITLE
BUG: _time_mask does not work properly for non-uniformly spaced inputs

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#2928]
See:
```Python
>>> from mne import _time_mask
>>> import numpy as np
>>> _time_mask(np.array([0.4]), tmin=1., sfreq=1000.)
array([ True], dtype=bool)
>>> _time_mask(np.array([0.4, 1]), tmin=1., sfreq=1000.)
array([False,  True], dtype=bool)
>>> _time_mask(np.array([0.4, 1]), tmin=0.5, sfreq=1000.)
array([ True,  True], dtype=bool)
```
@jaeilepp I think you wrote the `deltas.min()` stuff that causes this, can you fix it?

**Comment by Eric89GXL** [comment]
(in case it's not clear, the first and third cases are bugs, but the middle one is fine)

**Comment by jaeilepp** [comment]
I'm not sure why the third case is a bug. I thought we wanted the ``_time_mask`` to be inclusive i.e. 0.5 is closer to 0.4 than 1. Unless you mean that the 'closeness' should be defined with sfreq taken into account.
