### ISSUE TITLE
ENH: speed up ICA application and support partial weight matrices

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#2933]
We could probably improve our ICA application speed by following the fieldtrip model of assembling a new projection matrix from selected components and subtracting that from eye(n_channels).
A second benefit would be that we could deal with partial mixing and unmixing matrices (only giving you a subset of components).

cc @agramfort @jona-sassenhagen

**Comment by dengemann** [comment]
Tested a bit with some dirty code and it looks rather promising.

**Comment by agramfort** [comment]
oups...

**Comment by Eric89GXL** [comment]
@dengemann maybe this could be a target for the sprint?

**Comment by dengemann** [comment]
Yes, maybe.

**Comment by larsoner** [comment]
I think we probably don't need this since it doesn't seem to be a processing bottleneck, and we recently refactored the component selection code
