### ISSUE TITLE
Reading Xfit dipole file

### ISSUE THREAD

**Issue by kambysese** [mne-tools/mne-python#2935]
@Eric89GXL attaching xfit .fif in compressed file containing single ecd waveform and goodness of fit time series. You can also find [here] (https://www.dropbox.com/s/lurthfo1hy9tzvg/fam_115_LH.fif?dl=0) if attachment doesn't work. 
[fam_115_LH.zip](https://github.com/mne-tools/mne-python/files/143288/fam_115_LH.zip)

Like I said `read_meas_info(fid, tree, clean_bads=True)` seems to get at `meas` but not `info` b/c there is no isotrak, unable to make much sense out of the TAG structure. Although, 't = mne.io.tag.read_tag(fid, pos=3, shape=204)' implies some hope....

> File "/home/ktavabi/Projects/mne-python/mne/io/tag.py", line 501, in read_tag
>     tag.data = _read_matrix(fid, tag, shape, rlims, matrix_coding)
>   File "/home/ktavabi/Projects/mne-python/mne/io/tag.py", line 237, in _read_matrix
>     raise ValueError('Row reading not implemented for matrices '
> ValueError: Row reading not implemented for matrices yet

**Comment by Eric89GXL** [comment]
@kambysese okay with you if I add this to the mne-testing-data repo publically available?

**Comment by kambysese** [comment]
> @kambysese okay with you if I add this > to the mne-testing-data repo
publically > available?

Fine by me.

**Comment by Eric89GXL** [comment]
Great, thanks. PR made: #2935

**Comment by Eric89GXL** [comment]
Whoops I mean #2942
