### ISSUE TITLE
test CTF pipeline using the phantom data

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#2937]
I've just been told that we may have bugs in refs channels in our CTF code (present in matlab too apparrently).

to validate our code we should use the phantom data that BST is also using:

http://neuroimage.usc.edu/brainstorm/Tutorials/Phantom

cc @ftadel

**Comment by Eric89GXL** [comment]
That would explain why the bst tutorial never looked right

**Comment by Eric89GXL** [comment]
@agramfort I don't see a reference for where the dipole actually gets localized. Do you have Brainstorm? Can easily you try running the suggested pipeline and report the results? If not I can give it a shot.

**Comment by agramfort** [comment]
ping @ftadel

**Comment by ftadel** [comment]
I'm currently fixing the issue and writing code to display correctly the references, so we can have a nice visual reference of what the CTF reference coils look like. It may take me a few more days before I fix everything down to the dipole fitting and update the tutorials. I'll let you know when I'm done.

**Comment by Eric89GXL** [comment]
Thanks for the quick response @ftadel, looking forward to the updates.

**Comment by Eric89GXL** [comment]
Based on the website it looks like this might be done now

**Comment by ftadel** [comment]
Yes, the CTF part is finished and properly documented. It includes the equivalent .fif equivalent to the .ds folders produced with the last update of Matti's converter.

We're waiting for equivalent recordings from the Cleveland Clinic (Neuromag) and hopefully from various 4D sites. I will update the sample_phantom.zip package, the scripts and the website as we get these.

**Comment by Eric89GXL** [comment]
Great, thanks for the info @ftadel

**Comment by agramfort** [comment]
@Eric89GXL are you on it?

**Comment by Eric89GXL** [comment]
I'll see if I can get to it in the next few days

**Comment by Eric89GXL** [comment]
I don't think I'll have time for this before 0.12, @agramfort okay with you to move it to 0.13?

**Comment by Eric89GXL** [comment]
We could/should probably tackle it at the same time as the bst_auditory stuff

**Comment by agramfort** [comment]
fine with me.

no time to help either
