### ISSUE TITLE
Improve epoching / robust_average

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#294]
I liked that mne_process_raw could save several averages to a single evoked FIF. It would be nice if we could do that with our datasets, too. I think this basically requires enhancing the evoked instances to deal with storing multiple datasets. This is also a natural extension now that epochs can hold multiple event types in an intuitive way. This is how I'm thinking it might work:

1) On creation of evoked from `read_evoked`, you can specify one _or more_ datasets/setno's to load from the disk.

2) On creation of evoked from epochs, `epochs.average()` would maintain current behavior, that is, averaging over all events regardless of event number, for backward compatibility. Enhanced functionality would come from `epochs.average('AudL')`, or `epochs.average(['AudL', 'AudR'])`, which would return an evoked with one or two datasets coming from averaging a subset of the epochs objects, respectively.

While I'm in there, I think there was a way to also access the saved evoked data based on it's name (probably from the `comment` field?) instead of setno. Since we now have dict() use in epochs and such, this should be fairly straightforward.

@agramfort, let me know what you think before I start to hack hack hack.

**Comment by jona-sassenhagen** [comment]
Hmmm ... couldn't we at least have something like:

```
epochs.average(method="median")
epochs.average(method=np.median)
epochs.average(method=lambda d: (d * d).mean(0))
```

?

This would actually simplify a bunch of internal code too, because we're doing stuff like plotting GFPs quite a lot.

**Comment by larsoner** [comment]
Sounds like there is finally a volunteer to do this :)

**Comment by jona-sassenhagen** [comment]
Well, if Alex and you agree it's useful now. See rejection in #3044

**Comment by larsoner** [comment]
Closing as dup of #3044 :)

I can live with it now, especially if we can use it to simplify our internal functions.
