### ISSUE TITLE
FIX : import problem for psd_welch in example/realtime

### ISSUE THREAD

**Issue by jpirsch** [mne-tools/mne-python#2947]
While trying to use the example ft_client_rt_compute_psd.py, I found an error with the import of psd_welch : "from mne.time_frequency import psd_welch
ImportError: cannot import name psd_welch"
As i had mne 0.9.0 I did "pip install mne --upgrade" to get mne 0.11.0 but the problem remain unsolved.
Could someone check it ?

**Comment by jasmainak** [comment]
You need the development version to solve your problem.

Or do ``from mne.time_frequency import compute_epochs_psd``

**Comment by jasmainak** [comment]
http://mne-tools.github.io/stable/auto_examples/realtime/ftclient_rt_compute_psd.html#sphx-glr-auto-examples-realtime-ftclient-rt-compute-psd-py
