### ISSUE TITLE
Memory consumption / scipy fft

### ISSUE THREAD

**Issue by jaeilepp** [mne-tools/mne-python#2967]
``time_frequency/plot_epochs_spectra.py`` consumes over 2GB of memory. I tracked it down to  https://github.com/mne-tools/mne-python/blob/master/mne/time_frequency/multitaper.py#L440
Then I tried breaking it to parts so that one signal at a time is transformed. That reduced the memory consumption, but I noticed that the results are less smooth. Here are plots from ``plot_epochs_spectra.py``
On master:
![figure_1-4](https://cloud.githubusercontent.com/assets/3456414/13422160/2b088a9c-df93-11e5-8219-11198b9b2d60.png)
One signal at a time:
![figure_1-1](https://cloud.githubusercontent.com/assets/3456414/13422168/339af94c-df93-11e5-978d-1777c185c95c.png)

Any idea what's going on?

**Comment by agramfort** [comment]
open a PR so we can see the diff.

it does not seem obvious looking at your plots.
