### ISSUE TITLE
Timing error 

### ISSUE THREAD

**Issue by kambysese** [mne-tools/mne-python#2976]
@Eric89GXL what is `_time_mask` in #2927 doing? I am on commit e1b90ef13a and still hitting this for a case where chpi T0 is 22 and first sample offset is 23, and another case for the comparison 20.8330 < 20.8333 that is identical to initial problem.

**Comment by Eric89GXL** [comment]
Can you put the pos and raw file somewhere for me to look at?

**Comment by kambysese** [comment]
@Eric89GXL were you able to access the files on Kasga?

**Comment by Eric89GXL** [comment]
Haven't had time to look for/at the files yet
