### ISSUE TITLE
BUG: inconsistent authors formatting in docs

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#2999]
in the examples, the authors are in the script:
![author](https://cloud.githubusercontent.com/assets/4881164/13638748/b62df546-e5db-11e5-9d1b-a2dd6dab19e9.png)

in the tutorials, two font types are used for the authors:
![authors](https://cloud.githubusercontent.com/assets/4881164/13638749/b675675a-e5db-11e5-98ce-edff4f9945e1.png)

**Comment by jasmainak** [comment]
Fix welcome.

**Comment by kingjr** [comment]
I don't master sphinx sorry.

**Comment by jasmainak** [comment]
You have to simply move the authors into the comment like this: https://github.com/mne-tools/mne-python/blob/master/tutorials/plot_cluster_methods_tutorial.py#L55

**Comment by Eric89GXL** [comment]
@jasmainak does that work for multi-line author lines? It seems like that's the problem here

**Comment by jasmainak** [comment]
yep it does. Example here: http://www.martinos.org/mne/stable/auto_tutorials/plot_ica_from_raw.html.

**Comment by Eric89GXL** [comment]
This looks fixed to me, feel free to reopen if it's not
