### ISSUE TITLE
isinstance('ch_name', str) should be checked against basestring

### ISSUE THREAD

**Issue by sstober** [mne-tools/mne-python#3009]
Checking against str fails for unicode channel names. Specifically, this problem occurs here
https://github.com/mne-tools/mne-python/blame/master/mne/preprocessing/eog.py#L105
for ch_name=u'EXG1'

Possibly, this is not the only place where this is problematic.

**Comment by jasmainak** [comment]
yeah, I think it should be `isinstance(ch_name, string_types)` where `string_types` comes from `externals.six`

**Comment by agramfort** [comment]
indeed

PR welcome
