### ISSUE TITLE
raw.info / pick.py error from .fif with BIO channels

### ISSUE THREAD

**Issue by tntdynamight** [mne-tools/mne-python#3017]
Hi, 
This relates to [#694](https://github.com/mne-tools/mne-python/issues/694). 
Using the latest git mne-python, I get an error when 'BIO001' etc channel is included. 
(` raise Exception('Unknown channel type')`)

I tried guessing and adding into pick.py / channel_type function:
`56     elif kind == FIFF.FIFFV_BIO_CH:`
` 57         return 'misc'`

but then I get: 
`AttributeError: 'BunchConst' object has no attribute 'FIFFV_BIO_CH'`

Here is a small file including the channels:
https://www.dropbox.com/s/i65bvjhlq2kj1b3/BIO_fif_tsss_mc.fif?dl=0

Appreciate any help with this, 
best 
tnt

**Comment by agramfort** [comment]
see fix coming at  https://github.com/mne-tools/mne-python/pull/3018

**Comment by tntdynamight** [comment]
Works great, thanks for the quick update!
