### ISSUE TITLE
ADD to FAQ resample versus decimate methods

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-python#3021]
I have a question about the resample method for `mne.source_estimate.SourceEstimate`. why do we have resample here and how is it different from the `decimate` method that we have the `Epochs`? Is it generally safe to resample the `SourceEstimate` if it is doing internal filtering?

**Comment by teonbrooks** [comment]
cc: @reddigari

**Comment by Eric89GXL** [comment]
Decimate doesn't do any filtering, just subselects samples. It's appropriate if you know your data are already low-passed, and doesn't introduce edge artifacts.

Resampling, on the other hand, does apply a low-pass filter of its own before sub-selecting samples. This therefore can introduce edge artifacts.

Make sense? If so, please open a PR to the FAQ page about the differences between decimation in mne-python, and resampling if you have time. If you don't please re-title this issue to be about adding such a section.

**Comment by teonbrooks** [comment]
thanks @Eric89GXL. next question would be, should we have the decimate method added to the `SourceEstimate` as well?

**Comment by Eric89GXL** [comment]
It's not as safe because for the SourceEstimate objects we have no knowledge of `lowpass`, whereas for `Epochs` we do in `info['lowpass']`.

**Comment by Eric89GXL** [comment]
But I think you can get what you want by using `stc.bin`

**Comment by teonbrooks** [comment]
ah, I didn't realize that this wasn't in its info. actually, I just discovered that it has no info.

**Comment by Eric89GXL** [comment]
@teonbrooks you updating the FAQ section? If not, I can tackle it -- there are a few things I'd like to add.

**Comment by teonbrooks** [comment]
I can't at the moment. please feel free to jump in, thanks :)
