### ISSUE TITLE
BUG broken ref on the stable website

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-python#3025]
On the stable website:

MNE includes a comprehensive Python package supplemented by tools compiled from C code for the LINUX and Mac OSX operating systems, as well as a MATLAB toolbox.

From raw data to source estimates in about 30 lines of code (:ref:`try it yourself! <getting_started>`_):

The ref link is broken

**Comment by agramfort** [comment]
@jaeillep we need to update the website stable and dev asap.
