### ISSUE TITLE
ENH: Make non-example-plotting CircleCI run on PRs

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#3029]
CircleCI could run on all PRs and build the `make html_dev-noplot` version. It would make it easier to check how docstrings get formated. @jaeilepp WDYT?

**Comment by jaeilepp** [comment]
Sounds good to me.

**Comment by Eric89GXL** [comment]
Are you on it or should I try?

**Comment by jaeilepp** [comment]
I'm actually trying to get circle to auto-update the mne-tools.github.io repo on success. Maybe it's best to make these in separate PRs, so go ahead.
