### ISSUE TITLE
epochs.apply_baseline does not return self

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#3037]
`Epochs.apply_baseline` claims it returns `self`, but it returns nothing:
https://github.com/mne-tools/mne-python/blob/4b93a7051f8ee5bc46b02f2acf5823900029f418/mne/epochs.py#L437
https://github.com/mne-tools/mne-python/blob/4b93a7051f8ee5bc46b02f2acf5823900029f418/mne/epochs.py#L455

Also, shouldn't it have a copy method?

I can PR once I have another one merged.

**Comment by kingjr** [comment]
> Also, shouldn't it have a copy method?

+1
