### ISSUE TITLE
plot_meg_sensors not working on docs.

### ISSUE THREAD

**Issue by jaeilepp** [mne-tools/mne-python#3056]
This is broken https://circle-artifacts.com/gh/mne-tools/mne-python/552/artifacts/0/home/ubuntu/mne-python/doc/_build/html/auto_examples/visualization/plot_meg_sensors.html#sphx-glr-auto-examples-visualization-plot-meg-sensors-py because the data isn't available, but we probably shouldn't add test paths to ``setup.py``. I'm not sure what would be he best way to fix this. Should we add the bti and kit data to ``mne/data``?

**Comment by agramfort** [comment]
the data are cloned in the repo so they should be somewhere on circle
