### ISSUE TITLE
BUG: get_brainvision_events does not return neuromag-formatted events

### ISSUE THREAD

**Issue by rkmaddox** [mne-tools/mne-python#3061]
`mne.io.brainvision.brainvision.RawBrainVision.get_brainvision_events` gives a three-column array where column 0 is index and column 2 is trigger value, as one would expect. However, column 1 stores the duration of the trigger, instead of the standard value of the trigger channel before the change. This creates problems when you try to mask events. So basically, where `raw` is a brainvision Raw object, this:

`mne.find_events(raw)`

gives you a different event list than this:

`raw.get_brainvision_events`

It seems to me that the use of the latter function should be strongly discouraged, or the function deprecated, since its output is incompatible with other functions.

**Comment by Eric89GXL** [comment]
@teonbrooks WDYT?

**Comment by jona-sassenhagen** [comment]
@teonbrooks maybe we can simply deprecate it? Or is there ever a reason to use it over find_events?

**Comment by teonbrooks** [comment]
it should be a hidden function, it's being used internally. we should deprecate the public use and note the particular use for the private function

**Comment by Eric89GXL** [comment]
Okay will deprecate, I can make a PR

**Comment by Eric89GXL** [comment]
@teonbrooks is `set_brainvision_events` meant to be exposed? I'm not sure what the purpose is.

**Comment by teonbrooks** [comment]
I don't know either. I didn't write this function. it was factored out of the code I wrote. closing this for #3074
