### ISSUE TITLE
ENH: better solver for rERP, encoder models redux

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#3062]
Ridge and OLS as implemented in sklearn are much faster than the current solver, for some reason. (The reason is that obviously, something I hack together will always be worse than sklearn.)
They also are better at optionally dealing with sparse input.
I'd like to add them, and make them the go-to with the current one as a fallback.

(This is another incremental step of expanding rERP/linear_regression_raw into an encoder model.)

I'll go about implementing the first one soon.

Q: what's the most economic way of checking if a scipy coc sparse array is truly sparse, or alternatively, what's a good way of checking if it should be treated as sparse by the solver, or converted to dense and solved by a normal solver?

**Comment by Eric89GXL** [comment]
> Q: what's the most economic way of checking if a scipy coc sparse array is truly sparse

Depends on what you mean by that, but this would get you some of the way maybe

http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.sparse.csr_matrix.nnz.html

**Comment by jona-sassenhagen** [comment]
E.g. you can currently use this for the solver param and it works better:

`def solver(X, y):
    from sklearn.linear_model import Ridge
    return Ridge().fit(X, y.T).coef_`

Also works with RidgeCV. Not really with Lasso though ..

**Comment by jona-sassenhagen** [comment]
Thanks Eric, that's probably it. Unless anybody has a rule of thumb regarding up to what sparsity/density it makes sense to leave X as sparse/use a sparse solver.

**Comment by Eric89GXL** [comment]
I think you should always leave it sparse and leave it up to the user to do the right thing in terms of converting it or not

**Comment by jona-sassenhagen** [comment]
Sadly, this is not possible for the user-facing rERP function, because exists only inside the function. The user doesn't supply X, they supply the information to construct X, and gets the evokeds.

**Comment by Eric89GXL** [comment]
so the rERP function decides whether to construct a sparse matrix or dense array?

**Comment by jona-sassenhagen** [comment]
Due to the way we've settled on handling it internally, it always starts out as sparse (see https://github.com/mne-tools/mne-python/blob/master/mne/stats/regression.py#L363), and right now, the solver always converts it to dense (see https://github.com/mne-tools/mne-python/blob/master/mne/stats/regression.py#L254).

**Comment by jona-sassenhagen** [comment]
The part where Denis and I settled on using sparse.dia_matrix is handled differently by Chris' approach, by XDawn, by the original implementation, and was handled differently by the initial version of linear_regression_raw. The current version is the only one of these that's sparse, and that was because we saw major performance improvements from that.

**Comment by Eric89GXL** [comment]
> Unless anybody has a rule of thumb regarding up to what sparsity/density it makes sense to leave X as sparse/use a sparse solver.

Ahh, that's what you mean by this. I don't know any rule of thumb, but you could do some benchmarking to try to see when approximately it switches.

> The current version is the only one of these that's sparse, and that was because we saw major performance improvements from that.

To start, though, I'd just try to get it working and leave such optimization for later (with notes in the code to come back to it). Trying to optimize with such branching while also expanding / unifying funtionality can make things more difficult. To do it properly I'd verify that the dense and sparse paths give equivalent results (meaning unit tests) and then do benchmarking, etc.

**Comment by jona-sassenhagen** [comment]
Actually, I just realized the user can indeed decide on converting to dense by plugging in a solver that converts to dense vs. one that doesn't. But I always like an 'auto' option ... I'll play around with it a bit.

**Comment by jona-sassenhagen** [comment]
E.g. the user can do

```
def solver_sparse(X, y):
    from sklearn.linear_model import Ridge
    return Ridge().fit(X, y.T).coef_
```

and

```
def solver_dense(X, y):
    from sklearn.linear_model import Ridge
    return Ridge().fit(X.toarray(), y.T).coef_
```

and then

```
evokeds = linear_regression_raw(raw, events, event_id, solver=solver_dense, ...)
```

**Comment by jona-sassenhagen** [comment]
Nathaniel Smith uses a very memory efficient incremental solver where Xt * X and Xt * y are constructed incrementally. I've finally basically figured out how it works (I think ...), and implemented a special solver for it. It's not necessarily faster, and it is only an asymptotically approximate solution as far as I can tell, but for certain cases, it should be much faster, and in general, it should allow to solve even massive problems in little RAM. (I usually run this on a machine with 250 GB RAM, but I am being told some use their laptops ...)
 
Example results (EEGLAB sample data) looks like this.

Incremental solver:
![unknown-126](https://cloud.githubusercontent.com/assets/4321826/14157424/3ec07ce4-f6cb-11e5-9a6a-807b3bd9970c.png)

Current solver:
![unknown-127](https://cloud.githubusercontent.com/assets/4321826/14157429/42b790d0-f6cb-11e5-8e70-0dfbefb6a2e9.png)

Difference (notice the unit):
![unknown-125](https://cloud.githubusercontent.com/assets/4321826/14157436/498b25b6-f6cb-11e5-876e-78136b6ff20a.png)

Implementation:
```
def incremental_solver(X, data):
    stride_ratio = 2
    n_times, n_coefs = X.shape
    one_stride = int(n_coefs * stride_ratio)
    loops = (n_times // one_stride) - 1

    XtX_all = np.zeros((n_coefs, n_coefs))
    XtY_all = np.zeros((X.T * data.T).shape)
    for ii in range(0, n_times - one_stride + 1, one_stride):
        reach = (one_stride + (n_times % one_stride)
                 if ii + (one_stride * stride_ratio) > n_times
                 else one_stride)
        XtX_all += (X[ii:ii + reach, :].T * X[ii:ii + reach, :])
        XtY_all += (X[ii:ii + reach, :].T * data[:, ii:ii + reach].T)

    return linalg.solve(XtX_all, XtY_all)
```

I'd like to offer this as an alternative.
