### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-python#3069]
- [x] the development links says this is v0.11 but we are in dev0.12

- [x] when hovering over header links, it displays the paragraph symbol, this doesn't seem like the correct behavior.

- [ ] the example figures look funky here:
http://martinos.org/mne/dev/auto_examples/visualization/plot_meg_eeg_fields_3d.html#sphx-glr-auto-examples-visualization-plot-meg-eeg-fields-3d-py

**Comment by agramfort** [comment]
can you refresh your browser cash?

**Comment by Eric89GXL** [comment]
> when hovering over header links, it displays the paragraph symbol, this doesn't seem like the correct behavior.

That's a symbol that means you can use it as a link and I think it's useful. I've seen it on other sites, too.

**Comment by teonbrooks** [comment]
the website is up-to-date for me now. everything looks great!

> That's a symbol that means you can use it as a link and I think it's useful. I've seen it on other sites, too.

ah, ok. sounds fine. 

closing
