### ISSUE TITLE
Return self for in-place operations; Enable chaining for in-place operations

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-python#3070]
We have some inconsistencies about when we return `self` for in-place operations and when we don't. I think we apply this rule consistently when there is a `copy` param but it seems like we should have it elsewhere. it's useful for chaining. this was recently brought up on the listserv when someone tried to assign the `raw.filter()` output to a variable. If you wanted to `raw.filter().plot()` it wouldn't work.

**Comment by jona-sassenhagen** [comment]
I heartily support this.

Note it can probably be made to work without disruptive changes (unless somebody really needs their `raw.filter()` to return `None`...).

One big PR or slower rollout?

**Comment by kingjr** [comment]
+1 Some methods already return self, e.g. `pick_types` but it's not consistent.

**Comment by Eric89GXL** [comment]
I'd say get as many as you can in one PR, they should be almost exclusively one-liners plus docstring updates

**Comment by Eric89GXL** [comment]
(IMO we don't need to test the return value actually exists, so don't need to modify tests -- we'll end up naturally modifying them in the future probably to use the functionality)

**Comment by Eric89GXL** [comment]
@teonbrooks @jona-sassenhagen @kingjr one of you have time to take a stab at it in the next week or two? If not I can try. Would be good to have for 0.12.

**Comment by kingjr** [comment]
If I have time, I was thinking to devote it to the binder examples.

**Comment by Eric89GXL** [comment]
+1 that's a higher priority in my mind

**Comment by mmagnuski** [comment]
(this got closed by accident :hamster: )

**Comment by Eric89GXL** [comment]
I think @agramfort and @jona-sassenhagen's PRs hopefully take care of most of the cases

**Comment by teonbrooks** [comment]
@mmagnuski you're right, there was a misdirected ref that closed it.

**Comment by jona-sassenhagen** [comment]
What else needs a copy param? Epochs.savgol?

**Comment by Eric89GXL** [comment]
Added `savgol` to my PR
