### ISSUE TITLE
FIX: tutorials title layout

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#3075]
Several sections of the tutorials have their title as first bullet:

http://martinos.org/mne/dev/manual/index.html

e.g.

```
Cookbook
A quick run-through of the basic steps involved in M/EEG source analysis.

    * Cookbook
```

I guess the advantage is that the bullet has an external link, but it seems redundant.

**Comment by agramfort** [comment]
PR welcome :)

**Comment by Eric89GXL** [comment]
I've noticed this before and poured over the sphinx docs trying to find a way to exclude items from a TOC, or to start the TOC from e.g. one level deep without success. So I'm not optimistic about solving this one, but I'd love to be proved wrong.

**Comment by Eric89GXL** [comment]
I opened an issue on Sphinx-doc (https://github.com/sphinx-doc/sphinx/issues/2790) with an offer to make a PR, we'll see if it gets any traction

**Comment by Eric89GXL** [comment]
I looked into it and this is a pain at the Sphinx level. So I'll close this as won't fix
