### ISSUE TITLE
Add two methods Epochs, Evoked

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-python#3083]
It would be super useful to have these methods added to the Epochs, and Evoked.

`raw.time_as_index` and `raw.index_as_time`

**Comment by kingjr** [comment]
What s the use case ? Can you just divide by `info['sfreq']`?

**Comment by teonbrooks** [comment]
yes, but it is a function that exists. it seems like it should be propagated since it's convenient, it takes into account the rounding business as well

**Comment by teonbrooks** [comment]
it's mostly needed for time_as_index. it deals with the fact that you might have a baseline period and just by multiply by the sfreq isn't enough, you would have to adjust for baseline

**Comment by agramfort** [comment]
time_as_index makes sense. The other one is just a matter of e.times[idx]

**Comment by Eric89GXL** [comment]
@agramfort okay with you to deprecate `raw.index_as_time` then and point people toward `inst.times[idx]`?

**Comment by agramfort** [comment]
yes
