### ISSUE TITLE
errors in install mne c tuto

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#3088]
see http://martinos.org/mne/dev/install_mne_c.html

$ $MNE_ROOT/bin/mne_setup_sh

should be

$ . $MNE_ROOT/bin/mne_setup_sh

it's the usual problem.

Please please if you have a bit of time help us with the web site. I unfortunately cannot allocate more time to it :(

**Comment by jaeilepp** [comment]
Wow. That's bad.
I can include it with all the other fixes.

**Comment by agramfort** [comment]
Please do
