### ISSUE TITLE
Cannot exclude KIT marker coil

### ISSUE THREAD

**Issue by reddigari** [mne-tools/mne-python#3091]
When using two sets of marker coil measurements in `gui.kit2fiff`, it is no longer possible to exclude a single marker from one or both measurements.
![screen shot 2016-04-01 at 12 04 01 pm](https://cloud.githubusercontent.com/assets/10101166/14213000/9a8d0824-f803-11e5-9186-c71f41f2817b.png)

**Comment by reddigari** [comment]
cc: @teonbrooks

**Comment by teonbrooks** [comment]
cc: @christianbrodbeck

**Comment by christianbrodbeck** [comment]
@reddigari I can't reproduce this, can you send me your files and tell me the exact sequence of commands?

**Comment by teonbrooks** [comment]
UPDATE: it was a problem that resulted from a bad squid file, not the marker file
