### ISSUE TITLE
Misleading install instructions

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#3092]
The website reads:

>If you don't have git installed, you can download a zip or tarball of the latest code: >https://github.com/mne-tools/mne-python/archives/master

But when you click on that link, it currently reads:
>There aren’t any uploads for this repository.

Perhaps that link should be changed to link to https://github.com/mne-tools/mne-python/archive/master.zip instead?

**Comment by Eric89GXL** [comment]
PR welcome for that and anything else you find

**Comment by jona-sassenhagen** [comment]
On it.
