### ISSUE TITLE
scipy.linalg error with maxwell_filter

### ISSUE THREAD

**Issue by szorowi1** [mne-tools/mne-python#3094]
Hi all,

Following up on an issue we've been running into when using the maxwell_filter function from mne 0.11. Attached are the files and code necessary to recreate the issue. 

[github_code.txt](https://github.com/mne-tools/mne-python/files/200990/github_code.txt)
[hc021_arc1_motion_hpi.txt](https://github.com/mne-tools/mne-python/files/200991/hc021_arc1_motion_hpi.txt)
[hc021_arc2_motion_hpi.txt](https://github.com/mne-tools/mne-python/files/200992/hc021_arc2_motion_hpi.txt)
[hc021_arc3_motion_hpi.txt](https://github.com/mne-tools/mne-python/files/200993/hc021_arc3_motion_hpi.txt)

Because the raw file is quite large, I've stored in a dropbox link here:

raw pt. 1: https://www.dropbox.com/s/5xnr8jn0e8dvwos/hc021_arc_rer_raw.fif?dl=0
raw pt. 2: https://www.dropbox.com/s/j9qset1pzzn95w8/hc021_arc_rer_raw-1.fif?dl=0

Let me know if there is anything else I can provide!

The error itself is posted below.

> Traceback (most recent call last):
>   File "motion_correction_flat.py", line 65, in <module>
>     raw = maxwell_filter(raw, st_duration=st_duration, destination=trans.mean(axis=0), verbose=True)
>   File "<string>", line 2, in maxwell_filter
>   File "/homes/5/szoro/.local/lib/python2.7/site-packages/mne/utils.py", line 548, in verbose
>     return function(*args, **kwargs)
>   File "/homes/5/szoro/.local/lib/python2.7/site-packages/mne/preprocessing/maxwell.py", line 404, in maxwell_filter
>     t_proj = _overlap_projector(orig_in_data, resid, st_correlation)
>   File "/homes/5/szoro/.local/lib/python2.7/site-packages/mne/preprocessing/maxwell.py", line 1237, in _overlap_projector
>     overwrite_a=True, mode='economic', **check_disable)[0].T
>   File "/homes/5/szoro/.local/lib/python2.7/site-packages/scipy/linalg/decomp_qr.py", line 142, in qr
>     overwrite_a=overwrite_a)
>   File "/homes/5/szoro/.local/lib/python2.7/site-packages/scipy/linalg/decomp_qr.py", line 20, in safecall
>     ret = f(*args, **kwargs)
> ValueError: failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (0,)

**Comment by szorowi1** [comment]
In response to Eric's request:

cat /proc/cpuinfo | grep avx | wc -l
24
cat /proc/cpuinfo | grep sse4_2 | wc -l
24
cat /proc/cpuinfo | grep sse4_1 | wc -l
24

**Comment by Eric89GXL** [comment]
Can you give mne.sys_info() output too?

**Comment by szorowi1** [comment]
Apologies, but is that an attribute of mne? I'm getting an error running mne.sys_info()

**Comment by Eric89GXL** [comment]
Are you on latest master? It should be there.

If not, it would be good to know what Python you're running (anaconda,
system, etc.) and numpy and SciPy versions

**Comment by szorowi1** [comment]
I thought I was, but evidently not. I'm running Anaconda. Numpy version 1.10.4. Scipy version 0.16.0

**Comment by Eric89GXL** [comment]
That function was added only a month or two ago, if it matters.

**Comment by Eric89GXL** [comment]
> from mne 0.11

Although from your previous post it sounds like you are on 0.11, not master?

**Comment by szorowi1** [comment]
Just checked: I am on 0.11.

**Comment by Eric89GXL** [comment]
The weird thing is that your `scipy` is imported from `.local/lib/python2.7/site-packages/scipy/linalg/decomp_qr.py`. I don't think that's usually where Anaconda would install it. I wonder if perhaps some program ended up doing `pip install scipy` and installing it to your system package location instead. What does `which python` say?

**Comment by szorowi1** [comment]
/usr/pubsw/packages/python/anaconda/bin/python

**Comment by Eric89GXL** [comment]
I suspect if you do `ls -d /usr/pubsw/packages/python/anaconda/lib/python2.7/site-packages/sci*` you'll see some `scipy` packages there, probably with version 0.16?

What does `python -c "import scipy; print(scipy); print(scipy.__version__)"` say?

**Comment by szorowi1** [comment]
<module 'scipy' from '/homes/5/szoro/.local/lib/python2.7/site-packages/scipy/__init__.pyc'>
0.16.0

**Comment by Eric89GXL** [comment]
I'm a bit stumped. You could try:
```
conda update conda
conda install mkl
```
And see if that updates anything. You could also do:
```
conda update scipy
```
But that could possibly break something.

**Comment by szorowi1** [comment]
I'm not sure if this helps explain, but I'm at the Martinos center. So the anaconda distribution is sourced through the center's install; my MNE is sourced through a local install given that their time install is still on 0.9

**Comment by Eric89GXL** [comment]
@szorowi1 any luck fixing this one, or are you still stuck?

**Comment by Eric89GXL** [comment]
Closing since I suspect this is a packaging issue that has been resolved (?), but feel free to reopen if I'm mistaken
