### ISSUE TITLE
pick_types allows non-bool args for e.g. EEG

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#3103]
I saw somebody doing this today:

`raw.pick_types(meg=False, eeg='grads')`

Which works (picking EEG channels).
Maybe a bit confusing, but not necessarily a bug ... Should we fix or keep?

**Comment by Eric89GXL** [comment]
People could also do `pick_types(eeg=0)` which would evaluate the same way as False, and `pick_types(eeg=1)` which would eval as `True`, which I'm okay with. I guess we could strictly type check to be safe, though.

**Comment by agramfort** [comment]
well I guess it's hard to catch all possible bugs but for such a common
function might we can make an effort to type check

**Comment by jona-sassenhagen** [comment]
I can make a PR with something like
```
params = eeg, stim, ...
for param in params:
    if not isinstance(param, bool):
        raise ValueError(param + " must be of type ``bool``!")
```

**Comment by agramfort** [comment]
yes but say also what is the type provided.

**Comment by jaeilepp** [comment]
We have ``ref_meg='auto'`` as a default. I'm still unclear about what it means.
