### ISSUE TITLE
nosetests attempts ftp download

### ISSUE THREAD

**Issue by jjnurminen** [mne-tools/mne-python#3113]
Hi,
I tried running nosetests via make, but it fails attempting a ftp download. I'm behind a hospital firewall and 
cannot use ftp (http downloads work fine via a proxy). Any suggestions?

If I only change documentation (docstrings and/or .rst), is it enough to run make test-doc?

**Comment by agramfort** [comment]
yes it should be good. We'll polish it if needed

**Comment by Eric89GXL** [comment]
Does it get to running the tests, and the file-downloading test fails? Or does it try to download a dataset *before* even running the tests? If it's the former, just ignore the failing download test -- the other tests are still valid. If it's the latter, you can run `nosetests -a '!slow_test' mne` (which is the second part in the Makefile).

You probably also want to run `nosetests mne/tests/test_docstring_parameters.py` to test some aspects of docstring formatting.

**Comment by jjnurminen** [comment]
It was the former, but somehow the failed ftp download brought the whole thing down and the tests stopped running right there. I lost the console output, but I'll try it again.

**Comment by jjnurminen** [comment]
[output.txt](https://github.com/mne-tools/mne-python/files/214502/output.txt)

Attached console output.

**Comment by agramfort** [comment]
ERROR: Test file downloading is unrelated.

FAIL: Test Raw compensation by comparing with MNE is more problematic.
Maybe your sample dataset is not up to date?

**Comment by Eric89GXL** [comment]
Probably the testing dataset needs an update.

**Comment by Eric89GXL** [comment]
@jjnurminen okay to close this one? I think a test failing about FTP download is the right behavior if you can't actually download using FTP. If you really want to avoid seeing these failures, we could add a mne config like `MNE_SKIP_FTP_TESTS` that you and anyone else who can't use FTP could set to true.

**Comment by jjnurminen** [comment]
Nice! I'll try it tomorrow. Closing now.
