### ISSUE TITLE
fine tuning for plot sensors

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#3120]
After merging #3065 the next thing would be to add axis, picks and color parameters. Why is this? It facilitates creating educational plots of ROIS, e.g. like that:
![sensor_selection](https://cloud.githubusercontent.com/assets/1908618/14492458/40160738-0177-11e6-999b-d1a051ccdbba.png)

**Comment by teonbrooks** [comment]
that looks great

**Comment by dengemann** [comment]
> that looks great

thanks, so far done with Python-(minus)MNE

**Comment by jona-sassenhagen** [comment]
Yes I like it. This is used in many ERP publications.

**Comment by jaeilepp** [comment]
This is now done in https://github.com/mne-tools/mne-python/pull/3237 although there is no color parameter. The color is automatically defined when you use an array as ``regions``. See if it satisfies you.

**Comment by agramfort** [comment]
quick feedback after playing a bit with it

- regions seems like a misnomer as it can be a list of arrays that are not clusters / form regions

- regions='selection' would allow to see the automatic selections used in raw.plot

- raw.plot_sensors(ch_type='grad', regions='position')  # crashes on SPM dataset
# returns:
RuntimeError: Did not find any digitization points of kind FIFFV_POINT_EEG (3) in the info.

but this works

raw.plot_sensors(regions='position')

- raw.copy().pick_types(meg=False, eeg=True).plot_sensors(regions='position')

gives rather weird results.

Also see with grad or mag on sample. See the light blue dot at the right corner.

![screen shot 2016-05-24 at 19 57 10](https://cloud.githubusercontent.com/assets/161052/15516778/6c45ff82-21c2-11e6-9cc1-6a4af32191bb.png)

**Comment by jaeilepp** [comment]
> regions seems like a misnomer as it can be a list of arrays that are not clusters / form regions

Any suggestion for a better name? All the other comments addressed.

**Comment by jona-sassenhagen** [comment]
Can this be closed due to #3237 then?

**Comment by agramfort** [comment]
I guess so.
