### ISSUE TITLE
mne.viz.topomap sensor name size too small

### ISSUE THREAD

**Issue by moritzschaefer** [mne-tools/mne-python#3127]
Names on the topomap are always printed small:
https://github.com/mne-tools/mne-python/blob/master/mne/viz/topomap.py#L604
`ax.text(p[0], p[1], ch_id, horizontalalignment='center', verticalalignment='center', size='x-small')`

That's too small if you choose a size of several inches (e.g. 10).

Possible solutions:
- Provide another API parameter 
- Derive the parameter from the 'size' parameter

**Comment by jona-sassenhagen** [comment]
How about simply increasing the default?

I agree it's usually unreadable.

**Comment by moritzschaefer** [comment]
That would be an easy solution to start with. Just feels a bit like a workaround

**Comment by jona-sassenhagen** [comment]
Ping @agramfort @jaeilepp ?

I volunteer for a PR if you agree this is an issue, but we would have to decide on the API (vs. e.g. defaults) first.

**Comment by agramfort** [comment]
if you can infer a good value from size param it's nice.

**Comment by moritzschaefer** [comment]
+1

Alexandre Gramfort <notifications@github.com> schrieb am Sa., 23. Apr.
2016, 22:59:

**Comment by jona-sassenhagen** [comment]
I won't get to it for .12 though.

**Comment by dengemann** [comment]
Another solution, just edit the figure post-hoc:

```Python
for tt in plt.findobj(fig, matplotlib.text.Text):
    if tt.get_text() in evoked.ch_names:
        tt.set_fontsize(14)
```

**Comment by dengemann** [comment]
In the latter case make sure to plot with show=False and call fig.canvas.draw() and plt.show() once you're done

**Comment by Eric89GXL** [comment]
@jona-sassenhagen any time to tackle this one?

**Comment by agramfort** [comment]
I upvote @dengemann 's answer. It should do the job.
