### ISSUE TITLE
Q? neuromag vectoriview layout naming

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#3128]
The neuromag layout called `Vectorview-mag`, but the connectivity is `neuromag306mag` (and similar for `grad` etc)

https://github.com/mne-tools/mne-python/tree/master/mne/channels/data/layouts

I found it a bit confusing. Can't we make the naming consistent?

**Comment by agramfort** [comment]
these files are not ours. We just expose them.

**Comment by kingjr** [comment]
Shouldn't we make a lookup table to impose consistency?

**Comment by dengemann** [comment]
Not sure it's worth the effort, Fieldtrip users for example should already
be very familiar with what we have. But what I think would help indeed at
least would be an option to list layouts from the command line in an
informative, as these names are not necessarily easy to remember.

**Comment by agramfort** [comment]
if you write the narrative doc on this I am ok to negotiate :)

**Comment by kingjr** [comment]
We could also add a page somewhere in the manual to add a table listing the 2D, 3D and neighbours layout of each system we currently expose.

**Comment by agramfort** [comment]
thanks for volunteering :)

**Comment by kingjr** [comment]
crawling under work ATM, closing for now it's low priority.
