### ISSUE TITLE
Importing OpenBCI data

### ISSUE THREAD

**Issue by ncullen93** [mne-tools/mne-python#3134]
Any plan to read/stream OpenBCI data? I use that hardware... so I'd be interested in incorporating it. Perhaps something along the lines of the following project: https://github.com/OpenBCI/OpenBCI_Python  or ideally just incorporating that project in MNE.

**Comment by teonbrooks** [comment]
hi @ncullen93, we have a pull request, https://github.com/mne-tools/mne-python/pull/2671, that aims to incorporate OpenBCI streaming into MNE. feel free to join the discussion there, and if you would like, you can help contribute to help finish. we can re-stimulate its progress. 
there was an older discussion before https://github.com/mne-tools/mne-python/pull/2462 about this. the data file that comes from OpenBCI_Processing GUI is a modified csv. we decided that it would not be advantageous to support it within the package for a host of reasons. 
I wrote a reader for converting the Processing Data for MNE [here](https://github.com/OpenBCI/OpenBCI_Python/blob/master/externals/mne_openbci.py). 

Let me know if you have any more questions about this. I would happy to answer them. If not, feel free to close this issue.

**Comment by ncullen93** [comment]
I appreciate the info and apologize for the repeat - should have looked harder. Will close this.

**Comment by teonbrooks** [comment]
no worries :)

**Comment by d3christ** [comment]
Hey when I try to run the "from mne_openbci import read_raw_openbci"
I get an error saying that mne is needed but I already have mne installed and activated.

**Comment by cbrnr** [comment]
This module tries to import `_BaseRaw`, which doesn't exist (anymore?) in MNE. Try changing this in lines 17 and 21 to `BaseRaw` and it should work. @teonbrooks you might want to update your module. Also, I don't really understand why you set `np =  None` and `mne = None`?

**Comment by teonbrooks** [comment]
@d3christ that mne_openbci package is deprecated. are you trying to read data in real time or are you trying to the export csv file?

**Comment by teonbrooks** [comment]
I wrote the package like three years and haven't used it since. both mne and openbci has changed significantly since then
