### ISSUE TITLE
Q: Make Info a top-level class

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#3149]
`mne.io.meas_info.Info` is such an important class (across most submodules) so I think it should be in the main namespace as `mne.Info`. Okay if I change it and all references to it before 0.12?

**Comment by jona-sassenhagen** [comment]
Is there any particular reason why Raw only lives under io by the way?..

**Comment by Eric89GXL** [comment]
`io` is for raw `io` only

This was a point of debate a long time ago, and seems to keep coming up @agramfort ... :)

**Comment by Eric89GXL** [comment]
Specifically:

https://github.com/mne-tools/mne-python/pull/1273#issuecomment-42754494

**Comment by Eric89GXL** [comment]
Opened a PR #3150, if anyone else wants to comment feel free over there
