### ISSUE TITLE
FIX: doc API

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#3170]
http://martinos.org/mne/dev/python_reference.html#decoding

In the API section of the dev websites, under `classes` we find several decoding objects, that are not present in the `decoding` section (e.g. `TimeDecoding`).

I'm not sure why..

**Comment by jaeilepp** [comment]
I wonder how we should organize the API section. Is it okay to have duplicate entries (like we're supposed to have now) or should we group them better. Also these things have to be made by hand which often causes dead links as people forget to update this.
