### ISSUE TITLE
ENH: plot_joint_psd

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#3200]
Do we want this?

![unknown-149](https://cloud.githubusercontent.com/assets/4321826/14938529/93ec5878-0f26-11e6-97a1-48e2750ab373.png)

**Comment by kingjr** [comment]
If you find a better example, maybe?

**Comment by kingjr** [comment]
Actually the plot_joint with the topos can be good, although I would normalize per window to make it easier to read and avoid the 1/f non-informative gradient, but the colored line are not super convincing (although for consistency, why not)

**Comment by agramfort** [comment]
if you do it on somato with proper baselining it could be nice.

**Comment by dengemann** [comment]
It could be nice but not with the PSD default settings that we have, for
low frequencies we need long windows, and the welch periodograms don't look
nice. Detrending, power normalization and loglog plotting are further
options. I have some private code on this but I'm hesitating to push it
here as it is pretty particular.

**Comment by dengemann** [comment]
second, the joint plotting needs a rewrite, on resizing the series and the
topo plots get misaligned. very often you want the series plot to be bigger
in this case.

**Comment by jona-sassenhagen** [comment]
Okay, let's see ... also I have way too many issues open already :)

**Comment by dengemann** [comment]
Let's get back to it in a while once we discussed and solved the issues
mentioned in our use cases.

**Comment by dengemann** [comment]
And a related issue I'm holding back is of course a PSDEpochs container
with .freqs instead of .times as sample descriptor axes.
