### ISSUE TITLE
error installing MNE again

### ISSUE THREAD

**Issue by MartinBaBer** [mne-tools/mne-python#3204]
Hello,
I'm using MNE now for exploring MEG data and recognized an error occurring while MNE was installed by pip.

The web page reads: 

> $ pip install mne –upgrade

this is an unknown command on Unix, maybe you could use --upgrade but if it's your first installation I'd recommend using:

> $ pip install mne

There was already an issue about that but no relation to the reduced code snip leaving out -upgrade.

Best
Martin

**Comment by agramfort** [comment]
thanks for the report.

would you have time to send us a pull request to update the doc about this?
