### ISSUE TITLE
split fiff io error

### ISSUE THREAD

**Issue by kambysese** [mne-tools/mne-python#3210]
I am encountering a few cases where `_read_raw_file` returns an `IndexError` when trying to read in the latter portion of split `.fif` files.  From Trace...

> if directory[first].kind == FIFF.FIFF_DATA_SKIP:
> IndexError: list index out of range

What exactly is this about? and anyone know how I can get around it?

**Comment by Eric89GXL** [comment]
That sounds like a bad bug we should fix for 0.12. I think I have a dataset I can try to replicate it on. But just in case, can you make sure you're on latest master, make a short script to reproduce the error, email it to me, and I'll take a look tomorrow.
