### ISSUE TITLE
stable and dev tutorials page is different (at release)

### ISSUE THREAD

**Issue by mmagnuski** [mne-tools/mne-python#3219]
I guess the tutorials page for 0.12 shouldn't look like [this](http://martinos.org/mne/stable/tutorials.html) (stable) but rather like [this](http://martinos.org/mne/dev/tutorials.html) (dev).

**Comment by Eric89GXL** [comment]
Indeed it should look like this:

http://mne-tools.github.io/stable/tutorials.html

@agramfort can you upload to Martinos?

**Comment by agramfort** [comment]
is it not fixed? can you refresh the page?

**Comment by mmagnuski** [comment]
Hm, works now. :)
