### ISSUE TITLE
ENH: FAQ filtering details

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#3227]
As mentioned in https://github.com/mne-tools/mne-sandbox/pull/7#issuecomment-218825443, it would be great to enhance the FAQ with some details on MNE's default filters, the reasons for having chosen them, and some recommendations we may have.

PR welcome ;)

**Comment by jona-sassenhagen** [comment]
I concur.

**Comment by jona-sassenhagen** [comment]
In before Alex says "are you volunteering?"

**Comment by Eric89GXL** [comment]
Cross-ref #1941 for papers
