### ISSUE TITLE
Epoching problem-CNT data

### ISSUE THREAD

**Issue by cfoodc** [mne-tools/mne-python#3232]
Hi all,

I encountered a problem on my CNT data.
After epoching, I found that data in several channels became all the same.
(in this case, channel index 1,3,5,7,11,13,15....etc, their values are identical)
I am not sure what's going on.

The ipynb and original CNT were attached.
It might be easier to reproduce the problem from the actual files. 
https://www.dropbox.com/s/gnbur10vizbsfqw/bug.zip?dl=0

Best,

CF

**Comment by cfoodc** [comment]
I just found there is a same problem during the raw data stage.
Several channels are just flat lines.

<img width="1895" alt="screen shot 2016-05-13 at 4 49 15 pm" src="https://cloud.githubusercontent.com/assets/16938414/15242855/f08f0edc-192a-11e6-914e-8c2df189607b.png">

**Comment by agramfort** [comment]
so is it a software problem or just a data problem? If so please close.
thx

**Comment by cfoodc** [comment]
I have tried to read the data with spm and eeglab, the data looks like normal.
So it might be a software problem.

**Comment by Eric89GXL** [comment]
@jaeilepp do you have time to look at this one?

**Comment by jaeilepp** [comment]
Taking a look now.

**Comment by jaeilepp** [comment]
Looks like the problem is that the data is in 32 bits instead of 16. The annoying thing is that this info is not included in the header, so I'll have to infer it from the data.
