### ISSUE TITLE
Elekta xfit dipole file reader

### ISSUE THREAD

**Issue by kambysese** [mne-tools/mne-python#3244]
@Eric89GXL it looks like the parsing of the xfit dipole file is prone to being botched likely due to how users decide to write out the `.dip` file (i.e. what fields to include). [Here](https://www.dropbox.com/s/hk3ez4512ml1168/All_157_RH.dip.txt?dl=0) is an e.g. dipole file; and the resulting `__dict__`

```
{'amplitude': array([  4.36000000e-08]),
 'gof': array([-5.8]),
 'name': None,
 'ori': array([[ 0.4587156 ,  0.16055046,  0.40825688]]),
 'pos': array([[ 0.0382,  0.0056,  0.0674]]),
 'times': array([ 0.363])}
```
`gof` and `amplitude` fields are off and I am not sure how the `ori` is being represented here.

**Comment by Eric89GXL** [comment]
I guess we'll have to modify the reading and writing functions to actually
deal with the header text :(
