### ISSUE TITLE
BUG: Download dir

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#3256]
We should default to `~/` somewhere, people during teaching are having problems with putting it in `examples/` by default.

**Comment by kingjr** [comment]
+10

**Comment by agramfort** [comment]
+11

**Comment by Eric89GXL** [comment]
How about `~/mne_data`? If that's acceptable I'll make a PR

**Comment by agramfort** [comment]
yes +1 for ~/mne_data like sklearn and nilearn do it
