### ISSUE TITLE
Can't import data from EEG-LAB

### ISSUE THREAD

**Issue by pbrusco** [mne-tools/mne-python#3264]
Hello, 

I'm having issues importing raw EEG data with mne.io.read_raw_eeglab(set_filename)

It seems to be related with the events on the file:

![eeglab-import](https://cloud.githubusercontent.com/assets/1205576/15614009/b474010e-240c-11e6-9798-3e775db81231.png)

I tried importing the data by hand and seems to be working. 

![eeg-lab-import-2](https://cloud.githubusercontent.com/assets/1205576/15614090/28c90694-240d-11e6-879c-fd9a81be6515.png)

Any ideas? 

mne.__version__
'0.12.0'

Thanks!

**Comment by jona-sassenhagen** [comment]
How was the EEGLAB .set file created?

**Comment by mmagnuski** [comment]
Some older eeglab files may have event type as integer. It is not allowed in current eeglab version (if I remember correctly). `eeg_checkset` (in matlab) should turn these to string.

**Comment by jona-sassenhagen** [comment]
This could be easily fixed by forcing events to be str, but I'm not sure we should support old EEGLAB version files. Any opinions?

**Comment by jasmainak** [comment]
is there a way to check what is the EEGLAB version from the `.set` file?

**Comment by Eric89GXL** [comment]
Casting to string seems fine to me, assuming the older files otherwise work. But maybe we should emit a warning about old files if we can get the version as @jasmainak asked

**Comment by jona-sassenhagen** [comment]
pbrusco can you make the file in question available somehow?

**Comment by pbrusco** [comment]
Thanks for the fast answers (I think the files are a little bit old, but not too much)

https://dl.dropboxusercontent.com/u/43547597/test1.set
https://dl.dropboxusercontent.com/u/43547597/test1.fdt

**Comment by jona-sassenhagen** [comment]
@jasmainak do you want to do it or should I?

**Comment by jasmainak** [comment]
@jona-sassenhagen feel free to take a stab at it. Thanks!

**Comment by pbrusco** [comment]
@jasmainak, in the mean time, do you recommend me to download the mne source code and just change cast events to string? Thanks :)

**Comment by jona-sassenhagen** [comment]
Sorry, I'll try and get something done today.

**Comment by jona-sassenhagen** [comment]
How do we go about testing for this? Probably don't want to add a new EEGLAB data file just for this.

@pbrusco in the meantime, I'd try loading and re-saving the file in a current version of EEGLAB.

**Comment by pbrusco** [comment]
@jona-sassenhagen Ok, good idea ;), thanks!

**Comment by jona-sassenhagen** [comment]
@pbrusco I think I don't understand your EEGLAB test file. It has only 1 trial?

**Comment by mmagnuski** [comment]
pbrusco was using `mne.io.read_raw_eeglab` so it is probably a raw file.

**Comment by jona-sassenhagen** [comment]
Haha I'm stupid.

**Comment by pbrusco** [comment]
Worked perfectly! Thanks a lot
