### ISSUE TITLE
Unused variable in test code

### ISSUE THREAD

**Issue by ARudiuk** [mne-tools/mne-python#3271]
The variable `evoked_nf_name` is declared in several testing modules, but is not actually used in any of them except for one from my search. Should it be removed from those files? What's the policy on unused variables?

**Comment by Eric89GXL** [comment]
Yes please get rid of them. We don't keep unused variables. Usually
pyflakes catches them but it can't for top-level variable creation.

**Comment by ARudiuk** [comment]
When the fork is merged into master should I close the issue. Like this one?

**Comment by agramfort** [comment]
yes. If you had written `closes #3271` is the PR description if would have been closed automatically.
