### ISSUE TITLE
ENH: Show source space (or source space points?) in `plot_trans`

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#3278]
Maybe for surface source spaces we should show the two hemispheres, and for volume grid or discrete, show the locations using `points3d` (or whatever the Mayavi call is). Or we could show the points in all cases. Perhaps I'll experiment. Could be relevant for what @kingjr is trying to work through.

**Comment by agramfort** [comment]
you have some mayavi code to show the source space sampling at:

http://martinos.org/mne/dev/auto_tutorials/plot_forward.html#compute-source-space

**Comment by Eric89GXL** [comment]
I think we might not need this now that we have improved `plot_bem`, but we can reopen later if necessary
