### ISSUE TITLE
BUG: write_surface doesn't write in same reference frame as read_surface

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#3281]
`write_surface` doesn't seem to write in the correct coordinates system. However, this is visible in freeviewer not in the mne `viz` functions.

To reproduce the error (you have to copy/paste `subjects/sample` into `subjects/sample_test` since it modifies the file in a bad way.)

```
import os.path as op
from mne.viz import plot_bem
from mne.datasets import sample
from mne.surface import read_surface, write_surface
data_path = sample.data_path()

# the raw file containing the channel location + types
raw_fname = data_path + '/MEG/sample/sample_audvis_raw.fif'
# The paths to freesurfer reconstructions
subjects_dir = data_path + '/subjects'
subject = 'sample_test'

fname = op.join(subjects_dir, subject, 'bem', 'inner_skull.surf')
coord, faces = read_surface(fname)
write_surface(fname, coord, faces)

plot_bem(subject=subject, subjects_dir=subjects_dir, orientation='coronal')
```

`plot_bem` plots as expected:

![write_surface_mne](https://cloud.githubusercontent.com/assets/4881164/15800612/e9fce31e-2a4b-11e6-92f7-a77934baaf8a.png)

but in freeview, we now see a misalignment:

![bug_write_surface](https://cloud.githubusercontent.com/assets/4881164/15800613/eb6503da-2a4b-11e6-960b-610c021acc1b.png)

**Comment by Eric89GXL** [comment]
Can you try using nibabel to read and write the surfaces to see if they
have the same problem?

**Comment by kingjr** [comment]
What is the nibabel function to read surfaces?

**Comment by Eric89GXL** [comment]
From Googling "nibabel read freesurfer surface":

http://nipy.org/nibabel/reference/nibabel.freesurfer.html#nibabel.freesurfer.io.read_geometry

**Comment by kingjr** [comment]
> From Googling "nibabel read freesurfer surface":

ouch.

Yes same error, I'll open an issue there.

**Comment by Eric89GXL** [comment]
We might have contributed the code there actually, not sure :) I'll try to
take a look Monday. I've seen something like this before, but assumed it
was a Freeview problem. I'm not aware of any coordinate frame information
on the file, and we just do simple read and write with no transformations,
so I'm not sure why it would happen.

The original (not yet overwritten) surface looks okay though, right?

**Comment by kingjr** [comment]
yes they look fine.
