### ISSUE TITLE
ENH: detect whether dev_t is the same across epochs before compute_covariance

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#3286]
In https://github.com/mne-tools/mne-python/issues/3283, I encountered a difficulty to find what was wrong with my sources. 

This was because the covariance was estimated from trials acquired in different run, and therefore with different `dev_head_t`. 

`compute_covariance` should probably throw a warning if the head alignment don't match.

cc @dengemann

**Comment by teonbrooks** [comment]
related to #2109 and #2122. realigning isn't as straightforward as one would think...

started down the road last year with @yousrabk but needed to retreat.

would be happy to see a solution ;)

**Comment by kingjr** [comment]
+1, but I think we should first start with a warning, that should be easy enough ("PR welcome")

**Comment by Eric89GXL** [comment]
Actually an error by default would be better. We can have an argument `misaligned='error' | 'warning'` for now and eventually add `misaligned='interpolate'`. Maybe there is a better name than `misaligned`, though.

**Comment by Eric89GXL** [comment]
I loosely plan to work on reconstruction (#3184) this summer, so I might be able to tackle the interpolation bit.
