### ISSUE TITLE
'predict_proba' is not an option in GeneralizationAcrossTime

### ISSUE THREAD

**Issue by romquentin** [mne-tools/mne-python#3299]
@kingjr 
When running this:
`gat = GeneralizationAcrossTime(clf=clf, scorer=scorer, n_jobs=-1, predict_mode='predict_proba')`
`gat.fit(epochs, y)`
`gat.score(epochs, y=y)`

It gives this error:
`ValueError: `predict_mode` must be a str, "mean-prediction" or"cross-validation"`

I have the last mne update. Did you remove the option?

Thanks

**Comment by jona-sassenhagen** [comment]
You're confusing predict_mode and predict_method. Check the docs again: http://martinos.org/mne/stable/generated/mne.decoding.GeneralizationAcrossTime.html#mne.decoding.GeneralizationAcrossTime

Admittedly, this is confusing nomenclature.

**Comment by romquentin** [comment]
Thanks. But now running this:
`gat = GeneralizationAcrossTime(clf=clf, scorer=scorer, n_jobs=-1, predict_method='predict_proba')`
gives this error:
`TypeError: __init__() got an unexpected keyword argument 'predict_method'`
What I am doing wrong?

**Comment by kingjr** [comment]
Which version of mne are you using?

**Comment by kingjr** [comment]
> Admittedly, this is confusing nomenclature.

Yes. I'll refactor the gat in the late summer. sklearn will soon accept `predict_proba` for its pipeline so we won't need this anymore.

**Comment by romquentin** [comment]
I cloned the last version but I guess something was wrong with the install. I reinstall with `pip install mne --upgrade`and it works. 
Thanks!
