### ISSUE TITLE
ENH: New modes for extract_label_time_course

### ISSUE THREAD

**Issue by nfoti** [mne-tools/mne-python#3326]
I'm proposing to added some new modes to the `SourceEstimate.extract_label_time_course` method and appreciate any feedback. Specifically, I would like to add `weighted-mean` and `weighted-mean-flip` modes that would compute a (flipped) weighted-mean for each label with weights given by the values of the label. This functionality would be useful for instance to weight the signals in each label proportional to their distance from the center of the label.

**Comment by Eric89GXL** [comment]
Sounds reasonable to me

**Comment by agramfort** [comment]
I see conceptually the reason but do you have some evidence that it's
actually useful / helpful on data?

**Comment by Eric89GXL** [comment]
@wronk has some evidence coming out any day now. But even without a
publication it seems useful for aiding simulation studies, no?

**Comment by agramfort** [comment]
well I am bit reluctant to add methods / options for our users unless it's really what we recommend to use. Let's try to limit confusion.

my 2c

so I did not say no but I'd like to be able to explain why we offer this option.

**Comment by nfoti** [comment]
I'm find tabling this issue for now. It just seemed like an easy way to add in a lot of flexibility that has come up recently for generating synthetic data.

**Comment by Eric89GXL** [comment]
Fine by me
