### ISSUE TITLE
AtrributeError while reading EEGLab data

### ISSUE THREAD

**Issue by pfaion** [mne-tools/mne-python#3347]
Hi,
I am trying to read in some data from EEGLab with the function
[mne.io.read_raw_eeglab()](https://martinos.org/mne/stable/generated/mne.io.read_raw_eeglab.html#mne.io.read_raw_eeglab)

but I get the error
**AttributeError: 'int' object has no attribute 'isdigit'**
[in line 541 of io/eeglab/eeglab.py](https://github.com/mne-tools/mne-python/blob/master/mne/io/eeglab/eeglab.py#L541)

Any ideas on this?

**Comment by jaeilepp** [comment]
Perhaps it needs to be cast to string on https://github.com/mne-tools/mne-python/blob/master/mne/io/eeglab/eeglab.py#L533 @mmagnuski @jona-sassenhagen ?
Just a stab in the dark...

**Comment by jona-sassenhagen** [comment]
Yeah, @pfaion is this with current MNE master?

**Comment by agramfort** [comment]
@pfaion if it's still broken with mne master please share a file

**Comment by jona-sassenhagen** [comment]
I think the line @jaeilepp links to would actually fail if you have a file created with an old version of EEGLAB with only a single event, so we need to fix either way.

But let's first see if this is the problem @pfaion has run into, or if there's another problem.

**Comment by pfaion** [comment]
Works with the current master. Sorry for any inconvenience...

**Comment by jona-sassenhagen** [comment]
It's good, it made me realize another error.
