### ISSUE TITLE
Broken fig background plotting

### ISSUE THREAD

**Issue by choldgraf** [mne-tools/mne-python#3361]
Just noticed in the docs - it looks like the background isn't plotting properly when setting a custom image with the `plot_topo` functions:

http://martinos.org/mne/dev/auto_examples/visualization/plot_clickable_image.html#sphx-glr-auto-examples-visualization-plot-clickable-image-py

Anyone know what caused this? If nothing obvious I'll look into it and try to fix.

**Comment by agramfort** [comment]
no idea

**Comment by jaeilepp** [comment]
This got fixed
