### ISSUE TITLE
Tutorial for migrating from Fieldtrip

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#3362]
We have a tutorial for EEGLAB users. We should have the same for Fieldtrip users, as Fieldtrip is I think the second-largest software platform (and IME a bit more popular amongst MEG people).

I can't do it, I've never really used Fiedltrip.

**Comment by jona-sassenhagen** [comment]
https://www.martinos.org/mne/stable/manual/migrating.html EEGLAB tutorial here.

**Comment by mmagnuski** [comment]
I've used FieldTrip mainly for time-frequency and cluster-correction, so I could try creating some examples of migration with respect to this. I wouldn't be able to do this soon however.
Currently the table for migrating from EEGlab should work well also for other migrations - one should just ignore the "EEGLAB function" column.

**Comment by mmagnuski** [comment]
Related: #3201

**Comment by Eric89GXL** [comment]
Closing for #1495
