### ISSUE TITLE
File specification for FIF

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-python#3369]
Is there a file specification sheet for the FIF file, that is, the listing of the data blocks, the sensor array, the metadata, etc. I have a colleague, @eh1255, who is interested writing a hardware export in FIF?

cc: @Eric89GXL @agramfort

**Comment by Eric89GXL** [comment]
http://www.aston.ac.uk/lhs/research/centres-facilities/brain-centre/facilities-clinical-services/meg-studies/downloads/

**Comment by eh1255** [comment]
Hi Eric,

Thanks for the quick response, I really appreciate it. This will help a lot!

Thanks,
Erik

**Comment by teonbrooks** [comment]
thanks @Eric89GXL!
