### ISSUE TITLE
BUG: simulate_evoked errors with finite SNR

### ISSUE THREAD

**Issue by nfoti** [mne-tools/mne-python#3370]
I am running into a problem where calling `simulate_evoked` with a finite and positive SNR results in an error. The forward solution I am using has 306 channels but only 305 channels of noise are simulated.

This [gist](https://gist.github.com/nfoti/22158db5eb67d447e24d2d07728189a5) demonstrates the problem.

**Comment by Eric89GXL** [comment]
Can you make that gist a minimal example? It will help isolate the problem to the fewest calls possible and thus be eaiser to fix

**Comment by jaeilepp** [comment]
The problem seem to lie in bad channels being dropped when computing covariance matrix, resulting in evoked and covariance instances having different set of channels. Maybe the correct fix would be just improving the error message and saying that some channels are not present in the covariance instance.
