### ISSUE TITLE
dev docs updated partially?

### ISSUE THREAD

**Issue by mmagnuski** [mne-tools/mne-python#3378]
In [this docs tutorial](http://martinos.org/mne/dev/auto_tutorials/plot_artifacts_correction_ica.html) the figure have been updated but the text not. The result is a little confusing :)

**Comment by mmagnuski** [comment]
If you download the tutorial as `.py` or `.ipynb` - you can see that the text is actually different than the one rendered.

**Comment by agramfort** [comment]
is it better now?

**Comment by mmagnuski** [comment]
It's better - but now it shows the version from before merging the PR that corrects for bad component inds.

**Comment by Eric89GXL** [comment]
It takes over an hour (plus queue time) to build the docs, so it's possible
your PR's changes were (or are) still pending. You can check the CircleCI
site to be sure.

**Comment by mmagnuski** [comment]
I checked circle and I could not see any unfinished "circles" [here](https://circleci.com/gh/mne-tools/mne-python) but the dev docs are still behind (although the circle artifacts for my PR were correct).

**Comment by Eric89GXL** [comment]
Someone will need to go through the CirceCI logs and cross check the
website repo to sort it out

**Comment by agramfort** [comment]
Is the pb on github.io or martinos.org ? If martinos I need to debug my rsync






On Sat, Jul 2, 2016 at 10:33 PM +0200, "Eric Larson" <notifications@github.com> wrote:










Someone will need to go through the CirceCI logs and cross check the

website repo to sort it out

**Comment by jaeilepp** [comment]
I think [mne-tools.github.io](http://mne-tools.github.io/dev/auto_tutorials/plot_artifacts_correction_ica.html) is up to date. [Martinos](http://martinos.org/mne/dev/auto_tutorials/plot_artifacts_correction_ica.html) has not yet been updated.

**Comment by agramfort** [comment]
rsync is telling me it's up to date with the master branch of github.io

**Comment by jaeilepp** [comment]
It looks like it's only partially updated (as the title here suggests). See the tag at the bottom of the page for the ica tutorial (Last updated on 2016-07-01) and the index (Last updated on 2016-07-02).

**Comment by agramfort** [comment]
should be fixed now.

**Comment by jaeilepp** [comment]
Looks good. Closing.
