### ISSUE TITLE
kwarg value error for compute_covariance

### ISSUE THREAD

**Issue by mdclarke** [mne-tools/mne-python#3388]
When using `compute_covariance(method=None)` I get a ValueError: Invalid method error. According to the doc string and error message "None" is a valid kwarg. I also tried 'None', but same error.

**Comment by jaeilepp** [comment]
Thanks for pointing this out. Fix coming up.

**Comment by agramfort** [comment]
@mdclarke fixed by #3392 in the mean time use method="empirical"
