### ISSUE TITLE
Is there an option for PSD calculations to use CUDA/CUFFT ?

### ISSUE THREAD

**Issue by JulesGM** [mne-tools/mne-python#3399]
It's all in the title. I've looked around, and it doesn't seem to be available; I just wanted to ask to make sure.

Thanks!

**Comment by Eric89GXL** [comment]
No not yet. Feel free to look at the ideas we've had about this sort of thing here, and comment there as well:

https://github.com/mne-tools/mne-python/issues/2722

**Comment by JulesGM** [comment]
thanks. I'll start by using cufft, and see if I get any speedups. will return with updates.
