### ISSUE TITLE
Message box for coregistration gui

### ISSUE THREAD

**Issue by jaeilepp** [mne-tools/mne-python#3405]
See https://github.com/mne-tools/mne-python/pull/3332#issuecomment-230987891
So my suggestion is to pop up a message box (I'm not sure if it's trivial with traits) when none of the subjects have a bem ready. Now the subject box is just left unpopulated which led me to think that there is something wrong with the subjects_dir path or the coreg-gui itself.

**Comment by christianbrodbeck** [comment]
If it's just a message box that would be simple, I could include that in #3332

**Comment by jaeilepp** [comment]
Yeah, IMO that would be enough.

**Comment by christianbrodbeck** [comment]
So the message should just suggest to run mne `$ mne make_scalp_surfaces`?

**Comment by Eric89GXL** [comment]
I think this is done
