### ISSUE TITLE
plot_trans only works for head.fif surface.

### ISSUE THREAD

**Issue by jaeilepp** [mne-tools/mne-python#3406]
AFAIK we could also use outer_skin.surf to plot the head surface.

**Comment by agramfort** [comment]
you suggest to try to find outer_skin.surf is head.fif is not present?

**Comment by jaeilepp** [comment]
Yes. Or allow to pass a param or smth.

**Comment by agramfort** [comment]
I prefer to detect it automatically and do not add a parameter. It's fine
with me as it's not doing any computation nore creating new files.

**Comment by christianbrodbeck** [comment]
We should also use high res head shapes if they are present?

**Comment by Eric89GXL** [comment]
We can modify `head` parameter from `True` (current behavior, use head.fif) to other things like `'best'` or something. @jaeilepp you want to do it, or should I?

**Comment by jaeilepp** [comment]
I'll take a look.
