### ISSUE TITLE
Tutorial on EEG average ref

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#3410]
A question popped up on the mailing list and highlights the fact that EEG average reference is a bit opaque (e.g. the non conventional term 'projection', or 'proj' are used throughout the API, the defaults are not clear etc).

This issue was clearly answered by @wmvanvliet, but we may want to add a tutorial to clarify this issue, remind users that bad channels must be removed first, etc

**Comment by agramfort** [comment]
agreed

**Comment by dengemann** [comment]
+1 yes this is a recurrent one.
