### ISSUE TITLE
ENH: Alternative references / Reference free EEG

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#3412]
MNE has the most common ways of re-referencing EEG: channel(s) and average. But there is also a range of attempts to create a "reference-free" reference, such as

http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2953588/
http://www.ncbi.nlm.nih.gov/pubmed/11761077
http://math.bu.edu/people/mak/Lepage_J_Neurosci_Meth_2014.pdf

Might be cool to have some of these. @wmvanvliet maybe you feel like doing some of these.

**Comment by larsoner** [comment]
Closing as YAGNI but if someone wants to discuss further feel free to reopen
