### ISSUE TITLE
copy params

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#3426]
A few functions have copy params - for example, [set_eeg_reference](https://github.com/mne-tools/mne-python/blob/93e369654c2b0f881d433ac4a80c00ff3121a964/mne/io/reference.py#L124). Shouldn't these be deprecated in favour of using `inst.copy()`?

@Eric89GXL @dengemann

**Comment by Eric89GXL** [comment]
The policy we settled on is that methods should work in place and not copy,
functions should copy by default but have an option to work in place

**Comment by jona-sassenhagen** [comment]
Ah ok
