### ISSUE TITLE
ENH: EMS with sklearn object?

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#3427]
@kaichogami there is a function `mne.decoding.ems.compute_ems` which could be implemented as an sklearn object to get a simple API.

Although the function looks awfully simple (it's a normalized differential response? Or I'm missing something). 

@dengemann Do you have an opinion on this?

**Comment by agramfort** [comment]
+1 for sklearn API object for EMS

**Comment by dengemann** [comment]
Would be neat to have such an object. But priority is low at this point

**Comment by jona-sassenhagen** [comment]
Do people use this much? (Just as an estimate for priorities.) My intuition would be like @dengemann 's

**Comment by agramfort** [comment]
low priority I agree but maybe we should document it better to attract more
users of this...

**Comment by jona-sassenhagen** [comment]
Couldn't it be reconstructed by relying on e.g. sklearn's LOO cv? Building on standard tools rather than a custom implementation with a novel API?

**Comment by agramfort** [comment]
yes probably...
