### ISSUE TITLE
Stickers?

### ISSUE THREAD

**Issue by choldgraf** [mne-tools/mne-python#3441]
For a totally non-coding-related question:

I just got back from Scipy and there were so many cool stickers there for the various open-source projects in the scientific python ecosystem. Now, I'm not usually a "fill my laptop with stickers" kinda guy, but the scipy folks guilt tripped me into putting on a few of them.

Now that MNE has a fancy shmancy logo with nice colors and such, did anybody happen to make stickers for it? Imagine, your computer could one day look like this!

![image](https://cloud.githubusercontent.com/assets/1839645/16968769/920df40a-4dd6-11e6-9a15-6e08ca96ed5d.png)

**Comment by agramfort** [comment]
:)

**Comment by kingjr** [comment]
lol #PhotoshopSkills

**Comment by teonbrooks** [comment]
would be cool if our logo had an optional, transparent background. that would make for better printed decals.

**Comment by Eric89GXL** [comment]
I'm pretty sure @drammock included scripts with the logo when he made it so you should be able to recreate it, but it's already an SVG somewhere so changing the background color in something like Inkscape should hopefully be trivial

**Comment by teonbrooks** [comment]
cf. https://github.com/mne-tools/mne-python/pull/2395

I tried it a while back but I'm missing a font in mpl and that was a rabbit hole I couldn't go down. nevertheless, it still rendered

**Comment by choldgraf** [comment]
Printing a clear MNE logo was pretty easy for me. Just modify the script to save to .svg and delete the background in Illustrator/whatever (or you might be able to just sit the background patch `visible` parameter to false in matplotlib). E.g.:

![mne_logo_03](https://cloud.githubusercontent.com/assets/1839645/17003391/5bfe0494-4e95-11e6-969e-2b898cc38b7e.png)

FWIW, all the other folks seemed to be using stickermule for their stickers. Would probably just be a matter of pooling together some cash to pay for 'em.

**Comment by jona-sassenhagen** [comment]
That's actually the first time Donald Trump has "worked" for me.

If his job was running around and selling people on MNE, ... I think he'd be well suited to that.

**Comment by Eric89GXL** [comment]
There is something wrong with that one... I think it's the wrong font perhaps

**Comment by jona-sassenhagen** [comment]
The way the gradient works, it makes Trump's cheeks look really hamsterish.

**Comment by agramfort** [comment]
just make a proper one and I'll find the cash :)

**Comment by choldgraf** [comment]
i actually do think my computer is missing a font as well (probably the same problem @teonbrooks ran into). I think it's pretty easy to add the font to MPL if I can find the TTL file somewhere.

BTW, where is that logo-generating script these days? I had to find it in a link that somebody sent in an old PR, but I couldn't find it in the main codebase

**Comment by choldgraf** [comment]
Does this look correct?

![mne_logo_03](https://cloud.githubusercontent.com/assets/1839645/17009850/5294dcbe-4ec4-11e6-9ee9-6be0c36afc3e.png)

**Comment by Eric89GXL** [comment]
That would looks a bit stretched, it should look like it does on the MNE-Python website:
![Logo](http://mne-tools.github.io/stable/_static/mne_logo.png)

**Comment by choldgraf** [comment]
Hmm, well I'm using the script that was linked here:

https://github.com/mne-tools/mne-python/blob/d42a711f5184f64a251398bc39834cf46ac60d17/doc/generate_mne_logos.py

Only changing the output to `svg` instead of `png`. There there system /
software requirements for that script to work properly? Or is there an
updated version somewhere? It looks like it's not in master at that
location.

**Comment by Eric89GXL** [comment]
I just generated this (on Windows even!) after:

1. installing [Primetime TTF] (http://www.dafont.com/primetime.font) and [Cooper Hewitt OTF] (https://www.cooperhewitt.org/wp-content/uploads/fonts/CooperHewitt-OTF-public.zip)
2. Removing `~/.matplotlib/fontList.cache` to force it to rebuild my cache
3. Removing `op.join`s in the writing (since I was running it from out of place)

and got the correct logo in PNG:

![mne_logo](https://cloud.githubusercontent.com/assets/2365790/17010906/926787f0-4ec5-11e6-9149-2193a4a2bd8d.png)

When modifying to save as SVG, I get the same output when I view it in Chrome (but can't attach here because GitHub doesn't support it).

Maybe you are getting matplotilb warnings about not finding the correct fonts when you run it?

I have no idea why that script is missing from `master`, I see it in the commit log, then it disappears at the next `master` commit for some reason.

**Comment by Eric89GXL** [comment]
Oh actually the script is here (hah!):

https://github.com/mne-tools/mne-python/blob/master/logo/generate_mne_logos.py

**Comment by Eric89GXL** [comment]
(found using http://stackoverflow.com/questions/6839398/find-when-a-file-was-deleted-in-git)

**Comment by drammock** [comment]
Sorry to chime in so late.  @Eric89GXL is right, the script needs a couple of uncommon (though free) fonts to work properly.  Here's an SVG version:

http://dan.mccloy.info/data/mne-logo.svg
-- dan

**Comment by choldgraf** [comment]
Huh, I wonder why it's appearing stretched on my computer. I'm not getting any font errors but it still looks slightly vertically stretched (using the version that is in the `logo` folder, which I stupidly missed before)

**Comment by choldgraf** [comment]
Though either way it sounds like the SVG @drammock linked is all we need. Here's a PNG version w/o a background:

![mne-logo_03](https://cloud.githubusercontent.com/assets/1839645/17040422/249e4bd2-4f65-11e6-95eb-227f5a149ded.png)

It looked like this is what the other folks at scipy were using:

https://www.stickermule.com/products/die-cut-stickers

**Comment by drammock** [comment]
@all please note that the Primetime font used for the letters MNE is "free
for personal use only" so the stickers should not be used for fundraising /
profit.  The tagline font (Cooper Hewitt) is under a SIL Open Font Licence.

@choldgraf I've often noticed that matplotlib is inconsistent on when /
whether its missing font warnings make it through to stdout, so I wouldn't
be surprised if on your system it's failing to find Primetime and falling
back silently to DejaVu Sans.

**Comment by choldgraf** [comment]
Yeah I'm not sure what's up with matplotlib. I was getting font errors before, but I found/downloaded the ttl files for those fonts and now I'm not getting the errors. Comparing the PNG I showed above vs. the correct ones below it, the fonts look pretty much the same, so I'm not sure what's going on

**Comment by Eric89GXL** [comment]
@agramfort WDYT about making a handful of these to keep with our poster at BioMag?

**Comment by choldgraf** [comment]
I can bring some to SfN as well if they're made before then. If you want to ship some to NYC then I can pick them up there (I'll be there in October)

**Comment by agramfort** [comment]
@yousrabk @jasmainak can you maybe take care of this? I will pay and manage to get reimbursed afterwards

**Comment by jasmainak** [comment]
@agramfort how many and what size? is 2" x 2" the size that is typical size?

**Comment by choldgraf** [comment]
@jasmainak for reference, the two stickers in the dopey-looking picture of me at the top of this thread are 3" x 1" and 3" x 1.5", respectively. I think it's good to have at least some in that size since it's the common laptop sticker size.

**Comment by agramfort** [comment]
I would make about 150. wdyt?

fine with 3" x 1.5"

**Comment by jasmainak** [comment]
okay we might have some stickers by 23rd sept ;)

**Comment by dengemann** [comment]
LOL .... If someone would have told me 4 years ago that one day we'd be
discussing stickers on github. Good stuff!

**Comment by jasmainak** [comment]
are we happy with this?
![mockup](https://cloud.githubusercontent.com/assets/15852194/18413816/138279fe-77b5-11e6-82bb-d35fd20178c1.png)
It's going to be 3" x 1.3542". Speak up now if you have any reservations! Otherwise I'll approve it tomorrow morning.

**Comment by dengemann** [comment]
It reminds me of Nintendo game cartridges from the early 90's .... Awesome!

**Comment by Eric89GXL** [comment]
Awesome

**Comment by jasmainak** [comment]
okay since I got two +1s, I'm going to approve it now :)

**Comment by choldgraf** [comment]
Do you think you could get it at 1.3543" instead?

**Comment by jasmainak** [comment]
I rather like the trailing 42 ;)

**Comment by choldgraf** [comment]
haha, shame on me for not seeing the answer to the universe when it's staring me in the face

**Comment by kingjr** [comment]
nice

**Comment by jasmainak** [comment]
closed by https://twitter.com/mainakjas/status/778153289150062593

**Comment by Eric89GXL** [comment]
Nice, closing via tweet. Next issue we should closing via vine

**Comment by teonbrooks** [comment]
So I was just informed that our stickers do not conform to cool kids standards. Apparently [hexagonal stickers](www.hexb.in) are in. Should we do stickers 2.0?

**Comment by choldgraf** [comment]
omg hexagons are so 2016, I hear octagons are the new way to go. So I propose being even more cutting edge and going with a dodecahedron.

**Comment by kingjr** [comment]
ha!

**Comment by Eric89GXL** [comment]
Shall we reformulate as a hexagon? We could do it in time for the March sprint

**Comment by choldgraf** [comment]
fine w/ me, shouldn't be too expensive or time consuming. Maybe I can get BIDS to pay for some.

also this one is great

![image](https://cloud.githubusercontent.com/assets/1839645/22752720/708f0888-edee-11e6-82f2-3af51c4951be.png)

**Comment by dengemann** [comment]
icosahedron!

**Comment by jasmainak** [comment]
if you order again through stickermule, let me know. I might have a discount code lying around somewhere. Not sure though ...

**Comment by teonbrooks** [comment]
hexagon! hexagon! @bmpvieira, you started something ;)

**Comment by drammock** [comment]
Here you go, everyone: https://gist.github.com/drammock/2020b5111135bafb71ce6b5d8488495f

**Comment by Eric89GXL** [comment]
Hah, great!

**Comment by choldgraf** [comment]
I like it! I am a little concerned that the text underneath will be hard to read. Have you played around with making the font a bit stronger? Maybe it's fine when printed tho...

**Comment by drammock** [comment]
@choldgraf no I didn't...  I was imagining a larger size, but I just checked back and discovered the [sticker constructor spec](https://github.com/terinjokes/StickerConstructorSpec).  Will revise and update with those dimensions in mind.

**Comment by choldgraf** [comment]
cool - I think that is quite close though :) we should also make sure that
having the lettering so near the edges of the hexagon won't mean that it
gets cut off or overwritten by a line or something
--

**Comment by drammock** [comment]
@choldgraf [the gist](https://gist.github.com/drammock/2020b5111135bafb71ce6b5d8488495f) has been updated to

1. conform to constructor spec
2. pull wordmark in from edge of hexagon a bit
3. boldify tagline

Send some to Seattle when they're ready!

**Comment by choldgraf** [comment]
has anyone here printed hexagonal stickers before? I looked at the main company that website suggests and it isn't clear since I don't read japanese (also...the website header is very japanese and it's kind of great)

![image](https://cloud.githubusercontent.com/assets/1839645/22954574/1ecb0bea-f2cc-11e6-839a-74dbb0731e4d.png)

**Comment by Eric89GXL** [comment]
Nope, no idea about where to do it

**Comment by choldgraf** [comment]
just FYI I ordered about 60 of these, will bring 'em to NYC

**Comment by teonbrooks** [comment]
@choldgraf how did it turn out, layout-wise?

**Comment by choldgraf** [comment]
it looked like a hexagon, in the end ;-)

**Comment by choldgraf** [comment]
jk, here's the proof: https://www.stickermule.com/artworks/954501?token=7aba51b4d5450dc7314b320219c276b6

**Comment by choldgraf** [comment]
![](https://lh3.googleusercontent.com/Eg3Sesj49strnjjpe-SPV2uN41UiPZQy68yxe_2jYcmFnymJE6HkprZXE82qwN1EbrsbRXgpUtshE_9OEhkyadrnoONnoYPg_9uOPpdmXoHELJ_oerZ7PlPEaM1NtU93Fmjcwscd7F_gjrRT28GhKWgpfjjS_l0i-Ur1w5TRt6vxcWRWjabwqf16RRCs9JGdcQo-iBGOeJfncbKtaFJTjtC5bbmBOUUrm3MkBPDu-3x0rMzTclOlS4AOIRtsK58HgW6_4GTJOfYTEvGhfEI_Y7dUFyzIn9sH16vZQV9rCSJg4eTAP9OTOarH_HtIBJ-QJ2Pf8ScEP9sUsfZW4gBAi5haQ8ThFjxs5kPweDoAsQk5zAMmnDNH3k4eAYilZ4YWYTgM47NdyXLv61fSYolahZX-_G473049sW_8kFhkWPHT5FS9Oo9dO_k4AuTio3v2jPIgMnokymwY6G8efOGXt9Iccwz5rR-il4tWKzPKRybbykoUIjgfEYCM2l5BccgEUOLM3urXtJz-t10Nofqqgwk1YDjK2sfNBP9tdXpcHv1xDkrzsPY50Wcog4qLKYvK97qmjt0sRmgo5sfOAQpqTcvq0tXSsZ_x1RxjxE2etCxvEYp6pg_HDw=w878-h1168-no)

**Comment by choldgraf** [comment]
I'll bring 'em to NYC :)
