### ISSUE TITLE
ica.plot_overlay - red and black lines are now mixed

### ISSUE THREAD

**Issue by mmagnuski** [mne-tools/mne-python#3451]
[`plot_overlay` mixes red and black lines](http://www.martinos.org/mne/dev/_images/sphx_glr_plot_artifacts_correction_ica_010.png) because `mne.viz.evoked._plot_evoked` uses `z_order` param now and the default 'unsorted' value gives different z-order to each line. When two evokeds are plotted successively (before ICA - red; after ICA - black) this causes the lines to mix.
Potential solutions:
* `_plot_evoked` could expose another z_order option ('no', 'none', same', 'flat'?) that does not set line z-order
* `_plot_evoked` 'unsorted' z_order could lead to not changing z-order at all
* `ica.plot_overlay` could use the option to pass a callable to z_order where the callable would just return `np.ones(n_channels)`

I think the first and second solutions are more general and thus better.

**Comment by jona-sassenhagen** [comment]
In https://github.com/mne-tools/mne-python/blob/master/mne/viz/evoked.py#L348

`zorder=z+1 if spatial_colors else 1`

?

**Comment by mmagnuski** [comment]
@jona-sassenhagen even better :)

**Comment by agramfort** [comment]
PR welcome
