### ISSUE TITLE
FIX: raise explicit error for concatenate epochs with different dev_head_t

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#3458]
Related to https://github.com/mne-tools/mne-python/pull/3313.

Concatenating epochs with different 'dev_head_t' throws an error, with may look a bit mysterious for those users who don't know what this info means.

**Comment by Eric89GXL** [comment]
Do you have time for a PR? Sometimes it's almost a quick as opening an
issue :)

**Comment by kingjr** [comment]
My experience sofar is that it's PR opening is a bit like a pandora box :/

**Comment by Eric89GXL** [comment]
This one should be pretty straightforward (unlike the decoding ones) but I
can do it later if you're not going to
