### ISSUE TITLE
Transform docs and API

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#3465]
There should be
- good documentation
- accessible functions

for transforming between the various coordinate systems, e.g. volume to source, sensor to RAS, etc.

@Eric89GXL @christianbrodbeck

**Comment by Eric89GXL** [comment]
And also the relationship between high-density cortical meshes (i.e., what FreeSurfer gives us) across different subjects and source spaces (decimated versions of those).

**Comment by Eric89GXL** [comment]
Currently the best "documentation" of these is in the `setup_volume_source_space` function because most of these transforms needed to be used there. There is also a little bit in the `SourceEstimate` class IIRC having to do with getting to Talairach.

**Comment by christianbrodbeck** [comment]
Related to this, a few weeks ago I wrote a function to coregister head to MRI programmatically based only on the three fiducials, I don't know if it's desirable to include but if it is I can make a PR

**Comment by jona-sassenhagen** [comment]
Jesus H. Christ yes. That's precisely what I need. How soon can you PR? :)

**Comment by christianbrodbeck** [comment]
It's in #3466

**Comment by Eric89GXL** [comment]
I added these doc things to #1495, closing
