### ISSUE TITLE
ENH: manual edition of annotations & channels

### ISSUE THREAD

**Issue by deep-introspection** [mne-tools/mne-python#3467]
Hi there,

it could be nice to manually (add/delete/modify) annotations and (status/type) of channels.
On top of being convenient, it would also help many people transitioning to MNE Python.

The MNE annotations seem to quite suit the job for the former part, but such feature would maybe require to expand the GUI of the interactive plot or build something dedicated.

Did you already thought about something like that? Are people working on it?

Cheers!
Guillaume

**Comment by agramfort** [comment]
yes allowing to create and modify in the raw data browser is planned

**Comment by deep-introspection** [comment]
Cool! How can I help?

**Comment by agramfort** [comment]
hack the raw matplotlib plotting code :)

**Comment by agramfort** [comment]
and submit a clean PR :)
