### ISSUE TITLE
DOC: Clarify how to use Annotations

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#3468]
An issue on the listserv recently brought up how to reject epochs that have a certain event in them. This would be a great simple (~20 line?) example that should go in the docstring for Annotations:

http://martinos.org/mne/dev/generated/mne.Annotations.html#mne.Annotations

Also, there is currently no mention of how the annotation events should be named to get epochs to be rejected.

@jaeilepp can you add something?

**Comment by agramfort** [comment]
+1

**Comment by jaeilepp** [comment]
Crap. Can't believe I forgot to add that. Maybe I can take a quick look in the evening or tomorrow morning.
