### ISSUE TITLE
Savitzky-Golay filter

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#347]
add support of the Savitzky-Golay filter

see : https://github.com/scipy/scipy/pull/304

and : 

http://inst.eecs.berkeley.edu/~ee123/fa12/docs/SGFilter.pdf

could be used to filter Evoked and Epochs.

**Comment by Eric89GXL** [comment]
I guess we haven't needed this for two years... do you think we still need it @agramfort?

**Comment by agramfort** [comment]
it's in scipy now.

we need to integrate it.

it can be convenient to smooth the evoked data late in the pipeline

**Comment by Eric89GXL** [comment]
you want it for 0.9? it seems like it *should* be pretty straightforward

**Comment by agramfort** [comment]
let's focus on open PR

conversion between frequency params and sav gol params is maybe not that
trivial.

**Comment by Eric89GXL** [comment]
I wrote a gist suggesting that using a 5th-order polynomial with a window length twice as large as the wavelength of the freq of interest should work okay:

https://gist.github.com/Eric89GXL/bbac101d50176611136b

Plotting the original spectra (yellow) and post-savgol spectra for different filter orders (left labels) and requested "lowpass frequencies" (bottom labels), with the -20 dB point in horizontal dashed line and requested freq in dotted vertical line:

![figure_1](https://cloud.githubusercontent.com/assets/2365790/6629911/3ebfae9c-c8d0-11e4-9255-f6e34ec342bd.png)
