### ISSUE TITLE
ENH: Filterer for decoding

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#3471]
@kaichogami 

We need to create a `mne.decoding.Filterer` object that takes `low'`, `high`, `sfreq` ... params, deals with 3D numpy array (n_epochs, n_chans, n_times) and transform the data with low/high/band pass filters.

It would be great to add a time_padding option to add zeros before and after tmin and tmax, so as to minimize edge artefact.

We'll eventually deprecate `FilterEstimator` in one or two deprecation cycles, as it uses `info` as param.

**Comment by Eric89GXL** [comment]
Keep in mind the IIR and FIR both already do (different forms of) padding

**Comment by kingjr** [comment]
@Eric89GXL Ok thanks. How about the time frequency transform ?

**Comment by Eric89GXL** [comment]
I can't remember, you'll have to look at the code

**Comment by kingjr** [comment]
PR in #3472

**Comment by kaichogami** [comment]
This can be closed now.
