### ISSUE TITLE
ENH: CSP multiclass uwedge implementation + examples

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#3495]
As discussed in https://github.com/mne-tools/mne-python/pull/3485, the current multi class CSP is quite slow for high dimensions; uwedge should be faster, although probably less good.

Additionally the CSP examples need a lifting and an additional example is necessary for > 2 class problems.

**Comment by larsoner** [comment]
I'm going to close this and hope that it lands (or has landed) in pyriemann
