### ISSUE TITLE
LinAlgError: SVD did not converge

### ISSUE THREAD

**Issue by mdclarke** [mne-tools/mne-python#3499]
@Eric89GXL 

Im getting LinAlgError: SVD did not converge errors now on files I didn't before when running maxwell_filter. Tried changed the st_duration, but nothing works. Any ideas?

**Comment by Eric89GXL** [comment]
Argh, we have to wait for Intel to release a real (proper) fix for this. In the meantime you can try updating to SciPy 0.18. Of course that isn't compatible with a Mayavi installation (it will break it), so you might have to have two environments, one that you use with SciPy 0.18 to work around this error, and another that you use for Mayavi.

**Comment by mdclarke** [comment]
OK thanks. Any ideas when Intel will fix this? :)

**Comment by Eric89GXL** [comment]
No idea. Feel free to look here for more info, though:

https://software.intel.com/en-us/forums/intel-distribution-for-python/topic/628049
