### ISSUE TITLE
BUG: Need two key presses in raw plot

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#3512]
When I plot my raw EEG with `raw.plot()`, the keyboard controls do not work as expected. For example, to scroll one page to the right I press the right arrow key. Nothing happens - I need to press another key until the plot gets updated and shows the next page. I've tested this on Mac OS X with the latest Anaconda distribution in IPython (with and without `%matplotlib`).

Update: I actually have to press Shift in order to confirm the left/right key presses. Other keys don't seem to work.

**Comment by mmagnuski** [comment]
I'm not on a mac but heard from other people that they are also experiencing this problem.

**Comment by Eric89GXL** [comment]
@cbrnr is this still a problem with latest `matplotlib`? Have you tried different backends, e.g. MaxOSX vs pyqt4 / pyqt5?

**Comment by cbrnr** [comment]
You're right, this seems to be specific to the `macosx` backend. Everything works fine with `Qt5Agg`.

**Comment by Eric89GXL** [comment]
Okay, closing as upstream bug. @cbrnr if you have time, can you add an entry to `doc/faq.rst` about OSX `matplotlib` backends?

**Comment by cbrnr** [comment]
OK sure! Although I'd appreciate it if someone else reproduced this behavior first - not that it is just me and my specific setup...

**Comment by Eric89GXL** [comment]
It sounds like @mmagnuski knows you're not alone in this. Hopefully the MPL people fix it soon.

**Comment by cbrnr** [comment]
Is there a corresponding upstream issue?

**Comment by Eric89GXL** [comment]
I'm not entirely sure, maybe one of these (with a possible fix)?

https://github.com/mne-tools/mne-python/issues/2450
https://github.com/matplotlib/matplotlib/pull/6178

Feel free to look further. If there isn't a good one, feel free to make a minimal example for them

**Comment by Eric89GXL** [comment]
Ignore that first link, bad copy-paste. But the MPL PR does have some linked issues IIRC

**Comment by cbrnr** [comment]
Thanks - I'll see if this issue fits in there. I wouldn't want to forget about it though, because I assume that many MNE users work on a Mac. Maybe MNE should tell them to switch to the Qt5Agg backend when they start up the viewer?
