### ISSUE TITLE
issues with animate_topomap in interactive mode

### ISSUE THREAD

**Issue by mmagnuski** [mne-tools/mne-python#3515]
using `animate_topomap matplotlib` when in interactive mode (`%matplotlib`) does not work very well (at least on windows):
- "Initializing animation..." is printed every time the animation goes back to the beginning - and the whole animation seems to be recomputed from scratch (I need to wait for a few seconds before it restarts)
- clicking the topo does not stop the progression of time - only turns off redrawing. If I click the topo, and wait a few seconds, and then click again - the animation is a number of frames ahead (proportional to the time being paused)

**Comment by agramfort** [comment]
In a notebook?






On Sat, Aug 13, 2016 at 3:26 AM +0200, "Mikolaj Magnuski" <notifications@github.com> wrote:












using animate_topomap matplotlib when in interactive mode (%matplotlib) does not work very well (at least on windows):


"Initializing animation..." is printed every time the animation goes back to the beginning - and the whole animation seems to be recomputed from scratch (I need to wait for a few seconds before it restarts)
clicking the topo does not stop the progression of time - only turns off redrawing. If I click the topo, and wait a few seconds, and then click again - the animation is a number of frames ahead (proportional to the time being paused

**Comment by mmagnuski** [comment]
In Spyder, but I can check the notebook.

**Comment by agramfort** [comment]
ok it's bad then. @jaeilepp please look when you're back

**Comment by Eric89GXL** [comment]
@mmagnuski do you still experience this? I suspect it could just be a transient `matplotlib` bug.

**Comment by larsoner** [comment]
Closing since last I checked it worked okay, so probably an old mpl bug
