### ISSUE TITLE
Morph subjects dipoles onto standard brain

### ISSUE THREAD

**Issue by tcford** [mne-tools/mne-python#3521]
To plot each subjects left and right auditory dipole, on the same brain, with the groups differentiated by colour (e.g. blue for group1 and red for group2).

**Comment by Eric89GXL** [comment]
I think this is probably a duplicate of #2995, @tcford can you see if your use case would be supported by what is discussed there? If not, please add to that discussion what you'd like to see.

**Comment by tcford** [comment]
Hi Eric,

Yes, sorry! I was prompted to add the issue by Alex- this looks similar though.
I’ll stay tuned.

Thank you,
Talitha
On 16 Aug 2016, at 10:28, Eric Larson <notifications@github.com<mailto:notifications@github.com>> wrote:


I think this is probably a duplicate of #2995<https://github.com/mne-tools/mne-python/issues/2995>, @tcford<https://github.com/tcford> can you see if your use case would be supported by what is discussed there? If not, please add to that discussion what you'd like to see.

**Comment by Eric89GXL** [comment]
That's fine, duplicate issues are easy :)
