### ISSUE TITLE
python 2.6 and nibabel - how about dropping python 2.6?

### ISSUE THREAD

**Issue by mmagnuski** [mne-tools/mne-python#3529]
Travis is failing on python 2.6 due to zero length field name in format [here - in nibabel]( https://github.com/nipy/nibabel/blob/master/nibabel/deprecator.py#L149).
Nibabel does not support python 2.6 - maybe it's time to drop support of python 2.6 in mne too? :)

**Comment by Eric89GXL** [comment]
@agramfort okay with this yet? +1 from me

**Comment by agramfort** [comment]
Ok fine with me 






On Tue, Aug 23, 2016 at 10:08 PM +0200, "Eric Larson" <notifications@github.com> wrote:












@agramfort okay with this yet? +1 from me

**Comment by dengemann** [comment]
Also ok with me.

**Comment by Eric89GXL** [comment]
Can we bump minimum `numpy` to 1.8 (as SciPy is doing currently)? We could also do SciPy to 0.13, MPL to 1.3, sklearn to 0.14, and pandas to 0.13 to mirror Ubuntu 14.04.
