### ISSUE TITLE
Update sample data evokeds names

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#3537]
It seems the sample data evokeds currently have as names: "Left Auditory", "Right Auditory", "Left visual", "Right visual"
Any chance of changing that to "Left/Auditory", "Right/Auditory", "Left/Visual", "Right/Visual"?

**Comment by Eric89GXL** [comment]
People's scripts likely make use of existing names in this (long time)
publicly available dataset so we probably should not change them

**Comment by jona-sassenhagen** [comment]
Ok!
