### ISSUE TITLE
MNE Python for fNIRS?

### ISSUE THREAD

**Issue by mcaffini** [mne-tools/mne-python#3539]
Hi all,

I successfully tested some of the **MNE Python** methods and classes in my **fNIRS** data processing workflow.
I wonder if anyone else is interested in this and whether it's worth to write some code in this direction. I can also swallow the bitter pill and keep labeling my fNIRS data as "eeg", but maybe we could seize the day to start something useful. Happy to share more of what I did if needed.

Let's discuss it! :-)

**Comment by Eric89GXL** [comment]
I see no problem with asking to add a fNIRS channel type to the FIF tags and making the appropriate adjustments in our code. @agramfort @jaeilepp do you agree?

**Comment by Eric89GXL** [comment]
@mcaffini do you have some small data file that you can share? What format is it?

**Comment by jaeilepp** [comment]
Sure, why not.

**Comment by Eric89GXL** [comment]
Can you ask the Neuromag folks?

**Comment by agramfort** [comment]
fine with me.

**Comment by mcaffini** [comment]
Dear all, sorry for the late reply.
@Eric89GXL I use the ISS Imagent. fNIRS raw data come from different technologies (continuous wave, frequency domain, time domain) and each instruments has its own format, but they all eventually get transformed into oxyhemoglobin (HbO) and deoxyhemoglobin (HbR) concentrations (this transformation process is different for different technologies). Maybe we skip this step and we directly start from a numpy array containing the concentrations? This way we would only need two tags like fNIRS-HbO and fNIRS-HbR...

**Comment by jaeilepp** [comment]
> Maybe we skip this step and we directly start from a numpy array containing the concentrations?

Sounds reasonable. We probably don't want to provide the 'preprocessing' steps for this transformation anyway.

**Comment by jaeilepp** [comment]
Actually, it sounds like we would need a tag for fNIRS channel type and for two units (HbO and HbR). Am I right?

**Comment by mcaffini** [comment]
What do you mean with unit? If you have in mind each channel having two independent tracks/signals (HbO and HbR), that sounds good!

**Comment by Eric89GXL** [comment]
Physical units, preferably of the SI variety -- for EEG it's V (commonly viewes as uV) and for MEG it's T and T/m (more commonly viewed as fT / fT/cm).

**Comment by mcaffini** [comment]
OK, then for fNIRS is molar concentration (M=mol/l=mol/dm3, usually as μM, proper SI unit would be mol/m3). Each channel gives two independent signals (HbO and HbR) with the same unit (μM). How do we refer to each one separately?

**Comment by jaeilepp** [comment]
Ok, yeah. I'm thinking that maybe we need just one channel type with two kinds (like we have with MEG channels mag and grad). Makes sense? Although it might be the easier to have just two types. Not sure which is better.

**Comment by mcaffini** [comment]
One type with two kinds makes more sense to me. That way you can pick all HbO with 'hbo', all HbR with 'hbr', or both with 'fnirs' (no caps to be consistent with the other tags?), the same way you pick magnetometers with 'mag', gradiometers with 'grad', ... or everything MEG with 'meg'. Adding total hemoglobin (HbT or hbt) is trivial (but not necessary) being the algebraic sum of HbO and HbR.

In http://martinos.org/mne/stable/generated/mne.pick_types.html would it look like this?

[...]
**meg** : bool or string
If True include all MEG channels. If False include None. If string it can be 'mag', 'grad', 'planar1' or 'planar2' to select only magnetometers, all gradiometers, or a specific type of gradiometer.

**fnirs**: bool or string
If True include all fNIRS channels. If False include None. If string it can be 'hbo', 'hbr', 'hbt' to select only oxyhemoglobin, deoxyhemoglobin, or total hemoglobin (algebraic sum of hbo and hbr).
[...]

**Comment by agramfort** [comment]
yes that sounds good to me

**Comment by agramfort** [comment]
@jaeilepp what did we converge on regarding fif constants?

**Comment by jaeilepp** [comment]
No response from Elekta yet.

**Comment by jaeilepp** [comment]
Here they are:
```
fnirs_hbo 300  "FNIRS oxyhemoglobin"
fnirs_hbr 301  "FNIRS deoxyhemoglobin"
fnirs 1100 "Functional near-infrared spectroscopy"
FIFF.FIFFV_FNIRS_CH     = 1100
```

**Comment by agramfort** [comment]
cool

thx @jaeilepp

let's get this merged

**Comment by agramfort** [comment]
@mcaffini there is a new public dataset with EEG + NIRS:

https://www.depositonce.tu-berlin.de/handle/11303/6271

maybe a good way to have a first example of NIRS with MNE?

**Comment by mcaffini** [comment]
Thanks @agramfort very interesting, I'll give it a shot.
I have completed my fNIRS analysis with MNE and I have also coded the source space reconstruction using a Monte Carlo method for the forward solution.
Still interested in a tutorial for the MNE website?

**Comment by dengemann** [comment]
Yes, this sounds really cool. Go for it!

**Comment by agramfort** [comment]
>
> Thanks @agramfort <https://github.com/agramfort> very interesting, I'll
> give it a shot.
> I have completed my fNIRS analysis with MNE and I have also coded the
> source space reconstruction using a Monte Carlo method for the forward
> solution.
> Still interested in a tutorial for the MNE website?
>
I don't know about the forward code I would to see it but basic raw data viz
would already be neat I think.

**Comment by mcaffini** [comment]
I prepared a Jupyter notebook tutorial with basic fNIRS data analysis, [here](https://github.com/mcaffini/mne-python-fnirs). Of course comments and suggestions are more then welcome. :-)

**Comment by agramfort** [comment]
we cannot really comment code with a rendered notebook

could be done with public data available from a website so we can
write a data fetcher? maybe not start from a custom .mat file which
generates a lot of boiler plate code which clutters the example/tutorial

**Comment by mcaffini** [comment]
@agramfort the notebook as well as the npy file with data should be downloadable for testing from my repo. The provided dataset comes from my lab and is real data, but we can change dataset and fetch it online, no problem.
Btw, I don't see any boilerplate code (apart from numpy.load :-D).

**Comment by agramfort** [comment]
can you make a tutorial script in a PR so we can comment line by line?
