### ISSUE TITLE
drop_channels silently passes when no channels are dropped

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#3542]
Maybe it's only me who's this thick skulled, but I do this all the time:

`raw.drop_channels('EEG 000')`

And then wonder why my channel is still in there.

I think it would be helpful if
- drop_channels would be a bit more verbose on what it does
- particularly, if it would warn if the channels intended to be dropped are not found, and if the action would result in no drops at all
- we could do a little `ch_names = [ch_names] if isinstance(ch_names, string_types) else ch_names` at the beginning of `.drop_channels`

**Comment by agramfort** [comment]
+1 for a ValueError when trying to drop a channel that is not present in
the data

**Comment by jona-sassenhagen** [comment]
Ok I will get on this ASAP, and afterwards, when it's still open, the ica.get_components issue.
