### ISSUE TITLE
ENH: granger

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#3548]
It would be great to have some granger analyses in MNE-Python. Although the method is regularly being criticized, many people use it, especially in ECoG.

There s one ready in nipy: https://github.com/nipy/nitime/pull/147#event-772264586

And an attempt in mne-sandbox: https://github.com/mne-tools/mne-sandbox/pull/8

If anyone wants to give it a try

**Comment by Eric89GXL** [comment]
Can we just refer people to `nipy` or make a tutorial on how to use the one from `nipy`?

**Comment by kingjr** [comment]
> make a tutorial on how to use the one from nipy

+1

**Comment by larsoner** [comment]
Closing as this is in the meta-issue
