### ISSUE TITLE
find_events fails on TRIUX data with legacy stim channels

### ISSUE THREAD

**Issue by jjnurminen** [mne-tools/mne-python#3554]
Not sure if this is a bug or not, but I think the situation could be improved.

Typically Elekta TRIUX (and recent Vectorview?) systems record triggers only on the digitally coded channel STI101, which contains all trigger information. However, in the data acquisition, there is a possibility of also acquiring 'legacy' trigger channels STI001, STI002, etc. These are binary channels which indicate the corresponding trigger channel being on/off. The main reason for acquiring these would be to support legacy software that does not understand STI101.

The problem is that `mne.find_events` fails (does not find any events) for raw files that contain both STI101 and the legacy channels, because it regards all of them as stim channels and considers them simultaneously. Setting `stim_channel=STI101` remedies the situation. I think an easy solution would be to always use STI101 if it exists, and disregard the legacy channels.

(In some setups, the trigger channel STI201 is also used separately, enabling 32 trigger lines. However this is a rare use case, so I think it doesn't need to be considered by default. Usually STI101 and STI201 are mirrored, i.e. contain identical information.)

**Comment by jjnurminen** [comment]
Actually this is nicely remedied by returning STI101 in `_get_stim_channel()`
Will submit a PR.

**Comment by Eric89GXL** [comment]
Yeah it should try `STI 014`, `STI101`, then whatever it does now.

**Comment by jjnurminen** [comment]
I already wrote a small patch but it ended up into the wrong branch and my
attempt at cherry-picking failed. (insert tearful emoji)

**Comment by Eric89GXL** [comment]
Nothing wrong with a little bit of manual cut and paste in desperate times
