### ISSUE TITLE
eeglab reader warns that it failed to find events when no events are present in the file

### ISSUE THREAD

**Issue by mmagnuski** [mne-tools/mne-python#3555]
I either have no events in the file (for example 'resting-state' activity) or have the events somewhere else and I would like to turn off the warnings that I get from eeglab reader. I tried changing `mne.set_log_level()` as well as setting `warnings.filterwarnings("ignore")` but I still get the warnings.
The warning is [here](https://github.com/mne-tools/mne-python/blob/master/mne/io/eeglab/eeglab.py#L613).
I don't think the reader should warn about not being able to find events when there are no events to be found. The intent of this warning was to signal when no events could be coerced to integers etc.

**Comment by jasmainak** [comment]
maybe @jona-sassenhagen has comments?

**Comment by Eric89GXL** [comment]
> I don't think the reader should warn about not being able to find events when there are no events to be found.

Agreed, can you open an issue to only warn if the file has events in it?

**Comment by jona-sassenhagen** [comment]
Im on it.

**Comment by jona-sassenhagen** [comment]
That'd be just making L612 in io/eeglab/eeglab.py

    if len(events) < 1 and len(types) > 0:

right?

**Comment by mmagnuski** [comment]
@jona-sassenhagen yes, that should work (+ a test maybe? :) )

**Comment by jona-sassenhagen** [comment]
For a test, we'd have to write a new EEGLAB structure. So we're looking at a few lines of test for half a line of code.

@Eric89GXL ?

**Comment by Eric89GXL** [comment]
We can live without a test, just don't tell @agramfort

**Comment by mmagnuski** [comment]
:no_mouth: :speak_no_evil:

**Comment by agramfort** [comment]
too bad for you I still have time to read emails...

but I can live here without a test...
