### ISSUE TITLE
New filter defaults

### ISSUE THREAD

**Issue by jaeilepp** [mne-tools/mne-python#3567]
I tried the new defaults when analysing the multi-modal faces dataset. I filtered the data with new filter defaults
```
raw.filter(1, 40, method='iir', n_jobs=1, h_trans_bandwidth='auto', l_trans_bandwidth='auto', verbose='INFO')
```
and was surprised to see the 50 Hz line noise in the results with cut-off frequency of 40 Hz.
![figure_1-6](https://cloud.githubusercontent.com/assets/3456414/18264284/a27ed728-740f-11e6-9cb2-45f2515dd3d3.png)
![figure_1-7](https://cloud.githubusercontent.com/assets/3456414/18264286/a3d2c5bc-740f-11e6-8965-9a22befb9299.png)

(For some reason the bad channel isn't as visible in the picture as in the mpl figure.)

**Comment by Eric89GXL** [comment]
IIR defaults shouldn't have changed, just FIR

**Comment by Eric89GXL** [comment]
The trans_* arguments aren't used with IIR actually

**Comment by jaeilepp** [comment]
Ok, I see. Closing this.
