### ISSUE TITLE
info.pick_info method?

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#3572]
Any chance of adding `mne.pick_info` as a method to info? That would make it more elegant to pass the (picked) info to other functions - without creating a handle to an intermediate object.

**Comment by agramfort** [comment]
type code you would like to write

**Comment by jona-sassenhagen** [comment]
`mne.viz.plot_topomap(array_for_data_chans, info.copy().pick(...))`

instead of:

```
info_picked = mne.pick_info(info, ...)
mne.viz.plot_topomap(array_for_data_chans, info_picked)
```

I guess you could also do

```
from mne import pick_info
mne.viz.plot_topomap(array_for_data_chans, pick_info(info.copy(), ...))
```

But we usually allow to chain methods for objects.

**Comment by agramfort** [comment]
is that

info.pick_types that you need?

**Comment by jona-sassenhagen** [comment]
... closing this :3
