### ISSUE TITLE
CSP transform doesn't comply with sklearn API

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#3583]
`CSP.transform` currently returns the CSP features averaged over time. 

IMO this is not a transform in the sklearn sense, it's a feature extraction. The transform should be the time course of each CSP i.e. return an array of `shape (n_epochs, n_filters, n_times)`.

Typically, if I want to do a dim reduction by CSP e.g. `make_pipeline(CSP(), TimeFrequency())` the current API can't work.

I don't think there's a way to do a nice deprecation cycle for this :/, except by redoing another object like we did for the Xdawn...

cc @alexandrebarachant @agramfort

**Comment by agramfort** [comment]
I would add a parameter to CSP to average over time or not.

the averaging is the standard use of CSP

**Comment by kingjr** [comment]
ok
