### ISSUE TITLE
ENH: Add minimum-phase filtering

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#3598]
We should have minimum phase filtering. It could especially be useful in realtime applications, cc @aj-ptw @m-brantheim. We need the upstream SciPy PR https://github.com/scipy/scipy/pull/6497 to land first. But it should only be 1-2 months away.

**Comment by agramfort** [comment]
can you clarify why this would be useful for realtime?

**Comment by Eric89GXL** [comment]
For things like online BCI, reducing delay is important. In linear phase
(or zero phase by delay correction) filtering the group delay in the
passband is substantially larger than in minimum phase

**Comment by Eric89GXL** [comment]
(Well the actual group delay is zero for the zero phase case, but it is
acausal so you do need to wait half the filter length before doing the
delay correction -- hence an effective delay when actually trying to use it)
