### ISSUE TITLE
Progress Bar in GAT

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-python#3604]
Is there a place in the gat code to add a progress bar like the spatiotemporal test has? I'm running it and I can't tell if it is a taxing on the computer or if it just silently died. Even if it is an update on each fold would be sufficient.

**Comment by dengemann** [comment]
Teon is back!!! :)

**Comment by kingjr** [comment]
There may be a way but I don't know it.

I actually would like this feature too, as I get a tonne of useless outputs from joblib instead :/

**Comment by teonbrooks** [comment]
> Teon is back!!! :)

not yet... :/ almost!

**Comment by jasmainak** [comment]
we have a progressbar in utils.py. That could be used ...

**Comment by kingjr** [comment]
Iirc The problem was not the problem bar itself but it's use in a
parallelized context.

**Comment by Eric89GXL** [comment]
The clustering code is parallel, so we can hopefully do the same thing in
both places.

**Comment by kingjr** [comment]
Right, we just have to copy 
```
    def get_progress_bar(seeds):
        # make sure the progress bar adds to up 100% across n jobs
        return (ProgressBar(len(seeds), spinner=True) if
                logger.level <= logging.INFO else None)
```

in `_GeneralizationAcrossTime` `TimeDecoding` and `SearchLight`. @teonbrooks you up for that?

**Comment by teonbrooks** [comment]
i'm grounded from coding for about one more month.

**Comment by jona-sassenhagen** [comment]
Yes, this would be very nice to have.

Also for Time-Freq computations.
