### ISSUE TITLE
Plot layout with selected channels

### ISSUE THREAD

**Issue by kambysese** [mne-tools/mne-python#3618]
Maybe I am misunderstanding the docstrings but shouldn't the following snippet result in a layout plot with only two (selected) channels?

channels = ['MEG0242', 'MEG0243']
exclude = [ch for ch in evoked.ch_names if ch not in channels]
layout=mne.channels.find_layout(evoked.info, ch_type='grad', exclude=exclude)
layout.plot()

![image](https://cloud.githubusercontent.com/assets/4381290/18852331/d3004acc-83f4-11e6-9be7-24998f22c1e2.png)

**Comment by agramfort** [comment]
indeed it's weird

**Comment by kambysese** [comment]
Thanks @agramfort :grinning: I specialize in weird
