### ISSUE TITLE
n_fft issue

### ISSUE THREAD

**Issue by ImmanuelSamuel** [mne-tools/mne-python#3621]
Changing n_fft does not change the frequency bins when using
`mne.time_frequency.psd_welch`

**Comment by Eric89GXL** [comment]
is `n_fft > n_samples` for your signal?

**Comment by ImmanuelSamuel** [comment]
yes

**Comment by Eric89GXL** [comment]
Read the docstring of `n_fft` more carefully, it says that if `n_fft > n_samples` , then `n_samples` will be used, i.e. `n_fft = min(n_fft, n_samples)`. Make sense?

**Comment by ImmanuelSamuel** [comment]
Yes I see that sorry about that. I had previously had n_fft  > n_samples and I got the zero-padded result. Not qute sure what function I used. Does mne support zero-padding or should I have to zero-pad the data before turning it into an Epoch?

**Comment by ImmanuelSamuel** [comment]
I know that tfr_* does that but what if I needed padding without the need to do time-frequency analysis? In this case where I fix the time bounds computation time is faster.

**Comment by mmagnuski** [comment]
IIRC psd_welch does not support padding and I also remember myself expecting at the beginning that `n_fft > n_samples` does zero padding. 
The `scipy.signal.welch` function that `psd_welch` is using supports zero-padding however: `nperseg` argument controls segment length and `nfft` is used for zero-padding, when needed.

**Comment by Eric89GXL** [comment]
I suppose we could change it so that if `n_fft > n_samples` it zero-pads, seems more consistent. Not sure how to do it in a nice way from a non-API-breaking standpoint, though. We might need to introduce a kwarg :(

**Comment by mmagnuski** [comment]
In some cases one may still want a welch window that is shorter than n_samples and zero-padding too, so another kwarg seems necessary (`pad_to`, `pad`, `zero_pad` ?).

**Comment by agramfort** [comment]
I agree

**Comment by Eric89GXL** [comment]
@mmagnuski did you change this behavior in #3823? If so can you update `whats_new.rst` to say so, and we can close this?

**Comment by mmagnuski** [comment]
No, I have a local branch for this. I will try to push it tomorrow.

**Comment by Eric89GXL** [comment]
Great thanks for fixing these issues
