### ISSUE TITLE
BUG: sklearn cannot find LeaveOneLabelOut

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#3623]
On latest `sklearn` I get this error in `master`:
```
======================================================================
ERROR: Test time generalization decoding
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/larsoner/custombuilds/nose/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/larsoner/custombuilds/mne-python/mne/utils.py", line 807, in dec
    return function(*args, **kwargs)
  File "/home/larsoner/custombuilds/mne-python/mne/decoding/tests/test_time_gen.py", line 61, in test_generalization_across_time
    from sklearn.model_selection import (KFold, StratifiedKFold,
ImportError: cannot import name LeaveOneLabelOut
```
@kingjr @agramfort were we using a deprecated feature, or is this a sklearn bug?

**Comment by Eric89GXL** [comment]
Actually looks like that class doesn't even exist in `master`:

http://scikit-learn.org/dev/modules/classes.html

**Comment by Eric89GXL** [comment]
Ahh, it's now called `LeaveOneGroupOut`

**Comment by kingjr** [comment]
oh god, they call it "LeaveOneGroupOut" now :/ We urgently need to deprecate classes that handle the cv, it's causing too much bleeding edge.

**Comment by agramfort** [comment]
ok but needs a backport :(

**Comment by Eric89GXL** [comment]
Do we need it? We only have the problem on bleeding-edge sklearn. We'll probably get 0.14 out before they get out 0.19 or 0.20

**Comment by agramfort** [comment]
we'll have a problem with 0.18 released imminently ...

**Comment by Eric89GXL** [comment]
I'm on 0.19-dev, are you sure it's a problem with 0.18?

**Comment by agramfort** [comment]
yes...

**Comment by Eric89GXL** [comment]
It only shows up in `mne/decoding/tests/test_time_gen.py` (not core code), so maybe not worth it? :)

**Comment by agramfort** [comment]
unless it makes debian packaging break....

**Comment by Eric89GXL** [comment]
Argh, yes it could. :( I can do it after #3622 is in

**Comment by Eric89GXL** [comment]
Indeed the problem is now in `master`:

https://travis-ci.org/mne-tools/mne-python/jobs/163710863

It is fixed by #3622, so I'll backport to 0.13 once that's in.

**Comment by agramfort** [comment]
can you backport?

**Comment by Eric89GXL** [comment]
done

**Comment by agramfort** [comment]
Thx!






On Mon, Oct 3, 2016 at 2:08 PM +0900, "Eric Larson" <notifications@github.com> wrote:












done
