### ISSUE TITLE
BUG: source space decoding example is broken

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#3627]
Check it out: http://martinos.org/mne/stable/auto_examples/decoding/plot_decoding_spatio_temporal_source.html#sphx-glr-auto-examples-decoding-plot-decoding-spatio-temporal-source-py

The plots are broken.

**Comment by kingjr** [comment]
also noted in #3350. @jona-sassenhagen did you check that it runs locally?

**Comment by jaeilepp** [comment]
This is actually fixed now. The martinos page just needs an update.

**Comment by agramfort** [comment]
website updated

let me know if not ok
