### ISSUE TITLE
ENH: example with noise levels from empty room

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#3631]
People often show noise levels of MEG systems as e.g. 10 fT/Hz**0.5. We should probably have an example where we do this with data. I'm thinking it would be cool to have it for empty-room data from different sites and/or systems, too, maybe eventually with e.g. sythetic gradiometry and/or compensation grades for systems that support those.

I thought about showing how different denoising algorithms work for some of these datasets, but that might make the example too dense. But collecting these files would at least make it more tenable to do do those types of analyses. Other ideas welcome.

For starters, @kingjr can you get a good empty-room recording from your setup and put it somewhere for me to get?

**Comment by kingjr** [comment]
Sure. You only want kit or all systems ?

**Comment by Eric89GXL** [comment]
Whatever systems you have

**Comment by SherazKhan** [comment]
I can provide latest one from Martinos (The quietest room in the world)

**Comment by Eric89GXL** [comment]
I was planning on using the one from the sample dataset for MGH, but if you have a "more illustrative" example for me to use from The Quietest Room in the World™ feel free to upload one and shoot me a link

**Comment by SherazKhan** [comment]
May be I share THE  [world record MEG empty recording from Martinos](http://www.guinnessworldrecords.com/world-records/weakest-magnetic-field-measured)

**Comment by Eric89GXL** [comment]
Oh, I thought that was a joke until I read the link. Awesome. Yes please :)
