### ISSUE TITLE
BUG: coregistration doesn't read fiducials anymore

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#3679]
Something has changed in mne.gui.coregistration. Now I can't load the fiducials file, it throws the following error:

![screenshot](https://cloud.githubusercontent.com/assets/4881164/19610695/cca6d1ee-97ab-11e6-8a11-5f70669b91b1.png)

I checked that this works fine with a previous version version

@christianbrodbeck

**Comment by christianbrodbeck** [comment]
Can you read the file with `read_fiducials()`?

**Comment by kingjr** [comment]
no:
```
----> 1 read_fiducials('/media/jrking/USB30FD/sub01/sub01_YFAALKWR_JA/_tmp_epoch_coreg.fif')

/home/jrking/mne-python/mne/io/meas_info.py in read_fiducials(fname)
    301         err = ("No coordinate frame was found in the file %r, it is probably "
    302                "not a valid fiducials file." % fname)
--> 303         raise ValueError(err)
    304 
    305     # coord_frame is not stored in the tag

ValueError: No coordinate frame was found
```

I had to revert back to ~ january 2016 to make it work.

**Comment by Eric89GXL** [comment]
Want to try [git bisect] (http://webchick.net/node/99) to find the offending commit?

**Comment by kingjr** [comment]
here is the file that worked with a previous version of mne https://ufile.io/8cc9

**Comment by christianbrodbeck** [comment]
Well I guess we could silence that error? Warn instead? Which application saves fiducials without coordinate frame? Did we in the past?

**Comment by kingjr** [comment]
The coordinate system was brainsight, usually used for TMS. I don't know much more, I'm not very skilled regarding coregistration functions and i/o.

**Comment by Eric89GXL** [comment]
@kingjr I just tried to download your file but it has expired. Can you re-upload?

**Comment by Eric89GXL** [comment]
@kingjr can you track down the offending file?

**Comment by kingjr** [comment]
I'm closing this for now, as the last PRs fixed some problem. I'll re-open it if I encounter this issue again.
