### ISSUE TITLE
DOC: verbose

### ISSUE THREAD

**Issue by jjnurminen** [mne-tools/mne-python#3680]
I was trying to figure out how to reduce the amount of output from certain functions. Looking at the docs, it says everywhere:  

```
verbose : bool, str, int, or None
If not None, override default verbose level (see mne.verbose). Defaults to raw.verbose.
```

In the docs there is no link to `mne.verbose` and googling for it finds nothing useful. Doing `mne.verbose?`in IPython tells that it's from `mne.utils`. Looking at the source, it appears to be an 'improved verbose decorator', but still no hints on what values one could set etc. I finally found the relevant documentation in `mne.utils.set_log_level()`, but maybe the situation could be improved :)

**Comment by agramfort** [comment]
agreed. We should have a section on doc about this and point to it in
docstrings.
