### ISSUE TITLE
Serious issues with 'Linear Model'

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#3681]
I'm only reading this http://martinos.org/mne/stable/auto_examples/decoding/plot_linear_model_patterns.html

I have several serious concerns:

minor:
* we suggest to vectorize the data to apply a single linear model; (doesn't seem very smart, but ok)
* the code has many syntax issues, copy/paste from sklearn etc

major:
* we plot the patterns without rescaling the coefficients (but perhaps that's ok??)
* there is no cross-validation ?
* there is no unit test ?

@agramfort @trachelr

**Comment by trachelr** [comment]
Hi @kingjr 
the scale of the coefficients depends on the scale of the data. normalisation is applied before fitting the model... I dont see any issue here.
cross validation is available by model=LogisticRegressionCV in the LinearModel init function.
@agramfort unit test is needed for examples?

**Comment by kingjr** [comment]
Regarding the CV, IIUC LogisticRegressionCV is a cross val to optimize the parameter (C) not a CV to estimate the effect size. Although the example doesn't explicitly score the data, the filters and patterns can only make sense if there's an effect of condition - a requirement which should be addressed via a cross_val_score IMO.

Regarding the unit tests, I was referring to the object LinearModel and the X.X^T function.

Regarding the scaling, I would think that if you want to source localize the pattern, you'd need to unscale the data, else the grads and mags (and the eeg if you fit a single model) won't be meaningfully related to one another anymore. @agramfort what's your view on this?

**Comment by agramfort** [comment]
I don't see the pb. If you scale the features then you need to undo the
scaling to get patterns in signal space with good units.

**Comment by agramfort** [comment]
it's the first iteration on this code/method so I am sure it needs some
love....

**Comment by trachelr** [comment]
yesss it was quickly/kindly coded during a mne sprint last year and not heavily tested... so more contributions are welcome!
@kingjr I can write some unit tests to finish the job but not more since i'm not doing any decoding stuff anymore.

**Comment by kingjr** [comment]
ok; let me first have a chat with Alex, I'm encountering weird things with the Haufe's trick; I wanna make sure I'm missing something before fixing the details.
