### ISSUE TITLE
BUG: Version number not in compliance

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#3691]
@agramfort it looks like you changed it to `.git` instead of `.git0` at release, [we need to change it] (https://www.python.org/dev/peps/pep-0440/#public-version-identifiers). While we're at it, I propose we change it to `.dev0` instead of `.git0`, since it seems more standard. Was there a reason for `.git0` instead of `.dev0`?

**Comment by agramfort** [comment]
please go for .dev0 it was my bad old habit...

**Comment by Eric89GXL** [comment]
Done
