### ISSUE TITLE
BUG: Point-spread example doesn't render properly

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#3692]
http://martinos.org/mne/dev/auto_tutorials/plot_point_spread.html

@jaeilepp you fixed this in another example, right? Do we just need to make it not show multiple views?

**Comment by jaeilepp** [comment]
The problem was with multiple views. For some reason it does not work on circle. When I build the doc locally it works fine for me. So changing ``views=['lat', 'med']`` to a single view (and maybe do two plotting calls) should fix it.
