### ISSUE TITLE
BUG: Missing epochs with RtEpochs

### ISSUE THREAD

**Issue by Odingod** [mne-tools/mne-python#3695]
The RtEpochs misses epochs if they start at the boundary of two buffers. The trigger channel is now read only from the current buffer. If the triggers are split between two buffers it's possible to miss them since they are not long enough.

Example:
[... 0 0 0 0 1 1][1 1 1 1 0 0 0 ... ]
Trigger channel that's split to two buffers. If we want a minimum of 5 samples neither of these buffers alone triggers an epoch.

I have written a small fix and can create a pull request for it.

**Comment by agramfort** [comment]
this is fixed in #3738
