### ISSUE TITLE
Add button to project electrodes onto scalp in  mne.gui.coregistration

### ISSUE THREAD

**Issue by noreun** [mne-tools/mne-python#3700]
Since `mne.make_forward_solution` will project electrodes onto scalp before calculations, wouldn't it be better to do so during `mne.gui.coregistration`, using a button "project" or something like that?

This was we can visualize the real position of electrodes, that might be far from scalp due to digitization issues.

**Comment by Eric89GXL** [comment]
@christianbrodbeck any interest? I can make `plot_trans` have such an option first, and thus take care of any necessary refactoring. Then you would just need to cover the `traits`-related tweaks.

**Comment by Eric89GXL** [comment]
Actually, what would be cool is `plot_trans(..., eeg_sensors='original' | 'projected' | ['original', 'projected'])`, so show the original locations, projected ones, or both. In the GUI that would be two checkboxes, defaulting to original-only (the current behavior).

**Comment by christianbrodbeck** [comment]
I don't really have time (and I'm not working with EEG at the moment) but if it would be very useful in the GUI and all the underlying functions are there I will give it a try

**Comment by Eric89GXL** [comment]
@noreun do you think you will have time to do this at some point? You can see how it's done in `plot_trans`

**Comment by noreun** [comment]
@Eric89GXL yes, it seems quite simple. I'll give it a shot later tonight.

**Comment by agramfort** [comment]
this is done

**Comment by larsoner** [comment]
@agramfort this isn't done, you are probably thinking of `plot_alignment` but this issue is for `mne coreg`
