### ISSUE TITLE
ENH: plot_topomap, plot_joint & plot: API homogeneity for scalings/scale parameters

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#3702]
Small API heterogenity: different plotting functions use similar parameters slightly differently (and named slightly differently)
- scaling: `evoked.plot(scalings=dict())` but `evoked.plot_topomap(scale=dict() | float)`
- units: `evoked.plot(units=dict())` but `evoked.plot_topomap(unit=dict() | str)`
- max amplitude: `evoked.plot(ylim=dict())` but `evoked.plot_topomap(vmin=dict() | float, vmax=dict() | float())`

Changing parameter names can be annoying for deprecation, but I suggest we at least make their input similar (e.g. always accepts both `dict` and `float`).

Additionally, `evoked.plot_joint()` could gather the parameters common to `plot()` and `plot_topomap()` to simplify it. WDTY @jona-sassenhagen ?

**Comment by jona-sassenhagen** [comment]
Somewhat related: #3164

**Comment by jona-sassenhagen** [comment]
Unity here would be greatly improved IMO.

We must be careful however with how different functions handle different channel types.

**Comment by jona-sassenhagen** [comment]
Can we split this into multiple smaller PRs?

**Comment by jaeilepp** [comment]
It feels a bit redundant to have ``scaling`` and ``vmin, vmax`` in the first place. Could we get rid of scaling in for instance topomaps or is there a use case where you'd prefer using scaling?

**Comment by agramfort** [comment]
to me scaling and vmin and vmax very different usage. I think we should
keep them.

**Comment by jona-sassenhagen** [comment]
I think you need scaling if you use for example stats.regression, where you plot t values on data channels.

**Comment by jona-sassenhagen** [comment]
Ugh I must get back to this. @jaeilepp can you maybe assign me so I don't forget?

**Comment by jaeilepp** [comment]
Done.

**Comment by jona-sassenhagen** [comment]
Also: mne.viz.plot_compare_evokeds is missing a bunch of options, like scalings and units.

:(

**Comment by jona-sassenhagen** [comment]
@Eric89GXL @agramfort do you have any idea about solving the different names for identical params for different functions (e.g., "unit" vs "units")?

I guess a **kwargs could do, but we never use that (in public functions), so ...

**Comment by Eric89GXL** [comment]
Can you give an example of what you are trying to do?

**Comment by Eric89GXL** [comment]
Oh it is in the top post.

I think the only clean way to fix it is to deprecate.
