### ISSUE TITLE
ENH?: News / updates

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#3703]
It seems like we should have a little news/updates section of one-liners on the website, including things like:
1. Release notifications
2. Upcoming MNE-Python workshops
3. Upcoming coding sprints

If people agree I can put some old ones (last couple of release dates), and we can add to it as announcement-worthy things come up.

**Comment by dengemann** [comment]
Sounds cool! I like this idea.

**Comment by kingjr** [comment]
+1 for also adding the old ones, typically useful when asking for
institutional support to show that we're serious

**Comment by agramfort** [comment]
+1
