### ISSUE TITLE
avoid use of mne_surf2bem

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#3709]
we should remove the use of mne C tool mne_surf2bem in mne-python.

**Comment by Eric89GXL** [comment]
This would require translating `mne_surf2bem`, right? It should be pretty simple, I think.

**Comment by agramfort** [comment]
yes it's nothing. We have everything already. Just 2 hours to find :(

**Comment by Eric89GXL** [comment]
Actually it looks like we don't need to add anything, just modify calls. We already have `write_bem_surfaces(fname, surfs)`, so we should just need to make the list of dict `surfs` properly.

**Comment by agramfort** [comment]
so 20 mins not 2 hours? :)
