### ISSUE TITLE
AssertionError brainvision.pyc file

### ISSUE THREAD

**Issue by clementdonde** [mne-tools/mne-python#3740]
Hello,

I can't open my .vhdr files for EEG analysis, there's got to be a pb with my brain vision.pyc file. Can someone guides me to fix this ?
Thxs in advance !
![screen shot 2016-11-05 at 19 56 47](https://cloud.githubusercontent.com/assets/23283446/20033075/8d84e58e-a398-11e6-9fe3-365863e911ec.png)

**Comment by agramfort** [comment]
please share a problematic file.

how was this file created?

**Comment by clementdonde** [comment]
Thxs for your answer.
The file was downloaded with the brain vision package.

[brainvision.pyc.zip](https://github.com/mne-tools/mne-python/files/573966/brainvision.pyc.zip)

**Comment by agramfort** [comment]
I meant share the .vhdr file so we can replicate the error and ideally fix
it.

thanks

**Comment by clementdonde** [comment]
ok, sure

**Comment by clementdonde** [comment]
ok, sure
[exemple.vhdr.zip](https://github.com/mne-tools/mne-python/files/574093/exemple.vhdr.zip)

**Comment by agramfort** [comment]
ok so you have data in ASCII and our reader only supports data in binary
format
(binary by the way more compact on disk and avoids loss in numerical
precision)

can you save them to binary so it fixes your problem?

See https://github.com/mne-tools/mne-python/pull/3748

**Comment by clementdonde** [comment]
thxs for this quick solution.
do you have a method to access my .vhdr files content and translate it to binary ?

**Comment by agramfort** [comment]
no.

but if you share a full dataset we can look into it.

you can't save again to binary with your brainvision software?

**Comment by Eric89GXL** [comment]
Would it be possible for you to get a short segment (say, 1 sec?) of the ASCII data and upload it? It might also be possible to add support for it at some point.

**Comment by clementdonde** [comment]
do you know which program other than my terminal can open vhdr file ? I can't open it with anything so can't get segments out of it. 
[Archive.zip](https://github.com/mne-tools/mne-python/files/578683/Archive.zip)
please find attached the vhdr + dat and vmrk corresponding files, if it can help.

thxs in advance

**Comment by agramfort** [comment]
more news happening at https://github.com/mne-tools/mne-python/pull/3752 ...

**Comment by clementdonde** [comment]
ok, nice job! 
I try to use this conversion tool but I'm a very beginner at MNE, can't find solution to solve this error, can you advise me ?
thx in advance

![screen shot 2016-11-08 at 23 40 04](https://cloud.githubusercontent.com/assets/23283446/20120481/4c279952-a60d-11e6-8ea7-9a0c6de57c9f.png)

**Comment by jaeilepp** [comment]
See instructions at http://martinos.org/mne/stable/contributing.html#some-other-things-you-might-want-to-do on how to fetch a single pull request. Once https://github.com/mne-tools/mne-python/pull/3752 gets fixed you should be able to read the ascii files with ``mne.io.read_raw_brainvision(fname)``.

Hope this helps.

**Comment by clementdonde** [comment]
my terminal can't open the files even after conversion of the .vhdr file from ASCII to binary.
please find attached the error code
[error.pdf](https://github.com/mne-tools/mne-python/files/614646/error.pdf)

**Comment by Eric89GXL** [comment]
How did you convert it? I don't think the header file was what needed to be
converted, but rather the data file.

Did you try my PR with your original ASCII data?

**Comment by Eric89GXL** [comment]
(... And the conversion would need to be done with a brainvision tool,
which I suspect is not the case here)

**Comment by agramfort** [comment]
Yes I tried this PR with the original files cf my private email

**Comment by Eric89GXL** [comment]
What error did you get on my PR with the original files? I thought I had
the original file working. Or is there a new / different failing file now?

**Comment by Eric89GXL** [comment]
I had a little bug, should hopefully work now
