### ISSUE TITLE
API: default params in `raw.apply_hilbert` and `raw.apply_funtion`

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#3742]
These two methods would be more handsome if equipped with some defaults.
At least picks and n_jobs could default to something, maybe also dtype.
What do you think? @Eric89GXL @agramfort ...

**Comment by dengemann** [comment]
And while we're at it also let them return self.

**Comment by agramfort** [comment]
+1

picks should default to data channels
n_jobs to 1 and dtype to float
and raise a warning if a complex is returned

**Comment by dengemann** [comment]
Ok sending PR later today
