### ISSUE TITLE
ENH: mne.gui.coregistration automatically changes subject to fsaverage

### ISSUE THREAD

**Issue by noreun** [mne-tools/mne-python#3761]
mne version: MNE 0.14.dev0
OS: Ubuntu 16.04.1 LTS

whenever I open a new Head Shape Source File, the current subject is automatically changed to fsaverage.

the only way for me to work now is to delete the symbolic link that freesurfer creates in the subjects folder and recreate it after finishing all the coregistrations.

**Comment by christianbrodbeck** [comment]
This is not a bug, but maybe there is a way to improve it. The GUI should look for an MRI subject name that equals the beginning go the Head Shape source filename. If none is found we assume you want to use fsaverage instead. What subject would you want it to change to instead? Are you using a different standard brain?

**Comment by noreun** [comment]
Thank you for the prompt response.

No I'm using fsaverage. I was going to ask first if it was a feature but I thought it was too weird to be a feature.

Indeed the files where generated by different groups and they have different naming conventions.

I could rename them, but I don't really understand the feature: If the subject is on the top left of the screen, the idea is not to first select the subject you want to work with, and later select the other files? Perhaps just create a filter when selecting the Head Shape file, but allow the user to overwrite it? 

Even better, include a parameter when calling mne coreg to disable this automatic feature? 

If this would be possible I could change the name of the issue from BUG to ENH, otherwise I'll just close it.

**Comment by christianbrodbeck** [comment]
I could add a checkbox to make it optional.

> I don't really understand the feature: If the subject is on the top left of the screen, the idea is not to first select the subject you want to work with, and later select the other files?
> 

You’re right about this. Would it be more logical to put the Head Shape Source section above the MRI?

**Comment by noreun** [comment]
> I could add a checkbox to make it optional.
>

I would favor a parameter in the command line, since I rather write a
script than click in the checkbox every time ;)

but the checkbox would already avoid deleting the the fsaverage folder and
renaming all the files one by one ( they don't really have a proper naming
convention now :/ )


>
> You’re right about this. Would it be more logical to put the Head Shape
> Source section above the MRI?


Not Sure about that... I seems logical to first pick MRI, then MRI
fiducials, then digitization info, then rotate/translate digitization into
MRI space.

I think the option to disable the automatic behavior, which I can see that
saves time to people that do not want to click in the first listbox with
users AND click again to select the digitization file, should be enough.

**Comment by christianbrodbeck** [comment]
Of course, it can be exposed as argument, but you probably also want the checkbox for the times you forget to specify the argument :)

**Comment by noreun** [comment]
> Of course, it can be exposed as argument, but you probably also want the
> checkbox for the times you forget to specify the argument :)
>
>
> True. :)

Another nice option would be to automatically pick the digitization file
matching the subject selected on the list (the other way around). And if
none is found, clear the digitization field.

Indeed it is weird that, when processing a batch of subjects, the old
digitization file is still selected after changing the subject on the top.
Now I see that this is probably because people only change the digitization
file instead, and the subject changes automatically.

For this you would need to specify the digitization folder in advance
though, similar to specifying the subjects folder for freesurfer (used to
populate the list one the top, I'm guessing...).

**Comment by christianbrodbeck** [comment]
> On Nov 11, 2016, at 12:16 PM, Leonardo S. Barbosa <notifications@github.com> wrote:
> 
> > Of course, it can be exposed as argument, but you probably also want the
> > checkbox for the times you forget to specify the argument :)
> >
> >
> > True. :)
> 
> Another nice option would be to automatically pick the digitization file
> matching the subject selected on the list (the other way around). And if
> none is found, clear the digitization field.
> 
> Indeed it is weird that, when processing a batch of subjects, the old
> digitization file is still selected after changing the subject on the top.
> Now I see that this is probably because people only change the digitization
> file instead, and the subject changes automatically.
> 
> For this you would need to specify the digitization folder in advance
> though, similar to specifying the subjects folder for freesurfer (used to
> populate the list one the top, I'm guessing…).

This would be harder, I think conventions for digitization files might vary more…. we use `MEG/subject_name/something-raw.fiff`, so it’s more nested than the MRIs...

How would clearing the field help, wouldn’t you still have to click the same number of times to load the next one?

**Comment by noreun** [comment]
>
>
> This would be harder, I think conventions for digitization files might
> vary more…. we use `MEG/subject_name/something-raw.fiff`, so it’s more
> nested than the MRIs...
>

I see.

I think the checkbox close to the digitization file should be enough. This
way people are aware of the behavior, and also can disable if needed.


>
> How would clearing the field help, wouldn’t you still have to click the
> same number of times to load the next one?


I think in general it is one digitization file per subject, so if the
pipeline I'm using is : select subject, then select digitization, it makes
no sense to keep the old digitization / transformation parameters loaded.

But perhaps it makes sense to people using standard nets and morphing the
MRI to fit them, right?

In any case, this is more of a detail. The checkbox / command line is the
important thing here.

**Comment by noreun** [comment]
addressed by #3762
