### ISSUE TITLE
Official docs still 0.12

### ISSUE THREAD

**Issue by christianbrodbeck** [mne-tools/mne-python#3764]
I just noticed that http://martinos.org/mne/stable/ still points to the docs for 0.12

**Comment by agramfort** [comment]
can you be more explicit?

**Comment by christianbrodbeck** [comment]
The window title says mne 0.12 and I tried to look up a method signature
that changed from 0.12 to 0.13 (SourceEstimate.plot()) and it showed the
0.12 version (
http://martinos.org/mne/stable/generated/mne.SourceEstimate.html#mne.SourceEstimate.plot
ought to have )

**Comment by christianbrodbeck** [comment]
![img_0671](https://cloud.githubusercontent.com/assets/145771/20246377/b3cfd19a-a983-11e6-816e-a43f5c44d073.PNG)

**Comment by agramfort** [comment]
arfff maybe it's because I pushed a fix to maint/0.12 branch and it updated
the git repo containing the web site :(

let's see if this fixes the pb

https://github.com/mne-tools/mne-python/commit/bdbbb84a46a20e7cdcc4ca08621a5c939791117c

**Comment by Eric89GXL** [comment]
Should we start keeping old documentation versions like sklearn, scipy,
etc.?

**Comment by Eric89GXL** [comment]
Now GitHub is correct, martinos is not

**Comment by mmagnuski** [comment]
Would be really nice if there was some drop-down menu to switch between versions (for example). Similarily to how it works on readthedocs (Julia docs for example).

**Comment by agramfort** [comment]
fixed

**Comment by Eric89GXL** [comment]
Do we want a drop down with different doc versions? It would also fix this
overwriting problem.

**Comment by agramfort** [comment]
why not but it's not a priority for me
