### ISSUE TITLE
Way to remove portions of continuous data using Annotations but not Epochs?

### ISSUE THREAD

**Issue by kaczmarj** [mne-tools/mne-python#3767]
MNE tutorials ([Tutorial 1](https://martinos.org/mne/stable/auto_tutorials/plot_artifacts_correction_rejection.html#tut-artifacts-reject), [Tutorial 2](https://martinos.org/mne/stable/auto_tutorials/plot_brainstorm_auditory.html#sphx-glr-auto-tutorials-plot-brainstorm-auditory-py)) on how to remove artifacts suggest that segments annotated 'bad' are removed during the creation of `mne.Epochs`. This seems great for ERPs but not for time-frequency analysis of continuous data. Is there a way to remove portions of continuous data with `mne.Annotations`? I think this would be similar to boundary events in EEGLAB. I also did not find a method for this in the code for `mne._BaseRaw`.

**Comment by agramfort** [comment]
see #3731 this is related issue. Please continue discussion there
