### ISSUE TITLE
linking colorbar yticks and topoplot countour lines?

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#3795]
Would it in principle be possible to link the contour lines of a topoplot and the yticks of the corresponding colorbar?
Just an idea.

@jaeilepp

**Comment by mmagnuski** [comment]
Yeah - you can find the contour lines in the:
```python
im, lines = plot_topomap(values, info)
contour_levels = lines.levels
```
and use it in setting legend ticks.
I like the idea BTW.
