### ISSUE TITLE
TFR plot colorbar problems?

### ISSUE THREAD

**Issue by choldgraf** [mne-tools/mne-python#3799]
A labmate of mine is getting weird errors when calling `plot` without any color using multiple axes. This is the line that's giving it trouble:

https://github.com/choldgraf/mne-python/blob/master/mne/time_frequency/tfr.py#L766

The error is saying that `CB` isn't an attribute. I've never seen a colorbar referenced in this way. Could it be deprecated in MPL or something like this?

**Comment by jaeilepp** [comment]
Crap. Looks like leftovers from my PR...
