### ISSUE TITLE
Viz improvement: AverageTFR.plot_joint

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#3801]
![unknown-127](https://cloud.githubusercontent.com/assets/4321826/20705719/61bf033c-b624-11e6-968f-dd0a7c03bb36.png)

This is something EEGLAB has. I dislike normal TF plots ... these are much nicer IMO. Thoughts?

It's not *that* much code, and the most complicated part is already in `evoked.plot_joint`.

@jaeilepp @kingjr

**Comment by jona-sassenhagen** [comment]
@jaeilepp don't make a PR already, let me try first :D

**Comment by jaeilepp** [comment]
Sure, go ahead.

**Comment by mmagnuski** [comment]
It may be nice if the channels (set of channels) used for the TFR is highlighted in the topomaps (although the user will always know which channels the TRF is obtained from...).
Would be also cool if topomapped parts of the TFR could be set in a rectangle way (for example in time, Hz order: `[(-0.2, 0), (8., 10.)]`) - but that could be something for later. :)

**Comment by jaeilepp** [comment]
> Would be also cool if topomapped parts of the TFR could be set in a rectangle way (for example in time, Hz order: [(-0.2, 0), (8., 10.)]) 

You can already do that interactively.

**Comment by mmagnuski** [comment]
Oh, I didn't know, thanks! 
Here I meant that the topos in plot_joint would not point to a single point but to a box surrounding the defined tfr region.

**Comment by jona-sassenhagen** [comment]
>It may be nice if the channels (set of channels) used for the TFR is highlighted in the topomaps (although the user will always know which channels the TRF is obtained from...).

All. It's a mean over all by default, and I'm not sure other options should be provided.

>Here I meant that the topos in plot_joint would not point to a single point but to a box surrounding the defined tfr region.

The API for topomaps here is already a time point plus window around it parameter, IIRC `times`and `average`. Just make `average` take a (time, freq) tuple and there it is.

The above is actually with 3-Hz freq bins and 200-msec time windows (for the topomaps).

**Comment by jona-sassenhagen** [comment]
Is it save to average TF data over multiple channels using plain old `np.mean` btw? I guess they're reasonably normally distributed across channels.

**Comment by jona-sassenhagen** [comment]
Any further comments? Don't just wanna go for implementing this if there's little interest. Also I'm sure if you care about this, you'll have opinions on specifics :)

**Comment by kingjr** [comment]
Sounds interesting, but I'm not totally clear about the proposal. What is the tfr image showing? the average time frequency over channels? It's std across channels (equivalent of GFP)?

**Comment by jona-sassenhagen** [comment]
It's the average. It's done like this in an EEGLAB viz function, used for example in Makeig's Science and PLoS Biology papers.

**Comment by kingjr** [comment]
I'm +1. It seems like a helper for mining tfr

**Comment by agramfort** [comment]
ok for me

**Comment by mmagnuski** [comment]
I like it - but would like an option for it to not be average over all channels (`picks`). So that one could show ROI-based tfrs (or build on this functionality to show cluster-corrected stats etc.).

**Comment by jona-sassenhagen** [comment]
w.r.t. @mmagnuski , I think we first need a function to plot the image for a selection of channels, or extend the normal tfr.plot() function like that.

@agramfort , would you be ok with this:

`averageTFR.plot(picks=picks, average=True)`

docstring:

```
average : bool
    If False, show one plot per picked channel.
    If True, show only one plot: the average over all selected channels. If picks
    is empty, the mean over all channels is plotted.
    Defaults to False.
```

And then this one simply adds the topomaps on top.

**Comment by dengemann** [comment]
not opposed.

**Comment by mmagnuski** [comment]
`average` is good - I previously considered lists of lists so that `[[1, 2], [3, 4, 5]]` produces two figures - one for average of picks 1 and 2 and the other for average of picks 3, 4 and 5. But this is probably less intuitive than `average` param.
