### ISSUE TITLE
[BUG] sources_as_raw leads to error when calling __repr__ of raw object

### ISSUE THREAD

**Issue by ppasler** [mne-tools/mne-python#3804]
After creating an `ICA object` and calling `get_sources`. The created `Raw object` hast an empty filenames list [mne.preprocessing.ica:_sources_as_raw](https://github.com/mne-tools/mne-python/blob/master/mne/preprocessing/ica.py#L729).
This causes an `IndexError` when calling [mne.io.Base:repr](https://github.com/mne-tools/mne-python/blob/master/mne/io/base.py#L1884) because the list is not `None`, but empty.

**Comment by Eric89GXL** [comment]
Looks like it should set `_filenames = [None]` instead of `_filenames = []`. Can you make a PR to fix it, and add a test? The test can just be a line in `mne/preprocessing/tests/test_ica.py` that does `print(repr(ica_raw))`

**Comment by dengemann** [comment]
Wow, this seems like a time-warp, a regression?
Fix welcomed.

**Comment by ppasler** [comment]
@Eric89GXL @dengemann sure.

**Comment by ppasler** [comment]
@Eric89GXL @dengemann this is first time I contribute to an open source project. 

1. fork the repo
2. create a branch from master
3. add a PullRequest with my changes

Is this correct?

**Comment by Eric89GXL** [comment]
Yep that's the idea. How you go about creating branches and the like is up to you. It's possible to do it all graphically on GitHub to start. For frequent development it's easier to learn the `git` command-line interface.

**Comment by ppasler** [comment]
I am familiar with git, but not with the workflow for OS projects :)
I'll try it now!

**Comment by ppasler** [comment]
It seems not to connect the issue with the PR, do I have to use some specific branch name or commit text?
