### ISSUE TITLE
disable testing for the same 'dev_head_t' when using concatenate_epochs

### ISSUE THREAD

**Issue by romquentin** [mne-tools/mne-python#3809]
Dear experts, 
I am using concatenate_epochs and I got this error since version 0.14.
`epochs[0]['info']['dev_head_t'] must match`
It is true that I am concatenate different runs but is there a quick way to disable this check (that was not present in 0.13 I guess)?
Thank you!

**Comment by Eric89GXL** [comment]
You can manually set `info['dev_head_t']` for each epoch to the same thing. But keep in mind this could have unintented consequences in terms of smearing spatial information at the sensor and source level.

**Comment by romquentin** [comment]
Ok. Thank you!
