### ISSUE TITLE
mne.time_frequency.EpochsTFR.save?

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#3810]
Shouldn't `EpochsTFR` objects have a save method? Or am I missing something ..?

@agramfort @kingjr (I forgot who did the class ...)

Not volunteering :)

**Comment by mmagnuski** [comment]
They should but it wasn't implemented yet.

**Comment by kingjr** [comment]
Yes, it should. (but I'm not an API guy, so I'll pass it @agramfort .)

**Comment by agramfort** [comment]
yes it should. It should be easy to do if you use hdf5 and not fif

PR welcome
