### ISSUE TITLE
[ENH] forward model with fixed orientations

### ISSUE THREAD

**Issue by Mountainmums** [mne-tools/mne-python#3811]
Hi,

are there any plans to add the --fixed functionality for forward modeling to MNE-Python? 

We are trying to migrate our processing pipeline to Python and it would be much simpler to be able to do all our steps within that framework.

**Comment by Eric89GXL** [comment]
You can simply use convert_forward_solution after computation.

**Comment by Mountainmums** [comment]
Did not know that. Thanks for the tip !

**Comment by Eric89GXL** [comment]
Do you have time to make a PR to improve a tutorial? Also in `make_forward_solution` we could say in the `Notes` section that `fixed` is not necessary because you can just `convert_forward_solution`

**Comment by Mountainmums** [comment]
Not sure I have the expertise to improve anything, but if I can figure out how to make a PR (GitHub newbie,), I can add to the relevant tutorials and to the make_forward_solution a line about using the convert_forward_solution to get fixed orientations.
