### ISSUE TITLE
public TFR function for arrays?

### ISSUE THREAD

**Issue by choldgraf** [mne-tools/mne-python#3838]
I've had a few people become confused now that `cwt_XXX` is deprecated, as they were using this function to compute a TFR on arrays. The new `tfr_` functions operate on MNE objects, not arrays. Is it worth either supporting arrays w/ those objects, or adding a `tfr_array` function?

**Comment by mmagnuski** [comment]
Related: #3789

**Comment by Eric89GXL** [comment]
Closing as dup
