### ISSUE TITLE
ENH: Real filter in DICS

### ISSUE THREAD

**Issue by brovelli** [mne-tools/mne-python#3840]
Hi all,
here is an issue related to #3832
As far as I understand the mne DICS beamforming implementation is the orginal version proposal by Gross et al. (PNAS, 2001). Hipp et al (Neuron, 2011) proposed to derive the filter from only the **_real_** part of the cross-spectral-density matrices instead of the complex cross-spectral density matrix as originally proposed. They argue that [ I cite from their suppl material] "the propagation of the brains’ electrical and magnetical fields can be considered instantaneous (Nunez and Srinivasan, 2006). Thus signals at different EEG/MEG sensors from one source have no phase lag. Consequently, only the real part of the cross-spectral density matrix captures this instantaneous correlation and should be used to derive the filter."

In Fieldtrip there is the possibility to have both complex and real filters using cfg.dics.realfilter='yes'. I would suggest to do the same in mne. I personally use real filters only for the above arguments. To get real filters, , we should simply change for example line 67 in _dics.py.

From:
Cm = data_csd.data
To:
Cm = data_csd.data.real

Or maybe you have implemented this option somewhere else in the code I am missing.
NB: this issue is strongly related to #3832
Thanks

**Comment by agramfort** [comment]
I was not aware of this feature in fieldtrip and this Hipp argument.

I would add an option for this in the function.

can you open a PR?

**Comment by brovelli** [comment]
Yep, I'll open a PR
