### ISSUE TITLE
coregistration error

### ISSUE THREAD

**Issue by romquentin** [mne-tools/mne-python#3844]
Hi, 
When I am running 
`coregistration(inst=fname, subject='sub29', subjects_dir=freesurf_subject_path)`
I have this error:
The 'subject' trait of a MRISubjectSource instance must be '', but a value of 'sub29' <type 'str'> was specified.
Do you have an idea what is wrong? (I am using 0.14dev version)
Thank you!
Romain

**Comment by christianbrodbeck** [comment]
Looks like "sub29" is not a valid subject in your subjects_dir, or not recognized as such

**Comment by romquentin** [comment]
Yes, the path was not good... Thank you!
