### ISSUE TITLE
BUG: Plotting TFR with non-linear frequency spacing

### ISSUE THREAD

**Issue by nwilming** [mne-tools/mne-python#3847]
I've computed a TFR decomposition with logarithmically spaced frequencies. Calling `plot` on the resulting AverageTFR objects shows plots with wrong frequency labels.

Digging a bit deeper I found that plotting is done with a call to matplotlib's imshow function (in `mne.viz.topo._imshow_tfr`)  and then using the `extent` keyword to put appropriate labels onto the plot. However, these labels only work for uniform linearly spaced labels. 

The following example illustrates this point:
```
x, y = logspace(log10(4), log10(150)), logspace(log10(4), log10(150))
Z = dot(x[:, newaxis],(y[newaxis,:]*0)+1)
extent = (x.min(), x.max(), y.min(), y.max())
subplot(1,2,1)
imshow(Z, origin='lower', cmap='gray', extent=extent, aspect='auto')
title('imshow')
subplot(1,2,2)
pcolormesh(x, y, Z, cmap='gray')
ylim([y.min(), y.max()])
xlim([x.min(), x.max()])
title('pcolor')
```
![log_spacing](https://cloud.githubusercontent.com/assets/623604/21183762/b79696bc-c209-11e6-92c2-fa864d738b60.png)

`pcolor` correctly displays the spacing between points on the x and y-axis, but imshow does not. The imshow plot gives the impression that values for 80 on the y-axis are low (black), while they actually are quite high (gray). 

One way to fix this would be to use `pcolormesh` instead of `imshow` for plotting. The only tricky thing would be to get the edges right that are needed for `pcolormesh`. I have a test implementation of a `_pcolormesh_tfr` that I could share. But I suspect fixing this behavior would need changes to a all of the plotting functions in AverageTFR - insofar I'd be interested in your opinion on how to best fix this issue.

**Comment by mmagnuski** [comment]
I had this issue before. The problem is that theoretically you can have arbitrary spacing in your freqs of interest. Simplest solution would be to allow log y axis (or detect this automatically). Another simple solution is to just change the y tick labels (this is what I have been doing so far). The y extent is still linear then however and adding things onto the axis (bounding boxes highlighting ROI for example) might give unexpected results.

**Comment by agramfort** [comment]
indeed this needs a fix.

PR or at least a gist welcome

thx

**Comment by Eric89GXL** [comment]
> The problem is that theoretically you can have arbitrary spacing in your freqs of interest. 

That isn't really a problem if we use a `pcolor` variant like `pcolormesh` because it will take that spacing into account.

Yes please open a PR for the `pcolormesh` version if you're up for it

**Comment by mmagnuski** [comment]
@Eric89GXL ok, I actually never used `pcolormesh`. Can you still have interpolation then?

**Comment by Eric89GXL** [comment]
You can do `shading='gouraud'` which might be the same

**Comment by Eric89GXL** [comment]
Actually according to the `mpl` folks there is a `NonUniformImage` class we can use.

@mmagnuski do you have time to try it in the next couple of days? It would be good to get this in for 0.14. If not, I can probably do it.

**Comment by mmagnuski** [comment]
Yes, I can work on this this week. I looked into the mpl example of NonUniformImage and it is perfect for this indeed.
