### ISSUE TITLE
spatial_colors takes into account channels that are not plotted (ref meg)

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#3862]
I think ref_meg channels are included when "normalizing" the channel positions to RBG space, but not plotted. This means the available color range is not fully used when ref_meg channels are included.

With ref_meg
![unknown-149](https://cloud.githubusercontent.com/assets/4321826/21278477/acd1b0bc-c3db-11e6-93f8-5588ce6677bb.png)
Without ref_meg
![unknown-145](https://cloud.githubusercontent.com/assets/4321826/21278476/ab2bad12-c3db-11e6-8126-2974ad3ceae4.png)

@jaeilepp if you have time, otherwise I will do it.

**Comment by kingjr** [comment]
These graphs are just both so beautiful & diagnostic, you should make a viz paper.
