### ISSUE TITLE
EDF voltage values are of by factor e^6

### ISSUE THREAD

**Issue by skjerns** [mne-tools/mne-python#3863]
After the [slow reading of EDF]( https://github.com/mne-tools/mne-python/issues/3852) has been quickly fixed, I discovered another bug:

My EDF values are too large. So -0.297696020398689 becomes -297696.0203989165 with MNE.
This does not seem to be the case with all files though.

**Comment by skjerns** [comment]
I now discovered that there is a self._raw_extras[units] field which is `1e-06` for other files and `1` for my EDF file, which explains the voltage issue (seems to be a problem with my file).

**Comment by Eric89GXL** [comment]
Probably a setting during recording, then?
