### ISSUE TITLE
compute_proj_exg filtering

### ISSUE THREAD

**Issue by Teekuningas** [mne-tools/mne-python#3864]
Hello,

Could someone explain why is the raw data filtered in compute_proj_exg? As copy=False as default it seems to me that when the projection vectors are finally applied when epoching, the data where the projection vectors were calculated is different than the data where they are applied. Does this not matter?

Thanks,

**Comment by agramfort** [comment]
you should use the mailing list for such question but anyway.
An SSP vector is a spatial transform and you need the best SNR to estimate
it.
So you can fit it on band-pass filtered data and then apply it to broad
band signals.

HTH

**Comment by Teekuningas** [comment]
Ok, thanks. It makes sense

-- Tk
