### ISSUE TITLE
When using mne.viz.iter_topography, on_pick callback is called with pyplot instance instead of the axes

### ISSUE THREAD

**Issue by Teekuningas** [mne-tools/mne-python#3871]
This is the line:

https://github.com/mne-tools/mne-python/blob/master/mne/viz/topo.py#L223

Shouldn't it be the axes? This would suggest so: http://martinos.org/mne/stable/auto_examples/visualization/plot_topo_customized.html

Thanks,
Tk

**Comment by agramfort** [comment]
what fix do you suggest?

**Comment by Teekuningas** [comment]
As even the docstring of the iter_topography says: 

"on_pick : callable | None
        The callback function to be invoked on clicking one
        of the axes. Is supposed to instantiate the following
        API: `function(axis, channel_index)`",

I would be as daring as replacing the line "show_func(plt, ch_idx)" with "show_func(ax, ch_idx)" and let people fix their code (they can always introduce pyplot themselves if they want minimal changes)..

-- Tk

**Comment by Eric89GXL** [comment]
+1 that sounds like a bug in our implementation

Are you up for making a PR?

**Comment by Teekuningas** [comment]
I can do that, yes

-- Tk

**Comment by agramfort** [comment]
thanks !
