### ISSUE TITLE
mne.viz.plot_topomap() for MEG data and extracting the pos parameter.

### ISSUE THREAD

**Issue by DominiqueMakowski** [mne-tools/mne-python#3878]
Hey,

I have an array of MEG data corresponding to averaged values for 306 channels (MAG: 102, GRAD: 204). I'd like to visualize a topographic plot of this map. However, the `mne.viz.plot_topomap()` requires a `pos` argument that I have no idea how to extract from the `raw` object.

Moreover, as my data has two channel types (GRAD and MAG), it won't infer it from the raw.info object. 

How can I extract the `pos` parameter or make my way around the `Multiple channel types` problem?

Thanks!!

**Comment by jona-sassenhagen** [comment]
Pick the info object with pick_types? The help should say that IIRC

**Comment by DominiqueMakowski** [comment]
but it seems that `pick_types()` only allows for a global `meg` parameter that picks both GRAD et MAG channel types, thus making it impossible to plot using `mne.viz.plot_topomap()` 😢

**Comment by agramfort** [comment]
@DominiqueMakowski make an EvokedArray using the info from the sample dataset and then use the evoked.plot method.

**Comment by DominiqueMakowski** [comment]
It works!

Here's the code:

```python
values  # (306, ) numpy array
values = np.array(values, ndmin=2).T  # Transpose it to a 2D array
evoked = mne.EvokedArray(values, raw.info, tmin=0)  # Convert it to a EvokedArray
evoked.plot_topomap(times=0)
```

Thanks 😄
