### ISSUE TITLE
CNT files with event_type == 3

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#3882]
A friend has a recent CNT file that fails to be read in. The reader assumes `event_type` to be either 1 or 2, but here it is 3.

Minimally, I think we'd just have to go from
`elif event_type == 2:`
to
`elif event_type > 1:`

I can make a PR later.

@jaeilepp

**Comment by jaeilepp** [comment]
The best [documentation](http://paulbourke.net/dataformats/eeg/) I've been able to find says that it should be either 1 or 2.
```
typedef struct {
   char Teeg;                   /* Either 1 or 2                           */
   long Size;                   /* Total length of all the events          */
   long Offset;                 /* Hopefully always 0                      */
} TEEG;
```
Not sure what 3 means...
Also, it seems that there are a lot of cnt files that don't really conform to these definitions, so the reader maybe needs a revision anyway, but it's hard to find good docs on this.

**Comment by wmvanvliet** [comment]
we can take the code from eeglab as a reference.
