### ISSUE TITLE
FSAverage data

### ISSUE THREAD

**Issue by christianbrodbeck** [mne-tools/mne-python#3903]
@Eric89GXL I noticed that you added the MNE fsaverage data at mne/data/fsaverage, and it looks like they are in the manifest too, so they will be distributed right? We could use those in the coregistration GUI instead of asking for MNE-C?

**Comment by Eric89GXL** [comment]
I added what was in MNE-C's `share` directory, yeah. Not sure if it's sufficient for the `coreg` GUI or not, but if you only look for MNE-C for files related to `fsaverage` then it should be enough.
