### ISSUE TITLE
ENH: plot_white rotation

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#3907]
From Matti on the listserv:

> y’ = lambda^(-1)U^t y
> y’’ = U lambda^(-1)U^t y
> the y’’ data have their original spatial meaning and the values are SNRs or “z scores”.  Since the whitened data are sphered, they can be rotated in any way. Maybe there is even another more interesting rotation than U.

I suspect we do the former but the latter would be more useful I think. @dengemann I think you worked on this the most, do you agree?

**Comment by agramfort** [comment]
evoked.plot_white does y'' (ie rotates back) otherwise the whitened evoked
would not look like a butterfly as in
https://mne-tools.github.io/dev/auto_examples/visualization/plot_evoked_whitening.html

**Comment by Eric89GXL** [comment]
Ahh okay, good
