### ISSUE TITLE
make_watershed_bem still requires MNE-C tools

### ISSUE THREAD

**Issue by bloyl** [mne-tools/mne-python#3930]
I just noticed that make_watershed_bem still requires MNE-C tools to be installed.

https://github.com/mne-tools/mne-python/blob/master/mne/bem.py#L1060-L1063

Is that intentional? They don't seem to used as I just ran through without them.

**Comment by Eric89GXL** [comment]
Yeah that looks like a bug to me, PR welcome to fix it

**Comment by jaeilepp** [comment]
This got fixed in https://github.com/mne-tools/mne-python/pull/3931
