### ISSUE TITLE
Read in EGI GPS Digitization Coordinates

### ISSUE THREAD

**Issue by mattboggess** [mne-tools/mne-python#3953]
To the best of my knowledge, MNE does not currently support reading in digitization files using EGI's GPS digitization process. An example file can be found [here](https://drive.google.com/file/d/0B-D6HZYNzLixTmowV19reWtTQWs/view?usp=sharing). I was hoping to integrate this functionality into MNE. I'd be willing to put in time and effort to do so, but was hoping for guidance on best approach for this integration. Thanks!

**Comment by Eric89GXL** [comment]
For now you'd want to modify the `read_dig_montage` function / `DigMontage` class. Take a look at those and see if the necessary changes make sense

**Comment by mattboggess** [comment]
I'm confused about the distinction between elp and hpi? Similarly, elp seems required to be set for both plotting the montage and transforming the coordinates though for the EGI montage only the fiducials and electrode positions are relevant. I'm not sure I understand what elp is supposed to contain?

**Comment by Eric89GXL** [comment]
`hpi` are in MEG device space, `elp` are in digitizer space. So they're the same points in two different coordinate systems. They should only be necessary for determining an MEG<->head transformation

**Comment by Eric89GXL** [comment]
I think this one was solved by PR
