### ISSUE TITLE
Unit of measure for raw data in mne.io.RawArray

### ISSUE THREAD

**Issue by kaczmarj** [mne-tools/mne-python#3970]
I am trying to load EEG data from a `numpy` array into an `mne.io.RawArray` object. What is the correct unit of measure for the data in the array? Volts? I looked through the source for `mne.create_info`, and it looks like the unit should be volts. Can anyone confirm?

Thank you.

**Comment by Eric89GXL** [comment]
Yes volts. Do you have time to open a PR to clarify the documentation for
the next person?

**Comment by kaczmarj** [comment]
I could do that. Because a class like `RawArray` can accept more than just EEG data, how would you suggest I add the proper unit of measure to the documentation?

**Comment by Eric89GXL** [comment]
Probably a bulleted list. To keep it slightly shorter, you can organize it by type:
```
* V: eeg, eog, seeg, emg, ecg, bio, ecog
* T: mag
* T/m: grad
* M: hbo, hbr
* Am: dipole
* AU: misc
```
And I guess it should probably go in `create_info`, too / instead of `RawArray`?

**Comment by kaczmarj** [comment]
Thanks. I think it would make sense to include that list in the docstring of each `*Array` class, and in the notes of `create_info`.

**Comment by Eric89GXL** [comment]
Sounds good to me

**Comment by agramfort** [comment]
this tutorial should be edited too:

http://martinos.org/mne/stable/auto_tutorials/plot_creating_data_structures.html

**Comment by kaczmarj** [comment]
To edit that tutorial, would I edit https://github.com/mne-tools/mne-python/blob/master/tutorials/plot_creating_data_structures.py ?

**Comment by agramfort** [comment]
yes exactly
