### ISSUE TITLE
Maxwell filter does not update dev_head_t.

### ISSUE THREAD

**Issue by jaeilepp** [mne-tools/mne-python#4008]
When passing an array as the ``destination`` to ``maxwell_filter``, the ``dev_head_t`` is not updated. This prevents concatenating epochs from different runs. [Example](https://github.com/mne-tools/mne-biomag-group-demo/blob/master/scripts/processing/02-maxwell_filtering.py).

**Comment by Eric89GXL** [comment]
You have `st_only=True`, the `destination` has no effect / the data are not transformed. So no bug here
