### ISSUE TITLE
ENH: Better evoked.comment from epochs[cond].average()

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#4012]
From the mailing list, people get `epochs[cond].average().comment == 'Unknown'`.

Deep in our code it uses `epochs.name`, which I didn't even know existed, but defaults to `Unknown`. We could set this name to something at least when doing `epochs[cond]`, which would then propagate to `epochs[cond].average()`.

**Comment by agramfort** [comment]
+1

**Comment by jaeilepp** [comment]
Also, the ``name`` attribute is not saved or read.

**Comment by Eric89GXL** [comment]
From `git grep` it looks like `epochs.name` is almost unused. And if it's not read/written it's not very useful. I'm +1 for getting rid of it.

**Comment by jaeilepp** [comment]
> I'm +1 for getting rid of it.

Me too.

**Comment by jaeilepp** [comment]
On further investigation, it seems that it tries to read it, but the save function does not save it. There is also a FIFF constant for it.

**Comment by jaeilepp** [comment]
So I'm wondering if we should stick to the old way, but just make sure it gets saved?

**Comment by Eric89GXL** [comment]
I can live with that. So we fix the save, and fix the comment creation.
