### ISSUE TITLE
slider example is broken

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-python#4033]
went to try to run an example but it didn't work. I think there might be something run with the `mne.datasets.sample.data_path()`. is it still https://s3.amazonaws.com/mne-python/datasets/MNE-sample-data-processed.tar.gz?

here is the ex.
http://martinos.org/mne/dev/auto_examples/visualization/make_report.html#sphx-glr-auto-examples-visualization-make-report-py

cc: @dengemann

**Comment by teonbrooks** [comment]
nvm it somehow fixes itself when I pulled the latest mne version

**Comment by teonbrooks** [comment]
UPDATE: download is now located at https://mne-tools.s3.amazonaws.com/datasets/MNE-sample-data-processed.tar.gz

**Comment by dengemann** [comment]
Mysterious magic :)
