### ISSUE TITLE
ENH: find peak for vector sum

### ISSUE THREAD

**Issue by jjnurminen** [mne-tools/mne-python#4035]
Many¹ Elekta users like to analyze combined gradiometer data. `mne.viz.plot_evoked_topo` supports this via the `merge_grads` argument. Should `mne.Evoked.get_peak()` support a similar argument?

¹anecdotal evidence

**Comment by agramfort** [comment]
I would say yes

**Comment by jjnurminen** [comment]
I could whip up a PR.
