### ISSUE TITLE
add on_missing argument to EpochsArray

### ISSUE THREAD

**Issue by cmmoenne** [mne-tools/mne-python#4041]
As `on_missing`'s default is set to `'error'` on `BaseEpochs`, `EpochsArray` will always raise a *"ValueError: No matching events found for ..."* when epochs are not found in some condition. This is not always desirable, so control `on_missing` from `EpochsArray` would be very useful.

**Comment by Eric89GXL** [comment]
Sounds reasonable to me, can you make a PR?

**Comment by cmmoenne** [comment]
yep, I can!

...as I was super lazy with PR #3965 (I work in my master instead of branching), I will wait for that PR first. I never thought I'd be doing another PR so soon... shame on my 😞
