### ISSUE TITLE
raw.set_montage should return self

### ISSUE THREAD

**Issue by mmagnuski** [mne-tools/mne-python#4044]
Currently `raw.set_montage(montage)`  does not return anything so I get `None`.
It would be nice if it returned self so I could chain it with other operations:
```
raw = mne.io.read_raw_eeglab(fname, preload=True).filter(1, None).set_montage(montage)
```

**Comment by Eric89GXL** [comment]
Agreed, +1 for PR

**Comment by Akshay0724** [comment]
I will like to work on this issue for start. Thanks

**Comment by agramfort** [comment]
this is done
