### ISSUE TITLE
ENH: slider widget

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#4050]
Would be nice to get that for the topomap slider:

https://github.com/janfreyberg/niwidgets

**Comment by jasmainak** [comment]
maybe something @parulsethi can look into after her current PR

**Comment by parulsethi** [comment]
Sure, i'll see to this after current one

**Comment by Eric89GXL** [comment]
We almost certainly need to speed up our topomap code to make this usable. @jaeilepp have you looked at all to see where we can make speed gains? Maybe we need to use some lower-level `matplotlib` object, given that we know things like sensor positions don't change time point to time point.

**Comment by kingjr** [comment]
Yes, and perhaps reduce default resolution

**Comment by larsoner** [comment]
Since this is a Jupyter<->MPL thing I think it's mostly out of scope
