### ISSUE TITLE
Q?: how to add layout to info

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#4051]
I'm trying to plot an home-made EEG dataset (e.g. `evoked = mne.EvokedArray([[0, 0], [0, 0]], info=mne.create_info(2, sfreq=1))`)

I made a layout and I can do `evoked.plot_joint(topomap_arg=dict(layout=layout))`. However the plot doesn't show Jona's spatial colors because `plot_joint()` looks for the layout in the evoked instance.

Is there a way to add a `layout` to an evoked/info?

**Comment by teonbrooks** [comment]
do you have a Montage or can you make it into one? that could be added with `.set_montage`

**Comment by kingjr** [comment]
I'm confused. I thought a montage was used to do like bipolar construct etc.

I just want to include the layout, i.e. be able to plot the data based on the position of the electrodes.

I tried

```python
montage = mne.channels.Montage(layout.pos[sel], np.array(layout.names), 3, range(len(layout.names)))
raw.set_montage(montage)
mne.io.write_info('eeg_layout-info.fif', raw.info)
info = mne.io.read_info('eeg_layout-info.fif')
```

But this just load my RAM forever

**Comment by kingjr** [comment]
(i.e. reading the resulting info leads to an infinite loading...)

**Comment by kingjr** [comment]
And on the same topic, the following code fails for non-explicit reasons. I think we may need to revision of the Montage functions.

```python

import mne
from mne.io import read_raw_edf
from mne.datasets import eegbci
from mne.channels import read_layout

raw = read_raw_edf(eegbci.load_data(1, [6])[0], preload=True)
raw.rename_channels(lambda x: x.strip('.'))

# Setup layout
layout = read_layout('EEG1005')
montage = mne.channels.Montage(
    pos=layout.pos[:, :2],
    ch_names=layout.names,
    kind='standard_1005',
    selection=range(len(layout.names)))
raw.set_montage(montage)

# Read write
fname = 'eeg_layout-info.fif'
raw.info = mne.io.write_info(fname, raw.info) # ok
info = mne.io.read_info(fname)  # fails

```

**Comment by Eric89GXL** [comment]
Yes, see #3893

**Comment by Eric89GXL** [comment]
(This is one potential target for me during the sprint.)

**Comment by larsoner** [comment]
Closing as a doc problem covered by #3893
