### ISSUE TITLE
bug viz in plot_sensors_time_frequency

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#4060]
see what I get when running plot_sensors_time_frequency.py

![figure_5](https://cloud.githubusercontent.com/assets/161052/23850050/2184e2a8-07de-11e7-9205-d51934b52f8a.png)

**Comment by mmagnuski** [comment]
I'll take a look tomorrow and make a few adjustments to tick placement.
I'm generally not sure whether adding support for unequal y-scale (#3905) was such a good thing - the time-freq image type is now different and has less intuitive organization of data so things like adding transparency masks would be harder.
