### ISSUE TITLE
BUG: RSA example is skipped

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#4066]
http://mne-tools.github.io/dev/auto_examples/decoding/decoding_rsa.html?highlight=rsa 

doesn't create the image, we probably need to just change the name of the example.

**Comment by Eric89GXL** [comment]
Yes `plot_`

**Comment by jaeilepp** [comment]
I think we left this without the ``plot`` because of the size of the dataset.

**Comment by agramfort** [comment]
yes it's too much for Circle CI

**Comment by kingjr** [comment]
ok

**Comment by Eric89GXL** [comment]
We should add a note
