### ISSUE TITLE
ENH: cross_val_multiscore

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#4068]
Scikit-Learn only accepts scorer that output a float (although see https://github.com/scikit-learn/scikit-learn/pull/7388)

This make it limiting for mass-multivariate analyses like TimeDecoding and GeneralizationAcrossTime.

I suggest we add our own `cross_val_multiscore` that score the estimator but allows outputing an array of score

e.g.

```python
def cross_val_multiscore(est, X, y, cv=5, **kwargs):
    """cross-validated scores when each score is an array rather than a number.
    """
    if isinstance(cv, int):
        cv = StratifiedKFold(cv, random_state=0)
    scores = list()
    for train, test in cv.split(X, y):
        est.fit(X[train], y[train])
        scores.append(est.score(X[test], y[test]))
    return np.mean(scores, axis=0)
```

**Comment by jona-sassenhagen** [comment]
I think this can be closed after #4103? Good to have this!
