### ISSUE TITLE
Consistency in naming freqs vs. frequencies

### ISSUE THREAD

**Issue by choldgraf** [mne-tools/mne-python#4116]
It looks like most of the TFR-style functionality calls it `freqs`:

https://github.com/mne-tools/mne-python/search?utf8=%E2%9C%93&q=freqs&type=

while the stats and connectivity style objects call it `frequencies`:

https://github.com/mne-tools/mne-python/search?utf8=%E2%9C%93&q=frequencies&type=

Should we standardize this?

**Comment by Eric89GXL** [comment]
I'm okay to go with a deprecation cycle to unify around `freqs`

**Comment by dengemann** [comment]
+1

**Comment by jona-sassenhagen** [comment]
Somewhat related:
https://github.com/mne-tools/mne-python/issues/3164
https://github.com/mne-tools/mne-python/issues/3702

**Comment by agramfort** [comment]
+1
