### ISSUE TITLE
BIDS I/O Functionality

### ISSUE THREAD

**Issue by choldgraf** [mne-tools/mne-python#4127]
@jasmainak you have a function to convert an MNE object to BIDS format, yes? I think it'd be a nice and relatively quick project to expose something like this that we could put into an example. WDYT? I'm happy to sit down and think through it if you like, or adapt your code to MNE.

**Comment by teonbrooks** [comment]
- [ ] move it to the I/O module
- [ ] write to bids
- [ ] handle how MNE reads a bids folder structure
- [ ] finish the first round of this
- [ ] make a report for a BIDS directory

**Comment by teonbrooks** [comment]
cc: @chrisfilo

**Comment by teonbrooks** [comment]
closing since we now know have [mne-bids](https://github.com/mne-tools/mne-bids), which will be handling making files BIDS-compatible. inspired [here](https://github.com/mne-tools/mne-python/pull/4128#issuecomment-296484714)
