### ISSUE TITLE
create_ecg_epochs crashes if data is not preloaded

### ISSUE THREAD

**Issue by ARudiuk** [mne-tools/mne-python#4137]
I found this error when I ran create_ecg_epochs before create_eog_epochs. 

create_eog_epochs will preload the data when it creates the epochs, and then create_ecg_epochs will run fine. 
However, create_ecg_epochs will crash on data that is not preloaded, if run first. This happens when it tries to run the line `raw.add_channels([ecg_raw])` which needs the data to be preloaded.

You can easily recreate this error by running create_ecg_epochs on raw_fif data that has not been preloaded. I can create an example if need be, I can also create a pull request to fix this if you want me to. My solution to the problem would just be preloading the data though, not sure if that is too naive of an approach or not.

**Comment by agramfort** [comment]
please open a PR.

thx
