### ISSUE TITLE
psd_welch default n_fft value 

### ISSUE THREAD

**Issue by ARudiuk** [mne-tools/mne-python#4147]
I was wondering if this is the intended behaviour for the psd_welch function  

If you run psd_welch on data that has less than 256 time points you get the error message 

> raise ValueError(('If n_per_seg is None n_fft is not allowed to be > '
>                           'n_times. If you want zero-padding, you have to set '
>                           'n_per_seg to relevant length. Got n_fft of %d while'
>                           ' signal length is %d.') % (n_fft, n))

And, the docmentation says:

>     n_fft : int
>         The length of FFT used, must be ``>= n_per_seg`` (default: 256).
>         The segments will be zero-padded if ``n_fft > n_per_seg``.
>     n_per_seg : int | None
>         Length of each Welch segment. The smaller it is with respect to the
>         signal length the smoother are the PSDs. Defaults to None, which sets
>         n_per_seg equal to n_fft.

To me the two solutions seem to be:
- specifying in the documentation that n_fft also has to be <= n_times 
or
- default the n_fft value to n_times 

Thanks!

**Comment by agramfort** [comment]
+1 for :

> specifying in the documentation that n_fft also has to be <= n_times
