### ISSUE TITLE
gitter on website

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#4176]
It could be interesting to add a snippet to gitter: (https://sidecar.gitter.im/)

**Comment by Eric89GXL** [comment]
I'm -0.5 on this. I think it would clutter the already busy page. I actually think if we can go the opposite direction and simplify the landing page it would be better.

If we set up a dedicated "Get help" page (could be a useful top-level link!) then we could embed it there, and I'd be +1 for that.

**Comment by kingjr** [comment]
Make sense

**Comment by agramfort** [comment]
done it's at bottom now
