### ISSUE TITLE
Data size computed with double precision but written in single precision.

### ISSUE THREAD

**Issue by jaeilepp** [mne-tools/mne-python#4180]
cf. mailing list. 64 bit epoch data is split to multiple files if saving the whole data would take more than 1GB.

It seems that if the epoch data is in 64bit format the size calculation is not done correctly. I suppose the correct fix would be to check the data type before computing the size of the data matrix.

There is probably a good reason the data cannot be saved as 64bit?

**Comment by Eric89GXL** [comment]
> There is probably a good reason the data cannot be saved as 64bit?

64-bit arrays are not well supported outside of MNE-Python.

>  I suppose the correct fix would be to check the data type before computing the size of the data matrix.

Yeah you should use the *output* data type to determine the split.
