### ISSUE TITLE
ica.plot_properties with gradiometers throws reshape error

### ISSUE THREAD

**Issue by jdue** [mne-tools/mne-python#4185]
I wanted to use ica.plot_properties with an ICA object having only gradiometers, however, reshape throws a ValueError in _merge_grad_data complaining "ValueError: total size of new array must be unchanged" (python 2) or "ValueError: cannot reshape array of size 202 into shape (0,2,newaxis)" (python 3). 

Following the tutorial from http://martinos.org/mne/stable/auto_tutorials/plot_artifacts_correction_ica.html but replacing meg=True with meg="grad" in the line where picks_meg is defined also exhibits this behavior (otherwise, the magnetometers seem to be used and everything is fine).

It seems that ica.get_components()[:,idx] (in _plot_ica_topomap) returns an array of size (n_chan,), np.atleast_2d transforms to (1,n_chan) but _merge_grad_data expects (n_chan, n_times), hence the error in _merge_grad_data in the line "data = data.reshape((len(data) // 2, 2, -1))".

Hope the issue is clear and that I didn't overlook something obvious. I am not an experienced programmer so let me know if you need any other information.

I am using MNE version 0.14 on Windows and tested it under python 2.7 and 3.6.

**Comment by jaeilepp** [comment]
Thanks for the bug report. Fix coming up.
