### ISSUE TITLE
`contours` argument in viz.topomap's plot_tfr_topomap doesn't behave as described

### ISSUE THREAD

**Issue by hubertjb** [mne-tools/mne-python#4197]
According to the docstring of viz.topomap's `plot_tfr_topomap()` function,  if `contours=0`, no contour lines will be plotted. However, I get two contour lines (`_set_contour_locator()` actually returns two contours).

Also, if `contours=False`, I get the same result as for `contours=0`. This seems to be because `isinstance(contours, int)` in `_set_contour_locator()` returns True for bool.

Finally, if `contours` is 1, 2, 3, etc. I always get one more contour than expected (2, 3, 4, etc.).

Am I right in my understanding of what `contours` is supposed to do or is there a reason for this behaviour? Maybe @jona-sassenhagen would know?

**Comment by jaeilepp** [comment]
Fix at https://github.com/mne-tools/mne-python/pull/4203. FYI it is also possible to pass a list as the ``contours``. So you could set the contours just outside the data range to have none plotted.
