### ISSUE TITLE
How did we set up the auto-gallery for API pages?

### ISSUE THREAD

**Issue by choldgraf** [mne-tools/mne-python#4200]
I think either @Eric89GXL or @agramfort did this, so pinging them...

I'm trying to help Nelle migrate Matplotlib to sphinx-gallery. One thing we'd like to do is get the API docs to start including sphinx gallery thumbnails automatically, kinda like this page:

http://martinos.org/mne/stable/generated/mne.read_epochs.html#mne.read_epochs

It seems [from the docs](http://sphinx-gallery.readthedocs.io/en/latest/advanced_configuration.html#linking-to-documentation) like you need to create your own template file, and then specify this template file anywhere in the docs that the API gen stuff is happening?

Who set this up for MNE? I'd love a quick runthrough of how to do this if it's possible...

**Comment by agramfort** [comment]
everything is there:

https://github.com/mne-tools/mne-python/blob/master/doc/conf.py#L301

there was not much magic / hacking to make it work

**Comment by dengemann** [comment]
Also see mne-hcp repo where these conf params are adjusted.

**Comment by choldgraf** [comment]
What is the purpose of `'mod_example_dir': 'generated'`? I can't see any mention of it on the sphinx gallery website but it's in both of these projects

**Comment by Eric89GXL** [comment]
It has been renamed to `backreferences_dir` and we are just behind the times

**Comment by choldgraf** [comment]
ahh I see - ok so both will work, that's good to know. I'm gonna leave this open for a little bit because I may wanna ping you guys about this but I'll close it soon

**Comment by choldgraf** [comment]
(unless you'd rather talk offline about it, but I figured it's useful to have up here for posterity)

**Comment by Eric89GXL** [comment]
We can continue to talk here as necessary but I'll close it so it doesn't show up as an open issue
