### ISSUE TITLE
mne.viz.plot_trans failed

### ISSUE THREAD

**Issue by romquentin** [mne-tools/mne-python#4206]
Hi mne-python experts

I have an issue running:

`plot_trans(epochs.info, trans=None, subject=freesurf_subject, dig=True,
           meg_sensors=True, subjects_dir=subjects_dir, brain=True)`

it gives me this error:

/Applications/anaconda/lib/python2.7/site-packages/mne-python/mne/viz/_3d.pyc in _fiducial_coords(points, coord_frame)
     52     points_ = dict((p['ident'], p) for p in points if
     53                    p['kind'] == FIFF.FIFFV_POINT_CARDINAL)
---> 54     return np.array([points_[i]['r'] for i in FIDUCIAL_ORDER])
     55 
     56 

KeyError: 1

I am running on macOS X El capitan and with mne.0.15dev.
The error seems to be not present on mne.0.13stable.

Thank you

Romain

**Comment by Eric89GXL** [comment]
We should add a check for this. 

But you have strange data -- you have digitization points but no fiducials?

**Comment by romquentin** [comment]
I have 3 digitization points corresponding to the fiducials in surface_MRI coordinate system.

**Comment by Eric89GXL** [comment]
Ahh yes, this problem again :) Okay we can make `plot_trans` work in the short term and make it actually plot those properly in the long term.

**Comment by romquentin** [comment]
Yes :)
Ok. Thank you!

**Comment by Eric89GXL** [comment]
Can you try #4069 to see if it fixes your problem?

**Comment by romquentin** [comment]
It fixed it! Thank you!

**Comment by Eric89GXL** [comment]
Should be fixed in `master` now
