### ISSUE TITLE
BUG: coregistration translation / rotation not working

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#4229]
The rotation and translation changes seem to have no consequence. I'm not sure whether this is because these options don't update the points, or whether it's a pur viz issue.

- Checking out what changed in the previous PRs, #3940 seems to have fixed an analogous failure to update (viz of?) the *scaling*.

- I use the default fsaverage wiht the following hand-made electrode locations: https://ufile.io/2ctfn

- Adding fiducials didn't seem to change the problem.

- there is no warning or error displayed in the terminal

![ezgif-1-109ed7d6cd](https://cloud.githubusercontent.com/assets/4881164/25492746/f6ce2290-2b41-11e7-87e7-adfa64cbdb76.gif)

@christianbrodbeck

**Comment by kingjr** [comment]
The problem disappears when I add nasion/lpa/rpa in the digmontage => https://ufile.io/4i4x9

It seems that the translation and rotation are dependent on these variable (but IMO, they shouldn't).

**Comment by christianbrodbeck** [comment]
Yes, we should probably show an error message when a digitizer instance without nasion is specified; coregistration with a center other than nasion would have to be implemented (see https://github.com/mne-tools/mne-python/issues/3934#issuecomment-275425957)

**Comment by kingjr** [comment]
I took me a while to understand why I could only work the fix for 'sample' but not 'fsaverage'. Turns out, I need to create a mock `subjects/fsaverage/bem/fsaverage-fiducials.fif` file.

IMO we shouldn't throw an error if nasion etc are missing. You should be allowed to do coregistration purely on the sensors if you know where they are.

**Comment by christianbrodbeck** [comment]
> IMO we shouldn't throw an error if nasion etc are missing. You should be allowed to do coregistration purely on the sensors if you know where they are.

Agreed, I suggested a temporary solution until someone can work on it

**Comment by larsoner** [comment]
I think this has been fixed by recent coreg changes
