### ISSUE TITLE
montage topoplot differs from eeg_projection plot

### ISSUE THREAD

**Issue by pbrusco** [mne-tools/mne-python#4231]
Hi! 

I'm having trouble plotting topoplots. 

Executing:
```python
montage_file = "/tmp/LNI.sfp"
montage = mne.channels.read_montage(montage_file)
```

I get 
![3d](https://cloud.githubusercontent.com/assets/1205576/25506882/438aa274-2b7f-11e7-8665-d00a508042e5.png)

which seems to be perfect. 

But then, when I execute 
```python
info = mne.create_info(montage.ch_names, sfreq=512.0, ch_types="eeg", montage=montage)
eeg_layout = mne.channels.make_eeg_layout(info)
eeg_layout.plot()
```
I get:

![2d](https://cloud.githubusercontent.com/assets/1205576/25507043/29b0486c-2b80-11e7-8f49-923270e4ce1f.png)

which is wrong (90 degrees wrong (?) )

Any ideas?

I have the same problem with plot_topomap that uses the same 2d projection. 

Here the montage_file: https://gist.github.com/pbrusco/b55824af996652156e6ecfcfc830de05

**Comment by jaeilepp** [comment]
Looks like your montage file is not in RAS coordinates. You need to switch x and y coordinates (and flip left to right by the looks of it). I wonder how common this is. Maybe there should be an option for switching between coordinate systems.

**Comment by Eric89GXL** [comment]
It could be a coordinate system problem, or it could just be that our reader assumes something about the ordering of data in the file format, and it's violated here. @pbrusco do you have time to dig into our code a bit to find out?

**Comment by pbrusco** [comment]
Hi! Thanks for the responses. 

I'm not sure what should I check. 

I'm using a .sfp file (that is a EEGlab supported format (matlab)).

When I plot it using Matlab I see the following. 

![image](https://cloud.githubusercontent.com/assets/1205576/25550587/a025ae80-2c50-11e7-8f66-d33c0aa2f036.png)

The file is exactly what I posted on: https://gist.github.com/pbrusco/b55824af996652156e6ecfcfc830de05

Thanks! let me know how can I help specifically if you need.

**Comment by agramfort** [comment]
see this:

https://github.com/mne-tools/mne-python/blob/master/mne/io/eeglab/eeglab.py#L91

you need indeed to do something equivalent to:

locs = np.r_[-loc_y, loc_x, loc_z]

as EEGLAB uses a different coordinate system by default

**Comment by pbrusco** [comment]
Hi, thanks for the information. 

But I have a doubt anyway. Why is it that montage.plot(show_names=True) show the right positions of the electrodes. Isn't that inconsistent? 

Changing montage.pos = new_positions works. 

Thanks a lot!

**Comment by agramfort** [comment]
are all the sfp you have access to flipped the same way?

i think we need a fix or a documentation

**Comment by pbrusco** [comment]
I'm not sure actually. That's the standard for EEGLab sfp I think but I'm not sure in general.

**Comment by agramfort** [comment]
can you share a few of such files so we can test and avoid this issue in
the future?
