### ISSUE TITLE
epochs_image: smoothing happens before sorting, extreme overlay_times handling

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#4232]
1. I think epochs.plot_image could handle `overlay_times` exceeding the data window better:

![unknown-246](https://cloud.githubusercontent.com/assets/4321826/25542247/08602f4c-2c52-11e7-99a9-41ad53e2f87d.png)

E.g., either the x axis of the ERP below should be scaled to the image, or the extreme overlay_times should be dropped, or something like that.

2. I think the image interpolation/smoothing should happen on the *sorted* image, cause otherwise the sorting essentially doesn't do anything:

![unknown-247](https://cloud.githubusercontent.com/assets/4321826/25542245/04d0e646-2c52-11e7-8a62-9e456124e3d8.png)

@agramfort do you agree?

**Comment by agramfort** [comment]
agreed for both. For 2 it's a bug. Smoothing has to be done after sorting.

**Comment by jona-sassenhagen** [comment]
Fix for # 2 in #4227. For # 1, what should we do - censor the overlay_times? Drop the epochs? Keep the x axis for the image and the evoked plot aligned?

**Comment by jona-sassenhagen** [comment]
Closed by #4227 and #4535
