### ISSUE TITLE
"What's new" isn't easy to find

### ISSUE THREAD

**Issue by choldgraf** [mne-tools/mne-python#4249]
I tried looking around for the what's new page but couldn't find it. Where is it discoverable with the current website?

**Comment by Eric89GXL** [comment]
"MNE-Python code updates" on the front page

**Comment by choldgraf** [comment]
Ah I see it now. I'm a little concerned at how long it took me to find that. Why not put links to "what's new" at the top of the documentation page or something like this? Also why not call it "what's new" since that's a standard nomenclature for OS projects? (e.g., I did `ctrl-f` "what's new" and didn't find anything...probably wouldn't have thought to do "code updates")

**Comment by Eric89GXL** [comment]
I wanted to avoid "what's new" because it's more of a changelog than a nicely-narrated news page (devs probably expect the former but users might expect the latter). But if you think what's new is clear enough then that's fine by me.

**Comment by choldgraf** [comment]
I don't think it needs to be called "what's new" necessarily, I just want it to be easy to find :-) I think it is partially a challenge of having all the logos in the top-right, it's not useful information for users and it makes me basically just discount the right sidebar in general :-(  perhaps putting it in the documentation page would be fine. WDYT?

**Comment by choldgraf** [comment]
looking back through the page I just realized this is partially because chrome was using 120% zoom, which was causing the logos to push all of the text below the "fold" of my initial computer screen view. So I don't think it's as bad as I originally said it was, but perhaps still worth having a link in the documentation?

**Comment by Eric89GXL** [comment]
I'll take a minute and try a reorganization (since we haven't stressed @agramfort enough with the last one)

**Comment by choldgraf** [comment]
haha this is true, we should be careful or we'll give him a disincentive to attend coding sprints ;-)

**Comment by agramfort** [comment]
hum...

I have to admit it also took me some time to find where the what's new page
was...

FYI sklearn calls this page "what's new" :)

**Comment by Eric89GXL** [comment]
See #4250
