### ISSUE TITLE
Supported File Type

### ISSUE THREAD

**Issue by jarrja** [mne-tools/mne-python#4266]
I am using XLTEK EEG which produces EEG files, .eeg, .erd, .ent, Are these file types supported in MNE?

**Comment by agramfort** [comment]
it's not presently supported but it's possible.

would you have time to give it a try?

**Comment by jarrja** [comment]
I tried working with the mentioned file types, but I can't seem to successfully read them. I found that the best way is to convert the file from the machine to .edf

**Comment by agramfort** [comment]
ok closing
