### ISSUE TITLE
BUG: mne.make_field_map indicate wrong `origin` parameter

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#4268]
There's a mismatch between docs and actual default parameter. 

I'm not sure what the param should be.

cc @Eric89GXL

**Comment by Eric89GXL** [comment]
We usually try to use `'auto'`, so we should probably change it to that as a bugfix

**Comment by kingjr** [comment]
does auto take the center of the electrodes or of a sphere fit to the head ?

**Comment by Eric89GXL** [comment]
sphere fit to the head digitization

**Comment by kingjr** [comment]
I started to make a fix by changing the default parameter value, but it
creates a series of error in the tutorials and in the tests, so I'll let
you guys deal with it

**Comment by Eric89GXL** [comment]
For now we can just fix the documentation to reflect the actual default then.

**Comment by kingjr** [comment]
(0, 0, 0.04) is a very weird default parameter IMO

**Comment by Eric89GXL** [comment]
it is approximately where the origin fit usually ends up for adult subjects

**Comment by kingjr** [comment]
yes, I had guessed, but this kind of numerical guess can lead to very
weird-looking results, without a clear warning, so I would recommend doing
either a real fix, or just explicitly use these numbers in the tests and
tutorials that crash with the 'auto' parameter.
