### ISSUE TITLE
BUG in the website: No contribute page

### ISSUE THREAD

**Issue by yousrabk** [mne-tools/mne-python#4269]
Neither the [github.io](https://mne-tools.github.io/stable/contribute_to_mne.html) nor the [martinos](http://martinos.org/mne/stable/contribute_to_mne.html) stable version gives a contribute page. It is though working for the [dev](http://martinos.org/mne/dev/contributing.html#) version.

**Comment by kingjr** [comment]
It's a dead link problem, the page is here:
http://martinos.org/mne/stable/contributing.html#

cc @Eric89GXL

**Comment by Eric89GXL** [comment]
It is already fixed in `dev`, my solution would be just to wait for release. The number of people who miss the contributing page in the meantime is probably small
