### ISSUE TITLE
Add an example for creating channel neighborhoods with triangulation?

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#4272]
Creating channel neighborhoods (for e.g. cluster-based permutation tests) is non-trivial for the math impaired. I was just asked by another researcher if this was possible in MNE. Maybe we could have something like this gist as an example?

https://nbviewer.jupyter.org/gist/jona-sassenhagen/4d5db1a30ef47f26de468aeec4e04dd6

**Comment by Eric89GXL** [comment]
Yes please add an example if you have time. Although you can save a number of lines by using `spatial_tris_connectivity` once you have the triangulation

**Comment by Eric89GXL** [comment]
... and we can't use `_find_topomap_coords` so we'll have to find a better way to do that
