### ISSUE TITLE
Add function to plot montage (channel locations)

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#4275]
As mentioned in #4273, it is not straightforward to plot channel locations of a given montage. Here's a function that might be convenient when a user just wants to visualize channel locations without having to load any data:

```Python
import mne
from mne.channels.montage import _set_montage


def plot_montage(montage):
    if isinstance(montage, str):
        montage = mne.channels.read_montage(montage)
    info = mne.create_info(montage.ch_names, sfreq=256, ch_types="eeg")
    _set_montage(info, montage)
    mne.viz.plot_sensors(info, show_names=True)


plot_montage("biosemi32")
```

In which module should this function go? Right now, it only plots EEG channels - are there montages for other channel types available and should these be taken into account as well? Does this function need other arguments (such as an option to show only a subset of channels, an option to hide names, etc)?

**Comment by jaeilepp** [comment]
I think it would be appropriate to change the ``plot`` method to reuse the ``plot_sensors`` code. Note that ``create_info`` takes a ``montage`` param you can use instead of calling ``_set_montage``.

**Comment by cbrnr** [comment]
Alright, so this becomes:

```Python
import mne


def plot_montage(montage):
    if isinstance(montage, str):
        montage = mne.channels.read_montage(montage)
    info = mne.create_info(montage.ch_names, sfreq=256, ch_types="eeg",
                           montage=montage)
    mne.viz.plot_sensors(info, show_names=True)


plot_montage("biosemi32")
```

Which `plot` method do you mean?

**Comment by jaeilepp** [comment]
``montage.plot``

**Comment by cbrnr** [comment]
Yes, this would make sense as currently only a 3D plot can be created.
