### ISSUE TITLE
default for mask_type

### ISSUE THREAD

**Issue by jjnurminen** [mne-tools/mne-python#4286]
Hi,
I was recently a bit surprised by the fact that when finding trigger events with a mask, `mne.find_events` defaults to `mask_type='not_and'`, whereas the `AcqParserFIF` class defaults to `mask_type='and'`

I cannot recall now if this was done deliberately, or is it a mistake?

**Comment by agramfort** [comment]
I guess it's a mistake.

**Comment by jjnurminen** [comment]
I guess this is related to #3284 
and it seems that `mask_type='and'` is (was?) supposed to become the default behavior?

**Comment by agramfort** [comment]
possibly :)

**Comment by jjnurminen** [comment]
@Eric89GXL is it so that `mask_type='and'` was supposed to become default behavior for `mne.find_events` by 0.14?
