### ISSUE TITLE
use nilearn.plotting.plot_surf for plotting surface data

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#4288]
Nilearn can plot static surface data in matplotlib (and thereby, the notebook and py3). Considering how often Mayavi drives @kingjr into an existential crisis, maybe adding this as an alternative is worth a try.
The code isn't complicated.

http://nilearn.github.io/modules/generated/nilearn.plotting.plot_surf.html

**Comment by agramfort** [comment]
see https://github.com/mne-tools/mne-python/pull/4086

**Comment by kingjr** [comment]
I also like the 3-view glass brain of nilearn for a diagnostic (non
interactive) plotting

**Comment by agramfort** [comment]
sounds like we have a volunteer :)

**Comment by jona-sassenhagen** [comment]
I have to finish a bunch of other PRs first sadly.

**Comment by jona-sassenhagen** [comment]
See https://github.com/nilearn/nilearn/issues/1461

Minimally, we could just give an example and possibly a bit of glue for integration with nilearn.

**Comment by jona-sassenhagen** [comment]
(Essentially, mapping from an stc or labels to the stat_map of nilearn's plot_surf would be super low effort and would allow quick visualisation of surface locs.

I agree with @kingjr  on the glass brain.)

**Comment by agramfort** [comment]
there is now an stc.plot with matplotlib backend
