### ISSUE TITLE
BUG: Loose != None is permitted in volume source spaces

### ISSUE THREAD

**Issue by joewalter** [mne-tools/mne-python#4308]
I am wondering how the loose parameter are used with volume or mixed source spaces. It is possible to make an inverse operator with a volume source space with loose not being None. The log says "Converting to surface-based source orientations" even with volume source space. But is that really what one wants to have? I think that while using a mixed source space it could be useful to apply loose to surface based source spaces as a cortical constraint, but not to volume source spaces. But I don't see in the code that MNE discriminates between types of source spaces while applying the loose parameter. Any hints?

**Comment by agramfort** [comment]
you cannot use ori and loost with a volume source space

**Comment by joewalter** [comment]
But is there a test or is it set automatically anywhere? Does that imply that loose is not possible in mixed source spaces?

**Comment by agramfort** [comment]
no it should crash. If it's not the case it needs a fix.

**Comment by joewalter** [comment]
It is possible to run plot_mixed_source_space_inverse.py with loose=0.2 and depth=0.8 without crash.

**Comment by agramfort** [comment]
is it simply ignored then?

**Comment by joewalter** [comment]
The log says "Creating the depth weighting matrix..." and "Applying loose dipole orientations. Loose value of 0.2.", so it doesn't seem to be ignored.

**Comment by Eric89GXL** [comment]
Dup of #2163. Keeping this open and re-titling as a bug

**Comment by agramfort** [comment]
this needs a fix :(

**Comment by Eric89GXL** [comment]
Sure, but whatever fix is implemented needs to be considered in the context of #2163

**Comment by joewalter** [comment]
@haribharadwaj do you have any suggestions?

**Comment by Eric89GXL** [comment]
I think the API proposal was `loose=dict(surf=..., discrete=..., volume=...)`. I'm okay with making `loose=float` an alias for `loose=dict(surf=float, discrete=float, volume=None)`. This is a backward-incompatible change but probably qualifies as a bugfix.

**Comment by joewalter** [comment]
I'll give it a try

**Comment by larsoner** [comment]
I think we have taken care of this in a recent PR, closing
