### ISSUE TITLE
ENH?: SSP on SSS data mag/grad

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#4330]
If we do SSP after SSS perhaps we want to do grad+mag jointly, since they are no longer independent. @agramfort does this make sense to you?

Currently, IIRC sometimes if we do SSP after SSS we sometimes don't end up reducing the rank of the data.

**Comment by dengemann** [comment]
Sounds interesting. It could also benefit from the low rank computation that I plan to work on after we merge #4329.

**Comment by agramfort** [comment]
I've never thought about this

**Comment by larsoner** [comment]
Moving to 0.18, I think it will make the most sense with the cov reg PR anyway

**Comment by larsoner** [comment]
This has been implemented
