### ISSUE TITLE
Plot effects of maxfilter on raw.

### ISSUE THREAD

**Issue by jaeilepp** [mne-tools/mne-python#4331]
I came across a use case where the user wanted to plot the effects of maxfiltering on top of raw data. Currently this is not easy to do. Do you think there would be wider interest in doing this? If so, I can take a look.

**Comment by agramfort** [comment]
You mean overlay raw and mf data e.g. In raw.plot?

**Comment by dengemann** [comment]
Maybe at the level of power spectra I could see this to be more generally
useful. An example would suffice.

**Comment by jaeilepp** [comment]
> You mean overlay raw and mf data e.g. In raw.plot?

Yeah, something like that.

**Comment by agramfort** [comment]
too much work on our side. You can hack this making a new raw with twice
more channels interleaved.

**Comment by jaeilepp** [comment]
Ok, closing.
