### ISSUE TITLE
ENH: add support for Micromed EEG data

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#4359]
Hi there,

while being in Bari I have learned that the popular Micromed format for EEG with .TRC file extension is not readily supported in MNE. It seems however, EEGLAB and other toolboxes support it. Since this format is especially popular in Italy it would be really great to add support for it.

I will try to get some testing data.

**Comment by sappelhoff** [comment]
closing this in favor of https://github.com/mne-tools/mne-python/issues/10524, as there is more discussion in that thread and both threads have the same goal.
