### ISSUE TITLE
ENH: sklearn wrapper for common transformers and estimators?

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#4366]
I'm find myself re-writing the same ~8 import line across my analyses to import all of sklearn's little function (cross_val, Ridge, LogisticRegression, StandardScaler, PCA etc). 

Do you think it would be useful to have a wrapper such that our meta-estimator (e.g. `mne.decoding.LinearModel`, `mne.decoding.UnsupervisedSpatialFilter`) accepts strings: e.g.

```python
LinearModel('LogisticRegression')
LinearModel('StandardScaler, Ridge')
UnsupervisedSpatialFilter('PCA')
```

**Comment by agramfort** [comment]
no

use snippets and shortcuts in your editor.

please close. It's not a bug.
