### ISSUE TITLE
MEG Interpolation

### ISSUE THREAD

**Issue by Chrisinger** [mne-tools/mne-python#4377]
Dear MNE-community,

I am currently trying to interpolate some bad MEG channels with MNE.
Unfortunately there seems to occur an exception, such that the resulting
channels hold only zeros. Even when I try to interpolate only one
channel I get from '_field_interpolation.py:80' the log
'Truncate at 0 missing 0.0001'
As I understand it, this happens because the eigenvalues are all too
small. My data contains of 248 channels measured at ~291000 time steps.

I am currently stuck there, with no idea remaining. Can you give me a
hint what else I could try to get at least some interpolation for my bad
channels?

As suggested, I attached a minimal example.

[interpol.zip](https://github.com/mne-tools/mne-python/files/1136430/interpol.zip)

Thanks in advance, Christoph

**Comment by agramfort** [comment]
@Eric89GXL are you on it?

**Comment by Eric89GXL** [comment]
This example runs with no problem on my machine. Can you try updating to latest MNE `master` to see if it fixes the problem?

If it doesn't, what is your `mne.sys_info()`?

**Comment by Eric89GXL** [comment]
... oh wait, the channel is all zero. I'll see if I can make sense of it.
