### ISSUE TITLE
Remove deprecated imp module

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#4378]
Currently, `mne/commands/utils.py` still uses the deprecated `imp` module, which has long been replaced with `importlib`. According to [this answer on SO](https://stackoverflow.com/a/67692/1112283), the current solution works only on Python 3.5/3.6, and there is a (deprecated) alternative for Python 3.3/3.4. All versions < 3.3 need to use `imp`.

How should this be handled in MNE?

**Comment by agramfort** [comment]
can you send a PR that uses importlib on recent python and imp otherwise?
