### ISSUE TITLE
drop_channels without preloading

### ISSUE THREAD

**Issue by skjerns** [mne-tools/mne-python#4381]
I remember in a previous version I was able to drop channels without preloading the data.

Now this is not possible anymore.

What would be the most simple (and fastest) way to get all data from a certain selection of channels as a numpy array?

Right now I'm loading all data with `header.load_data()` and then I extract the channels with `header.get_data([0,1,2])`. I fear that somewhere on the way there might be a memory leakage (I had this before), as my memory consumption is far above the final numpy array nbytes. One way to avoid that is to call `header.pick_channels([0,1,2])` but then I'm loading all data just to discard 80% of it.

**Comment by agramfort** [comment]
no need to preload to get the data of a few channels

raw = read_raw_xxx(..., preload=False)
data, times = raw[picks, :]

**Comment by skjerns** [comment]
great, thanks! works perfectly. Who would have thought that's so easy (well probably it was at an obvious point in the manual that I didn't see).

**Comment by Eric89GXL** [comment]
> well probably it was at an obvious point in the manual that I didn't see

I'd rather think of it as, if you looked and didn't see it, it wasn't obvious enough. Where did you look? Any time to make a PR to add a line to help the next person?

**Comment by skjerns** [comment]
I expected to find that at http://martinos.org/mne/stable/manual/memory.html

But also generally at http://martinos.org/mne/stable/manual/#reading-your-data

I'll try to add that to the docs in the next days.

**Comment by agramfort** [comment]
> I'll try to add that to the docs in the next days.

thanks a lot.

**Comment by jaeilepp** [comment]
I believe this is solved.
