### ISSUE TITLE
issues in test_docstring_parameters

### ISSUE THREAD

**Issue by amueller** [mne-tools/mne-python#4385]
The way that walk_packages is called in the docstring tests that got ported to scikit-learn means that the tests only work when called from a specific location. Also it misses all subpackages.
The right call should look like 
```python
                      for pckg in walk_packages(prefix='mne.',                                                                
                                                path=mne.__path__) 
```

**Comment by Eric89GXL** [comment]
We currently call:
```
for importer, modname, ispkg in walk_packages(mne.__path__, prefix='mne.'):
```
And I think you're just suggesting to change the `arg` to a `kwarg` as `path=mne.__path__`, but [path is the first argument](https://docs.python.org/3.6/library/pkgutil.html#pkgutil.walk_packages) so this shouldn't matter. I must be missing something...?

**Comment by amueller** [comment]
Huh, ok. I didn't look at the code, but the code @agramfort copied to sklearn looked very different. Your seems to be fine.

**Comment by Eric89GXL** [comment]
He probably copied over an old version long ago. Thanks for checking back in any case
