### ISSUE TITLE
bug? writing fixed fwd

### ISSUE THREAD

**Issue by joewalter** [mne-tools/mne-python#4393]
As discussed with @agramfort the following code results in an error in `assert_allclose`:

```
import os.path as op
from numpy.testing import assert_allclose
from mne.datasets import testing
from mne import read_forward_solution, write_forward_solution
from mne.utils import _TempDir

data_path = testing.data_path(download=False)
fname_meeg_grad = op.join(data_path, 'MEG', 'sample',
                          'sample_audvis_trunc-meg-eeg-oct-2-grad-fwd.fif')
fwd_fixed = read_forward_solution(fname_meeg_grad, surf_ori=True,
                                  force_fixed=True)
temp_dir = _TempDir()
fname_temp = op.join(temp_dir, 'test-fwd.fif')
write_forward_solution(fname_temp, fwd_fixed, overwrite=True)
fwd_fixed_io = read_forward_solution(fname_temp)
assert_allclose(fwd_fixed['sol']['data'], fwd_fixed_io['sol']['data'])
```
In my opinion, the reason is line 749 in forward.py, which is `if fwd['surf_ori'] is True`, so it tries to rotate fixed fwd, too. Replacing this line with `if fwd['surf_ori'] is True and fwd['source_ori'] == FIFF.FIFFV_MNE_FREE_ORI:` fixes the problem.

If confirmed, I can add this bugfix to #4372.

**Comment by agramfort** [comment]
I think it's better to fix bugs in separate PRs. It makes things simpler to review. Is it possible? thx
