### ISSUE TITLE
N_max_eog parameter in ICA artifact detection?

### ISSUE THREAD

**Issue by ryscet** [mne-tools/mne-python#4417]
[Artifact Correction with ICA](http://martinos.org/mne/stable/auto_tutorials/plot_artifacts_correction_ica.html) Tutorial usues a variable `n_max_eog`. This variable is never used, where could it be used? If not used, should it not be removed from the tutorial?

**Comment by jaeilepp** [comment]
I suppose it's just for selecting only the best component. So you could do something like ``eog_inds = eog_inds[:n_max_eog]``. I think it can just be removed from the tutorial.

**Comment by agramfort** [comment]
indeed

fixed in 1b1d3bc2c

thx @ryscet
