### ISSUE TITLE
Unable to pick electrodes in raw.to_data_frame() method

### ISSUE THREAD

**Issue by hadrienj** [mne-tools/mne-python#4436]
I try to convert few electrodes to dataframe from raw data. I use the method `to_data_frame()` but I can't get it work if I select electrodes in no order. For instance this is working:

```python
raw.to_data_frame(picks=[0, 1, 2], stop=10)
```

But this doesn't:

```python
raw.to_data_frame(picks=[0, 1, 3], stop=10)
```
I get the following error:

> .../lib/python2.7/site-packages/mne/io/base.pyc in to_data_frame(self, picks, index, scale_time, scalings, copy, start, stop)
>     170                 idx = [picks[i] for i in range(len(picks)) if types[i] == t]
>     171                 print idx
> --> 172                 if len(idx) > 0:
>     173                     data[:, idx] *= scaling
>     174         else:
> 
> IndexError: index 3 is out of bounds for axis 1 with size 3

Thank you!

**Comment by jaeilepp** [comment]
Looks like a bug. I'll see what I can do...
