### ISSUE TITLE
Missing xlabel with spatial_colors=True when plotting evoked responses

### ISSUE THREAD

**Issue by jdue** [mne-tools/mne-python#4472]
Attempting to plot an evoked response (from an evoked object) I have encountered the issue that the xlabel ('Time (ms)') is removed from all subplots when spatial_colors is set to True, e.g.,

    evoked.plot(spatial_colors=True)

The code responsible for this seems to be (in viz.evoked, lines 277-8)

    for ax in fig.axes[:-1]:
        ax.set_xlabel('')

which, without spatial_colors=True, exhibits (what I suppose is) the desired behavior, i.e., to retain only the xlabel of the bottommost butterfly plot. With spatial_colors=True, however, the first axes in fig.axes seem to be the subplots whereas the last axes are the projection of the channels onto the head (showing their position) and so all xlabels are removed (irrespective of the number of modalities plotted).

One way to solve this could be to change the above code to
    
    if len(ch_types_used) > 1:
        for ax in fig.axes[:len(ch_types_used)-1]:
            ax.set_xlabel('')
        
to only consider the subplot axes. This seems to solve the issue for me at least (whether plotting one or several modalities).

I am using MNE 0.14.1.

**Comment by agramfort** [comment]
@jdue it's indeed still broken in master. Can you open a PR?
