### ISSUE TITLE
ENH/VIZ: display .nave by default in plot_evoked

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#4484]
I was thinking repeatedly for months that having the .nave output by default in the title or so of plot_evoked would be so useful. What do you think?

cc @jona-sassenhagen @mmagnuski

**Comment by larsoner** [comment]
A parenthetical after the condition name would be nice

**Comment by jona-sassenhagen** [comment]
Probably better than what we have right now :)

**Comment by dengemann** [comment]
> A parenthetical after the condition name would be nice

yes

> Probably better than what we have right now :)

and yes.

Great, so it seems some people like it. Let's do it! Marking as easy.

**Comment by dengemann** [comment]
@massich maybe something you could like to look into, relaxing from pytests.

**Comment by mmagnuski** [comment]
I like that too :)

**Comment by dengemann** [comment]
> I like that too :)

great!

**Comment by thesujitroy** [comment]
Hi,
Can I get some reference to the problem and what sort of script is required to be written.
And this is related to which objective.

**Comment by thesujitroy** [comment]
Or if I can get some doc to look into

**Comment by dengemann** [comment]
Hi @thesujitroy have a look at some of the basic tutorials that compute evoked responses and call ```evoked.plot()```. You will notices that no information on the number of averages (nave) is present. The idea is to find a way to show the evoked.nave attribute when plotting. mne.viz.plot_evoked needs to be updated for that. I hope this helps.

**Comment by thesujitroy** [comment]
Alright. Thank you

**Comment by thesujitroy** [comment]
I  am taking this issue.

**Comment by dengemann** [comment]
Great! Don't hesitate moving in small steps. It is bettet to start
somewhere and communicate early. Perfection comes in iterations.

**Comment by thesujitroy** [comment]
Hi,
I was going through the code and it seems that nave is declared to be 1.
However, in plot_evoked the attribute needs to be added. But I cant understand the attributes we are trying to show is evoked.nave, this needs to show in plot in what form.
Can the Number of averages be more than 1, and are trying to put it in butterfly plot?

**Comment by jasmainak** [comment]
> But I cant understand the attributes we are trying to show is evoked.nave, this needs to show in plot in what form.

See comment [from above](https://github.com/mne-tools/mne-python/issues/4484#issuecomment-322205698)

> Can the Number of averages be more than 1, and are trying to put it in butterfly plot?

It's the number of trials used in the average for the evoked, i.e., evoked.nave

**Comment by jona-sassenhagen** [comment]
@thesujitroy any progress?
