### ISSUE TITLE
DOC: Return value of ICA.apply

### ISSUE THREAD

**Issue by aweinstein** [mne-tools/mne-python#4499]
The method ICA.apply returns the processed object. However, its [documentation](https://martinos.org/mne/stable/generated/mne.preprocessing.ICA.html#mne.preprocessing.ICA.apply) does not list the return value.

Along the same lines, ICA.apply seems to change in place the data instance. It might be a good idea to mention this behavior in the documentation (as a new user I was surprised by this).

**Comment by agramfort** [comment]
indeed

can you send a PR to update the docstring?

thanks

**Comment by aweinstein** [comment]
I can, and I will. But before doing that, can you clarify the rationale for changing the raw data in place, and also returning the modified data? 

I ask because perhaps is better to keep only one of the two behaviors.

Alejandro

**Comment by larsoner** [comment]
It goes against what most Python packages do, but we decided it was worth it to have long chains like:
```
raw.copy().load_data().pick_types(meg=True).filter(None, 40)
```

**Comment by aweinstein** [comment]
I just send PR #4500.
