### ISSUE TITLE
Issue w/ fill_mean in `ReceptiveField`

### ISSUE THREAD

**Issue by choldgraf** [mne-tools/mne-python#4514]
From @nbara 

> Isn't there a small bug Line 414 of receptive_field.py ? delayed[...] = fill_value is over-indented isn't it? Meaning the fill_value is effectively only applied when epoch_axis is not None?

I took a look and think this is true...we should fix this!

**Comment by larsoner** [comment]
Yes feel free to make a PR w/test (true TDD!)

**Comment by choldgraf** [comment]
thanks @nbara for pointing this out!
