### ISSUE TITLE
Capitalization in axis labels

### ISSUE THREAD

**Issue by bgagl** [mne-tools/mne-python#4534]
Hey guys 
amazing stuff your are doing ...
just wondered if it would be possible to switch the default for axis labeles to first letter capitalized (e.g. from time [ms] to Time [ms])? 

Would be great as it is a requirement for several journals ... (Nature: Lettering in figures (labelling of axes and so on) should be in lower-case type, with the first letter capitalized and no full stop.)

Cheers
Ben

**Comment by dengemann** [comment]
Hey Benjamin (it's you I hope), thanks!
I think the better thing to watch our for is how to edit matplotlib figures.
The idea would be that you get the axis text objects for the titles and
just replace them.
See here:
https://stackoverflow.com/questions/11244514/modify-tick-label-text
Keep in mind that our plotters are in the end providing convenient short
cuts for matplotlib but do not and cannot replace matplotlib.

Denis

**Comment by bgagl** [comment]
Hi Denis, 
yes its me ;) 
ok I see. Unfortunately, I like e.g. the plot_joint function very much and as far as I can see you would recommend to take the code and customize the figure directly with the code itself.
Cheers

**Comment by dengemann** [comment]
But you can do that! All plotting functions return matplotlib figure
handles. You can edit any detail of a figure post-hoc using matplotlib.

**Comment by jona-sassenhagen** [comment]
Maybe we should do a tutorial for styling default figure outputs.
(I'm comfortable with matplotlib, but arguably it's pretty arcane to use. MNE is a lot more beginner friendly than matplotlib!)

On the other hand, if journals require capitalisation, why should we return all-lower case in the first place? We're implicitly making a choice either way, so why the one to return lower case?

**Comment by dengemann** [comment]
We can do both :)

**Comment by jona-sassenhagen** [comment]
Who is "we" :D

But yes, you're right.

**Comment by agramfort** [comment]
> On the other hand, if journals require capitalisation, why should we
return all-lower case in the first place? We're implicitly making a choice
either way, so why the one to return lower case?

same feeling. Can you build case for capitalisation ? then we could change
all our defaults.

**Comment by cbrnr** [comment]
And while we're at it, "Time [ms]" is wrong, units should be in parens and not brackets, so it should be "Time (ms)" (not that I think MNE is using brackets, but it might be worth checking).
