### ISSUE TITLE
colormap of individual maps in evoked.plot_joint()

### ISSUE THREAD

**Issue by timmidee** [mne-tools/mne-python#4538]
This one will probably end up with @jona-sassenhagen .

Is appears that when all data are positive at a time-point passed for the argument "times", the colormap of the individual topography at that time-point is set to "reds". Which I believe is standard behavior for the function that plots the topomap. It doesn't adhere to the colorbar though. It is particularly striking pre t=0 in the attached image (but can also happen later in the time series).

Explicitly passing the colormap as an argument in topomap_args helps, but perhaps this can be handled more elegantly? It took me a while to notice. Sometimes it can be fairly obscured (like all electrodes around a strong peak being a "little too red").

![unknown-27](https://user-images.githubusercontent.com/25376820/30123451-53d91532-9332-11e7-9264-0aed4a5b4269.png)

**Comment by larsoner** [comment]
Yeah the `plot_joint` should look at all data points, the topomap ones individually, to determine the colormap to use for all of the topomaps

**Comment by jona-sassenhagen** [comment]
@jaeilepp do you have time? Or should I do it?

Or maybe you want to do it yourself, @timmidee

**Comment by agramfort** [comment]
@jaeilepp <https://github.com/jaeilepp> is not working with me anymore but
maybe he needs a break with his new job :)

**Comment by jona-sassenhagen** [comment]
@timmidee I can't replicate the problem. Can you share the evoked dataset and the precise call to plot_joint?

**Comment by timmidee** [comment]
`times = (-.190,-.030,-.010,.100,.275,.460)

topomap_args = dict(average = .05,cmap='RdBu_r')

sk_sacSinCoef.plot_joint(times = times, topomap_args=topomap_args,
                           title='rERP estimated effect of continuous covariate fixIncSac SIN',
                           ts_args= None);`

Note the difference at -10 and 275ms when omitting the cmap from topomap_args.
This one does not mess up the colorbar, but that happens when the first map is set to cmap='reds'.
I assume that will fix itself once all maps get the same colormap ;-)

[weird_map-ave.fif.zip](https://github.com/mne-tools/mne-python/files/1288413/weird_map-ave.fif.zip)

![unknown-23](https://user-images.githubusercontent.com/25376820/30220243-fc505bf2-94be-11e7-99b6-668e681651b5.png)
![unknown-22](https://user-images.githubusercontent.com/25376820/30220248-ff27379c-94be-11e7-8aae-251031fc0bfe.png)

**Comment by jona-sassenhagen** [comment]
Hm. I still can't replicate this. I get the 1st plot regardless of if I include a cmap or not. Has this somehow been fixed already?

**Comment by jona-sassenhagen** [comment]
The crucial lines are probably:

```
    norm = min(data) >= 0
    vmin, vmax = _setup_vmin_vmax(data, vmin, vmax, norm)
    if cmap is None:
        cmap = 'Reds' if norm else 'RdBu_r'
```
here
https://github.com/mne-tools/mne-python/blob/9ac6547284bbd73b4c18d7d7031042585388005c/mne/viz/topomap.py#L606

**Comment by timmidee** [comment]
I can't try right now, but looking at the code you cite (with the risk of saying something stupid here):

If this is done on a map-to-map basis then isn't that the problem?
I.e. the overarching function (plot_joint()) should look at the data for _all_ maps and then consistently pass the colormap to plot_topomap()?

Or perhaps I'm missing the structure of what function calls and/or passes what here. In that case let me know. I'll give this another try with the latest version of MNE when I have easy access to my work machine again.

**Comment by larsoner** [comment]
Closing as it sounds like this has been fixed, but @timmidee if you still see this on `master` please reopen
