### ISSUE TITLE
Description of rescale mode 'percent' wrong?

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#4557]
The docstring of the `rescale` function in `mne/baseline.py` (and in seven other places where this docstring has been copied and pasted) currently states for the `mode` argument:

    percent is the same as applying ratio then mean

The calculation is:

    data -= mean
    data /= mean

So I think the description should be the other way round, namely:

    percent is the same as applying mean then ratio

Besides, a line in the docstring exceeds the PEP8 line length:

    mode : None | 'ratio' | 'zscore' | 'mean' | 'percent' | 'logratio' | 'zlogratio'

**Comment by agramfort** [comment]
PR welcome
