### ISSUE TITLE
Import error from EEGLAB

### ISSUE THREAD

**Issue by pbrusco** [mne-tools/mne-python#4564]
Hi! When importing epochs from EEGLAB, the function __init__ from io/eeglab/eeglab.py has a condition:
`if not isinstance(ep.eventtype, string_types):` and then treats the event as an array of events. 

The problem is that sometimes, the eventtype is a number (not an array), so, we add this as a patch:
```                
eventype = str(ep.eventtype)
if not isinstance(eventype, string_types):
```
And then we replace `ep.eventtype` for `eventype` and it seems to work. Any idea if this is the right way to solve it or we are missing something? 

Thanks!

**Comment by jasmainak** [comment]
are you sure you are using the latest version of mne?

I think this was addressed here: https://github.com/mne-tools/mne-python/pull/3912. Or did I misunderstand your problem?

**Comment by pbrusco** [comment]
Hi, sorry I didn't find the other issue, but yes, that was the problem.

Now, I tried with 0.15.dev0 and when the event is an int it's working. 

But, when the array contains ints, then it explodes again :). 

the solution I found, change 
```python
event_type = '/'.join(ep.eventtype.tolist())
``` 
for 
```python 
event_type = '/'.join(map(str, ep.eventtype.tolist()))
```

Thanks!

**Comment by agramfort** [comment]
please share the problematic set file.

**Comment by pbrusco** [comment]
Here it goes. 
[set_file.zip](https://github.com/mne-tools/mne-python/files/1306717/set_file.zip)

**Comment by agramfort** [comment]
thanks for sharing.

please share a gist that produces the crash (saves us time)

also if you can send us a pull request so we clearly see the diff for your
changes it's even better.

thanks a lot

**Comment by jona-sassenhagen** [comment]
In general ... @jasmainak do you have time to do this?

**Comment by jasmainak** [comment]
see: https://github.com/mne-tools/mne-python/pull/4581/
