### ISSUE TITLE
No amplitude from evoked.get_peak()

### ISSUE THREAD

**Issue by jjnurminen** [mne-tools/mne-python#4575]
Wouldn't it be logical for `evoked.get_peak()` to also return the max amplitude? 
I coded this myself into a script that uses `get_peak()`, but I had to:

-arrange a new data matrix and channel names according to the pair grads logic
-find the index of the channel with maximum amplitude

`get_peak()` would already do these for free. However returning the amplitude would break API, as a 3-tuple of outputs would be needed.

**Comment by larsoner** [comment]
We can add a return_amplitude to avoid API breakage

**Comment by jjnurminen** [comment]
Yep. Then that would also be needed for the underlying machinery of `_get_peak()`.

**Comment by larsoner** [comment]
`_get_peak` is private you can modify the API without adding an argument

**Comment by jjnurminen** [comment]
Ahh, of course.

**Comment by larsoner** [comment]
But in any case, +1 from me for this ENH

**Comment by agramfort** [comment]
no objection

**Comment by jjnurminen** [comment]
Ok, I will try to cook a relevant PR.
