### ISSUE TITLE
UserWarning in decoding_rsa example

### ISSUE THREAD

**Issue by arokem** [mne-tools/mne-python#4577]
Running this example, I get the following warning 
    
    decoding_rsa.py:94: RuntimeWarning: More events than colors available. You should pass a list of unique colors.

**Comment by jona-sassenhagen** [comment]
That's ok I would say. It comes from `plot_events`, and it will happen in many designs because there simply aren't that many distinguishable colours. It's only a warning after all.

Reopen if you disagree.

**Comment by larsoner** [comment]
We should avoid warnings in examples wherever possible. I'd rather we fix
it by doing whatever we would like our users to do in this situation.

**Comment by agramfort** [comment]
+1

**Comment by kingjr** [comment]
remove plot_events, it's unnecessary?

**Comment by larsoner** [comment]
@kingjr can you make a quick PR?

**Comment by ARudiuk** [comment]
Hello, this still seems to be an issue, and I was wondering if I could help? If the fix is to remove plot_events I can do that in a quick pull request.

**Comment by larsoner** [comment]
+1 for removing it

**Comment by agramfort** [comment]
go for it
