### ISSUE TITLE
API: Remove `loose=None`

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#4604]
After ￼ #4562 lands, we should remove `loose=None` support via deprecation.

**Comment by joewalter** [comment]
IIRC, this is already part of #4312.

**Comment by larsoner** [comment]
@joewalter do you want to take parts of #4312 to take care of this? If not, I'm happy to do it. It would be good to get it done quickly though since it's one of the last few remaining 0.15 blockers.

**Comment by larsoner** [comment]
We also need to fix the bug introduced by #4562:

https://circleci.com/gh/mne-tools/mne-python/5918
