### ISSUE TITLE
BUG: Limiting to 15 chars breaks examples

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#4605]
So limiting the output to 15 chars broke the example that uses virtual channels:

https://circleci.com/gh/mne-tools/mne-python/5902

Options:

1. Warn on setting, truncate only on write (round-trip is broke).
2. Change the virtual names not to be `_virtual` anymore but maybe `_v` or something more likely to fit.
3. Change logic for pairing to use channel locations rather than names (harder to do).

We should probably do both (2) and (3) for completeness. Maybe (2) before release and (3) after, for the sake of time.

**Comment by agramfort** [comment]
arfff

let's just add _vl and not _virtual to make it shorter?
