### ISSUE TITLE
BUG: plot_projs_topomap throws RT error for EEG layout

### ISSUE THREAD

**Issue by kambysese** [mne-tools/mne-python#4612]
Here is the gist I used to reproduce the error with sample data
```
import mne
from mne.datasets import sample
from mne.preprocessing import compute_proj_ecg, compute_proj_eog

# getting some data ready
data_path = sample.data_path()
raw_fname = data_path + '/MEG/sample/sample_audvis_filt-0-40_raw.fif'

raw = mne.io.read_raw_fif(raw_fname, preload=True)
raw.set_eeg_reference()
raw.pick_types(meg=True, ecg=True, eog=True, stim=True)
projs, events = compute_proj_eog(raw, n_grad=1, n_mag=1, n_eeg=1)
print(projs)

mne.viz.plot_projs_topomap(projs)
```

Here is the trace

> Traceback (most recent call last):
> File "/home/ktavabi/miniconda3/envs/py2.7/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
> exec(code_obj, self.user_global_ns, self.user_ns)
> File "", line 5, in 
> mne.viz.plot_projs_topomap(projs)
> File "/home/ktavabi/Projects/mne-python/mne/viz/topomap.py", line 264, in plot_projs_topomap
> % proj['desc'])
> RuntimeError: Cannot find a proper layout for projection Average EEG reference
 
@larsoner

**Comment by agramfort** [comment]
I agree that this should work

import mne
from mne.datasets import sample
from mne.preprocessing import compute_proj_ecg, compute_proj_eog

# getting some data ready
data_path = sample.data_path()
raw_fname = data_path + '/MEG/sample/sample_audvis_filt-0-40_raw.fif'

raw = mne.io.read_raw_fif(raw_fname, preload=True)
raw.set_eeg_reference()
raw.pick_types(meg=True, eeg=True, ecg=True, eog=True, stim=True,
exclude='bads')
projs, events = compute_proj_eog(raw, n_grad=1, n_mag=1, n_eeg=1)
print(projs)

layout_eeg = mne.find_layout(raw.info, ch_type='eeg')
layout_grad = mne.find_layout(raw.info, ch_type='grad')
layout_mag = mne.find_layout(raw.info, ch_type='mag')
layout = [layout_eeg, layout_grad, layout_mag]
mne.viz.plot_projs_topomap(projs, layout=layout)

I am thinking that we should allow passing info to plot_projs_topomap so it
can
infer the proper layouts automatically....

here is fails as eeg avg ref has 60 chans and the info has 59 good EEGs :'(
