### ISSUE TITLE
Using CHB-MIT seizure dataset in EDF format

### ISSUE THREAD

**Issue by syedumaramin** [mne-tools/mne-python#4613]
I was wondering how could I use MNE for CHB-MIT seizure dataset classification which does not have stim channel and hence I can not find events.

**Comment by agramfort** [comment]
please share a file or tell us what you typed to try

**Comment by syedumaramin** [comment]
the CHB-MIT eeg database has no annotation channel so how can I use MNE to find events like seizure. 
It gives error that " no STIM channel found

**Comment by agramfort** [comment]
how are stored the annotations? in the edf file?

please give me an example file

**Comment by syedumaramin** [comment]
Here is the link for the files. These are edf files and seperate annotation file but no annotation channel
https://physionet.org/physiobank/database/chbmit/

**Comment by agramfort** [comment]
I have no problem reading a file with current master:

raw = mne.io.read_raw_edf('chb01/chb01_01.edf', stim_channel='auto')

the annotation of seizures are stored outside of the edf AFAIK see
eg chb01_03.edf.seizures

don't bother about stim channel

**Comment by syedumaramin** [comment]
thanks but how can i find events for classification purpose

**Comment by syedumaramin** [comment]
Ho can I find events in a file with no annotation channel

**Comment by agramfort** [comment]
you need to read the seizure file and do the maths to know where it
corresponds to in the file. this is not an MNE problem.

**Comment by syedumaramin** [comment]
@agramfort , thanks

**Comment by nurinathirahh** [comment]
hi @syedumaramin can you share how did you manage to read the .seizure file? i am a beginner in this EEG im having difficulty to read the .seizure using mne. Thank you so much

**Comment by saiful1604008** [comment]
Can anyone share the pre-processing code of CHB-MIT dataset. I am new in EEG and facing difficulty to read the files. My email - u1604008@student.cuet.ac.bd

Thank you

**Comment by drammock** [comment]
@saiful1604008 please use the MNE forum for usage questions. https://mne.discourse.group
