### ISSUE TITLE
"ImportError: No module named parallel" when launching mne

### ISSUE THREAD

**Issue by claire-braboszcz** [mne-tools/mne-python#4615]
Step to reproduce (`python 2.7.12`):

- install `mne` from git using [these instructions](http://martinos.org/mne/dev/install_mne_python.html#install-the-mne-module) (`python setup.py develop`)
- run `mne`

Fix:

In `mne/decoding/search_light.py`, replace `from .parallel import parallel_func` by `from ..parallel import parallel_func`

(since `parallel.py` is not in the same directory, I wonder why it was working for me until yesterday...)

**Comment by agramfort** [comment]
there is 2 "." in our code:

https://github.com/mne-tools/mne-python/blob/master/mne/decoding/search_light.py#L9

**Comment by claire-braboszcz** [comment]
that's weird as I installed from scratch... anyway, good to know

**Comment by agramfort** [comment]
how did you install?
