### ISSUE TITLE
find_ch_connectivity doesn't find EEG templates

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#4631]
It looks like `mne.channels.find_ch_connectivity` only searches for MEG template files. This means that it doesn't work for EEG montages such as e.g. "biosemi64", even though a template exists. I think a note should be added in the docstring to clarify this behavior. Also, the note in `mne.channels.read_ch_connectivity` should be changed. Ideally, a good separation of the two functions is that `read_ch_connectivity` reads from template files whereas `find_ch_connectivity` computes connectivity.

**Comment by agramfort** [comment]
PR welcome

**Comment by cbrnr** [comment]
OK - I guess clarifying the docstrings is sufficient (the other alternative would be to add support for automatic detection of EEG montages).

**Comment by agramfort** [comment]
if you think the automatic way can have a low enough failure mode sure why
not.
