### ISSUE TITLE
ENH/FIX: mne_analyze allows fitting with eeg electrodes, not mne.gui.coregistration

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#4639]
`mne_analyze` allows you to fit the trans thanks to the position of the EEG electrodes, whereas `mne.gui.coregistration` doesn't seem to take the EEG chans into account to do the fitting. 

Consequently, if we only have electrode positions, we cannot do the fitting and must rely in fiducials only. Ideally, we should have the option to force using  the EEG electrodes' position for the fitting.

As @larsoner mentioned, in the meantime, one can hack the info of the `fif` file by copying of each dig point in `info['dig']` that is EEG type, set its type to `FIFFV_POINT_EXTRA`, and append it to `info['dig']`

**Comment by larsoner** [comment]
This was fixed recently
