### ISSUE TITLE
Permutation cluster tests should compute vertex connectivity explicitly

### ISSUE THREAD

**Issue by wmvanvliet** [mne-tools/mne-python#4643]
This has bitten two of my coworkers in the ass. The permutation clustering examples on source space (e.g. https://martinos.org/mne/stable/auto_tutorials/plot_stats_cluster_spatio_temporal.html) use this to compute the connectivity between vertices:

    connectivity = spatial_tris_connectivity(grade_to_tris(5))

However, this is not always appropriate, depending on mixtures of old freesurfer brains and old mne-python versions. If the connectivity matrix is wrong, the statistics will go haywire in unpredictable ways. Since our users are prone to copy-pasting our example code without a second thought, this will be safer:

    # Read the source space that the individual stcs were morphed to
    src = mne.read_source_space('/path/to/fsaverage-ico4-src.fif')
    connectivity =  spatial_src_connectivity(src)

**Comment by larsoner** [comment]
When we do this we'll also want to fix `spatial_src_connectivity` to work for `oct` source spaces. It seems like both should just use `spatial_tris_connectivity` under the hood, not sure whether or not they do currently.

**Comment by wmvanvliet** [comment]
`spatial_src_connectivity` calls `spatial_tris_connectivity` under the hood, yes.
