### ISSUE TITLE
do volume based group study with ANTS?

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#4667]
I just saw this:

https://github.com/ANTsX/ANTsPy/blob/master/README.md

I am curious if this could be a viable option to have a group study option using
volume grids as source spaces.

**Comment by jona-sassenhagen** [comment]
I would like to see this.

Not volunteering, I'm helpless in source space.

**Comment by larsoner** [comment]
I think nowadays we recommend using volume group studies using SourceMorph so I'll close this
