### ISSUE TITLE
ENH: show channel in plot_evoked_topo()

### ISSUE THREAD

**Issue by jjnurminen** [mne-tools/mne-python#4673]
In the `plot_evoked_topo` display, the status bar could show which channel you are hovering over. Currently if you want to zoom in to e.g. MEG 1711 you probably will have no idea where it is (unless you are intimately familiar with the sensor layout).

**Comment by larsoner** [comment]
That would be great. Usually I click on the channel to have the window pop up and get the name from there, but it's not as convenient as a status bar update would be.
