### ISSUE TITLE
plot_joint as an axis-level function

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#4686]
It annoys me that we can't just assign plot_joint to axes. It seems people are doing a lot of these, and it would make things cleaner if we could put them in subplots. For that, it'd have to take an axes argument, which would require redoing how the plot_topomap part gets its own axes.

**Comment by jona-sassenhagen** [comment]
This would also work well if we could, as suggested by Denis, switch to axis divider for the topomaps and colorbar.

However, that brings with it its own set of problems ...

**Comment by jona-sassenhagen** [comment]
Closed by #5263

(Could still use an example though.)

**Comment by egorananyev** [comment]
> (Could still use an example though.)
A code example *would* be great!
