### ISSUE TITLE
raw.plot error when there are events and annotations

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#4690]
When I plot raw data with both events and annotations, I get an `IndexError: pop from empty list` in

    mne/viz/raw.py", line 1025, in _plot_raw_traces
        params['ax'].texts.pop(0)

I didn't realize that there could be other texts besides events in `params['ax'].texts`, so I set `params['ax'].texts = []` in [line 1016](https://github.com/mne-tools/mne-python/blob/master/mne/viz/raw.py#L1016).

Any ideas how to fix this are very much appreciated. This is pretty serious, although the plot continues to work even after such an error.

**Comment by agramfort** [comment]
can you provide a snippet to replicate?
