### ISSUE TITLE
raw.plot error when adding annotation

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#4691]
When I plot raw data, press 'a' and then 'Enter' I get the following error:

```
File "/usr/local/lib/python3.6/site-packages/mne/viz/utils.py", line 1880, in _annotations_closed
    params['ax'].selector.disconnect_events()
AttributeError: 'NoneType' object has no attribute 'disconnect_events'
```

This problem also existed in MNE 0.14.1.

**Comment by agramfort** [comment]
with what data?

**Comment by cbrnr** [comment]
Some data set we've recorded. I'm currently trying to replicate with a sample data set (but the download process from OSF is really slow).

**Comment by cbrnr** [comment]
OK, this happens with any data.

**Comment by agramfort** [comment]
how do I replicate?

**Comment by cbrnr** [comment]
```
import mne
from mne.datasets import sample


data_path = sample.data_path()
raw_fname = data_path + '/MEG/sample/sample_audvis_filt-0-40_raw.fif'
raw = mne.io.read_raw_fif(raw_fname, preload=True)
raw.plot()
```

Then press 'a' and in the annotations window click on "Add label" - voilà!

**Comment by larsoner** [comment]
I can't replicate in my environment. Maybe it's a `matplotlib` backend issue?

**Comment by cbrnr** [comment]
Hm, did you test this on a Mac (with the default `osx` backend)?

**Comment by larsoner** [comment]
No, Linux. On my OSX machine with the MacOSX backend I can't get the button presses to go to the window instead of the terminal (even after clicking in the window, etc.).

**Comment by cbrnr** [comment]
I get the same error on Linux. Did you press "a" and then click on the "Add label" button?

**Comment by cbrnr** [comment]
And this happens as far back as 0.14, which is before I made any commits to this module :relieved: - probably some update to Matplotlib introduced this error.

**Comment by larsoner** [comment]
> Did you press "a" and then click on the "Add label" button?

Yes

Can't add a simple conditional `if params['ax'].selector is not None` to fix this?

**Comment by cbrnr** [comment]
Strange, maybe you have a different Matplotlib or Qt or some other dependent lib version.

> Can't we add a simple conditional if params['ax'].selector is not None to fix this?

Yes, I'll do that (now that I'm pretty sure it's caused by a change in behavior of either Matplotlib or its deps).
