### ISSUE TITLE
Undocumented times attribute in Raw and Epoch object

### ISSUE THREAD

**Issue by aweinstein** [mne-tools/mne-python#4700]
Both `Raw` and `Epoch` classes have a `times` attribute. However, this attribute is not described in the documentation (see [epoch](https://martinos.org/mne/stable/generated/mne.Epochs.html) and [raw](https://martinos.org/mne/stable/generated/mne.io.Raw.html)).

(I can do a PR).

**Comment by agramfort** [comment]
please do

thanks
