### ISSUE TITLE
stim_channel="auto" in read_raw_edf renames stim channel

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#4710]
The new default for `mne.io.read_raw_edf` in MNE 0.16 will be `stim_channel="auto"`. Using this argument, the stim channel is called `Status` instead of the usual `STI 014`. This causes `mne.find_events` to fail because by default it looks for a channel called `STI 014`. Is this intended?

**Comment by cbrnr** [comment]
Not only that, but when I use `stim_channel="auto"` the resulting stim channel in the data contains negative values whereas it looks normal with the previous default of taking the last channel.

**Comment by agramfort** [comment]
there is maybe a bug but you can can set a default name for your stim
channels with the set_config

**Comment by larsoner** [comment]
> This causes mne.find_events to fail because by default it looks for a channel called STI 014. Is this intended?

Different systems sometime have different names. FWIW the default for the last number of years (10 maybe?) for Neuromag has even been STI101, so all newer systems use this. We usually use STI 014 when we synthesize a new events channel only. So this part is okay I think.

> when I use stim_channel="auto" the resulting stim channel in the data contains negative values whereas it looks normal with the previous default of taking the last channel.

This sounds like a bug

**Comment by cbrnr** [comment]
Using the exact same file, the stim channel is called `STI 014` if `stim_channel=True` (the current default) and `Status` if `stim_channel="auto"` (the default in 0.16). This is also a bug. I'm currently trying to find a public EDF file with a stim channel to reproduce this behavior.

**Comment by cbrnr** [comment]
The problem seems to occur in BDF files and not in EDF files. To reproduce, download the [BDF test files](https://www.biosemi.com/download/BDFtestfiles.zip) (unzip) and run:

```
print(mne.io.read_raw_edf("BDFtestfiles/Newtest17-256.bdf", preload=True, stim_channel=True).info["ch_names"][-1])
print(mne.io.read_raw_edf("BDFtestfiles/Newtest17-256.bdf", preload=True, stim_channel="auto").info["ch_names"][-1])
```

**Comment by agramfort** [comment]
sorry no time to look.

**Comment by cbrnr** [comment]
@larsoner do you have time to confirm?

**Comment by agramfort** [comment]
now on current master I get :

```
~/work/src/mne-python/mne/io/edf/edf.py in _get_info(fname, stim_channel, annot, annotmap, eog, misc, exclude, preload)
    562     # These are the conditions under which a stim channel will be interpolated
    563     if stim_channel is not None and not (annot and annotmap) and \
--> 564             tal_channel is None and n_samps[stim_channel] != int(max_samp):
    565         warn('Interpolating stim channel. Events may jitter.')
    566     info._update_redundant()

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

:(

**Comment by larsoner** [comment]
I think we need somebody with EDF expertise/knowledge to tackle this one. @cbrnr do you know enough to have an idea of what the right thing would be to do in each of these situations? If so, maybe a table or bulleted list would be good to guide fixes and also add to the `Notes` docstring.

**Comment by cbrnr** [comment]
No, I'm not familiar enough with the internal workings of EDF to do this quickly. I assume @jaeilepp is not available anymore, right? In the worst case, we could revert his changes regarding the stim channel.

**Comment by larsoner** [comment]
> In the worst case, we could revert his changes regarding the stim channel.

This seems like a reasonable choice to me, but it's complicated by the changes already existing in 0.15 (and it might work properly for some users in `'auto'` mode, and we would cause them pain with removal). So it's probably better to fix it rather than remove it.

**Comment by cbrnr** [comment]
Cf #4750

**Comment by cbrnr** [comment]
The last channel in the test file I've linked above is the stim channel. Since the previous default was `-1`, this channel was correctly detected as a stim channel. Now the new default is `'auto'`, which results in the last channel being interpreted as an EEG channel (and hence the weird values).

What exactly does `stim_channel='auto'` do?

**Comment by cbrnr** [comment]
To answer my question, maybe `stim_channel='auto'` should behave differently. Currently, it adds a stim channel if EDF annotations are present. If not, no stim channel is added. Maybe it should add the last channel in the latter case instead. Thoughts?

**Comment by cbrnr** [comment]
It's a mess. I'm discovering weird behavior as I go. I thought that `stim_channel=None` wouldn't add a stim channel. Consider [this example EDF file](https://www.physionet.org/pn4/eegmmidb/S001/S001R04.edf). If I load it with `stim_channel=None`, an additional MISC channel is still appended, even though this file does not have such a stim channel (events are stored as EDF annotations).

**Comment by larsoner** [comment]
It sounds like there are now several problematic files. If you have time, making a bulleted list (one per file) at the top of one of these issues that contains file link + existing behavior + what it should do would go a long way to setting up for a proper fix.

**Comment by cbrnr** [comment]
#4760

**Comment by cbrnr** [comment]
I think the backport label can be removed, because nothing is really broken (now that I understand the internals of EDF better), but only less ideal from a usability perspective.

**Comment by agramfort** [comment]
cool. can you document this somewhere ? and maybe suggest API improvements?

**Comment by cbrnr** [comment]
Yeah, it's all in #4760.

**Comment by cbrnr** [comment]
@agramfort @larsoner slightly OT, when is 0.15.1 planned to be released? The viz bug in raw.plot is pretty serious and 0.15.1 fixes it. This issue is for 0.16 because everything (EDF-related stuff) is still working in 0.15.

**Comment by agramfort** [comment]
just pushed 0.15.1 https://pypi.python.org/pypi/mne

**Comment by cbrnr** [comment]
Thanks @agramfort! So far `pip` isn't seeing the new version, but I'm hoping this won't take too long.
