### ISSUE TITLE
ENH: plot_alignment with sphere model

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#4723]
Currently there is no way to determine the "up" direction when using a sphere model. This is fine from a forward modeling standpoint because it doesn't matter, but for checking alignment it actually matters because you can't see if the head is in a reasonable position (i.e., not upside-down). You can check this with `coord_frame='head'` but that's not an optimal solution -- it would be nice if we had some way of recognizing the "up" of that coordinate system.

Options/ideas:

1. make the sphere color non-uniform by e.g. making the top light gray and the bottom dark gray
2. make the sphere color non-uniform by marking the topmost face of the sphere with some different color (white?)
3. add optional 3-arrow axis indicators showing the origin each coordinate system (MRI, head, MEG)

Personally I like the idea of having (2) and (3) -- I'd find (3) interesting/cool for even proper BEM models, and it has some nice pedagogical value.

**Comment by agramfort** [comment]
looks like you have not done enough coding lately :)
