### ISSUE TITLE
Force scalp surface routine skip topology check

### ISSUE THREAD

**Issue by ktavabi** [mne-tools/mne-python#4727]
Shouldn't `--force` arg allow for skipping topology checks in `mne make_scalp_surfaces`? Presently it's is returning topology error for volume(s) I don't see anything wrong with. 

<img width="727" alt="screen shot 2017-11-03 at 5 21 41 pm" src="https://user-images.githubusercontent.com/4381290/32400306-a1df9466-c0bb-11e7-97da-e09eec11b067.png">

> RuntimeError: Surface outer skin is not complete (sum of solid angles = 6.2829 * 4*PI instead).

cc @larsoner

**Comment by ktavabi** [comment]
@larsoner Does this sound reasonable to you?

- [ ] Add bool arg to `_surfaces_to_bem` inherited from `mne_make_scalp_surfaces`
- [ ] If `--force` then skip `_check_surface_size` for one or all surfs?

**Comment by larsoner** [comment]
I wouldn't skip it but rather turn the error into a warning. If you can share privately the offending surfaces I can take a look

**Comment by larsoner** [comment]
This was fixed IIRC

**Comment by ktavabi** [comment]
Yes it was. Thanks.

**Comment by ckiefer0** [comment]
I am getting the same error. How can I visualize my data to check for problems (similar to the image provided by @ktavabi)? If the volumes look fine I can just use '--force' to suppress the error, however, if there is a problem I have to obtain a new MR scan?

**Comment by ktavabi** [comment]
@ckiefer0 this fix concerned surface topology check. I only use '--force' to skip topology check for problematic outer skin surfaces. I wouldn't recommend skipping any sanity checks for other surfaces. Use the FS FreeView viewer to examine volumes & corresponding surfaces to ensure you have good segmentation and if need be you can use `--force` to skip topology check for the outer skin. In my experience, it is signal dropouts in the neck and face that seem to cause issues. HTH.
