### ISSUE TITLE
Error in error message in viz/topomap: points to function in wrong file. 

### ISSUE THREAD

**Issue by TomDonoghue** [mne-tools/mne-python#4732]
I found (what I think is) a small error in an error printed in mne/viz/topomap.py. 

Line 557 defines a message to be printed if, as I did, you mess up the channel pos input (gets printed in lines 561 & 564). 

It states:
("Pick Info with e.g. mne.pick_info and "
 "mne.channels.channel_indices_by_type.")

The issue/error is that 'channel_indices_by_type' is not 'mne.channels', but rather in 'mne.io.pick', so this error sends you on a bit of a quest to find that function to try and use it, if applicable. 

I'm guessing it moved at some point, and this reference is just out of date. If it just needs a quick PR fixing the path listed in the string, I'm happy to do so - just wanted to throw this up here in case it hints at anything more, and/or I've misunderstood something.

**Comment by agramfort** [comment]
thx.

fixed in bd1b3184f
