### ISSUE TITLE
RSA example plot missing

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#4747]
https://mne-tools.github.io/dev/auto_examples/decoding/decoding_rsa.html#sphx-glr-auto-examples-decoding-decoding-rsa-py

There should be an image here right?

@kingjr @larsoner

**Comment by larsoner** [comment]
No, does not start with `plot_` (what SG actually plots) so this is by design. The dataset is too big for our automated build system.

Feel free to add a comment if you think it would help users

**Comment by jona-sassenhagen** [comment]
No, makes sense.
