### ISSUE TITLE
dedicated float option for mne.viz.plot_compare_evokeds

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#4753]
As discussed between @mmagnuski and @agramfort , the color gradient should allow 0-1 float inputs.
I will do it.

See #4526 

closed by #4775

**Comment by mmagnuski** [comment]
hooray! 🙌

**Comment by jona-sassenhagen** [comment]
As soon as #4526 is merged, I will go about this :)
