### ISSUE TITLE
Create annotation within other annotation

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#4769]
Maybe I'm missing something, but since it is possible to create overlapping annotations (with different types) in `raw.plot` I thought that it should also be possible to create an annotation within some other annotation (of a different type). Apparently, this does not work, because if a start my new annotation in a region where there is already some other annotation, no selection rectangle is created.

Moreover, is it somehow possible to use different colors for different annotations (I didn't find any argument e.g. to `raw.plot`)?

**Comment by agramfort** [comment]
I don't get the question. See:

<img width="1258" alt="screen shot 2017-11-22 at 14 41 25" src="https://user-images.githubusercontent.com/161052/33130330-46213558-cf93-11e7-9f27-a9df99964a99.png">

if it starts with BAD then it stays red.

**Comment by cbrnr** [comment]
You can't create a new annotation which is completely within another annotation. This is useful if you don't only consider good/bad, but arbitrary information such as e.g. "trial", "cue", and "feedback". In this example, the "trial" annotation would extend from e.g. 2-10s. If I then want to create a "cue" annotation from e.g. 3-5s, I can't create it.

**Comment by agramfort** [comment]
indeed. There should be a way to toggle on/off certain type of annotations

**Comment by drammock** [comment]
Not sure when it got fixed, but this works now.
