### ISSUE TITLE
raw.plot fixes not in 0.15.1?

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#4777]
@agramfort could it be that https://github.com/mne-tools/mne-python/pull/4692 didn't get into 0.15.1?

**Comment by larsoner** [comment]
Yes I missed the `backport` label :(

**Comment by cbrnr** [comment]
This was the main reason (at least for me) for the bugfix release - I guess we can't just include it and call it 0.15.1 again. Can we release 0.15.2 pretty soon?

**Comment by agramfort** [comment]
yes backport and I'll push 0.15.2

let me know when to do it

**Comment by larsoner** [comment]
Backported and bumped version to 0.15.2, feel free to (double check and) cut a release

**Comment by agramfort** [comment]
done https://pypi.python.org/pypi/mne
