### ISSUE TITLE
Is scikit-learn required for ICA?

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#4788]
When creating an `ICA` object, I get the following error if scikit-learn is not installed:

    RuntimeError: the scikit-learn package (version >= 0.12)is required for ICA

I think MNE's ICA implementation uses the `FastICA` class from scikit-learn, but AFAIK it ships its own (Extended) Infomax algorithm, in which case scikit-learn should not be required.

**Comment by cbrnr** [comment]
Also, there's a space missing in this error message. And the main README says that scikit-learn >= 0.18 is required - which version is it?

**Comment by larsoner** [comment]
>  AFAIK it ships its own (Extended) Infomax algorithm, in which case scikit-learn should not be required.

We also use randomized PCA from `sklearn` for dimensionality reduction and whitening.

> the main README says that scikit-learn >= 0.18 is required - which version is it?

I think the error message is old and should be updated to say 0.18
