### ISSUE TITLE
Using `@deprecated` breaks docstring test

### ISSUE THREAD

**Issue by wmvanvliet** [mne-tools/mne-python#4816]
If you use `@deprecated` somewhere, `make pep` will fail on the `test_docstring_parameters.py` test. This has probably something to do with it overwriting the docstring of the deprecated object.

**Comment by agramfort** [comment]
yes you need to add it to list of ignored functions.

**Comment by wmvanvliet** [comment]
This seems to suggest this ignoring should happen automatically:

https://github.com/mne-tools/mne-python/blob/9fa084b33d0870f6da6af6fb61264068808e949b/mne/tests/test_docstring_parameters.py#L103

**Comment by wmvanvliet** [comment]
Ah, I get it now. You should add the function names to the `_docstring_ignore` list. Thanks @agramfort for the pointer.
