### ISSUE TITLE
core dumped in normal code execution or kernel dead in jupyter notebook after calling crop function of raw object..

### ISSUE THREAD

**Issue by abhiramsingh0** [mne-tools/mne-python#4817]
trying to crop the raw object based on some indices. This is killing the kernel in Jupyter notebook. Running in python 2.7 also generates core dump. What is the reason of this?

**Comment by agramfort** [comment]
how did you install python / jupyter?

show us what

mne.show_info()

tells you

**Comment by abhiramsingh0** [comment]
python is already installed on ubuntu. Jupyter was installed via pip.
Since program is terminated, after crop(), no information is obtained.
on running mne.show_info(), i got attribute error: module object has no attribute 'show_info'

**Comment by agramfort** [comment]
sorry i meant

mne.sys_info()

did you do:

sudo pip install jupyter

?

**Comment by abhiramsingh0** [comment]
Platform:      Linux-4.4.0-98-generic-x86_64-with-Ubuntu-16.04-xenial
Python:        2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
Executable:    /home/gnl/TF/bin/python
CPU:           x86_64: 16 cores
Memory:        31.3 GB

mne:           0.15.2
numpy:         1.13.1 {lapack=openblas, blas=openblas}
scipy:         0.19.1
matplotlib:    2.0.2

sklearn:       0.19.0
nibabel:       2.2.1
mayavi:        Not found
pycuda:        Not found
skcuda:        Not found
pandas:        Not found
>>> 
yes i installed jupyter as you have mentioned.

**Comment by abhiramsingh0** [comment]
also getting same problem of kernel dead while running get_data() method of raw object.

**Comment by agramfort** [comment]
well that's really dangerous to do

sudo pip install

I would recommend you install ubuntu version of jupyter with apt-get
or use anaconda but do not mix the 2.

**Comment by abhiramsingh0** [comment]
pip install was done by first creating virtualenv so I think this might not be the problem.

**Comment by agramfort** [comment]
you have an install problem for sure. it's not an mne problem.

try using anaconda

**Comment by abhiramsingh0** [comment]
One more point I want to mention is that when I am trying to do crop directly on raw object it is not showing any error. But when different raw objects are appended in list and then crop and get_data method on elements of list are giving kernel dead error.

**Comment by agramfort** [comment]
can you share a code snippet to replicate?

**Comment by abhiramsingh0** [comment]
**working case:**
```
raw_eeg = mne.io.read_raw_eeglab(path_to_set_file, preload='True')
raw_eeg.crop()
raw_eeg.get_data()
```

**non working case:**
```
raw_eeg_obj = []
for index in range(13):
    raw_eeg = mne.io.read_raw_eeglab(path_to_set_file[index], preload='True')     # need .set files
    raw_eeg_obj.append(raw_eeg)
for index in range(13):
    raw_eeg_obj[index].crop()            # this is not working
    raw_eeg_obj[index].get_data()      # this is also not working
```

**Comment by agramfort** [comment]
this is not a self-contained example using sample dataset. to try quickly I
should just need to "copy and paste".

thx

**Comment by abhiramsingh0** [comment]
Providing full code to replicate the issue.
However you need to download the dataset, extract it and change the **initial path** in the code where all extracted folders are placed.
You need to download the files MM05.tar.bz2 and so on from the website [http://www.cs.toronto.edu/~complingweb/data/karaOne/karaOne.html](url)
```
import scipy.io as sio
import mne
import os

full_data = []
trial_indices = []

initial_path = '/home/gnl/Abhi/imagined_UoT/kara_one_classify/dataraw/'
dir1 = os.listdir(initial_path)
second_path = '/spoclab/users/szhao/EEG/data/'
for file_ in dir1:
    path = initial_path+file_+second_path
    dir2 = os.listdir(path)
    if dir2[0] != 'P02':
        # collect desired files for data, indices and labels
        files = os.listdir(path+dir2[0])
        set_file = [s for s in files if '.set' in s][0]
        index_file = [s for s in files if 'epoch_inds' in s][0]
        dir3 = os.listdir(path+dir2[0]+'/kinect_data')
        label_file = [s for s in dir3 if 'p.txt' in s][0]
        # now load the data of each subject
        raw_eeg = mne.io.read_raw_eeglab(path+dir2[0]+'/'+set_file, preload='True')
        full_data.append(raw_eeg)
        indices = sio.loadmat(path+dir2[0]+'/'+index_file)
        trial_indices.append(indices)

trial_data_full = []

def data_by_trial():
    for subject in range(13):
        for trial in range(trial_indices[subject]['thinking_inds'].shape[1]):
            # get indices of the trial
            indices = trial_indices[subject]['thinking_inds'][0][trial][0]/1000.0
            # crop data sequence
            tempData = full_data[subject].copy().crop(start=indices[0],stop=indices[1])
            # append to trial_data_full
            trial_data_full.append(tempData)

data_by_trial()
```

**Comment by agramfort** [comment]
you don't replicate with eg the sample dataset?

**Comment by abhiramsingh0** [comment]
I am unable to replicate on **mne.datasets.eegbci** dataset. 
Can you please check on the _karaone_ dataset provided on the link above?
I am continuously facing the issue on _karaone_ dataset.

**Comment by agramfort** [comment]
can you share with me privately a dropbox folder with the script and the
data next to it.

it will make it trivial for me (and others) to replicate

**Comment by abhiramsingh0** [comment]
Sorry, I do not have Dropbox account.
I believe that by following steps mentioned in the above post, one can easily download the dataset, copy-paste the code and replicate the issue.
Thanks

**Comment by agramfort** [comment]
what file should I use? each is 2GB....

**Comment by abhiramsingh0** [comment]
Yes I know, each file is pretty heavy. You have to download 13 files starting from MM05.tar.bz2 to MM21.tar.bz2.

**Comment by agramfort** [comment]
ok that won't happen. Please make an effort to make a minimal reproducible
example.

**Comment by mmagnuski** [comment]
If the files are so big maybe the problem is just memory-related. Does `crop` work for `preload=False` (it should)? BTW @abhiramsingh0 it should be `preload=True` not `preload='True'`, although it shouldn't make a difference in the code (but `preload='False'` will behave as if it was `True` so better use booleans).

**Comment by abhiramsingh0** [comment]
@mmagnuski , thanks for pointing out the preload point. Also, I am loading the .set file and associated .fdt file is in the same folder. Size of each .fdt is about 600MB and I am loading 13 of these different files. You can see mne.sys_info() output that I have pasted above. Now how do I detect if problem is related to memory or mne as there seems to be enough memory for loading these files.

**Comment by larsoner** [comment]
Try concatenating just two of them. Then 3, then 4, then ... etc. Watch your memory consumption as it goes. See if crash coincides with running out of memory.

MNE provides `preload=temp_fname` to load data into a memmapped file to get around memory limitations if you can't use `preload=False`.

**Comment by jona-sassenhagen** [comment]
@abhiramsingh0 is this issue solved?

**Comment by jona-sassenhagen** [comment]
I am closing this. @abhiramsingh0 reopen if the problem is still there.
