### ISSUE TITLE
OverflowError: date value out of range

### ISSUE THREAD

**Issue by nerdmiao** [mne-tools/mne-python#4824]
```
  File "/home/zm/PycharmProjects/braindecode-master/braindecode/datasets/bcic_iv_2a.py", line 13, in load
    cnt = self.extract_data()
  File "/home/zm/PycharmProjects/braindecode-master/braindecode/datasets/bcic_iv_2a.py", line 20, in extract_data
    raw_edf = mne.io.read_raw_edf(self.filename, stim_channel='auto')
  File "/home/zm/mne-python/mne/io/edf/edf.py", line 1232, in read_raw_edf
    exclude=exclude, preload=preload, verbose=verbose)
  File "<string>", line 2, in __init__
  File "/home/zm/mne-python/mne/utils.py", line 728, in verbose
    return function(*args, **kwargs)
  File "/home/zm/mne-python/mne/io/edf/edf.py", line 158, in __init__
    annotmap, eog, misc, exclude, preload)
  File "/home/zm/mne-python/mne/io/edf/edf.py", line 408, in _get_info
    edf_info = _read_gdf_header(fname, stim_channel, exclude)
  File "/home/zm/mne-python/mne/io/edf/edf.py", line 889, in _read_gdf_header
    datetime.timedelta(date * pow(2, -32) - 367)
OverflowError: date value out of range
```
I got this error, how can fix it?

**Comment by agramfort** [comment]
you can put a break point eg with:

import ipdb; ipdb.set_trace()

then inspect the value of :

date * pow(2, -32) - 367

to understand what happened.

please show us what:

mne.sys_info()

gives you

**Comment by nerdmiao** [comment]
I guessed my dataset files is wrong. I edited it with notepad but it was not aligned。

**Comment by agramfort** [comment]
we could make a try except to avoid error and give warnings but we need to
be able to replicate.

can you share a file?

**Comment by nerdmiao** [comment]
ok！ It's the data file with incorrect modify.
[A01T.gdf.zip](https://github.com/mne-tools/mne-python/files/1546705/A01T.gdf.zip)

**Comment by agramfort** [comment]
thanks

ok I can replicate.

now i tried to see what is expected answer for these lines:

https://github.com/mne-tools/mne-python/blob/master/mne/io/edf/edf.py#L888

but I see that these lines are not covered by our EDF/GDF tests and I
cannot find
a file on my disk that needs these lines.

@teonbrooks maybe?

what does a matlab reader gives for the date on this file you shared?

**Comment by nerdmiao** [comment]
It can not be opened with matlab.

**Comment by agramfort** [comment]
it crashes too?

if so I guess it's really a bug with this file so we can close the issue.

**Comment by nerdmiao** [comment]
yes.
