### ISSUE TITLE
ValueError: No channel names specified

### ISSUE THREAD

**Issue by Rockingsnow** [mne-tools/mne-python#4832]
this issue occurred that  the inverse operator can't be computed when I ran my code below:

import numpy as np
import matplotlib.pyplot as plt
import mne
from mne.datasets import sample
from mne import Epochs, pick_types, find_events
from mne.io import concatenate_raws, read_raw_edf
from mne.datasets import eegbci
from mne.minimum_norm import (make_inverse_operator, apply_inverse,
                              write_inverse_operator)

##############################################################################

tmin, tmax = -1., 4.
event_id = dict(hands=2, feet=3)
subject = 1
runs = [6, 10, 14]  # motor imagery: hands vs feet

raw_fnames = eegbci.load_data(subject, runs)

raw_name = [read_raw_edf(f, preload=True, stim_channel='auto') for f in
             raw_fnames]
raw=raw_name[0]
events = find_events(raw, stim_channel='STI 014')

picks = pick_types(raw.info, meg=False, eeg=True, eog=False,
                       exclude='bads')
baseline = (None, 0)  # means from the first instant to t = 0
epochs = Epochs(raw, events, event_id, tmin, tmax, proj=True, picks=picks,
                baseline=None, preload=True)

##############################################################################
noise_cov = mne.compute_covariance(
      epochs, tmax=0., method=['shrunk', 'empirical'])

fig_cov, fig_spectra = mne.viz.plot_cov(noise_cov, raw.info)

##############################################################################
evoked = epochs.average()
evoked.plot()
evoked.plot_white(noise_cov)
##############################################################################
data_path = sample.data_path()
fname_fwd = data_path + '/MEG/sample/sample_audvis-eeg-oct-6-fwd.fif'
fwd = mne.read_forward_solution(fname_fwd)
fwd = mne.convert_forward_solution(fwd, surf_ori=True)
fwd = mne.pick_types_forward(fwd, meg=False, eeg=True)

info = evoked.info
inverse_operator = make_inverse_operator(info, fwd, noise_cov,
                                         loose=0.2, depth=0.8)
Extracting edf Parameters from C:\Users\user\mne_data\MNE-eegbci-data\physiobank\database\eegmmidb\S001\S001R06.edf...
EDF file detected
Setting channel info structure...
Created Raw.info structure...
Reading 0 ... 19999  =      0.000 ...   124.994 secs...
Ready.
Extracting edf Parameters from C:\Users\user\mne_data\MNE-eegbci-data\physiobank\database\eegmmidb\S001\S001R10.edf...
EDF file detected
Setting channel info structure...
Created Raw.info structure...
Reading 0 ... 19999  =      0.000 ...   124.994 secs...
Ready.
Extracting edf Parameters from C:\Users\user\mne_data\MNE-eegbci-data\physiobank\database\eegmmidb\S001\S001R14.edf...
EDF file detected
Setting channel info structure...
Created Raw.info structure...
Reading 0 ... 19999  =      0.000 ...   124.994 secs...
Ready.
Removing orphaned offset at the beginning of the file.
29 events found
Events id: [1 2 3]
15 matching events found
0 projection items activated
Loading data for 15 events and 801 original time points ...
0 bad epochs dropped
Epochs are not baseline corrected, covariance matrix may be inaccurate
<ipython-input-1-21908bdcebfc>:40: RuntimeWarning: Epochs are not baseline corrected, covariance matrix may be inaccurate
  epochs, tmax=0., method=['shrunk', 'empirical'])
Estimating covariance using SHRUNK
Done.
Estimating covariance using EMPIRICAL
Done.
Using cross-validation to select the best estimator.
Number of samples used : 2415
[done]
Number of samples used : 2415
[done]
log-likelihood on unseen data (descending order):
   shrunk: -259.877
   empirical: -299.073
selecting best estimator: shrunk
estimated rank (eeg): 64
Setting small EEG eigenvalues to zero.
Not doing PCA for EEG.
No average EEG reference present in info["projs"], covariance may be adversely affected. Consider recomputing covariance using with an average eeg reference projector added.
Total rank is 64
<ipython-input-1-21908bdcebfc>:53: RuntimeWarning: No average EEG reference present in info["projs"], covariance may be adversely affected. Consider recomputing covariance using with an average eeg reference projector added.
  evoked.plot_white(noise_cov)
Successfully extracted to: [u'C:\\Users\\user\\mne_data\\MNE-sample-data']
Reading forward solution from C:\Users\user\mne_data\MNE-sample-data/MEG/sample/sample_audvis-eeg-oct-6-fwd.fif...
    Reading a source space...
    Computing patch statistics...
    Patch information added...
    Distance information added...
    [done]
    Reading a source space...
    Computing patch statistics...
    Patch information added...
    Distance information added...
    [done]
    2 source spaces read
    Desired named matrix (kind = 3523) not available
    Read EEG forward solution (7498 sources, 60 channels, free orientations)
    Source spaces transformed to the forward solution coordinate frame
    Average patch normals will be employed in the rotation to the local surface coordinates....
    Converting to surface-based source orientations...
    [done]
    60 out of 60 channels remain after picking
Computing inverse operator with 0 channels.
Traceback (most recent call last):

  File "<ipython-input-1-21908bdcebfc>", line 72, in <module>
    loose=0.2, depth=0.8)

  File "<string>", line 2, in make_inverse_operator

  File "C:\Users\user\Anaconda2\lib\site-packages\mne\utils.py", line 728, in verbose
    return function(*args, **kwargs)

  File "C:\Users\user\Anaconda2\lib\site-packages\mne\minimum_norm\inverse.py", line 1376, in make_inverse_operator
    _prepare_forward(forward, info, noise_cov, rank=rank)

  File "<string>", line 2, in _prepare_forward

  File "C:\Users\user\Anaconda2\lib\site-packages\mne\utils.py", line 728, in verbose
    return function(*args, **kwargs)

  File "C:\Users\user\Anaconda2\lib\site-packages\mne\minimum_norm\inverse.py", line 1212, in _prepare_forward
    rank, pca)

  File "C:\Users\user\Anaconda2\lib\site-packages\mne\cov.py", line 1248, in _get_whitener
    noise_cov = prepare_noise_cov(noise_cov, info, ch_names, rank)

  File "<string>", line 2, in prepare_noise_cov

  File "C:\Users\user\Anaconda2\lib\site-packages\mne\utils.py", line 728, in verbose
    return function(*args, **kwargs)

  File "C:\Users\user\Anaconda2\lib\site-packages\mne\cov.py", line 1316, in prepare_noise_cov
    ch_names)

  File "C:\Users\user\Anaconda2\lib\site-packages\mne\io\proj.py", line 547, in make_projector
    return _make_projector(projs, ch_names, bads, include_active)

  File "C:\Users\user\Anaconda2\lib\site-packages\mne\io\proj.py", line 560, in _make_projector
    raise ValueError('No channel names specified')

ValueError: No channel names specified

**Comment by LeviZell** [comment]
solution?

**Comment by agramfort** [comment]
I don't know. It was closed without explanation. If you have pb please reopen and give us a gist to replicate the pb.

**Comment by LeviZell** [comment]
https://gist.github.com/anonymous/16b128f625b0b34b8cf547e2855d7f24

**Comment by agramfort** [comment]
first you have bad channels in your data. See the noise cov that have some
channels with much larger variance.

then you're using a forward operator obtained with a different system
which therefore has different channel names. it comes from an older system.

you need to compute a dedicated forward model for your data.
