### ISSUE TITLE
ENH: `group_by` for epochs.plot()

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#4850]
Any reason not to have it (other than no time to implement it yet)? It might be nice to have like we do for `raw.plot`.

**Comment by agramfort** [comment]
+1 for nice to have

**Comment by thesujitroy** [comment]
Can you please explain what you intend to perform (objective), I plan on trying it.
Or you can give some reference as well.

**Comment by jasmainak** [comment]
okay perhaps not as easy as I thought @thesujitroy. 

@larsoner would you recommend this as a starter issue?

**Comment by larsoner** [comment]
No it will probably involve too much refactoring

**Comment by thesujitroy** [comment]
@larsoner Thank you. I am looking into it.
@jasmainak Do you want to look into something else?

**Comment by jasmainak** [comment]
yeah, pick one of the issues labeled as easy.
