### ISSUE TITLE
De-duplicate channel types

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#4851]
As a follow-up to #4842, we should de-duplicate various definitions of valid channel types. Currently, these can be found in

- `mne.io.pick`: `get_channel_types`, `pick_types`, `_PICK_TYPES_DATA_DICT`, ... There are many more possibly relevant objects, but I need feedback which should be refactored and which should be left as is.
- `mne.io.meas_info`: `_kind_dict`

Anywhere else I forgot?

There should be only one place where valid channel types are defined. I suggest using `mne.io.pick` (currently it is inside `get_channel_types`, but this could be moved to a global dict in this module if desired.

**Comment by agramfort** [comment]
I would also standardize stuff in pick.py

**Comment by cbrnr** [comment]
@agramfort did you think of anything in particular in addition to the functions in `pick.py` I mentioned above? I think we should go through the whole module and choose what to refactor and what to leave alone.

**Comment by agramfort** [comment]
did not have time to look yet. Start and we'll see how the diff looks like

**Comment by agramfort** [comment]
@cbrnr I am not sure what you had in mind here? can you point to a code duplication or possible inconsistency?

**Comment by cbrnr** [comment]
Currently the mapping between channel type and FIFF constants is implemented multiple times (at least in `mne.io.pick.get_channel_types` and `mne.io.meas_info._kind_dict`). There should be only one place where this  mapping is defined.

**Comment by agramfort** [comment]
indeed !

+1 for using get_channel_types in meas_info and remove _kind_dict

**Comment by larsoner** [comment]
We'll want to do this at the start of a new release cycle rather than right before release so I'm bumping to 0.21
