### ISSUE TITLE
Issue with raw.plot()

### ISSUE THREAD

**Issue by suntracks** [mne-tools/mne-python#4876]
I am using a custom data format (*tdms from LabVIEW) . Used pandas to read data into MNE raw, however there seems to be some issue with the way the data is stored. 
I am seeing blobs of vertical lines. 
Current shape of numpy array - (8, 914585)

![image](https://user-images.githubusercontent.com/3403089/35008537-d9d4293a-fb22-11e7-963f-f6992deffc11.png)

**Comment by larsoner** [comment]
The scale factor is probably wrong. If these are EEG data they should be in units of volts, you probably have them in microvolts. Try changing the "scalings" parameter for your channel type (or multiply the channel values by e.g. 1e-6) to see if it fixes the problem.

**Comment by suntracks** [comment]
Thanks @larsoner,
That solved the problem.
