### ISSUE TITLE
Q: why eletrode positions plot is different from other tools like Fieldtrip?

### ISSUE THREAD

**Issue by iraquitan** [mne-tools/mne-python#4880]
In the Wikipedia [10–20 system (EEG)](https://www.wikiwand.com/en/10%E2%80%9320_system_(EEG)) the electrode positions when plotting are much like the following image (**EEG1010.lay**) extracted from Fieldtrip, where the midline (T9 -- Cz  -- T10) is definitely a straight line.

![eeg1010 lay](https://user-images.githubusercontent.com/3467229/35116071-e6d53434-fc68-11e7-87e2-d80f0e6c44c5.png)

But in MNE when I plot the standard montage like the following:

```python
import mne

montage = mne.channels.read_montage('standard_1020')
montage.plot()
```
I end up with this plot (**standard_1020**) where the (T9 -- Cz  -- T10) line is curved down.

![standard_1020](https://user-images.githubusercontent.com/3467229/35116096-f6d9fd24-fc68-11e7-89f8-39f3697341d0.png)

Why there's this difference? And there are any implications on topomap visualizations?

Thanks in advance!

**Comment by agramfort** [comment]
it seems like the outlines parameter from http://martinos.org/mne/
stable/generated/mne.Evoked.html#mne.Evoked.plot_topomap is not exposed in
plot_montage

we could add this yes...

**Comment by cbrnr** [comment]
I remember having discussed this before - wasn't it related to a transform from some coordinate space to another (based on the fiducials) that isn't done? I can't find the relevant issue though.

**Comment by larsoner** [comment]
Yes this is probably a dup of #3987
