### ISSUE TITLE
martinos.org ??

### ISSUE THREAD

**Issue by VitalyRS** [mne-tools/mne-python#4890]
Good day !
https://www.martinos.org/mne/getting_started.html is down?
Hmm. We’re having trouble finding that site.

We can’t connect to the server at www.martinos.org.
If that address is correct, here are three other things you can try:

    Try again later.
    Check your network connection.
    If you are connected but behind a firewall, check that Firefox has permission to access the Web.

**Comment by agramfort** [comment]
it works for me

otherwise you have a mirror here :
https://mne-tools.github.io/stable/index.html

**Comment by VitalyRS** [comment]
Thank you!
