### ISSUE TITLE
Excel/CSV File

### ISSUE THREAD

**Issue by agahEbrahimi** [mne-tools/mne-python#4897]
Hello,
I wanted to ask if MNE has any abilities to convert excel data to fif file?
Thank you in advance.

**Comment by agramfort** [comment]
use pandas to read the csv or xls file and use RawArray object as explained
here

http://martinos.org/mne/stable/auto_tutorials/plot_creating_data_structures.html#creating-raw-objects

**Comment by agahEbrahimi** [comment]
Thank you very much

**Comment by agahEbrahimi** [comment]
But that's not for the Heatmap imagery, does it work for that too?

**Comment by agramfort** [comment]
I don't know what heatmap imagery is. I am closing. Please reopen if you have more questions.
