### ISSUE TITLE
Verbosity control for _find_events

### ISSUE THREAD

**Issue by hekolk** [mne-tools/mne-python#4898]
Hi,

it would be great if the ``@verbose`` decorator could be added (back) to ``mne.event._find_events`` (https://github.com/mne-tools/mne-python/blob/master/mne/event.py#L423 ):

The realtime epochs call this method during processing of each data chunk and using the default log level causes a lot of unnecessary console output for each stimulus. The relevant ``_process_raw_buffer`` method already uses the verbose parameter ( https://github.com/mne-tools/mne-python/blob/master/mne/realtime/epochs.py#L325 ), but the necessary decorator of ``_find_events`` got removed a while ago in commit c96eef4fef05b. Hence, it would be great if you could reinsert the decorator!

**Comment by larsoner** [comment]
We should probably add the decorator, and not set `verbose='ERROR'` but rather let the user set it with the `find_events` argument to the constructor.

**Comment by agramfort** [comment]
Fine with me

**Comment by hekolk** [comment]
Thanks for the feedback - I created the mini-PR #4902, using verbose='ERROR' as default in the constructor argument.

**Comment by hekolk** [comment]
thanks for merging!
