### ISSUE TITLE
Mixed source space

### ISSUE THREAD

**Issue by SherazKhan** [mne-tools/mne-python#4899]
@agramfort @larsoner @dengemann Today I was talking with Matti, I am wondering how we normalized forward operator in case of mixed source space, say surface space with ico5 and 7mm for cerebellum volume source space. There should be a normalization factor ?

**Comment by agramfort** [comment]
currently if you have a mixed source space "I think" you cannot use surface
ori and loose param. Everything should be free ori.

but **yet** this needs to be investigated and validated with simulations /
experiments.

**Comment by SherazKhan** [comment]
I am currently working on mixed source space problem, I agrees, we need to verify/evaluate the bias between these two surfaces.

**Comment by agramfort** [comment]
>
> I am currently working on mixed source space problem
>

great. Open a WIP PR asap so we can play with you.

**Comment by larsoner** [comment]
Closing since we have other issues open having to do with mixed source space priors
