### ISSUE TITLE
[RFC] crop behaviour

### ISSUE THREAD

**Issue by massich** [mne-tools/mne-python#4904]
I was playing with crop and I found weird that based on this description the raw object gets modified:
```
Signature: reference_mne_data.crop(tmin=0.0, tmax=None)
Docstring:
Crop raw data file.

Limit the data from the raw file to go between specific times. Note
that the new tmin is assumed to be t=0 for all subsequently called
functions (e.g., time_as_index, or Epochs). New first_samp and
last_samp are set accordingly.

Parameters
----------
tmin : float
    New start time in seconds (must be >= 0).
tmax : float | None
    New end time in seconds of the data (cannot exceed data duration).

Returns
-------
raw : instance of Raw
    The cropped raw object.
```

Then going through the snipped provided in #4697 I realized that I might not be the only one having issues with it. Take a look at the following user code:

```
old_raw = raw.copy()
new_raw = raw.copy().crop(raw.times[times_start[0]],
                          raw.times[times_end[0]])

for idx in range(1, len(times_start)):
    cropped_raw = raw.copy().crop(raw.times[times_start[idx]],
                                  raw.times[times_end[idx]])
    mne.concatenate_raws([new_raw, cropped_raw])
```
either `old_raw` or `raw.copy()` should be unnecessary. 

So do you think we should change crop behavior or it's better to leave it as it is to keep backward compatibility?

**Comment by dengemann** [comment]
We can improve the documentation and make explicit that it returns self, that is the modified raw object.

**Comment by agramfort** [comment]
yes I think that this line:

old_raw = raw.copy()

is unnecessary. raw.crop indeed returns self.

**Comment by larsoner** [comment]
Closing as addressed, feel free to reopen if I'm wrong @massich

**Comment by agramfort** [comment]
I don't think it is fixed no?

**Comment by larsoner** [comment]
Right, #5094 should do it
