### ISSUE TITLE
Marking ischemic damage on topoplots

### ISSUE THREAD

**Issue by suntracks** [mne-tools/mne-python#4917]
Would like to know if there is a way to mark ischemic damage on topoplots.
It be great to visualise changes in evoked potentials around the damaged area of brain.

**Comment by agramfort** [comment]
can you share an example figure to see what you have in mind?

**Comment by suntracks** [comment]
Suppose we know that ischemic damage was in the region between P3 and P4, if  we could mark all the plots with this (maybe as a 'X' or 'O' or '.')  , so that we can view all the topo plots with the damaged region as a reference.

**Comment by agramfort** [comment]
change channel names in data and plot channel locations with name in your
topo?

**Comment by suntracks** [comment]
how can it be achieved in function for a series for plots starting t0 - t1

evoked.plot_topomap( ch_type='eeg',times=times)

**Comment by agramfort** [comment]
use show_names and sensors options in plot_topomap

**Comment by suntracks** [comment]
Thanks for the input, 
This really does not solve the purpose but a good work around.
is it possible to mark just one sensor position rather than all the channels from the list.

**Comment by agramfort** [comment]
you mean a list with one element ? if so just put the channel name in []

**Comment by suntracks** [comment]
This is showing up all the channel names specified in the channel name [].
plotting evoked data needs this info file marked correctly i suppose with all channel names & type.
Otherwise the montage locations are an issue. Correct me if am wrong here.

**Comment by agramfort** [comment]
yes info needs to be complete to work.

we could allow show_names names to take a list of channels
to specify what channels to plot.

**Comment by larsoner** [comment]
> we could allow show_names names to take a list of channels to specify what channels to plot.

I'd rather fix the dig sizing / position to properly assume head coords. Then this option is unnecessary as `pick_info` can be used.

For now a workaround would be to iterate over the text objects (using `matplotlib`) and change them based on their names (e.g., set some `visible=False` or change their colors).

**Comment by jona-sassenhagen** [comment]
Could one also rename the channels in the evoked object used for plotting ..?

**Comment by agramfort** [comment]
closing. @suntracks reopen if you think it's still relevant.
