### ISSUE TITLE
Importing Yokogawa/KIT data

### ISSUE THREAD

**Issue by makkostya** [mne-tools/mne-python#4923]
I try to import data from Brainstorm tutorial: http://neuroimage.usc.edu/brainstorm/Tutorials/Yokogawa and get an error. However, I can import it in Brainstorm. My MNE version 0.15.2
I run this code:
```
import mne
mne.io.read_raw_kit('SEF_000-export.con')
```
output:
```
Extracting SQD Parameters from SEF_000-export.con...
Creating Raw.info structure...
```

error:
`IOError: Unknown FLL type: 300`

**Comment by larsoner** [comment]
@christianbrodbeck any idea how we add support for this site?

**Comment by christianbrodbeck** [comment]
Implementation of the SQD reader is dependent on information on the file format, which is unfortunately not complete. It looks like the relevant component of brainstorm is compiled without source code (https://github.com/brainstorm-tools/brainstorm3/tree/master/external/yokogawa).
