### ISSUE TITLE
frequency shift in beamforming.lcmv_raw

### ISSUE THREAD

**Issue by dokato** [mne-tools/mne-python#4939]
Hi,

recently I'm dealing with the following problem: I wanted to reconstruct the MEG resting state signals in specific frequency band. I heard about one approach in which you apply inverse method to epoched data in specific frequency. So I did the following:

- filtered my signal in alpha;
- epoched my continuous data into 2 sec trials;
- created also the same epochs for broadband data;
- created covariance matrices both for alpha: `band_cov` and broadband signal `noise_cov`.

Then I followed standard steps: computed source space, created BEM, made forward model and assembled inverse operators for  `band_cov`.

The problem appears when I want to apply an inverse method. I do it by calling two functions on my continuous recordings filtered in alpha band (to be consistent with covariance matrix and inverse operator creation).

So this is PSD of my raw filtered recordings:
![figure_1-1](https://user-images.githubusercontent.com/4547289/36253421-6d90652a-123f-11e8-9b8c-f504ee253bd3.png)

This is output from one of the channels from sLORETA:

```
        stc_sol = apply_inverse_raw(raw_band, inverse_operator, lambda2,
                                    method=method, pick_ori=pick_ori)
```
![figure_1-2](https://user-images.githubusercontent.com/4547289/36253439-79bde61a-123f-11e8-9518-e648d1af1730.png)

And this is what I got from from beamforming:

```
        stc_sol = beamformer.lcmv_raw(raw_band, forward, noise_cov, band_cov, reg=reg,
                        pick_ori=pick_ori, weight_norm='unit-noise-gain',
                        max_ori_out='signed')
```
![figure_1](https://user-images.githubusercontent.com/4547289/36253447-80a57ef2-123f-11e8-85b2-103d63268932.png)

As you can see there is strange frequency shift. I thought at the beginning that there is something wrong with my input data, but results from sLORETA suggest that everything is fine. The difference appear after that line.

For completeness I just add that I plot data after parcelation:
```
    labels = mne.read_labels_from_annot(subject_number, parc='aparc', subjects_dir=head_shape_dir)
    label_names = [l.name for l in labels]
    label_ts = mne.extract_label_time_course(stc, labels, inverse_operator['src'], mode='pca_flip',
                                            return_generator=False)
    a = label_ts[21,:]
    p,f=mne.time_frequency.psd_array_welch(a,fs)
    plt.plot(f,p)
```

Can you spot any mistake in my procedure, or should I dig more into the code to solve this?

**Comment by jasmainak** [comment]
I would recommend providing us a "minimal reproducible example" so it's easy to trace the bug (if any)
