### ISSUE TITLE
Add a bit of support for categorical data to `TimeDelayedRidge`?

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#4940]
We should in the long run integrate `linear_regression_raw` and the Receptive Field code. I think in many regards the `TimeDelayedRidge` approach is probably the right way, API wise. But it's ghastly slow for my purposes - i.e., mostly sparse matrices. `linear_regression_raw` is much faster. Could we(/I) add a new keyword for integrating the `linear_regression_raw` way of creating the temporal embedding matrix (stacking sparse diagonal matrices)?

Also I'd like to have more options for tmin and tmax. I often want to estimate very long time windows (2, 3 seconds). But if I add in a dense(r) feature, running them on the same time windows would really blow up the size of the problem.

Alternatively, I'd have to copy the temporal delaying into its own module accessible outside.

@choldgraf @larsoner

**Comment by larsoner** [comment]
Closing in favor of more complete discussions in #3884
