### ISSUE TITLE
Covariance plots - Colorbar missing

### ISSUE THREAD

**Issue by ngayraud** [mne-tools/mne-python#4941]
In version 0.16, the colorbar setting (True or False) of the covariance plot (plot_cov function in file /viz/misc.py) does not affect the result. It is in fact not used in the code at all. Also,  when one sets show_svd=True the plots are not aligned since they are two different figures. 

I made a branch with some code to correct these small problems. The function returns a single figure containing either 2 of 4 subfigures. The code passes all tests.

Here are the figures, produced by running the following line of plot_simulate_evoked_data example:

> f1(,f2) = cov.plot(info,exclude = 'bads',colorbar = True,  show_svd= True)

original (in branch master):

![covariance_plot_colorbar_before_cov](https://user-images.githubusercontent.com/18072563/36307370-cbed46a4-1313-11e8-8dee-fc2364b9bf3d.png)
![covariance_plot_colorbar_before_svd](https://user-images.githubusercontent.com/18072563/36307371-cc07d5e6-1313-11e8-8ebc-527b82c1c9b0.png)

aligned, with colorbar:
![covariance_plot_colorbar](https://user-images.githubusercontent.com/18072563/36307409-f287a836-1313-11e8-8e1b-a6cb8e0e064b.png)

Let me know what you think

**Comment by agramfort** [comment]
indeed... can you open a PR?
thanks a lot

**Comment by jona-sassenhagen** [comment]
Closed by #4942 I assume.
