### ISSUE TITLE
cannot import name cwt_morlet

### ISSUE THREAD

**Issue by wendyli** [mne-tools/mne-python#4943]
I am trying to run code from someone's github install that calls:
  from mne.time_frequency.tfr import cwt_morlet

However I get the error 
ImportError: cannot import name cwt_morlet

I looked through the folder and found that in time_frequency there was a tfr.py, but no mention of cwt_morlet.  

I thought it could have been due to an update in mne and looked through mne- 0.12 and mne -0.14 but haven't seen a change in the tfr file compared to 0.15.  Has anyone encountered this error before?

**Comment by larsoner** [comment]
From `whats_new` for 0.13 [here](https://martinos.org/mne/stable/whats_new.html#id8):

```
- Deprecated mne.time_frequency.cwt_morlet and mne.time_frequency.single_trial_power in favour of mne.time_frequency.tfr_morlet() with parameter average=False, by Jean-Remi King and Alex Gramfort
```

Does that help? FWIW we are on version 0.15 now, so there might be other relevant changes. You can look here for publicly available/supported functions:

https://martinos.org/mne/stable/python_reference.html

**Comment by wendyli** [comment]
Thank you!
