### ISSUE TITLE
Rounding bug in axis labels? Perhaps MPL?

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#4948]
As of recently, something is weirding up some of the axis labels - rounding messes with the formatting. It's not an MNE issue per se- maybe a matplotlib update? Anyone got an idea?

Before:
<img width="505" alt="unknown-116" src="https://user-images.githubusercontent.com/4321826/36358065-2d1c06a4-1508-11e8-9733-bf32592a7444.png">
Now:
<img width="505" alt="unknown-117" src="https://user-images.githubusercontent.com/4321826/36358066-2f334790-1508-11e8-85be-69bb18cec88f.png">

**Comment by mmagnuski** [comment]
Oh, I got that too some weeks ago. I didn't dig to find what causes these labels go weird.

**Comment by agramfort** [comment]
please share a gist to replicate

**Comment by jona-sassenhagen** [comment]
You can just do

```
import mne
from mne.datasets import testing

data_path = testing.data_path()
fname = data_path + "/EEGLAB/test_raw.set"
montage = data_path + "/EEGLAB/test_chans.locs"

event_id = {"rt":1, "square":2}
raw = mne.io.eeglab.read_raw_eeglab(fname, preload=True, eog=eog,
                                    montage=montage, event_id=event_id
                                   )
events = mne.find_events(raw)
epochs = mne.Epochs(raw, events, {"square":2})
evoked = epochs["square"].average()
mne.viz.plot_compare_evokeds(evoked);
```

And you get

![unknown-119](https://user-images.githubusercontent.com/4321826/36437065-4c2633e4-1666-11e8-8154-0e48e59bfbb3.png)

**Comment by mmagnuski** [comment]
But I guess it doesn't happen if you take that data and plot it by hand? Any chance this is due to how `plot_comapre_evokeds` passes ticks or ticklabels to plt.plot?

**Comment by agramfort** [comment]
I don't have a pb with matplotlib 2.1.0

**Comment by larsoner** [comment]
@jona-sassenhagen what is `mne.sys_info()`? It could be due to some NumPy update, too.

**Comment by jona-sassenhagen** [comment]
```
mne.sys_info()
Platform:      Darwin-17.4.0-x86_64-i386-64bit
Python:        3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Executable:    /Users/jona/miniconda3/bin/python
CPU:           i386: 4 cores
Memory:        16.0 GB

mne:           0.16.dev0
numpy:         1.14.1 {blas=mkl_rt, lapack=mkl_rt}
scipy:         1.0.0
matplotlib:    2.1.2

sklearn:       0.19.1
nibabel:       2.1.0
mayavi:        Not found
pycuda:        Not found
skcuda:        Not found
pandas:        0.22.0
```

**Comment by jona-sassenhagen** [comment]
I'm gonna take a real look at what's happening now ... Just wanted to ask if anyone had any immediate ideas.

**Comment by mmagnuski** [comment]
I recently had that problem with pure matplotlib (+seaborn) and it seemed to be due to NumPy as Eric suggests. I didn't explore further, however.

**Comment by jona-sassenhagen** [comment]
If you check the PR, here, the problem is essentially doing `ax.set_xticklabels(ax.get_xticks())`.
