### ISSUE TITLE
BUG:  permutation clustering 2samp test depends on data order?

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#4979]
I saw something horrible today and it can be demonstrated on our sample data. In https://martinos.org/mne/dev/auto_tutorials/plot_stats_spatio_temporal_cluster_sensors.html,
say:

```Python

# set cluster threshold
threshold = 5.0  # very high, but the test is quite sensitive on this data
# set family-wise p-value
p_accept = 0.05
```

then

```Python
cluster_stats = spatio_temporal_cluster_test(X, n_permutations=1000,
                                             threshold=threshold, tail=0,
                                             n_jobs=1,
                                             seed=42,
                                             connectivity=connectivity)

T_obs, clusters, p_values, _ = cluster_stats
good_cluster_inds = np.where(p_values < p_accept)[0]
print(good_cluster_inds)
>>>  array([ 6 13 22 26])
```

*versus*

```Python

X_rev = list(reversed(X))  # !!!!
cluster_stats = spatio_temporal_cluster_test(X_rev, n_permutations=1000,
                                             threshold=threshold, tail=0,
                                             n_jobs=1,
                                             seed=42,
                                             connectivity=connectivity)

T_obs, clusters, p_values, _ = cluster_stats
good_cluster_inds = np.where(p_values < p_accept)[0]
print(good_cluster_inds)
>>> array([ 6 13 19 22 26])
```

In other words, for a 2-sided test with fixed seed the input order produces different results.

Thoughts? @agramfort @larsoner

**Comment by britta-wstnr** [comment]
Hi @dengemann - just came across this,
isn't this due to the fact that the indices for the permutations are the same due to the seed, however, they index different trials since X is reversed - meaning your permuted data sets will look different?
I took a quick look and for me, the two solutions converge when using more permutations (`n_permutations=5000`).

**Comment by dengemann** [comment]
> Hi @dengemann - just came across this,

Hi Britta, thanks for anticipating the right test. I independently concluded that it must be arbitrary initial differences that get randomly amplified by the seed but should converge at some point. Great to hear that it seems to be this. This adds to the discussion in #4953 -- and reinforces me in thinking that we want to have a small tutorial somewhere that shows how the impact of seeds diminishes with numbers of permutations.

**Comment by larsoner** [comment]
Closing as dup of #4953
