### ISSUE TITLE
problem with reading fieldtrip data

### ISSUE THREAD

**Issue by dokato** [mne-tools/mne-python#4984]
I was trying to load a dataset from fieldtrip and noticed a small bug, when trying to plot the signal:

```
/mne/viz/utils.pyc in _handle_decim(info, decim, lowpass)
   2210         lp = min(lp, info['sfreq'] if lowpass is None else lowpass)
   2211         info['lowpass'] = lp
-> 2212         decim = max(int(info['sfreq'] / (lp * 3) + 1e-6), 1)
   2213     decim = _ensure_int(decim, 'decim', must_be='an int or "auto"')
   2214     if decim <= 0:

ValueError: cannot convert float NaN to integer
```

It's because:
```
highpass : float | nan Hz
lowpass : float | nan Hz
```
in `raw.info` and MNE assumes that it will be either number or None.

To reproduce this bug you can follow sections _Procedure > Export to Raw_ from this tutorial:
http://www.fieldtriptoolbox.org/development/integrate_with_mne
 and call eg. `raw.plot()`.

I can help with fixing it, but wonder if we should check for NaN in this function, or rather while loading the data and making info?

**Comment by agramfort** [comment]
please send a PR

should it be fixed in Fieldtrip?

**Comment by dokato** [comment]
@agramfort In case of not detecting that info in FT header it assigns default values as (funct `fieldtrip2fiff.m`):
```
  info.highpass = NaN;
  info.lowpass  = NaN;
```
I think we can just replace all nans by Nones, since MNE can deal with it later on.

**Comment by agramfort** [comment]
yes sounds good
