### ISSUE TITLE
autoreject (global) in MNE

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-python#4989]
Since I have a little "free time" these days, I am wondering if there is some interest in adding `autoreject` to MNE. Although the API of autoreject (local) is not yet settled, I think adding autoreject (global) would be quite easy without any additional dependencies. We could do something like:

```py
import mne
mne.Epochs(..., reject="autoreject",)
ICA(..., reject="autoreject")
```

In the `autoreject` repository, I can internally call the MNE function so that those relying on it are not affected. Let me know.

**Comment by dengemann** [comment]
+1 after doing the 0.1 release :)

**Comment by dengemann** [comment]
I'd probably not bake this into the epochs constructor though as, usually, you interact with the autoreject outputs. Where the hack does the aureject object go Mainak when you do it the way you suggest here?

**Comment by jasmainak** [comment]
I'm actually suggesting something more simple than what you are probably thinking. What I propose is to do it in small steps. So to start with, I would just move the functionality offered by [this example](http://autoreject.github.io/auto_examples/plot_estimate_global_reject.html#sphx-glr-auto-examples-plot-estimate-global-reject-py). And of course, it wouldn't be baked into the Epochs object. It would just be one line extra to call this method inside the constructor.

**Comment by dengemann** [comment]
I am thinking at this point we should just copy the future autoreject API
into MNE preprocessing.
Then we can copy over some of the examples.
Then eventually add reject=‘auto’ when we know how to then get fixlog /
droplog etc.
As long as you want to look at autoreject results you want to have the
object. That’s ok. Also keep in mind how reject interacts with .get_data
and preloading. You don’t want to wait for autoreject until you get your
data from disk.

**Comment by agramfort** [comment]
what is preventing a 0.1 release now?

**Comment by dengemann** [comment]
Api changes that are only 80 % realized and missing tests

**Comment by jasmainak** [comment]
okay, let's discuss it in Inria next week :-)

**Comment by jona-sassenhagen** [comment]
I like autoreject. If we're adding cutting-edge ICA like Picard, may as well add autoreject.

**Comment by dengemann** [comment]
It's happening Jona! But not before a proper release on pip and finishing
the API transition. Good news: we will do it these days.

**Comment by jona-sassenhagen** [comment]
This issue is still open!!! @jasmainak @dengemann

**Comment by jasmainak** [comment]
okay for me to close it. We can keep maintaining autoreject in a separate repo for now.

**Comment by jona-sassenhagen** [comment]
Ok. Would still be cool to have it here, it's a great tool!
