### ISSUE TITLE
Link to github gist is broken (404) in .resample method doc

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-python#4994]
https://github.com/mne-tools/mne-python/blob/e84b316cb188043c69a4958b74884bfb556d78d8/mne/io/base.py#L1410-L1411

**Comment by agramfort** [comment]
it should be : https://gist.github.com/larsoner/01642cb3789992fbca59

PR welcome

**Comment by sappelhoff** [comment]
Alright, this should be it: #4995 

thanks for your work.
