### ISSUE TITLE
Images missing on the tutorial website

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#5005]
E.g. the ones at the end here:

https://mne-tools.github.io/stable/manual/decoding.html

@larsoner

**Comment by larsoner** [comment]
This should be fixed by turning this `manual` entry into a `tutorials` script. It should be easy for someone to do when they are bored

**Comment by cbrnr** [comment]
But which parts stay in the manual and which parts will be moved to a new tutorial script?

**Comment by larsoner** [comment]
> But which parts stay in the manual and which parts will be moved to a new tutorial script?

Eventually I think all of `manual` should / could be in `tutorials`.

**Comment by jona-sassenhagen** [comment]
<img width="721" alt="screenshot 2018-04-02 19 42 18" src="https://user-images.githubusercontent.com/4321826/38207401-f8e45eaa-36ad-11e8-8ecc-8504d8cc3742.png">

This is what I see ...

**Comment by larsoner** [comment]
Argh yes, temporary blindness on my part
