### ISSUE TITLE
Question: to exact phase values of single trial on source space 

### ISSUE THREAD

**Issue by XBTinChina** [mne-tools/mne-python#5017]
Dear all,

   I would like to get a source estimation (brain map) of my analysis on phase values of single trial. For example, on sensor space, I exact phase of every time points and do some averaging for each trial and then average across trials within one block. 
  I want to do this on source space, but I can't find MNE functions to return phase values on source space, so I am thinking of doing two options in below:
1) Do my analysis on sensor space and then project the results like projecting evoked response to source space.
2) Project each trial data from sensor space to source space using 'apply_inverse_epochs' and apply time-frequency analysis to get phase and do my analysis.

 Could someone give me some advices on this single-trial analysis on source space? 
  Many many thanks. 

 By the way, is there a function in MNE to return just phase values from time-frequency analysis? 

Best,
Shawn

**Comment by agramfort** [comment]
please use the mailing list for usage questions:

https://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis

we use the tracker for bugs and issues.
