### ISSUE TITLE
problem with mne.decoding.Scaler

### ISSUE THREAD

**Issue by giuliagennari** [mne-tools/mne-python#5022]
I am trying to standardize my epochs:
from mne.decoding import Scaler
epochs_data = epochs.get_data()
epochs_sc = Scaler().fit_transform(epochs_data)

And I get this error:
![image](https://user-images.githubusercontent.com/25058434/37486816-f307da7e-288f-11e8-80e7-8910af6cef51.png)

As if an epochs object and a numpy array were required at the same time.
Could anybody help me out?

**Comment by kingjr** [comment]
Hi,

By default the Scaler objects scale magnetometers, gradiometers and EEG
channels by a fixed amount: see details on the documentations
https://martinos.org/mne/dev/generated/mne.decoding.Scaler.html

This means that you need to inform the object about the channel
identify:e.g.
Scaler(info=epochs.info).fit_transform(epochs.get_data())

Else, you can scale the data using a variety of statistical approach: e.g.
Scaler(scalings='mean').fit_transform(epochs.get_data())

Best regards,

Jean-Remi

**Comment by giuliagennari** [comment]
That's right, I completely forgot to specify scalings='mean'.

Thank you very very much Jean-Remi!!!

Best,

Giulia

**Comment by jona-sassenhagen** [comment]
The error message is a bit cryptic ... we should probably do a better one (`Both "info" and "scalings" can't be None, please specify` etc).

**Comment by jona-sassenhagen** [comment]
@sappelhoff this would also be an easy thing to do, if you're still looking :)

**Comment by sappelhoff** [comment]
haha @jona-sassenhagen - thanks for finding some easy tasks for me ;-) 

something like this ... #5042 ?
