### ISSUE TITLE
Bug in peak_finder() and find_eog_events()

### ISSUE THREAD

**Issue by HariSeldon11988** [mne-tools/mne-python#5025]
If no peaks were found there is _TypeError: can't multiply sequence by non-int of type 'float'_,
because in line 161 of peak_finder.py an empty list is multiplied by -1.0

A solution is to put in lines 156 and 157:
```
            peak_mags = np.array([])
            peak_inds = np.array([])
```
instead of
```
            peak_mags = []
            peak_inds = []
```

However, it will only delay a problem. Full solution has to contain also a verification of eog_events length in 68th line of eog.py, e.g.:
```
    if len(eog_events) > 0:
        eog_events[:, 0] = np.round(times[eog_events[:, 0] -
                                      raw.first_samp]).astype(int)
```
instead of just:
```
    eog_events[:, 0] = np.round(times[eog_events[:, 0] -
                                      raw.first_samp]).astype(int)
```
which assumes that eog_events is not empty.

**Comment by agramfort** [comment]
please share a code snipped to replicate the pb. It will be used as
non-regression test.

thanks

**Comment by mmagnuski** [comment]
I've had a similar problem before using bare `peak_finder` (`ValueError: zero-size array to reduction operation maximum which has no identity`), here is how to replicate:
```python
import numpy as np
from mne.preprocessing.peak_finder import peak_finder

values = np.arange(2, 1, 0.05)
peak_finder(values)
```
maybe just fixing `peak_finder` would be enough?

**Comment by agramfort** [comment]
yes fix welcome

**Comment by TommyClausner** [comment]
Hey there! Guess I would like to fix it if not already done

**Comment by agramfort** [comment]
Go for it. Thx
