### ISSUE TITLE
Wrong axis scaling in .plot_image

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-python#5033]
When I call `.plot_image()` on epochs data, the x axis (time) is correctly shown in seconds.

However, when I call `.plot_image()` on evoked data (=`epochs.average()`), the x axis (again, time) is incorrectly shown in milliseconds (although the values indicate seconds).

Having used some of the plotting functions, I have also realized that the labeling for the time axis is not *always* either in milliseconds or in seconds but rather this changes from function to function and apparently depending on the object that I call the function on (see above).

Apart from fixing the issue with `evoked.plot_image()`, maybe it would be better to use consistent labeling for the time axis? Or are there reasons that would speak against this consistency?

Pictures to show what I mean (the data is always the same): 
`evoked.plot_image()` --> time axis label should be "seconds"  ... or `x_axis_values *= 1000`
![mneissue](https://user-images.githubusercontent.com/9084751/37769053-10d4fc86-2dd0-11e8-98e4-efcda181e5f1.png)

`epochs.plot_image()` --> again, this is a correct example ... working with an `epochs` instead of an `evoked` object
![mneissue3](https://user-images.githubusercontent.com/9084751/37769250-ab68f11c-2dd0-11e8-8bf8-edf907d1f621.png)

`evoked.plot_joint()` --> another correct example, this time with an `evoked` object again. However why is it in milliseconds now?
![mneissue2](https://user-images.githubusercontent.com/9084751/37769165-67b9501a-2dd0-11e8-8d5e-0ea2edd6b05a.png)

**Comment by larsoner** [comment]
> However, when I call .plot_image() on evoked data (=epochs.average()), the x axis (again, time) is incorrectly shown in milliseconds (although the values indicate seconds).

This sounds like a bug we should fix, do you have time to do it?

> Having used some of the plotting functions, I have also realized that the labeling for the time axis is not always either in milliseconds or in seconds but rather this changes from function to function and apparently depending on the object that I call the function on (see above).

Can you comment over on the closed #3164? If enough people gripe it might get @agramfort to budge :)

**Comment by larsoner** [comment]
... if you do make a PR, feel free to also take care of this aspect of the plot(s) you change:

https://github.com/mne-tools/mne-python/issues/4534

**Comment by larsoner** [comment]
And it looks like there is a bug in that image plot, too. Zero should be white (middle of colorbar).

**Comment by jona-sassenhagen** [comment]
I'm fixing the colorer scaling in #5010 already.

**Comment by sappelhoff** [comment]
@jona-sassenhagen, that's great. Would be cool if you could incorporate the fix for the axis. 

Making the axis labelling consistent could then be another step as it's not a bug per so :-)
