### ISSUE TITLE
Broken if in interpolate_bads()

### ISSUE THREAD

**Issue by stralu** [mne-tools/mne-python#5047]
Hi everybody,
I am using interpolate_bads() on raw eeg data. If I run this function without setting a bad channel, the function runs into an error similar to  #5029.
As already described in this issue a call like `interpolate_bads(verbose=False)` is a workaround and fixes the error.

While debugging I found a broken if in the file interpolation.py at line 126.
The check: `if len(picks) == 0 or len(bads_idx) == 0:` misses its purpose, because bads_idx is a boolean ndarray and its length is therefore always greater than 0.

Can someone please fix this? (`bads_idx.sum() == 0` would work)
Thanks

**Comment by jasmainak** [comment]
I don't follow. Can you provide script to reproduce using the sample data? Thanks.

**Comment by jasmainak** [comment]
good catch, fix coming
