### ISSUE TITLE
BUG: spoc example broken

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#5050]
@agramfort tells me the SPoC example in master is broken, haven't had time to look at it yet.

cc @alexandrebarachant

**Comment by jona-sassenhagen** [comment]
https://mne-tools.github.io/dev/auto_examples/decoding/plot_decoding_spoc_CMC.html

**Comment by jhouck** [comment]
Was this fixed already?  The example works fine for me, although only after updating from mne 0.16.2 to 0.18.dev0 and sklearn 0.19.1 to 0.20.1 .  Prior to the update it didn't like the 'rank' keyword in `make_pipeline` but ran OK without it.  I kept the old version's anaconda environment so can replicate if someone really wants to read the original error message.

**Comment by dengemann** [comment]
@jhouck yes we fixed it with @DavidSabbagh. Take a look at current master and let us know if there is some remaining issue.

**Comment by jhouck** [comment]
Thanks @dengemann.  No remaining issues,  I'd borrowed pretty heavily from the example and was worried when I saw the open issue. :)
