### ISSUE TITLE
Refactor evoked image and tfr image plot masking code

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#5061]
`evoked.plot_image(..., mask=...)` and the corresponding TFR method should share code for masking.

@cbrnr

**Comment by jona-sassenhagen** [comment]
@cbrnr do you want to do it, or should I?

**Comment by cbrnr** [comment]
Do you have time? Currently I won't be able to start working on it anytime soon(ish).

**Comment by jona-sassenhagen** [comment]
I don't have the *time*, but I'm doing MNE stuff right now anyways, so yeah, I can do it :) Means you'll have to review ofc.

**Comment by cbrnr** [comment]
Sure thing!
