### ISSUE TITLE
ENH: LCMV and vector source solution

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#5067]
We recently added support for VectorSourceEstimate in MNE solutions. It seems like this could be added to LCMV, too, by changing `_apply_lcmv`.

@britta-wstnr do you see any reason not to allow this?

**Comment by larsoner** [comment]
It is already in #5069, but I'm stuck there because I'm not sure why the LCMV orientation is incorrect

**Comment by TommyClausner** [comment]
If the problem still exists after the 15th this month, I'd be happy to have a look ;)

**Comment by larsoner** [comment]
@TommyClausner feel free to take over #5069, I'll leave it for you :)
