### ISSUE TITLE
BUG: Ref problem for ECoG / sEEG

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#5081]
Currently we check for average reference for EEG, but not ECoG / sEEG at least in `prepare_noise_cov`. What is the right thing to do here?

**Comment by agramfort** [comment]
@choldgraf is there a best practice for the reference on ECoG?

for sEEG please tend to use a bipolar montage for viz but for inverse problem I think it's an open question...

**Comment by maedoc** [comment]
For sEEG there are usually plain EEG scalp sensors used to reference the data, otherwise average or bipolar references would work.

**Comment by larsoner** [comment]
We have reworked ECoG/sEEG referencing so I think this can be closed
