### ISSUE TITLE
pb with read_raw_edf and channel names truncation

### ISSUE THREAD

**Issue by Slasnista** [mne-tools/mne-python#5087]
Hi,

Channel name truncation might lead to some issues especially when one channel with a truncated name is passed to the reader function as a channel to exclude.
-> the reader does not manage to find the channel to exclude and raises an error.

There might be a possible solution consisting in creating a correspondance table between ch_names and truncated ch_names to overcome this problem in read_raw_edf around line 620 / 621.

Best regards,
Stanislas

**Comment by agramfort** [comment]
you have this info in:

`raw._raw_extras[0]['ch_names']`
