### ISSUE TITLE
coreg issue in mne 0.16

### ISSUE THREAD

**Issue by dokato** [mne-tools/mne-python#5088]
When running with mne-0.16.dev0: `mne coreg` I got: 

```
TypeError: coregistration() got an unexpected keyword argument 'project_eeg'
```

**Comment by dokato** [comment]
Strange, I do have different mne versions but in separate conda environments.

**Comment by christianbrodbeck** [comment]
Did you check your paths? It looks like you might be accessing the script (the `$ mne` command) from a different version than the package. Also check `$ which mne`.

**Comment by christianbrodbeck** [comment]
I think it could be due to mixing conda and pip installs, they're not completely compatible, I would try (pip) installing mne again.

**Comment by larsoner** [comment]
Closing as an installation problem, but we can reopen if there is something to fix at the MNE end.

If you do figure it out, maybe adding some insights to a new "debugging conflicting environments" entry in the FAQ would help.
