### ISSUE TITLE
Plot Source Alignment tutorial is out of commission

### ISSUE THREAD

**Issue by er06645810** [mne-tools/mne-python#5104]
The tutorial file `plot_source_alignment.py` is broken. It looks like there were some changes introduced to the API that haven't been taken into account in the tutorial. 

I stumbled across this while trying to figure out how to create a forward solution from a sphere model. I found some issues from a couple years back (2014 maybe?) where it was documented, but I can't figure out how to do in the current version.

```
ValueErrorTraceback (most recent call last)
~/src/mne-python/tutorials/plot_source_alignment.py in <module>()
    193
    194 sphere = mne.make_sphere_model(info=raw.info, r0='auto', head_radius='auto')
--> 195 src = mne.setup_volume_source_space(sphere=sphere, pos=10.)
    196 mne.viz.plot_alignment(
    197     raw.info, eeg='projected', bem=sphere, src=src, dig=True,

~/miniconda3/envs/mne/lib/python3.6/site-packages/mne/source_space.py in setup_volume_source_space(subject, pos, mri, sphere, bem, surface, mindist, exclude, subjects_dir,volume_label, add_interpolator, verbose)

~/miniconda3/envs/mne/lib/python3.6/site-packages/mne/utils.py in verbose(function, *args, **kwargs)
    726         with use_log_level(verbose_level):
    727             return function(*args,**kwargs)
--> 728     return function(*args, **kwargs)
    729
    730

~/miniconda3/envs/mne/lib/python3.6/site-packages/mne/source_space.py in setup_volume_source_space(subject, pos, mri, sphere, bem, surface, mindist, exclude, subjects_dir,volume_label, add_interpolator, verbose)
   1541     sphere = np.asarray(sphere)
   1542     if sphere.size != 4:
-> 1543         raise ValueError('"sphere"must be array_like with 4 elements')
   1544
   1545     # triage bounding argument

ValueError: "sphere" must be array_like with 4 elements
```

**Comment by agramfort** [comment]
what version are you using? current master? where did you take the example
code from? stable or dev website?

**Comment by er06645810** [comment]
Sorry about the lack of clarity. This was on the latest commit to `master`, and I ran the file directly from the repo as opposed to copy/pasting from the website to ensure that the version of mne and the tutorial matched.

**Comment by agramfort** [comment]
it works fine with me on master

I suspect a mismatch of versions on your system

**Comment by moppymopperson** [comment]
Hmm...alright, I’ll close this in the meantime. I’ll be out of town for a week or two before I have time to try again. Thanks for testing it out.

**Comment by er06645810** [comment]
Hmm...I tried to make sure the versions matched. I won’t be able to check it for a bit because I’ll be out of town, so I’ll close it until I can reproduce the issue or get it working. Thanks for taking the time to test it.
