### ISSUE TITLE
src.plot different color for each source space

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#5111]
when doing src.plot for a volumic source space it would be nice to see in different colors (not just yellow) the source locations depending to which structure they belong.

**Comment by jona-sassenhagen** [comment]
Definitely.

**Comment by larsoner** [comment]
In theory for the volume ones we might be able to get the colors from the Freesurfer LUT / aseg somewhere

**Comment by agramfort** [comment]
+1 !

**Comment by vagechirkov** [comment]
I'll take this one (sprint 2021) :)

**Comment by sappelhoff** [comment]
closed in #9114
