### ISSUE TITLE
EpochsTFR should preserve metadata

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#5112]
@choldgraf @palday @sappelhoff

**Comment by sappelhoff** [comment]
Could you expand a bit on this issue please @jona-sassenhagen ?

**Comment by agramfort** [comment]
that should not be too hard via mixin classes

**Comment by jona-sassenhagen** [comment]
@kdoelling1919 after your recent great work on this ...

**Comment by kdoelling1919** [comment]
Yep! This issue can be closed after #5762
