### ISSUE TITLE
BUG?: average=False in compute_proj_exg

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#5148]
By default we have `average=False` in `compute_proj_ecg` and `compute_proj_eog`. But when I was toying with the idea of using `Xdawn` (which I think might still be a good idea) to compute projectors rather than plain SSP, I found that `average=True` seemed to always be better than `average=False`.

Here is the sample data, with four columns: the first two are `average=False`, the last two are `average=True`; within those, the left are ECG epochs (to be projected) and the right are auditory epochs (hopefully not contaminated):

![xdawn](https://user-images.githubusercontent.com/2365790/39069053-800dbcd0-44ac-11e8-8ed2-b5ad53db0055.png)

Note that the "average=True" does not really make sense for Xdawn because it already uses the average, so the first two and last two columns are the same for Xdawn.

I think we might consider:

- [x] 1. Changing the default `average=False` to `average=True`.
- [x] 2. ~~Probably unify `compute_exg_proj` and `create_exg_epochs`. The former does not use the latter but it probably should.~~
- [x] 3. Implement Xdawn as a backend instead of just SSP. Even with `average=True` it should do better against other noise present in the epochs, especially if that noise is large (yet to be shown).

**Comment by larsoner** [comment]
I suggest we use a deprecation cycle to get to `average=True`, then, for 0.16. The others can be 0.17.

**Comment by agramfort** [comment]
Ok for me

**Comment by cbrnr** [comment]
+1 for tackling `average=True` now and the rest later. But why do you think this is a bug?

**Comment by larsoner** [comment]
It probably should have been True from the beginning.

>

**Comment by cbrnr** [comment]
So results are wrong if `average=False`?

**Comment by larsoner** [comment]
They seem to be less correct in testing.

**Comment by cbrnr** [comment]
OK, so probably not a but, but suboptimal parameter settings.

**Comment by massich** [comment]
I don't think so (because point 3 is missing), but we can take it off of the 0.16 milestones.

**Comment by agramfort** [comment]
ok done

**Comment by larsoner** [comment]
Point (3) is open we just need to decide about whether or not to do it
