### ISSUE TITLE
turn off evoked Nave printing?

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#5151]
Shouldn't there be an option to turn off Nave printing? Otherwise some forms of plots can look a bit awkward:

<img width="576" alt="unknown-140" src="https://user-images.githubusercontent.com/4321826/39089338-08c9f840-45c5-11e8-8359-bc9dd34b774f.png">

@larsoner

**Comment by larsoner** [comment]
ax.texts = []

Good enough?

>

**Comment by jona-sassenhagen** [comment]
Hm, not really, cause there might be a ton of other texts there right?

So far, I'm setting `evoked.nave = None`, but that does not seem right.

**Comment by larsoner** [comment]
Ahh I thought there was 1 but there are 3:
```
>>> mne.read_evokeds(mne.datasets.sample.data_path() + '/MEG/sample/sample_audvis-ave.fif')[0].plot().axes[0].texts
Text(0, 0, 'blank'),
 Text(0, 5, 'N$_{\\mathrm{ave}}$=55'),
 Text(0.01, 0.1, 'Loading...')]
```
So `ax.texts.pop(1)` would do it.

I'd rather not clutter the API with another option. Can we instead think of a better placement so that removal is not necessary? Maybe right-aligned to the Y-axis ?

**Comment by jona-sassenhagen** [comment]
Yeah another kwarg seems overkill ... I'm not sure.

**Comment by larsoner** [comment]
I'm going to close this since I seem to remember us having some suitable solution to this in a PR, but @jona-sassenhagen feel free to reopen if it's still an issue
