### ISSUE TITLE
[Easy] Switch default colors to MPL defaults?

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#5154]
Since 2.0, the MPL defaults (c0, c1, ...) are very good. Should we not transition there with, for example, our line plot defaults?

**Comment by larsoner** [comment]
Which line plots do you have in mind?

**Comment by jona-sassenhagen** [comment]
All plots that use mne.viz.utils.COLORS, i.e., the annotation plots.

**Comment by larsoner** [comment]
Sounds good to me. I think we can just change these and put a note in the API section.

**Comment by sappelhoff** [comment]
See PR .. is this what you meant @jona-sassenhagen? [Here](https://matplotlib.org/users/dflt_style_changes.html#colors-in-default-property-cycle) are the colors.

However, this change means going from 
```python
['b', 'g', 'r', 'c', 'm', 'y', 'k', '#473C8B', '#458B74',
 '#CD7F32', '#FF4040', '#ADFF2F', '#8E2323', '#FF1493']
```

to 
```python
[u'#1f77b4', u'#ff7f0e', u'#2ca02c', u'#d62728',
 u'#9467bd', u'#8c564b', u'#e377c2', u'#7f7f7f', u'#bcbd22', u'#17becf']
```

i.e., fewer colors. Is that an issue?

**Comment by jona-sassenhagen** [comment]
We could just stick with `'c0', 'c1', 'c2', ...` right?

**Comment by larsoner** [comment]
And we do have conditionals that look for `'r'` in the color cycle somewhere in the viz plotting code having to do with annotations. So that will need to be changed.
