### ISSUE TITLE
Value error on float comparison in mixed norm solver

### ISSUE THREAD

**Issue by ktavabi** [mne-tools/mne-python#5162]
Possibly a bug?

> Traceback (most recent call last):
> ...
>   File ".../Projects/nbwr/nbwr/process/compute_sparse_inverse.py", line 82, in <module>
>     alpha=25)
>   File ".../Projects/nbwr/nbwr/bin/source_imaging.py", line 118, in mixed_norm_solver
>     return_as_dipoles=return_as_dipoles)
>   File "<string>", line 2, in mixed_norm
>   File ".../Projects/mne-python/mne/utils.py", line 729, in verbose
>     return function(*args, **kwargs)
>   File ".../Projects/mne-python/mne/inverse_sparse/mxne_inverse.py", line 403, in mixed_norm
>     weights_min)
>   File ".../Projects/mne-python/mne/inverse_sparse/mxne_inverse.py", line 108, in _prepare_gain
>     loose, weights, weights_min)
>   File "<string>", line 2, in _prepare_gain_column
>   File ".../Projects/mne-python/mne/utils.py", line 729, in verbose
>     return function(*args, **kwargs)
>   File ".../Projects/mne-python/mne/inverse_sparse/mxne_inverse.py", line 91, in _prepare_gain_column
>     weights, weights_min)
>   File "<string>", line 2, in _prepare_weights
>   File ".../Projects/mne-python/mne/utils.py", line 729, in verbose
>     return function(*args, **kwargs)
>   File ".../Projects/mne-python/mne/inverse_sparse/mxne_inverse.py", line 33, in _prepare_weights
>     (weights_min, weights_max))
> ValueError: weights_min > weights_max (8.0 > 7.9015784205980015)

I wasn't able to reproduce error with sample data but following gist with [these files](https://www.dropbox.com/sh/os3kbpf0xwtc6oi/AADb4jZYia8-3DwzXwTVpPSja?dl=0) and default kwargs produces generalized version of the error.
cc @larsoner 

```
from mne import (read_cov, read_evokeds, read_forward_solution)
from mne.minimum_norm import read_inverse_operator, apply_inverse
from mne.inverse_sparse import mixed_norm as mxne

fwd_fname = 'sub-nbwr426_ses-001_task-lexicaldecision_run-01_meg-sss-fwd.fif'
ave_fname = 'Lexicality_55-sss_eq_sub-nbwr426-ave.fif'
cov_fname = 'sub-nbwr426_ses-001_task-lexicaldecision_run-01_meg-55-sss-cov.fif'
inv_fname = 'sub-nbwr426_ses-001_task-lexicaldecision_run-01_meg-55-sss-meg-inv.fif'  # noqa
cov = read_cov(cov_fname)
evokeds = read_evokeds(ave_fname, condition=['Words', 'Nonwords'],
                       baseline=(0, None), kind='average')
fwd = read_forward_solution(fwd_fname)
operator = read_inverse_operator(inv_fname)
stc = apply_inverse(evokeds[0], operator)
dipoles, residual = mxne(evokeds[0], fwd, cov, 55, weights=stc)
# to reproduce exact error
#dipoles, residual = mxne(evokeds[0], fwd, cov, 55, weights=stc,
#                        loose=0.2, depth=0.9, maxit=3000,
#                         tol=1e-4, active_set_size=10,
#                         debias=True, 
#                         weights_min=8.,
#                         n_mxne_iter=10,
#                         return_residual=True,
#                         return_as_dipoles=True)

```

**Comment by agramfort** [comment]
@ktavabi the weights_min is set to 8 here. Basically this parameter allows to limit the source space to locations where the dSPM values exceed 8 at any point in time. It's historically to make the solver faster. You should lower this value.

**Comment by ktavabi** [comment]
Thanks @agramfort. I'll try 4. How does this interact, if at all, with the regularization?

**Comment by larsoner** [comment]
Also you mention "historically" does this mean it might be possible to disable this param and have it work (albeit somewhat slower but still tolerable)?

**Comment by agramfort** [comment]
good question. It should not in theory.

@larsoner well we still need to integrate the faster solvers we working on.
No reason to removing these now.

**Comment by larsoner** [comment]
I seem to recall fixing this in the past year but if someone hits this error again, feel free to reopen
