### ISSUE TITLE
function to tell what type of object is stored in file

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-python#5164]
something like

```py
>>> mne.what(fname)
'ica'
```

It could be useful for MNE report and also for validating filenames in BIDS.

Implementation: try/catch clauses (easy) or digging into the tags (harder)

**Comment by larsoner** [comment]
Or maybe just `mne.read(...)` and return the correct type of object. And if people want more options/kwargs they should use the dedicated reader.

**Comment by agramfort** [comment]
-1 on this. There should one way of doing things. It makes doc easier to write and understand

**Comment by larsoner** [comment]
Fair enough
