### ISSUE TITLE
Trouble dealing with stc file using mne.SourceEstimate 

### ISSUE THREAD

**Issue by Rockingsnow** [mne-tools/mne-python#5165]
I wonder how to extract  the source estimates of the stc file in the specific time interval  by using mne.SourceEstimate.crop()

After I got the stcs transformed from the epoch of -1~4s (stcs = apply_inverse_epochs(epochs,inverse_operator,  lambda2, verbose=False,method="dSPM",pick_ori="normal")), 
I tried to run the stcs = SourceEstimate(stcs).crop(tmin=3., tmax=4.), then the issue generated as follow: 
ValueError: Vertices, if a list, must contain two numpy arrays
then I add the vertices=stc.vertices to the code to run the stcs = SourceEstimate(stcs,vertices=stc.vertices).crop(tmin=3., tmax=4.)
the new issue generated: AttributeError: 'list' object has no attribute 'shape'
I don't know how to set up the parameters of the mne.SourceEstimate to Restrict SourceEstimate to a time interval

**Comment by Rockingsnow** [comment]
thanks for your assistance, it solved my great confusion, and another question I need to ask is that how I could obtain a final stcs file including all of processed stcs after I run each stcs[int].crop(...).
Need to reintegrate?

**Comment by agramfort** [comment]
if you want to crop all stcs then crop the epochs you pass to
apply_inverse. It's simpler.

otherwise you could do:

stcs = [stc.crop(...) for stc in stcs]

HTH

**Comment by Rockingsnow** [comment]
I got it，thank you
