### ISSUE TITLE
Digitalization source is not flush when changing subject in MNE Coreg

### ISSUE THREAD

**Issue by massich** [mne-tools/mne-python#5181]
When processing several subjects, when selecting a different subject the points on the display are flushed, but not the digitalization file. This could lead to problems like fitting the wrong digitalization. 

See the following images:
![image](https://user-images.githubusercontent.com/7044835/39529875-00a20caa-4e28-11e8-9d4b-6f062d49f2f5.png)
![image](https://user-images.githubusercontent.com/7044835/39529881-068e6708-4e28-11e8-89a9-53f8b89dd5c8.png)

**Comment by larsoner** [comment]
I'm not sure that the dig file should change when loading a different MRI. When using a surrogate / warping someone might want to choose MRI based on closest fit to the dig, in which case clearing the dig when the MRI changes would be very annoying.

**Comment by agramfort** [comment]
well for me if you change the subject you have a new MRI and you need to
update dig points.

it's less surprising. We got bitten by this by @massich and this triggered
this issue.

**Comment by christianbrodbeck** [comment]
Maybe the logic of the GUI, assuming that people work from top to bottom, would be more intuitive if the digitizer source was above the MRI source?

**Comment by agramfort** [comment]
for me this does not fix the pb. if you switch subject in your study you
want to flush what is not relevant

**Comment by larsoner** [comment]
> well for me if you change the subject you have a new MRI and you need to update dig points.

Sure, but this is just one of many possible workflows. In this workflow, I agree in this case it could be less surprising to remove it.

However it is surprising in other use reasonable (and not uncommon) use cases:

- in the case where a user has their `subjects_dir` selected (likely the default), then picks their dig source, then picks the MRI subject, what you would propose would remove their dig source.
- in the case where someone is looking for a surrogate MRI that fits a dig source

Moreover, in `mne_analyze` you can change MRI subject and the dig info is never removed.

So I'm still -1 on making an MRI change remove the dig source by default. Maybe a (off by default) command line option `--clear-dig` that removes the `dig` if the `subject` is changed?

**Comment by agramfort** [comment]
ok I see the use case and the rationale then. I will be able to argue like you next time
I hear someone complain :)

I guess we can close

**Comment by larsoner** [comment]
Yes we can classify this as a [BEBKAC](https://en.wikipedia.org/wiki/User_error) bug :)
