### ISSUE TITLE
mne.gui.coregistration does not properly update on change to SUBJECTS_DIR

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-python#5204]
It seems that selecting the `SUBJECTS_DIR` from the dropdown menu from `mne coreg` does not find the surfaces. However, manually setting it in the command line before starting `mne coreg` seems to work. This seems unexpected behavior to me. I get the following for the sample data:

![nothing](https://user-images.githubusercontent.com/15852194/39990559-291a4c94-576d-11e8-8cf4-4939562bd9c8.png)

Let me know if you need more information to reproduce.

**Comment by larsoner** [comment]
Not a critical bug (and probably a pain to fix) so moving to 0.18

**Comment by larsoner** [comment]
I can no longer reproduce, I'm assuming this was fixed with some of the coreg refactors
