### ISSUE TITLE
CTF regularization parameter unnecessarily fixed

### ISSUE THREAD

**Issue by anttimc** [mne-tools/mne-python#5206]
https://github.com/mne-tools/mne-python/blob/dc8fab44153c7e01cfc339dc65e17de538d391ec/mne/minimum_norm/psf_ctf.py#L243-L244

Parameter lambda2 is ignored by overwriting the variable in _get_matrix_from_inverse_operator(). The default value for lambda2 is already 1/3**2, so the same default functionality could be maintained by removing these lines.

**Comment by larsoner** [comment]
Agreed that line should not be there

**Comment by agramfort** [comment]
PR welcome. thanks

**Comment by agramfort** [comment]
fixed by #5393
