### ISSUE TITLE
check info against compensation chans (Continued)

### ISSUE THREAD

**Issue by bloyl** [mne-tools/mne-python#5218]
Following #5133 exceptions are raised when meas_info objects are created with channels that don't allow for attached compensation matrices to be applied/interpreted.
A coupled PR will come once I have some time. 

This is a running list of places where this causes a problem

- [ ] ica.plot_overlay()
       specifically  `picks = [inst.ch_names.index(k) for k in ica.ch_names]` of viz.plot_ica_overlay

**Comment by agramfort** [comment]
can you share a snippet to replicate?

**Comment by larsoner** [comment]
Note that this affects `examples/datasets/spm_faces_dataset.py`

**Comment by agramfort** [comment]
luke or @larsoner are you on it?

**Comment by agramfort** [comment]
we can have a quick hangout if it helps
