### ISSUE TITLE
problems with spm_faces_dataset

### ISSUE THREAD

**Issue by joewalter** [mne-tools/mne-python#5222]
I was trying to run the example spm_faces_dataset.py with the current master and dataset on my Windows PC. This resulted in a RuntimeError: "Compensation grade 3 has been applied, but compensation channels are missing". Can someone confirm?

**Comment by agramfort** [comment]
I can replicate.

@larsoner you worked recently on the Compensation pbs. Can you have a look?

**Comment by larsoner** [comment]
This appears to be a dup of #5218 (plot_overlay)
