### ISSUE TITLE
DOC: Reporting filter properties

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-python#5226]
Concerning filtering, in [Wiedmann et al. (2015)](https://pdfs.semanticscholar.org/2797/1b6c30851ea1046a2504a50cbec37459e78d.pdf) they recommend to report:

> All filter parameters, including **filtertype** (high-pass, low-pass, band-pass, band-stop, FIR, IIR), **cutoff frequency** (including definition), **filter order (or length),** roll-off or **transition bandwidth**, **passband ripple** and **stopband attenuation**, **filter delay**(zero-phase, linear-phase, non-linear phase) and **causality**, and direction of computation (one-pass forward/reverse,or two-pass forward and reverse) must be reported

Checking the MNE documentation and specifically the [background on filtering](https://martinos.org/mne/stable/auto_tutorials/plot_background_filtering.html) and [tutorial](https://martinos.org/mne/stable/auto_tutorials/plot_artifacts_correction_filtering.html#sphx-glr-auto-tutorials-plot-artifacts-correction-filtering-py), there are some questions that I have:

1. What is the definition of the cutoff frequency by the filters used in MNE? In the docstring of [`create_filter`](https://mne-tools.github.io/dev/generated/mne.filter.create_filter.html) it say that -6dB is the middle of the transition window. Does that mean that in MNE, the middle of the transition window is the "half-amplitude" cutoff? (as opposed to half-power)

2. Filter length and transition bandwidth are being printed upon calling `raw.filter()`, which is nice - but how would I compute them without having to filter data and copying the values from the console?

3. I haven't seen a method to calculate stopband attenuation and passband ripple in MNE. Did I miss it? Is there some straight forward way using scipy?

Does anyone besides me think that these outputs would be a nice addition to the `raw.info`? Maybe providing filter information as a dictionary containing the meta data named above in addition to the frequencies which are the only thing that is specified currently ... opinions?

**Comment by larsoner** [comment]
Someone needs to check all of these things (preferably by showing them by updating the tutorial) because I can't remember offhand, but yes what you say sounds right. Do you have the time / knowledge to check and update it?

> Filter length and transition bandwidth are being printed upon calling raw.filter(), which is nice - but how would I compute them without having to filter data and copying the values from the console?

`mne.filter.create_filter` will create the filter and give these log messages. You can pass it a dummy `data` array. Actually we should proably make `data=None` a possibility, meaning "skip length checks/warnings".

> I haven't seen a method to calculate stopband attenuation and passband ripple in MNE. Did I miss it? Is there some straight forward way using scipy?

This would be another great addition to the tutorial. We use standard `scipy.signal.firwin` design, so these properties are dependent upon the `window` used in design. In theory this might be documented in  SciPy. If not, they should probably be added there. They are standard windows so the values should be listed online somewhere, probably on Wikipedia. We should make a table...

> Does anyone besides me think that these outputs would be a nice addition to the raw.info?

Yes in principle but in practice there is a limited set of items we can put in `raw.info` and the filter parameters are not included. If you want you can modify `raw.info['description']` string to include this information.

**Comment by sappelhoff** [comment]
I'll see what I can do ... I don't have a lot of knowledge about filters though, .. and the [scipy docstring for firwin](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.firwin.html) does not specify details about the cutoff either. So maybe I will post a question to stackexchange signal processing or stackoverflow for help ...

related: The docstring "Returns" seems to be wrong. It actually returns `h`, the filter coefficients:

https://github.com/mne-tools/mne-python/blob/45898628a416691a89a8d48ca38860298cfb58fc/mne/filter.py#L337-L374

**Comment by larsoner** [comment]
Here is a table, the "peak approximation error" here is really the stop-band attenuation (e.g., 53 dB for Hamming) which matches the table in Ifeachor and Jervis p357 (except Blackman attenuation, which I&J list as 75 dB):

https://www.allaboutcircuits.com/technical-articles/design-examples-of-fir-filters-using-window-method/

Filters designed using windowed FIR design have equal pass-band and stop-band ripple, so giving the attenuation effectively gives you those numbers, too.

**Comment by sappelhoff** [comment]
That's already great. Do you suggest that I copy the table (Ifeachor and Jervis) into the updated version of the "Background on Filtering" example? 

![p294](https://user-images.githubusercontent.com/9084751/40492652-40e945c6-5f71-11e8-8d26-bd7841c90b38.png)


I'd do that together with a short intro on Wiedmann's recommendations on what to report of filters ... then followed by a code block on how to get transition bandwidth and filter length. 

Then the only missing information at this point is:

- are the `scipy.signal.firwin` filter cutoffs specified in half-amplitude or half-power at the middle of the transition band?
- source that "Filters designed using windowed FIR design have equal pass-band and stop-band ripple" (the table actually suggests otherwise?)
- all of the above information for IIR filters?

**Comment by jona-sassenhagen** [comment]
... would be super cool if we had a function to automatically add a fully specified methods section report from filter settings :)

**Comment by larsoner** [comment]
This could be added to the `logger.info` of `create_filter`

**Comment by larsoner** [comment]
Reopening this since @bmaess brought up the idea again, and noted we should do this for IIR filters, as well.

**Comment by bmaess** [comment]
Concerning the -3dB versus -6dB problem: Both is 'correct' and it offers a very elegant way to publish the cutoff limits for the forward-backward filters: design the filter using the -3dB cutoff and in case of the two-pass filter - present the cutoff values as -6dB values. If the corresponding report also mentions the damping of the cutoff, there should be no problem. A bandpass designed as a single-pass 5th order butterworth with -3dB cutoffs at 8 and 12 Hz becomes a two-pass filter of 10th order butterworth with -6dB cutoffs at 8 and 12 Hz.
