### ISSUE TITLE
allow to pass a cov to beamformer filters to get a static image as in FieldTrip

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#5229]
cc @britta-wstnr @wmvanvliet

**Comment by britta-wstnr** [comment]
giving back a power estimate? We have ``_lcmv_source_power`` which could be changed accordingly. I think I even started that somewhere and can have a look soon.
It is in the part that is not touched by https://github.com/mne-tools/mne-python/pull/5135 so it shouldn't clash with that one either.

**Comment by vlitvak** [comment]
I must say I'm only getting to grips with MNE code structure but to me it seems that a sensible way to implement this would be as apply_lcmv_covariance that would take covariance as an input and output a source time course with a single frame.

**Comment by robertoostenveld** [comment]
note that the units would be power rather than amplitude, and the values cannot be negative, whereas the source time (normally) could

**Comment by wmvanvliet** [comment]
The implementation can be mostly taken from our `apply_dics_csd` method.
