### ISSUE TITLE
Can't import mne when installing from pip

### ISSUE THREAD

**Issue by mivade** [mne-tools/mne-python#5248]
For various reasons I don't want to install MNE via the [instructions](https://martinos.org/mne/stable/install_mne_python.html) in the documentation, but rather by using pip. However, the package on PyPI is not setup correctly to install dependencies. By simply trying to `import mne`, I get the following:

```python
>>> import mne
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/depalati/miniconda3/envs/thetamod/lib/python3.6/site-packages/mne/__init__.py", line 25, in <module>
    from .io.pick import (pick_types, pick_channels,
  File "/Users/depalati/miniconda3/envs/thetamod/lib/python3.6/site-packages/mne/io/__init__.py", line 15, in <module>
    from .base import BaseRaw
  File "/Users/depalati/miniconda3/envs/thetamod/lib/python3.6/site-packages/mne/io/base.py", line 22, in <module>
    from ..channels.channels import (ContainsMixin, UpdateChannelsMixin,
  File "/Users/depalati/miniconda3/envs/thetamod/lib/python3.6/site-packages/mne/channels/__init__.py", line 8, in <module>
    from .montage import (read_montage, read_dig_montage, Montage, DigMontage,
  File "/Users/depalati/miniconda3/envs/thetamod/lib/python3.6/site-packages/mne/channels/montage.py", line 19, in <module>
    from ..viz import plot_montage
  File "/Users/depalati/miniconda3/envs/thetamod/lib/python3.6/site-packages/mne/viz/__init__.py", line 6, in <module>
    from .topo import plot_topo_image_epochs, iter_topography
  File "/Users/depalati/miniconda3/envs/thetamod/lib/python3.6/site-packages/mne/viz/topo.py", line 14, in <module>
    from matplotlib.colors import colorConverter
ModuleNotFoundError: No module named 'matplotlib'
```

This can be fixed by including dependencies with the `install_requires` keyword argument in `setup.py`. Alternatively, why is `mne/__init__.py` importing so many things in the first place? If only a small subset of MNE's functionality is required, why should a user have to install so many unused dependencies?

**Comment by larsoner** [comment]
> This can be fixed by including dependencies with the install_requires keyword argument in setup.py. 

It used to be a bad idea to include numpy/scipy/matplotlib in `install_requires` because of complications with building them properly. Maybe nowadays with wheels it's not a big problem.

> Alternatively, why is mne/__init__.py importing so many things in the first place? If only a small subset of MNE's functionality is required, why should a user have to install so many unused dependencies?

Our assumption is that the vast majority of people using MNE will have (at minimum) a standard scientific Python stack installed, meaning numpy/scipy/matplotlib are already there. Having `import mne` import all namespaces makes things easier for users, and having top-level imports for things like `matplotlib` makes things easier for maintainers.

**Comment by agramfort** [comment]
btw matplotlib should not be a strong dependency... only numpy and scipy.

what do you recommend? we went the conda route because we had issues
with pip and mayavi/vtk.

regarding conda package if people are still tempted to do "conda
install mne" and it's not maintained we should remove the conda
package.

**Comment by cbrnr** [comment]
FYI `pip install mne` works fine, it automatically pulls in all hard dependencies including `matplotlib`.

**Comment by cbrnr** [comment]
+1 for adding hard dependencies with `install_requires` if this works now - any way to test this? Personally, I'd leave `matplotlib` as a hard dependency unless we switch to nested imports.

**Comment by larsoner** [comment]
It should work now that `numpy` and `scipy` wheels are available with OpenBLAS.

The right way to test would be to add a `pip` version on the CIs. I can give it a shot. Travis has been horribly slow the past few days though so it'll take a while to iterate.

**Comment by jona-sassenhagen** [comment]
>regarding conda package if people are still tempted to do "conda install mne" and it's not maintained we should remove the conda package.

Agreed. Let's show our best work :)

**Comment by mivade** [comment]
Thanks, @larsoner!
