### ISSUE TITLE
Brainvision stim channel creation fails if event durations are 0

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#5249]
Stim channels for brainvision and EEGLAB files are created like this:

```
    for onset, duration, trigger in events:
        stim_channel[onset:onset + duration] = trigger
```

If the duration is 0, which it often is, this will result in no events being recorded.

I am not sure how to deal with this.

The events are still available to the user at `raw._events`, but `mne.find_events` etc won't work.

**Comment by larsoner** [comment]
we should probably make the min duration 1 sample

**Comment by jona-sassenhagen** [comment]
BV vmrk files have a duration column that is set to 0 for the file I'm looking at ... but yeah, we can do `min(duration, 1)` in _create_stim_channel`

**Comment by mmagnuski** [comment]
I've just had somebody contact me with this problem (as it turned out) - I'm definitely +1 on Jona's proposal.

**Comment by agramfort** [comment]
agreed

**Comment by jona-sassenhagen** [comment]
@agramfort ... and you actually said "agreed" here :)

**Comment by agramfort** [comment]
yes there is no cleaner solution now.
