### ISSUE TITLE
"Brain" object initialised with "curv" parameter; doesn't exist

### ISSUE THREAD

**Issue by jshanna100** [mne-tools/mne-python#5260]
MNE 0.16.1, mne.viz._3d.py, line 1665:

        brain = Brain(subject, hemi=hemi, surf=surface, curv=True,
                      title=title, cortex=cortex, size=size,
                      background=background, foreground=foreground,
                      figure=figure, subjects_dir=subjects_dir,
                      views=views)

Variable "curv" is not part of the init parameters for class Brain. Seems to work fine if I just remove it.

**Comment by larsoner** [comment]
Thanks for the report, this is fixed in master and will be in the next maintenance release.
