### ISSUE TITLE
ENH/IO start / stop arguments for EEG readers

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#5273]
Reading long EEG recordings can be a challenge on most computers. We should see which readers already support reading segments from raw and add start / stop args where ever needed. A current more urgent case is the EGI reader.

cc @agramfort

**Comment by larsoner** [comment]
A workaround is to use `preload` as `str`, which will use memmapping (no restriction on memory size then)

**Comment by dengemann** [comment]
That's actually true. It may just be slower. Looking at the more recently added .get_data in combination with preload I'm thinking we may actually be good already. Let me check out how it works in practice.

**Comment by larsoner** [comment]
> That's actually true. It may just be slower. 

In theory it should be at least as fast as reading segment by segment from the disk directly (assuming the file and the memmapped file are on the same hard disk).

**Comment by agramfort** [comment]
the recommended way is to do:

raw = read_raw...(preload=False)
raw.crop(tmin, tmax)
raw.load_data()

ideally this should work for all readers.

**Comment by dengemann** [comment]
Good point. I was not remembering that crop works without preloading. I think we're good here. Perhaps we can add some content to FAQ.

**Comment by dengemann** [comment]
Closing for now.
