### ISSUE TITLE
DOC: Explain core MNE concepts in glossary.rst file

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#5275]
We have a few terms that are MNE specific, or for which multiple names would make sense, but we've settled on one. We don't have a doc page going through all of them, right?

Would it make sense to have such a page?

Thinking of:
- selection
- group_by
- picks
- raw
- epochs
- evoked
- info
- montage
- events (explain markers, triggers, stim channel ... here)
- ...

**Comment by sappelhoff** [comment]
+1 ... I was confused by "picks" in the beginning

**Comment by agramfort** [comment]
+100

like sklearn glossary: http://scikit-learn.org/dev/glossary.html

can you start this?

**Comment by cbrnr** [comment]
And even more basic things like raw, epoch, evoked, projection/projector, ...

**Comment by agramfort** [comment]
ok I edited a bit the issue to start listing things we should put in the
glossary. Can you complement?

**Comment by jona-sassenhagen** [comment]
I guess it should live in tutorials, and be referenced from the manual? I can make a sketch PR soon.

**Comment by agramfort** [comment]
would be great
