### ISSUE TITLE
Add COC, contributing, issue and PR templates

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#5281]
Should we add a code of conduct to our project? Most projects seem to adopt the [Contributor Covenant](https://www.contributor-covenant.org/) these days. Thoughts? If we decide to adopt this as well, how can people report violations? I assume opening an issue is not the best way to do this, but I don't know if we have a project email address.

**Comment by agramfort** [comment]
honestly I don't think MNE is big enough to necessitate this. So far I have
never
observed wrong behavior but maybe I am the one to blame? :)

**Comment by larsoner** [comment]
SciPy recently adopted a contributor-covenant-like code of conduct, which includes how to report issues (they have members of a committee). I have no problem with us adding this if it seems worthwhile to pepole. So I'm +0.5 on it (not a full +1 because I also agree with @agramfort that our risk level is lower than other libs due to specificity of use cases)

**Comment by cbrnr** [comment]
I agree with you that currently it is not really necessary. However, I think that having a code of conduct doesn't hurt either. Although MNE is much smaller than e.g. SciPy, it is also not a small project anymore. Since the Contributor Covenant obviously contains rules that I think we all support, we could just as well add it to the project so that we are as open and inclusive as possible. So also +0.5 from my side.

**Comment by cbrnr** [comment]
Does anyone else have an opinion?

**Comment by massich** [comment]
Actually, github uses those things for its metrics.
see this 
![image](https://user-images.githubusercontent.com/7044835/41842131-46a73006-786a-11e8-94c2-aba8f8d2ca91.png)

I'm +1 to pick up conde-of-conduct, issue template and PR template from a project similar to MNE-python, modify them, add them and point contribute.md to our `doc/contribute.rst` So that we get the bar to the right ;)

**Comment by cbrnr** [comment]
Good point. I'm also +1 for getting all ticks, but I don't like issue and PR templates. They add lots of boilerplate that makes it difficult to get to the core of the issue/PR. Unless of course we can just write some recommendations how to open an issue/PR and we don't pre-fill the actual issue/PR text field.

**Comment by massich** [comment]
I think that pre-fill issue/PRs a are good thing. I think that regular contributers would just ignore them, however I find it really helpful when I don't know a project.

As a scikit-learn core dev phrase it: 
> I like the issue/PR templates, I `ctrl+a` and start taping.

**Comment by cbrnr** [comment]
I completely agree with this person. Adding this extra step is creating a lot of unnecessary work (even if it is just pressing Ctrl+a). I'd prefer to have an empty template, and for newbies we can still have some text that explains how to create good issues/PRs.

**Comment by cbrnr** [comment]
@massich can you check if it is possible to use the existing `doc/contribute.rst` file? The [help page](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) only talks about how to create a new file.

**Comment by larsoner** [comment]
Can you look at what SciPy did? I think it was a google group with a few volunteer admins added

**Comment by cbrnr** [comment]
Yes, they set up scipy-conduct@googlegroups.com (https://github.com/scipy/scipy/blob/master/doc/source/dev/conduct/code_of_conduct.rst).

Should we set up mne-conduct@googlegroups.com? Who will be on the committee (i.e. have access to this group)?

**Comment by cbrnr** [comment]
As a more professional-looking alternative to an @googlegroups address (which would also be more appropriate from a privacy point of view), might it be possible to create an email account @martinos.org?

**Comment by larsoner** [comment]
It might be possible but increases admin difficulty, so I'd rather not

**Comment by larsoner** [comment]
As for access we'd need volunteers who are frequent contributors

**Comment by cbrnr** [comment]
OK, then l'll go ahead and create the google groups address. Since I assume there won't be many violation reports, I volunteer to be on the committee. Who else? We need at least three people.

**Comment by larsoner** [comment]
I can be on it, and also @agramfort unless he objects

**Comment by agramfort** [comment]
you're in charge

**Comment by cbrnr** [comment]
Now that we have our CoC, what about linking our existing contributing guide? Do you have time to look @massich?

Also, it would be great if we had short texts for our issue/PR templates. However, if GitHub insists on creating an actual template that users like me select and delete, it's probably not worth it. I don't think that this is possible, but maybe I didn't check hard enough. Anyone care to double-check?

**Comment by agramfort** [comment]
we just miss an issue template now.

@cbrnr or @massich can you have a look?

**Comment by agramfort** [comment]
see https://github.com/mne-tools/mne-python/community

**Comment by cbrnr** [comment]
Have we decided that we need templates? It seems like adding this extra step just to turn all community features green is probably not worth it because most reports seem to be OK. But if we decide we need it, I'd go with minimal templates (one minimal PR template and two issue templates for bug reports and feature requests).

**Comment by agramfort** [comment]
Issue template suggested to provide a test file and a code snippet to
replicate the error, as well as report mne.sys_info() would be nice.
It would save us some emails.

**Comment by cbrnr** [comment]
Closing since we already added everything.
