### ISSUE TITLE
"picks" attribute is null list in _sources_as_epochs/evoked

### ISSUE THREAD

**Issue by jshanna100** [mne-tools/mne-python#5286]
"picks" attribute is null list in _sources_as_epochs/evoked in the case when add_channels is None. This breaks functionality when, for example, you want to pick individual components out of the resulting epochs/evoked object with .pick_channels, as this function require a "picks" array.

**Comment by agramfort** [comment]
can you share a code snippet to expose / replicate the pb?

**Comment by jshanna100** [comment]
In the else case below picks is an empty list.

def _sources_as_epochs(self, epochs, add_channels, concatenate):
        """Aux method."""
        out = epochs.copy()
        sources = self._transform_epochs(epochs, concatenate)
        if add_channels is not None:
            picks = [epochs.ch_names.index(k) for k in add_channels]
        else:
            picks = []
        out._data = np.concatenate([sources, epochs.get_data()[:, picks]],
axis=1) if len(picks) > 0 else sources

**Comment by agramfort** [comment]
I am sorry I don't get the issue. This function is executed by a test and
it's fine
to do things like this:

>>> epochs.get_data()[:, []]
array([], shape=(1, 0, 241), dtype=float64)

**Comment by jshanna100** [comment]
Yes, but it will fail if one calls e.g. .pick_channels on it, because that function expects an array to be in self.picks. One can hack around it by doing something like 

`epochs.picks = np.array(range(len(epochs.ch_names)))`

**Comment by agramfort** [comment]
please share a full gist to replicate a crash so I don't have to reverse
engineer what you have in mind.

ideally paste it at: https://gist.github.com/

thanks

**Comment by jshanna100** [comment]
I can no longer replicate the bug, and don't really have an explanation for it. Yesterday, the code required the hack I mentioned above in order to run, and today, it doesn't. Really sorry to waste your time...
