### ISSUE TITLE
Inclusion of buffer_size_sec breaks epochs.add_channels

### ISSUE THREAD

**Issue by jshanna100** [mne-tools/mne-python#5287]
This entry, AFAIK, only exists in raw objects, so it breaks when running this function on non-raw data.

https://github.com/mne-tools/mne-python/blob/e1b441460b3eb426dea9a90e1d250da18a169f12/mne/io/meas_info.py#L1692

**Comment by agramfort** [comment]
sounds like a good bug fix opportunity :)

**Comment by larsoner** [comment]
Fixed by #5327 which is now merged
