### ISSUE TITLE
broken links to source in docs

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#5290]
Some links from function documentation in the API reference to the function definition in the source code are broken.  For example, on this page: https://mne-tools.github.io/dev/generated/mne.stats.spatio_temporal_cluster_1samp_test.html

the link text `[source]` to the right of the function signature links to `http://github.com/mne-tools/mne-python/blob/master/doc/%3Cstring%3E#L1210-L1339` (note the `<string>` near the end of the URL)

Also occurs for `spatio_temporal_cluster_test`, `permutation_t_test`, `permutation_cluster_1samp_test` (but is not a sitewide problem --- it works fine for e.g., `fdr_correction`; maybe it's only broken for functions in `cluster_level.py`?)

**Comment by larsoner** [comment]
It will be broken for anything that uses the verbose decorator. We need to make the linking function smarter
