### ISSUE TITLE
mne.viz.plot_evoked_joint does not accept "time_unit" parameter, but warns about it

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-python#5294]
See this screenshot as an illustration:

![image](https://user-images.githubusercontent.com/9084751/41782022-4e045d8e-7639-11e8-95c1-c0e64dd67df1.png)

**Comment by larsoner** [comment]
You need to pass it in the `ts_args` and `topo_args` dicts

**Comment by sappelhoff** [comment]
Thanks @larsoner
