### ISSUE TITLE
Digitizing EEG electrode location

### ISSUE THREAD

**Issue by neelesh314** [mne-tools/mne-python#5299]
Hi, 

Is there MNE library support for digitizing eeg electrode locations using Polhemus Patriot digitizer? Basically, I am looking for an MNE equivalent of the following Brainstorm package:

https://neuroimage.usc.edu/brainstorm/Tutorials/TutDigitize

Thanks, 
Neelesh

**Comment by agramfort** [comment]
no there is no such GUI.

you should use the MNE mailing list for usage questions and not the issue
tracker.

https://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis

you should get suggestions and help there.

**Comment by neelesh314** [comment]
thanks!
