### ISSUE TITLE
merge_grad_data and rescale in plot_tfr_topomap

### ISSUE THREAD

**Issue by Teekuningas** [mne-tools/mne-python#5305]
Hi,

I was wondering if the order of merge_grad_data and rescale could be reversed in https://github.com/mne-tools/mne-python/blob/96bd8661599558024cdcd9edcc5eb0e12919722b/mne/viz/topomap.py#L1050

Now merging is losing the information of inhibition that is revealed by the rescale.

**Comment by agramfort** [comment]
can you be more explicit? Not sure to follow what you mean by
"inhibition that is revealed by the rescale."

**Comment by Teekuningas** [comment]
Or actually even better, use method='mean' in the merge_grad_data call. I don't see benefits in using 'rms' for power data. The problem is that when you use 'mag', 'planar1', 'planar2' or 'eeg' with baseline correction, you can get topomap that shows as red the areas where power has increased and as blue the areas where power has decreased compared to baseline. When you use 'grad', the plot will have only red colors as the merge_grad_data will force every value to be non-negative, and does that after rescaling.

**Comment by larsoner** [comment]
@Teekuningas the reason `rms` is used rather than `mean` is that the grads are orthogonal in the tangential plane. So doing a plain `mean` will cause anything in the upper right or lower left of this tangential plane to add constructively, and anything in the lower right or upper left will cancel out. I can't think of a scenario where you would actually want this interpretation.

**Comment by Teekuningas** [comment]
That probably makes sense; I kind of wanted a shortcut for also plotting a "difference tfr" (tfr1 - tfr2). But for a normal tfr, where every value is positive, it should be possible to first take the RMS and then rescale to have have meaningful plots where there is power increase and power decrease, shouldn't it?

**Comment by agramfort** [comment]
I agree there should be a way to see ERD (blue) on grads.

the arithmetic could be done after combining grads for this.

PR + an example welcome

**Comment by larsoner** [comment]
Agreed

**Comment by Teekuningas** [comment]
Ok, I'll look into it!
