### ISSUE TITLE
Artifact Correction with ICA

### ISSUE THREAD

**Issue by GalaChen** [mne-tools/mne-python#5336]
Hi,
   I used MNE 0.14.1 to run the "Artifact Correction with ICA". However, when I run the code 
`raw.filter(1, 40, n_jobs=2)`, I got error: "'module' object has no attribute '_args_from_interpreter_flags'
". However, I also can't import '_args_from_interpreter_flags' from module subprocess.
   So, what should I do to solve this problem?

**Comment by larsoner** [comment]
The latest release is MNE 0.16, can you upgrade?

It looks like this bug might be related to a conflict in the Python environments, are you using an old 2.7 env?

**Comment by GalaChen** [comment]
Thanks! I have fixed it!
When I upgrade my subprocess.py, It worked!

**Comment by larsoner** [comment]
Good to hear!
