### ISSUE TITLE
mne.Evoked.plot for different event types

### ISSUE THREAD

**Issue by carlosgmartin** [mne-tools/mne-python#5339]
How can I get [mne.Evoked.plot](https://martinos.org/mne/dev/generated/mne.Evoked.html#mne.Evoked.plot) to plot the averages for different event types on the same axes, but in different colors?

**Comment by agramfort** [comment]
can

https://martinos.org/mne/stable/generated/mne.viz.plot_compare_evokeds.html#mne.viz.plot_compare_evokeds

do the job?

This tutorial can be useful:

https://martinos.org/mne/stable/auto_tutorials/plot_visualize_evoked.html

**Comment by carlosgmartin** [comment]
I'm getting `RuntimeError: No digitization points found.` when I try to set the `picks` parameter. Do you know why this might be happening?

**Comment by jona-sassenhagen** [comment]
Can you show your code? It might be a bug.

**Comment by jona-sassenhagen** [comment]
@carlosgmartin is this still an issue?

**Comment by carlosgmartin** [comment]
I'm no longer having this issue.
