### ISSUE TITLE
Brainvision does not read meas_date properly

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-python#5357]
The `raw.info['meas_date']` is defined in the [docs](https://martinos.org/mne/dev/generated/mne.Info.html#mne.Info) to do this:

```
meas_date : list of int

    The first element of this list is a POSIX timestamp
 (milliseconds since 1970-01-01 00:00:00)
denoting the date and time at which the measurement was taken.
The second element is the number of microseconds.

```
First of all: Why would we need a list of
- POSIX miliseconds
- and then POSIX microseconds?

Second: When reading brainvision data, the following is executed concerning `raw.info['meas_date]`

https://github.com/mne-tools/mne-python/blob/241161d00d685c988a5937888f8c76959d0cd224/mne/io/brainvision/brainvision.py#L463

Was this perhaps intended as a temporary placeholder but it got forgotten? It is not a list and it does not contain the measurement date but the date at reading of the file.

The actual recording date can be obtained from the .vmrk file. See the documentation from Brain Products below:

![image](https://user-images.githubusercontent.com/9084751/43080197-6fd22da6-8e8f-11e8-8a73-459b98272491.png)

So it usually gets written by the Brain Products equipment at the event called "New Segment". I can make a PR if you agree that the current code is strange.

**Comment by larsoner** [comment]
`time.time()` is wrong, yes please read from the file if you can

**Comment by larsoner** [comment]
> Why would we need a list of
>
> POSIX miliseconds
> and then POSIX microseconds?

Probably due to file storage specifications of FIFF

**Comment by larsoner** [comment]
(microseconds are *in addition to* the specified number of milliseconds)

**Comment by agramfort** [comment]
indeed this needs improvement.

please open a PR.

thanks

**Comment by sappelhoff** [comment]
> (microseconds are in addition to the specified number of milliseconds)
This still does not make sense to me. See this example:

```python
# Parse BrainVision date
date_str = '20131113161403794232'
meas_date = datetime.strptime(date_str, '%Y%m%d%H%M%S%f')

# Convert to format for FIF meas_date
# We need list of unix time ... and unix time in microseconds
meas_date_unix = time.mktime(meas_date.timetuple())
meas_date_unix_micro = meas_date_unix * 1000000.
raw.info['meas_date'] = [meas_date_unix, meas_date_unix_micro]
```

This would give us `[1384355643.0, 1384355643000000.0]`. How does that help?

**Comment by larsoner** [comment]
That looks like a bug
