### ISSUE TITLE
Importing\working with a general format 

### ISSUE THREAD

**Issue by omergra** [mne-tools/mne-python#5360]
Hi, 
I'm working with an EEG/EMG system that was made in my lab. 
The output files from the hardware are 'rhd' files.
I then convert them to xarray dataset for easier analysis.
I was thinking about working with MNE, but there seems to be no general format I can use to import my data. 
Can we open a project to deal with this issue?
 maybe csv or jason files - importing?

Omer

**Comment by larsoner** [comment]
Have you looked at RawArray / EpochsArray / EvokedArray?

**Comment by larsoner** [comment]
https://martinos.org/mne/stable/auto_examples/io/plot_objects_from_arrays.html#sphx-glr-auto-examples-io-plot-objects-from-arrays-py
