### ISSUE TITLE
Can the parameter "picks" be added to EpochArray?

### ISSUE THREAD

**Issue by underscoredam** [mne-tools/mne-python#5372]
The constructor of `EpochArray` does not have the `picks` parameter, while the constructor of its superclass, `BaseEpochs` does. Can I add the parameter and send a pull request?

**Comment by larsoner** [comment]
It doesn't seem totally necessary to add it as you can do data[:, picks,:] and mne.io.pick_info(info,picks) before passing to the constructor

**Comment by agramfort** [comment]
agreed.
