### ISSUE TITLE
Memory-Mapping Preload Fails When Adding Channels

### ISSUE THREAD

**Issue by alexrockhill** [mne-tools/mne-python#5382]
When data is memory-mapped to a file, there is a memory error in:

e-packages/mne/channels/channels.py", line 877, in add_channels
    data = np.concatenate(data, axis=con_axis)
MemoryError

**Comment by jasmainak** [comment]
A [minimal reproducible example](http://sscce.org/) on [gist](https://gist.github.com/) would be very much appreciated

**Comment by alexrockhill** [comment]
https://gist.github.com/alexrockhill/f2ddbae467e8e5728db48834f2601e0d

Here is a gist that could work. There is some difficulty because the memory error depends on the RAM of the machine and also to create a RawArray, one must be able to load the RawArray into memory, so there must be a workaround where many raw files are made and loaded into memory-mapped files.

**Comment by larsoner** [comment]
We could probably handle this more gracefully. It might be possible to resize the memmapped array. If not, then we could make a new one, possibly via param.
