### ISSUE TITLE
ref_meg trouble

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#5384]
My MEG data says this now with essentially anything I do:

```
~/tools/mne-python/mne/io/pick.py in pick_info(info, sel, copy)
    406                     'compensation channels are missing: %s\n'
    407                     'Either remove compensation or pick compensation '
--> 408                     'channels' % (current_comp, comps_missing))
    409             else:
    410                 logger.info('Removing %d compensators from info because '

RuntimeError: Compensation grade 3 has been applied, but compensation channels are missing: ['BG1-3609', 'BG2-3609', 'BG3-3609', 'G11-3609', 'G12-3609', 'G13-3609', 'G22-3609', 'G23-3609', 'P11-3609', 'P12-3609', 'Q11-3609', 'Q12-3609', 'Q13-3609', 'R12-3609', 'R13-3609', 'R22-3609', 'R23-3609']
Either remove compensation or pick compensation channels
```

... what? Happens, for example, when I do `raw.pick_types(meg=True, ref_meg=False)`.
I can `raw.apply_gradient_compensation(0)`, but then my data looks kind of shitty.

**Comment by jona-sassenhagen** [comment]
This works:

```
picks = mne.pick_types(raw.info, meg=True, ref_meg=False)
mne.viz.plot_topomap(raw._data[picks], mne.pick_info(raw.copy().apply_gradient_compensation(0).info, picks));
```

But it feels very wrong. And it doesn't work for many functions.

**Comment by larsoner** [comment]
We have had a number of these. Should be fixed by #5342, feel free to comment on that proposal

**Comment by agramfort** [comment]
@jona-sassenhagen what is a gist that allows to replicate this issue? you have a number of tiny CTF files in the mne-testing-data folder.

**Comment by agramfort** [comment]
@jona-sassenhagen a fix along these lines https://github.com/mne-tools/mne-python/pull/5388

please share a gist to know how we can fix this.

**Comment by larsoner** [comment]
@jona-sassenhagen can you write a minimal example from a `testing` or `mne/io/data/*.fif` file? It will make it easy for us to test that fixes/workarounds from #5342 work. It would be good to get to this example in the next week so a fix can be made the next week to make it into 0.17.

**Comment by larsoner** [comment]
@jona-sassenhagen any chance to make this `gist` quickly? There is a PR open to take care of most of these problems and it would be great to have this test case

**Comment by larsoner** [comment]
Okay actually I think this does it:
```
import os.path as op
import mne
raw = mne.io.read_raw_fif(op.join(op.dirname(mne.__file__), 'io', 'tests',
                                  'data', 'test_ctf_comp_raw.fif'))
evoked = mne.EvokedArray(raw[:, :10][0], raw.info)
evoked.pick_types(meg=True, ref_meg=False)
evoked.plot_topomap()
```
It fails on `master` but passes on the open PR, fortunately!
