### ISSUE TITLE
Missing support for arbitrary BrainVision marker types

### ISSUE THREAD

**Issue by hekolk** [mne-tools/mne-python#5387]
The BrainVision ``vmrk`` files allow for arbitrary marker types, but MNE currently only handles ``Response`` markers separately.

For example, we use optical markers to correct for display latencies, which leads to a marker files looking like the following excerpt:

```
Mk79=Stimulus,S224,125503,1,0
Mk80=Optic,O  1,125599,1,0
Mk81=Response,R  1,127066,1,0
```

The documentation allows for arbitrary types (see #5357). Currently only the type ``Response`` is handled  (``response_trig_shift`` parameter, https://github.com/mne-tools/mne-python/blob/master/mne/io/brainvision/brainvision.py#L290) and otherwise the type is ignored, which can lead to different markers getting the same event id.

One option would be to add a new ``trig_shift_by_type`` parameter through which users could supply a dictionary of the form ``{'Stimulus': 0, 'Optic': 1000, 'Response': 2000}`` (and deprecate ``response_trig_shift``).

**Comment by agramfort** [comment]
no objection for the suggested change.
