### ISSUE TITLE
installation problems on python3

### ISSUE THREAD

**Issue by nugenta** [mne-tools/mne-python#5390]
EDIT: To do:

- [ ] update install docs to mention warnings are not fatal
- [ ] update `environment.yml` to avoid mkl warnings
- [ ] update install docs to mention the MESA version workaround @nugenta found

Original post:

I had this working, then a system upgrade broke my conda environments.  Now I'm running a miniconda install. I've tried:

$ curl -O https://raw.githubusercontent.com/mne-tools/mne-python/master/environment.yml
$ conda env create -f environment.yml
$ source activate mne
$ mne coreg

I've pasted in the voluminous error at the bottom. The interface pops up, and looks fine, but no brain is shown and the error pasted in below is resent everytime you touch anything. 

I've tried specifying ETS_TOOKIT and QT_API and then I get 
"RuntimeError: No pyface.toolkits plugin found for toolkit qt5' 

I tried updating pyface; that downgrades twister.

I tried updating qt to 5.10, also no luck.

I did notice a potential problem:
$ conda list | grep vtk
vtk                       8.1.1                     <pip>
vtk                       8.1.0           py36h9686630_201  

I don't know if the two versions of vtk could be conflicting.

ERROR: In /work/standalone-x64-build/VTK-source/Rendering/OpenGL2/vtkShaderProgram.cxx, line 431
vtkShaderProgram (0x556abe29b9b0): 

ERROR: In /work/standalone-x64-build/VTK-source/Rendering/OpenGL2/vtkShaderProgram.cxx, line 430
vtkShaderProgram (0x556abe29c3a0): 1: #version 120
2: #ifdef GL_ES
3: #if __VERSION__ == 300
4: #define attribute in
5: #define varying out
6: #endif // 300
7: #else // GL_ES
8: #define highp
9: #define mediump
10: #define lowp
11: #if __VERSION__ == 150
12: #define attribute in
13: #define varying out
14: #endif
15: #endif // GL_ES
16: 
17: 
18: /*=========================================================================
19: 
20:   Program:   Visualization Toolkit
21:   Module:    vtkPolyDataVS.glsl
22: 
23:   Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
24:   All rights reserved.
25:   See Copyright.txt or http://www.kitware.com/Copyright.htm for details.
26: 
27:      This software is distributed WITHOUT ANY WARRANTY; without even
28:      the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
29:      PURPOSE.  See the above copyright notice for more information.
30: 
31: =========================================================================*/
32: 
33: attribute vec4 vertexMC;
34: 
35: // frag position in VC
36: varying vec4 vertexVCVSOutput;
37: 
38: // optional normal declaration
39: attribute vec3 normalMC;
40: uniform mat3 normalMatrix;
41: varying vec3 normalVCVSOutput;
42: 
43: // extra lighting parameters
44: //VTK::Light::Dec
45: 
46: // Texture coordinates
47: //VTK::TCoord::Dec
48: 
49: // material property values
50: //VTK::Color::Dec
51: 
52: // clipping plane vars
53: //VTK::Clip::Dec
54: 
55: // camera and actor matrix values
56: uniform mat4 MCDCMatrix;
57: uniform mat4 MCVCMatrix;
58: 
59: // Apple Bug
60: //VTK::PrimID::Dec
61: 
62: // Value raster
63: //VTK::ValuePass::Dec
64: 
65: void main()
66: {
67:   //VTK::Color::Impl
68: 
69:   normalVCVSOutput = normalMatrix * normalMC;
70: 
71:   //VTK::TCoord::Impl
72: 
73:   //VTK::Clip::Impl
74: 
75:   //VTK::PrimID::Impl
76: 
77:   vertexVCVSOutput = MCVCMatrix * vertexMC;
78:   gl_Position = MCDCMatrix * vertexMC;
79: 
80: 
81:   //VTK::ValuePass::Impl
82: 
83:   //VTK::Light::Impl
84: }
85: 

ERROR: In /work/standalone-x64-build/VTK-source/Rendering/OpenGL2/vtkShaderProgram.cxx, line 431
vtkShaderProgram (0x556abe29c3a0):

**Comment by agramfort** [comment]
are you working on a remote system?

**Comment by nugenta** [comment]
Yes; I'm using NoMachine.

**Comment by agramfort** [comment]
ok so it's via a remote desktop system.

Do you have the pb if you work directly from the machine? Just to know
if it can be a VNC issue.

**Comment by nugenta** [comment]
It's a centralized server I don't have access to.  I got mne coreg running fine under python 2.7 through NoMachine, back when the python3 install was more experimental. I don't remember if I had to change anything to make it work.

Do you think the two versions of VTK is a problem? I've similar issues with cloning environments or using .yml's before. You get an environment working, then export a .yml. The problem is that the .yml doesn't contain the order you installed things in. Modules get installed by conda as dependences, then pip may reinstall them without removing or upgrading the original conda installed module.

Do you have a .yml that has specific versions rather than >=?

**Comment by agramfort** [comment]
I would make a minimal example of failure using mlab test functions and
report the issue to mayavi folks.

**Comment by larsoner** [comment]
Actually NoMachine [should be able to deal with modern OpenGL](https://unix.stackexchange.com/questions/233571/enabling-graphics-acceleration-for-opengl-over-remotely-via-vpn-from-ubuntu-clie) so what I wrote might not be the problem.

One thing you could try is:
```
$ pip uninstall mayavi
$ conda remove vtk
$ pip install --upgrade mayavi
$ python -ic "from mayavi import mlab; mlab.test_plot3d()"
```
If it works, then it was due to the VTK version conflict. If you get an error, can you paste the output of:
```
$ glxinfo | grep -i version
```
We should do this first to make sure you have support for modern OpenGL on your system. I think you need OpenGL version 2.1 or greater, but I'm not sure.

**Comment by nugenta** [comment]
I did the uninstall/reinstall above, and initially got this error, which made me think vtk didn't install properly:

(mne) [nugenta@felix Desktop]$ python -ic "from mayavi import mlab; mlab.test_plot3d()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/nugenta/conda/envs/mne/lib/python3.6/site-packages/mayavi/mlab.py", line 16, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "/data/nugenta/conda/envs/mne/lib/python3.6/site-packages/mayavi/tools/camera.py", line 24, in <module>
    from .engine_manager import get_engine
  File "/data/nugenta/conda/envs/mne/lib/python3.6/site-packages/mayavi/tools/engine_manager.py", line 14, in <module>
    from mayavi.core.engine import Engine
  File "/data/nugenta/conda/envs/mne/lib/python3.6/site-packages/mayavi/core/engine.py", line 27, in <module>
    from tvtk.common import is_old_pipeline
  File "/data/nugenta/conda/envs/mne/lib/python3.6/site-packages/tvtk/common.py", line 13, in <module>
    vtk_major_version = vtk.vtkVersion.GetVTKMajorVersion()
AttributeError: module 'vtk' has no attribute 'vtkVersion'

So, I uninstalled vtk and re-installed, and got the same vtkShader error, this time using the mlab test script. The error was more voluminous, and also contained this:
 
ERROR: In /work/standalone-x64-build/VTK-source/Rendering/OpenGL2/vtkShaderProgram.cxx, line 446
vtkShaderProgram (0x55c121894880): 0:31(12): error: extension `GL_EXT_gpu_shader4' unsupported in fragment shader

And here's the glxinfo output:

(mne) [nugenta@felix Desktop]$ glxinfo |grep -i version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL version string: 2.1 Mesa 17.2.3
OpenGL shading language version string: 1.30

**Comment by agramfort** [comment]
can you share the full procedure you used on a fresh conda env?

**Comment by nugenta** [comment]
$ conda clean --all   (just for good measure)
$ curl -O https://raw.githubusercontent.com/mne-tools/mne-python/master/environment.yml
$ conda env create -f environment.yml

This gives the following errors:  
twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
mkl-random 1.0.1 requires cython, which is not installed.
mkl-fft 1.0.4 requires cython, which is not installed.

If I execute this:
$ python -ic "from mayavi import mlab; mlab.test_plot3d()" 

The mayavi window pops up, but I get these errors, plus code blocks printed:

ERROR: In /work/standalone-x64-build/VTK-source/Rendering/OpenGL2/vtkShaderProgram.cxx, line 446
vtkShaderProgram (0x55c198066af0): 0:31(12): error: extension `GL_EXT_gpu_shader4' unsupported in fragment shader
ERROR: In /work/standalone-x64-build/VTK-source/Rendering/OpenGL2/vtkShaderProgram.cxx, line 430
vtkShaderProgram (0x55c198066af0): 1: #version 120

I tried taking care of the dependency warnings:

$ conda install cython
$ pip install PyHamcrest

I can see that there are two versions of vtk installed:

$ conda list | grep vtk
vtk                       8.1.1                     <pip>
vtk                       8.1.0           py36h9686630_201  

So I followed Eric's instructions:

$ pip uninstall mayavi
$ conda remove vtk
$ pip install --upgrade mayavi

But then I get this error:
$ python -ic "from mayavi import mlab; mlab.test_plot3d()"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/nugenta/conda/envs/mne/lib/python3.6/site-packages/mayavi/mlab.py", line 16, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "/data/nugenta/conda/envs/mne/lib/python3.6/site-packages/mayavi/tools/camera.py", line 24, in <module>
    from .engine_manager import get_engine
  File "/data/nugenta/conda/envs/mne/lib/python3.6/site-packages/mayavi/tools/engine_manager.py", line 14, in <module>
    from mayavi.core.engine import Engine
  File "/data/nugenta/conda/envs/mne/lib/python3.6/site-packages/mayavi/core/engine.py", line 27, in <module>
    from tvtk.common import is_old_pipeline
  File "/data/nugenta/conda/envs/mne/lib/python3.6/site-packages/tvtk/common.py", line 13, in <module>
    vtk_major_version = vtk.vtkVersion.GetVTKMajorVersion()
AttributeError: module 'vtk' has no attribute 'vtkVersion'

That seems to be a vtk installation error, so I do this:

$ pip uninstall vtk
$ pip install vtk

Which gets me back to the original errors with vtkShaderProgram.cxx and GL_EXT_gpu_shader4.
(mne) [nugenta@felix nugenta]$ glxinfo |grep version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL version string: 2.1 Mesa 17.2.3
OpenGL shading language version string: 1.30

This is really out of my wheelhouse, but my cursory internet search makes me think that my version of Mesa should support OpenGL 3.2, but the version listed is only 2.1.

**Comment by larsoner** [comment]
> This is really out of my wheelhouse, but my cursory internet search makes me think that my version of Mesa should support OpenGL 3.2, but the version listed is only 2.1.

All of the installation warnings seem non-critical to me. I agree that the problem seems to be the OpenGL configuration not being sufficient to support 3D rendering. Unfortunately updating Mesa to a newer version manually is a pain. So I'm not sure what the path forward is :( FWIW Ubuntu 18.04 LTS does have sufficiently modern OpenGL support through Mesa I think, if a system upgrade is on your todo list sometime anyway.

> https://raw.githubusercontent.com/mne-tools/mne-python/master/environment.yml contains a lot of unrelated packages

You could argue `spyder` and `ipython` are not necessary but for newcomers they really help get them up and running. Everything else seems to be something that we or our dependencies do use (though some of them are not configured properly to pull in dependencies themselves, so we need to manually list them). So I'm not sure what we should eliminate.

**Comment by larsoner** [comment]
> my cursory internet search makes me think that my version of Mesa should support OpenGL 3.2, but the version listed is only 2.1.

It depends on what driver you are using for rendering. I assume it's software rasterization (swr), which looks like it should have 3.0 support:

https://github.com/mesa3d/mesa/blob/17.2/docs/features.txt

Not sure why yours does not show it.

**Comment by nugenta** [comment]
OMG the solution was shockingly simple:

$ export MESA_GL_VERSION_OVERRIDE=3.3

There are still rendering issues, though, although I suspect there's not much to be done about them.  Not all the points (including the fiducial points) show up all the time. But it's not throwing any errors. If you view the nasion from the side, you can see the fiducial point.  But when you move the image to look at it head on, it disappears. Likewise for the fiducials by the ears. Do you think that's just a consequence of using software graphics rendering? Although it's odd the python2.7 implementation works better.

**Comment by larsoner** [comment]
Someone else reported the same issue so it's systemic somehow.

What's your sys_info?

Thanks for iterating on this with us

**Comment by nugenta** [comment]
{'commit_hash': 'dd83a2163',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/spin1/users/nugenta/conda/envs/mne/lib/python3.6/site-packages/IPython',
 'ipython_version': '6.5.0',
 'os_name': 'posix',
 'platform': 'Linux-3.10.0-862.9.1.el7.x86_64-x86_64-with-centos-7.5.1804-Core',
 'sys_executable': '/data/nugenta/conda/envs/mne/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) \n'
                '[GCC 7.2.0]'}

**Comment by larsoner** [comment]
I meant `mne.sys_info()`, but I'm also curious how you got this output :)

**Comment by nugenta** [comment]
Also, because you asked about the renderer, I'm using llvmpipe.
I tried changing that; swr doesn't render the fiducials at all, and softpipe is just horrifically slow.

**Comment by nugenta** [comment]
Ha! I wasn't sure what you wanted, so I just googled sys_info, and got this:
IPython.utils.sysinfo.sys_info()

But here's what you asked for:
>>> mne.sys_info()
Platform:      Linux-3.10.0-862.9.1.el7.x86_64-x86_64-with-centos-7.5.1804-Core
Python:        3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51)  [GCC 7.2.0]
Executable:    /data/nugenta/conda/envs/mne/bin/python
CPU:           x86_64: 120 cores
Memory:        1007.6 GB

mne:           0.16.2
numpy:         1.15.0 {blas=mkl_rt, lapack=mkl_rt}
scipy:         1.1.0
matplotlib:    2.2.2 {backend=Qt5Agg}

sklearn:       0.19.1
nibabel:       2.3.0
mayavi:        4.6.1 {qt_api=pyqt5}
pycuda:        Not found
skcuda:        Not found
pandas:        0.23.4

**Comment by larsoner** [comment]
@nugenta thanks.

I assume you are "just" fighting #5375 now (there is a workaround in there that might help). If so I'll retitle this to mention MESA tweaks somewhere in advanced install docs, and we can take care of the fiducials problem in #5375.

**Comment by larsoner** [comment]
@nugenta can you give me the output of `$ glxinfo | grep version` when you get a chance? I want to see if there is some consistency between systems experiencing the "disappearing fiducials" problem. In the meantime has the workaround fro #5375 worked for you?

**Comment by larsoner** [comment]
Never mind @nugenta you already pasted that above! You are on `Mesa`. I'll check that with the other report.

**Comment by nugenta** [comment]
Yup, the workaround for #5375 worked - but it's quite sluggish. That's not terribly surprising for software rendering, except that the python2 implementation performs significantly better viewed remotely. It's not too much trouble to switch between conda environments, though.
