### ISSUE TITLE
ica.plot_properties only plots 3 epochs with raw input?

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#5401]
Try:

```
import mne
path_eeglab = mne.datasets.testing.data_path()

fname = path_eeglab + '/EEGLAB/test_raw.set'
montage = path_eeglab + "/EEGLAB/test_chans.locs"

event_id = {"rt": 1, "square": 2}
raw = mne.io.read_raw_eeglab(fname, event_id=event_id, preload=True, montage=montage)
ica = mne.preprocessing.ICA(20, random_state=0).fit(raw.filter(1, None))
ica.plot_properties(raw, 0)
```

Gives:

<img width="491" alt="unknown-191" src="https://user-images.githubusercontent.com/4321826/43680492-68ce6a04-983c-11e8-9b40-79552bc99cb3.png">

I.e., for some reason, only 3 "epochs" are plotted.

@mmagnuski

**Comment by agramfort** [comment]
I can replicate the pb.

**Comment by mmagnuski** [comment]
I can replicate the problem too.
But it gets even weirder for me: each time I restart the notebook I get different axes filled with spectrum, epoch variance, etc. Below three examples:  

<img width="300" alt="01" src="https://user-images.githubusercontent.com/8452354/43684373-30716c0c-989f-11e8-9a84-ba87977cce6f.PNG">
<img width="300" alt="02" src="https://user-images.githubusercontent.com/8452354/43684374-330391d4-989f-11e8-82aa-9ce1f770ffef.PNG">
<img width="300" alt="03" src="https://user-images.githubusercontent.com/8452354/43684378-362171ce-989f-11e8-92e6-dd4e1cff2476.PNG">

I currently have no other explanation than that your code is haunted...

**Comment by agramfort** [comment]
I would try with an older matplotlib so see if we broke it or they did.

**Comment by jona-sassenhagen** [comment]
Hm ... The axes are created here, and later unpacked order:

```
def _create_properties_layout(figsize=None):
    """Create main figure and axes layout used by plot_ica_properties."""
    import matplotlib.pyplot as plt
    if figsize is None:
        figsize = [7., 6.]
    fig = plt.figure(figsize=figsize, facecolor=[0.95] * 3)

    axes_params = {'topomap': [0.08, 0.5, 0.3, 0.45],
                   'image': [0.5, 0.6, 0.45, 0.35],
                   'erp': [0.5, 0.5, 0.45, 0.1],
                   'spectrum': [0.08, 0.1, 0.32, 0.3],
                   'variance': [0.5, 0.1, 0.45, 0.25]}
    axes = [fig.add_axes(pos, label=name) for name, pos in axes_params.items()]

    return fig, axes
```

Dict order should be fixed in Py3.6+, but is not guaranteed otherwise right?

Which would however not explain why it does not work on my Py3.6 either.

**Comment by jona-sassenhagen** [comment]
(Also I think I wrote that code :()

**Comment by jona-sassenhagen** [comment]
Oh! I think I got it then.
