### ISSUE TITLE
realtime/client.py : There no methed named stop() in threading instance

### ISSUE THREAD

**Issue by ChaiGuangJie** [mne-tools/mne-python#5449]
def stop_receive_thread(self, stop_measurement=False):
        """Stop the receive thread.

        Parameters
        ----------
        stop_measurement : bool
            Also stop the measurement.
        """
        if self._recv_thread is not None:
            self._recv_thread.stop()
            self._recv_thread = None

        if stop_measurement:
            self.stop_measurement()

**Comment by jasmainak** [comment]
@ChaiGuangJie can you be more explicit what's the issue and how to reproduce?

**Comment by ChaiGuangJie** [comment]
self._recv_thread cannot stop by calling the method stop() @jasmainak

**Comment by jasmainak** [comment]
pull request welcome to remove the line in question
