### ISSUE TITLE
ENH: interactive volume viz followup/todos

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-python#5457]
I'm raising a new issue to keep track of things that need to be done but are not part of https://github.com/mne-tools/mne-python/pull/5329

- [ ] Allow plotting surface data in volume plotters using the cortical ribbon (see closed glass brain PR)
- [ ] Visualization of vector fields on top of functional maps (after @britta-wstnr implements the computation aspect)
- [ ] Ability to save an animation of the functional map
- [ ] Getting a max: temporal / spatial (globally or within x mm of mouse click) / spatiotemporal
- [x] be able to use arrows to move in time like we have eg in mne_analyze (right arrow : move one sample forward, shift+right arrow move by 10ms and the reverse for left arrow)
- [x] I think we should have an entry in the visualization section in http://martinos.org/mne/stable/documentation.html on source estimates. Basically showing every option to visualize source estimation results : on surface, on volume, dipoles.
- [x] Add more divergent colormaps in `_limits_to_control_points`, with proper `transparent=True` support (set middle to fully transparent, fmin->fmid linear from 0->1 as `mne` colormap already does) and nonlinear scaling of colormaps (which `mne` already does during its construction). (#5522)

cc @agramfort @sarangnemo

**Comment by agramfort** [comment]
great summary.

I think you can start with 1 starting from current master. Then add to it
the interactive volume viz
when merged.

**Comment by larsoner** [comment]
I added a point that these plotters can be extended to work with volume data using the ribbon definition, hopefully easy to copy paste over from my closed glass brain PR

**Comment by larsoner** [comment]
Argh I mean with surface data

**Comment by mmagnuski** [comment]
I've ticked off viz tutorial cause it's done. :)

**Comment by larsoner** [comment]
@jasmainak marking this for the sprint in case you want to work on it

**Comment by jasmainak** [comment]
okay, perfect!

**Comment by larsoner** [comment]
I think most of this is YAGNI at this point and/or can be obtained from the 3D viz code so I'll close. But let's reopen if people are still enthusiastic about some of these features
