### ISSUE TITLE
Adding KIT-160 system

### ISSUE THREAD

**Issue by EstiBlancoElorrieta** [mne-tools/mne-python#5469]
Hi,

I am trying to import MEG data from a 160 channel KIT system, but it seems like currently only 157 and 208 channel KIT systems are supported (https://martinos.org/mne/dev/manual/io.html). 

Can someone help me with this? @teonbrooks @christianbrodbeck. I am attaching the sensor locations. 
[AdultMEG-channel.txt](https://github.com/mne-tools/mne-python/files/2319261/AdultMEG-channel.txt)

Thanks a lot for your help,
Esti

**Comment by teonbrooks** [comment]
hi @EstiBlancoElorrieta. do you have a small sample of the sqd file for this system. we should be able to read the file directly to extract channel information and we can use this list to check against it to make sure it's being done properly. then we could modify the code to support this 160 KIT system

**Comment by EstiBlancoElorrieta** [comment]
Sounds good! Here's a link to a sample .sqd from this system (sorry, I couldn't upload it to github):

https://drive.google.com/file/d/0B4do8y7JvWOAZC01VUFzSlgtaTBvVDRkZWlkbi1ZaUVXcVZr/view?usp=sharing

**Comment by larsoner** [comment]
This already works on latest `master`:
```
>>> import mne
>>> raw = mne.io.read_raw_kit('2784_AG_ME155_2017_11_17_test.con')
>>> raw
<RawKIT  |  2784_AG_ME155_2017_11_17_test.con, n_channels x n_times : 257 x 9000 (9.0 sec), ~476 kB, data not loaded>
```
Can you give it a shot?

It was probably fixed by #5310 / #5314

**Comment by teonbrooks** [comment]
@EstiBlancoElorrieta is this file supposed to only have 160 channels?

**Comment by JD-Zhu** [comment]
Hi @teonbrooks and @larsoner 

The sample recording Esti uploaded above has 256 channels (160-channel gradiometers + 96-channel extra analog inputs).

I can read in .con files recorded from this system and do the preprocessing steps without a problem, but I get a "Not Implemented" error when using the plot_joint command (please see code and screenshot below):
```
clf = make_pipeline(StandardScaler(), LinearModel(LogisticRegression()))
time_decod = SlidingEstimator(clf, n_jobs=1, scoring='roc_auc')
time_decod.fit(X, y)

coef = get_coef(time_decod, 'patterns_', inverse_transform=True)
evoked = mne.EvokedArray(coef, epochs.info, tmin=epochs.times[0])
joint_kwargs = dict(ts_args=dict(time_unit='s'),
                    topomap_args=dict(time_unit='s'))
evoked.plot_joint(times=np.arange(0., .500, .100), title='patterns',
                  **joint_kwargs)
```
![mne_error](https://user-images.githubusercontent.com/38392787/44826231-58fb6900-ac51-11e8-8b26-7788dea7664f.png)

Any help would be greatly appreciated!

Thanks,
Judy

**Comment by teonbrooks** [comment]
@larsoner is there a way to compute a layout on the fly?

**Comment by larsoner** [comment]
Yes but it's best if we use whatever method was used for creating the other layouts. We actually already have a KIT-160.lay, it might be worth first looking to see if that one is correct for this site as well

**Comment by larsoner** [comment]
Actually this layout was added in #5314 so it probably is the correct one. 

@JD-Zhu are you on latest master? It should work there.

**Comment by JD-Zhu** [comment]
Thanks so much @teonbrooks @larsoner ! It's all working for me now.

I was using the latest stable release rather than the development master (sorry I didn't know the difference as I am new to python and mne). I've updated to latest master now and everything is working.

Thanks again for your help!

**Comment by teonbrooks** [comment]
awesome! glad to hear that it's working for you @JD-Zhu and @EstiBlancoElorrieta :)
