### ISSUE TITLE
Fit two or more dipoles

### ISSUE THREAD

**Issue by niraknitsew** [mne-tools/mne-python#5490]
Hi!
I'd like to be able to fit two or more dipoles. I work with epileptic spikes, and sometimes patients have simultaneously occurring spikes with different sources. Fitting one dipole results in this dipole being centered in between the two epileptic sources - not so optimal I'm afraid. It would be best if one dipole could be fitted for each source of epileptic activity.

Best,
Karin

**Comment by agramfort** [comment]
how would you proceed? fit them sequentially by hand picking time
points? fitting multiple ones simultaneously is computationally more
challenging and for me brings you closer to sparse distributed inverse
methods.

**Comment by niraknitsew** [comment]
I'll try and use only a part of the sensors (here one hemisphere at the time), make a new forward model with only these ones and fit one dipole for each hemisphere.

**Comment by niraknitsew** [comment]
I'll try to hand pick time points, but I'm not sure it will work since none one of the two foci are completely silent at any point (when there is activity in the contralateral one).

I got the advice to model only a subset of sensors (here eg one hemisphere at the time) but that doesn't seem to be possible?

Thanks for all the help

**Comment by larsoner** [comment]
You can use `evoked_left = evoked.copy().pick_channels(left_hemi_channels)` once you make a list of the `left_hemi_channels` you want to use to subselect channels, then fit

**Comment by niraknitsew** [comment]
I tried to fit only a subset of sensors but the dipole doesn't change location - even if the dipole is fitted to a region quit far from the selected sensors.

**Comment by agramfort** [comment]
how does the topography look like?

>

**Comment by niraknitsew** [comment]
Here's one example. The dipole, even though I've fitted only one hemisphere, ends up in the contralateral hemisphere. 


![sp6_topo](https://user-images.githubusercontent.com/35346888/45284854-d2147f00-b4e1-11e8-9f7f-8f1eae48b065.png)

**Comment by agramfort** [comment]
you should get a clear dipole around the left inferior frontal cortex with
such a topo.

can you show what you get with plot_alignment ? see
https://martinos.org/mne/dev/auto_tutorials/plot_source_alignment.html#sphx-glr-auto-tutorials-plot-source-alignment-py

**Comment by niraknitsew** [comment]
![plot_align](https://user-images.githubusercontent.com/35346888/45288283-99c56e80-b4ea-11e8-8e66-c5837c0bec05.png)

(I've used single layer BEM, hence the brain)

**Comment by agramfort** [comment]
looks great. Did you try using only a selection of left side sensors?

**Comment by niraknitsew** [comment]
This an example of a topo-plot + dipole fit of sensors only from the right hemisphere 
![fig](https://user-images.githubusercontent.com/35346888/45412989-54cf4280-b678-11e8-99ee-cc03a520c1af.png)

**Comment by agramfort** [comment]
that's really weird ...

**Comment by niraknitsew** [comment]
My personal guess is this:
Almost all of this patient's spikes move about (more or less). This ought to result in a number of sources, thus violating the assumption that the activity can be modeled by only one dipole?
 I tried to pick dipoles time point by time point and it works for some spikes but not for all. However maybe this time restriction results in a dipole corresponding to a local minimum quite "far" from the global minimum?
Thus maybe one can simply conclude that dipole fit is not the model of choice here?

**Comment by agramfort** [comment]
what you say makes sense. I cannot propose more

**Comment by larsoner** [comment]
Closing as this does not seem to require action at the MNE-Python end
