### ISSUE TITLE
[BUG] Issue with EEGLAB filenames

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-python#5503]
When reading a raw file into an [`mne.io.Raw`](https://martinos.org/mne/stable/generated/mne.io.Raw.html) object, we usually get an attribute "filenames", which points to the datafile.

For formats that have just a single file, such as `.cnt`, the `.filenames` attribute will be a tuple pointing to that single file:
```python
import mne
from mne.datasets import testing

f = op.join(testing.data_path(), 'CNT', 'scan41_short.cnt')
raw = mne.io.read_raw_cnt(f, None)
raw.filenames
>>>('/home/stefanappelhoff/mne_data/MNE-testing-data/CNT/scan41_short.cnt',)
```

For formats that have multiple files, such as BrainVision, `.filenames` will point to the data file.In the case of BrainVision this is to the `.eeg` file. (Actually, this might be considered a bit weird, as one could also expect the accompanying `.vmrk` and `.vhdr` files in the `.filenames` tuple. Is that a bug?)

Now the issue:

EEGLAB's `.set` format is basically a MATLAB structure which contains a field called `data`. This field can either be a string, pointing to a binary data file `.fdt`, or it can contain the data as an array already (no `.fdt` file necessary).

As expected, when we have `.set` and an accompanying `.fdt`, we get the following:
```python
f = op.join(testing.data_path(), 'EEGLAB', 'test_raw.set')
raw = mne.io.read_raw_eeglab(f)
raw.filenames
>>>('/home/stefanappelhoff/mne_data/MNE-testing-data/EEGLAB/test_raw.fdt',)
```

The bug arises when no `.fdt` is present and we thus have a "standalone" `.set` file:
```python
f = op.join(testing.data_path(), 'EEGLAB', 'test_raw_onefile.set')
raw = mne.io.read_raw_eeglab(f)
raw.filenames
>>>(None,)
```

Here, we get `(None,)`, while we would expect `('/home/stefanappelhoff/mne_data/MNE-testing-data/EEGLAB/test_raw_onefile.set',)`

------------
Next to the obvious bug it'd be great to get a comment on why `.filenames` only ever lists a tuple of length 1, even for multifile formats.

**Comment by larsoner** [comment]
> Actually, this might be considered a bit weird, as one could also expect the accompanying .vmrk and .vhdr files in the .filenames tuple. Is that a bug?

We have not been strict about this, but the idea roughly is that doing `raw = read_raw_*` will have `raw.filenames` give the name of *one* file or directory that contains the data. For example in CTF you load a directory with many files, but `filenames` contains the `res4` data filename:
```
>>> raw = mne.io.read_raw_ctf(mne.datasets.testing.data_path() + '/CTF/catch-alp-good-f.ds')
>>> raw.filenames
('/home/larsoner/python/MNE-testing-data/CTF/catch-alp-good-f.ds/catch-alp-good-f.meg4',)
```
Then when you concat:
```
>>> raws = mne.concatenate_raws([raw.copy(), raw.copy()])
>>> raws.filenames
('/home/larsoner/python/MNE-testing-data/CTF/catch-alp-good-f.ds/catch-alp-good-f.meg4',
 '/home/larsoner/python/MNE-testing-data/CTF/catch-alp-good-f.ds/catch-alp-good-f.meg4')
```
So for `EEGLAB` it should probably not be `None` but rather the `.set` filename.
