### ISSUE TITLE
Make raw.annotations a property with setter decorator

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#5512]
I don't know when this changed, but now there is a `set_annotations` method that needs to be called to set annotations. A more Pythonic way would be to make `raw.annotations` a property with associated setter using the `@property` and `@annotations.setter` decorators.

If people agree, I can create a PR with the changes.

**Comment by cbrnr** [comment]
I like properties exactly because of this feature. Especially if it is just a simple check if all values are within bounds, what would be so bad about getting an exception when setting `raw.annotations = my_annotations`?

**Comment by agramfort** [comment]
yes I asked for the set_annotations to be explicit that calling the method does something to the assign annotations. It's not just checking that it's valid. It's less magic as it is now.
