### ISSUE TITLE
Generating volume source estimates for a specified frequency band

### ISSUE THREAD

**Issue by WilliamCollishaw** [mne-tools/mne-python#5516]
I am creating volume source estimates using mne.minimum_norm.apply_inverse_epochs and morphing them to fsaverage using the new SourceMorph class. I was wondering if it was possible only generate volume source estimates for for a specified frequency band?

**Comment by agramfort** [comment]
what do you mean an stc for volume a specified frequency band?

you filter the data before solving the inverse problem?

**Comment by larsoner** [comment]
Closing due to non-response, might be better for Discourse nowadays anyway
