### ISSUE TITLE
add_annotation shows only one label

### ISSUE THREAD

**Issue by dnacombo** [mne-tools/mne-python#5529]
On latest version, running this

```Python
from surfer import Brain

import mne

subjects_dir = mne.datasets.sample.data_path() + '/subjects'
mne.datasets.fetch_hcp_mmp_parcellation(subjects_dir=subjects_dir,
                                        verbose=True)
labels = mne.read_labels_from_annot(
    'fsaverage', 'HCPMMP1', 'lh', subjects_dir=subjects_dir)

brain = Brain('fsaverage', 'lh', 'inflated', subjects_dir=subjects_dir,
              cortex='low_contrast', background='white', size=(800, 600))
brain.add_annotation('aparc.a2009s')
```
shows only one label on the medial wall.

Perhaps it has something to do with the fact that the example below (almost same code) suddenly changed in the current 0.17dev version. On my computer, it shows this white brain with one red label.
http://mne-tools.github.io/dev/auto_examples/visualization/plot_parcellation.html
But I guess it should show this:
https://martinos.org/mne/dev/auto_examples/visualization/plot_parcellation.html

**Comment by agramfort** [comment]
FYI it's broken for me too.

**Comment by larsoner** [comment]
@dnacombo do you have time to get bisect, or at least check what the last tagged version that works is?

**Comment by dnacombo** [comment]
Quick test: white plot_parcellation remains on my install with tagged versions back to 0.14.
0.13 crashes because fetch_hcp_mmp_parcellation does not exist.
But online examples:
http://mne-tools.github.io/0.15/auto_examples/visualization/plot_parcellation.html
is fine
http://mne-tools.github.io/stable/auto_examples/visualization/plot_parcellation.html
is not.
Something odd in the environment, I guess... I can help further but need directions.

**Comment by larsoner** [comment]
I mean PySurfer versions not MNE actually. The MNE version shouldn't change
the add_annotation behavior (beyond making the annot dataset available) as
add_annotation is a PySurfer function.

>

**Comment by agramfort** [comment]
FYI to make pysurfer plot_parcellation.py I had work with a new env that I
one still
use currently. So it means that maybe updating the env will fix the pb?

**Comment by dnacombo** [comment]
Just tried all sorts of variants of `conda update env` without a chance.
`pip install pysurfer` or update or anything won't work.
What should I do?

**Comment by larsoner** [comment]
Can you see if it's a `nibabel` problem:

https://github.com/nipy/PySurfer/issues/250#issuecomment-423144386

Let's move discussion over there
