### ISSUE TITLE
raw.plot does not work on my data

### ISSUE THREAD

**Issue by erfpak7** [mne-tools/mne-python#5539]
I've faced a problem regarding the raw.plot().
I have a .csv file with 7782 X 21 (n_times, n_channel) structure - myData. I've used mne.io.RawArray function to convert my data to a raw data format readable by mne data structure. 
<raw = mne.io.RawArray(myData, info)>
When I am using the raw.plot() function, it does not show me what it's supposed to show as channel activities, although eeglab could show me all the activities including noises (plz take a look at the following pictures). I was wondering where does the problem come from and how I can tackle it? 
Besides, it is not an **interactive** plot. How can I make it interactive?

<img width="477" alt="screen shot 2018-09-19 at 8 20 11 pm" src="https://user-images.githubusercontent.com/16671325/45789100-03145280-bc4c-11e8-86e9-f4e4c268fd5a.png">
<img width="437" alt="screen shot 2018-09-19 at 8 19 51 pm" src="https://user-images.githubusercontent.com/16671325/45789101-03145280-bc4c-11e8-96ff-c7b33dd1dfcd.png">
<img width="460" alt="screen shot 2018-09-19 at 8 19 32 pm" src="https://user-images.githubusercontent.com/16671325/45789103-03ace900-bc4c-11e8-8d19-e11630f2c0ba.png">

**Comment by larsoner** [comment]
You need to change the scaling of the plot or your data. Probably you have data in units of uV and MNE expects data in V

**Comment by erfanpak** [comment]
> You need to change the scaling of the plot or your data. Probably you have data in units of uV and MNE expects data in V

Thanks for the quick response. It is not an **interactive** plot. How can I make it interactive?

**Comment by agramfort** [comment]
it's interactive if you don't use %matplotlib inline
in the notebook. You can use "%matplotlib qt" or try
"%matplotlib notebook"

**Comment by mmagnuski** [comment]
I'd recommend `%matplotlib` or `%matplotlib qt`, `%matplotlib notebook` doesn't work so well on my machine - it seems to be slower and usually the default figure size does not fit in the output window of the notebook so the navigation is inconvenient.

**Comment by massich** [comment]
Closing as solved, @erfpak7 feel free to reopen if you still have troubles

**Comment by shivam-199** [comment]
It might help input the correct type of data into the array info. For my case, I was analyzing LFP data and set the type as "seeg" (could be wrong). But by doing this, I could get the data to plot without scaling it.

`lfp_info = mne.create_info(nChan, ch_types=["seeg"] * nChan, sfreq=sampling_freq)`
