### ISSUE TITLE
epoch.plot(spatial_colors = True)

### ISSUE THREAD

**Issue by Sonia2016** [mne-tools/mne-python#5551]
Hey again,
I am using epoch.plot() function and I want to have one of the channels be colorful and the rest be black. I've used `spatial_colors = True` which assign the color to all the channel. How can I have a control on which channel has which color? (e.g. I need one channel color red and the rest be black)
Thanks!

**Comment by agramfort** [comment]
then don't use spatial colors and mark this channel as bad.

see first plot in
https://martinos.org/mne/stable/auto_tutorials/plot_visualize_evoked.html
