### ISSUE TITLE
Unused variables in test_brainvision.py

### ISSUE THREAD

**Issue by massich** [mne-tools/mne-python#5571]
https://github.com/mne-tools/mne-python/blob/fd23ba8bfc1f11dd046abcfa89868f7dd8569d76/mne/io/brainvision/tests/test_brainvision.py#L37

https://github.com/mne-tools/mne-python/blob/fd23ba8bfc1f11dd046abcfa89868f7dd8569d76/mne/io/brainvision/tests/test_brainvision.py#L41

https://github.com/mne-tools/mne-python/blob/fd23ba8bfc1f11dd046abcfa89868f7dd8569d76/mne/io/brainvision/tests/test_brainvision.py#L114

**Comment by agramfort** [comment]
that's weird. Use git blame to understand what happened

**Comment by massich** [comment]
https://github.com/mne-tools/mne-python/pull/4524/files#r222033158
