### ISSUE TITLE
"dateutil" package requirement issue

### ISSUE THREAD

**Issue by makkostya** [mne-tools/mne-python#5584]
1. Package "dateutil" is required to install mne but is not in requirements.txt

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-1-d70f97b8aea9> in <module>
> ----> 1 import mne
> 
> /home/kmaksyme/dev/mne-python/mne/__init__.py in <module>
>      23                     get_config, get_config_path, set_cache_dir,
>      24                     set_memmap_min_size, grand_average, sys_info, open_docs)
> ---> 25 from .io.pick import (pick_types, pick_channels,
>      26                       pick_channels_regexp, pick_channels_forward,
>      27                       pick_types_forward, pick_channels_cov,
> 
> /home/kmaksyme/dev/mne-python/mne/io/__init__.py in <module>
>      23 from . import constants
>      24 from . import edf
> ---> 25 from . import egi
>      26 from . import fiff
>      27 from . import kit
> 
> /home/kmaksyme/dev/mne-python/mne/io/egi/__init__.py in <module>
>       3 # Author: Denis A. Engemann <denis.engemann@gmail.com>
>       4 
> ----> 5 from .egi import read_raw_egi
> 
> /home/kmaksyme/dev/mne-python/mne/io/egi/egi.py in <module>
>       9 import numpy as np
>      10 
> ---> 11 from .egimff import _read_raw_egi_mff
>      12 from .events import _combine_triggers
>      13 from ..base import BaseRaw, _check_update_montage
> 
> /home/kmaksyme/dev/mne-python/mne/io/egi/egimff.py in <module>
>       5 import time
>       6 from xml.dom.minidom import parse
> ----> 7 import dateutil.parser
>       8 
>       9 import numpy as np
> 
> ModuleNotFoundError: No module named 'dateutil'

2. Package "dateutil" requires  Python 2 while:

> Note that MNE-Python 0.17 will be the last release to support Python 2. From MNE-Python 0.18, only Python 3 will be supported.

**Comment by agramfort** [comment]
I have no idea how this slipped through the cracks.

how about using datetime to avoid this issue?

**Comment by larsoner** [comment]
It looks like the dep is from `xml.dom.minidom.parse` so we'd actually need to replace that

**Comment by agramfort** [comment]
+1

**Comment by larsoner** [comment]
Oh no I'm wrong, it is just `dateutil`. Yes we should just try to replace it
