### ISSUE TITLE
How to use mne-analyze

### ISSUE THREAD

**Issue by vivekosdd** [mne-tools/mne-python#5593]
How to use mne-analyze gui based. Does it require to install mne-C or it works with mne python also.
Also to create a forward solution we need transformation matrix, can anyone tell me how to generate the file from mri structure file in .nii format.

**Comment by vivekosdd** [comment]
Yeah I read that. But I couldn't figure out how to launch the gui of mne_analyze.

**Comment by agramfort** [comment]
mne_analyze is a C program.

to get the coregistration you need to use in Python the "mne coreg" tool.

See doc in https://martinos.org/mne/stable/auto_tutorials/plot_forward.html?highlight=coregistration
