### ISSUE TITLE
Negative meas_date in gdf2 example

### ISSUE THREAD

**Issue by massich** [mne-tools/mne-python#5604]
I was not expecting 'meas_date' to be negative. Is this a bug? or that this example indeed has negative meas_date?

#### Steps and/or code to reproduce
```py
import os.path as op
from mne.io import read_raw_edf
from mne.annotations import _handle_meas_date
from mne.datasets import testing

data_path = testing.data_path(download=False)
gdf2_path = op.join(data_path, 'GDF', 'test_gdf_2.20')

raw = read_raw_edf(gdf2_path + '.gdf', eog=None, misc=None, preload=True,
                    stim_channel='STATUS')
assert _handle_meas_date(raw.info['meas_date']) > 0
```

**Comment by agramfort** [comment]
pb is here:

https://github.com/mne-tools/mne-python/blob/master/mne/io/edf/edf.py#L899

if date is not present we use:

date = datetime.datetime(1, 1, 1)

and then we use:

meas_date=(calendar.timegm(date.utctimetuple()), 0)

which leads to a negative meas_date....

basically we can fix this as it's negative as we fixed a bad date by default.
