### ISSUE TITLE
plot_compare_evokeds is missing the channel location plot

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#5621]
for a few workshop attendants.

**Comment by jasmainak** [comment]
I think it would be great to have a test accompany the fix. Thanks @jona-sassenhagen !

**Comment by jona-sassenhagen** [comment]
I'm not sure how to test this. The problem is that the figure looks different. We don't test for that anywhere.

**Comment by jasmainak** [comment]
yeah never mind then. I approved the PR ...
