### ISSUE TITLE
open new issue from the code no longer works

### ISSUE THREAD

**Issue by massich** [mne-tools/mne-python#5623]
Normally issues can be open from the code. 

i.e: get a line in mne-tools/mne-openmeeg, clik and open an issue:

![image](https://user-images.githubusercontent.com/7044835/47092409-3932fb00-d227-11e8-9285-3d2ddc13f035.png)
![image](https://user-images.githubusercontent.com/7044835/47092419-3d5f1880-d227-11e8-9b14-74901f123342.png)

However in mne-tools/mne-python,
![image](https://user-images.githubusercontent.com/7044835/47092460-51a31580-d227-11e8-8a67-123636c47f8a.png)
you get to the issue template selection:
![image](https://user-images.githubusercontent.com/7044835/47092502-6384b880-d227-11e8-9ebf-f00d687a2252.png)
and even if you try `Open a regular issue` the issue is empty
![image](https://user-images.githubusercontent.com/7044835/47092526-73040180-d227-11e8-8174-af3e03885a55.png)

Does anyone know how to fix/trace that? 
Also if someone thinks this irrelevant, feel free to close this issue.

**Comment by sappelhoff** [comment]
I have encountered this as well and it's been there ever since we introduced the templates. Would be nice to fix it ... +1

**Comment by larsoner** [comment]
Closing this as an upstream bug. I think we have to live with it until they fix it unless we want to scrap the templates
