### ISSUE TITLE
ENH: Add `overwrite` parameter in epochs.save as in raw.save

### ISSUE THREAD

**Issue by QB3** [mne-tools/mne-python#5627]
#### Describe the problem
* The `save` method of the `raw` object has  parameters   `fname` (string) and `overwrite` (boolean) stating if you want to overwrite a file with the name `fname`.
* However the `save` method from the `epoch` object has no such `overwrite` parameter.
* I would expect the API to behave the same. 

See these two parts of `plot_introduction.py`:

https://github.com/mne-tools/mne-python/blob/9df12aa57dce2a75ba619c90abc6a6547dde9997/tutorials/plot_introduction.py#L156-L157

https://github.com/mne-tools/mne-python/blob/9df12aa57dce2a75ba619c90abc6a6547dde9997/tutorials/plot_introduction.py#L243

and this is the `Epochs.save(...` signature :
https://github.com/mne-tools/mne-python/blob/9df12aa57dce2a75ba619c90abc6a6547dde9997/mne/epochs.py#L1680

#### Describe your solution
It would be good if a  boolean parameter `overwrite` could be added to the method `save` of the `epoch` object to state if you want to overwrite a file or not.

**Comment by larsoner** [comment]
@QB3 can you make a PR to add this option?

**Comment by agramfort** [comment]
PR very welcome indeed !

**Comment by massich** [comment]
@QB3 https://mne-tools.github.io/stable/contributing.html are the instructions in how to contribute, if something is not clear enough. Please open an issue and we'll try to improve our documentation. Thanks a lot.
