### ISSUE TITLE
easy to find mne-c commands download button.

### ISSUE THREAD

**Issue by massich** [mne-tools/mne-python#5630]
The download button of MNE-C commands is kind of hard to find. Maybe we should place a big colorful button somewhere. 

https://github.com/mne-tools/mne-python/blob/master/doc/install_mne_c.rst#L8

see how its rendered so far:
![image](https://user-images.githubusercontent.com/7044835/47208463-22f37f00-d38e-11e8-9ad6-fc9027bfcd1f.png)

**Comment by drammock** [comment]
MNE-C is still behind a login wall.  We can add a bigger button I guess, but it will still go [here](http://www.nmr.mgh.harvard.edu/martinos/userInfo/data/MNE_register/index.php).  @massich given how the MNE-C install page looks now, is this still something you want implemented?

![Screenshot_2019-09-19_14-18-13](https://user-images.githubusercontent.com/1810515/65281903-77483700-dae8-11e9-911e-1f726f1d2f80.png)

**Comment by larsoner** [comment]
It looks clear enough given the new title/org so I'll close, but feel free to reopen if you disagree @massich
