### ISSUE TITLE
Math rendering in snr estimate documentation

### ISSUE THREAD

**Issue by massich** [mne-tools/mne-python#5632]
see this:
https://martinos.org/mne/stable/generated/mne.minimum_norm.estimate_snr.html?highlight=estimate_snr#mne.minimum_norm.estimate_snr

![image](https://user-images.githubusercontent.com/7044835/47219687-c86b1a80-d3af-11e8-80dc-601c65ec8503.png)

The issue has been replicated by @sappelhoff @tjochmann and @larsoner .

@larsoner pointed in gitter that these type of things can come from MathJax. But not this time.

**Comment by larsoner** [comment]
This is fixed in master

http://mne-tools.github.io/dev/generated/mne.minimum_norm.estimate_snr.html#mne.minimum_norm.estimate_snr
