### ISSUE TITLE
DOC Be more accurate for 1-sample Monte Carlo-sampling based tests

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#5636]
We must be careful regarding how we document the one-sample permutation test. What exactly is the null hypothesis?

After some comments from Eric Maris and discussion with @larsoner , it seems we should be really careful so not to lead people into writing false things in their methods sections.

See e.g.

https://mne-tools.github.io/dev/generated/mne.stats.permutation_cluster_1samp_test.html#mne.stats.permutation_cluster_1samp_test

vs.

https://mailman.science.ru.nl/pipermail/fieldtrip/2018-August/012309.html

**Comment by agramfort** [comment]
and we should also clean up / improve all our statistics examples
http://martinos.org/mne/stable/documentation.html#collapse_statistics
some of them have not been touched for years and we have now much better
datasets for educational purposes

**Comment by larsoner** [comment]
> and we should also clean up / improve all our statistics examples

This is more in the scope of #4859
