### ISSUE TITLE
CI badges in readme out of sync

### ISSUE THREAD

**Issue by QB3** [mne-tools/mne-python#5645]
#### Describe the bug

in the github main page (see screenshot) the badges show all the CI failing. 

![image](https://user-images.githubusercontent.com/20907043/47361331-ebf4d480-d6d1-11e8-8d90-6b6b19694ffb.png)

checking if thats the case (by clicking on it) Travis is all green. see this:

![image](https://user-images.githubusercontent.com/20907043/47361266-cec00600-d6d1-11e8-813b-723d72cf8822.png)

It seems to mean that the badges are not synchronized.

#### Expected results
Since the tests are passed I would expect the badges to be green.

#### Actual results
The bagdes are red, and it states "failing".

**Comment by agramfort** [comment]
well our current master is actually broken :(

but the svg badges should point to the master branch as done here:

https://docs.travis-ci.com/user/status-images/

**Comment by larsoner** [comment]
It appears correct see

https://travis-ci.org/mne-tools/mne-python/jobs/444753486

**Comment by agramfort** [comment]
hum :(

but we still should fix the badges to point to master branch or maybe it's
not necessary?

**Comment by larsoner** [comment]
in README.rst:
```
.. |Travis| image:: https://api.travis-ci.org/mne-tools/mne-python.png?branch=master
```
so it should already
