### ISSUE TITLE
[RFC] documentation on how to use github

### ISSUE THREAD

**Issue by QB3** [mne-tools/mne-python#5646]
Based on https://github.com/mne-tools/mne-python/issues/5627#issuecomment-432226676 I start reading https://www.martinos.org/mne/stable/contributing.html but the documentation specific to github: https://www.martinos.org/mne/stable/configure_git.html#using-github  is burried at the end of the doc. 
In found it is not obvious to find, and it could be more easy (especially for newcommers) to put it in a more visible place. 

Apart from that once I founded https://www.martinos.org/mne/stable/configure_git.html#using-github,  the word "trunk" was repeatedly used, and it is not clear to me what it is exactly. I had to go to the document twice to find this:

```In the present document, we refer to the mne-python/master branch, as the trunk.```

I never heard of SBN before going on this page (you can blame my youth). Do you think it might worth the effort to change it to the new github paradigm ?

**Comment by agramfort** [comment]
trunk should be replaced by master (trunk is from svn historical times.)

if you have some spare cycles to rephrase / clarify things it would be much
appreciated

file to edit is :
https://github.com/mne-tools/mne-python/blob/master/doc/configure_git.rst
