### ISSUE TITLE
Latest version of testing data is not downloaded

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#5653]
When I download the testing data via

```
import mne
mne.datasets.testing.data_path(force_update=True, verbose=True)
```

I always get release 0.47, but 0.60 is the latest version. I assume there's something wrong with my setup, but I can't figure out what.

**Comment by agramfort** [comment]
it does not force the redownload? and if you remove the mne-testing-data
folder it downloads fine?

**Comment by cbrnr** [comment]
Yes. It always fetches 0.47.

**Comment by agramfort** [comment]
no idea what's going on on your machine. On mine it works:

In [1]: %paste
import mne
mne.datasets.testing.data_path(force_update=True, verbose=True)

## -- End pasted text --
Downloading archive mne-testing-data-0.60.tar.gz to /Users/alex/mne_data
Downloading
https://codeload.github.com/mne-tools/mne-testing-data/tar.gz/0.60 (960.5
MB)

see what you have in cat ${HOME}/.mne/mne-python.json

**Comment by cbrnr** [comment]
Found it: the current release 0.16.2 still uses 0.47, I wasn't using the master branch. Let's not forget to update this for the next release.

**Comment by larsoner** [comment]
It's already updated in master any time a PR needs new data
