### ISSUE TITLE
How to extract the lead field matrix after the eeg inverse transformation

### ISSUE THREAD

**Issue by Rockingsnow** [mne-tools/mne-python#5662]
I want to know which file or function the lead field matrix exists in and how to extract it？

**Comment by agramfort** [comment]
see:

leadfield = fwd['sol']['data']

if https://mne-tools.github.io/dev/auto_examples/forward/plot_forward_sensitivity_maps.html#sphx-glr-auto-examples-forward-plot-forward-sensitivity-maps-py for example.

reopen if it does not fix your pb.

@Rockingsnow please rather use the mailing list or gitter channel for such questions https://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis https://gitter.im/mne-tools/mne-python
