### ISSUE TITLE
BrainVision: Confusing warning message since intro of annotations

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-python#5669]
When I want to read a `.vhdr` BrainVision header file, I get this  warning message:

```
Extracting parameters from xxx/sub-002_task-bandit_eeg.vhdr...
Setting channel info structure...
Used Annotations descriptions: ['Stimulus/S  1', 'Stimulus/S  2', 'Stimulus/S  3', 'Stimulus/S  4', 'Stimulus/S  5', 'Stimulus/S  6', 'Stimulus/S  7']

<ipython-input-8-7feb117556b8>:1: RuntimeWarning: 1 annotation(s) will be dropped, such as ['Comment/actiCAP Data On']. Consider using ``regexp`` to ignore annotations that do not follow a specific pattern.
  raw = mne.io.read_raw_brainvision(fname)
```

This is fine and a warning should be printed (like we did previously). However the new message does not make sense in the user context:

> Consider using ``regexp`` to ignore annotations that do not follow a specific pattern.

`regexp` is not a possible argument for `mne.io.read_raw_brainvision`, so I assume that this is some unintended spillover from the annotations refactoring.

**Comment by agramfort** [comment]
what was the error message before?

it's this line
https://github.com/mne-tools/mne-python/blob/master/mne/io/brainvision/brainvision.py#L163
that you want to change.
As there is indeed no way to filter out some annots with the current
brainvision API shall we just
notify that some annots will be ignored without saying more?

**Comment by sappelhoff** [comment]
The prior message was referring to `event_id` and that users should make use of that (potentially with regexp) 

>    event_id : dict | None
        Special events to consider in addition to those that follow the normal
        BrainVision trigger format ('###' with an optional single character
        prefix). If dict, the keys will be mapped to trigger values on the
        stimulus channel. Example: {'SyncStatus': 1; 'Pulse Artifact': 3}.
        If None or an empty dict (default), only BrainVision format events are
        added to the stimulus channel. Keys are case sensitive. "New Segment"
        markers are always dropped.

See: https://github.com/mne-tools/mne-python/blob/ad1c43beec450a1c7f4dcdcc02b38869e0a5370d/mne/io/brainvision/brainvision.py#L301-L304

I suggest we go back to that and just include, that regexps are accepted as well.

**Comment by agramfort** [comment]
can you give it a try ?
