### ISSUE TITLE
ENH: Unify `rank` computations of beamformer and compute_whitener

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#5690]
As pointed out in https://github.com/mne-tools/mne-python/pull/5447#issuecomment-435378632, the `rank` argument in `mne.beamformer` and `mne.cov.compute_whitener` follow slightly different code paths. In #5481 the `compute_whitener` behavior lives in `_smart_eigh`; in #5447 it lives in `reg_pinv`.

This issue is related to #5362, where @britta-wstnr has also been thinking about how to do this inversion.

**Comment by larsoner** [comment]
... also, the default for `make_lcmv` should change from `rank='full'` to `rank=None` (via deprecation cycle) once we are confident it all works properly.

**Comment by britta-wstnr** [comment]
@larsoner is this the same as #5879 ?
