### ISSUE TITLE
RuntimeError: Reader error, notify mne-python developers

### ISSUE THREAD

**Issue by usarawgi911** [mne-tools/mne-python#5722]
Firstly, thank you for this amazing library, helps a lot. :))

![github_issue](https://user-images.githubusercontent.com/22166359/48679249-f5038500-eb5b-11e8-9ed6-6343293e79ef.png)

I am running into the above error using MNE 0.16.2 -- "RuntimeError: Reader error, notify mne-python developers" originating from mne/io/base.py (as can be seen in the above snapshot as well)

Any help with be highly appreciated :))

**Comment by agramfort** [comment]
you use openbci data.

You should report the issue here: https://github.com/OpenBCI/OpenBCI_MNE

**Comment by usarawgi911** [comment]
Yup, I already raised the issue there but nvm, I just wrote some custom code to parse through the file and get the data into an MNE object, works. Thanks anyway :))

**Comment by agramfort** [comment]
if you have the fix you should open a PR to fix it upstream
