### ISSUE TITLE
whats new refactor

### ISSUE THREAD

**Issue by massich** [mne-tools/mne-python#5731]
the whats new it's getting long. I suggest we split it. I think that matplotlib did it long ago, and scikit-learn did it last year (https://github.com/scikit-learn/scikit-learn/issues/9124)

we could recycle much of the work. 

We could also try whatever use people from [pytest](https://docs.pytest.org/en/latest/changelog.html) and force the whats new by the CI

**Comment by agramfort** [comment]
again

+0 on this. If multiple people feel the need to change this no objection
