### ISSUE TITLE
TFCE on 3D spatial or 4D spatio-temporal data

### ISSUE THREAD

**Issue by ilogue** [mne-tools/mne-python#5745]
Would `spatio_temporal_cluster_1samp_test` and the other clustering functions work on 3D spatial or 4D spatio-temporal data? I'm thinking to use it for data in MNI space. Dimensions would be approximately 256 * 65 * 77 * 53 (t * x * y * z). Would I have to provide it with a connectivity matrix or would it take into account a "3D lattice"?

What do you think @larsoner @ktavabi ? many thanks!

**Comment by mmagnuski** [comment]
I don't know about volumetric data (surface- or channel- based representations have only one spatial dimension) but in general currently cluster based tests are limited to 2d in mne.

**Comment by mmagnuski** [comment]
So if you have 3 spatial dimensions and one additional you would have to "unroll" the spatial dimensions and provide connectivity for them.

**Comment by agramfort** [comment]
you can work with any connectivity provided it's regular grid or you
provide a sparse matrix to define the connectivity

**Comment by ilogue** [comment]
alright I'll give that a go

**Comment by larsoner** [comment]
Closing in favor of #4859
