### ISSUE TITLE
Allow adding electrode names next to evoked plots in evoked.plot_topomap

### ISSUE THREAD

**Issue by jdpigeon** [mne-tools/mne-python#5746]
We're using the MNE plots to great success in the [BrainWaves educational neuroscience app](https://github.com//makebrainwaves/brainwaves)

![image](https://user-images.githubusercontent.com/4932565/48955584-9acc4080-ef1c-11e8-8f28-0f271f2bfcc3.png)

However, we have a slightly odd user experience now because the plot we generate to show ERP waveforms at all channels isn't labeled by electrode. AFAIK, there isn't any way to do this within the constraints of what MNE provides.

In a future release, it would be really nice to be able to provide a legend to this plot so that each electrode name is labeled. This, along with some other tweaks to the graphical MNE components, is something I'd love to help out with in a future MNE sprint.

**Comment by agramfort** [comment]
+1

we should also return channel name with _iter_topography and pass the ch_name
to the plotting function.

any volunteer?

**Comment by jona-sassenhagen** [comment]
See https://github.com/mne-tools/mne-python/pull/5568 and https://github.com/mne-tools/mne-python/issues/4746

**Comment by jdpigeon** [comment]
Yes! That example in https://github.com/mne-tools/mne-python/issues/4746 would be perfect

**Comment by jona-sassenhagen** [comment]
Well the PR is still very work in progress, but you can just steal the code I posted in #4746.
