### ISSUE TITLE
combined M/EEG and apply_inverse and extract_label_time_course

### ISSUE THREAD

**Issue by Sambami** [mne-tools/mne-python#5749]
Hi all,

I have a brief question about how apply_inverse and extract_label_time_course handle combined M/EEG data. Are the source estimates a combination of the MEG and EEG data, or based only on the MEG data?

The epochs used in the forward model contain mag/grad and EEG channels.

Thank you,
Sam

**Comment by agramfort** [comment]
it's combined so inverse pb is done jointly with all available channels. It's made possible by the whitening step. See for example https://www.ncbi.nlm.nih.gov/pubmed/25541187 and https://hal-imt.archives-ouvertes.fr/hal-01183551/document

**Comment by Sambami** [comment]
Thank you very much. I did not realize this; I hope it is okay that I ask a follow-up question. To provide some background: I have M/EEG (tSSS'd) data + structural MRIs of children with many epochs (~800-900). I expect the noise to be heteroscedastic. I am using MNE to extract the current values and dSPM for visualization.

- The epochs used to estimate the covariance matrix are already tSSS'd, and artifacts are rejected with ICA. I have been using the Shrunk method, but I was wondering if I should use FA instead?

I appreciate any help you can provide!

Best,
Sam

**Comment by agramfort** [comment]
please the mailing list
https://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis
and not the issue tracker to ask your questions.

To know if you should use FA or Shrunk just use the builtin
cross-validation procedure.
That's the whole point of our work with @dengemann to automate this decision.

**Comment by Sambami** [comment]
Apologies. Will do, thank you.
