### ISSUE TITLE
mixed source space and pick_ori='vector'

### ISSUE THREAD

**Issue by annapasca** [mne-tools/mne-python#5751]
Hi all,

I tried to use `pick_ori=vector` with a mixed source space but it crashed.

Here the example script to reproduce the problem
 [plot_mixed_source_space_inverse_vector.py](https://gist.github.com/annapasca/5f292a55e2b5f152c872e6047d495c7d).

I 'd like also to come back to #4317 since it seems #4312 doesn't implement the issue of #4317

**Comment by jasmainak** [comment]
@agramfort @larsoner let us know if this is interesting for you. @annapasca tells me she has code to make it work ...

**Comment by agramfort** [comment]
sure this should have worked. PRs welcome

**Comment by larsoner** [comment]
We test that this works nowadays so it must have been fixed at some point along the way! But feel free to reopen if I'm mistaken
