### ISSUE TITLE
How to compare ERPs or TF on different samples?

### ISSUE THREAD

**Issue by psychoxiatao** [mne-tools/mne-python#5763]
I have another question, I have two samples, and I have computed the ERP, ERS, and ERD for the individual level, how to do statistics and plot them on the group level in MNE. Thanks a lot.

**Comment by mmagnuski** [comment]
Please use the mne discussion list for general questions (as opposed to bug reports and feature requests):
https://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis

**Comment by jona-sassenhagen** [comment]
We should really improve the docs on group analyses though.
