### ISSUE TITLE
mne.viz.plot_evoked_topo(): all evoked times must be the same?

### ISSUE THREAD

**Issue by jjnurminen** [mne-tools/mne-python#5766]
Howdy!

A student here tried to compare different datasets in mne.viz.plot_evoked_topo(), but the function bails due to slightly different sampling frequencies, giving the error that "all evoked times must be the same".

Should the plotter work even if the data are on different x grids, or is there a good reason for it not working?

**Comment by larsoner** [comment]
> Should the plotter work even if the data are on different x grids, or is there a good reason for it not working?

It's likely just an implementation detail that it's easier internally to do the plotting if the `times` are all the same (e.g., choosing axis limits or ticks, combining data into arrays, etc.). So feel free to look to see if it can be generalized easily enough. I don't see any reason in principle that we can't or shouldn't support it, other than its implementation might be more complicated than it's worth.

**Comment by jjnurminen** [comment]
Asking for identical time grids is a bit restrictive IMO, so it'd be nice to fix it.

If there's several plotting functions that assume identical times, it might be easier to write a gadget that interpolates a list of Evokeds into a common time grid? Then that could be called from any function.

**Comment by agramfort** [comment]
I would rather see how to fix plotting functions

**Comment by jjnurminen** [comment]
Of course matplotlib will interpolate the data anyway when plotting it, so interpolating it beforehand would be kind of superfluous...
