### ISSUE TITLE
MNE Installation from source

### ISSUE THREAD

**Issue by GuillaumeFavelier** [mne-tools/mne-python#5767]
Hi,

I followed the instructions described in the [MNE website](https://martinos.org/mne/stable/install_mne_python.html) and it worked fine, I was able to use try some [examples](https://martinos.org/mne/stable/auto_examples/index.html) as well.

Then I tried to install MNE from the source code but I was not able to find any instructions on how to achieve this in [README.rst](https://github.com/mne-tools/mne-python/blob/master/README.rst) or the [contributing section](https://martinos.org/mne/stable/contributing.html) of the website, can you help with that?

By the way, I'm using Arch Linux.

**Comment by massich** [comment]
yep! it is true that we might need to update that an make it more clear. But I'm not where should it be placed. Anyway, usually when I need a clean installation what I do is a variant of this lines in `appveyor.yml`:
https://github.com/mne-tools/mne-python/blob/86d3f20e0e1bdf57089517037961348cd0a5f260/appveyor.yml#L14-L16

what I do is:
```sh
$ git clone git@github.com:mne-tools/mne-python.git $MY_PATH_TO_MNE
$ conda create --name mne_XXX python=X.X
$ conda activate mne_XXX
$ conda install mne
$ conda uninstall mne
$ cd $MY_PATH_TO_MNE
$ pip install -e .
```
