### ISSUE TITLE
Broken link + bad rendering of plot_source_alighnment

### ISSUE THREAD

**Issue by massich** [mne-tools/mne-python#5773]
![image](https://user-images.githubusercontent.com/7044835/49525331-d3213680-f8ad-11e8-9998-965d950e3679.png)

this 3 bullets do not render properly in my computer + 1 `transformation matrices` points [here](https://mne-tools.github.io/stable/auto_tutorials/trans_matrices)

**Comment by larsoner** [comment]
What's wrong with the bullet points?

**Comment by massich** [comment]
Actually nothing. I just did not understood that actually for visualizing purposes the arrows have different lengths, (and maybe labels) that's why some letters are capital and surrounded by ( ). 

I thought it was a rendering issue.

**Comment by massich** [comment]
maybe I would explain what RAS is, relate it to XYZ and then explain the arrows length. But I'm not sure if this is already done somewhere else.

**Comment by larsoner** [comment]
That's what the bullet points are meant to do, feel free to reword if it's not clear

**Comment by massich** [comment]
Actually, when I opened the issue, my goal was the broken link. And to know if we have some way to test that all links are right.

**Comment by larsoner** [comment]
It should probably be:
```
`transformation matrices <trans_matrices_>`_
```
You can check to see if Sphinx provides a way to check that all links (including URL links inline) actually point somewhere valid, but doing so might slow things down a lot because it could cause potentially a *lot* of remote URL checks.

**Comment by massich** [comment]
we can run it in an overnight build

**Comment by GuillaumeFavelier** [comment]
Actually I found another broken link in [plot_introduction](https://martinos.org/mne/stable/auto_tutorials/plot_introduction.html?highlight=inverse) that points to https://martinos.org/mne/stable/auto_tutorials/auto_examples/index.html instead of https://martinos.org/mne/stable/auto_examples/index.html

![image](https://user-images.githubusercontent.com/18143289/49934523-e431ff00-fece-11e8-9c81-e50cb66249bd.png)
