### ISSUE TITLE
error when trying to convert .vhdr file from brainvision to numpy array

### ISSUE THREAD

**Issue by rafaa1988** [mne-tools/mne-python#5785]
I have mne_version: 0.16.2
I can import brainvision .vhdr file in mne:
import mne
from mne import io
import numpy as np
myraw=mne.io.read_raw_brainvision('myvhdrfile.vhdr')

However I get error when trying to convert Raw object to numpy array:

my_array = A.get_data() # TypeError: unhashable type: 'dict'

Thanks for help

**Comment by agramfort** [comment]
Can you try with mne 0.17 ? If you also have the problem please share the file privately with me 

Thanks

**Comment by rafaa1988** [comment]
I sent the file to your email
I tried 0.17 and 0.18 and I'm getting now in the line 
myraw=mne.io.read_raw_brainvision('myvhdrfile.vhdr')
the following error:
BrainVision files with ASCII data in vectorized order (i.e. channels in rows) are not supported yet.

wehereas when in 0.16 there was no problem with the above line but with the line after that:
my_array = myraw.get_data() # TypeError: unhashable type: 'dict'

So I can understand from the error in 0.17 and 0.18 that the error is that the channels are rows and might should be columns. But I don't have this error in 0.16

**Comment by cbrnr** [comment]
MNE doesn't support this version of BrainVision data. Even in 0.16 or earlier, this was not supported (you only received an error messages at a later stage when the data was actually accessed, now you get the error up front - you can try `preload=True` in 0.16 and you will get an error).

**Comment by agramfort** [comment]
indeed. You'll need to fix our reader to support your file or find a
way to convert it to a format we support.

**Comment by massich** [comment]
PRs are wellcome

**Comment by w018elf** [comment]
What version of BrainVision data does MNE support?

**Comment by cbrnr** [comment]
MNE supports binary and ASCII with channels in columns flavors of BrainVision files. If you have the chance to pick the flavor, go for the binary one.

**Comment by larsoner** [comment]
Closing as something we probably won't fix, but if someone is up for making a PR to support row-ordered data please do!
