### ISSUE TITLE
BUG: Adding columns to raw._data does not change the data returned by raw.get_data()

### ISSUE THREAD

**Issue by jhouck** [mne-tools/mne-python#5790]
It's not clear if this is a bug or a reason not to mess around with hidden features, but changing the number of columns in raw._data doesn't change the shape of what is returned by `raw.get_data()`.  

For example, if you do a very simple test such as:

```import mne
import numpy as np
from mne.datasets import sample

data_path = sample.data_path()
fname = data_path + '/MEG/sample/sample_audvis_raw.fif'
raw = mne.io.read_raw_fif(fname, preload=True)
x, y = raw._data.shape
raw._data = np.zeros((x,y+50000))
print(raw._data.shape)
print(raw.get_data().shape)
raw._last_samps = [raw._first_samps[0] + raw._data.shape[1] - 1]
print(raw.get_data().shape)
```

You see that `get_data` only returns up to the previous raw._last_samps. (See also my note-laden gist at https://gist.github.com/jhouck/aff32f67a903a5d75721f148a52de852) Would it be worth having `get_data` update _times and  _last samps -- e.g., `raw._last_samps = [raw._first_samps[0] + raw._data.shape[1] - 1]`?  Or would it be better to stay away from this kind of thing and, rather than breaking a perfectly good raw, instead create a new RawArray?  It might be an unusual use case -- there are mne functions that directly modify raw._data but none of the ones I'm aware of would affect its shape in this way.

**Comment by larsoner** [comment]
> Or would it be better to stay away from this kind of thing and, rather than breaking a perfectly good raw, instead create a new RawArray

Yes. Modifying private (prefixed with `_`) attributes of classes leads to undefined and often wrong behavior. `RawArray` is what I would use here.
