### ISSUE TITLE
[BUG] EpochsTFR.save not saving metadata

### ISSUE THREAD

**Issue by kdoelling1919** [mne-tools/mne-python#5798]
Just realized that EpochsTFR.save doesn't save metadata so if you save and reload the function you'll lose the metadata, event, and event_id information. I missed this when I updated EpochsTFR to include metadata. The problem arises when writing to the Hard Disk, `mne.time_frequency._prepare_write_tfr()` hardcodes what attributes to save into a dict, so that when I added new attributes, they didn't get saved. I think I can fix this by doing something like

`attributes = vars(epochsTF)`

with a few other adjustments.

If others agree, I can make a quick PR on this

**Comment by agramfort** [comment]
+1 for bug fix PR asap. thx

I would just copy how it's done in epochs.save

**Comment by larsoner** [comment]
> I would just ~~copy~~ /refactor and reuse/ how it's done in epochs.save

FTFY :)

**Comment by larsoner** [comment]
... in general we try to avoid things like `vars(epochsTF)` because while general is not so obvious what is actually getting saved. So we tend to use explicit variable names instead.
