### ISSUE TITLE
Use raw.set_annotations directly with arguments for mne.Annotations

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#5803]
Would it be totally insane if we could call `raw.set_annotations` directly with the arguments that we provide to `mne.Annotations`? I mean, if I want to use `raw.set_annotations`, I have to construct my annotations like this:

    annotations = mne.Annotations(onset, duration, description)

Which I then immediately follow up with:

    raw.set_annotations(annotations)

Therefore, it would be convenient if I could just do:

    raw.set_annotations(onset, duration, description)

I'd be happy to contribute a PR is people think this is useful.

**Comment by larsoner** [comment]
I'd rather not add another way of doing the same thing

**Comment by cbrnr** [comment]
What about deprecating the old way then? I don't see why this has to be two steps when it could be done in one.

**Comment by larsoner** [comment]
A few reasons not to. In general we want to have a good reason to break people's code by deprecation. We've already done it this way for a couple of releases. You can create, save, and load annotations independent of any raw data.

**Comment by agramfort** [comment]
> +1


also look at the sleep data that are in separate edf files.

https://github.com/mne-tools/mne-python/pull/5718/files#diff-eccb82e78c8dd0ecbdbdbd57deb2a8ff

in PR https://github.com/mne-tools/mne-python/pull/5718/files

**Comment by cbrnr** [comment]
I still think we could accept both argument types, this would save a line for the most common use case. I agree that deprecating the current behavior is not a good idea.

**Comment by cbrnr** [comment]
It is similar to what we did with `raw.set_montage`, where we can either pass a `Montage` object or a string with the montage name.

**Comment by larsoner** [comment]
Yes we have other instances of having multiple ways of doing the same thing, but I'd rather not add more. (For that example in particular, too, we plan to overhaul quite a bit how montage/digitization/etc. are handled. It's not great API design that there is a `montage` argument in readers, plus a `set_montage`, plus `set_montage` taking a `Montage` as arg or string.)
