### ISSUE TITLE
epochs.plot_psd loses axis labels

### ISSUE THREAD

**Issue by massich** [mne-tools/mne-python#5816]
I would expect this code to work

```py
from mne.viz.tests.test_epochs import _get_epochs
import matplotlib.pyplot as plt
import mne

epochs = _get_epochs()

# subplot axis properly labeled
_, (ax1, ax2) = plt.subplots(nrows=2)
epochs.plot_psd(picks=mne.pick_types(epochs.info, meg='meg'), ax=[ax1, ax2])

# proper axis labels
epochs.plot_psd(picks=mne.pick_types(epochs.info, meg='mag'))

# missing labels
_, (ax1, ax2) = plt.subplots(nrows=2)
epochs.plot_psd(picks=mne.pick_types(epochs.info, meg='mag'), ax=ax1)
```
 
![image](https://user-images.githubusercontent.com/7044835/50742462-c6c12e00-120b-11e9-9e85-5a7c059d1b08.png)

**Comment by agramfort** [comment]
I can replicate the pb

>

**Comment by massich** [comment]
The issue is here:

We recover the figure and if the number of axis match, then we set `make_label=True`.

https://github.com/mne-tools/mne-python/blob/feb0bec3acf334ee391711109c9a541697813a30/mne/viz/raw.py#L600-L602

What I'm not sure if this is a bug or a feature.
This was added by @larsoner [here](https://github.com/mne-tools/mne-python/commit/53506d1d5547a5dbed8e30d9927232a58ced7a81#diff-190df768fb5ee305b0a421d3dd6ae9adR600)

**Comment by agramfort** [comment]
I would say it's a bug. It's easier to change the labels afterwards.

**Comment by massich** [comment]
>I'm fine with changing this, but make sure the change is in the BUG section because it's a backward incompatible change that will break some people's plotting code. (I'm sure it will break some of mine.)

That's why I asked. What I could not figure out is when this should be false. My understanding is that you add that so that the first plot is possible. (otherwise, it does not). But If we always return True that would work in both cases (first and last). But I could not figure out when we would like to not write the labels.

**Comment by larsoner** [comment]
Basically if we create the axes internally, we know (at least) the `xlabel` is placed correctly; if the user supplies them, we can't guarantee it

**Comment by agramfort** [comment]
yes that's why it should be displayed by default when you pass one ax

>
