### ISSUE TITLE
Saving Raw object to .fif file Modifies Channel Values

### ISSUE THREAD

**Issue by lpjiang97** [mne-tools/mne-python#5843]
When I save my `Raw` object to `*.fif` files using the `Raw.save` function, it adds very small floating point values to channel values: 

```Python
import mne

print(raw[-1, :]) # last column is stim channel
raw.save("testing_raw.fif", overwrite=True)
test_raw = mne.io.read_raw_fif("testing_raw.fif")
print(raw[-1, :]) # different from above
```

The values of each column are modified with *very minor floating point values* (e.g. trigger 22 is now 22.000006, Channel Fp1 has values modified from -4.18593870e-09 to -4.18593890e-09). I wonder if I'm not setting up anything correctly?

Thank you!

**Comment by agramfort** [comment]
mne saves in float32 by default. You can set fmt param in raw.save to save
in float64 but it will double the size of the files on disk.

>
