### ISSUE TITLE
ENH: Annotations.sort

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#5854]
Sort annotations based on onset. Should return `self` for consistency.

**Comment by massich** [comment]
If we have a sorting method, we should used in places like this (there are more):
https://github.com/mne-tools/mne-python/blob/e96d706b65b6c6a21821d3dcbc06e10903e9c05b/mne/viz/utils.py#L1913-L1914

The other option it would be to actually keep annotations always sorted by onset, and use `numpy.searchsorted` in `append` and `_combine_annotations`

**Comment by mmagnuski** [comment]
I'd be +1 for always sorting, but I'm also ok with `annotations.sort()`.

**Comment by agramfort** [comment]
+1 for always sorting

>

**Comment by cbrnr** [comment]
+1 for always sorting and adding an extend method. As tie breakers I suggest that we use description and then duration.

**Comment by larsoner** [comment]
It looks like `append` already has `extend`-like behavior, so we can just update the docstring.
