### ISSUE TITLE
Processing all channels in one go with `Raw.apply_function`

### ISSUE THREAD

**Issue by hubertjb** [mne-tools/mne-python#5860]
I want to apply a function on the internal data in a `Raw` object, and I saw that there is an `apply_function()` method for this purpose. However, `apply_function` seems to apply the function channel-wise (sequentially or in parallel), while my function could potentially be run faster by working on all channels at once.

Would there be any interest in adding an attribute to `apply_function` to allow applying the function on all channels at once instead of channel-by-channel?

I had something like this in mind:

```python
if n_jobs == 1:
    # modify data inplace to save memory
    if apply_in_one_go:
        self._data[picks, :] = _check_fun(fun, data_in[picks, :],
                                           *args, **kwargs)
    else:
        for idx in picks:
            self._data[idx, :] = _check_fun(fun, data_in[idx, :],
                                            *args, **kwargs)
```

If this is of interest I can make a PR.

Thanks!

**Comment by massich** [comment]
I think it makes more sense to do the opposite, the function should always work with the data in one go, and delegate the operation to the call.

**Comment by larsoner** [comment]
> But this might not be backward compatible. So we should add the parameter and deprecate it, in one go.

I wouldn't bother with a deprecation cycle, it seems overkill. But sure, if `channel_wise=True` (default) is `False`, then ignore `n_jobs` and just pass the entire data array.

**Comment by massich** [comment]
+1 for `channel_wise=False`

**Comment by hubertjb** [comment]
Perfect, I'll make a PR to add 'channel_wise' then. Thanks!

**Comment by larsoner** [comment]
Please leave the default as `True` for backward compat

**Comment by larsoner** [comment]
Argh I mean `False`, mis-read things...

**Comment by larsoner** [comment]
Double mis-read, `channel_wise=True` is what we do now and it should remain the default

**Comment by massich** [comment]
@hubertjb can we close this?

**Comment by larsoner** [comment]
Yes the PR has been merged
