### ISSUE TITLE
ENH: Reading file-like objects

### ISSUE THREAD

**Issue by arokem** [mne-tools/mne-python#5867]
#### Describe the problem

Some data reading APIs provide open file objects, and do not provide a full path to the file. For example, [gcsfs](https://gcsfs.readthedocs.io/en/latest/) provides an API to read files directly from Google File Storage

```
fs = gcsfs.GCSFileSystem(project='my-gcp-project')
with fs.open("my_bucket/data.fif") as f:
    # Do things with an open file object
    ...
```    

It would be useful to be able to do: 

```
fs = gcsfs.GCSFileSystem(project='my-gcp-project')
with fs.open("my_bucket/data.fif") as f:
    raw = io.read_raw_fif(f)
```

But `io.read_raw_fif` can only take a string as input.

So it would be good if there was some way to take an open file object and use that instead. 

Sorry: I have no idea what the implementation details would be.

**Comment by jjnurminen** [comment]
I wonder how one would handle split fif files when accepting file objects as args. Maybe just assume that everything is in a single file?

**Comment by agramfort** [comment]
it will certainly break with split fif files but also many other
readers that put data in directories (CTF, 4DBTi) and have data split
in multiple files (brainvision).

so we could eventually support this but just for a small set of readers.

**Comment by larsoner** [comment]
For FIF the code changes would not be so bad, but as @jjnurminen suggests it would not work for all FIF files (split ones), and as @agramfort hints it wouldn't work with most other readers.

@arokem would it make your life a lot easier to have it for FIF? If so, I can try adding support for it, which seems reasonable alongside a docstring caveat that split files will not read properly.

**Comment by arokem** [comment]
"A lot" is a very relative term. If you think that implementing this just for non-split FIF files is relatively easy, that would be a step forward. If it seems too niche to support, I will probably find a way around it (e.g., converting to HDF5 before uploading to GCS).

**Comment by larsoner** [comment]
I tried implementing this today, and unfortunately it's a bit tricky to implement. We control the `.close` (often via context manager), so we have to keep track of or fake that somehow. Even once that's done, internally we assume a filename is available in a number of places. Then the `raw.copy()` method just does `copy.deepcopy(self)`, which does not work if `self` has open file pointers (`TypeError: cannot serialize '_io.BufferedReader' object`). That's where I stopped trying to cobble together workarounds, as it's possible there would be other problems, and I'm not confident it would work all that well.

**Comment by arokem** [comment]
Thanks for trying. It might be that the short run solution is to convert locally to another file format before uploading to GCS. Feel free to close this, unless you want to keep this around as a reminder for future adventurous souls.

**Comment by larsoner** [comment]
Can you make a local copy of the entire thing when you need it instead?

**Comment by larsoner** [comment]
Closing since unfortunately I think this is intractable for now.

**Comment by larsoner** [comment]
Reopening due to renewed interest (this time in StringIO, which implementation-wise is going to have similar issues with open file objects).

@arokem @teonbrooks would it work for your use cases if we supported file-like objects (e.g., open file objects, StringIO) only when used with `preload=True`? This would probably get around most of the implementation problems I foresee.

**Comment by teonbrooks** [comment]
Yep, that would fit my use case.

**Comment by arokem** [comment]
I believe so!

**Comment by larsoner** [comment]
Okay I can implement this hopefully without too much complexity. I'll shoot for next week.
