### ISSUE TITLE
ENH?: delayed reduction of induced power in source space

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#587]
Currently we have two functions wrapping `_source_induced_power`, that is, 
`source_band_induced_power` and `source_induced_power`. 
It seems there is at least one use case which is only indirectly covered with this API, namely, computing TFRs for the entire source space in a first step and then doing binning or label-based reduction at some later point. E.g. for a group analysis it might be nice to first compute the TFR in source space for each subject X condition and then later select bins / labels. I'm wondering whether we should have a third API for this purpose. Alternatively we could think about making  `_source_induced_power` a public function.

Wdyt?

cc @mluessi

**Comment by larsoner** [comment]
I'm closing in favor of the ongoing TFR work, which I think will support this sort of thing
