### ISSUE TITLE
(Vector) beamformer should throw error with sphere headmodel

### ISSUE THREAD

**Issue by britta-wstnr** [mne-tools/mne-python#5880]
Leadfield rank reduction is not implemented yet for vector beamformers, so they should throw an error with leadfields that are not full rank (e.g. with sphere head models). 
Furthermore, the scalar beamformer does only complain about leadfield rank if the inversion fails. It would in general be good to inform the user about reducing the rank when having sphere head model upfront.

**Comment by britta-wstnr** [comment]
Add an ``auto`` option to the ``reduce_rank`` parameter: reduce the rank of the leadfield on a voxel by voxel basis to deal with sphere models as well as unstable voxels in other headmodels. --- Think again, whether it is a good idea to make voxels behave differently.

**Comment by agramfort** [comment]
@britta-wstnr @larsoner has this been addressed already? I have the feeling that maybe...
