### ISSUE TITLE
Problems with installation instructions

### ISSUE THREAD

**Issue by biancasama** [mne-tools/mne-python#5884]
I was following the installation guides for MacOS and then at [point 2](https://martinos.org/mne/stable/install_mne_python.html#get-mne-and-its-dependencies) I get the following error:

```sh
(base) Biancas-MacBook-Pro:~ bt_neurospin$ curl -0 https://raw.githubusercontent.com/mne-tools/mne-python/master/environment.yml
name: mne
channels:
- defaults
dependencies:
- python>=3.6
- pip
- mkl
- numpy
- scipy
- matplotlib
- cython
- pyqt>=5.9
- vtk>=8
- pandas
- xlrd
- scikit-learn
- h5py
- pillow
- statsmodels
- jupyter
- pytest
- pytest-cov
- pytest-mock
- pytest-timeout
- joblib
- psutil
- numpydoc
- flake8
- spyder
- numexpr
- traits>=4.6.0
- pyface>=6
- traitsui>=6
- testpath<0.4
- pip:
  - mne
  - https://api.github.com/repos/enthought/mayavi/zipball/b3fc35218dda9776d8f1a407663bfb49783dca12
  - PySurfer[save_movie]
  - dipy --only-binary dipy
  - nibabel
  - nilearn
  - neo
  - pytest-faulthandler
  - pydocstyle
  - codespell
  - python-picard
(base) Biancas-MacBook-Pro:~ bt_neurospin$ conda env create -f environment.yml

EnvironmentFileNotFound: '/Users/bt_neurospin/environment.yml' file not found

(base) Biancas-MacBook-Pro:~ bt_neurospin$ 
```

**Comment by massich** [comment]
The problem is a typo in your command. It should be `curl -O blabla` (minus capital '0') not `curl -0` (minus 'zero'). The problem is that `conda env create -f` requires the `environment.yml` file and this one is not there because `curl -0` does not create the file but rather spits out the file in the console (thats why you see all those package names).

Just make sure that you copy paste this:
```sh
curl -O https://raw.githubusercontent.com/mne-tools/mne-python/master/environment.yml
conda env create -f environment.yml
conda activate mne
```

**Comment by massich** [comment]
Maybe we should update our documentaiton to make sure this does not happen. Maybe we should modify our sinpped so that it can be copy pasted without any problem. 

The other option is to pass the curl to conda, so that the file is not even saved in the disc.

**Comment by agramfort** [comment]
we could use something like this:

https://predictablynoisy.com/sphinx-copy-buttons
https://clipboardjs.com/

>

**Comment by ValMand** [comment]
This happen to me as well 
![image](https://user-images.githubusercontent.com/47141515/51911869-2c4fa700-23d3-11e9-9e81-991c4ca4751b.png)

**Comment by agramfort** [comment]
we definitely need to improve this. Ie make it easier to copy-paste
and/or add a warning note.
