### ISSUE TITLE
Extracting ICs number from corrmap

### ISSUE THREAD

**Issue by AmirDJV** [mne-tools/mne-python#5899]
I'm trying to use [mne.preprocessing.corrmap ](https://martinos.org/mne/stable/generated/mne.preprocessing.corrmap.html?highlight=corrmap) to identify artifacts. The output of the function returns:
> template_fig : fig
> Figure showing the template.
> labelled_ics : fig
> Figure showing the labelled ICs in all ICA decompositions.

Given that it already identify and plot the similar ICs, is there a way to extract the subject number and the ICs names?. 
Thus, for example, when I identified eye blinking artifact in one subject, I can exclude it from all the other ICAs.

**Comment by agramfort** [comment]
ping @jona-sassenhagen

**Comment by jona-sassenhagen** [comment]
Check the ```label``` kwarg.

```
label : None | str
If not None, categorised ICs are stored in a dictionary labels_ under the given name. Preexisting entries will be appended to (excluding repeats), not overwritten. If None, a dry run is performed and the supplied ICs are not changed.
```

I.e., if you give a label here, corrmap will store a list of the selected ICs for each ICA, in a dict that you can find on the ICA object itself. I.e., `my_ica.labels_["eog"]`. Makes sense?

Don't forget that this is only temporary (in memory) - you have to save the ICA object to disk to make it permanent.

**Comment by AmirDJV** [comment]
Makes perfect sense, don't know how I missed that. Thank you!
