### ISSUE TITLE
[ENH] MNE-Python 0.17.1 release

### ISSUE THREAD

**Issue by massich** [mne-tools/mne-python#5941]
WDYT?

**Comment by agramfort** [comment]
+1

branch is update to date as well as website?

Shall I just push to pypi?

**Comment by larsoner** [comment]
The CircleCI build for `maint/0.17` failed so no don't release yet

**Comment by larsoner** [comment]
Scratch that, someone must have restarted the build so that's fine. But we should probably also squeeze #5942 in the release.

**Comment by agramfort** [comment]
ok cool

let me know when I can push to pypi

I'll also update then the martinos website

**Comment by massich** [comment]
> But we should probably also squeeze #5942 in the release.

There's no need. The file is not in 0.17

**Comment by larsoner** [comment]
You should be good to go @agramfort

**Comment by agramfort** [comment]
0.17.1 is on pypi and website is updated

>
