### ISSUE TITLE
Loading BDF file fails on UTF-8 decoding error

### ISSUE THREAD

**Issue by danieldiamont** [mne-tools/mne-python#5943]
#### Describe the bug
Please provide a clear and concise description of the bug.

The header of my BDF file has a patient with a name that contains the character `è`, which causes line 600 of `io/edf/edf.py` to fail with error:

```python
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 4: invalid continuation byte
```

#### Steps and/or code to reproduce

Loading any `.bdf` file with that accent causes the issue. The issue occurs with the most recent pip package and the current head of master.

#### Additional information

We temporarily solved our issue by changing the line to:

```python
# patient ID
pid = fid.read(80).decode(errors='ignore')
```

However, it may be worthwhile to replace the offending character with a space or something harmless.

**Comment by larsoner** [comment]
This suggests that EDF does not encode using UTF-8. We should find out what encoding they use, and `decode()` with that.

**Comment by agramfort** [comment]
how did you write the edf file? is utf-8 accepted by the standard? is there
a way to know if the edf file should be decoded in latin1 or utf-8?

>

**Comment by cbrnr** [comment]
AFAIK the standard does not mention which encoding should be used. We've stumbled into a similar issue for GDF files, which we solved by using `.decode('latin-1')`. This should take care of the accent (and other special characters).

**Comment by agramfort** [comment]
cool. Who sends the PR and shares a test file?

>

**Comment by cbrnr** [comment]
I can do the PR if nobody else beats me to it.

**Comment by agramfort** [comment]
go for it please
