### ISSUE TITLE
Download status bar shows incorrect speed

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#5948]
I just downloaded the testing data with

```
from mne.datasets import testing
testing.data_path()
```

The download is extremely slow. However, the status bar shown high speed such as

```
[........................................] 100.00% ( 54.9 MB,   7.0 MB/s) -   
```

Obviously, this is incorrect - maybe because the total file size is unknown? Should we do something to fix this?

**Comment by larsoner** [comment]
Yeah we should. AFAIK it really only happens with `testing` because it fails to get the size properly sometimes for that dataset in particular, because it comes from GitHub which does some redirects.

**Comment by cbrnr** [comment]
OK. Another thing that bothers me is that the status bar doesn't update itself in the same line, but each update creates a new line. Would it make sense to just use `tqdm` for any progress bars we need?

**Comment by larsoner** [comment]
It should update on the same line. You are probably looking at a terminal that does not support backspace, so tqdm would not help

**Comment by cbrnr** [comment]
You're right, obviously this doesn't work in the PyCharm terminal.

**Comment by agramfort** [comment]
I don't know how we can fix this without changing the way we work with the
testing data

>
