### ISSUE TITLE
simulate_sparse_stc throws assertion error when n_dipoles > len(labels)

### ISSUE THREAD

**Issue by QB3** [mne-tools/mne-python#5953]
#### Describe the bug
 ```simulate_sparse_stc ```  throws an assertion error when   ```n_dipoles > len(labels) ```.
It should generate   ```min(n_dipoles, len(labels))  ``` dipoles.

#### Steps and/or code to reproduce
If you slightly modified the code of the following MNE example: 
https://www.martinos.org/mne/stable/auto_examples/simulation/plot_simulate_evoked_data.html#sphx-glr-auto-examples-simulation-plot-simulate-evoked-data-py
by remplacing ```n_dipoles=2``` by ```n_dipoles=4``` ligne 58, whiwh I did here:
https://gist.github.com/QB3/6ac76962c9ab7b9f1b44c1026021cafe
an assertion error is thrown.

#### Expected results
As  ```len(labels) = 3  ``` I expect 3 dipoles.

#### Actual results
assertion error from this line https://github.com/mne-tools/mne-python/blob/8b00fc96ec8574c364007ea6b9655eb288d464bb/mne/simulation/source.py#L210

**Comment by agramfort** [comment]
I would suggest to raise an informative exception message rather than
silently using min(n_dipoles, len(labels))

>

**Comment by QB3** [comment]
OK then we will have to change also the current warning msg:
https://github.com/mne-tools/mne-python/blob/8b00fc96ec8574c364007ea6b9655eb288d464bb/mne/simulation/source.py#L180

**Comment by agramfort** [comment]
hum so now you get a warning but it will always crash afterwards? Basically warn should be ValueError or the `min(n_dipoles, len(labels))` should actually be implemented?

**Comment by QB3** [comment]
yes, current warning is  ```The number of labels is different from the number of dipoles. 2 dipole(s) will be generated```, but then an assertion error is thrown

**Comment by agramfort** [comment]
ok then I would make it a ValueError and not a warn

>

**Comment by QB3** [comment]
OK I will do this then:
-  ```n_dipoles > len(labels)```  --->>> ValueError
- ```n_dipoles < len(labels)```  ---->>> keep the same gene

**Comment by agramfort** [comment]
go for it @QB3
