### ISSUE TITLE
Some questions about ’resample‘

### ISSUE THREAD

**Issue by dongfangyier** [mne-tools/mne-python#5956]
Hi，

Today I have some problems. When I use the MNE library for downsampling, I want to reduce the sampling rate from 5000Hz to 256Hz.
I used the following method.
Raw. resample (256, npad='auto')

Or should I use the following method?
Raw = raw. filter (None, 128)
Raw. resample (256, npad='auto')

I looked at the source code, but did not understand whether the function "resample" had its own filtering.

**Comment by cbrnr** [comment]
Yes, resampling includes the necessary anti-aliasing filter (see also [here](https://martinos.org/mne/stable/auto_tutorials/plot_artifacts_correction_filtering.html)).

**Comment by larsoner** [comment]
Looks resolved, closing
