### ISSUE TITLE
`vlines='auto' in mne.viz.plot_compare_evokeds doesn't work

### ISSUE THREAD

**Issue by PilyuginaNina** [mne-tools/mne-python#5972]
I got error 
vlines must be a list or tuple, not <class 'str'>

`conditions = ['1', '2', '4']
evoked_dict = dict()
for condition in conditions:
    evoked_dict[condition] = mne.read_evokeds(fname, baseline=(None, 0), proj=True, condition=condition)
print(evoked_dict)

colors = dict(Left="Crimson", Right="CornFlowerBlue")

pick = evoked_dict['1'].ch_names.index('MEG0242')

mne.viz.plot_compare_evokeds(evoked_dict, picks=pick, colors=colors, vlines='auto', split_legend=True)`

tmin= 0.0
tmax = 1.021

**Comment by larsoner** [comment]
Fixed by #5969
