### ISSUE TITLE
BUG: plot_sparse_source_estimates broken

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#5985]
See last plot in [master](http://mne-tools.github.io/dev/auto_examples/inverse/plot_custom_inverse_solver.html) compared to [maint/0.17](http://mne-tools.github.io/stable/auto_examples/inverse/plot_custom_inverse_solver.html). @GuillaumeFavelier

**Comment by GuillaumeFavelier** [comment]
I'm on it.
