### ISSUE TITLE
BUG: phyionet links broken

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#5990]
[CircleCI says](https://circleci.com/gh/mne-tools/mne-python/11524) that the links to the sleep dataset are broken, such as

https://physionet.org/pn4/sleep-edfx/

@massich any ideas?

**Comment by massich** [comment]
Yes.
https://physionet.org/physiobank/database/sleep-edfx/

 #5932

I'll check it out, and sent a pr

**Comment by massich** [comment]
https://github.com/MIT-LCP/physionet/issues/97#issuecomment-463299136
