### ISSUE TITLE
fork sphinx-bootstrap-theme?

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#6000]
Just a heads up: `sphinx_bootstrap_theme` is going to break when sphinx 2.0 is released, because [these lines](https://github.com/ryan-roemer/sphinx-bootstrap-theme/blob/master/sphinx_bootstrap_theme/bootstrap/layout.html#L11-L17) will no longer be allowed --- building mne docs on current master of sphinx yields this (excerpt; most of traceback omitted for brevity):
```
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/sphinx_bootstrap_theme/bootstrap/layout.html", line 11, in top-level template code
    {% set script_files = script_files + [
  File "/opt/sphinx/sphinx/builders/html.py", line 137, in __add__
    ret += other
  File "/opt/sphinx/sphinx/builders/html.py", line 129, in __iadd__
    RemovedInSphinx30Warning, stacklevel=3)
sphinx.deprecation.RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
```

This is potentially a problem because `sphinx_bootstrap_theme` hasn't had a commit in around 10 months. If it remains stale, then either mne needs to find a new theme, or mne-tools needs to fork the sphinx_bootstrap_theme repo, fix it, and set things up to install from our fork.

**Comment by larsoner** [comment]
See https://github.com/ryan-roemer/sphinx-bootstrap-theme/pull/193, they are looking into merging

**Comment by drammock** [comment]
@larsoner this can be closed, yes?  ryan-roemer/sphinx-bootstrap-theme#193 has been merged.

**Comment by larsoner** [comment]
Indeed
