### ISSUE TITLE
y-limits of subplots in plot_evoked_topo

### ISSUE THREAD

**Issue by flecaignard** [mne-tools/mne-python#6039]
Hi all,

Is there a way to set y-axis limits in the « click-to-magnify » plots in plot_evoked_topo? The ylim input applies to the main plot, but does not seem to be transferred to sensor-specific subplots.
Thanks!

Françoise

**Comment by jjnurminen** [comment]
Thanks for the ping @agramfort 
I can take a look, if this wasn't picked up already.

**Comment by agramfort** [comment]
please go for it Jussi

>

**Comment by jjnurminen** [comment]
I started playing with this, but can't get the ylim to work at all on latest master. For example, modifying `plot_topo_compare_conditions` and supplying `ylim` as below has no effect on the plot. Am I missing something?

    plot_evoked_topo(evokeds, color=colors, title=title, background_color='w', ylim=dict(grad=[-1e3, 1e3], mag=[-1e3, 1e3]))

**Comment by jjnurminen** [comment]
Also it looks like topoplot refactor is coming in #5568. I guess that will completely change how ylim works, so maybe we should wait.
@jona-sassenhagen

**Comment by jona-sassenhagen** [comment]
I will try to get the refactor done at the code sprint ... But I am not yet sure how to deal with interactivity.

**Comment by agramfort** [comment]
maybe this can be done during the sprint then...

>

**Comment by jona-sassenhagen** [comment]
We can try. @flecaignard can you wait for a month? :)

**Comment by jona-sassenhagen** [comment]
This is done in  #6211. However,  #6211 is not doing evoked.plot_topo (but a way for doing topo plots with viz.plot_compare_evokeds). Should I additionally work on making evoked.plot_topo handle this?
