### ISSUE TITLE
4D/BTi import error reading channel data

### ISSUE THREAD

**Issue by ebeich** [mne-tools/mne-python#6048]
#### Describe the bug
Program fails to read a 4D data file, probably due to bad interpretation of 4D data file header

#### Steps and/or code to reproduce
 import mne
fname = 'c,rfDC,fbp3-75n,o'
raw = mne.io.read_raw_bti(fname)
 
#### Expected results
read in the raw data
 
#### Actual results
crashes 
/usr/local/lib/python3.5/dist-packages/mne-0.17.1-py3.5.egg/mne/io/bti/bti.py in _read_channel(fid)
    660                 'index': read_int32(fid),
    661                 'checksum': read_int32(fid),
--> 662                 'off_flag': read_str(fid, 16),
    663                 'offset': read_float(fid)})
    664
with UnicodeDecodeError: 'ascii' codec can't decode byte 0xa4 in position 4: ordinal not in range(128)
 
#### Additional information
Platform:      Linux-4.9.0-8-amd64-x86_64-with-debian-9.8
Python:        3.5.3 (default, Sep 27 2018, 17:25:39)  [GCC 6.3.0 20170516]
Executable:    /usr/bin/python3
CPU:           : 4 cores
Memory:        15.7 GB

mne:           0.17.1
numpy:         1.12.1 {lapack=lapack, blas=blas}
scipy:         0.18.1
matplotlib:    2.0.0 {backend=TkAgg}

sklearn:       0.18
nibabel:       2.1.0
mayavi:        Not found
cupy:          Not found
pandas:        0.19.2
dipy:          Not found

#### Proposed fix:
4D/BTi's $STAGE/map/src/include/dftk_channel_ref.h has
struct dftk_channel_ref_data
{ [...]
    int32_t         checksum;
    char            off_flag[4];
    float           offset;
    char            reserved[24];
};
and in mne/io/bti/bti.py 'off_flag' and fid.seek() should be adjusted:
def _read_channel(fid):
    [...]
                'checksum': read_int32(fid),
                'off_flag': read_str(fid, 4),
                'offset': read_float(fid)})
    fid.seek(24, 1)

**Comment by larsoner** [comment]
@ebeich can you make a PR with your proposed changes?

Any chance you can make and share a tiny recording that shows this problem so we can add it to our set of regression test files?
