### ISSUE TITLE
ENH/IO: add support for LIMO data.

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#6075]
In the past weeks we explored the LIMO dataset with @JoseAlanis and @jona-sassenhagen. We understood how to read its files and make sense of its contents.

https://datashare.is.ed.ac.uk/handle/10283/2189?show=full

@JoseAlanis can you start making a PR with our IO code such that we can add an example that does some basic processing, like computing ERPs of one subject?

**Comment by JoseAlanis** [comment]
yes! where would it be best to put the code? any suggestions?

**Comment by jona-sassenhagen** [comment]
https://mne-tools.github.io/stable/auto_examples/index.html#examples-on-open-datasets ?

**Comment by JoseAlanis** [comment]
PR is WIP; I stored the code as suggested under ``master/examples/datasets``
