### ISSUE TITLE
pip install mne should install numpy and scipy

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#6082]
Currently, the `mne` PyPI package doesn't have any dependencies, but I think it should really treat `numpy` and `scipy` as hard dependencies (and automatically install them if they are not present).

**Comment by larsoner** [comment]
Now that wheels seem to be a very usable, stable thing, I agree we should add our hard dependencies in our requirements list. Even [sklearn does it nowadays](https://github.com/scikit-learn/scikit-learn/blob/master/setup.py#L246-L249).

**Comment by cbrnr** [comment]
I was gonna mention that even sklearn does it but you beat me to it :smile:. I'll make a PR.
