### ISSUE TITLE
Channel names from .locs file truncated to 4 characters

### ISSUE THREAD

**Issue by achilleas-k** [mne-tools/mne-python#6090]
I'm reading a locs montage file with an EDF file and I noticed that my channel names weren't matching.  I dug through the `read_montage()` function and found the following:

https://github.com/mne-tools/mne-python/blob/b74bb10d779dfd8144a4b6fd8fc5444f441f2141/mne/channels/montage.py#L316

Is it part of the specification of the locs format that channel names are restricted to 4 characters?  I have some examples here with longer names and I was wondering if this is valid.

**Comment by massich** [comment]
@achilleas-k I don't think so at least not in EDF+ (IIRC)

**Comment by agramfort** [comment]
It's very possible MNE is too conservative here. PR welcome

>
