### ISSUE TITLE
ENH: Facilitate PyTorch integration

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#6093]
From talking to @kingjr it would be nice to facilitate integration with PyTorch for backpropagation of error, for example when doing:
```
make_pipeline(SpatialFilter, ReceptiveField)
```
A good first goal would be to make an advanced example (with whatever MNE utils we need) that uses `sktorch` to get our sklearn-compatible objects to work with PyTorch with backprop. Bonus points if it actually shows there is a benefit to doing this over just using the forward methods.

**Comment by larsoner** [comment]
Maybe this is a good one for @agramfort at some point :)

Or should we close as scopes etc. have changed to where this no longer makes sense?

**Comment by agramfort** [comment]
this is not going happen anytime soon... closing
