### ISSUE TITLE
question: puzzling results in epochs.plot_topo_image

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#6112]
Setup:
```
import os
import mne
sample_data_folder = mne.datasets.sample.data_path()
sample_data_raw_file = os.path.join(sample_data_folder, 'MEG', 'sample',
                                    'sample_audvis_raw.fif')
raw = mne.io.read_raw_fif(sample_data_raw_file, preload=True, verbose=False)
events = mne.find_events(raw, stim_channel='STI 014')
epochs = mne.Epochs(raw, events, preload=True)
```
I expected these two options to yield the same results, but they're very different:
```
# OPTION 1
epochs.copy().pick_types(meg=False, eeg=True).plot_topo_image()
```
![Figure_1](https://user-images.githubusercontent.com/1810515/55372922-db7e2c80-54af-11e9-9e52-503aa2065d51.png)
```
# OPTION 2
eeg_layout = mne.channels.find_layout(raw.info, ch_type='eeg')                                                            
epochs.plot_topo_image(layout=eeg_layout)
```
![Figure_2](https://user-images.githubusercontent.com/1810515/55372927-e20ca400-54af-11e9-9d20-07cce3152ecc.png)

Is the difference here intentional, or a bug?

**Comment by larsoner** [comment]
Looks like a scaling / vmiv / vmax problem in the first example

**Comment by drammock** [comment]
So, not intentional I take it. I'll have a look.

**Comment by jona-sassenhagen** [comment]
For the purpose of DRY, this could default to #6078 ...

**Comment by drammock** [comment]
@jona-sassenhagen it looks like `_plot_masked_image` (and its proposed public version) require/create an axes object each time called, whereas `plot_topo_image_epochs` does the `_iter_topography` thing to plot each little imagmap inside one big axes.  So changing `plot_topo_image_epochs` to use `_plot_masked_image` behind the scenes might take some heavy lifting.  

(as an aside, I noticed that `_plot_masked_image` has a `picks` argument that appears to go unused?)

**Comment by jona-sassenhagen** [comment]
Hm? iter_topography creates one axis per plot, right?

https://github.com/mne-tools/mne-python/blob/9b5ae5104ecdeaea13a88273c712382bf131162c/mne/viz/topo.py#L214

So this would essentially be about changing the show_func mostly, right?
Not saying it is trivial.

Either way, the same applies to https://github.com/mne-tools/mne-python/issues/4746, which I will do during the sprint.

**Comment by drammock** [comment]
ah, you're right @jona-sassenhagen.  I thought it was passing `unified=True` by default, but that must have been something else I was looking at yesterday.

**Comment by drammock** [comment]
@larsoner I'm convinced that in fact both of the plots above have messed up vmin/vmax. Compare the detail plots:

```
epochs.plot_image(picks='EEG 060') 
```
![Figure_3](https://user-images.githubusercontent.com/1810515/55432352-22ffc980-553f-11e9-9b3a-c9fd43cffce9.png)

versus clicking on that channel after
```
epochs.copy().pick_types(meg=False, eeg=True).plot_topo_image()
```
![Figure_5](https://user-images.githubusercontent.com/1810515/55432395-41fe5b80-553f-11e9-852b-e1ca90d54e48.png)

versus clicking on that channel after 
```
epochs.plot_topo_image(layout=eeg_layout)
```
![Figure_4](https://user-images.githubusercontent.com/1810515/55432420-4c205a00-553f-11e9-86fe-1ba249c4181d.png)

Still working out how to correct it.

**Comment by jona-sassenhagen** [comment]
I remember fixing a lot of code in epochs.plot_image to get the vlims right. Maybe check there.

Or I could indeed try to hook this up to _plot_masked_image at the sprint, so it could simply share that vlim functionality.

**Comment by drammock** [comment]
I'm gonna punt on this one until the sprint, I think. I put in a draft PR for what I think should be happening, but the resulting plots don't look right (too much of the signal lands near zero => images are mostly grey/white).  I also considered an approach using `np.quantile` to set vmin/vmax at the (0.01, 0.99) quantiles to pull some color into the middle range... maybe worth exploring?

**Comment by mmagnuski** [comment]
I've had this problem too some time ago, but now I rarely use `plot_topo_image`.

**Comment by jona-sassenhagen** [comment]
Mayyyyybe with #6186 in we can use _set_image_lims_and_scale for this.
