### ISSUE TITLE
[ENH] Support StringIO as a valid input

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-python#6156]
Currently working implementing some of the core functionality of mne-python into Pyodide (example [here](https://definitely-staging.iodide.io/notebooks/19/)). I noticed that we do not support StringIO in our readers. When the browser fetches data within the Python implementation, files are brought in as StringIO, which has the same functionality of a reading a file.

The user would still need to use the appropriate reader for the file format.

**Comment by larsoner** [comment]
This is essentially a dup of https://github.com/mne-tools/mne-python/issues/5867, let's discuss there.
