### ISSUE TITLE
MAINT: Beamformer simulation study

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#6159]
To be filled in by @wmvanvliet (turning project stub into issue).

**Comment by wmvanvliet** [comment]
The beamformer code is getting more powerful with every PR we push. However, this comes at the cost of accumulating parameters at a rapid pace. We need to find out which configurations work well and which do not. During the sprint, we're going to design and execute this study.

The study will be performed both on [phantom data](https://martinos.org/mne/stable/auto_tutorials/plot_brainstorm_phantom_elekta.html?highlight=phantom) and simulated data.

My idea right now is to test the LCMV and DICS beamformers with a huge grid of all possible parameter permutations and compute the performance on the phantom and simulated dataset in terms of:

 - Location of peak source activity versus true source origin
 - Field spread
 - Depth bias
 - Orientation bias

And use [multi objective optimization](https://en.wikipedia.org/wiki/Multi-objective_optimization to map out optimal configurations.

**Comment by britta-wstnr** [comment]
Let's add a comparison to FieldTrip to the list, happy to work on that one.

**Comment by wmvanvliet** [comment]
We're working in a separate repo for this: https://github.com/wmvanvliet/beamformer_simulation

**Comment by larsoner** [comment]
Done by @wmvanvliet, the conclusions led to updating some other beamformer issues for further actions
