### ISSUE TITLE
no way to read saved ica fif files

### ISSUE THREAD

**Issue by AleDallavecchia** [mne-tools/mne-python#6162]
There is the ability to save an ica solution, but no way to read it. The previous version of MNE had this same functionality that somehow got lost in this one.

**Comment by cbrnr** [comment]
The functionality is still there: https://martinos.org/mne/stable/generated/mne.preprocessing.read_ica.html

Can you try again and if it still doesn't work please let us know what you tried.

**Comment by AleDallavecchia** [comment]
I found the solution. Had to change how I called it.
previously: mne.read_ica(fname) to mne.preprocessing.read_ica(fname)

Sorry and thank you!

**Comment by AleDallavecchia** [comment]
I found the solution. Had to change how I called it.
previously: mne.read_ica(fname) to mne.preprocessing.read_ica(fname)

Sorry and thank you!
