### ISSUE TITLE
ENH :  speed up mixed_norm solvers with BLAS

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#6164]
for @QB3

**Comment by jona-sassenhagen** [comment]
@larsoner could Cupy also help hear?

**Comment by larsoner** [comment]
Depends on where the slowdowns are, which I'm not sure about. Can discuss this week

**Comment by agramfort** [comment]
I doubt about cupy as the solver requires many for loops over the sources

**Comment by larsoner** [comment]
Fixed by #6220
