### ISSUE TITLE
ENH: better automatic plot titles in plot_compare_evokeds

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#6165]
```py
plot_compare_evokeds(list_of_evokeds, picks='grad')
```
yields
`RuntimeWarning: More than 6 channels, truncating title ...`

Two suggested enhancements:

1. if `picks` is one of the standard types (`eeg`, `mag`, `grad`...) then the title should reflect the channel type, rather than trying to list all channel names
2. if specific channels are requested, the truncation should happen with an info message printed to the terminal, not a `RuntimeWarning` (admittedly subjective, but I think a warning seems too strong for a "we truncated your plot title" message)

**Comment by drammock** [comment]
I can take this on at the sprint; cc @jona-sassenhagen because of possible interaction with #4746

**Comment by jona-sassenhagen** [comment]
Agreed!

I think it's fairly independent and I agree with your judgements though. But we will talk about all this at the sprint anyways.
