### ISSUE TITLE
ENH: show GFP by default in plot_compare_evokeds if picks is a channel type

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#6166]
`plot_compare_evokeds(..., picks=None, gfp=False)` (which are the defaults) gives GFP plots for each sensor type, but if `picks='grad'` (or `mag` or `eeg`) it gives a simple average.  To me it seems more consistent to use GFP if `picks` is a channel type. This would require changing the default `gfp=False` to `gfp=None` --- otherwise, there would be no way for users to force the simple average if that's what they wanted.

Note that currently, if a user wants separate plots for all channel types and also wants a simple average rather than GFP, they cannot get it without calling the function multiple times (once for each channel type), since `picks=None` overrides `gfp=False`.  The above-proposed change would make it possible to get that via `plot_compare_evokeds(..., picks=None, gfp=False)`

**Comment by agramfort** [comment]
+1

>

**Comment by jona-sassenhagen** [comment]
Why not. I probably did it this way cause I'm not used to MEG.
