### ISSUE TITLE
plot_compare_evokeds zooms out of axes

### ISSUE THREAD

**Issue by stfnrpplngr** [mne-tools/mne-python#6178]
@drammock 
Using `mne.viz.plot_compare_evokeds` has plotting problems when using zoom. The lines are plotted outside of figure axes.

Default:
![plot_compare_evokeds_default](https://user-images.githubusercontent.com/20129752/56501386-e0faef80-650e-11e9-96f2-b767d8e9a991.png)

Zoom:
![plot_compare_evokeds_zoomedin](https://user-images.githubusercontent.com/20129752/56501396-ea845780-650e-11e9-89e3-7de287419b78.png)

Here, I use some random data:
```Python
import numpy as np
import mne

rng = np.random.RandomState(0)
n_epochs, n_channels, n_times = 50, 10, 20
sfreq = 1000.
data = rng.randn(n_epochs, n_channels, n_times)
events = np.array([np.arange(n_epochs), [0] * n_epochs, np.ones([n_epochs], dtype=np.int)]).T
info = mne.create_info(n_channels, sfreq, 'eeg')
epochs = mne.EpochsArray(data, info, events)

mne.viz.plot_compare_evokeds([epochs[:n_epochs//2].average(), epochs[n_epochs//2:].average()], picks=[0])
```

**Comment by jona-sassenhagen** [comment]
I discussed with @stfnrpplngr that I think it should be very low priority to make this work as is. I would prefer if we wrote a different, more appropriate callback for click and drag here. One simple option would be plotting a copy of the cropped evokeds objects (cropped to the time interval selected by the user). Another would be to show bar plots of the mean values in the dragged window.

**Comment by drammock** [comment]
I thought that the zooming was default matplotlib zooming, not something we wrote. If what we currently do isn't compatible with mpl, I'm inclined to try to fix it before adding a new callback. Let's discuss tomorrow morning.

**Comment by drammock** [comment]
After several long discussions, @agramfort @jona-sassenhagen and @drammock agree that we are closing this as `[won't fix]`.  Having beautiful defaults *and* elegant cooperation with the matplotlib GUI interface is too difficult to maintain.  Sorry :(
