### ISSUE TITLE
DOC ENH: better setup instructions for new contributors

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#6179]
Currently there is some info in [the contributing page](https://mne-tools.github.io/dev/contributing.html#id1) and some other info in [the advanced setup page of the install docs](https://mne-tools.github.io/dev/advanced_setup.html#using-the-development-version-of-mne-python-latest-master) about how to set up your system as an MNE developer.  This info should only be in one place.  Also, the info on [using GitHub to set up a pull request](http://martinos.org/mne/stable/configure_git.html#using-github) should also probably be incorporated in the same place.

@jasmainak suggests we make a `CONTRIBUTING.rst` file with (more detailed) info on system setup, and use the sphinx `include::` directive to paste that file into one of the documentation pages.

@drammock has a bash script for system setup; parts of that could be added.

Questions:

1. how much content should go in `CONTRIBUTING.rst`?  (i.e., just the code to set up your dev environment?  basically all of the current contributor's guide? something in between?)

2. where in the docs should it be included?  in the contributing guidelines page, or in the advanced installation docs?

cc @massich

**Comment by massich** [comment]
Apparently, we hit the issue where the documentation on how to interact with the repo itself gets duplicated between repos, outdated, etc.. 

cc: @emdupre

**Comment by emdupre** [comment]
Adding a .github repository to the org might help, here !

https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/
