### ISSUE TITLE
ENH?: more sophisticated SSP selection

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#618]
Now that we have improved internals for SSP management it occurred to me that we could improve SSP activation / deactivation a dict argument / keyword arguments. This would allow to activate the desired number vectors per kind while allowing to keep as many vectors as available in info['projs'].
Something like e.g. 

`evoked.apply_proj(n_room=2, n_ecg=1, n_eog=1)`

 Currently one has to assemble a list / replace the entire list to make selections. Opinions?

**Comment by Eric89GXL** [comment]
@dengemann this one's 2.5 years old, do you still want/need it, or can we close?
