### ISSUE TITLE
Development environment installation

### ISSUE THREAD

**Issue by ikojcic** [mne-tools/mne-python#6180]
I was following the contributing guide and it wasn't clear how to have simultaneous mne (stable, user) environment and mne-dev environment in which I could make contributions.
I installed MNE (stable, user version) using installation guidelines:
```sh
 curl --remote-name https://raw.githubusercontent.com/mne-tools/mne-python/master/environment.yml
 conda env create -f environment.yml
 conda activate mne
```
Then, when I followed the contributing guide which says:
``` sh
 cd <path_to_where_you_want_mne-python_source_code_installed>
 git clone git://github.com/mne-tools/mne-python.git
 cd mne-python
 python setup.py develop
```
So both environments had the same name (mne), instead of e.g. mne and mne-dev.
To fix it, I had to:
- copy the .yml file (and rename it)
- change the the environment name in the .yml file from mne to mne-dev

**Comment by massich** [comment]
Ok, this seems to be a dubplicate of #6179
