### ISSUE TITLE
MAINT: Beamformer comparisons

### ISSUE THREAD

**Issue by britta-wstnr** [mne-tools/mne-python#6183]
As discussed with @larsoner, we will add a test for LCMV and DICS to test against FieldTrip (i.e., against saved FieldTrip output).

**Comment by britta-wstnr** [comment]
Steps:
- get ``.m`` file to run _unit-gain_, _unit-array_, and _unit-noise-gain_ beamformer in FieldTrip
- save FieldTrip output as ``.stc`` files
- use these files to test MNE-Python output against in new test

**Comment by larsoner** [comment]
Sounds good to me
