### ISSUE TITLE
Permutation test on channels connectivity

### ISSUE THREAD

**Issue by AmirDJV** [mne-tools/mne-python#6203]
I’m running a permutation test on channels connectivity between two groups and I encountered a few issues. 

**Jupyter notebook can be found [here](https://github.com/AmirDJV/EEG_question/blob/master/questions_on_permutation_cluster_test_250419.ipynb) and data files for the notebook [here]( https://www.dropbox.com/sh/ik6hmp0b09c3l8f/AABsZ0uSp5AR2GK70XUGk4Vta?dl=0).**

Each “cap”/file in my data actually reflects data which I collected from two caps simultaneously (hyper-scanning). My data is arranged these way because I’m interested in the relationship between the participants and less within the participants (e.g. the relationship between the temporal area in participant1 to frontal area in participant2). Thus, I have 62 channels were channels 0-30 are for participant1 and 31-62 are for participant2.

I calculated the connectivity between the channels like this:
```
freqbands = {'alpha': (8, 14), 'beta': (14, 30), 'gamma': (30, 60)}
fmin = np.array([f for f, _ in freqbands.values()])
fmax = np.array([f for _, f in freqbands.values()])
    
# perform the connectivity analysis:
picks = mne.pick_types(combinedBaseline.info, eeg=True)
connection_pairs = mne.connectivity.seed_target_indices(picks, picks)
    
#Connectivity for baseline
connB, freqsB, timesB, n_epochsB, n_tapersB = mne.connectivity.spectral_connectivity(
        combinedBaseline, method='pli', mode='multitaper', fmin=fmin, fmax=fmax, faverage=True,
        indices=connection_pairs, n_jobs=2, verbose=False)
```

**I would deeply appreciate your help with:**

1. I'm trying to build clusters of close sensors within each cap and between caps. For example, Fp-0 (Fp1 in participant 1) should be tested with Fp1-1 (Fp1 in participant 2).

In order to do that, I shifted the channels of the second cap by 0.00001 and created a sparse matrix using the following code: 

```
A = find_ch_connectivity(combinedBaseline.info, ch_type="eeg")
metaconn = np.zeros((vectconn.shape[-1], vectconn.shape[-1]))
for ne1, (e11,e12) in tqdm(enumerate(electrodes)):
    for ne2, (e21,e22) in enumerate(electrodes):
        metaconn[ne1, ne2] = (((A[0][e11,e21]) and (A[0][e12,e22])) or 
                              ((A[0][e11,e22]) and (A[0][e12,e21])) or
                              ((A[0][e11,e21]) and (e12 == e22)) or 
                              ((A[0][e12,e21]) and (e11 == e22)) or
                              ((A[0][e11,e22]) and (e12 == e21)) or 
                              ((A[0][e12,e22]) and (e11 == e21)))
```
Is there a better way to do that?

2. While running the permutation test, I get errors about using 1 tail instead of 2 tailed, in addition to other errors, why? 

The code I used for permutation: 

```
Fobs, clusters, cluster_pv, H0 = mne.stats.permutation_cluster_test(X=[romantic, strangers],
                                                                        tail=0,
                                                                        n_permutations = 1000,
                                                                        seed = 42, 
                                                                        step_down_p = 0.05,
                                                                        connectivity = lil_matrix(metaconn), 
                                                                        check_disjoint = False) 
```

Thank you for you help!

**Comment by mmagnuski** [comment]
I think your question may be a better fit for the discussion emailing list, you could get more responses there - github is mostly for bugs and feautre requests not so much "how to" questions.

> In order to do that, I shifted the channels of the second cap by 0.00001 and created a sparse matrix using the following code:

Why do you need to shift channels?
I don't understand how you exactly build your adjacency (you use variables that are not defined within the provided code), but could we use a simpler minimal example maybe? For example lets assume you have channels a, b and c and the adjacency between them is `a - b - c` so `[[0, 1, 0], [1, 0, 1], [0, 1, 0]]`. The first participant has `a1, b1, c1` channels and the second one `a2, b2, c2`. Lets say your connectivity (not adjacency) contains information in `frequencies x channel_pairs` matrix where `channel_pairs` dimension is for example `['{}-{}'.format(ch1, ch2) for ch1 in ['a1', b1', c1'] for ch2 in ['a2', 'b2', 'c2']]`. Are we on the same page here?

> For example, Fp-0 (Fp1 in participant 1) should be tested with Fp1-1 (Fp1 in participant 2).

I understand you have connectivity between sensors of two participants so you don't have single channels but channel pairs as one of you dimensions. Then what you want is to have pair `a1-x2` (where x is just whatever to simplify) to be adjacent to pair `b1-x2` but not `c1-x2` (and the same for the channel on "the other side"). If your question is whether you have to build your adjacency by hand in such case then yes, at least that's what I would do in such situation.

> While running the permutation test, I get errors about using 1 tail instead of 2 tailed, in addition to other errors, why?

The default stat_fun is F test as far as I am aware so it is one-tailed. But I am not sure if I understand your problem exactly unless you paste the whole error traceback.
