### ISSUE TITLE
extra "misc" row in raw.plot(butterfly=True)

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#6219]
hey @stfnrpplngr, since you're working on butterfly mode, can you confirm this?

```py
import os
import mne
sample_data_folder = mne.datasets.sample.data_path()
sample_data_raw_file = os.path.join(sample_data_folder, 'MEG', 'sample',
                                    'sample_audvis_raw.fif')
raw = mne.io.read_raw_fif(sample_data_raw_file, preload=False, verbose=False)
raw.crop(10).load_data()
raw.pick_types(meg=False, eeg=True).plot(butterfly=True)
```
I'm seeing an extra row for "misc" channels even though I've done `pick_types`

cc #6210

**Comment by larsoner** [comment]
FWIW the epochs butterfly mode and raw butterfly mode use slightly different code paths, so this might not be trivial to fix in #6210 :(

**Comment by drammock** [comment]
OK, I'll self-assign then. @stfnrpplngr if you want to take it on before I get around to it, LMK.

**Comment by stfnrpplngr** [comment]
Applying my changes in epochs.py to raw.py will probably solve the problem. I will do that after finishing the refactoring of epochs.py.
