### ISSUE TITLE
Autoscale is not working properly in epochs.plot()

### ISSUE THREAD

**Issue by stfnrpplngr** [mne-tools/mne-python#6226]
#### Describe the bug
Autoscale does not appear to work properly. It seems that scales are not calculated channel-type-wise. Probably related to https://github.com/mne-tools/mne-python/issues/5760.

#### Code to reproduce
```Python
import os.path as op
import mne

data_path = op.join(mne.datasets.sample.data_path(), 'MEG', 'sample')
raw = mne.io.read_raw_fif(
    op.join(data_path, 'sample_audvis_raw.fif'), preload=True)
raw.pick_types(eeg=True, meg=True)
raw.load_data().filter(None, 9, fir_design='firwin')
raw.set_eeg_reference('average', projection=True)  # set EEG average reference
event_id = {'auditory/left': 1, 'auditory/right': 2, 'visual/left': 3,
            'visual/right': 4, 'smiley': 5, 'button': 32}
events = mne.read_events(op.join(data_path, 'sample_audvis_raw-eve.fif'))
epochs = mne.Epochs(raw, events, event_id=event_id, tmin=-0.2, tmax=.5)

epochs.plot(scalings='auto')
```

#### Expected results
`epochs.plot(scalings=None)`
![autoscale_issue_scalingNone](https://user-images.githubusercontent.com/20129752/56743436-d8a4ed80-6776-11e9-9a15-3f9558bc5122.JPG)

#### Actual results
`epochs.plot(scalings='auto')`
![autoscale_issue](https://user-images.githubusercontent.com/20129752/56743499-f5d9bc00-6776-11e9-952b-0bfa60a4d200.JPG)

#### Additional information
Platform:      Windows-10-10.0.16299-SP0
Python:        3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
Executable:    C:\Continuum\anaconda3\pythonw.exe
CPU:           Intel64 Family 6 Model 142 Stepping 10, GenuineIntel: 8 cores
Memory:        15.9 GB

mne:           0.18.dev0
numpy:         1.16.2 {blas=mkl_rt, lapack=mkl_rt}
scipy:         1.2.1
matplotlib:    3.0.3 {backend=Qt5Agg}

sklearn:       0.20.3
nibabel:       Not found
mayavi:        Not found
cupy:          Not found
pandas:        0.24.2
dipy:          Not found

**Comment by agramfort** [comment]
the "auto" explanation is not clear here
https://martinos.org/mne/stable/generated/mne.Epochs.html#mne.Epochs.plot
I agree that it should be done per channel type.

>

**Comment by stfnrpplngr** [comment]
Just checked it. `mne.viz.utils._compute_scalings()` actually is doing the scaling per channel type. The bug seems to be somewhere else.

**Comment by stfnrpplngr** [comment]
PR #6255 should solve the issue. 

![ausoscale_issue_fixed](https://user-images.githubusercontent.com/20129752/56956597-f68e9b80-6b44-11e9-9dde-1c92e2765057.JPG)
