### ISSUE TITLE
ENH: speed up ica.plot_properties

### ISSUE THREAD

**Issue by mmagnuski** [mne-tools/mne-python#6268]
I currently have to wait some time after clicking a component in `ica.plot_components` window and the time seems to be mostly from waiting for the multitaper psd estimation to complete. I think that we should use something much simpler like welch or even fft as the default. The plotted spectrum is for informational reasons, not for analysis. I can compare timings on one of my datasets.

**Comment by larsoner** [comment]
Sounds good to me

**Comment by cbrnr** [comment]
OK, I would be interested in the timings if this is really the bottleneck.

**Comment by jona-sassenhagen** [comment]
Sure, sounds good.

**Comment by jona-sassenhagen** [comment]
While you're there, generalise plot_properties to channels please :D

**Comment by agramfort** [comment]
+1 for doing a comparison

>

**Comment by mmagnuski** [comment]
I profiled plot_properties and it seems I was wrong: a lot of time (> 2 s in this case) is spent in bootstrap CI computation:
![image](https://user-images.githubusercontent.com/8452354/57179607-d3832500-6e7f-11e9-9397-beed0d81a8ce.png)
We should consider switching to analytic (and possibly one-sided to better represent skewed distributions).
BTW - 7 seconds here is an exaggeration, 2 seconds were spent in plt_show before I closed the figure.

**Comment by mmagnuski** [comment]
but I still think multitaper should be changed to somthing lighter (welch or fft), people with less experience with multitapersing could be mistaken by the fatter, more square-like peaks that can sometimes arise due to frequency smoothing.

**Comment by mmagnuski** [comment]
@jona-sassenhagen I can take a stab at that if you insist. :)

**Comment by jona-sassenhagen** [comment]
>I profiled plot_properties and it seems I was wrong: a lot of time (> 2 s in this case) is spent in bootstrap CI computation:

Uh oh, it's my fault :)

For the tests, we can pass a different ci function to plot_compare_evokeds here. You wanna do that, or should I?

>@jona-sassenhagen I can take a stab at that (generalizing to channels) if you insist. :)

I insist.

**Comment by mmagnuski** [comment]
> Uh oh, it's my fault :)

This is what you meant in #6250, right?

> For the tests, we can pass a different ci function to plot_compare_evokeds here. You wanna do that, or should I?

I can test later today.

> We can also default to a different function for the default for plot_properties.

That could be useful.

> I insist.

😅

**Comment by jona-sassenhagen** [comment]
>This is what you meant in #6250, right?

It is connected to that, yes. Another reason for speeding up epochs iteration.

Maybe it would also make sense to see if we can speed up the bootstrap ci function.

**Comment by jona-sassenhagen** [comment]
@mmagnuski I suggest to, in `plot_ica_properties`, add a `ts_args` param and default the time series (plot_compare_evokeds) internally to your CI function, unless overwritten to a `ci` param in `ts_args`.

**Comment by jona-sassenhagen** [comment]
I can do it too.

**Comment by mmagnuski** [comment]
@jona-sassenhagen Sure, If you have a plan, go for it. :)
