### ISSUE TITLE
`raw.plot` for ICA sources scalings are bad

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#6271]
`ica.get_sources(raw).plot()` yields a largely useless plot, presumably because ICA activities are rescaled by the defaults for the channel type. Would it make sense to allow this to work by default (without the user passing scalings manually)?

**Comment by agramfort** [comment]
as sources get returned as MISC channels it's a matter of setting a good
default fo misc channels.

my 2c

>

**Comment by jona-sassenhagen** [comment]
Maybe @stfnrpplngr has an idea?

**Comment by larsoner** [comment]
Maybe we should always by default auto-scale `misc` channel types in `viz` plotting. By definition we don't have an idea of what the scales should be, so auto-scaling them makes sense.

**Comment by agramfort** [comment]
that would be fine with me.

>

**Comment by mmagnuski** [comment]
+1 to autoscaling misc, had some issues with these in the past.
