### ISSUE TITLE
Recording EOG using 64 channel Hydrocel Geodesic Sensor Net

### ISSUE THREAD

**Issue by titoghose** [mne-tools/mne-python#6277]
My study revolves around ERP detection and P300 in particular. 

The net I have does not have EOG electrodes. The placement is according to the 10-20 system. I was thinking of removing some electrodes and replacing them in the EOG locations. 

I have 2 questions:
1. Which electrodes should I remove and where should I place them for EOG recording. 
2. Will the removal of electrodes from these channels affect the source reconstruction in any way? If so, how can I deal with it?

Thanks

**Comment by agramfort** [comment]
Please don’t use the issue tracker to ask usage questions. Use the mailing list. Thanks
