### ISSUE TITLE
tiny bug in title of AverageTFR.plot()

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#6282]
Titles always seem to end up with a right-parentheses at the end. 

![Screenshot_2019-05-07_15-03-45](https://user-images.githubusercontent.com/1810515/57338336-6d91da00-70d9-11e9-8a2c-32283effa6af.png)

Happens also with `AverageTFR.plot_joint()`

![Screenshot_2019-05-07_15-03-09](https://user-images.githubusercontent.com/1810515/57338327-64087200-70d9-11e9-9759-a38bdc0d1687.png)

**Comment by jona-sassenhagen** [comment]
Ugh. This possibly also affects other functions. You can assign me too, I'm probably to blame.

**Comment by drammock** [comment]
cool, it will be a race to see who needs to procrastinate first!
