### ISSUE TITLE
RFC: Draft for the new release note v0.18

### ISSUE THREAD

**Issue by GuillaumeFavelier** [mne-tools/mne-python#6338]
I put together a release note, please feel free to comment on it (or edit).

--- 

Dear community!

We are very pleased to announce the new 0.18 release of MNE-Python (http://martinos.org/mne/stable/).

A few highlights
================

- Python 2 is no longer supported; MNE-Python now requires Python 3.5+
- New tutorials and examples on sleep stage classification, data simulation using subject's anatomy, how to use EEG montages on fsaverage
- New module to simulate SourceEstimates 
- Improved performance using CUDA, better copy management, better dispatching of the computation over the channels
- New fetchers for polysomnography (PSG) recordings from Physionet and fsaverage template
- Better support for source reconstruction with beamformers and other inverse models
- Improved UI and visualizations for topomaps, Raw and Epochs objects 
- Better support for Annotations
- Support to compute power envelope correlations on brain parcellation for rest data
- Better rendering of the coregistration 
- Added partial support for PyVista as a 3D backend that can replace mayavi
- Added support for Raw, Epochs and Evoked noise simulation
- Added new parcellation (448-labels subdivided aparc) and improve support including morphing of the labels
- Better support for the TFR objects

And we caught and fixed more than 50 bugs!

Notable API changes
===================

- Deprecation of `mne.realtime` module to become entire project in the MNE echosystem
- Deprecation of `mne.io.find_edf_events`, `raw.estimate_rank`
- Reading BDF and GDF files with `mne.io.read_raw_edf` is deprecated and replaced by `mne.io.read_raw_bdf` and `mne.io.read_raw_gdf`
- The signatures of `mne.preprocessing.ICA`, `mne.simulation.add_noise` and `mne.simulation.add_chpi` have changed
- Added overwrite parameter in `mne.Epochs.save` 
- `mne.minimum_norm.apply_inverse` now returns `mne.VolVectorSourceEstimate` when needed
- Annotations are now kept sorted by onset
- `peak_finder` should be imported as: `from mne.preprocessing import peak_finder`

For a full list of improvements and API changes see:
http://martinos.org/mne/stable/whats_new.html#version-0-18

To install the latest release the following command should do the job:

    $ pip install --upgrade mne

As usual, we welcome your bug reports, feature requests, critiques, and contributions.

Some links:
- https://github.com/mne-tools/mne-python (code + readme on how to install)
- http://martinos.org/mne/stable/ (full MNE documentation)

Follow us on Twitter for general news (https://twitter.com/mne_news)
and for a regular feed of merged PRs (https://twitter.com/mne_python).

Regards,
The MNE-Python developers

52 people made commits that contributed to this release (in alphabetical order):

* 	Achilleas Koutsou
* 	Alexander Kovrig
* 	Alexandre Gramfort
* 	Antoine Gauthier
* 	Britta Westner
* 	Bruno Nicenboim
* 	Burkhard Maess
* 	Chris Bailey
* 	Chris Holdgraf
* 	Christian Brodbeck
* 	Clemens Brunner
* 	Cristóbal Moënne-Loccoz
* 	Daniel McCloy
* 	David Haslacher
* 	Denis A. Engemann
* 	Dirk Gütlin
* 	Eric Larson
* 	Evgenii Kalenkovich
* 	Fede Raimondo
* 	Guillaume Favelier
* 	Hubert Banville
* 	Ivana Kojcic
* 	Jean-Remi King
* 	Jeff Hanna
* 	Joan Massich
* 	Johannes Kasper
* 	Jon Houck
* 	Jona Sassenhagen
* 	José C. García Alanis
* 	Jussi Nurminen
* 	Katarina Slama
* 	Keith Doelling
* 	Kostiantyn Maksymenko
* 	Larry Eisenman
* 	Legrand Nicolas
* 	Mainak Jas
* 	Marijn van Vliet
* 	Mikolaj Magnuski
* 	Nathalie Gayraud
* 	Nikolas Chalas
* 	Oleh Kozynets
* 	Quentin Bertrand
* 	Samuel Deslauriers-Gauthier
* 	Sebastián Castaño
* 	Simon Kern
* 	Stanislas Chambon
* 	Stefan Appelhoff
* 	Stefan Repplinger
* 	Steve Matindi
* 	Teon Brooks
* 	Thomas Donoghue
* 	Thomas Hartmann

**Comment by sappelhoff** [comment]
We could add the second twitter channel:

```Text
Follow us on Twitter for general news: https://twitter.com/mne_news
... and for for a regular overview of merged PRs: https://twitter.com/mne_python

```

**Comment by britta-wstnr** [comment]
Something like:
``Better support for source reconstruction with beamformers // the beamformer module and other inverse models`` ?
-- beamformers are inverse models, too, that does not get quite clear to me as it is now.

**Comment by massich** [comment]
is it better now?

**Comment by sappelhoff** [comment]
And we catched and fixed more than 50 bugs !! --> `caught`

**Comment by britta-wstnr** [comment]
@massich sounds better to me, thanks!

**Comment by britta-wstnr** [comment]
``Add*ed* overwrite parameter`` under API changes? The rest is all past tense.

**Comment by jasmainak** [comment]
> catched and fixed more than 50 bugs

a naive reader might assume that it means mne-python is full of bugs :p Maybe you want to phrase it a little differently?

**Comment by agramfort** [comment]
made a few edits. LGTM

**Comment by cbrnr** [comment]
I also made some minor edits (formatting). LGTM!

**Comment by larsoner** [comment]
We should probably cut a 0.18.1 with the `mne.realtime` deprecations included, and add it to the release notes here

**Comment by massich** [comment]
I propose to do bump to `0.18.1rc0` in `maint/0.18` and do a pre-release waiting to get in some earlier feedback.

I tried in `test.pypi.org` but I don't seem to be able to find my package.
```sh
~/code/mne-python maint/0.18*
(mne) ❯ python setup.py sdist                                     
running sdist
running egg_info
writing mne.egg-info/PKG-INFO
writing dependency_links to mne.egg-info/dependency_links.txt
writing requirements to mne.egg-info/requires.txt
writing top-level names to mne.egg-info/top_level.txt
reading manifest file 'mne.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'mne/datasets' under directory 'mne'
warning: no previously-included files matching '*' found under directory 'examples/MNE-sample-data'
warning: no previously-included files matching '*' found under directory 'examples/MNE-testing-data'
warning: no previously-included files matching '*' found under directory 'examples/MNE-spm-face'
warning: no previously-included files matching '*' found under directory 'examples/MNE-somato-data'
warning: no previously-included files found matching 'Makefile'
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '*.yml'
warning: no previously-included files found matching 'ignore_words.txt'
warning: no previously-included files found matching '.mailmap'
warning: no previously-included files matching '*' found under directory 'doc'
warning: no previously-included files matching '*' found under directory 'logo'
warning: no previously-included files found matching 'CODE_OF_CONDUCT.md'
warning: no previously-included files found matching '.github'
warning: no previously-included files found matching '.github/CONTRIBUTING.md'
warning: no previously-included files found matching '.github/ISSUE_TEMPLATE'
warning: no previously-included files found matching '.github/ISSUE_TEMPLATE/blank.md'
warning: no previously-included files found matching '.github/ISSUE_TEMPLATE/bug_report.md'
warning: no previously-included files found matching '.github/ISSUE_TEMPLATE/feature_request.md'
warning: no previously-included files found matching '.github/PULL_REQUEST_TEMPLATE.md'
warning: no previously-included files matching '*' found under directory 'mne/io/tests/data'
warning: no previously-included files matching '*' found under directory 'mne/io/bti/tests/data'
warning: no previously-included files matching '*' found under directory 'mne/io/edf/tests/data'
warning: no previously-included files matching '*' found under directory 'mne/io/kit/tests/data'
warning: no previously-included files matching '*' found under directory 'mne/io/brainvision/tests/data'
warning: no previously-included files matching '*' found under directory 'mne/io/egi/tests/data'
warning: no previously-included files matching '*' found under directory 'mne/io/nicolet/tests/data'
warning: no previously-included files matching '*' found under directory 'mne/preprocessing/tests/data'
writing manifest file 'mne.egg-info/SOURCES.txt'
running check
creating mne-0.18.1rc0
creating mne-0.18.1rc0/bin
creating mne-0.18.1rc0/examples
creating mne-0.18.1rc0/examples/connectivity
creating mne-0.18.1rc0/examples/datasets

       ..... TL;DR;  ...

Writing mne-0.18.1rc0/setup.cfg
Creating tar archive
removing 'mne-0.18.1rc0' (and everything under it)


~/code/mne-python maint/0.18* 32s
(mne) ❯ twine upload --repository-url https://test.pypi.org/legacy/ dist/mne-0.18.1rc0.tar.gz 
Enter your username: massich
Enter your password: 
Uploading distributions to https://test.pypi.org/legacy/
Uploading mne-0.18.1rc0.tar.gz
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 6.03M/6.03M [00:03<00:00, 1.73MB/s]

**Comment by massich** [comment]
It does not allow me to push it back, so it means is there. But I can't find it in test.pypi.org
