### ISSUE TITLE
make mne-realtime a standalone repo

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-python#6339]
As discussed at the sprint, I would like to make the `mne-realtime` standalone similar to `mne-bids`.
1. I am unable to transfer rights of the https://github.com/teonbrooks/mne-realtime to the `mne-tools` organization.
2. I would like some help getting the repo to work properly with CI. I followed the `mne-project-template` but there are a few things that I need a hand with.

This will likely not happen before the `0.18` cycle. Proper deprecation should be put in place to advise on the movement.

cc: @massich

**Comment by massich** [comment]
I thought that we removed that already. My fault. 

This is a blocker, we should avoid the deprecation cycle. Can you make a quick PR? I'll get it in.
