### ISSUE TITLE
evoked file with aspect_kind==105 causes a KeyError

### ISSUE THREAD

**Issue by jjnurminen** [mne-tools/mne-python#6359]
Dear mne,

a colleague gave me an evoked fiff file created with mne Matlab toolbox. When trying to load it in mne-python, the Evoked instance is created fine. However when trying to look at it, I get:

```
  File "C:\Users\hus20664877\projects\mne-python\mne\evoked.py", line 179, in __repr__
    s = "'%s' (%s, N=%s)" % (self.comment, _kind_swap[self.kind],

KeyError: 'unknown'
```

It looks like `self.kind` is 'unknown'. If that's not OK, It seems to me that the situation should be handled before `__repr__` is invoked. Further, why is `self.kind` limited to average or standard deviation? This file seems to have `aspect_kind` set to 105, which corresponds to FIFFV_ASPECT_SAMPLE.

**Comment by larsoner** [comment]
This is a bug, I'll see if it's easy to fix it.

> why is self.kind limited to average or standard deviation

These are the only kinds produced by MNE-Python, and (apparently) the only ones people have tried to read with MNE-Python so far. But we might as well add the remaining ones to the list:

https://github.com/mne-tools/fiff-constants/blob/a3feddb3011335586d50bc40d1c4e36cea20913f/DictionaryTypes.txt#L347-L360
