### ISSUE TITLE
DOC: restore example deprecation code in contrib guide

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#6410]
this was inadvertantly lost in the contrib guide overhaul.

**Comment by massich** [comment]
yes and I realized that when ever I do something with deprecations I have it open:
mne-tools.github.io/0.17/contributing.html#deprecating

Maybe we could collect other patterns that we do in a FAQ. A possible candidate would be `@fill_doc`

**Comment by massich** [comment]
check this one out http://www.scikit-yb.org/en/latest/contributing.html
