### ISSUE TITLE
Repeated measures anova for unbalanced design with permutations test 

### ISSUE THREAD

**Issue by AmirDJV** [mne-tools/mne-python#6419]
I'm following the [Repeated measures ANOVA on source data with spatio-temporal clustering ](https://martinos.org/mne/stable/auto_tutorials/stats-source-space/plot_stats_cluster_spatio_temporal_repeated_measures_anova.html#sphx-glr-auto-tutorials-stats-source-space-plot-stats-cluster-spatio-temporal-repeated-measures-anova-py) tutorial with my own data. 

The solution to calculate permutations test for between  (visual vs auditory) - within (left vs right) repeated measures anova was to use the `stat_fun` argument with the [mne.stats.f_mway_rm](https://martinos.org/mne/stable/generated/mne.stats.f_mway_rm.html) function.  

My issue is that [mne.stats.f_mway_rm](https://martinos.org/mne/stable/generated/mne.stats.f_mway_rm.html) function only support fully balanced designs. Is there a way to support unbalanced designs? 

Thank you! :)

**Comment by jona-sassenhagen** [comment]
@dengemann

**Comment by dengemann** [comment]
No this is unfortunately not easy to do. The current implementation does not support mixed within-between models.

**Comment by AmirDJV** [comment]
Thank you :) Are you thinking about implementing it? and can you please explain why it is problematic?

**Comment by larsoner** [comment]
Closing as a dup of #4859
