### ISSUE TITLE
Why does MNE use adaptive z-scoring in find_bads_eog?

### ISSUE THREAD

**Issue by matthewhang** [mne-tools/mne-python#6445]
According to the documentation of find_bads_eog
> Detection is based on Pearson correlation between the filtered data and the filtered EOG channel. Thresholding is based on adaptive z-scoring.

Are there any experiments/papers demonstrating the benefits of this? or is it just a traditional practice? (which i believe it isnt as there are many papers still using visual inspection), or is it just a practical recommendation without detailed evidence?

Thank you very much. I am concerning if such computation would be too conservative.

**Comment by dengemann** [comment]
It’s original MNE cuisine :) something that turned out to work. We implemented it based on our own intuition and tested it on multiple datasets. We could add other options or change the default if we can convince ourselves of an alternative.

**Comment by matthewhang** [comment]
> It’s original MNE cuisine :) something that turned out to work. We implemented it based on our own intuition and tested it on multiple datasets. We could add other options or change the default if we can convince ourselves of an alternative.
> […](#)
> On 11 Jun 2019, at 08:46, matthewhang ***@***.***> wrote: According to the documentation of find_bads_eog Detection is based on Pearson correlation between the filtered data and the filtered EOG channel. Thresholding is based on adaptive z-scoring. Are there any experiments/papers demonstrating the benefits of this? or is it just a traditional practice? (which i believe it isnt as there are many papers still using visual inspection), or is it just a practical recommendation without detailed evidence? Thank you very much. I am concerning if such computation would be too conservative. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

thank you for the answer! I was just testing around the options!
