### ISSUE TITLE
ENH: migrate http://mne-tools.github.io to http://mne.tools

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#6459]
@mne-tools/contributors I bought last week the domain name http://mne.tools

what do you think about migrating http://mne-tools.github.io to http://mne.tools ?
it just means adding a CNAME to github repo. Nothing should be changed regarding how we deploy website etc.

**Comment by larsoner** [comment]
Sounds good

**Comment by teonbrooks** [comment]
i like it too

**Comment by drammock** [comment]
Cool! The old URL will redirect?

**Comment by agramfort** [comment]
yes It will redirect

>

**Comment by massich** [comment]
awesome !

**Comment by cbrnr** [comment]
Closing because this has been working for a while.
