### ISSUE TITLE
RFC, DOC, STY: update website fonts?

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#6485]
I'm often bothered by the font mismatch between the API links and the surrounding text. Here's a screenshot:

![mne-font-heights](https://user-images.githubusercontent.com/1810515/60042873-3072ae80-966b-11e9-9ad1-f887d2f64916.png)

The height difference is most jarring, but there are also edge-spacing issues, so that a line that starts with an API link will look slightly indented.  The proposal here is to switch to using [Source Code Pro](https://github.com/adobe-fonts/source-code-pro) for API links and code blocks, and [Source Sans Pro](https://github.com/adobe-fonts/source-sans-pro) for the main text. Here's a mock-up:

![mne-font-heights2](https://user-images.githubusercontent.com/1810515/60043446-8f84f300-966c-11e9-955e-4977dc4c0b12.png)

The [Source Code](https://adobe-fonts.github.io/source-code-pro/) and [Source Sans](https://adobe-fonts.github.io/source-sans-pro/) fonts are both available as WOFF or WOFF2 format, come in several weights, and the monospace has an italic version, so there's some flexibility in fine-tuning the weights (e.g., could use medium or semibold instead of bold for the API links if we wanted to).

**Comment by agramfort** [comment]
no objection

>

**Comment by larsoner** [comment]
Sounds good
