### ISSUE TITLE
import dataset in mne

### ISSUE THREAD

**Issue by Hamidbme** [mne-tools/mne-python#6508]
Hi,

I need to import a dataset for use in mne-python, but can not find a way to do so.The dataset was obtained from the paper referenced below.
moabb supported this dataset an I used below code to import but I had error.I attach the picture of error for you to see.

Thanks fo help!

paper:

Jaeyoung Shin, Alexander von Lühmann, Benjamin Blankertz, Do-Won Kim, Han-Jeong Hwang and Klaus-Robert Müller, "Open Access Dataset for EEG+NIRS Single-Trial Classification," IEEE Trans. Neural Syst. Rehabil. Eng., online published.

The code that I used :

import moabb
import mne
import os
import zipfile
from moabb.datasets import Shin2017A
dataset = Shin2017A()
data = dataset.get_data(subjects=[1])

![error](https://user-images.githubusercontent.com/51126085/60300089-710c4980-9943-11e9-8f0d-2a92854e06d4.png)

**Comment by drammock** [comment]
I have tried this, and it succeeds without error:

```python
import moabb
from moabb.datasets import Shin2017A
dataset = Shin2017A()
data = dataset.get_data(subjects=[1])
data
# {1: {'session_0': {'run_0': <RawArray  |  None, n_channels x n_times : 33 x 120436 (602.2 sec), ~30.4 MB, data loaded>}, 'session_2': {'run_0': <RawArray  |  None, n_channels x n_times : 33 x 119236 (596.2 sec), ~30.1 MB, data loaded>}, 'session_4': {'run_0': <RawArray  |  None, n_channels x n_times : 33 x 120851 (604.2 sec), ~30.5 MB, data loaded>}}}
```
It seems like maybe your data has been corrupted...  perhaps you should delete and re-download the EEG-fNIRS dataset?

As a side note, this error should probably have been reported to MOABB, not to MNE-Python.  Other than `import mne` there are no MNE-Python commands being used in your example script (and mine succeeds without even importing mne), and the traceback is entirely within the `moabb` and `zipfile` namespaces (look at the file paths in each line of the traceback; whatever comes after `lib` or `lib/site-packages` is a clue to where the error is happening). I realize that `moabb` is using `mne` under the hood, but it doesn't appear to be `mne` code that is failing in this case.
