### ISSUE TITLE
Incomplete PyVista 3d backend

### ISSUE THREAD

**Issue by GuillaumeFavelier** [mne-tools/mne-python#6518]
As suggested in this [comment](https://github.com/mne-tools/mne-python/pull/6464#issuecomment-504440519), we keep track of the primitives not yet implemented in the PyVista 3d backend:

- [x] `tube()`
- [x] `text3d()`
- [x] `scalarbar()`
- [x] `_set_3d_view()`
- [x] `_set_3d_title()`

**Comment by GuillaumeFavelier** [comment]
Showing the advancement with the example `examples/connectivity/plot_sensor_connectivity.py` :

Mayavi | PyVista
----------|-----------
![image](https://user-images.githubusercontent.com/18143289/60582994-26972c80-9d8a-11e9-95cb-4892a1d8f715.png) | ![image](https://user-images.githubusercontent.com/18143289/60583354-fe5bfd80-9d8a-11e9-96ab-a655645d650d.png)

**Comment by agramfort** [comment]
Next is color bar then ?

**Comment by GuillaumeFavelier** [comment]
yes indeed!

**Comment by GuillaumeFavelier** [comment]
In order to add `_set_3d_view()` and `_set_3d_title()` in the pyvista 3d backend, I have to use the `BackgroundPlotter` instead of the regular `Plotter` which depends on `PyQt5`. 
I need to thoroughly investigate the impact of this migration on the `_Brain` object, the interactivity inside a jupyter

**Comment by agramfort** [comment]
let me know if you need to discuss

>
