### ISSUE TITLE
BUG: epochs.plot_drop_log() wrong behavior

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#6579]
`epochs.plot_drop_log()` returns a figure saying "no drops" in cases where percentage of drops is lower than `threshold` parameter. There are two problems with this:

1. it is inaccurate (there were drops)
2. it is wrong behavior (according to the docs, `threshold` > percent dropped is supposed to *suppress* the figure, but it still gets generated / returned)

`epochs.plot_drop_log()`

![drop_log_default](https://user-images.githubusercontent.com/1810515/61320806-b12e5180-a7b6-11e9-9992-a78617cb487f.png)

`epochs.plot_drop_log(threshold=5)`

![drop_log_threshold_5](https://user-images.githubusercontent.com/1810515/61320825-c0150400-a7b6-11e9-9f4c-33e9f6d0c6a8.png)

**Comment by drammock** [comment]
while I'm at it, I'll center the bars over the ticks, and make the bars slightly darker so they're more visible on low-brightness laptop screens (unless someone objects)

**Comment by agramfort** [comment]
+100

**Comment by larsoner** [comment]
Sounds good
