### ISSUE TITLE
ICA.plot_sources(epoch) scaling (?) is wrong

### ISSUE THREAD

**Issue by jshanna100** [mne-tools/mne-python#6615]
The plot_sources method for ICA only produces a wall of blue when the Inst is an Epoch. This occurs even with a fresh conda environment with the stable .18 version. I assume this is a scaling issue, but trying to manually scale it down hasn't gotten me anywhere.

You should be able to reproduce this as follows:
```Python
import mne
path =  mne.datasets.sample.data_path()
raw = mne.io.Raw(path + '/MEG/sample/sample_audvis_raw.fif')
events = mne.read_events(path+"/MEG/sample/sample_audvis_raw-eve.fif")
epo = mne.Epochs(raw,events)
ica = mne.preprocessing.ICA(n_components=100)
ica.fit(epo)
ica.plot_sources(epo)
```

**Comment by agramfort** [comment]
I confirm the bug. Can someone have a look?

>

**Comment by larsoner** [comment]
Probably an auto-scaling problem. I can take a look
