### ISSUE TITLE
[Feature request]: add to_data_frame() function to EpochsTFR

### ISSUE THREAD

**Issue by justinf2** [mne-tools/mne-python#6619]
I would be great to be able to generate a pandas data frame from a EpochsTFR object like one can from an Epochs object, but with an extra index value for the frequencies.

**Comment by agramfort** [comment]
can you share a code snippet that would do this or even send a PR? how
would indexing work as data are naturally 3d?

**Comment by justinf2** [comment]
Sure. Let me take a look at implementing something and get back to you. Perhaps I am completely thinking about this in the wrong manner. Thanks for the quick response!

**Comment by drammock** [comment]
closing as duplicate of #7975
