### ISSUE TITLE
remove gray background from ICA.plot_sources

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#6634]
I don't mind the gray background for things like `ICA.plot_properties()` where several subplots of different types are all generated in one figure --- in tutorials and notebooks I think it makes it clearer that the several figures were generated by one function/method call.  But `ICA.plot_sources()` generates a single graph (similar to `Raw.plot()`) so I don't see why it's background should be gray.

cc @cbrnr

**Comment by agramfort** [comment]
Ok for me

**Comment by drammock** [comment]
actually I think this is a bug (possibly a sphinx-gallery bug?).  `ICA.plot_sources()` doesn't *always* have a gray background; seems like maybe it only happens when there's a previous call to `ICA.plot_properties()` in the same notebook cell...  but I can't replicate it even when downloading the `.ipynb` file from https://14567-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/preprocessing/plot_40_artifact_correction_ica.html and running it locally.

@larsoner @choldgraf do you have any insight into whether this might be a sphinx-gallery issue? Or something weird about CircleCI?  As far as I can tell we don't change `first_notebook_cell` anywhere, so I'm kinda stumped what is causing this.

**Comment by larsoner** [comment]
Can you replicate locally with `PATTERN=... make html_dev-pattern`? If so then we have a way forward for debugging.

Before each example is executed, a set of `reset_modules` actions is called:

https://sphinx-gallery.github.io/configuration.html#reset-modules

https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/scrapers.py#L306-L309

If you put a `plt.rcdefaults()` in between the two calls, does it fix `make html_dev-pattern`? If so, then perhaps there is some `rcParams` thing being inadvertently messed with in `plot_sources` or somewhere else.

**Comment by drammock** [comment]
yes, can replicate with `PATTERN=... make html_dev-pattern`.  CircleCI:

![circle](https://user-images.githubusercontent.com/1810515/62567157-795b7c80-b83f-11e9-9d6a-1fb911c8acdb.png)

Local:

![local](https://user-images.githubusercontent.com/1810515/62567170-7f515d80-b83f-11e9-959a-46d41f98b6a6.png)

Local with `rcdefaults()` between `plot_properties()` and `plot_sources()`:

![local-rcdefaults](https://user-images.githubusercontent.com/1810515/62574260-ec1f2480-b84c-11e9-89be-9b27d582b380.png)

**Comment by larsoner** [comment]
I realized that it was probably related to this:

https://github.com/sphinx-gallery/sphinx-gallery/blob/f270049dbc209f1d3bd5598c9fac19b5f665ecee/sphinx_gallery/scrapers.py#L89-L95

See https://github.com/sphinx-gallery/sphinx-gallery/pull/527

**Comment by drammock** [comment]
this is not an MNE-Python bug; will be fixed when sphinx-gallery/sphinx-gallery#527 is merged in.
