### ISSUE TITLE
mne-python is either GPL or non-free now due to mne/io/edf/gdf_encodes.txt

### ISSUE THREAD

**Issue by yarikoptic** [mne-tools/mne-python#6645]
mne/io/edf/gdf_encodes.txt from biosig says
```
# BioSig is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation; either
# Version 3 of the License, or (at your option) any later version.
#
# Alternative license: 
# This table of event codes can be used in any application 
# (without the restrictions of GPL) under the condition that this table 
# is not modified, changed, converted or transformed. No 
# derivative of any kind are allowed. Suggestions for improvement 
# and changes should be addressed to the author. 
```
so either then mne-python is effectively under GPL license or non-free (no modifications allowed)... what it is ? ;)  May be @schloegl could relax this restriction (I am really not sure why not to allow changes/fixes etc)?

**Comment by cbrnr** [comment]
AFAIK we didn't change the table, so we use the alternative license. Unlike the GPL, this alternative license only applies to this single file and does not automatically transfer to MNE.

**Comment by schloegl** [comment]
On 08.08.19 22:01, Yaroslav Halchenko wrote:
> mne/io/edf/gdf_encodes.txt from biosig says
> ```
> # BioSig is free software; you can redistribute it and/or
> # modify it under the terms of the GNU General Public
> # License as published by the Free Software Foundation; either
> # Version 3 of the License, or (at your option) any later version.
> #
> # Alternative license: 
> # This table of event codes can be used in any application 
> # (without the restrictions of GPL) under the condition that this table 
> # is not modified, changed, converted or transformed. No 
> # derivative of any kind are allowed. Suggestions for improvement 
> # and changes should be addressed to the author. 
> ```
> so either then mne-python is effectively under GPL license or non-free (no modifications allowed)... what it is ? ;)  May be @schloegl could relax this restriction (I am really not sure why not to allow changes/fixes etc)?
>


I do allow changes - under the terms of GPLv3.

The code table is used to standardize codes for events, markers and
annotations. Compatibility can only be maintained if the table is
normative.  Therefore, this event table must stay public and nobody
should use a modified, non-public version of this table.  The BSD
license (used by MNE) is not sufficient to guarantee this.


Alois

**Comment by agramfort** [comment]
I understand but how do you allow then the existence of BSD / MIT licensed
readers for GDF files?

**Comment by yarikoptic** [comment]
> Unlike the GPL, this alternative license only applies to this single file and does not automatically transfer to MNE

" is not modified, changed, converted or transformed" restrictions make it non-free.  Moreover "converted" is IMHO a bad term, since under some stretch of interpretation then it is not usable at all since use of those would typically require internal (to the codebase) conversion to other data types/representations.  IMHO trying to enforce it this way provides only disadvantages/inconveniences without actually solving any problem (I really do not see people modifying this file for their own good). tables of values for formats are known to exist in other cases (e.g. iirc

**Comment by cbrnr** [comment]
I don't understand the reasoning either, but if we can't use this file then I suggest we remove it and return only the event codes instead of the text mappings from the file.

**Comment by agramfort** [comment]
@schloegl are you asking us to remove the file with the consequence that mne cannot properly read GDF files?

**Comment by agramfort** [comment]
Maybe we should backport so yarik can cut a Debian release of 0.18 ? Or we wait for 0.19 release in September

**Comment by larsoner** [comment]
0.19 is only one month away, my vote is just to wait
