### ISSUE TITLE
Gradiometer units on PSD

### ISSUE THREAD

**Issue by zobm** [mne-tools/mne-python#6662]
Units PSDs for gradiometers are off (dB = True or False) -- fT/cm^2/Hz... Should it not be (fT/cm)^2/Hz or fT^2/cm^2/Hz? Is the square on the cm meant to represent the whole fT/cm term?

Thanks in advance for clarification.

Also curious why the estimate = 'auto' default is a PSD for dB = True but an ASD for dB = False?

**Comment by larsoner** [comment]
> Is the square on the cm meant to represent the whole fT/cm term?

Yes it's just poorly formatted

> Also curious why the estimate = 'auto' default is a PSD for dB = True but an ASD for dB = False?

Historical reasons / backward compatibility IIRC
