### ISSUE TITLE
Making Epochs when two different events happend at the same time (=duplicate timepoints)

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-python#6665]
Sometimes, raw data can contain two different events that happened at exactly the same time. In this case, when we have an MNE `events` array, the following holds True:

```Python
len(np.unique(events[:, 0])) != len(events[:, 0])
```

And then `mne.Epochs(raw, events, ...)` will raise an error.

Below, we see a suggestion by @larsoner to solve this issue:

> I have hit this problem before and it's annoying. It would be good to deal with this at the MNE end. Maybe the solution is `event_repeated='error'` (current behavior I think?) or `event_repeated='merge'` which will simply do `'%s/%s' % (event_1_key, event_2_key)`, or something similar. Feel free to open an MNE issue about this so that we can discuss.

cc @jasmainak

**Comment by jasmainak** [comment]
PR welcome :)

**Comment by agramfort** [comment]
>
> PR welcome :)
>

+1
