### ISSUE TITLE
BUG: dipy website change broke intersphinx

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#6671]
CircleCI now fails to load the dipy `objects.inv` with this error:
```
intersphinx inventory 'http://nipy.org/dipy/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 400 Client Error: Bad Request for url: https://dipy.org/objects.inv
```
It appears that now anything within `nipy.org/dipy/*` redirects to `dipy.org/*`

**Comment by larsoner** [comment]
This is a downer because it will kill all of our doc builds :(
```
$ git grep "dipy" | wc -l
      44
```
We can temporarily convert all the links to code blocks. It's easy to revert GH commits so I might just make a PR to work around this issue Monday.
