### ISSUE TITLE
raw.plot_psd squeezed to top part of figure

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#6676]
When using `raw.plot_psd` on [this particular GDF file](https://github.com/mne-tools/mne-python/files/3516275/sample_nan.zip) (please unzip first), I get this strange figure:
![Screen Shot 2019-08-19 at 16 13 41](https://user-images.githubusercontent.com/4377312/63272437-5481f300-c29c-11e9-92c4-b09579973498.png)

So far, this is the only file I found to produce this behavior.

```
import mne
raw = mne.io.read_raw_gdf("sample_nan.gdf", preload=True)
raw.plot_psd()
```

**Comment by larsoner** [comment]
This should have been fixed by https://github.com/mne-tools/mne-python/pull/6625, assuming you seed this behavior on current `master`, can you see if it worked okay before that PR?

**Comment by cbrnr** [comment]
Yep, that fixed it and it wasn't working before.
