### ISSUE TITLE
mne.grand_average() behaves differently for evoked data than mne.evoked.grand_average()

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#6696]
#### Describe the bug
`mne.grand_average()` and `mne.evoked.grand_average()` produce different results on the same data: the weights used to calculate the average are not normalized in `mne.grand_average()`.

#### Steps and/or code to reproduce
```python
In[5]: mne.grand_average(evokeds).data.max()
Identifying common channels ...
all channels are corresponding, nothing to do.
Out[5]: 7.730973384174128e-05
```
```python
In[6]: mne.evoked.grand_average(evokeds).data.max()
Identifying common channels ...
all channels are corresponding, nothing to do.
Out[6]: 4.294985213430072e-06
```

#### Expected results
`mne.grand_average()`, when operating on a sequence of `Evoked`s, should produce the  same results as `mne.evoked.grand_average()`

#### Actual results
The results differ. `mne.grand_average()` calls `mne.evoked.combine_evoked()`, which doesn't normalize the weights first:
https://github.com/mne-tools/mne-python/blob/adb70865accfbf2e473d0f78e5be69c090581c0d/mne/utils/numerics.py#L607-L623
https://github.com/mne-tools/mne-python/blob/1189d1a755f4297dcb7212d053f7e1b0d12fd082/mne/evoked.py#L896

`mne.evoked.grand_average()`, on the other hand,  does call `mne.evoked.combine_evoked()` too, but explicitly passes normalized weights, producing the correct result:
https://github.com/mne-tools/mne-python/blob/1189d1a755f4297dcb7212d053f7e1b0d12fd082/mne/evoked.py#L831-L832

#### Additional information
I wonder if it even makes sense that`mne.grand_average()` calls `mne.evoked.combine_evoked()` directly, instead of going through `mne.evoked.grand_average()`, which takes care of the correct weighting.

This is on `master`.

**Comment by agramfort** [comment]
why the heck do we have 2 functions to do this :( :(
one should be deprecated

**Comment by drammock** [comment]
@agramfort you can assign me, I'll get to it this afternoon. I'm the one who most recently dealt with grand average code I think.
