### ISSUE TITLE
ica.plot_properties: y-axis scale missing in variance plot

### ISSUE THREAD

**Issue by SophieHerbst** [mne-tools/mne-python#6718]
In mne 18.2., the plot that shows the variance captured by a component over segments (lower right) generated by ica.plot_properties lacks the tick marks (scale) for the y-axis. Could that be brought back? It helps to have an idea of the scale. Thanks!

**Comment by agramfort** [comment]
indeed we should not have AU for y-label and scale.

PR welcome

**Comment by SophieHerbst** [comment]
There isn't even a scale:
https://mne.tools/stable/auto_tutorials/preprocessing/plot_artifacts_correction_ica.html#sphx-glr-auto-tutorials-preprocessing-plot-artifacts-correction-ica-py

**Comment by mmagnuski** [comment]
@agramfort Last time this was discussed we decided variance should be AU, but eliminating the ticks and their values was mostly an aesthetic maneuver IIRC:
https://github.com/mne-tools/mne-python/pull/5748

BTW, I am not against bringing the y ticks back, I was actually not so happy to remove them, but I left it for the others to decide.

**Comment by cbrnr** [comment]
I just skimmed through the discussion in #5748 and actually no one wanted the y axis ticks and labels removed - it was a misunderstanding and apparently we forgot this because we were too busy with bikeshedding. I can do a PR unless @SophieHerbst wants to do it.

**Comment by agramfort** [comment]
go for it @cbrnr

thx

**Comment by SophieHerbst** [comment]
@agramfort, my issue was just about the ticks, so you get an idea of how much the component diverges. AU seems right to me. Thanks!
