### ISSUE TITLE
RFC: migrate coreg

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#6728]
I wonder how difficult it would be to migrate to Qt + traitlets instead of using traitsui for mne Corey. Then we can easily use other 3D backends. The "disadvantage" is that we'd lose the GUI backend abstraction, but I don't think wx ever worked that well anyway.

It might also be a lot of work.

**Comment by mmagnuski** [comment]
> mne Corey

mne coreg most likely :)

**Comment by larsoner** [comment]
This is in the roadmap so I'll remove this
