### ISSUE TITLE
coreg extremely slow

### ISSUE THREAD

**Issue by jshanna100** [mne-tools/mne-python#6738]
Coreg in the development version is unusably slow for me - it takes more than 5 minutes to load headshape points, and any further operation which requires them to redraw takes similar amounts of time. It runs fine however on branch maint/0.18.

This is on Ubuntu 18.04 and mayavi 4.7.0.dev0

**Comment by larsoner** [comment]
Can you try #6732

**Comment by jshanna100** [comment]
Yep, works great. Thanks!
