### ISSUE TITLE
DOC: instructions for using latest master shouldn't reference "mne" environment

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#6746]
looks like #6540 changed the `name` field in the environment file from `mne` to `base`.  Was that intentional?  I am -1 on our install instructions changing people's base environment.

**Comment by larsoner** [comment]
Yes it was intentional, the idea being that naive users don't want to mess with environments and switching (think about anaconda windows with a Spyder shortcut), and expert users can override it easily

**Comment by drammock** [comment]
hmm. OK. it looks like the docs [here](https://mne.tools/dev/install/mne_python.html#installing-mne-python-and-its-dependencies) got updated to reflect this, but [the advanced install docs](https://mne.tools/dev/install/advanced.html#using-the-development-version-of-mne-python-latest-master) still refer to "the `mne` environment". We should fix that.

**Comment by larsoner** [comment]
Agreed, feel free to make a PR
