### ISSUE TITLE
ICA sources plot_image

### ISSUE THREAD

**Issue by AleDallavecchia** [mne-tools/mne-python#6762]
I've been trying to plot individual epochs image of the individual ica sources. However, when I try plot_image, plot_epochs_image, etc. It gives me the same plot for each individual ICA component. When I reconstruct for example the evoked of the source myself, every component has a different evoked (as expected). This occurs also when I call the ica.plot_components as interactive. All the component properties show different spectrum plots, topoplots, but the same epoch images.

sample code:
```
method = 'infomax'
icacleaned.set_eeg_reference('average', projection=True).apply_proj() # av reref to epoched data
ica = ICA(method=method)
print(ica)
ica.fit(icacleaned)
ica.plot_components(picks=range(0-20),inst=icacleaned)

# example of plotting epoch image for component 1
# also note I run this before actually excluding any components
epochs_src = ica.get_sources(icacleaned)
epochs_src.plot_image(picks=1,colorbar=False)
```

**Comment by vferat** [comment]
Try:
`picks=range(0,20)` instead of `picks=range(0-20)` in `ica.plot_components(picks=range(0-20),inst=icacleaned)`

**Comment by AleDallavecchia** [comment]
Oh no I copied it in wrong, it was range(0,20). I've tinkered around a bit more and now it seems to be a problem I am having in Spyder. From powershell everything seems to work.

**Comment by jgeller112** [comment]
I am also having this issue. Any solution?

**Comment by agramfort** [comment]
again @AleDallavecchia @jgeller112 can you share a code snippet so we can replicate the issue. Otherwise we're stuck

**Comment by jgeller112** [comment]
```
def run_ica(subject, epoch_path, save_ica):
        epoch_file=mne.read_epochs(epoch_path +subject + '-epo.fif' ) # pull epochs from folder
        ica_name= subject + '-ica.fif'
        ica_path = save_ica + ica_name
        ica = mne.preprocessing.ICA(n_components=None, method='fastica')
        ica.fit(epoch_file)
        ica.save(ica_path)
       
```
Here is what some of the figures looks like: 

[GH_0019_EYELOVE_14_ica2.pdf](https://github.com/mne-tools/mne-python/files/3736392/GH_0019_EYELOVE_14_ica2.pdf)
[GH_0039_EYE_20_ica1.pdf](https://github.com/mne-tools/mne-python/files/3736393/GH_0039_EYE_20_ica1.pdf)


The data for 2 subjects can be found here: https://osf.io/h8njv/

**Comment by jgeller112** [comment]
This basic pattern will repeat across subjects.

**Comment by jgeller112** [comment]
I am not sure this
![image](https://user-images.githubusercontent.com/18429968/66964842-6209ee00-f03d-11e9-9083-946fe247bfcd.png)
results in this: 

[GH_0030_EYE_17_ica2.pdf](https://github.com/mne-tools/mne-python/files/3736675/GH_0030_EYE_17_ica2.pdf)

**Comment by agramfort** [comment]
can you please share a full code snippet that runs from start to finish
to replicate the error? thanks

>

**Comment by jgeller112** [comment]
‘’’
def prepro_epoch(subject, save_path, file_path, raw_path, overwrite=True):
    
    As=["A" + str(i) for i in range (1, 33)]
    Bs=["B" + str(i) for i in range (1, 33)]
    points = As + Bs
    montage1 = mne.channels.read_dig_polhemus_isotrak(polh_montage[subject], ch_names=points) # can read polhemus data directly
    raw_files=mne.io.read_raw_bdf(file_path + subject + ".bdf", preload=True, exclude=["EXG" + str(i) for i in range (1, 9)],
                        verbose=True)
    raw_files_filter=raw_files.filter(1,57)# ban
    bad_channels = bad_channels_dict[subject]
    raw_files_filter.info['bads'] = bad_channels
    events = mne.find_events(raw_files_filter)
    events[:,2]=events[:,2] % 256 
    event_id = {'NS': 45, 'VO6': 46}
    avg_raw = raw_files_filter.set_eeg_reference(ref_channels='A29')
    set_montage=avg_raw.set_montage(
    set_montage.interpolate_bads
reject =get_rejection_threshold(set_montage, decim=2)
    picks = mne.pick_types(set_montage.info, meg=False, eeg=True, eog=False, exclude='')
    epochs = mne.Epochs(set_montage, events=events, event_id=event_id,picks=picks, tmin=-.2, tmax=1, baseline=(-.2,0), reject =reject, preload=True)
    epochs.resample(256) # resample to 256Hz
    set_montage.save(raw_path +subject + '-raw.fif', picks=picks) # use raw data for 
    epochs.save(save_path + subject+ '-epo.fif')
    #save(monatge1 + subject+ '-dig.fif')
    return(epochs)
‘’’

I then run ICA

‘’’
def run_ica(subject, epoch_path, save_ica):
        epoch_file=mne.read_epochs(epoch_path +subject + '-epo.fif' ) # pull epochs from folder
        ica_name= subject + '-ica.fif'
        ica_path = save_ica + ica_name
        ica = mne.preprocessing.ICA(n_components=None, method='fastica')
        ica.fit(epoch_file)
        ica.save(ica_path)
’’’

**Comment by larsoner** [comment]
@jgeller112 I think @agramfort was looking for code that one of us could run locally. It looks like if you can upload one of the problematic `epoch_path + subject + '-epo.fif'` files, we can at least run the `run_ica` function. If you could share a link to one of the `-epo.fif` files and also add the plotting commands used to make the problematic figures that would make it so we can see what you see to properly debug.

**Comment by jgeller112** [comment]
Sorry about that! Please let me know if you need more information. 

I included a link to OSF repository with the epoch files for 2 Ss: https://osf.io/h8njv/

Here is the function I use to plot: 

def plot_ica(subject, ica_path,save_plots,ica_plot_path):
    
    ica = read_ica(ica_path +subject+ "-ica.fif") #pull ica soultions from folder
    ica_figure = ica.plot_components()
    
    if save_plots:
        save_path = os.path.join(ica_plot_path, subject + '_ica1' + '.pdf')
        save_path2 = os.path.join(ica_plot_path, subject+'_ica2'+ '.pdf')
        ica_figure[0].savefig(save_path, dpi=600) #cant print all ICA components
        ica_figure[1].savefig(save_path2, dpi=600)
        print('figure: ' + save_path + ' has been saved')
    else:
        print('Not saving plots; set "save_plots" to "True" to save')

**Comment by agramfort** [comment]
@jgeller112 here a full reproducible code snippet:

```
import os
from mne.preprocessing import read_ica

def plot_ica(subject, ica_path,save_plots,ica_plot_path):

    ica = read_ica(ica_path +subject+ "-ica.fif") #pull ica soultions from folder
    ica_figure = ica.plot_components()

    if save_plots:
        save_path = os.path.join(ica_plot_path, subject + '_ica1' + '.png')
        save_path2 = os.path.join(ica_plot_path, subject+'_ica2'+ '.png')
        ica_figure[0].savefig(save_path)
        ica_figure[1].savefig(save_path2)
        print('figure: ' + save_path + ' has been saved')
    else:
        print('Not saving plots; set "save_plots" to "True" to save')

plot_ica('GH_0019_EYELOVE_14', './', True, '.')
plot_ica('GH_0039_EYE_20', './', True, '.')
```

your code above needed some work to be able to produce these figures:

![GH_0019_EYELOVE_14_ica1](https://user-images.githubusercontent.com/161052/67144571-155e2700-f278-11e9-8e62-efae732722c6.png)
![GH_0019_EYELOVE_14_ica2](https://user-images.githubusercontent.com/161052/67144572-155e2700-f278-11e9-9c71-759e1642699c.png)
![GH_0039_EYE_20_ica1](https://user-images.githubusercontent.com/161052/67144573-155e2700-f278-11e9-82c4-ea26ff73e536.png)
![GH_0039_EYE_20_ica2](https://user-images.githubusercontent.com/161052/67144574-155e2700-f278-11e9-97cb-0e2e55c37e59.png)

yes some components look very similar so ICA did not do a great job. There much be some problem with the input data.

**Comment by jgeller112** [comment]
Thanks for looking into this. The evoked data look fairly clean before ICA. Any reason why ICA might produce this type of pattern? Across Ss, this pattern will repeat, which is why I thought it might be a bug.

**Comment by jgeller112** [comment]
If I change  ica = mne.preprocessing.ICA(n_components=None, method='fastica') to  ica = mne.preprocessing.ICA(n_components=.9, method='fastica'), I get a completely reasonable set of components.

**Comment by agramfort** [comment]
I would think you hit this problem:

https://hal.archives-ouvertes.fr/hal-01451432/document

The internal optimization solver of infomax if very hard to control
and makes it difficult to guarantee convergence. This was the motivation
for this work https://arxiv.org/abs/1706.08171 and the picard solver
https://github.com/pierreablin/picard. You can you method='picard' in ICA
to use it. Please let us know if it works for you.

**Comment by hoechenberger** [comment]
@jgeller112 Did you ever find time to test the Picard solver suggested by @agramfort?
