### ISSUE TITLE
Missing python scripts from all tutorials

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#6779]
when trying to download a .py script for a tutorial at the bottom of the page it's telling me that the file does not exist. For example this link is broken:

https://mne.tools/dev/_downloads/36e789cbf04a4ef0f75e81dbcd49ca2a/plot_20_events_from_raw.py

this link is the download button at the bottom of https://mne.tools/dev/auto_tutorials/preprocessing/plot_10_preprocessing_overview.html#low-frequency-drifts

cc @drammock

**Comment by larsoner** [comment]
It's because the conditional I added here was wrong:

https://github.com/mne-tools/mne-python/blame/master/.circleci/config.yml#L240
