### ISSUE TITLE
mne.convert_forward_solution : option force_fixed

### ISSUE THREAD

**Issue by MarliesG** [mne-tools/mne-python#6795]
Hi all, 

I'm trying to solve the forward model. I've noticed that the option force_fixed can be set to True (and although the function stated commented out that the option force_fixed is not currently available, it does somehow the job). Therefore: can the option force_fixed be used? And if so which orientation fixed source orientation is used (not entirely clear from https://www.nmr.mgh.harvard.edu/mne/stable/generated/mne.convert_forward_solution.html#mne.convert_forward_solution)?

**Comment by agramfort** [comment]
it uses the normal orientation to the cortex

>
