### ISSUE TITLE
Can't raw.filter MISC channels

### ISSUE THREAD

**Issue by ossadtchi** [mne-tools/mne-python#6802]
With raw.filter I can not filter the instance of the raw created with ```pick_channels``` using names of MISC channels. It complains about not finding the channels to work with. Still does not work when I tried to explicitly specify ```picks``` to the ```raw.filter``` method using either indices or channel names. Both of these instructions fail:  
```
raw_misc = raw.copy().pick_channels(names_misc);

raw_misc.filter(0.5, 5., h_trans_bandwidth='auto', filter_length='auto',
                         phase = 'zero', picks = names_misc);
raw_misc.filter(0.5, 5., h_trans_bandwidth='auto', filter_length='auto',
                         phase = 'zero', picks = np.array([0,1,2]));
```

**Comment by agramfort** [comment]
this is the same issue as #6801 6801
