### ISSUE TITLE
ENH: Prevent users from making some poor choices in volumes

### ISSUE THREAD

**Issue by jhouck** [mne-tools/mne-python#6803]
From the [gitter](https://gitter.im/mne-tools/mne-python?at=5d8780f3c77f285fb1c2ede4). In a `VolVectorSourceEstimate` or a `VolSourceEstimate`, attempting to use the inherited `normal` probably should at throw an error, or at least a warning.  It might also be good for the various `apply_inverse` functions to do something similar in these spaces when `pick_ori='normal'`.  Looks like `_compute_beamformer` might already do this.

**Comment by larsoner** [comment]
I can fix this tomorrow, would be good to make it an error before release
