### ISSUE TITLE
RFC: Draft for the new release note v0.19

### ISSUE THREAD

**Issue by massich** [mne-tools/mne-python#6810]
I put together a release note, please feel free to comment on it (or edit).

--- 

Dear community!

We are very pleased to announce the new 0.19 release of MNE-Python (http://mne.tools/stable/).

A few highlights
================

- New URL http://mne.tools
- Reorganized documentation, with 19 new or revised tutorials.
- Automatic MRI fiducial estimation based on MNI Talairach transforms.
- Improved plotting support, including new Butterfly plots for PSD epochs, and 3D sensor connectivity plots.
- Speed improvements in clustering, coregistration, volumetric source space creation, and other parts of the codebase.
- More supported file formats, including curry files, the updated NYU New York 2019 system for KIT, and the new Annotations support for CTF marker files.

In addition, we caught and fixed more than 41 bugs!

Notable API changes
===================

- New minimum supported dependencies, most critically **Python >= 3.5 is now required**.
- Complete reworking of EEG channel montage/digitization, including improvements for EEG source modeling with no MRI (surrogate MRIs).
- Fixes to volumetric morphing and plotting functions.
- Update of the FIF constants.

For a full list of improvements and API changes see:
http://mne.tools/stable/whats_new.html#version-0-19

To install the latest release the following command should do the job:

    $ pip install --upgrade mne

As usual, we welcome your bug reports, feature requests, feedback, and contributions.

Some links:
- https://github.com/mne-tools/mne-python (code + readme on how to install)
- http://mne.tools/stable/ (full MNE documentation)

Follow us on Twitter for general news (https://twitter.com/mne_news)
and for a regular feed of merged PRs (https://twitter.com/mne_python).

Regards,
The MNE-Python developers

70 people made commits that contributed to this release (in alphabetical order):

* 	Abram Hindle
* 	Achilleas Koutsou
* 	Alexander Kovrig
* 	Alexandre Gramfort
* 	Antoine Gauthier
* 	Britta Westner
* 	Bruno Nicenboim
* 	Burkhard Maess
* 	Chris Bailey
* 	Chris Holdgraf
* 	Christian Brodbeck
* 	Christian Clauss
* 	Clemens Brunner
* 	Cristóbal Moënne-Loccoz
* 	Daniel McCloy
* 	David Haslacher
* 	Denis A. Engemann
* 	Dirk Gütlin
* 	Elizabeth DuPre
* 	Eric Larson
* 	Evgenii Kalenkovich
* 	Fede Raimondo
* 	Guillaume Favelier
* 	Hubert Banville
* 	Ivana Kojcic
* 	Jean-Remi King
* 	Jeff Hanna
* 	Joan Massich
* 	Johannes Kasper
* 	Jon Houck
* 	Jona Sassenhagen
* 	Jose Alanis
* 	Jose C. G. Alanis
* 	José C. G. Alanis
* 	José C. García Alanis
* 	Jussi Nurminen
* 	Kambiz Tavabi
* 	Katarina Slama
* 	Keith Doelling
* 	Kostiantyn Maksymenko
* 	Larry Eisenman
* 	Legrand Nicolas
* 	Lorenz Esch
* 	Luke Bloy
* 	Mainak Jas
* 	Maksymenko Kostiantyn
* 	Marijn van Vliet
* 	Mikolaj Magnuski
* 	Milan Rybář
* 	Nathalie Gayraud
* 	Nikolas Chalas
* 	Oleh Kozynets
* 	Quentin Bertrand
* 	Richard Höchenberger
* 	Robert Seymour
* 	Samuel Deslauriers-Gauthier
* 	Sebastián Castaño
* 	Simon Kern
* 	Stanislas Chambon
* 	Stefan Appelhoff
* 	Stefan Repplinger
* 	Steve Matindi
* 	Teon Brooks
* 	Theodore Papadopoulo
* 	Thomas Donoghue
* 	Thomas Hartmann
* 	Thomas Radman
* 	Eberhard Eich
* 	Joshua J Bear
* 	Paul Roujansky

**Comment by larsoner** [comment]
Done with my pass

**Comment by massich** [comment]
I did my pas aswell.

**Comment by drammock** [comment]
I've done mine.

**Comment by cbrnr** [comment]
Done.
