### ISSUE TITLE
Remove deprecations

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#6829]
It seems like some deprecated functions were not removed in 0.19, e.g. https://github.com/mne-tools/mne-python/blob/b3f46657fad1599262b6290b0c97a14d264ffc78/mne/io/edf/edf.py#L30-L32 and https://github.com/mne-tools/mne-python/blob/76ee63ff92b0424a304a12532d0cb53c0833a0ec/mne/simulation/evoked.py#L84-L86 Does anyone already have a script to automate this? Otherwise, I can remove these things manually.

**Comment by agramfort** [comment]
We're removing them in 0.20 then.

too late to fix after the release.

**Comment by larsoner** [comment]
Made a quick PR for the first one in #6830, the second one was merged with #6825
