### ISSUE TITLE
BUG: morph.as_volume does not check subject `src`

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#6837]
@jhouck is able to do this for `inv` defined for `sample`:
```
stc_fsaverage.as_volume(inverse_operator['src'], dest='mri', mri_resolution=False, format='nifti1')
```
Assuming the `inv` has a properly defined `src[0]['subject_his_id']` this should not be possible. If that field is not defined, we should probably update the `sample` dataset.

**Comment by jhouck** [comment]
I did double-check, and for that file (sample_audvis-meg-vol-7-meg-inv.fif) `inverse_operator['src'][0]['subject_his_id']` is None.

**Comment by larsoner** [comment]
Ahh okay. So maybe it does check. But we should probably update the `sample` dataset.

**Comment by jhouck** [comment]
Maybe also a warning if you load/create an inverse operator when its subject is None?

**Comment by larsoner** [comment]
That's probably a reasonable thing to do, too.

**Comment by agramfort** [comment]
agreed. We should have a warning and update the sample dataset.

**Comment by larsoner** [comment]
FYI I just tried recreating the source space with MNE-C and it looks like it does not actually write `subject_his_id` for volume source spaces. I'll set it manually, save the file, and update the dataset. (Our Python `setup_volume_source_space` does set `subject_his_id` properly.)
