### ISSUE TITLE
Use eye-tracker data to reference ICA

### ISSUE THREAD

**Issue by mariusrak** [mne-tools/mne-python#6839]
Hi,
I have Eye-Tracker (ET) data recorded alongside EEG data. The ET data contains X,Y positions for both eyes on screen. The data are 4 time series, values are in pixels (0 - 1080/1920) or -1 if invalid (e.g. blink, not looking at screen). Would it be possible to use them for ICA as substitute for EOG channel? I'd like to try if ICA can correlate components to the ET data, which might help with artifact correction.

I have also data from accelerometer from head movement (3 time series, for each axis X, Y, Z). THose might also help ICA to correlate components.

I achieved that I have the data in the series, but I'm not sure how to tell ICA methods to use them as reference.

Thanks for help.

**Comment by agramfort** [comment]
>
> I have Eye-Tracker (ET) data recorded alongside EEG data. The ET data
> contains X,Y positions for both eyes on screen. The data are 4 time series,
> values are in pixels (0 - 1080/1920) or -1 if invalid (e.g. blink, not
> looking at screen). Would it be possible to use them for ICA as substitute
> for EOG channel? I'd like to try if ICA can correlate components to the ET
> data, which might help with artifact correction.
>
> I achieved that I have the data in the series, but I'm not sure how to
> tell ICA methods to use them as reference.
>

ICA algorithms we commonly use treat all channels equally. One is not a
reference even if you pass an EOG
it will be as another EEG channel. You can just tell mne that the misc / ET
signals are EEG channels to run ICA.
It's a hack but it should work
