### ISSUE TITLE
measurement Info shoudl have a _reprt_html method to be printed in a notebook

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#6846]
and the MNE report should be using the _repr_html method when available to produce HTML rendering of mne objects

**Comment by larsoner** [comment]
I would wait to work on this until we can use https://github.com/sphinx-gallery/sphinx-gallery/issues/540 to see the outputs

**Comment by agramfort** [comment]
this sphinx-gallery PR will help but it's quite orthogonal to me.

>

**Comment by larsoner** [comment]
Anybody want a fun quick one for 0.21? @hoechenberger maybe?

**Comment by hoechenberger** [comment]
> Anybody want a fun quick one for 0.21? @hoechenberger maybe?

Maybe I can squeeze it in somewhere, but no promises :)

**Comment by vagechirkov** [comment]
```Python
import os
import mne

from IPython.display import display, HTML

sample_data_folder = mne.datasets.sample.data_path()
sample_data_raw_file = os.path.join(sample_data_folder, 'MEG', 'sample',
                                    'sample_audvis_filt-0-40_raw.fif')
raw = mne.io.read_raw_fif(sample_data_raw_file)

string = raw.info.__repr__()


template_red = '<span1 style="color: red;  margin-left: 150px;">{}</span1>'
template_blue = '<span1 style="color: blue;">{}</span1>'
info_html_string = '<div class="MathJax_Display" style="text-align: left; background-color:rgba(201, 76, 76, 0.3);">'
info_html_string += "<style> span1 {border-radius: 5px;  font-family:fantasy;} </style>"
info_html_string += '<span1 style="color: green; margin-left: 250px; font-size: large;">INFO</span1><br>'

for line in string.split('\n')[1:-1]:
    line_parts = line.split(':')
    for n, l in enumerate(line_parts):
        if n == 0:
            info_html_string += template_red.format(l + ':')
        else:
            info_html_string += template_blue.format(l)
    info_html_string += "<br>"

display(HTML(info_html_string))
```

@hoechenberger @agramfort is it something that you expect in the ```_repr_html``` method?

**Comment by agramfort** [comment]
can you share a screen shot?

>

**Comment by vagechirkov** [comment]
> can you share a screen shot?
> […](#)

The design is random :)

![image](https://user-images.githubusercontent.com/42982039/111637402-ac2a6c80-87f9-11eb-9917-db76dbc11e5d.png)

**Comment by hoechenberger** [comment]
I'm wondering if we could "cast" the Info into a pandas DataFrame and simply use the DataFrame's HTML representation method?

**Comment by agramfort** [comment]
pandas is not a hard dependency of mne

>

**Comment by hoechenberger** [comment]
Ok. Then, how about repurposing what we already have in `Report`?
https://github.com/mne-tools/mne-python/blob/fc3f2b56bc172eb3b747751e636d55b0cbb56861/mne/report.py#L819-L874

**Comment by agramfort** [comment]
+100 !

>

**Comment by vagechirkov** [comment]
> Ok. Then, how about repurposing what we already have in `Report`?

Here is an example of ```raw_template``` output using ```IPython.display.HTML``` 

![image](https://user-images.githubusercontent.com/42982039/111674929-dc373700-881c-11eb-9373-4fa253cb16c6.png)

**Comment by larsoner** [comment]
That's great! I think if the `html` is returned by `_repr_html_` it should work properly.

Incidentally you can show this off in our doc build by modifying some example that talks about meas info, and just having a line at the end of some code block like:
```
#############################################
# We can also get a nice HTML representation in IPython like:

info
```
Sphinx-gallery will recognize this statement-without-assignment and, if the object has a `_repr_html_`, add it to the output of the code block...

**Comment by agramfort** [comment]
yes I would add _repr_html_ methods and then make sure that report.py just reuses these so we shoot 3 birds with one stone. It will work for the notebook, the doc and the Report

**Comment by vagechirkov** [comment]
Here is am output of rendering `plot_report.py` tutorial:

![image](https://user-images.githubusercontent.com/42982039/111766710-244e6c00-88a6-11eb-8e7b-33978c4d51e5.png)
