### ISSUE TITLE
To Export STEP File from MESH /VOLUME/STL?

### ISSUE THREAD

**Issue by selvakarna** [mne-tools/mne-python#6858]
To Export STEP File from MESH /VOLUME/STL?

**Comment by larsoner** [comment]
I'm not sure what you mean, but based on what you wrote this does not sound in scope for MNE.

**Comment by selvakarna** [comment]
Hi @larsoner ,

   What details needed to make STEP from Volume using Python.

**Comment by selvakarna** [comment]
@larsoner , or Surf export as step ? can you share Idea's

**Comment by larsoner** [comment]
I'm not even sure what a STEP file is, is this related to M/EEG somehow?
