### ISSUE TITLE
BUG, VIZ: raw.plot_psd fmax param ignored when plotting

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#6862]
the `fmax` parameter should be used to set the right-hand xlim of the plot, but it is not. In the plots below, the right-hand xlim is determined by the `sfreq` even though `fmax=350` is specified for both plots.

```
import os
import mne
sample_data_folder = mne.datasets.sample.data_path()
sample_data_raw_file = os.path.join(sample_data_folder, 'MEG', 'sample',
                                    'sample_audvis_raw.fif')
raw = mne.io.read_raw_fif(sample_data_raw_file)
raw.crop(0, 60).load_data() 

raw_downsampled = raw.copy().resample(sfreq=100)

for data in (raw, raw_downsampled):
    fig = data.plot_psd(fmax=350)
```
![Figure_1](https://user-images.githubusercontent.com/1810515/65967765-045b8c00-e417-11e9-9b8c-e32950f093c4.png)

![Figure_2](https://user-images.githubusercontent.com/1810515/65967773-07ef1300-e417-11e9-9be3-fc1a6aac8b5f.png)

**Comment by larsoner** [comment]
Somewhere there could be a `min(fmax, freqs[-1])` that makes it so that it uses the min of the actual freqs present and what you pass. But we can undo this / make it work.

**Comment by agramfort** [comment]
I think it should rather crash if you ask for an fmax > sfreq / 2 as you go beyond nyquist cut-off frequency. There is nothing to see beyond.
