### ISSUE TITLE
plot_psd with spatial_colors=True fails when some location values are nan

### ISSUE THREAD

**Issue by AKMeunier** [mne-tools/mne-python#6870]
Adding a simple warning would help, it took me a while to realize that this was the reason my plot was all in black. Even better would be plotting only the nan electrodes in black and showind them beside the head in the little head color plot.

**Comment by agramfort** [comment]
when trying I see in my terminal:

RuntimeWarning: Channel locations not available. Disabling spatial colors.

can you confirm that the warning is already there?

**Comment by AKMeunier** [comment]
I only get these two:

.../site-packages/matplotlib/colors.py:259: RuntimeWarning: invalid value encountered in less if np.any((result < 0) | (result > 1)):

.../site-packages/matplotlib/colors.py:259: RuntimeWarning: invalid value encountered in greater np.any((result < 0) | (result > 1)):

**Comment by agramfort** [comment]
please a file and a script so we can try to replicate

>

**Comment by dtxe** [comment]
To replicate this issue:
1. Load any dataset with a DigMontage
2. Either use a dataset where one electrode has an undefined position OR manually set a sensor to nan coordinates:
```
from math import nan
montage = raw.get_montage()
montage.dig[1]['r'][0:2] = nan
raw.set_montage(montage)
```
3. Plot the evoked response with spatial_colors=True
