### ISSUE TITLE
missing template for topoplot

### ISSUE THREAD

**Issue by cpelofi** [mne-tools/mne-python#6891]
Hello, 
Trying to use evoked.plot_topomap on MEG data with .sqd format and receive this message error:

"The layout for the KIT system with ID 35 is missing. Please contact the developers about adding it."

Thanks for your help!
Claire

**Comment by agramfort** [comment]
Can you share the file ? Where is the file coming from ?

**Comment by cpelofi** [comment]
The file come from NYU MEG system.

File can be downloaded here:

https://we.tl/t-Ezmn5SI0lQ


Thanks,
Claire

**Comment by teonbrooks** [comment]
it looks like christian updated the kit module to support that ID in `0.19` right before release. @cpelofi, which version of mne are you currently running? it might just need a quick update

**Comment by cpelofi** [comment]
I just ran 

pip install mne --upgrade

Received that:

Found existing installation: mne 0.18.1
    Uninstalling mne-0.18.1:
      Successfully uninstalled mne-0.18.1
Successfully installed mne-0.19.0


Then ran again

evoked = epochs['tone'].average()
evoked.plot()
evoked.plot(spatial_colors = True, gfp = True)

times = np.arange(0., 0.4, 0.04)
evoked.plot_topomap(times=times)

And received the same message..

**Comment by cpelofi** [comment]
I just upgraded to the 0.19 version but still get the same error message when I run the topomap.

**Comment by agramfort** [comment]
@christianbrodbeck can you have a look?

**Comment by christianbrodbeck** [comment]
Yeah I added sensor connectivity but not a layout. Is there a layout or a standard way for generating such a layout manually? Otherwise I would suggest to fall back on the automatic code in `find_layout` for missing KIT IDs. I can make PR if that seems like a good option.

**Comment by agramfort** [comment]
whatever works. for MEG systems we tend to have predefined layout files.
Maybe fieldtrip has made one we can reuse?

>

**Comment by christianbrodbeck** [comment]
I doubt it since this system has only just been updated (including a layout change)

**Comment by teonbrooks** [comment]
@cpelofi, it looks like the fix was landed. it is on the development cycle so to use it, you will have to use this setup outlined [here](https://github.com/mne-tools/mne-python#get-the-latest-code)

**Comment by cpelofi** [comment]
Working! Thanks
