### ISSUE TITLE
DOC: improvements to contributing guide

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#6898]
This issue is to collect suggestions from Woods Hole code sprint participants about how to improve the [contributing page](https://mne.tools/stable/install/contributing.html). Add your comments below!

**Comment by massich** [comment]
As a side note, I've been checking travis doc a lot these past 2 days and I found they have something really cool:
![image](https://user-images.githubusercontent.com/7044835/66137566-958c5780-e5fd-11e9-993b-755719865822.png)

The button saying `Improve this page in github` which allows for easy PRs in the doc. Maybe we could add something similar.

**Comment by AdoNunes** [comment]
Maybe add in the contribution page the requirement of adding the contributor's name and url in names.inc and explain how to write down the new contribution in latest.inc 

also, the link to what's new it's broken:
https://mne.tools/stable/install/whats_new.html

**Comment by drammock** [comment]
@AdoNunes the link is https://mne.tools/stable/whats_new.html (stable) or https://mne.tools/dev/whats_new.html (dev)

**Comment by massich** [comment]
adding that to the guide is good. Although IMHO a comment in a contributing guide is not enough to force people to add it. It should be a bot that forbids merging unless this info is there. But we should add it to the contributing guide none the less.

**Comment by AdoNunes** [comment]
@drammock the broken link I referred to is at the bottom of the contributing webpage

**Comment by drammock** [comment]
@AdoNunes Ahh, I see the problem now. Added a separate issue for that (#6901)

**Comment by jasmainak** [comment]
Many folks seemed to have missed the part about forking. I think more pictures in the guide would really help. You can just reuse pictures from github (assuming that the URL stays stable) so that you don't add anything to the repo.

**Comment by mohdsherif** [comment]
1- Make it more clear that a stable version under conda needs to have been installed (it took me a bit to figure I need this and that I cannot skip this step). 
2- For users on Linux who need to keep using their system python installation, note that they need to unset PYTHONPATH before installing.
3- Also, such users can switch back and forth when they need to use their system python by changing their PATH.

**Comment by massich** [comment]
@jasmainak would it work to point to https://help.github.com/en/articles/fork-a-repo ?

**Comment by drammock** [comment]
we already link to https://help.github.com/en/articles/fork-a-repo in the second paragraph of the contributing guide. So empirically, that was not sufficient.

**Comment by jasmainak** [comment]
nobody clicks the links. The document is already long. What can we do to make someone up and running in less than an hour?
