### ISSUE TITLE
BUG?  Extended infomax ICA  

### ISSUE THREAD

**Issue by christianbrodbeck** [mne-tools/mne-python#6919]
This looks like a bug to me, the documentation says that (through a backwards incompatible change) `if you want Extended Infomax, set method='infomax' and fit_params=dict(extended=True)`, however for `method='infomax'` [these lines](https://github.com/mne-tools/mne-python/blob/master/mne/preprocessing/ica.py#L359-L360) force `extended` to `False`.

**Comment by christianbrodbeck** [comment]
And I think this would have been the case in 0.18 too.

**Comment by larsoner** [comment]
That does look like a bug, can you make a bugfix? Then we can backport to 0.19. We're probably going to do a 0.19.1 early next week

**Comment by drammock** [comment]
I can do it. My flight is drastically delayed.

**Comment by larsoner** [comment]
Go for it!
