### ISSUE TITLE
BUG: Misalignement plotting TFR with linear y-axis

### ISSUE THREAD

**Issue by stfnrpplngr** [mne-tools/mne-python#6929]
### Describe the bug
Plotting TFRs with linear y-axis, bins for the particular frequencies are not properly aligned with the y-axis.

#### Steps and/or code to reproduce
[This gist](https://gist.github.com/stfnrpplngr/2378c70e6285322f38d54fa04d1fc764) is an example to produce the erroneous plot. The center of the notch filter appears not at 50 Hz regarding the plot.

#### Expected results
50 Hz frequency bin is centered at the 50 Hz y-tick:
![Issue_freq_shift_notch_solved](https://user-images.githubusercontent.com/20129752/66406313-b97bde80-e9eb-11e9-9367-9953b2fc2044.png)
![issue_freq_shift_solved2](https://user-images.githubusercontent.com/20129752/66406325-bbde3880-e9eb-11e9-93c3-74d487e234c5.png)

#### Actual results
50 Hz frequency bin is not centered at the 50 Hz y-tick:
![Issue_freq_shift_notch](https://user-images.githubusercontent.com/20129752/66406447-e9c37d00-e9eb-11e9-887d-691a7bb422f5.png)
![Issue_freq_shift_notch_2](https://user-images.githubusercontent.com/20129752/66406445-e92ae680-e9eb-11e9-9dfd-f80cacd6f787.png)

#### Additional information
Platform:      Windows-10-10.0.16299-SP0
Python:        3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Executable:    C:\Continuum\Anaconda3\envs\general\python.exe
CPU:           Intel64 Family 6 Model 142 Stepping 10, GenuineIntel: 8 cores
Memory:        Unavailable (requires "psutil" package)
mne:           0.20.dev0
numpy:         1.16.5 {blas=mkl_rt, lapack=mkl_rt}
scipy:         1.3.1
matplotlib:    3.1.1 {backend=Qt5Agg}

sklearn:       0.21.3
numba:         Not found
nibabel:       Not found
cupy:          Not found
pandas:        0.25.1
dipy:          Not found
mayavi:        Not found
pyvista:       Not found
vtk:           Not found

**Comment by stfnrpplngr** [comment]
The bin displaying the 50 Hz notch filter is not centered at 50 Hz.

**Comment by larsoner** [comment]
@stfnrpplngr PR welcome!

**Comment by agramfort** [comment]
@stfnrpplngr are you sure you did not paste twice the same image?

**Comment by larsoner** [comment]
@agramfort look at the 90 tick they are in different places (both are wrong actually)
