### ISSUE TITLE
mne.channels.read_montage deprecated without deprecation cycle?

### ISSUE THREAD

**Issue by mmagnuski** [mne-tools/mne-python#6950]
I might have missed something, but I have a feeling that `mne.channels.read_montage` did not raise any deprecation warnings before, and now it is unavailable. It took me a while to find out what I should use instead to create a standard montage. I could not find this information in whats new too (only the deprecation, but not what should be used instead). Was `read_montage` removed without a deprecation cycle?

**Comment by larsoner** [comment]
It is in `0.19` but not `master`, so there is a deprecation cycle. It was deprecated right before release, though, so users of `master` barely saw any warning (just for a week or two).

You should use `make_standard_montage` or one of the dedicated `mne.channels.read_dig_*` readers

**Comment by mmagnuski** [comment]
@larsoner Yes, I know what to use, I found it in one of the PRs. :) Good to know the deprecation is in 0.19, sorry for the noise.

**Comment by larsoner** [comment]
Feel free to make a doc update for `maint/0.19`, though, the release notes and deprecation warning perhaps could have been clearer about what to use instead
