### ISSUE TITLE
matplotlib set_cmap deprecation

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#6951]
matplotlib deprecation, happens only when changing "interactive" colorbars, so maybe not caught by our tests:

```
/opt/mne/python/mne/viz/utils.py:1949: MatplotlibDeprecationWarning: 
The set_cmap function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use ScalarMappable.set_cmap instead.
  self.cbar.set_cmap(cmap)
```

This happened for `evoked.plot_image()` but will probably happen anywhere we have an interactive colorbar.

**Comment by larsoner** [comment]
I've fixed these in various PRs (I hope)
