### ISSUE TITLE
Max and min frequency and time of EEG signal 

### ISSUE THREAD

**Issue by AndrianaMrt** [mne-tools/mne-python#6952]
I am new to signal processing and I am trying to find the maximum and minimum frequency and time of EDF signals obtained by electrodes. How could I do that with MNE - Python?

I read the file with mne.io.read_raw_edf and I tried to filter it from the artefacts with the filter method.

**Comment by agramfort** [comment]
please don't use issue tracker to ask usage questions. Use gitter or the mailing list

thanks
