### ISSUE TITLE
Keep the sign values from TF-MxNE solver or irMxNE solver

### ISSUE THREAD

**Issue by dasdiptyajit** [mne-tools/mne-python#6953]
Any possible way to keep the sign values (positive and negatives values) while performing source localization using TF-MxNE solver or irMxNE solver?

Note: Current solutions only provide absolute values in return as dipoles!

**Comment by dasdiptyajit** [comment]
Follow up! @agramfort

**Comment by agramfort** [comment]
do you think you could give it a try? it means adding a pick_ori parameter
like for apply_inverse and change the code accordingly.

>

**Comment by dasdiptyajit** [comment]
yes, I have tired. I had to set a forward solution with fixed dipole orientations and had to modify the code and some parameters accordingly and it works nicely.

Note: One needs to flip the activated signals of a particular dipole after source localization, in order to match the signal strength across other dipoles due to the fixed orientation across hemispheres  i.e., left and right auditory cortex label.

**Comment by dasdiptyajit** [comment]
Alright, I am closing the issue then!

**Comment by agramfort** [comment]
ok great !

>
