### ISSUE TITLE
ModuleNotFoundError: No module named 'mne.viz.plot_sensors_connectivity'

### ISSUE THREAD

**Issue by MSA8D8** [mne-tools/mne-python#6956]
I am faced with the problem below.

`import mne.viz.plot_sensors_connectivity`

> Traceback (most recent call last):
  File "D:\.....\~.py", line 24, in <module>
    import mne.viz.plot_sensors_connectivity as psc
ModuleNotFoundError: No module named 'mne.viz.plot_sensors_connectivity'
[Finished in 2.52s]

But, when I tried to `import mne.viz`, no error happened.
So, it seems to be something wrong with this plot_sensors_connectivity.

Thank you in advance.

**Comment by cbrnr** [comment]
You need to do:

```
from mne.viz import plot_sensors_connectivity
```

**Comment by MSA8D8** [comment]
Thanks for reply, @cbrnr  

I tried your suggestion, but the situation is completely the same.

> Traceback (most recent call last):
  File "C:\....\~.py", line 25, in <module>
    from mne.viz import plot_sensors_connectivity
ImportError: cannot import name 'plot_sensors_connectivity' from 'mne.viz'

**Comment by agramfort** [comment]
you must have an install problem or a too old mne version

>

**Comment by MSA8D8** [comment]
@agramfort 

Thank you for comment.

I can solve the problem by update the version of mne.
Here is the `pip install -U mne` result.

> Installing collected packages: mne
  Found existing installation: mne 0.18.2
    Uninstalling mne-0.18.2:
      Successfully uninstalled mne-0.18.2
Successfully installed mne-0.19.0

Thank you both, @cbrnr and @agramfort

**Comment by catalinasaini** [comment]
from mne_connectivity import plot_sensors_connectivity
