### ISSUE TITLE
can't export data to edf format

### ISSUE THREAD

**Issue by jetW** [mne-tools/mne-python#6963]
I want to save my data as edf format, but that is not natively supported.

the gist for saving edf on the page(https://mne.tools/stable/auto_tutorials/io/plot_20_reading_eeg_data.html?highlight=edf%20save) is not accessible.

Is there any solutions?

**Comment by agramfort** [comment]
what do you mean it's not accessible ?

https://gist.github.com/skjerns/bc660ef59dca0dbd53f00ed38c42f6be

>

**Comment by cbrnr** [comment]
You can also try [MNELAB](https://github.com/cbrnr/mnelab) (a GUI for MNE), which does support export to EDF/BDF out of the box if you have pyEDFlib installed.

**Comment by larsoner** [comment]
Closing as there are suitable solutions provided
