### ISSUE TITLE
Rejecting data in frquency domain

### ISSUE THREAD

**Issue by mariusrak** [mne-tools/mne-python#6970]
Hi, there is a feature to reject data spans based on value when working with ERPs. However I won't be working with ERPs, but only in frequency domain. Is it possible to reject parts of data that have e.g. amplitude higher than 100uV (EEG) form time series? Maybe with some padding around or based on hanning window or so. I have quite a lot of such spans (in one hour long recordings). It would be laborious to mark them manually and it can be done automatically. 
Thanks.

**Comment by agramfort** [comment]
I would do this with numpy. Something like this (disclaimer untested)

data = epochs.get_data()
n_epochs, n_channels, n_times = data.shape
bad_idx = np.where(data.max(axis=2).max(axis=1) > 100e-6)[0]
epochs.drop(bad_idx, reason='amplitude')

hope this helps.

please close this issue and don't use the issue tracker to ask usage
questions. There
is a mailing list for this.

>
