### ISSUE TITLE
Import .eeg extension

### ISSUE THREAD

**Issue by vitormfreis** [mne-tools/mne-python#6974]
Hi there,

I'm trying to import a '.eeg' file, I tried to use the BrainVision methods find here: https://www.youtube.com/watch?v=_TLDW5hlveI, however I had no success.

Does anyone knows which method should I use in this case? Or if someone could provide some example I would appreciate.

Best regards.

**Comment by jasmainak** [comment]
These are not the official docs. Please consult the official docs here:

https://mne.tools/stable/python_reference.html

and look for "brainvision" there. Furthermore, usage questions should be directed to the mailing list: https://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis. Closing issue for that reason.
