### ISSUE TITLE
Getting  Error while trying to read EDF file

### ISSUE THREAD

**Issue by fsultana44** [mne-tools/mne-python#6978]
I am  very  new user in MNE python. Resently I have started a project work that is related to EEG data analysis.And started to this analysis using MNE,but whenever I rund the below code to read edf file 
```
import os
import mne
sample_data_folder =("\\Users\\user\\Downloads\\ EEG recordings")
sample_data_raw_file = os.path.join(sample_data_folder, ' EEG recordings', '03062019 1',
                                    '1b09e70a-92b1-47b5-bf39-c9378374007b.edf')
raw = mne.io.read_raw_edf(sample_data_raw_file,preload = True )
```

I got the error massage `ValueError: not enough values to unpack (expected 3, got 0)`
Here is my mne system information
```
Platform:      Windows-10-10.0.18362-SP0
Python:        3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Executable:    C:\Users\user\Anaconda3\python.exe
CPU:           Intel64 Family 6 Model 58 Stepping 9, GenuineIntel: 4 cores
Memory:        7.9 GB

mne:           0.19.0
numpy:         1.16.5 {blas=mkl_rt, lapack=mkl_rt}
scipy:         1.3.1
matplotlib:    3.1.1 {backend=module://ipykernel.pylab.backend_inline}

sklearn:       0.21.3
numba:         0.45.1
nibabel:       2.5.1
cupy:          Not found
pandas:        0.25.1
dipy:          1.0.0
mayavi:        Not found
pyvista:       Not found
vtk:           8.2.0
```
I could not figurq out what is wrong here

**Comment by cbrnr** [comment]
Hello!

What is the value of sample_data_raw_file? Maybe you need to prepend C: to your sample_data_folder since this doesn't seem to be a valid Windows path. Furthermore, you might need to replace all \ with regular /.

Clemens

**Comment by cbrnr** [comment]
Alright, it looks like the function cannot parse the EDF header correctly. Could you share this EDF file with me so I can have a look?

**Comment by fsultana44** [comment]
Hi @cbrnr, you are right.In my *.edf file  date and time was invalid that's why the function could not work. After fixing the date and time the mne is able to read this edf file and no error showing anymore.
But I am wondering that when I plotted my raw edf file I got some wired picture.I have attached the picture in below.
![03062019 2](https://user-images.githubusercontent.com/51081858/68107319-213f1f80-feed-11e9-87cb-99811f6064df.png).
I think it might not related to mne, but it will be very helpful if I get some help regarding this issue.

**Comment by cbrnr** [comment]
This is probably not an MNE issue - it looks like your data was recorded without a highpass filter, which is why you see large slow changing offsets. Try plotting the data with `raw.plot(highpass=1)`.

**Comment by cbrnr** [comment]
I'm closing this because the original issue has been resolved. If you have more questions not directly concerning MNE specifics feel free to use our mailing list.

**Comment by HassaniAtefe** [comment]
I am a new user in MNE python. I have started to analysis 'EDF' file using MNE, but whenever I rund the below code to read  'EDF'  file and covert to raw data. but I got this error.
my code:

import os
import mne
raw  = mne.io.read_raw_edf('Data/EDF/d1.edf')
data = raw.get_data()

Error:

ValueError: invalid literal for int() with base 10: 'f¦ó»Ï\x0c\x89;'

**Comment by cbrnr** [comment]
@HassaniAtefe please try opening your file with [EDFbrowser](https://www.teuniz.net/edfbrowser/) to verify that it is a valid EDF file.

**Comment by HassaniAtefe** [comment]
@cbrnr I appreciate you for responding, thank you so much.
