### ISSUE TITLE
Average multiple runs (separate raw files) 

### ISSUE THREAD

**Issue by nithyar89** [mne-tools/mne-python#6984]
Hi,

I am analyzing some resting state MEG+EEG data that has been saved as separate runs within the same day for the same subject. Should I preprocess each MEG run separately and compute separate forward solutions. What is the best way for averaging multiple runs and is there an example that you could point to?

**Comment by jasmainak** [comment]
Hi for usage questions you should go to the mailing list: https://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis so others can benefit from the answer. Please ask it there
