### ISSUE TITLE
BUG: segmentation fault with mne.gui.coregister

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#6995]
I get a segmentation fault error if I have > 20 subjects and I update the digitization source on a fresh mac install.

I tried with pylab= wx and qt

**Comment by larsoner** [comment]
I have a directory with about 130 subjects (at least according to `ls -ld */ | wc -l` and a quick look at the drop-down) and `mne coreg -d $MY_DIR` works just fine. No large memory or CPU use, either.

Maybe it's not the number of subjects but rather one particular subject that is problematic?

**Comment by larsoner** [comment]
(I also updated the FIF dig source a couple of times and it updated the subject it was trying to use just fine. But maybe on your system it does not garbage collect something properly...)

**Comment by kingjr** [comment]
I get a segmentation fault every X subjects. As long as the intended
subject is loaded first it's fine, but when I change subject, it crashes
30% of the time.

So no, it's not the number of subjects, but there s still something wrong
