### ISSUE TITLE
Read empty txt annotations

### ISSUE THREAD

**Issue by AdoNunes** [mne-tools/mne-python#7012]
Hi

If the .txt annotation file is empty it gives a ValueError: not enough values to unpack (expected 3, got 0)

Sometimes, at least for me, it is useful to write empty files to keep track of steps already done. 
A simple option would be to add a try and except assigning empty values to the onset duration and desc.

What do you think?

This issue is similar to #6209

**Comment by agramfort** [comment]
@AdoNunes please provide a basic code snippet we could use to replicate the error and make later a test. thanks

**Comment by AdoNunes** [comment]
The snippet:

`from mne.annotations import Annotations,  _read_annotations_txt                                                                                                                                                            
Annot = Annotations([],[],[])                                                                                                                                                             
Annot.save('filename.txt')                                                                                                                                                                
_read_annotations_txt('filename.txt')    `
   
This seems to happen only for .txt

@agramfort in these cases, should I just do a PR directly or always first create an issue?

**Comment by agramfort** [comment]
If you can do the PR it’s great 

Issue first is better

Thanks
