### ISSUE TITLE
How to extract coordinates of a particular layout?

### ISSUE THREAD

**Issue by fishbacp** [mne-tools/mne-python#7046]
I apologize is this question is one I should post on elsewhere, e.g. stackoverflow.

Given a layout, such as "standard_1020," is there a feature to determine the (x,y) coordinates of each electrode?

I'm asking because I wish to use networkx to plot the nodes (EEG channels) using the precise coordinates as opposed to one of networkx' built-in layouts. This will help for purposes of visualizing various network phenomena, e.g. centralities. 

My raw.info does not include the locations.

**Comment by agramfort** [comment]
@fishbacp please done use the issue tracker to ask usage questions. There is a mailing list 
https://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis
and a gitter channel https://gitter.im/mne-tools/mne-python
