### ISSUE TITLE
RuntimeError: No digitization points found.

### ISSUE THREAD

**Issue by brinda3093** [mne-tools/mne-python#7047]
I am trying to plot the ICA for a set of data from a MAT file. However, I do not have the montage or the .info file for the data. 
Is there any method by which I can check the ICA of the data ?

**Comment by agramfort** [comment]
please don't use issue tracker for asking usage questions.
Use gitter or the MNE mailing list

See https://github.com/mne-tools/mne-python/pull/6938
or https://mne.tools/stable/auto_tutorials/simulation/plot_creating_data_structures.html#sphx-glr-auto-tutorials-simulation-plot-creating-data-structures-py

if it can help
