### ISSUE TITLE
ENH: Store `info` dates as `datetime` objects

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#7052]
In principle there is no reason we can't store `info['meas_date']` and other date entries as `datetime` objects. @agramfort proposed this and it makes sense to me. On read we convert to `datetime` and on write we convert to what the FIF format wants to see.

I can work on it if people agree it's worthwhile.

**Comment by cbrnr** [comment]
Good idea!

**Comment by jasmainak** [comment]
what's the advantage of doing so?

**Comment by larsoner** [comment]
`info['meas_date']` is easily interpretable by users, we hide the complications of the FIF format from them (they don't need to know the details)

**Comment by jasmainak** [comment]
good idea!

should be done also for birthday?

**Comment by larsoner** [comment]
If it falls under the "and other date entries" in the issue description I would say so. Basically anything we currently represent using tuple-of-int-as-date we should convert.

**Comment by agramfort** [comment]
this is now done too.
