### ISSUE TITLE
BUG/DOC: SSS origin

### ISSUE THREAD

**Issue by jjnurminen** [mne-tools/mne-python#7065]
Hi,

I was fooling around with `mne.preprocessing.maxwell._sss_basis*`, which take an origin parameter for the vector spherical harmonics.

According to the docstring, the origin is given in millimeters. However moving the origin by `[0, 0, 1]` which should give a very modest effect, I get a drastically different SSS basis. Therefore, I suspect that the origin is actually in meters. Also it seems that the functions simply subtract the origin from `rmags` which seem to be in meters. So, can you confirm that the doc is wrong on this?

**Comment by larsoner** [comment]
Yes we do everything in meters, PR welcome to clarify
