### ISSUE TITLE
MNE Plot_Raw Showing Unit Label Conflict w/ YLabels

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-python#7068]
## Describe the problem
When I plot using raw.plot(), there is a line specifying units that conflict w/ the y labels.

See here.
![image](https://user-images.githubusercontent.com/3460267/68997114-d3bd9d80-0870-11ea-88a1-56da46bfe239.png)

#### Describe your solution
Is it possible to make this either on the other side of the plot, somewhere else altogether, or make it optional?

**Comment by drammock** [comment]
You can turn that on and off. I forget off the top of my head what the key is, but if you push the "?" key while the plot is focused you'll get a list of all the keyboard shortcuts.

**Comment by adam2392** [comment]
I guess my issue is that I would like to see it and it is useful, but there is no way to put it somewhere else, or dynamically change it's size?

It's nice and out of the way when I have say only 5-10 channels showing, but when I have more, it gets in the way of the first channel text.

**Comment by agramfort** [comment]
did you change manually the font sizes of matplotlib? another option is to
show less sensors it should expand on yaxis. Or we need to tweak to shift
if down a tiny bit. I don't see how to fix it with guarantees otherwise

>

**Comment by cbrnr** [comment]
@adam2392 you can press "s" to toggle the scale bars. Currently, there is no argument to turn them off in the `raw.plot()` call though.

**Comment by adam2392** [comment]
Okay no problem. Visualization is always tough to functionalize in my exp. 

I would say a programmatic option to turn off the unit scale would be helpful tho in general. If you think this is easy enough / okay to add in, I’d be willing to submit a PR.

If not, we can close this off.

**Comment by drammock** [comment]
I would be OK with a `show_scale_bars` param (or maybe just `scale_bars`?) that defaults to `True` for backward compat.

**Comment by cbrnr** [comment]
👍 for `scale_bars=True`, @adam2392 PR welcome!
