### ISSUE TITLE
[ENH] Example for plot_evoked_field

### ISSUE THREAD

**Issue by alexrockhill** [mne-tools/mne-python#7069]
I didn't see any examples for plot_evoked_field. That might be helpful to have if it's not too many examples/much bloat.

**Comment by agramfort** [comment]
see at the bottom
https://mne.tools/dev/auto_tutorials/evoked/plot_visualize_evoked.html#sphx-glr-auto-tutorials-evoked-plot-visualize-evoked-py

>

**Comment by alexrockhill** [comment]
Didn't see it already existed https://mne.tools/stable/auto_tutorials/evoked/plot_visualize_evoked.html#sphx-glr-auto-tutorials-evoked-plot-visualize-evoked-py
