### ISSUE TITLE
minor issue - install python on window

### ISSUE THREAD

**Issue by virvw** [mne-tools/mne-python#7075]
Hi from Hackhathon Brainthemind Nov 2019 # 2
When following instructions here: 
https://mne.tools/stable/install/mne_python.html#installing-python

1) command lines like "which" may not work in windows but it is fine

2) python -c 'import mne; mne.sys_info()'
window users should use
python -c "import mne; mne.sys_info()"

**Comment by larsoner** [comment]
Thanks for the info, see #7076
