### ISSUE TITLE
misleading info message in compute_rank

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#7088]
in reviewing #7085 I noticed the output of running `mne.compute_covariance(epochs, ...)` yields the info message 

> Computing data rank from raw with rank=None

Looks like `mne.compute_covariance` converts `epochs` to a numpy array (let's call it "data"), and then `_compute_covariance_auto(data, ...)` calls `compute_rank(RawArray(data.T, ...), ...)`.  So the message will always say you're computing from "raw" regardless of whether you pass in `Raw` or `Epochs`

**Comment by larsoner** [comment]
Yeah it should probably say "Computing rank from data with rank=None" or so, feel free to put it in some PR
