### ISSUE TITLE
BUG: printing the info on windows date time

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#7116]
Yesterday, at the practical MEEG workshop, we made a striking discovery.

On several Windows computers, ```print(raw.info)``` led to an error pointing at a problem with the date fields. We used anonymized data, which may be at the core of the issue as dates and times may have been implausible.

I hope some of the attendees of our workshop can comment on this by providing a traceback of the error.

@agramfort @larsoner

**Comment by dengemann** [comment]
Here's a screenshot (thank you Tal!):

![image-2](https://user-images.githubusercontent.com/1908618/70160899-84be9780-16bb-11ea-92d4-4a38d82916bb.png)

**Comment by larsoner** [comment]
What is the `info['meas_date']` here?

**Comment by agramfort** [comment]
1941-03-22 11:04:14 GMT

> raw.info['meas_date']
(-908196946, 988669)

**Comment by larsoner** [comment]
This was actually fixed already in `master` by #7036
