### ISSUE TITLE
Formatting Error:

### ISSUE THREAD

**Issue by RoopiniVenkat** [mne-tools/mne-python#7123]
How to print Qobj elements (very low) without rounding off to zero ? 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~/anaconda3/lib/python3.7/site-packages/qutip/qobj.py in _repr_latex_(self)
    848             for m in range(5):
    849                 for n in range(5):
--> 850                     s += _format_element(m, n, self.data[m, n])
    851                 s += r' & \cdots'
    852                 for n in range(N - 5, N):

~/anaconda3/lib/python3.7/site-packages/qutip/qobj.py in _format_element(m, n, d)
    837                     return s + _format_float(np.imag(d)) + "j"
    838                 else:
--> 839                     s_re = _format_float(np.real(d))
    840                     s_im = _format_float(np.imag(d))
    841                     if np.imag(d) > 0.0:

~/anaconda3/lib/python3.7/site-packages/qutip/qobj.py in _format_float(value)
    822             elif abs(value) > 1000.0 or abs(value) < 0.001:
    823                 return ("%.3e" % value).replace("e", r"\times10^{") + "}"
--> 824             elif abs(value - int(value)) < 0.001:
    825                 return "%.1f" % value
    826             else:

ValueError: cannot convert float NaN to integer

**Comment by larsoner** [comment]
This does not seem to be a bug with `mne` but with `qutip`
