### ISSUE TITLE
VIZ: bug in plot_sensors(kind='3d')

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#7136]
#### Describe the bug
When plotting MEG and EEG sensors at the same time, the EEG and MEG sensors appear in the wrong position relative to one another.  Presumably this is an issue of which coordinate frame is chosen.  An example is [here](https://mne.tools/dev/auto_tutorials/epochs/plot_20_visualize_epochs.html#plotting-sensor-locations), where the EEG sensors are higher up than the MEG sensors (implying that the subject's head was embedded in the MEG helmet).

#### Steps to reproduce
See [the linked tutorial](https://mne.tools/dev/auto_tutorials/epochs/plot_20_visualize_epochs.html#plotting-sensor-locations).

@agramfort WDYT?  @larsoner suggested (offline) that if `ch_type='all'` then everything should get transformed to head coords, but if only plotting a single sensor type we can plot in whatever coord sys they're in.  If the overhead is not too bad, I might suggest always plotting in head coords, even if only one sensor type is chosen.  As an aside, it might also be good to label the 3d plot axes with a unit (meters).

**Comment by agramfort** [comment]
+1 with what @larsoner suggested.

>

**Comment by larsoner** [comment]
> If the overhead is not too bad

Transform overhead should be negligible.

> I might suggest always plotting in head coords, even if only one sensor type is chosen.

I was actually starting to think the same thing. So I would say to always use head coords for now, and if people want MEG sensors in MEG coords we can add `coord_frame` later -- or just tell them to use `plot_alignment` which already has these transform options built in.

>  As an aside, it might also be good to label the 3d plot axes with a unit (meters).

Agreed, feel free to add this at the same time as the coord frame changes
