### ISSUE TITLE
BUG view param in brain plot with pyvista

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#7143]
see
https://mne.tools/dev/auto_examples/inverse/plot_time_frequency_mixed_norm_inverse.html
vs
https://mne.tools/0.18/auto_examples/inverse/plot_time_frequency_mixed_norm_inverse.html

view medial parameter is ignored with pyvista backend.

cc @GuillaumeFavelier

**Comment by GuillaumeFavelier** [comment]
It's fixed now. I'll close this.
