### ISSUE TITLE
ICA algorithms problem

### ISSUE THREAD

**Issue by dalinzhangzdl** [mne-tools/mne-python#7152]
Hi, I want to use the 'picard' ICA algorithms. but when I used it, the error "ModuleNotFoundError: No module named 'picard'" happened. How can I solve it?

#### Additional information
 "ModuleNotFoundError: No module named 'picard'"

**Comment by cbrnr** [comment]
You need to `pip install python-picard`.

**Comment by agramfort** [comment]
reopen issue if it does not work @dalinzhangzdl
