### ISSUE TITLE
Compute all-to-all connectivity in sensor space issue

### ISSUE THREAD

**Issue by Charlesi8** [mne-tools/mne-python#7159]
hi, 
 i just ran the Compute all-to-all connectivity in sensor space .py but here came a ValueError :'zero-size array to reduction operation maximum which has no identity'  . I cannot fix it ,so could someone help me please.
![image](https://user-images.githubusercontent.com/21119592/71474337-f2229b80-2815-11ea-93c1-d8cfb2a37c73.png)

**Comment by agramfort** [comment]
is it running just the example script online or using your own data?

**Comment by Charlesi8** [comment]
i downloaded the example script without amendment then ran.

**Comment by agramfort** [comment]
I don't have the problem. Can you say what

mne.sys_info()

gives you?

**Comment by Charlesi8** [comment]
<img width="796" alt="无标题" src="https://user-images.githubusercontent.com/21119592/71504951-55fca100-28b6-11ea-8d9e-4bb447c2c37e.png">

**Comment by agramfort** [comment]
sorry I cannot replicate. Can you ask a friend to replicate with his
machine? or maybe can
you try on a different machine?

>

**Comment by Charlesi8** [comment]
ok, thanks for your advice , and i am thinking to run on another machine.

**Comment by larsoner** [comment]
Closing due to non-response. FWIW the reduction error happens when the array is empty, i.e., `con_val` must be a zero-length array.
