### ISSUE TITLE
AttributeError: 'Figure' object has no attribute 'lasso'

### ISSUE THREAD

**Issue by lxdfrank** [mne-tools/mne-python#7161]
**READ THIS FIRST:** When I run the plot_40_sensor_locations.py, a question of no attribute 'lasso' is appearing. and how to solve it

**Comment by agramfort** [comment]
is it an error or a warning?

matplotlib backend are you using? can you report what mne.sys_info()
outputs?

>

**Comment by lxdfrank** [comment]
![捕获](https://user-images.githubusercontent.com/20570845/71507541-d70c6600-28bf-11ea-921a-db5d4460e632.JPG)
This is the error result。 The Figure object has no attribute lasso

**Comment by lxdfrank** [comment]
> is it an error or a warning? matplotlib backend are you using? can you report what mne.sys_info() outputs?
> […](#)

![捕获](https://user-images.githubusercontent.com/20570845/71507616-176be400-28c0-11ea-95ee-5685722125c6.JPG)
This is the error result。 The Figure object has no attribute lasso

**Comment by agramfort** [comment]
can you make sure you use qt matplotlib backend and that you have a recent
matplotlib version?

>

**Comment by lxdfrank** [comment]
the version of matplotlib is 3.1.1

**Comment by agramfort** [comment]
what does mne.sys_info() give you?

I suspect it comes from a weird choice of matplotlib backend

**Comment by lxdfrank** [comment]
> what does mne.sys_info() give you? I suspect it comes from a weird choice of matplotlib backend

![捕获](https://user-images.githubusercontent.com/20570845/71515215-20b77980-28dd-11ea-92b7-dd0a4b423fa4.JPG)
and how to modify

**Comment by agramfort** [comment]
can you start ipython and from there run

%run plot_40_sensor_locations.py

this will run the example in interactive mode.

>

**Comment by larsoner** [comment]
Closing due to non-response
