### ISSUE TITLE
bem._prepare_env()'s `requires_freesurfer` argument

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#7195]
Commit https://github.com/mne-tools/mne-python/commit/799c2ecb74604ad0ab432b6cee5739dca5c85ca6 removed the use of the `requires_freesurfer` parameter inside `bem._prepare_env()`; yet, it's still a required argument of the function itself. I wonder if that was intentional (if so, what was the reasoning?) or @larsoner just overlooked something there?

**Comment by agramfort** [comment]
maybe it's required by the public function calling this private one so it
was redundant?

>

**Comment by larsoner** [comment]
It looks like `require_freesurfer=True` is always set. I probably meant to remove it in the function and in the calls to the function but forgot.

**Comment by hoechenberger** [comment]
I can probably it in #7196 too
