### ISSUE TITLE
Subject Info Should Have Age In Addition to Birthday?

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-python#7210]
#### Describe the problem
In `subject_info` of the ``Info`` data structure, there is a birthday for a subject, but generally birth dates are anonymized because it is more identifiable. Would it be better to have an "age" identifier instead?

#### Describe your solution
Either replace "birthdate", or add "age".

**Comment by agramfort** [comment]
the recommended way to anonymize is to shift by a random duration all dates
in a file. This is what current master code does so I think we are good
already.

>

**Comment by adam2392** [comment]
Sounds good! I will close this then.
