### ISSUE TITLE
Website documentation link broken in /stable/

### ISSUE THREAD

**Issue by lkorczowski** [mne-tools/mne-python#7217]
Hi,

It has been several weeks that the online documentation links are broken in the /stable/.

e.g.
https://mne.tools/stable/manual/cookbook.html

Unfortunately, from google, all links are pointing to the /stable/ documentation, meaning most of the links from google will be a dead end.

Thanks for the help

**Comment by agramfort** [comment]
this is the new link:

https://mne.tools/stable/overview/cookbook.html

we need to wait for google indexing update

>

**Comment by lkorczowski** [comment]
OK then, if it is out of our hands, I'm closing this issue. Thanks
