### ISSUE TITLE
BUG: Bug with multi-view screen capture

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#7228]
See this example that uses `hemi='split'`, all captured PyVista images are duplicated:

https://mne.tools/dev/auto_examples/visualization/plot_publication_figure.html#sphx-glr-auto-examples-visualization-plot-publication-figure-py

Moreover, once `brain.close()` is called, it should make sure no figures are generated (as they have been closed for that snippet). Compare the above to what used to be produced with `mayavi` produced (one pair of images rather than four pairs):

https://mne.tools/stable/auto_examples/visualization/plot_publication_figure.html#sphx-glr-auto-examples-visualization-plot-publication-figure-py

cc @GuillaumeFavelier can you look into it?

**Comment by GuillaumeFavelier** [comment]
Yep, I'll take care of it.

**Comment by GuillaumeFavelier** [comment]
I reported this behaviour upstream: https://github.com/pyvista/pyvista/pull/548

**Comment by GuillaumeFavelier** [comment]
Unfortunately, I think this might take a while to fix, probably at the next release of PyVista

**Comment by larsoner** [comment]
@GuillaumeFavelier it would be nice not to have our docs have this problem when they go to `stable`. So I think we either need this for 0.20, or we temporarily revert to using Mayavi to build docs during release...

**Comment by larsoner** [comment]
@GuillaumeFavelier should we revert to `Mayavi` on `CircleCI` until this is fixed?

**Comment by GuillaumeFavelier** [comment]
> should we revert to Mayavi on CircleCI until this is fixed?

+1 for this @larsoner, I'll open the PR
