### ISSUE TITLE
mne.find_events returning no stim channel found

### ISSUE THREAD

**Issue by danushaaditya** [mne-tools/mne-python#7229]
Tried running code from this website:
https://mne.tools/0.14/auto_examples/decoding/plot_decoding_csp_eeg.html

ValueError: No stim channel found to extract event triggers.

**Comment by agramfort** [comment]
can you be more explicit? for data that have no stim channels events are
now available in raw.annotations and you can get them with

events, _ = mne.events_from_annotations(raw)

does it fix the issue?

>

**Comment by danushaaditya** [comment]
I tried it, now it shows a new error.
AttributeError: module 'mne' has no attribute 'event_from_annotations'

I'm new to python so i'm not sure what i am doing wrong.
Thanks for helping out

**Comment by drammock** [comment]
You are running an example from version 0.14 of the documentation (look at the URL). Current version of MNE-Python is 0.19. At the very least, make sure your installed version matches the version of the docs you are working from. We also strongly recommend updating to the newest version.

**Comment by agramfort** [comment]
https://mne.tools/stable/generated/mne.events_from_annotations.html

events with an s

>

**Comment by danushaaditya** [comment]
@agramfort Thank you. The 's' was missing. I was being careless.
Thanks a lot for your help.
