### ISSUE TITLE
Problem importing data into EEGLAB

### ISSUE THREAD

**Issue by amitkanthi** [mne-tools/mne-python#7244]
I am facing a peculiar problem while importing .mat and .raw file into EEGLAB.  When I import data using .mat file then the EEGLAB doesn't import the events along with it. When I import data using .raw file then the EEGLAB doesn't show up the reference channel. Moreover, i failed to input the reference channel manually. 
Please help me with this issue.

**Comment by larsoner** [comment]
@amitkanthi this sounds like an EEGLAB problem. I don't think we support writing `.mat` files, only `.fif` files. So perhaps this issue should be raised with EEGLAB support?

**Comment by cbrnr** [comment]
Or did you mean MNELAB (which does support exporting to EEGLAB .set, which is basically just a .mat file)? If so, please report the issue with more details at https://github.com/cbrnr/mnelab.

**Comment by amitkanthi** [comment]
hello

sorry. my bad. Actually its an EEGLAB problem. Extremely sorry for the inconvenience.

thanks. Appreciate your response.
