### ISSUE TITLE
Minor: epoch counts in epochs.plot() starts with 1 instead of 0

### ISSUE THREAD

**Issue by SophieHerbst** [mne-tools/mne-python#7260]
When using `epochs.plot()` to display epochs, e.g. to manually identify bad ones, the epoch numbers displayed on the plot start with 1, not 0, `while epochs.drop()` expects counts to start from 0. 
[I am aware that one can use the interactive plot + annotations to manually reject epochs, but still think it would avoid confusion if the counters match.]

**Comment by agramfort** [comment]
we've had this issue in the past for ICA component numbering.
I think we ended up using 0 based-labels for plots using the # sign.
To be checked...

**Comment by SophieHerbst** [comment]
Yes, at least in my output ICA components are numbered form 0. Can the same be done for the epochs?

**Comment by agramfort** [comment]
+1

**Comment by larsoner** [comment]
Sounds good to me, @SophieHerbst can you make a PR?

**Comment by SophieHerbst** [comment]
I can give it a try in the next couple of days.
