### ISSUE TITLE
ENH: Add pop-up key mapping for PyVista stc.plot

### ISSUE THREAD

**Issue by SophieHerbst** [mne-tools/mne-python#7268]
@GuillaumeFavelier maybe this already exists: is there a way to move continuously through time on an stc, by holding for instance the left/right arrow key?  The playback speed scaler sets the step-size on the time-axis, but I still need to move the mouse across the time scale, which is a bit inconvenient, and hard to do continuously.

**Comment by agramfort** [comment]
did you try pressing space bar?

>

**Comment by SophieHerbst** [comment]
I did not (what a narrow concept of time). Cool!
What is the shortcut to bring up a legend / help ?

**Comment by agramfort** [comment]
>
> What is the shortcut to bring up a legend / help ?
>

it does not exist yet :) to be consistent with other plots it should be 'h'

**Comment by GuillaumeFavelier** [comment]
That would be nice to have considering the number of toggles/shortcuts has increased in TimeViewer. I added this idead in #7162 :+1:

**Comment by larsoner** [comment]
This window that pops up can just be a new / separate `matplotlib` figure like we do in all of our other plotters. @GuillaumeFavelier it might be worth refactoring the code to make a new function that takes a list of `(shortcut, description)` pairs and pops up a new window with the list.

**Comment by GuillaumeFavelier** [comment]
If we plan to reuse `MplCanvas`, this requires https://github.com/mne-tools/mne-python/pull/7247 to be merged

**Comment by larsoner** [comment]
I wouldn't reuse `MplCanvas`, I would actually pop up a window for this one. So you can just do a new `plt.figure`
