### ISSUE TITLE
autoreject() usage and channel information

### ISSUE THREAD

**Issue by neerajww** [mne-tools/mne-python#7291]
#### autoreject() usage and channel information
The ar.fir_transform() gets hanged if the channel location has 'nans'.  Example:
ar = AutoReject()
epochs_clean = ar.fit_transform(epochs) 
Running autoreject on ch_type=eeg
0.00% Creating augmented epochs   (struck here)

#### Expected results
Throwing an error and the reason will be better.

**Comment by jasmainak** [comment]
you should raise it here: https://github.com/autoreject/autoreject/issues. Thanks a lot

**Comment by neerajww** [comment]
Okay, moved now.
