### ISSUE TITLE
showing channel names on topomap

### ISSUE THREAD

**Issue by neerajww** [mne-tools/mne-python#7296]
####  Sorry found it working now. Below is the code.
```
import numpy as np
import mne
from mne.viz import plot_topomap
tempweights = np.random.rand(128) # 128 channels of arbitrary EEG data
egimontage = mne.channels.read_montage('GSN-HydroCel-128')
tempinfo = mne.create_info(egimontage.ch_names[3:], 1000, ch_types='eeg', montage=egimontage)
plot_topomap(tempweights, tempinfo, sensors=True, show_names = True, names = tempinfo["ch_names"], size=30)
```
Is there a way to change the font size of the channel names on the topomap.

**Comment by drammock** [comment]
This is not a bug or feature request, it is a question about usage.  Please use the [MNE mailing list](http://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis) or the [gitter channel](https://gitter.im/mne-tools/mne-python) for such questions.
