### ISSUE TITLE
URL in GitHub project description should point to https://mne.tools

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#7301]
Currently still pointing to http://martinos.org/mne/

<img width="860" alt="Screen Shot 2020-02-09 at 08 21 40" src="https://user-images.githubusercontent.com/2046265/74098199-95edaf80-4b15-11ea-9c9b-a78751eceaff.png">

**Comment by larsoner** [comment]
Fixed, thanks @hoechenberger
