### ISSUE TITLE
Remove window title decoration from new _TimeViewer

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#7316]
### Describe the problem
The new `_TimeViewer` by @GuillaumeFavelier  adds its own window title row, which is odd at least on macOS when not running in full screen mode, as the titlebar added by the operating system has the exact same name, so there's now redundant information:

<img width="841" alt="Screen Shot 2020-02-13 at 18 15 28" src="https://user-images.githubusercontent.com/2046265/74460486-400a6600-4e8d-11ea-98cc-ed43f179b62b.png">
<img width="512" alt="Screen Shot 2020-02-13 at 17 58 02" src="https://user-images.githubusercontent.com/2046265/74460497-44368380-4e8d-11ea-963d-5f66d599148f.png">

#### Describe your solution
The title should be switched off by default, at least on macOS.

**Comment by GuillaumeFavelier** [comment]
Thanks for reporting! It might be difficult for me to debug this one at the moment since it happens on macOS but I'll see what I can do. Also, I will link this to #7162

**Comment by larsoner** [comment]
@GuillaumeFavelier maybe you can sit with @hoechenberger and get this fixed for 0.20?

**Comment by hoechenberger** [comment]
Let's look into this together tomorrow morning, @GuillaumeFavelier

**Comment by cbrnr** [comment]
I've never tried this, but shouldn't this issue also affect all other platforms? Window title bars on Windows and Linux also contain names, so I'd assume that this also leads to duplicated titles. It's probably best to just remove the custom titles.

**Comment by hoechenberger** [comment]
Good point indeed!

**Comment by hoechenberger** [comment]
We couldn't reproduce this on Linux and macOS with different versions of (Py)Qt and PyVista. Seems the issue has magically disappeared since I'd first reported it...
Closing for now!
