### ISSUE TITLE
sphere argument in plot_topomap does nothing

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-python#7341]
I'm on the latest master and I am using the `sphere` argument in `plot_topomap` and it seems to do nothing for a range of values. See:

```py
import mne
from mne.datasets import sample

data_path = sample.data_path()
fname = data_path + '/MEG/sample/sample_audvis-ave.fif'
evoked = mne.read_evokeds(fname, condition='Left Auditory', baseline=(None, 0))

evoked.plot_topomap(ch_type='mag', title='mag (original)', time_unit='s', sphere=(0., 0., 0., 0.8))
evoked.plot_topomap(ch_type='mag', title='mag (original)', time_unit='s', sphere=(0., 0., 0., 0.5))
evoked.plot_topomap(ch_type='mag', title='mag (original)', time_unit='s', sphere=(0., 0., 0., 0.1))
evoked.plot_topomap(ch_type='mag', title='mag (original)', time_unit='s', sphere=(0., 0., 0., 0.01))
```

Only the last line did something. This seems a bit unintuitive to me. What values is MNE expecting? Perhaps that should be documented and an error raised if it gets a value that is too large?

**Comment by larsoner** [comment]
Seems like it's probably a bug, the MEG sensors should be scaled up proportionally to the head size (a smaller radius should mean that the outermost MEG sensors get more spread out relative to / farther from the head).
