### ISSUE TITLE
Setting custom_ref_applied for ECoG data

### ISSUE THREAD

**Issue by libertyh** [mne-tools/mne-python#7350]
#### Setting average reference for ECoG data
When using the `raw.set_eeg_reference(ref_channels='average')` to perform a common average reference on ECoG data, the `custom_ref_applied` bool flag in raw.info remains set to `False`. I looked at `io/reference.py` and in the function definition for `set_eeg_reference` it appears that when `_apply_reference` is called, it looks only for channels of type 'eeg' is 'custom_ref_applied' set to `True`. 

Also, in the comments for `_apply_reference`, it appears to say that `info['custom_ref_applied']=True` refers to a "non-CAR" reference, but the test is whether the reference includes EEG electrodes (which it would for an average reference, right?)

My general question then, is, for consistency, should `custom_ref_applied=True` after applying an average reference to ECoG data, or am I misunderstanding the use of this flag?  It seems like a nice marker for whether this operation has happened or not. Happy to help fix if this makes sense.  I see this is similar to this issue: https://github.com/mne-tools/mne-python/issues/6454, but not exactly.

**Comment by agramfort** [comment]
what type of reference would you apply on ECoG data? CAR? The usecase with
ECoG or sEEG has been
really explored that why it's called set_eeg_reference and not
set_reference(ch_type='eeg')

I guess we 'just' need the use case to adjust MNE to behave properly.

**Comment by libertyh** [comment]
For ECoG/sEEG, a CAR is common, but not always done. Sometimes a single reference channel is used (a subgaleal reference, for example, or even a white matter reference). Bipolar reference is also often used clinically. Basically it would make sense for `set_reference` or `set_eeg_reference` to work exactly as it does, but have the ability to set the channel type, as you suggested above.

**Comment by agramfort** [comment]
ok you suggest we need a set_reference(ch_type) and make set_eeg_reference
call set_reference(ch_type='eeg') before deprecating set_eeg_reference()

any objection anyone? Can you give it a shot?

>

**Comment by larsoner** [comment]
Rather than force a deprecation cycle, I would just add a `ch_type` argument to `set_eeg_reference`. It leaves it as a misnomer but since `set_eeg_reference` is mandatory for inverse modeling, it's going to be all over the place for users so the pain of deprecating this function is quite high.

**Comment by hoechenberger** [comment]
> Rather than force a deprecation cycle, I would just add a `ch_type` argument to `set_eeg_reference`. It leaves it as a misnomer but since `set_eeg_reference` is mandatory for inverse modeling, it's going to be all over the place for users so the pain of deprecating this function is quite high.

In that case, I'd prefer @agramfort's proposal sans the deprecation… i.e., add `set_reference()` and simply make `set_eeg_reference()` call `set_reference(ch_type='eeg')`

**Comment by drammock** [comment]
> Rather than force a deprecation cycle, I would just add a `ch_type` argument to `set_eeg_reference`. It leaves it as a misnomer [...]

Could we compromise by setting a longer deprecation cycle? (2 releases? Or even 4?)

**Comment by libertyh** [comment]
FWIW, I don't feel strongly about it being called `set_reference` instead -- intracranial EEG is a subset of EEG, I guess, so semantically it doesn't bother me if that's also the issue.

**Comment by larsoner** [comment]
> Could we compromise by setting a longer deprecation cycle? (2 releases? Or even 4?)

To me it's not about the duration, it's about the cost (amount of code changes people will have to make at some point or another) relative to the gain we (maintenance) and users (usability) get from the change. Here what I see is no maintenance benefit, a tiny usability/discoverability benefit, and a high cost of changing (i.e., any user scripts that involve EEG inverse modeling, or even most that process EEG in general, since these often set references with or without projections).

**Comment by agramfort** [comment]
I anticipate people will want to do it for sEEG too as some point...

>

**Comment by agramfort** [comment]
I am fine keeping set_eeg_reference to avoid breaking too much code

>

**Comment by libertyh** [comment]
Ok I can take a stab at this later!

**Comment by larsoner** [comment]
@libertyh just a heads up that we're looking to release 0.20 in the next couple of weeks so if you want this fix to make it into that release we'll have to iterate somewhat quickly. No rush from our end, though
