### ISSUE TITLE
Number of splits greater than the number of samples

### ISSUE THREAD

**Issue by sustianovich** [mne-tools/mne-python#7355]
I have run a test to try the Autoreject function. I have two issues.

1) When it gets to "autoreject.get_rejection_threshold" funtion it displays me the split-samples error.
Cannot have number of splits n_splits=5 greater than the number of samples: n_samples=2

2) I had to give random values not to have a NaN in epochs.info['chs] so as to run the code. In the  info = mne.create_info(ch_names, sfreq, ch_types) It gives me the NaN values.
RuntimeError: Valid channel positions are needed for autoreject to work

Does anyone know how to proceed. I am stuck with this.
What I want is to use the Autoreject funtion to get out artefact values that comes from an EEG file.

Thank you!

`
import autoreject
import numpy as np
import mne
from functools import partial

num_rows = 5
sfreq = 500.

data = np.random.rand(num_rows, 1000)
ch_names = [str(x) for x in range(5)]
ch_types = ['eeg'] * 5
info = mne.create_info(ch_names, sfreq, ch_types)
raw = mne.io.RawArray(data, info)

events = np.array([[150, 0, 0],
                   [400, 0, 1],
                  [800, 0, 2]])

event_id = {'artefact': 0, 'baseline': 1, 'seizure': 2}

picks = mne.pick_types(raw.info, meg=False, eeg=True, stim=False, eog=False, exclude='bads')
epochs = mne.Epochs(raw, events=events, event_id=event_id, picks=picks, preload=True)

for ch in epochs.info['chs']:
    ch['loc'] = np.random.random_sample(12)

ar = autoreject.AutoReject()
threshes = autoreject.compute_thresholds(epochs, picks=picks, method='random_search',
                              random_state=42, augment=False,
                              verbose='progressbar')

reject = autoreject.get_rejection_threshold(epochs=epochs, ch_types=ch_types)

epochs_clean = ar.fit_transform(epochs)

thresh_func = partial(autoreject.compute_thresholds, picks=picks, method='random_search')
`

**Comment by agramfort** [comment]
can you report your issue here
https://github.com/autoreject/autoreject/issues and close this issue?

>
