### ISSUE TITLE
How do I install v0.20.0(not v0.19) on win10?

### ISSUE THREAD

**Issue by lilexuan** [mne-tools/mne-python#7360]
I followed the procedure on [this page](https://mne.tools/dev/install/mne_python.html#installing-mne-python-and-its-dependencies). But I got the v0.19.2 rather than v0.20.0. What should I do to install v0.20 on win10?
![](https://i.loli.net/2020/02/28/CkyhfRqOSzgcGsZ.png)

the yml.file I download
```
name: base
channels:
- defaults
dependencies:
- python>=3.5
- pip
- mkl
- numpy
- scipy
- matplotlib
- numba
- pyqt>=5.9
- pandas>=0.18
- xlrd
- scikit-learn
- h5py
- pillow
- statsmodels
- jupyter
- pytest
- pytest-cov
- pytest-mock
- pytest-timeout
- joblib
- psutil
- flake8
- spyder
- numexpr
- traits>=4.6.0
- pyface>=6
- traitsui>=6
- pip:
  - mne
  - https://api.github.com/repos/numpy/numpydoc/zipball/master
  - vtk
  - pyvista>=0.23.1
  - mayavi
  - PySurfer[save_movie]
  - dipy --only-binary dipy
  - nibabel
  - nilearn
  - neo
  - pytest-faulthandler
  - pytest-sugar
  - pydocstyle
  - codespell
  - python-picard

```

**Comment by drammock** [comment]
Note: version 0.20 is the *development master*, 19.2 is the most recent stable release. If you still want 0.20, follow [these instructions](https://mne.tools/dev/install/advanced.html#using-the-development-version-of-mne-python-latest-master)
