### ISSUE TITLE
Evoked.times is documented twice

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#7373]
I'm guessing this is due to some clash between different Mixin classes, but I haven't investigated yet.  Here's a screenshot of the docs page: note how `times` shows up twice with two different definitions (both above and below `data`).

![Screenshot_2020-03-03_10-51-03](https://user-images.githubusercontent.com/1810515/75811962-3bc1c200-5d42-11ea-92ec-9352a5d1c44b.png)

**Comment by larsoner** [comment]
The problem is much simpler than all that :)

https://github.com/mne-tools/mne-python/blob/master/mne/evoked.py#L102-L109
