### ISSUE TITLE
stc.plot setting initial_time not working with time_viewer=True (PyVista)

### ISSUE THREAD

**Issue by SophieHerbst** [mne-tools/mne-python#7379]
There is something wrong with setting the initial time for an stc.plot with time_viewer=True (PyVista), it always defaults to the same value. I updated to the latest developers version, but the problem persists. @GuillaumeFavelier, maybe you know why?

```
import mne

mne.viz.set_3d_backend('pyvista')

data_dir = mne.datasets.sample.data_path('/volatile')
subjects_dir = data_dir + '/subjects'
stc_path = data_dir + '/MEG/sample/sample_audvis-meg-eeg'

stc = mne.read_source_estimate(stc_path, 'sample')

# First, morph the data to fsaverage_sym, for which we have left_right
# registrations:
stc = mne.compute_source_morph(stc, 'sample', 'fsaverage_sym', smooth=5,
                               warn=False,
                               subjects_dir=subjects_dir).apply(stc)

stc.plot(hemi='split', subjects_dir=subjects_dir, initial_time=0.,
          size=(800, 600),time_viewer=True)
```

![pyvista_initial_time](https://user-images.githubusercontent.com/6408073/75868869-02a05500-5e09-11ea-903c-e7358be8e8fd.png)

**Comment by GuillaumeFavelier** [comment]
This is definitely a bug, I will report it in #7162 and investigate this. Thanks for reporting @SophieHerbst
