### ISSUE TITLE
Legend does not reflect data for plot_psd

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-python#7395]
#### Describe the bug
`plot_psd` legends appear as grey dashed lines and do not represent the data in figure.

#### Steps to reproduce
This can be seen in the example here... https://mne.tools/dev/auto_examples/time_frequency/plot_compute_raw_data_spectrum.html#plot-a-cleaned-psd

#### Expected results
The second plot in this example from MNE V0.13 shows the behaviour I would expect https://mne.tools/0.13/auto_examples/time_frequency/plot_compute_raw_data_spectrum.html

**Comment by larsoner** [comment]
#7400

**Comment by rob-luke** [comment]
Thank you
