### ISSUE TITLE
BUG topomap grads

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#7404]
```
import numpy as np
import mne
from mne.datasets import sample
data_path = sample.data_path()
raw = mne.io.read_raw_fif(data_path + '/MEG/sample/sample_audvis_raw.fif')
info = raw.load_data().pick('grad').info
data = np.random.randn(204)
mne.viz.plot_topomap(data, info)
```

produces 
![Figure_1](https://user-images.githubusercontent.com/161052/76150213-29c88200-60a8-11ea-917f-73613c1a3d1b.png)

**Comment by mmagnuski** [comment]
That's an artifact of `extrapolate='box'` - it should look better with `extrapolate='head'` or `extrapolate='local'`.

**Comment by agramfort** [comment]
head:
![Figure_head](https://user-images.githubusercontent.com/161052/76159641-efe89180-6122-11ea-8ef3-a7ee39f07752.png)

local:
![Figure_local](https://user-images.githubusercontent.com/161052/76159642-f119be80-6122-11ea-9f4e-6f2cdb8afa6b.png)

so not much success.

**Comment by agramfort** [comment]
@larsoner any suggestion?

**Comment by mmagnuski** [comment]
Ah, I misunderstood your initial issue. I thought the circle shows what is wrong, but it is the head outline. It is weird indeed, I'll take a look at this.

**Comment by mmagnuski** [comment]
It seems that `_pair_grad_sensors` does not take `sphere` as an argument and no sphere-placement is done in general with grad ch type. I'll try fixing that later today.

**Comment by agramfort** [comment]
indeed the bug only appears with grad not mag.

thanks for taking a look

>

**Comment by mmagnuski** [comment]
@agramfort @larsoner 
I'm not sure what should be considered the source of this bug (apart from ignoring `sphere` argument):
* with 'grad', channel positions in info are ignored, only the layout is used
* layout for `'Vectorview-grad'` is not zero-centered, see below:

![image](https://user-images.githubusercontent.com/8452354/76165955-5ab5bf00-615b-11ea-9a96-6e22cf52928e.png)

**Comment by agramfort** [comment]
one should use the same thing as for mag. One should not use layout also in
this case.

>
