### ISSUE TITLE
What does the scaling mean in the compution of PSD?

### ISSUE THREAD

**Issue by waa8128** [mne-tools/mne-python#7405]
I notice that you use the scaling when computing the PSD.
For the scalings, the values you set as follow: {'mag': 1000000000000000.0, 'grad': 10000000000000.0, 'eeg': 1000000.0, 'eog': 1000000.0, 'emg': 1000000.0, 'ecg': 1000000.0, 'misc': 1.0, 'seeg': 1000.0, 'dipole': 1000000000.0, 'gof': 1.0, 'bio': 1000000.0, 'ecog': 1000000.0, 'hbo': 1000000.0, 'hbr': 1000000.0, 'ref_meg': 1000000000000000.0}
And you convert the PSDs by func '_convert_psds' 

> 

    if estimate == 'amplitude':
        np.sqrt(psds, out=psds)
        psds *= scaling
        ylabel = r'$\mathrm{%s/\sqrt{Hz}}$' % unit
    else:   # extimate = 'power'
        psds *= scaling * scaling
        if '/' in unit:
            unit = '(%s)' % unit
        ylabel = r'$\mathrm{%s²/Hz}$' % unit

i want to know that how you set the scaling by the 'eeg', 'eog' and so on? Or just to make the scale of PSD up to 1?

**Comment by agramfort** [comment]
## no usage questions

This appears to be a question about usage, not a bug report or a new feature request. Please use the [MNE mailing list](http://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis) or the [gitter channel](https://gitter.im/mne-tools/mne-python) for usage questions.
