### ISSUE TITLE
TFR plot_joint topo plot broken

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-python#7406]
#### Describe the bug
'plot_joint' for TFR data shows weird topo plots.

#### Steps to reproduce
https://mne.tools/dev/auto_tutorials/time-freq/plot_sensors_time_frequency.html#joint-plot

#### Expected results
https://mne.tools/stable/auto_tutorials/time-freq/plot_sensors_time_frequency.html#joint-plot

**Comment by agramfort** [comment]
same bug as in https://github.com/mne-tools/mne-python/issues/7404

>

**Comment by mmagnuski** [comment]
Fixed in #7411
