### ISSUE TITLE
DOC: add to glossary: whitening

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#7425]
#### Suggested term
whitening

#### Suggested definition
a linear operation that transforms data with a known covariance structure into "whitened data" which has a covariance structure that is the identity matrix (i.e., it creates virtual channels that are uncorrelated and have unit variance).

**Comment by larsoner** [comment]
Sounds good, PR welcome

**Comment by larsoner** [comment]
@drammock it's probably worth incorporating some logic here: https://github.com/scipy/scipy/issues/12446
