### ISSUE TITLE
Channels incorrectly scaled in `ica.plot_components()`

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#7430]
Channel locations are now incorrectly scaled when plotting ICA components with `ica.plot_components()`. Here's what the standard 10-20 layout looks like:

![Figure_1](https://user-images.githubusercontent.com/4377312/76529932-416e8480-6473-11ea-82c2-a09ef4e4cb14.png)

This used to work previously, see e.g. here: 

![](https://cbrnr.github.io/images/ica_components.png)

Interestingly, plotting the montage works:

```python
montage = mne.channels.make_standard_montage("standard_1020")
montage.plot()
```

![Figure_2](https://user-images.githubusercontent.com/4377312/76530202-af1ab080-6473-11ea-8e83-c070554da347.png)

**Comment by larsoner** [comment]
Do you only have channels C5-C6 for example in the middle row? If so it looks like the subselection might be correct (?). But if you have all channels from the 10-20 montage and some are just missing, then that's clearly wrong...

**Comment by cbrnr** [comment]
Hm, I use these channels:

```
["Fz", "FC3", "FC1", "FCz", "FC2", "FC4", "C5", "C3", "C1", "Cz",
 "C2", "C4", "C6", "CP3", "CP1", "CPz", "CP2", "CP4", "P1", "Pz",
 "P2", "POz", "EOG1", "EOG2", "EOG3"]
```

Fz is the most frontal channel, so it looks like the locations are indeed correct, or at least they match the locations in the montage. However, aren't these locations a bit off? I'd expect Fz to be much more frontal on the topomap, or POz much more occipital. Somehow, the previous figure looks more correct to me (which means that in the new montage plot, more channels should be located outside the head circle - I'm assuming that the head border is at the level of the inion at the most).

**Comment by larsoner** [comment]
Closing as dup of #7141, see and/or continue discussion there
