### ISSUE TITLE
Resample en raw or epochs?

### ISSUE THREAD

**Issue by aiaraneda** [mne-tools/mne-python#7433]
Hi.
I working in a EEG signal processing and machine learning for a discriminate two state. In the lab, use an EEGLAB AND BCILAB, but my idea is use mne package. In this moment we will compared the processing (mne vs BCILAB/EEGLAB), but the results its not the same(the idea is use a CSP and see the plot patterns). I think the problem is in the re sample (I will use raw.resample(...)), in the original data takes to EEG machine.  Your recommend re sample en raw or in EPOCHS objects

**Comment by agramfort** [comment]
## no usage questions

This appears to be a question about usage, not a bug report or a new feature request. Please use the [MNE mailing list](http://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis) or the [gitter channel](https://gitter.im/mne-tools/mne-python) for usage questions.
