### ISSUE TITLE
Reading single epochs from a fif file

### ISSUE THREAD

**Issue by hubertjb** [mne-tools/mne-python#7436]
I noticed that reading single epochs is significantly slower when the raw data is saved as a fif file vs. an edf file. Also, the reading time from fif files linearly increases with how far in the recording the epochs are, which is not the case with edf files.

I'm interested in getting this reading time as low as possible since I have to repeatedly load single epochs. I was wondering whether this difference between fif and edf is expected (maybe part of it is due to the lower precision of edf files).

#### Steps to reproduce
I created a gist that creates .fif, .edf and .hdf5 files out of the same fake raw data, and then times the loading of each individual epoch: https://gist.github.com/hubertjb/1b434688dba296d25eba8fab2866a50f

I included direct reading from an hdf5 file as a baseline. 

#### Expected results
I was expecting fif and edf to yield similar results. Specifically, I was expecting the loading time to be more or less constant across the recording for fif. 

#### Actual results
As shown below, reading from fif is slower than from edf, and reading times increase as the epochs get further from the beginning of the recording.
![image](https://user-images.githubusercontent.com/6500858/76554847-efc2fb80-646c-11ea-908a-ccaa2da9bf22.png)

Mean loading times are
{'edf': 0.0028056514029409373,
 'fif': 0.008060473086787204,
 'hdf5': 0.0009250746053807876}

#### Additional information
Platform:      Linux-4.15.0-70-generic-x86_64-with-debian-buster-sid
Python:        3.7.6 (default, Jan  8 2020, 19:59:22)  [GCC 7.3.0]
Executable:    /storage/store/work/hjacobba/miniconda3/envs/braindecode/bin/python
CPU:           x86_64: 72 cores
Memory:        376.5 GB

mne:           0.20.dev0
numpy:         1.18.1 {blas=openblas, lapack=openblas}
scipy:         1.4.1
matplotlib:    3.1.3 {backend=module://ipykernel.pylab.backend_inline}

sklearn:       0.22.1
numba:         0.48.0
nibabel:       Not found
cupy:          Not found
pandas:        1.0.1
dipy:          Not found
mayavi:        Not found
pyvista:       Not found
vtk:           Not found

@agramfort @larsoner

**Comment by larsoner** [comment]
> I was expecting fif and edf to yield similar results. Specifically, I was expecting the loading time to be more or less constant across the recording for fif.

In FIF the raw data are stored in "tags" of (usually) 1 sec duration so in principle I don't see why it should be slower. I agree it's worth looking into. @hubertjb do you want to look into it? If not I can give it a shot

**Comment by larsoner** [comment]
... actually from looking at the FIF code I already suspect a culprit. I'll open a WIP PR.
