### ISSUE TITLE
mne.bem._check_thicknesses reporting indices not distances

### ISSUE THREAD

**Issue by jdue** [mne-tools/mne-python#7453]
Hi

Preparing surfaces for BEM I run `mne.bem._surfaces_to_bem` and it prints the following

    outer skin  CM is   0.35  -3.30 -19.74 mm
    outer skull CM is  -1.36   6.39 -18.15 mm
    inner skull CM is  -0.53 -12.69  31.69 mm
    Checking that outer skull surface is inside outer skin  surface...
    Checking that inner skull surface is inside outer skull surface...
    Checking distance between outer skin  and outer skull surfaces...
    Minimum distance between the outer skin  and outer skull surfaces is approximately 10000.0 mm
    Checking distance between outer skull and inner skull surfaces...
    Minimum distance between the outer skull and inner skull surfaces is approximately 45000.0 mm
    Surfaces passed the basic topology checks.

Clearly, something is up with the distance estimation or rather I think the issue is with `mne.bem._check_thicknesses` in which `mne.surface._compute_nearest` is called like

    min_dist = _compute_nearest(surf_1['rr'], surf_2['rr'], return_dists=True)[0]

however, looking at `_compute_nearest` it returns `out[::-1] if return_dists else out[1]`, thus `out` has distances at 0 and indices at 1. Reversing this and keeping `[0]` retains the indices and not the distances which I suppose is the reason for getting the huge distance estimates above.

Suggested fix: change `[0]` to `[1]` in the call to `_compute_nearest`. Doing so, `mne.bem._surfaces_to_bem` now prints

```
outer skin  CM is   0.35  -3.30 -19.74 mm
outer skull CM is  -1.36   6.39 -18.15 mm
inner skull CM is  -0.53 -12.69  31.69 mm
Checking that outer skull surface is inside outer skin  surface...
Checking that inner skull surface is inside outer skull surface...
Checking distance between outer skin  and outer skull surfaces...
Minimum distance between the outer skin  and outer skull surfaces is approximately    0.4 mm
Checking distance between outer skull and inner skull surfaces...
Minimum distance between the outer skull and inner skull surfaces is approximately    0.7 mm
Surfaces passed the basic topology checks.
```

Best,
Jesper

**Comment by agramfort** [comment]
@jdue can you provide a full code snippet to replicate on sample data so we
can fix it.
If you can it would be appreciate if you can send a PR containing a test.
thanks

>
