### ISSUE TITLE
Update docs and code: set_eeg_reference([]) and the automatic average

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-python#7471]
Based on this the thread on referencing in the [mailing list](https://mail.nmr.mgh.harvard.edu/pipermail/mne_analysis/2020-March/006577.html), I got the idea that the past recommendation to use `set_eeg_reference([])` to prevent MNE from adding an automatic average reference is no longer needed.

Yet throughout the codebase, there are still references to this old behavior (a list follows).

https://github.com/mne-tools/mne-python/blob/25f6e5e097d8492bfcc3abb6e77804d372f68a9d/examples/preprocessing/plot_rereference_eeg.py#L47-L50

https://github.com/mne-tools/mne-python/blob/25f6e5e097d8492bfcc3abb6e77804d372f68a9d/tutorials/evoked/plot_eeg_erp.py#L72-L75

https://github.com/mne-tools/mne-python/blob/25f6e5e097d8492bfcc3abb6e77804d372f68a9d/tutorials/evoked/plot_eeg_erp.py#L93

... and there are many more :-)

Is it worth it to go through the code and remove these wrong docs? 

cc @dominikwelke @larsoner 

PS: Through my browser (Firefox), I get an encryption warning for the MNE mailing list. Just fyi.

**Comment by cbrnr** [comment]
I never understood this behavior anyway, and it would be great if this could be clarified!

**Comment by agramfort** [comment]
cleanup PR is very welcome !

>

**Comment by larsoner** [comment]
Yes we should get this into 0.20, @sappelhoff do you have time for it this week? If not I or maybe @drammock could look

**Comment by sappelhoff** [comment]
Cool, I can do this today. Good deed for the day :)

**Comment by dominikwelke** [comment]
nice, @sappelhoff ! I also planned to open a PR after finishing another project.. too slow :)
