### ISSUE TITLE
How to reject epochs bipolar EOG

### ISSUE THREAD

**Issue by pietro92** [mne-tools/mne-python#7475]
Goodmorning everyone, 

I am new to python and MNE. 

I am trying to replicate a brain vision analyzer pre-processing in MNE. In this pre-processing authors rejected epochs in which horizontal EOG exceeded 30 mV and/or vertical EOG exceeded 60 mV. I'm trying to achieve this result using the command mne.Epochs. However in the reject dictionary I don't know how to specify this double condition.

Ideally I would to write somenthing like that:

reject = dict(eeg = 160e-6, ["VEOG"] = 120e-6, ["HEOG"] = 30e-6) 

epochs = mne.Epochs(raw, events=events[0], event_id=[71, 72], tmin=-0.1, tmax=0.6, proj=True, baseline=(-0.1,0), reject=reject, preload=True)

However in reject dictionary, if I understood correctly,  I can only use one key 'eog'. 

Thank you very much for your help,
Any advice will be usefull,  
Bests, 
Pietro

**Comment by agramfort** [comment]
## no usage questions

This appears to be a question about usage, not a bug report or a new feature request. Please use the [MNE mailing list](http://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis) or the [gitter channel](https://gitter.im/mne-tools/mne-python) for usage questions.
