### ISSUE TITLE
GPU Installation Fail 

### ISSUE THREAD

**Issue by Vatsal-Malaviya** [mne-tools/mne-python#7502]
1. 'MNE_USE_CUDA' is not recognized as an internal or external command,
operable program or batch file.
![image](https://user-images.githubusercontent.com/31595943/77402381-98118200-6dd4-11ea-9c28-8863450ee848.png)

2. 'mne.utils.set_config' is not recognized as an internal or external command,
operable program or batch file.
![image](https://user-images.githubusercontent.com/31595943/77402433-abbce880-6dd4-11ea-8db3-a6ff387d3c5a.png)

Note: 
conda install cupy; was successful
MNE-python installation successful
My notebook has Nvidea RTX 2060

**Comment by drammock** [comment]
The first one didn't work because Bash died not allow spaces around the equals sign when assigning values to environment variables. The second one didn't work because you're trying to run a python command in the Bash shell.

**Comment by Vatsal-Malaviya** [comment]
Issue still prevails 
![image](https://user-images.githubusercontent.com/31595943/77439129-abd8da80-6e0c-11ea-8222-edaee5e3201d.png)

**Comment by Vatsal-Malaviya** [comment]
> The first one didn't work because Bash does not allow spaces around the equals sign when assigning values to environment variables. The second one didn't work because you're trying to run a python command in the Bash shell.

Issue still prevails
![image](https://user-images.githubusercontent.com/31595943/77439341-ed698580-6e0c-11ea-9310-e45625e095f1.png)

**Comment by larsoner** [comment]
Is that actually even a Bash shell? It looks like a windows command prompt based on the `>` end-line character

**Comment by Vatsal-Malaviya** [comment]
It is anaconda prompt snip, I thought the given code snippet was even applicable for Windows machine

**Comment by larsoner** [comment]
All of our code samples are Bash, for windows command prompt shell users -- or users of other shells generally -- you'll need to look up how to set environment variables in your given shell

**Comment by Vatsal-Malaviya** [comment]
I am still a newbie, it will be very helpful if you could guide me in a simple way

**Comment by Vatsal-Malaviya** [comment]
> I am still a newbie, it will be very helpful if you could guide me in a simple way

Can you direct me to the correct syntax to create a new environment variable(MNE_USE_CUDA)?
If that's what you are trying to say in your last message to create the environment variable first and then implement the above code.

**Comment by agramfort** [comment]
maybe this can help http://www.dowdandassociates.com/blog/content/howto-set-an-environment-variable-in-windows-command-line-and-registry/

none of the mne dev work on windows sorry

**Comment by GuillaumeFavelier** [comment]
Windows is not my main OS for dev but here is what I do to set variables on `Windows 10`:

On `Settings`:

![image](https://user-images.githubusercontent.com/18143289/77518459-1f670000-6e7e-11ea-92a5-47ed6bdcaa93.png)

In the search fileld: `Edit environment variables`:

![image](https://user-images.githubusercontent.com/18143289/77518563-4cb3ae00-6e7e-11ea-8fa3-dcd4587cc3a1.png)

Then `New`:

![image](https://user-images.githubusercontent.com/18143289/77518784-a4521980-6e7e-11ea-993f-d86d302bf754.png)

![image](https://user-images.githubusercontent.com/18143289/77518899-d794a880-6e7e-11ea-98b4-c37ba910a6ba.png)

And finally `OK`:

![image](https://user-images.githubusercontent.com/18143289/77518999-01e66600-6e7f-11ea-8d0c-c389958a9de6.png)

Hoping it could be useful.

**Comment by drammock** [comment]
@Vatsal-Malaviya what @GuillaumeFavelier suggested is one way to set environment variables in Windows.  But perhaps easier in your case is to run the second command you tried: `mne.set_config('MNE_USE_CUDA', 'true')`, but run it *in a python interpreter* instead of in the windows command shell.  In other words:

```
(mne) C:\Users\Vatsal\Desktop> python
>>> import mne
>>> mne.set_config('MNE_USE_CUDA', 'true')
```
