### ISSUE TITLE
Website examples after #7520

### ISSUE THREAD

**Issue by GuillaumeFavelier** [mne-tools/mne-python#7526]
I inspected the website frontpage after #7520 and I noticed 3 issues:

1) Taking screenshot with time viewer is not consistent with what we had previously
https://18971-1301584-gh.circle-artifacts.com/0/dev/auto_examples/visualization/plot_publication_figure.html#sphx-glr-auto-examples-visualization-plot-publication-figure-py

![image](https://user-images.githubusercontent.com/18143289/77763381-428ade80-703b-11ea-9643-0eee85cb49ee.png)

2) The titles overlap
https://18971-1301584-gh.circle-artifacts.com/0/dev/auto_examples/inverse/plot_psf_ctf_vertices_lcmv.html#sphx-glr-auto-examples-inverse-plot-psf-ctf-vertices-lcmv-py

![image](https://user-images.githubusercontent.com/18143289/77763395-4b7bb000-703b-11ea-9407-60d7cd66bcaa.png)

3) The figure is still registered after `close()`
https://18971-1301584-gh.circle-artifacts.com/0/dev/auto_examples/visualization/plot_publication_figure.html#sphx-glr-auto-examples-visualization-plot-publication-figure-py

![image](https://user-images.githubusercontent.com/18143289/77763591-9c8ba400-703b-11ea-8e58-d03bd43414fe.png)

**Comment by larsoner** [comment]
Can you make a PR to fix these?

**Comment by GuillaumeFavelier** [comment]
I have something locally, I'll take care of 1)
