### ISSUE TITLE
If first interaction with PyVista plot is a zoom action, a sphere is placed on the brain

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#7534]
#### Describe the bug
In the new PyVista-based viewer in 0.20, if the first interaction with the brain is "swipe up or down" on my trackpack (to zoom), a sphere is placed on the brain as if I had clicked on it. If I first click somewhere else and _then_ start zooming, the problem does not occur. 

#### Steps to reproduce
Plot an STC with the PyVista backend. After the window has opened, place the mouse pointer above the brain and scroll up or down.

#### Expected results
Zoom level should change.

#### Actual results
Zoom level changes and a sphere is placed on the brain.

#### Additional information
Screencast: https://drive.google.com/open?id=1NjRbsh1G4a8x-g9PscAqpEm3eIXkwp_P

```
Platform:      macOS-10.15.4-x86_64-i386-64bit
Python:        3.8.2 | packaged by conda-forge | (default, Mar 23 2020, 17:55:48)  [Clang 9.0.1 ]
Executable:    /Users/hoechenberger/miniconda3/envs/mne-dev-new/bin/python
CPU:           i386: 8 cores
Memory:        16.0 GB

mne:           0.21.dev0
numpy:         1.18.1 {blas=blas, lapack=blas}
scipy:         1.4.1
matplotlib:    3.2.1 {backend=Qt5Agg}

sklearn:       0.22.2.post1
numba:         Not found
nibabel:       3.0.2
cupy:          Not found
pandas:        Not found
dipy:          1.1.0
mayavi:        4.7.1 {qt_api=pyqt5, PyQt5=5.12.3}
pyvista:       0.24.0
vtk:           8.2.0
```

**Comment by GuillaumeFavelier** [comment]
I was able to reproduce this one and I opened #7563, can you try it?
