### ISSUE TITLE
read_raw_brainvision should support mV

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#7537]
While working on https://github.com/bids-standard/pybv/pull/39 (an option to explicitly specify the unit for the exported file), I noticed that `read_raw_brainvision` only supports signals in V, µV or nV, but not mV (https://github.com/mne-tools/mne-python/blob/master/mne/io/brainvision/brainvision.py#L504). Would it be OK if I added the missing mV unit?

**Comment by agramfort** [comment]
sure go for it. We should backport too

**Comment by sappelhoff** [comment]
cool, thanks for finding the issue @cbrnr
