### ISSUE TITLE
Diagonals in the envelope correlation matrix are not 1s

### ISSUE THREAD

**Issue by pshahbasak** [mne-tools/mne-python#7555]
I am using your envelope_correlation.py script for my analysis. I noticed that the diagonal values for the correlation output are not 1s. I have spent some time looking at the code and I think it is because of the demeaning of the 'X' signals (data_mag_nomean = data_mag - np.mean(data_mag, axis=-1, keepdims=True) before computing correlations with orthogonalized 'Y' signals.

Am I correct, or is there a different reason for it?

Thanks.

**Comment by agramfort** [comment]
yes when you orthogonalize it's not anymore a true correlation so diagonal is indeed not 1 anymore. Maybe you can send a PR to clarify to the docstring?
