### ISSUE TITLE
Evoked.plot_topomap() behaves in strange ways when axes is passed

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#7595]
#### Describe the bug
`Evoked.plot_topomap()` produces unexpected behavior for me when I pass an `Axes` object via the `axes` keyword argument.

#### Steps to reproduce
```python
import matplotlib
matplotlib.use('Qt5Agg')

import matplotlib.pyplot as plt
from mne.datasets import sample
from mne import read_evokeds

path = sample.data_path()
fname = path + '/MEG/sample/sample_audvis-ave.fif'

condition = 'Left Auditory'
evoked = read_evokeds(fname, condition=condition, baseline=(None, 0))

times = [0.05]

for colorbar_0, colorbar_1 in zip([False, True, True],
                                  [False, True, False]):
    fig, ax = plt.subplots(2, 2)
    evoked.plot_topomap(times, ch_type='mag', time_unit='s',
                        axes=ax[0, 0], show=True, colorbar=colorbar_0)
    evoked.plot_topomap(times, ch_type='mag', time_unit='s',
                        axes=ax[1, 0], show=True, colorbar=colorbar_1)
```

#### Expected results
Not to sure, actually! But certainly not what I do get :)

##### `colorbar_0 = colorbar_1 = False`
Two figures appear:
<img width="752" alt="Screenshot 2020-04-10 at 18 03 47" src="https://user-images.githubusercontent.com/2046265/79004778-bce85200-7b55-11ea-9706-f34a252547bd.png">
<img width="752" alt="Screenshot 2020-04-10 at 18 03 50" src="https://user-images.githubusercontent.com/2046265/79004792-c2de3300-7b55-11ea-8815-68628a32e4c6.png">

##### `colorbar_0 = colorbar_1 = True`
Two figures appear:
<img width="752" alt="Screenshot 2020-04-10 at 18 03 54" src="https://user-images.githubusercontent.com/2046265/79004818-cd003180-7b55-11ea-8bbd-09b851a3d61d.png">
<img width="752" alt="Screenshot 2020-04-10 at 18 03 57" src="https://user-images.githubusercontent.com/2046265/79004826-d12c4f00-7b55-11ea-94ab-6898cbfa4320.png">

##### `colorbar_0 =True; colorbar_1 = False`
Two figures appear:
<img width="752" alt="Screenshot 2020-04-10 at 18 04 01" src="https://user-images.githubusercontent.com/2046265/79004840-d5f10300-7b55-11ea-996e-85dbe8be3462.png">
<img width="752" alt="Screenshot 2020-04-10 at 18 04 06" src="https://user-images.githubusercontent.com/2046265/79004846-d8535d00-7b55-11ea-96eb-073e70dc7ff2.png">

#### Additional information
```
Platform:      macOS-10.15.4-x86_64-i386-64bit
Python:        3.8.2 | packaged by conda-forge | (default, Mar 23 2020, 17:55:48)  [Clang 9.0.1 ]
Executable:    /Users/hoechenberger/miniconda3/envs/mne-dev-new/bin/python
CPU:           i386: 8 cores
Memory:        16.0 GB

mne:           0.21.dev0
numpy:         1.18.1 {blas=blas, lapack=blas}
scipy:         1.4.1
matplotlib:    3.2.1 {backend=Qt5Agg}

sklearn:       0.22.2.post1
numba:         Not found
nibabel:       3.0.2
cupy:          Not found
pandas:        1.0.3
dipy:          1.1.0
mayavi:        4.7.1 {qt_api=pyqt5, PyQt5=5.12.3}
pyvista:       0.24.0
vtk:           8.2.0
```

**Comment by hoechenberger** [comment]
I think it would make sense to allow users to pass `axes` for the topomaps themselves, and `cbar_axes` to place the colorbars into!

**Comment by agramfort** [comment]
yes either this or require that if colorbar=True then one need to pass
n_axes = n_times + 1 where then last one is chosen
to place the colorbar. Currently I agree it's a mess

>

**Comment by drammock** [comment]
crossref #7586, maybe makes sense to tackle both of these at the same time

**Comment by mmagnuski** [comment]
are you using inline backend? If so use `show=False`.

**Comment by mmagnuski** [comment]
@agramfort 
I don't get missing topos (or duplicated figures) on windows in interactive backend. I was asking about inline because `show=True` shows multi-topo figure too early, so some topos are missing then.

**Comment by agramfort** [comment]
to me the pb here is really about colorbar axes that is too magical now

>
