### ISSUE TITLE
Error in picking EEG channels in Python

### ISSUE THREAD

**Issue by ophelia3** [mne-tools/mne-python#7617]
I have raw EEG (.edf format) with 9 channels and I extracted two of them, C3 and C4, with `raw.pick(['C3','C4'])` but when I try to do some operation on those channels, such as dividing in segments with `epochs = np.reshape(raw, (n_epochs, epoch_len))`, there is always this error: **All picks must be < n_channels (2), got 2** even if I selected only 2 from 9 channels. Why?

**Comment by agramfort** [comment]
raw is not a numpy array. You cannot reshape it like that. At best do:

np.reshape(raw.get_data(), (n_epochs, epoch_len))

>
