### ISSUE TITLE
read_dig_captrack should be renamed: CapTrak (k, not ck)

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-python#7633]
The function [mne.channels.read_dig_captrack](https://mne.tools/stable/generated/mne.channels.read_dig_captrack.html#mne.channels.read_dig_captrack) is for reading Brain Products electrode digitization data in the `bvct` format (=**B**rain**V**ision **C**ap**T**rak).

Apparently we had a typo at some point and now our function reads "captra**ck**" instead of "captra**k**".

I don't know why Brain Products decided to name their device [CapTrak](https://pressrelease.brainproducts.com/captrak/) instead of CapTrack ... but I think we should rename our function to fit the actual device/system that it supports.

**Comment by agramfort** [comment]
+1 with deprecation cycle

>
