### ISSUE TITLE
Tube in _Renderer

### ISSUE THREAD

**Issue by GuillaumeFavelier** [mne-tools/mne-python#7644]
Mayavi and PyVista uses different conventions on the input coordinates to display multiple tubes. This behaviour is not unified in the `_Renderer` API. The consequence is that only one tube can be plotted at a time. 

Related to https://github.com/mne-tools/mne-python/pull/7620#discussion_r412026438

**Comment by rob-luke** [comment]
I have submitted a fix for this in #7620. Hopefully CIs pass

**Comment by larsoner** [comment]
We should leave this open because (as mentioned in #7620) the fix there will be problematic for performance for long tubes. But we can use it until we hit problems

**Comment by larsoner** [comment]
Let's reopen if we find performance issues
