### ISSUE TITLE
ENH: Add volumetric rendering to _Brain

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#7648]
It would be nice to make MixedSourceEstimates and VolSourceEstimates plottable with _Brain instead of just surfaces.

Random ideas:

- Slicer is probably a good resource for ideas, and [context preserving](https://www.slicer.org/wiki/Modules:VolumeRendering-Documentation-3.5) looks cool
- [VTK example](https://lorensen.github.io/VTKExamples/site/Python/Medical/MedicalDemo4/) produces:

    ![Screenshot from 2020-04-21 12-24-59](https://user-images.githubusercontent.com/2365790/79888788-29234b00-83cb-11ea-921f-99240c7f8de2.png)

- A random [ray-tracing lib, MIT license](https://github.com/Gjacquenot/PyRayTracer)
- [A recent issue about it](https://discourse.vtk.org/t/volume-rendering-with-vtk-cpu-based-ok-gpu-based-not-visible/475/8)
- [5-year-old post from VTK folks](https://blog.kitware.com/volume-rendering-improvements-in-vtk/)
- [5-year-old post, using Python](https://pyscience.wordpress.com/2014/11/16/volume-rendering-with-python-and-vtk/)

Alternatively we could go with isocontours, but seems harder to control/configure

**Comment by agramfort** [comment]
#nerdsniping on the way...

>

**Comment by GuillaumeFavelier** [comment]
Another useful source?

https://docs.pyvista.org/examples/02-plot/volume.html?highlight=volume

**Comment by larsoner** [comment]
Yes much more useful!
