### ISSUE TITLE
get_montage and get_coordinates for Raw and Montage objects

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-python#7652]
#### Describe the problem
Once a user has set the montage, then getting the montage itself and data from it is not trivial.

Ideally, the users can get the actual xyz coordinates whether its an array, or dictionary via just a `get` function.

You have to do things like:
1. `ch_locs = raw.info['chs']['loc'][0:3]`
or
2. `ch_locs = [raw.info['dig'][idx]['r'][0:3] for idx in len(raw.info['dig'])]`

In 1., it took me a bit to end up figuring out that the 12 point locations in are not relevant for the most part if I need the xyz coordinates. And the xyz are stored in the first 3 indices. This is at least for iEEG. 

**Note:** In addition, idk if this is on purpose, but the raw.info['dig'] can be not in the same order as raw.info['ch_names'] especially if there was some reordering done when making `ch_pos` for the DigMontage. I don't think it affects internal code, but it further makes it non-trivial if you need access to the coordinates you want to work w/.

#### Describe your solution
An implementation at the Raw level for `get_montage()`, it simply returns the montage that is set for a Raw object, or returns an error message if no montage.

An implementation at the Montage level for `get_coordinates()`, which returns the xyz coordinates in it's 'm' form as a 3D array. 

Ideally it looks like this:

```
montage = raw.montage
ch_locs = montage.get_coordinates()
```

#### Describe possible alternatives
`get_coordinates` could also be at the Raw level?

#### Additional context
See related discussion: https://github.com/mne-tools/mne-bids/pull/393

Happy to submit a PR after discussion of if this is valid.

**Comment by larsoner** [comment]
I would not do `get_montage`, a `montage` is just a way to set channel positions.

I would add a `inst.get_channel_positions()` that for example returned a `dict` of the channel name: pos mapping. It would really just loop over `info['chs']` to look at `loc` but indeed a user should not have to do this.

**Comment by agramfort** [comment]
Get_montage that returns a dig montage that could be fed to set_montage is to me the most consistent. I would like to get all dig points etc

**Comment by larsoner** [comment]
Okay, fair enough

**Comment by drammock** [comment]
I'd also note that `get_ch_positions` (rather than `get_channel_positions`) is more consistent with other methods like `inst.get_ch_types()`.  So if you end up doing both `get_montage` and `get_xxx_positions` then I think `xxx` should be `ch`, not `channel`.

**Comment by cbrnr** [comment]
Although it would be useful if we could extract the name of the original montage somehow (maybe just for the standard montages shipped with MNE).

**Comment by agramfort** [comment]
if you want provenance of the original montage file it's really tricky as
it means changing info
data structures.

>

**Comment by cbrnr** [comment]
We could add a new info field, which contains the montage name every time the user does `raw.set_montage`. Of course, this does not mean that the name and the coordinates match (because the coordinates might have been changed after setting the montage), but something like `info["montage_name"]` would be nice to have. Maybe the value of this field could even be reset to `None` if someone tinkers with the coords, but I don't know if we have setters in place.

Anyway, if this is not feasible it's not that important.

**Comment by agramfort** [comment]
I don't think it's easily feasible

>

**Comment by adam2392** [comment]
Okay so:

- `inst.get_ch_positions()` -> dictionary of channels and their xyz positions. This is pretty clear to me.

> Get_montage that returns a dig montage that could be fed to set_montage is to me the most consistent. I would like to get all dig points etc

@agramfort what do you mean here? Implement a mne.get_montage() function, or an inst.get_montage()?

**Comment by agramfort** [comment]
Inst.get_montage()

**Comment by pchr-srf** [comment]
Sorry to dig up this PR, but what is `Inst` in your code snippet? 😅

**Comment by cbrnr** [comment]
This typically refers to `Raw`, `Epochs`, or `Evoked` (depending on the context).

**Comment by pchr-srf** [comment]
Ah, super quick! Yes, I just found that out, too. Thanks! Helping my partner with some analysis and super confused by everything 😅
