### ISSUE TITLE
Add option to only plot requested properties for plot_filter

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-python#7654]
#### Describe the problem
I would like to just plot one aspect of a filter (e.g. just magnitude). Further I would like to specify the axes the data is plotted on.

#### Describe your solution
Add additional arguments to the function (perhaps... `magnitude`, `phase`, `time`) that change enable/disable plotting of each subplot (all default to True to maintain current functionality).

Add an axes parameter that can be passed in to plot over existing axes ([possibly discussed before](https://github.com/mne-tools/mne-python/blob/master/mne/viz/misc.py#L893)).

#### Describe possible alternatives
Leave as is.

**Comment by larsoner** [comment]
Maybe instead of separate kwargs it can just be `plot=('magnitude', 'phase', 'time')` and the order and members of the iterable determine what is plotted, and `axes=None` if passed must match that length.
