### ISSUE TITLE
Cutting a Signal in a range of samples

### ISSUE THREAD

**Issue by ophelia3** [mne-tools/mne-python#7662]
Hello, I have a signal (edf format) of 503700 samples and I want to cut that signal in order to obtain just a portion of it from sample 600 to sample 501000. How can I do this in python?

**Comment by agramfort** [comment]
This appears to be a question about usage, not a bug report or a new feature request. Please use the [MNE mailing list](http://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis) or the [gitter channel](https://gitter.im/mne-tools/mne-python) for usage questions.
