### ISSUE TITLE
Unable to read EDF file

### ISSUE THREAD

**Issue by tayyabafaisal** [mne-tools/mne-python#7680]
Hello
I'm working on an EEG signal but even after trying several ways, I'm unable to read the dataset.
There is an error  of null values in the header while reading with mne
I have around 200 edf files in the dataset all have the same issue. Can you please identify the issue.

**Comment by cbrnr** [comment]
Can you share one of the problematic files with us?

**Comment by tayyabafaisal** [comment]
Zipped two files.Please check.Hope you can figure out
Thankyou 
[edffiles.zip](https://github.com/mne-tools/mne-python/files/4535089/edffiles.zip)

**Comment by cbrnr** [comment]
Both files work for me with the latest 0.20.1 release - please update MNE and try again.

**Comment by tayyabafaisal** [comment]
Thankyou for your reply 
Im using same version but get this error (check attached)
My script is
import mne
f='0000002.edf'
edf_file = mne.io.read_raw_edf(f, preload = True)

If you can please check my script 
Thankyou
<img width="1132" alt="Screenshot 2020-04-27 at 4 18 38 PM" src="https://user-images.githubusercontent.com/59199087/80366473-c2a69d00-88a2-11ea-8622-7865e1b20d40.png">
<img width="1069" alt="Screenshot 2020-04-27 at 4 19 00 PM" src="https://user-images.githubusercontent.com/59199087/80366497-cf2af580-88a2-11ea-8baf-dc7f2ad8d3dd.png">
<img width="771" alt="Screenshot 2020-04-27 at 4 20 11 PM" src="https://user-images.githubusercontent.com/59199087/80366607-fa154980-88a2-11ea-8ee0-5b8ce3957198.png">


<img width="743" alt="Screenshot 2020-04-27 at 4 17 11 PM" src="https://user-images.githubusercontent.com/59199087/80366330-8e32e100-88a2-11ea-959f-cd4a5657a4ff.png">

**Comment by cbrnr** [comment]
Got it, you're using the current dev version and I can reproduce the error with the current master. I'll try to figure out what change introduced the regression.

**Comment by cbrnr** [comment]
Wait, I made a stupid mistake. In fact, current master still works and correctly loads your example file. Same for 0.20.1. I guess you are referring to the issue reported and fixed in #7641. Prior to 0.20.1, I can indeed reproduce the error.

You are on an outdated master branch. Please either pull the latest changes from `upstream` (your remote might also be called `origin` depending on how you cloned the repo):

```
git pull upstream
```

However, I'd recommend to work with a release version which you can install with `pip`:

```
pip install -U mne
```

**Comment by larsoner** [comment]
Thanks for investigating and explaining @cbrnr

**Comment by tayyabafaisal** [comment]
@cbrnr can you please share script with me
