### ISSUE TITLE
What's New rendering issue

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#7692]
That's with the [0.20 What's New](https://mne.tools/stable/whats_new.html) and occurs with the 0.20.1 and 0.20 changelog:
![Screenshot 2020-04-29 at 08 05 48](https://user-images.githubusercontent.com/2046265/80565290-6c477480-89f0-11ea-883d-8b8b1d9c4b7f.png)

**Comment by agramfort** [comment]
pushed fixed in master. thx @hoechenberger for reporting this
