### ISSUE TITLE
filter_data docs 'upper cutoff frequency' typo

### ISSUE THREAD

**Issue by antonwnk** [mne-tools/mne-python#7696]
#### Describe the bug
The docs of `mne.filter.filter_data` have a typo: both `l_freq` and `h_freq` are said to represent "the upper cutoff frequency" for IIR filters.

#### Steps to reproduce
```
import mne
import pprint
pprint.pprint(mne.filter.filter_data.__doc__)
```
I would submit a PR myself but I don't know how your documentation works.

**Comment by larsoner** [comment]
Any time you see

https://github.com/mne-tools/mne-python/blob/master/mne/filter.py#L754

It just uses something from

https://github.com/mne-tools/mne-python/blob/master/mne/utils/docs.py#L241

Can you make a PR to fix `docs.py`?
