### ISSUE TITLE
Ignore logic of check-manifest 0.42

### ISSUE THREAD

**Issue by GuillaumeFavelier** [mne-tools/mne-python#7721]
Since the release of `check-manifest 0.42`, the ignore logic has changed leading in failures on Azure pipeline style:

![image](https://user-images.githubusercontent.com/18143289/80970661-cfd00880-8e1b-11ea-8400-136a9ac665ce.png)
![image](https://user-images.githubusercontent.com/18143289/80970697-dfe7e800-8e1b-11ea-9a67-40bc5bf1c165.png)

Reference: https://pypi.org/project/check-manifest/0.42/

**Comment by larsoner** [comment]
I'll look into it
