### ISSUE TITLE
libgfortran.so.1

### ISSUE THREAD

**Issue by kambysese** [mne-tools/mne-python#774]
Sometime ago I noticed that my installation of MNE-Nightly-Linux-x86_64 was missing libgfortran.so.1 in the $MNE_ROOT/lib directory. I searched the MNE Analysis archives and found an older post by @Eric89GXL that provided a url for downloading the file. Initially I tried the 64bit version of this file that for some reason was incompatible, but I didn't bother trouble shooting it because the 32 bit version worked on my 64 bit system! Next, I started receiving some thorny python errors related to libgfortran.so.1. Apparently, in the ANACONDA environment @dengemann there is already a version of this library file that is used by various packages, and issues arise when mne_setup_sh sets the environment variable  LD_LIBRARY_PATH to $MNE_ROOT/lib. After considerable effort I resorted to just creating aliases that either (1) set up the MNE environment OR (2) clear LD_LIBRARY_PATH and allow for ANACONDA python environment to run. In hindsight this is not a optimal fix, because now I have to figure out how to e.g., call mne_create_sourcespace in a shell script from python --there is a conflict since both the python environment and MNE  specifically require LD_LIBRARY_PATH and/or libgfortran.so.1 in their "special" way. Has anyone dealt with this? Some insight would be much appreciated.

**Comment by Eric89GXL** [comment]
It looks like people have found workable solutions for this, so I'm going to close.

**Comment by kingjr** [comment]
Encountered the problem again on a recent ubuntu 14.04 + conda install.

It used to work. Not sure what happened in between...

@MadsJensen 's trick fixed it.

**Comment by kambysese** [comment]
@kingjr this issue never went away. I've been linking to libgfortran3.so that comes with anaconda.

**Comment by kingjr** [comment]
We should add something in the FAQ then
