### ISSUE TITLE
error in find_bad_channels_maxwell

### ISSUE THREAD

**Issue by SophieHerbst** [mne-tools/mne-python#7741]
I have an error from find_bad_channels_maxwell that I am not able to fix. 
The file has a BAD_ACQ_SKIP segment at the beginning, but using `skip_by_annotation` did not help. 
Thanks for any hints on how to solve this!

> 
>  File "/home/sh254795/anaconda3/lib/python3.7/site-packages/mne/preprocessing/maxwell.py", line 1950, in find_bad_channels_maxwell
>     ss[-1] = end
> 
> IndexError: index -1 is out of bounds for axis 0 with size 0

You can find the data [here](https://somaxluan.hd.free.fr/nextcloud/index.php/s/FjoscRAJss2LtQG). 

Here is a minimal example:

```
import mne

filename = 'example_badchan_error-raw.fif'

raw = mne.io.read_raw_fif(filename,
                                  allow_maxshield=True,
                                  preload=True, verbose='error')

auto_noisy_chs, auto_flat_chs = mne.preprocessing.find_bad_channels_maxwell(raw,
             limit = 10., verbose=True, skip_by_annotation = 'BAD_ACQ_SKIP')
```

**Comment by agramfort** [comment]
can you share the file so we can debug this?

>

**Comment by larsoner** [comment]
I can see in the code where this can happen if there is some tiny segment of good data, will come up with a test and fix

**Comment by larsoner** [comment]
... actually it looks like the file is shared above already, thanks @SophieHerbst !

**Comment by SophieHerbst** [comment]
It does! awesome, thanks for the fast help @larsoner!

**Comment by gabrielbmotta** [comment]
Does anyone have a link to the file mentioned above? We are trying to fix a similar issue in MNE CPP. Thanks.

**Comment by larsoner** [comment]
@gabrielbmotta you shouldn't need the file above, you should just need to be on latest mne-python `master` dev branch. There is a fix in there already

**Comment by gabrielbmotta** [comment]
@larsoner thanks for the quick response. We don't have that same function in our code, we're still trying to find out where and why a segfault happens when the file was loaded.
