### ISSUE TITLE
ENH: make out_type default to 'indices' for permutation tests

### ISSUE THREAD

**Issue by yh-luo** [mne-tools/mne-python#7779]
#### Describe the problem
Permutation tests may crash when datasets are large (50 time points, oct6, 13 subjects  in my case). `mne.stats.permutation_cluster_1samp_test` with `out_type='mask'` caused memory overflow and the process was killed on a machine with 64GB RAM and 16GB swap. With `out_type='indices'`, the process only used about 4GB RAM.

Since `out_type` is default to `'indices'` for `mne.stats.spatio_temporal_cluster_1samp_test` and `mne.stats.spatio_temporal_cluster_test`, it would be nice that `out_type` in `mne.stats.permutation_cluster_1samp_test`, `mne.stats.permutation_cluster_test` also defaults to `'indices'` to prevent the memory error.

#### Describe your solution
Current:
```mne.stats.permutation_cluster_1samp_test(..., out_type='mask', ...)```

Proposed:
```mne.stats.permutation_cluster_1samp_test(..., out_type='indices', ...)```

**Comment by drammock** [comment]
+1 for this proposal. Another reason: just yesterday I noticed that the default results of `permutation_cluster_test` are not compatible with `summarize_clusters_stc` because it requires `out_type='indices'` in order to work.

**Comment by larsoner** [comment]
I can live with a deprecation cycle to get `out_type` to be consistent across these functions

**Comment by agramfort** [comment]
agreed

>
