### ISSUE TITLE
Divide signal to epochs

### ISSUE THREAD

**Issue by tayyabafaisal** [mne-tools/mne-python#7785]
Hi 
I want to divide raw EEG signals into shorter frames using a standard overlapping window approach. How can I do in MNE python 
<img width="1236" alt="Screenshot 2020-05-14 at 5 15 09 PM" src="https://user-images.githubusercontent.com/59199087/81933222-79767d00-9606-11ea-954e-b3985a3d2cea.png">

**Comment by agramfort** [comment]
This appears to be a question about usage, not a bug report or a new feature request. Please use the [MNE mailing list](http://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis) or the [gitter channel](https://gitter.im/mne-tools/mne-python) for usage questions.
