### ISSUE TITLE
MAINT: remove spyder from environment file?

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#7788]
Seems like every 6-12 months, one of my colleagues says "Spyder won't load, and in trying to fix it I borked my environment, please help."  I'm wondering why we implicitly recommend spyder by including it in our `environment.yml` file.  Spyder also imposes version constraints (e.g., currently it requires `PyQt5<5.13`), which has the potential to cause conflicts / inconsistent environments if (for example) pyvista and spyder impose incompatible dependency constraints.

Shouldn't we leave it up to the end user to pick their IDE?  If not, can we be a bit more intentional about our recommendations?

**Comment by larsoner** [comment]
Okay with me

**Comment by larsoner** [comment]
(to remove it from the environment file I mean)

**Comment by agramfort** [comment]
agreed

**Comment by hoechenberger** [comment]
Should be dropped.
