### ISSUE TITLE
Request for a dedicated reader for Ricoh MEG data (.con files)

### ISSUE THREAD

**Issue by apesquita** [mne-tools/mne-python#7808]
Hello,

I would like to suggest to make it possible to directly read Ricoh MEG system data into MNE python.
Please see the example file attached.

Many thanks!

Ana Pesquita
[010409_Motor_task_coregist-export_tiny.zip](https://github.com/mne-tools/mne-python/files/4666616/010409_Motor_task_coregist-export_tiny.zip)

**Comment by agramfort** [comment]
do you know any open source reader for these files or someone who knows
well the format?

>

**Comment by cbrnr** [comment]
It seems like Fieldtrip (http://www.fieldtriptoolbox.org/getting_started/ricoh/) and Brainstorm (https://neuroimage.usc.edu/brainstorm/) can read Ricoh data.

**Comment by apesquita** [comment]
Hello,

Fieldtrip has some information on these files:
http://www.fieldtriptoolbox.org/getting_started/ricoh/
Is this helpful?

Thanks!

Ana P

**Comment by agramfort** [comment]
we will need a BSD compatible implementation (no GPL code)

>

**Comment by apesquita** [comment]
Hello,

I will try to get info about a BSD compatible implementation reader from the Ricoh company (and link you up with them).
In addition, here is the marker file that belongs to the .con data file.

Many thanks!

Ana P

 
[010409_marker.zip](https://github.com/mne-tools/mne-python/files/4667506/010409_marker.zip)

**Comment by teonbrooks** [comment]
Ricoh is the new owners of the KIT/Yokogawa system. Unless their format has changed, one should be able to use the KIT module we have.

@apesquita, I was able to read in the file linked above. Try using the reader `mne.io.read_raw_kit`, let us know if this doesn't work for you.

**Comment by agramfort** [comment]
indeed I tried:

`raw = mne.io.read_raw_kit('010409_Motor_task_coregist-export_tiny.con')`

and it works fine !

**Comment by apesquita** [comment]
Thanks! I will check it asap with Kyung-Min (somehow I missed this message before). We will keep you posted. Many thanks!

**Comment by apesquita** [comment]
Hello all,

Thank you for your suggestions.
Indeed the mne.io.read_raw_kit seems to open the file.

But when using the mne.viz.plot_alignment we get back a geometry of sensors and helmet that seem to be somewhat misaligned. Please see the pdf in the attachment. 

Have you encountered this issue before?

Many thanks!


![snapshot](https://user-images.githubusercontent.com/49191643/83978623-c5b09680-a900-11ea-8aee-24c09e0dcbad.png)

**Comment by agramfort** [comment]
one cannot see attachments on github

>

**Comment by apesquita** [comment]
> one cannot see attachments on github
> […](#)

Updated previous message. Thanks!

**Comment by Kyung-minAn** [comment]
@agramfort & @apesquita 
This is Kyung-min.
I'm glad to hear that you would make an MNE tutorial for Ricoh data. 
The data is acquired using a child-customized MEG system located in Kanazawa, Japan.
I attach the raw MEG data with auditory stimuli and Freesurfered MRI data by email.

Thanks a lot!!

**Comment by agramfort** [comment]
@Kyung-minAn you cannot attach files on github.

can you make the files available on dropbox or google drive or whatever works?

**Comment by agramfort** [comment]
I started to look into. I can produce meaningful evoked data but I have some issues:
- the KIT reader overwrites the native channel names so using the shared layout files is hard. @teonbrooks or @christianbrodbeck do you know if it's possible to avoid having this forced renaming to MEG001, MEG002 etc...
- should we introduce a new read_raw_xxx function. If so how would you name it? raw_raw_yokogawa, raw_raw_ricoh, raw_raw_con?

anyone would have time to look into this? It's getting too ambitious for me to looking into it myself given the time I have.

**Comment by apesquita** [comment]
Hello,

Many thanks for these developments.
I was wondering if it would be the moment to get the Ricoh engineers in touch with the mne developers?
Min had forwarded some questions from Ricoh to the mne developers:

  1) MNE-Python has 'mne.io.*' functions depending on the type of MEG system to read the data.
   Are you planning to make a 'mne.io.ricoh.*' function?

2) If so, could you please tell me what Ricoh company contributes to it?
   They may provide a primitive script to read binary data ('*-export.con file'), although they cannot contribute much to the development of io/ricoh itself since they are not so familiar with fiff format.

Many thanks!

Ana P

**Comment by agramfort** [comment]
if we can have a Ricoh engineer to help it would be great !

>

**Comment by Kyung-minAn** [comment]
@agramfort 
I sent e-mail with a contact of Ricoh engineer.
Please check it !
And thanks a lot~!!

**Comment by teonbrooks** [comment]
If we can get a clear idea of what would be needed, I might be able to dedicate some spare cycles to get this work and/or coordinate with Ricoh engineers to modify our existing module. 

I wonder what the best nomenclature for the io package should be for Ricoh/Yokogawa/KIT. I 

>     * the KIT reader overwrites the native channel names so using the shared layout files is hard. @teonbrooks or @christianbrodbeck do you know if it's possible to avoid having this forced renaming to MEG001, MEG002 etc...

for the renaming, do we accept MEG channels that don't begin with `MEG`? I know that Fieldtrip naming for the channels are prefixed with AG for the axial gradiometers Ricoh hardware uses.

As for the layouts, can we derive the layout for the MEG system like we do for the EEG ones now?

**Comment by larsoner** [comment]
> for the renaming, do we accept MEG channels that don't begin with MEG

Some `planar1`/`planar2` can break if the naming is wrong for Neuromag systems, but I don't know of any restrictions for other systems. It's best if we can always use the manufacturer's naming as much as possible. So indeed we should not rename things as `MEG*` if they are not named this way on the acquisition system.

**Comment by agramfort** [comment]
I have layout files for Ricoh systems like for other MEG systems. We
'just' need the right channel names :)

**Comment by larsoner** [comment]
@teonbrooks want to take a stab at reading the correct names? Maybe add a `rename=None` param that defaults to `True` in 0.21 (do what we do now) but will be `False` in 0.22 (use the native names) via deprecation?

**Comment by teonbrooks** [comment]
sounds good. yeah, I take a stab at this over the weekend

**Comment by teonbrooks** [comment]
I took a look at this, and we're generating the name of the channels by their index. We don't have the original label information anywhere. It would be super helpful if we could be in touch with someone at Ricoh to see what block in the data may have these labels so we could read them directly. @agramfort, has the Ricoh engineer reached to you yet? If you would like, I could coordinate with them and see if they have this info anywhere. For Ricoh system in FieldTrip, they're using pre-compiled private matlab scripts. It's likely they could share with us how they do so if they have the source files.

**Comment by agramfort** [comment]
let me put you in contact with ricoh engineer

>

**Comment by apesquita** [comment]
Thank you for developing this reader! I will be thrilled to use it later on!

**Comment by apesquita** [comment]
Dear Alexander and Teon,

Did you receive all the necessary information from the Ricoh engineers to put together the mne reader for this system?
Do you think that it will be feasible to develop the mne reader for Ricoh?
Many thanks for any updates on this issue.

All the best!

Ana P

**Comment by agramfort** [comment]
hi,

I started to look and add the reading of the channel names but it will need
more time

I asked for help to @larsoner

we'll make progress in the coming weeks. I think we have all the info we
need and
I could run the code shared with us.

thanks for your patience

>

**Comment by Kyung-minAn** [comment]
Thank you for developing mne readers.
I'm excited about the great news!!
I appreciate your contributions~

Looking forward to hearing from you~!!

Best wishes,
Min

**Comment by larsoner** [comment]
@apesquita channel name reading seems to be working and we can just generate a layout on the fly for your data (with the right constants). I'm at the point that it would help to have a subject's evoked dataset plus MRI to do some source localization on to test alignment, etc.

**Comment by larsoner** [comment]
This should be fixed in `master`

**Comment by Kyung-minAn** [comment]
Hello. @agramfort @larsoner 
I hope you are doing well.

We (with @apesquita ) finally met in Birmingham and tried to import our data from the child-customized MEG at Kanazawa, Japan.
We can read the raw con data using 'mne.io.read_raw_kit', but not the coregistrated data.

The error code is below:

`import mne
raw = mne.io.read_raw_kit('010409_Motor_task_coregist-export_tiny_1s.con')
Extracting SQD Parameters from 010409_Motor_task_coregist-export_tiny_1s.con...
Creating Raw.info structure...
Traceback (most recent call last):

  File "C:\Users\eiren\AppData\Local\Temp/ipykernel_9800/996202582.py", line 2, in <module>
    raw = mne.io.read_raw_kit('010409_Motor_task_coregist-export_tiny_1s.con')

  File "C:\Users\eiren\anaconda3\envs\mne\lib\site-packages\mne\io\kit\kit.py", line 908, in read_raw_kit
    return RawKIT(input_fname=input_fname, mrk=mrk, elp=elp, hsp=hsp,

  File "<decorator-gen-234>", line 24, in __init__

  File "C:\Users\eiren\anaconda3\envs\mne\lib\site-packages\mne\io\kit\kit.py", line 133, in __init__
    info, kit_info = get_kit_info(

  File "<decorator-gen-237>", line 24, in get_kit_info

  File "C:\Users\eiren\anaconda3\envs\mne\lib\site-packages\mne\io\kit\kit.py", line 749, in get_kit_info
    assert meg_done

AssertionError`

I am looking forward to hearing from you.

Many thanks,
Min

**Comment by larsoner** [comment]
Can you share the data with us (link here or over email)?

**Comment by Kyung-minAn** [comment]
@larsoner Thank you for your prompt response!! 
I share a short version of our coregistrated data here. 

[010409_Motor_task_coregist-export_tiny_1s.zip](https://github.com/mne-tools/mne-python/files/6864118/010409_Motor_task_coregist-export_tiny_1s.zip)

Thank you for all your effort!
