### ISSUE TITLE
Raw.anonymize() docstring is irritating

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#7813]
When viewing the docs of `Raw.anonymize()`, I'm confronted with a warning:

> If info is part of an object like raw.info, you should directly use the method raw.anonymize() to ensure that all parts of the data are anonymized and stay synchronized (e.g., raw.annotations).

which is irritating because, well, I **am** reading up on `Raw.anonymize` already. Also see screenshot below.

<img width="1392" alt="Screenshot 2020-05-23 at 10 43 18" src="https://user-images.githubusercontent.com/2046265/82726169-7fddb680-9ce2-11ea-830c-0d2e624324c1.png">

**Comment by hoechenberger** [comment]
Also… what's a "date of service"?

**Comment by agramfort** [comment]
date of service can refer to the date at which the MEG system was checked
by MEGIN.
It's typically once a year.

>

**Comment by larsoner** [comment]
Feel free to modify the docstrings using the `docdict` so that the warning only shows up in the right place

**Comment by bloyl** [comment]
Date of service, in this context refers to `info['meas_date']`

**Comment by agramfort** [comment]
I would consider a rephrasing then. Date of acquisition ?
