### ISSUE TITLE
Magnetometer positions look odd in PSD plot

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#7837]
#### Steps to reproduce
Let's first visualize the magnetometer channel positions via `Raw.plot_sensors()`:
```python
import mne
from mne.datasets import sample


data_path = sample.data_path()
fname = data_path + '/MEG/sample/sample_audvis_raw.fif'
raw = mne.io.read_raw_fif(fname)
raw.plot_sensors(ch_type='mag')
```
This produces:
![sensors](https://user-images.githubusercontent.com/2046265/83051600-85bef900-a04e-11ea-9fe5-fbc2be43c365.png)

Looking good. Now let's plot PSDs of the data.

```python
raw.plot_psd()
```
Result cropped so it only shows the sensor positions (top to bottom: mag, grad, eeg):
![Figure_1 copy](https://user-images.githubusercontent.com/2046265/83051304-1ea14480-a04e-11ea-8017-51b1b17aa1e8.png)

The magnetometer sensor layout looks incorrect, and doesn't match the one produced by `plot_sensors()`. Am I missing something here?

cc @agramfort

**Comment by agramfort** [comment]
to me yes we have a bug.

any idea @larsoner ?

>

**Comment by larsoner** [comment]
Agreed it's a bug, no idea the cause. Someone will have to dig into the viz code to figure out why this is happening...

**Comment by agramfort** [comment]
this allows to clearly show the bug:

```
import mne
import os

sample_data_folder = mne.datasets.sample.data_path()
sample_data_raw_file = os.path.join(sample_data_folder, 'MEG', 'sample',
                                    'sample_audvis_raw.fif')
raw = mne.io.read_raw_fif(sample_data_raw_file, preload=True)
raw.plot_psd(picks=['grad'])
raw.plot_psd(picks=['mag'])
raw.plot_psd(picks=['meg'])
```

**Comment by agramfort** [comment]
and the bad news it that the bug is in the 0.20 stable release :( :(

**Comment by larsoner** [comment]
I'll `git bisect` and see how hard it is to fix

**Comment by agramfort** [comment]
thanks

**Comment by larsoner** [comment]
Looks like it was 9e785061f325191b809ade41590887230c1378ec / #7486, cc @drammock -- I'll see if I can figure out what the problem is
