### ISSUE TITLE
viz.plot_sensors() only partially honors axes parameter

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#7850]
#### Describe the bug
I wanted to add sensor alignment plots via `Raw.plot_sensors()` to some subplots of a larger figure. While the sensors **are** getting plotted, I observe some very annoying side effects that imho qualify as bugs.

#### Steps to reproduce
```python
import matplotlib.pyplot as plt
import mne
from mne.datasets import sample

data_path = sample.data_path()
fname = data_path + '/MEG/sample/sample_audvis_raw.fif'
raw = mne.io.read_raw_fif(fname)

fig, ax = plt.subplots(2, 2)

ax[0, 0].plot(range(10))
ax[0, 0].set_title('Title A')

ax[1, 0].plot(range(10))
ax[1, 0].set_title('Title B')

raw.plot_sensors(ch_type='mag', axes=ax[0, 1])
raw.plot_sensors(ch_type='grad', axes=ax[1, 1])
```

#### Expected results
All subplots should appear in their designated axes.

#### Actual results
![Figure_1](https://user-images.githubusercontent.com/2046265/83256519-d94a5780-a1b2-11ea-9cd2-06f8027d6d8a.png)

- First sensor plot doesn't have a title
- Second sensor plot's title appears as `suptitle` while it should be an axes title
- The entire figure appears to be truncated at the top, left, and bottom

#### Additional information
The behavior reminds me somewhat of #7595, which has been fixed by @drammock in #7706.

I'm using Matplotlibs Qt backend on macOS.

**Comment by hoechenberger** [comment]
There also seems to be an issue with the "click on sensors" callback, which is linked across BOTH sensor subplots…


![](https://im4.ezgif.com/tmp/ezgif-4-c12087ae43c6.gif)

**Comment by agramfort** [comment]
I would qualify this as a bug

>
