### ISSUE TITLE
MNE Fiducials and Their Usage in mne.coreg.get_mni_fiducials

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-python#7858]
#### Problem
II'm trying to use the `mne.coreg.get_mni_fiducials` function, but it is not clear what the output is. Is the dictionary ordered as LPA, nasion, RPA? If not what is it?

In addition, I was wondering what the best way of attaching these coordinates to a raw is? Would one save the fiducials say as JSON and can then reload and attach during the set_montage step?

#### Suggested glossary term
It would be great to also see a glossary item explaining how fiducials are used in general (or links) and how it is used in mne-python.

**Comment by agramfort** [comment]
fiducials are necessary to define the head coordinate system. What this
function does it transform to subject head the
fiducials hard coded for fsaverage

clear enough?

>

**Comment by vagechirkov** [comment]
@agramfort @adam2392 I think there is already [description in the glossary](https://github.com/vagechirkov/mne-python/blame/main/doc/glossary.rst#L123) and proper [documentation of the function](https://github.com/vagechirkov/mne-python/blob/56e9fbe67a554272a71dfd2b9ae96eb7fd58d104/mne/coreg.py#L1224). Is it still an open issue?

**Comment by agramfort** [comment]
@adam2392 <https://github.com/adam2392> are the links shared above clear
enough?

**Comment by adam2392** [comment]
Yes I think this is stale now. Can close
