### ISSUE TITLE
"compute_current_source_density" on Epochs only works with preload=True (--> add to documentation)

### ISSUE THREAD

**Issue by andrewsno1** [mne-tools/mne-python#7859]
[MNE v 0.20.5 on CentOS]

When I tried using mne.preprocessing.compute_current_source_density on an Epochs instance execution failed in line 167 with the classic 

TypeError: 'NoneType' object is not iterable

because inst._data was _None_.

This happens when the Epochs object is created **without** using "**preload=_True_**". 
An easy quick fix would be to add a sentence to the docstring explaining that the "Epochs" object needs to be created using preload=True. I think this would save the users some time debugging.

Thanks!

**Comment by larsoner** [comment]
@andrewsno1 I think the fix here is to use `_check_preloaded` (you can see how it's used elsewhere in our codebase). Would you be up for making a PR to add it?
