### ISSUE TITLE
phantom 4DBTi data includes a bunch of hidden macOS files

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#7867]
After downloading all the example data while setting up a new system, I noticed that a `__MACOSX` folder ended up inside `mne_data`.  It contains a bunch of finder / spotlight indexing files for the phantom 4DBTi dataset. The `__MACOSX` folder is not listed in the manifest on [the OSF repo](https://osf.io/v2brw/), but is present in the zip file.  In examining the OSF repo, I also noticed `.dropbox` and `.DS_Store` files inside the `MNE-phantom-4DBTi` folder, as well as a zero-byte text file called `Icon` (I dunno if this last one is a mac-generated file or a legitimate part of the dataset?)

**Comment by agramfort** [comment]
it's a mac thing. You can clean this up !

>

**Comment by drammock** [comment]
OK, I've requested access to MNE's OSF project. Once you grant that, I can fix.

**Comment by larsoner** [comment]
Granted
