### ISSUE TITLE
Bug in EEG processing and Event Related Potentials Tutorial

### ISSUE THREAD

**Issue by dimitriospantazis** [mne-tools/mne-python#7874]
#### Describe the bug
I believe the plot_eeg_erp.py tutorial does not combine trials properly. Lines 145-148 should use:
aud_l = epochs["auditory/left"].average()
instead of
aud_l = epochs["auditory","left"].average()

**Comment by drammock** [comment]
agreed.  I'll fix this in #7869 since I'm already fixing other parts of that tutorial.
