### ISSUE TITLE
How do I pick the correct frequency range for tfr_morlet?

### ISSUE THREAD

**Issue by jj-hennessy** [mne-tools/mne-python#7876]
Greetings human across the internet,

I am completely new to MNE and signal processing in general, so excuse my ignorance if I'm missing something simple here. Let me start by explaining what I am trying to do. Essentially my goal is to take in raw EEG data, feed it through a continuous wavelet transform algorithm (I'm using [pywt](https://pywavelets.readthedocs.io/en/latest/ref/cwt.html) instead of MNE to do this), and then feed the results of CWT directly into tfr_morlet. Here is the part of my code doing the things I just mentioned:

`       

        EEG_data = all_data[:n_channels, :]
        EEG_data = EEG_data.T
        EEG_data = EEG_data.reshape(n_epochs, n_channels, n_samples)

        random_scale = np.arange(1,n_channels)
        coef, freqs = pywt.cwt(EEG_data, random_scale, 'mexh')
        coef = coef.reshape(15, n_channels, n_samples)

        epochs = EpochsArray(data=coef, info=info)

        fig, ax = plt.subplots(1, 1, figsize=(15, 5), sharey=True)
        frequencies = np.arange(5, 20, 1)
        power = tfr_morlet(epochs, freqs=frequencies,
                           n_cycles=1, return_itc=False)
        power.plot([1], baseline=(0., 0.1), mode='mean', vmin=vmin, vmax=vmax,
                   axes=ax, show=False, colorbar=False)
        plt.tight_layout()
        plt.show()`

The pywt code performing CWT works correctly, but I have been getting the follow error every time I run my code:

`ValueError: At least one of the wavelets is longer than the signal. Use a longer signal or shorter wavelets.`

My main questions are: 

- How do I pick the correct frequency range so that it won't give me this error? 

- Does the input data for tfr_morlet have to be within a certain value range? Can the numbers in my data be literally anything and the code will run?

Any help whatsoever would be greatly appreciated -- I'm very confused as of right now.

Best,
JJ

**Comment by agramfort** [comment]
### no usage questions

This appears to be a question about usage, not a bug report or a new feature request. Please use the [MNE mailing list](http://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis) or the [gitter channel](https://gitter.im/mne-tools/mne-python) for usage questions.
