### ISSUE TITLE
Plot standard fNIRS response image with confidence bands

### ISSUE THREAD

**Issue by HanBnrd** [mne-tools/mne-python#7884]
Hello,

I was wondering why the confidence bands are not drawn when using the [plot_compare_evokeds](https://mne.tools/stable/generated/mne.viz.plot_compare_evokeds.html) function with the *ci* argument with HbO and HbR for fNIRS, as can be seen in the example [Preprocessing functional near-infrared spectroscopy (fNIRS) data](https://mne.tools/stable/auto_tutorials/preprocessing/plot_70_fnirs_processing.html#plot-standard-fnirs-response-image) (in the *Plot standard fNIRS response image* section)?

What would be a way to draw those confidence bands?

Thank you!

**Comment by drammock** [comment]
To get confidence bands from `plot_compare_evokeds`, you need to provide a *list of Evoked objects* corresponding to each condition. In the fNIRS tutorial you mention, each condition in `evoked_dict` is a single evoked, not a list of evokeds.

Put another way: when you create an `Evoked` object, it computes the average but does not keep track of the variance of the epochs that were averaged together to create it. So if you want to plot a representation of the variance (i.e., as a confidence band) then you need to either compute it yourself, or pass in the original epochs as a list of single-epoch "averages" (this is made convenient with `epochs.iter_evoked`).
