### ISSUE TITLE
Small docstring error in _auto_topomap_coords

### ISSUE THREAD

**Issue by aweinstein** [mne-tools/mne-python#7893]
The docstring of [`_auto_topomaps_coords`](https://github.com/mne-tools/mne-python/blob/03276c7c3d1d5a6cf7ca042f97d6cef51b14422e/mne/channels/layout.py#L622) says that parameter `to_sphere` defaults to `True`. However, this parameter has no default value.

**Comment by agramfort** [comment]
please send us a PR to remove this from docstring

>

**Comment by aweinstein** [comment]
PR send. (Sorry for being so picky :)
