### ISSUE TITLE
Python version dependency issue

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#7907]
#7758 introduced a dependency on `contextlib.nullcontext`, which was added to the standard library in Python 3.7.  We allegedly support Python 3.6 as our minimum version.  This came up in helping a user troubleshoot MNE on Google CoLab hosted notebooks, which run py 3.6

cc @GuillaumeFavelier

**Comment by larsoner** [comment]
Argh, I added that. Can you make a quick PR to add one to `mne/fixes.py`? If not, I can do it quickly later tonight or tomorrow
