### ISSUE TITLE
Data analysis without montage info

### ISSUE THREAD

**Issue by AleksandraPestka** [mne-tools/mne-python#7909]
I've loaded my iEEG data, although I don't have montage file. 
My data consists 16 channels and I'm not able to match it with any built-in montages proposed by MNE ( mne.channels.make_standard_montage() ).
I want to run ICA on my data, but I get an error:
`ValueError: Cannot determine location of MEG/EOG/ECG channels using digitization points.`

How can I use MNE analysis functions without providing sensors location?

**Comment by agramfort** [comment]
This appears to be a question about usage, not a bug report or a new feature request. Please use the [MNE mailing list](http://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis) or the [gitter channel](https://gitter.im/mne-tools/mne-python) for usage questions.
