### ISSUE TITLE
BUG: inconsistent auto-clim handling for SourceEstimate and VectorSourceEstimate

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#7911]
In theory, these two things should yield identical results:

```
vecstc = apply_inverse(..., pick_ori='vector')
vecstc.plot(..., brain_alpha=1., overlay_alpha=1., vector_alpha=0.)
```
versus
```
stc = apply_inverse(..., pick_ori=None)
stc.plot(..., surface='white')
```

In practice, `plot_vector_source_estimates` calls `brain.scale_data_colormap` under the hood, while `plot_source_estimates` does not, so the automatic choosing of `clim` is quite different in the two cases.  If you pass in a `clim` dict with your own values, then the two approaches indeed look identical, so probably (?) all that is needed is to remove the call to `brain.scale_data_colormap`.

**Comment by agramfort** [comment]
agreed

**Comment by GuillaumeFavelier** [comment]
I'm afraid `scale_data_colormap` might be need in `plot_vector_source_estimates` to update the colormap of the glyphs.

**Comment by larsoner** [comment]
Where? For PySurfer or PyVista? With my latest PR, I'd be surprised if it's the case for PyVista. If it is, then it seems like a bug. (And if things aren't working for PySurfer, it seems like probably a bug there, too, that should be fixed.)

**Comment by GuillaumeFavelier** [comment]
PySurfer, I think it's related to an issue opened a long time ago...

**Comment by GuillaumeFavelier** [comment]
I think I found it: https://github.com/mne-tools/mne-python/pull/6510

**Comment by larsoner** [comment]
So it sounds like the bug was not completely fixed
