### ISSUE TITLE
How can I plot a colorbar using mne.viz.plot_topomap() with my own data?

### ISSUE THREAD

**Issue by ZQInQAAS** [mne-tools/mne-python#7919]
hi，I'm using mne.viz.plot_topomap() to plot my own eeg data (ndarray), but I haven't find colorbar param. Could you tell me what should I do? Or maybe I use a wrong function?
thanks a lot !

**Comment by agramfort** [comment]
This appears to be a question about usage, not a bug report or a new feature request. Please use the [MNE mailing list](http://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis) or the [gitter channel](https://gitter.im/mne-tools/mne-python) for usage questions.
