### ISSUE TITLE
stc.project('pca', src) requires fwd['src']

### ISSUE THREAD

**Issue by bloyl** [mne-tools/mne-python#7932]
Sometimes a few source locations are dropped in forward computation so the `stc` gets out of sync with the original `src`. this means you need to call `stc.project('pca', fwd['src'])`. It would be nice if you could use the original `src`.

This problem used to exist with `stc.extract_label_time_course` but that has been fixed maybe by #6789?

I'm not sure how to replicate this issue on sample data but I could share some data that exhibits the issue if that is needed.

**Comment by larsoner** [comment]
Indeed it looks like the same fix from #6789 could be applied to `stc.project`. Can you look into refactoring it for example into a `_check_vertices_subset` for https://github.com/mne-tools/mne-python/pull/6789/files#diff-3623e826cb12cb2dfa80dddf3b746d02R2544-R2549 then just reusing `with _temporary_vertices(src, stc.vertices):`?
