### ISSUE TITLE
tutorial bug plot_stats_cluster_erp.py

### ISSUE THREAD

**Issue by dimitriospantazis** [mne-tools/mne-python#7960]
#### Describe the bug
Tutorial plot_stats_cluster_erp.py does not use the electrode connectivity matrix on the spatiotemporal cluster test. Connectivity 'con' is computed in line 79, but it is not used in line 88.

**Comment by agramfort** [comment]
fixed in https://github.com/mne-tools/mne-python/pull/7961/files
