### ISSUE TITLE
Add quantity to axis labels in Evoked.plot()

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#7969]
#### Describe the problem
Currently, `Evoked.plot()` produces a figure like this:

![](https://mne.tools/stable/_images/sphx_glr_plot_evoked_whitening_001.png)

As you can see, the abscissa is labeled in the form `Quantity (unit)`; however, the ordinates are labeled as `unit` only.

- This is inconsistent.
- This violates recommendations I've picked up during my engineering education (I agree that this is most probably opinionated though!)

#### Describe your solution
While it would be easy to label the ordinates for EEG and magnetometer data `Voltage (µV)` and `Field (fT)`, respectively, the case is more tricky with gradiometers, as the displayed quantity is effectively `∆Field / ∆Distance`.

Another difficulty is that, in the figure shown above, the individual subplots are quite small in terms of vertical height, so there's not always enough space to comfortably add the quantity to the label.

So I was thinking: One thing that all these quantities, in this context, have in common, is that they represent measured signals of some sort. So my idea would be to leave the figure as it currently is, but add a label `Signal`, which is shared by the ordinates of all subplots – see this mockup I've quickly put together:

![sphx_glr_plot_evoked_whitening_001](https://user-images.githubusercontent.com/2046265/86626911-b2f4b480-bfc7-11ea-8c8b-c9811af6aa5a.png)

Note how I have also
- adjusted the font of the abscissa label
- aligned the unit labels of the ordinates horizontally (though I'm not sure how to do that in Matplotlib easily)

Thoughts?

**Comment by larsoner** [comment]
I don't think "Signal" or (what would probably be my preference) "Amplitude" adds enough understanding here to justify eating the figure space
