### ISSUE TITLE
FR: REST method for EEG re-referencing

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#7973]
fieldtrip implements the REST method for EEG data re-referecing. See:

https://github.com/fieldtrip/fieldtrip/blob/master/preproc/ft_preproc_rereference.m#L140

it's actually quite simple.

EEG folks : @cbrnr @hoechenberger @sappelhoff ... do you see an interest in this?

**Comment by sappelhoff** [comment]
I think it's interesting and I'd certainly like to try it on my data if it were available in MNE. But I don't feel an urge to implement it myself :)

**Comment by hoechenberger** [comment]
> fieldtrip implements the REST method for EEG data re-referecing. See:
> 
> https://github.com/fieldtrip/fieldtrip/blob/master/preproc/ft_preproc_rereference.m#L140
> 
> it's actually quite simple.
> 
> EEG folks : @cbrnr @hoechenberger @sappelhoff ... do you see an interest in this?

I read about this method recently, but I was not convinced that it would be worth the effort to implement and use it. But of course, once we do have an implementation, we could run some quantitative comparisons :)

Would certainly be nice to have it in MNE! What would the API look like? `mne.set_eeg_reference('REST')`?

**Comment by agramfort** [comment]
yes

mne.set_eeg_reference('REST', fwd=fwd)

>

**Comment by cbrnr** [comment]
I'm probably not going to use it anytime soon because the additional requirements (lead field matrix) do not seem to yield strikingly improved results. But if anyone wants to implement it I won't object of course. Note that a Python implementation already exists here: https://github.com/HaoZ94/restpython
