### ISSUE TITLE
to_data_frame() method for EpochsTFR objects

### ISSUE THREAD

**Issue by eioe** [mne-tools/mne-python#7975]
Are there plans to implement a `to_data_frame()` method for `EpochsTFR` and `AverageTFR` objects?

I would like to export/save the according data for further analysis in R. 
I just recently learned about the `to_data_frame()` methods for `Epoch` and `Evoked` objects and find them terrifically useful. Would be great to get the same luxury for tfr data. 

I'm also thankful for hints regarding major obstacles that speak against it or if there are already similar implementations that I'm not aware of. 
Thanks!

**Comment by larsoner** [comment]
I think it would be fine to implement this for the TFR objects, do you want to give it a shot?

**Comment by eioe** [comment]
I will see what I achieve. However, I'm still quite new to MNE and have little experience with PRs into professionnally mainatained projects. So this will take a while and it's likely that I will come back for help. 

If someone else feels like implementing this earlier, please go for it. :)

**Comment by larsoner** [comment]
> However, I'm still quite new to MNE and have little experience with PRs into professionnally mainatained projects. So this will take a while and it's likely that I will come back for help.

No problem! We're here to help people work through the contributing process, so feel free to take a stab at an initial implementation, open a pull request, and we can iterate from there. It can help to read the [contributing guide](https://mne.tools/dev/install/contributing.html#overview-of-contribution-process) to help get oriented with the overall process.

**Comment by eioe** [comment]
Thanks! Yes, I worked through the guide and set up a local dev enviroment. 
I'll come back when I hit a wall.

**Comment by dengemann** [comment]
Sounds cool! Keep me in the loop. We can then add simultaneously a related vignette to mne-r: https://mne.tools/mne-r

**Comment by eioe** [comment]
@drammock & @dengemann 
as discussed earlier, I would like to use the sprint to finally close this issue. 
Can you add it to the Sprint Program please and assign me? 
Btw the same was suggested earlier in #6619.

**Comment by agramfort** [comment]
go for it

>

**Comment by dengemann** [comment]
done @eioe

**Comment by drammock** [comment]
closed by #9124
