### ISSUE TITLE
plot_projs_topomap() of data with EEG projection creates "EEG-style" topoplots even for MEG data

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#7993]
#### Describe the bug
Plotting SSP projectors via `Raw.plot_projs_topomap()`, we noticed that -- in some situations -- the visualized MEG fields didn't look quite right, i.e., looked like circular EEG topomaps instead like the expected "helmet-shaped" topomaps. Turns out, this only happened when among `info['projs']` was also an EEG average reference projector.

#### Steps to reproduce
```python
import os.path as op
import mne
from mne.datasets import sample

data_path = sample.data_path()
raw_fname = data_path + '/MEG/sample/sample_audvis_filt-0-40_raw.fif'
raw = mne.io.read_raw_fif(raw_fname, preload=True)

raw.copy().set_eeg_reference(projection=True).plot_projs_topomap()  # Add EEG avg ref projector
raw.copy().set_eeg_reference(projection=False).plot_projs_topomap()  # No EEG avg ref projector
```

#### Expected results
MEG topomap fields should follow the MEG helmet, and EEG fields should be circular.

#### Actual results
**With EEG avg ref projector:**
<img width="502" alt="Screenshot 2020-07-10 at 18 31 14" src="https://user-images.githubusercontent.com/2046265/87178570-a204b580-c2dd-11ea-95ed-63534e333475.png">

**Without EEG avg ref projector:**
<img width="697" alt="Screenshot 2020-07-10 at 18 31 21" src="https://user-images.githubusercontent.com/2046265/87178625-b943a300-c2dd-11ea-9c3c-7810ff4c076e.png">

cc @agramfort

**Comment by larsoner** [comment]
@hoechenberger do you want to look into how to fix this? I can confirm the bug

**Comment by hoechenberger** [comment]
I might have time for this tomorrow, sure. But if you're asking if I would also be okay with you going ahead: sure ;)
