### ISSUE TITLE
API: Confirm best defaults for LCMV/DICS before 0.21

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#8008]
In #7656 we set the default `make_lcmv(..., weight_norm='sqrtm')` because it's superior to the official `'unit-noise-gain'` in extensive simulation testing. But we should just double check with @britta-wstnr (busy right now AFAIK) that this is the default we should have for 0.21 before releasing.

**Comment by larsoner** [comment]
Also, @wmvanvliet should we deprecate apply_dics? Do we need a apply_dics_tfr first?

**Comment by wmvanvliet** [comment]
Let's deprecate when we have a viable alternative. Just so you know, I have no intention to work on an `apply_dics_tfr` function at the moment, but if someone else wants to take a stab at it, they have my blessing (and my simulations if they want)

**Comment by larsoner** [comment]
@wmvanvliet @britta-wstnr are we okay here?

**Comment by wmvanvliet** [comment]
I think so!

**Comment by larsoner** [comment]
Okay I'll close this for now then

**Comment by larsoner** [comment]
@wmvanvliet I'm trying to speed up some examples and noticed [in master](https://mne.tools/dev/auto_examples/inverse/plot_dics_source_power.html#sphx-glr-auto-examples-inverse-plot-dics-source-power-py) the DICS example gives:

![](https://mne.tools/dev/_images/sphx_glr_plot_dics_source_power_001.png)

[0.20 stable has](https://mne.tools/stable/auto_examples/inverse/plot_dics_source_power.html#sphx-glr-auto-examples-inverse-plot-dics-source-power-py):

![](https://mne.tools/stable/_images/sphx_glr_plot_dics_source_power_001.png)

Can you look to see if this is wrong? If so a `git bisect` might tell us where things went wrong.

**Comment by wmvanvliet** [comment]
master certainly is wrong...

**Comment by wmvanvliet** [comment]
we need either `inversion='single'` or `reduce_rank=True` to make it work again.

**Comment by larsoner** [comment]
Indeed `reduce_rank=True` works, I'll add it to #8260. Thanks for the quick investigation!
