### ISSUE TITLE
conda environment.yml broken?

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#8040]
Currently, all CIs using `conda` with our `environment.yml` are broken because of unsatisfiable dependencies. It has something to do with `traits`, which is available as 5.2.0, but some other package (`pyface`?) wants >=6.0.0. I tested this locally, but everything works fine, so maybe the problematic packages have already been updated upstream. I can't restart Travis jobs for some reason, maybe @sappelhoff can you do it in #8037?

Related issue: I noticed that `pyqt` 5.9.2 gets installed automatically as a dependency by `conda`, but then we overwrite it with a newer version of `PyQt5` available in `pip`. This could be problematic and might explain issues related to PyQt that pop up from time to time.

**Comment by sappelhoff** [comment]
![image](https://user-images.githubusercontent.com/9084751/88157538-2c68e580-cc0b-11ea-8f9e-21ffabb76076.png)

https://travis-ci.org/github/mne-tools/mne-python/builds/710508815

**Comment by cbrnr** [comment]
Now the first jobs have a different error:

```
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -n
```

**Comment by cbrnr** [comment]
There doesn't seem to be a `-n` argument (`pytest -m "${CONDITION}" --tb=short --cov=mne -n 1 ${USE_DIRS}`).

**Comment by GuillaumeFavelier** [comment]
`-n` is used by the `pytest-xdist` plugin. It's not installed?

**Comment by cbrnr** [comment]
Looks like not. Where is the requirements file that contains this package?

**Comment by cbrnr** [comment]
@sappelhoff could you maybe also restart the failing Azure job?

**Comment by sappelhoff** [comment]
done, but I can only re-run the failed ones. Can only the PR owner or an admin re-run? I think you and I should have same permissions @cbrnr

**Comment by cbrnr** [comment]
The failed ones are OK for now. I didn't find the restart button in Travis (although I was logged in and I know where the button usually is - now there is just a "More options" button). I haven't figured out how to restart Azure jobs, I'm logged in and now I see only a "Cancel" button for the running job.

**Comment by sappelhoff** [comment]
>  I haven't figured out how to restart Azure jobs, I'm logged in and now I see only a "Cancel" button for the running job.

you do it from the GitHub UI, go to "details" and then there is an expanded dropdown menu on the left

**Comment by cbrnr** [comment]
This page? I don't have a dropdown menu.

![Screen Shot 2020-07-22 at 11 32 03](https://user-images.githubusercontent.com/4377312/88160493-fded0980-cc0e-11ea-9bba-a7dd54835d53.png)

**Comment by sappelhoff** [comment]
This is the one I mean:

![image](https://user-images.githubusercontent.com/9084751/88161579-743e3b80-cc10-11ea-9205-05b3616c88d1.png)


and it shows handles when you can restart something. you can't do anything for running or succeeded jobs with simple maintainer permissions.

**Comment by cbrnr** [comment]
Fixed upstream.
