### ISSUE TITLE
LinearModel with SGDClassifer

### ISSUE THREAD

**Issue by algrmur** [mne-tools/mne-python#8062]
Hi everyone,

Quick question. I am currently doing some decoding with a linear SVM via `SGDClassifier` in `scikit-learn` with hinge loss for comparison with another method that is restricted to the online learning paradigm. I would like to look at the activity patterns and filters, but SGDClassfier's `partial_fit` doesn't seem to play nicely with `mne.decoding.LinearModel`. I was wondering is there a way I can wrap a `LinearModel` constructor around `SGDClassifier` and use it by putting it through my own training (i.e. sequences of calling `partial_fit` until my convergence requirement has been met)?

Alternatively, after the `SGDClassifier` has been trained, is there a way to instantiate `LinearModel` with the learnt coefficients and then maybe combine the covariance of the data to recover the activity patterns al Haufe et al. (2014)?

Thanks
Alex

**Comment by agramfort** [comment]
This appears to be a question about usage, not a bug report or a new feature request. Please use the [MNE mailing list](http://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis) or the [gitter channel](https://gitter.im/mne-tools/mne-python) for usage questions.
