### ISSUE TITLE
MNE plot window in dark mode

### ISSUE THREAD

**Issue by balandongiv** [mne-tools/mne-python#8065]
Lately, there has been a lot of hype surrounding dark mode, a simple toggle that lets user to change the background color of an app window to black. There are several benefit of dark mode including reduce eye strain and even look amazing. But, the former is crucial as most researcher (at least me) spent a considerable amount of time visually analysing the biosignal graph using plot(). This especially true during the pre processing stage.

#### Describe your solution
Maybe there can be an option to toggle the window plot to change the background color to black, while the text and graph line into contrasting color such as white.

Since mne plot is based on matplotlib, I think this easily achieved as shown [here dark_background](https://matplotlib.org/3.1.1/gallery/style_sheets/dark_background.html)

**Comment by drammock** [comment]
This is already planned and will be part of #7955

**Comment by balandongiv** [comment]
That great. Eager to try this new feature.
