### ISSUE TITLE
How to epoch by using events_from_annotations ?

### ISSUE THREAD

**Issue by JiangTao100** [mne-tools/mne-python#8106]
I‘ve learned that .set profiles store events in  raw. annotations . But when I wanna use the function 'mne. events_from_annotations' to epoch ,it displays 'TypeError: events should be a NumPy array of integers, got <class 'tuple'>' compared to my present tuple form.
Below is my code:

```python
import os
import numpy as np
import mne
from mne.datasets import sample
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mne.preprocessing import (ICA, create_eog_epochs, create_ecg_epochs,
                               corrmap)
raw=mne.io.read_raw_eeglab('eeglab_data.set')

event_raw=raw.copy()

a=mne.Annotations(onset=[2.1,4.0,53.5,54.0,59.0,60.8,156.4,168.2],
                  duration=[0.2,0.2,0.3,0.2,1.0,0.9,0.2,1.8],
                  description=['BAD'])
plus_anno=a+raw.annotations
event_raw.set_annotations(plus_anno)
event_dict=mne.events_from_annotations(event_raw)
epochs = mne.Epochs(event_raw,event_dict
                    ,tmin=-0.3, tmax=0.7,
                    preload=True)
```

error displayed:

```
runcell(0, 'D:/python project/mypython/eeg_profile_read.py')
Reading D:\softinstall\Anaconda3\lib\site-packages\mne\testdata\eeglab_data.fdt

runcell(12, 'D:/python project/mypython/eeg_profile_read.py')

runcell(12, 'D:/python project/mypython/eeg_profile_read.py')

runcell(12, 'D:/python project/mypython/eeg_profile_read.py')

runcell(12, 'D:/python project/mypython/eeg_profile_read.py')
Used Annotations descriptions: ['rt', 'square']
Traceback (most recent call last):

  File "D:\python project\mypython\eeg_profile_read.py", line 82, in <module>
    preload=True)

  File "<decorator-gen-184>", line 21, in __init__

  File "D:\softinstall\Anaconda3\lib\site-packages\mne\epochs.py", line 2095, in __init__
    event_repeated=event_repeated, verbose=verbose)

  File "<decorator-gen-175>", line 21, in __init__

  File "D:\softinstall\Anaconda3\lib\site-packages\mne\epochs.py", line 399, in __init__
    'got {}'.format(events_type))

TypeError: events should be a NumPy array of integers, got <class 'tuple'>
```

The file needs to be download: https://github.com/JiangTao100/CNT-profile

**Comment by cbrnr** [comment]
`mne.events_from_annotations` returns a tuple of the actual events (NumPy array) and a description dict. Use `event_dict[0]` to access the event array.

**Comment by mokennen** [comment]
I'm working on. EDF file but when I try to epoch the data, get Type "Error: events should be a NumPy array of integers, got <class 'tuple'>" error. how can I  bypass this problem
with regerads
​

**Comment by agramfort** [comment]
Events_from_annotations returns 2 things events and event_id 
Each one is one different parameter in Epochs

**Comment by drammock** [comment]
@mokennen please use our user forum, https://mne.discourse.group for usage questions. Do not post comments on already-closed GitHub issue threads. 

Note also that @cbrnr already gave the likely solution to your problem in the comment immediately above yours:

> `mne.events_from_annotations` returns a tuple of the actual events (NumPy array) and a description dict.
