### ISSUE TITLE
BUG: PyVista backend doesn't properly show axes in plot_alignment

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#8115]
```
import mne
fname = mne.datasets.sample.data_path() + '/MEG/sample/sample_audvis_raw.fif'
raw = mne.io.read_raw_fif(fname)
with mne.viz.use_3d_backend('pyvista'):
    mne.viz.plot_alignment(raw.info, show_axes=True, eeg=False, surfaces=[])
```
Produces:

![Screenshot from 2020-08-11 11-28-25](https://user-images.githubusercontent.com/2365790/89916733-f8f3f800-dbc5-11ea-9b72-d5ece4e58fa2.png)

The axes arrows are wrong, it should look like they do for the `mayavi` backend:

![Screenshot from 2020-08-11 11-28-37](https://user-images.githubusercontent.com/2365790/89916782-08734100-dbc6-11ea-9a3d-72bc06e4eef1.png)

@GuillaumeFavelier can you look?

**Comment by GuillaumeFavelier** [comment]
I'll take care of it :+1:
