### ISSUE TITLE
anonymize also sex and hand

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#8130]
anonymize with keep_his False keeps what's in: `raw.info['subject_info']`
which contains hand and sex for example.

Should we remove these info with keep_his=False or should we introduce another parameter?

**Comment by cbrnr** [comment]
What does "his" mean?

**Comment by larsoner** [comment]
Thoughts @bloyl ?

**Comment by agramfort** [comment]
HIS = health information system

**Comment by bloyl** [comment]
I don't think that handedness and sex/gender are considered PHI or
Identifing information in the US.

That being said I would remove them if `keep_his=False` to not further
complicate the API.

In general I feel like depending on the fif files to hold this type of
information is error prone and probably unreliable particularly across
sites.

**Comment by agramfort** [comment]
I would look at what other software do to be consistent.

**Comment by Falach** [comment]
I'll take this one

**Comment by agramfort** [comment]
do we know what other software are doing?

@ftadel @robertoostenveld are brainstorm or fieldtrip removing handness and gender when anonymizing?

**Comment by robertoostenveld** [comment]
FieldTrip itself does not anonymize and does not have a single tool for converting data to BIDS. Instead the user would write a script around the data2bids function (looping over subjects and sessions). So a user may do it, depending on how he feeds these two into the cfg.participants.handedness and cfg.participants.sex options.

However, I personally would not do it as the entropy in these two is just too low. 

In most cases we would code both with 2 values, which means that with 5 subjects you would already have some repetition as there can only 4 possible pairs of values. For handedness you would have 90/10% occurrence. When only considering M and F as levels for sex, you would have approximately 50/50% occurence of both.In the least probable case (a female left-hander), 1 out of 22 people will still have the same sex and handedness.  However, if you were to collect and store gender, it can become more unique.

**Comment by ftadel** [comment]
In Brainstorm, we don't store (yet) any subject-related meta-data beyond ID and acquisition date. So the .tsv files generated when exporting a Brainstorm database as a BIDS dataset do not include these fields. 

However, the info could remain the in headers of the recordings. Some files can be copied as is to the BIDS export, and propagate sex/handedness info. The anonymization of the file headers is not part (yet) of the export process, it remains a separate optional step (for now).

The only BIDS-compatible file format (exported by Brainstorm, ie. excluding the EEGLAB .set) that can store this information is **FIF**.
Before the export to BIDS, the user can call this function **fiff_anonymizer.m** (from a script or from the GUI), which by default removes both sex and handedness:
https://github.com/brainstorm-tools/brainstorm3/blob/master/external/other/fiff_anonymizer.m

**Comment by agramfort** [comment]
thanks a lot for the quick feedback !

>
