### ISSUE TITLE
 get_point_spread/get_cross_talk for labels

### ISSUE THREAD

**Issue by olafhauk** [mne-tools/mne-python#8140]
#### Describe the problem
get_point_spread/get_cross_talk currently only output results for point sources, but no summaries across vertices within labels (e.g. mean/max/SVD).

#### Describe your solution
I'm planning to add options 'labels' and 'mode' to get_point_spread/get_cross_talk in order to summarise PSFs/CTFs across vertices for a list of labels (e.g. mean, sum, max, SVD). Default would be labels=None and mode=None. 
('mode' would match extract_label_time_course (https://mne.tools/stable/generated/mne.extract_label_time_course.html, and was suggested by Eric a while back)

**Comment by olafhauk** [comment]
I have something like this in mind:

    def _get_psf_ctf(resmat, src, idx, func='psf', mode=None, n_comp=1,
                     norm=False):
        """Get point-spread (PSFs) or cross-talk (CTFs) functions.

        Parameters
        ----------
        resmat : array, shape (n_dipoles, n_dipoles)
            Forward Operator.
        src : Source Space
            Source space used to compute resolution matrix.
        idx : list of int | list of Label | list of lists of int
            Source for indices for which to compute PSFs or CTFs.
            Can be:

            - list of integers:
                Return PSFs/CTFs for all indices specified in idx.
            - list of Label:
                Take indices from specified labels.
            - list of lists of integers:
                Similar to previous option, but indices are specified as list
                of lists of integers instead of labels. For every outer list
                item, compute PSFs/CTFs for indices specified in inner lists.

        func : str ('psf' | 'ctf')
            Whether to produce PSFs or CTFs. Defaults to psf.
        mode: None | 'mean' | 'max' | 'svd'
            Compute summary of PSFs/CTFs across indices specified in 'idx'.

            Can be:
            - None (default):
                Output individual PSFs/CTFs for each specific vertex.
            - 'mean':
                Mean of PSFs/CTFs across vertices.
            - 'max':
                PSFs/CTFs with maximum norm across vertices. Returns the n_comp
                largest PSFs/CTFs.
            - 'svd':
                SVD components across PSFs/CTFs across vertices. Returns the n_comp
                first SVD components.

        n_comp: int
            Number of PSF/CTF components to return for mode='max' or mode='svd'.
        norm : bool
            Whether to normalise to maximum across all PSFs and CTFs (default:
            False). This will be applied before computing summaries as specified in
            'mode'.

        Returns
        -------
        stc: instance of SourceEstimate
            PSFs or CTFs as an STC object.
            All functions will be returned as successive samples in one STC
            file, in the order they are specified in idx. Functions for labels
            are grouped together.
        """

**Comment by olafhauk** [comment]
> 
> 
> It's just `label.vertices`, but it would still be nicer to allow `list of Label` I think

label.vertices seems to return the indices for the Freesurfer surface, but not to the source space vertices. For For example, for the sample data set the source space has 7498 vertices, but label.vertices has values up to ~100000 (e.g. for 'Aud-lh'). I cannot use them to do something like leadfield[:, label.vertices]?
I've found some code in _prepare_label_extraction (in source_estimate.py, see below) that seems to find the right vertices for the source space. Please tell me if there is a better/simpler way to do this.

This is from _prepare_label_extraction():

    vertno = stc.vertices

    if label.hemi == 'both':
        # handle BiHemiLabel
        sub_labels = [label.lh, label.rh]
    else:
        sub_labels = [label]

    this_vertidx = list()
    for slabel in sub_labels:
        if slabel.hemi == 'lh':
            this_vertices = np.intersect1d(vertno[0], slabel.vertices)
            vertidx = np.searchsorted(vertno[0], this_vertices)
        elif slabel.hemi == 'rh':
            this_vertices = np.intersect1d(vertno[1], slabel.vertices)
            vertidx = nvert[0] + np.searchsorted(vertno[1], this_vertices)
        else:
            raise ValueError('label %s has invalid hemi' % label.name)
        this_vertidx.append(vertidx)

**Comment by larsoner** [comment]
> I've found some code in _prepare_label_extraction (in source_estimate.py, see below) that seems to find the right vertices for the source space. Please tell me if there is a better/simpler way to do this.

Yes you probably need something like this. I would put this in a separate private function and use it in both places (DRY).

**Comment by agramfort** [comment]
I would not support the option list of lists of int and suggest to use
a list of Label

besides ok for me

**Comment by olafhauk** [comment]
> 
> I would not support the option list of lists of int and suggest to use a list of Label besides ok for me

Fine by me - I thought some users may want to use some specific selection of vertices, not necessarily labels. Can one convert a list of indices to a label? Or they would have to do mean/max/svd themselves.

**Comment by agramfort** [comment]
you can construct a Label from vertices by calling Label constructor.
How does this relate to mean, max and svd?
are you refered to
https://mne.tools/stable/generated/mne.extract_label_time_course.html ?

>

**Comment by olafhauk** [comment]
Some users may want mean/max/svd for a selection of vertices that are not in a label (e.g. from some activation peaks, patterns, etc.). But this is probably rare. I'll continue without "list of lists".

**Comment by larsoner** [comment]
You mean "list of Label", right?

**Comment by olafhauk** [comment]
No - I will continue with only "list of Label", but NOT with "list of lists". That's how I understood Alex.

**Comment by larsoner** [comment]
Ahh I misread, I thought you said you'll continue *with* list of List -- agreed implementing just list of label is the way to go for now.

**Comment by olafhauk** [comment]
I need advice on how to deal with changes to an API that affects users.
I would like change the option 'norm' from Bool to 'max' | 'norm' | None such that users also have a choice of different normalisations (to max value and norm). I don't know how many current users this will affect (maybe not many). 
Should I still allow Bool (and choose a default for 'True') and use mne.utils.warn()?
I also added options for mode.

def _get_psf_ctf(resmat, src, idx, func='psf', mode=None, n_comp=1,
                 norm=False):
    """Get point-spread (PSFs) or cross-talk (CTFs) functions.

    Parameters
    ----------
    resmat : array, shape (n_dipoles, n_dipoles)
        Forward Operator.
    src : Source Space
        Source space used to compute resolution matrix.
    idx : list of int | list of Label
        Source for indices for which to compute PSFs or CTFs. If mode is None,
        PSFs/CTFs will be returned for all indices. If mode is not None, the
        corresponding summary measure will be computed across all PSFs/CTFs
        available from idx.
        idx can be:

        - list of integers:
            Compute PSFs/CTFs for all indices specified in idx.
        - list of Label:
            Compute PSFs/CTFs for all indices in specified labels.

    func : str ('psf' | 'ctf')
        Whether to produce PSFs or CTFs. Defaults to psf.
    mode: None | 'sum' | 'mean' | 'maxval' | 'maxnorm' | 'svd'
        Compute summary of PSFs/CTFs across all indices specified in 'idx'.

        Can be:
        - None (default):
            Output individual PSFs/CTFs for each specific vertex.
        - 'sum':
            The sum of PSFs/CTFs across vertices.
        - 'mean':
            The mean of PSFs/CTFs across vertices.
        - 'maxval':
            PSFs/CTFs with maximum absolute value across vertices. Returns the
            n_comp largest PSFs/CTFs.
        - 'maxnorm':
            PSFs/CTFs with maximum norm across vertices. Returns the n_comp
            largest PSFs/CTFs.
        - 'svd':
            SVD components across PSFs/CTFs across vertices. Returns the n_comp
            first SVD components.

    n_comp: int
        Number of PSF/CTF components to return for mode='max' or mode='svd'.
        Default n_comp=1.
    norm : 'max' | 'norm' | None
        Whether and how to normalise the PSFs and CTFs (default: None).

        Can be:
        - None (default):
            Use un-normalized PSFs/CTFs.
        - 'max':
            Normalize to maximum absolute value across all PSFs/CTFs.
        - 'norm':
            Normalize to maximum norm across all PSFs/CTFs.

        This will be applied before computing summaries as specified in 'mode'.

    Returns
    -------
    stc: instance of SourceEstimate
        PSFs or CTFs as an STC object.
        All PSFs/CTFs will be returned as successive samples in one STC object,
        in the order they are specified in idx. PSFs/CTFs for labels are
        grouped together.
    """

**Comment by larsoner** [comment]
I would just make `True` an alias for `'norm'`, no need for deprecating I think.

**Comment by agramfort** [comment]
fine with me

**Comment by olafhauk** [comment]
For mode='svd', I would like to output the variances for the different components in addition to the STC (useful to select components later). Do you allow this (couldn't find this anywhere else):
```python
if mode == 'svd':
    return stc, s_var
else:
    return stc

**Comment by agramfort** [comment]
I would add another parameter called return_exp_variance ? saying it
only applies if mode  == 'svd'

**Comment by olafhauk** [comment]
> 
> I would add another parameter called return_exp_variance ? saying it only applies if mode == 'svd'

Proposal accepted.

**Comment by larsoner** [comment]
We have this from #8275
