### ISSUE TITLE
Epochs and Events (No stim channel found to extract event triggers)

### ISSUE THREAD

**Issue by mianjalal786** [mne-tools/mne-python#8148]
Hey
i got this error when i m trying to get events and making epochs.
ValueError: No stim channel found to extract event triggers.

What to do if my dataset file(.edf) have no stim channel?
I actually want to do frequency time analysis  of my data.

Thanks

**Comment by agramfort** [comment]
This appears to be a question about usage, not a bug report or a new feature request. Please use the [MNE mailing list](http://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis) or the [gitter channel](https://gitter.im/mne-tools/mne-python) for usage questions.
