### ISSUE TITLE
Custom montage object not loading to NIRS info

### ISSUE THREAD

**Issue by Isamaoz** [mne-tools/mne-python#8149]
Hello,

I am trying to classify EEG and NIRS data using MNE. The datasets I am using were converted into MATLAB format; therefore, I created my data structures from scratch (raw data, montage files, epochs). I did not have any problems loading and classifying the EEG data, but I realised that raw.set_montage() does not support NIRS channels. When I tried to set the montage file to the info object, the coordinates of the sources and detectors are converted into NaNs. 

Do you know if there is an alternative for me to set a montage using NIRS? Thank you!

**Comment by agramfort** [comment]
ping @rob-luke

**Comment by rob-luke** [comment]
Hi @Isamaoz,

Can you provide a minimum working example of how you are setting the montage?

I haven't added added NIRS support to set_montage(), so it doesn't surprise me it doesn't work. Taking a quick look at the code I think the following line is just skipping the nirs channels. But the whole code seems quite EEG specific.

https://github.com/mne-tools/mne-python/blob/master/mne/channels/montage.py#L700

I won't be able to add support for this before 0.21. @Isamaoz are you able to take make an attempt at a PR to fix this issue?

**Comment by HanBnrd** [comment]
Hi @larsoner, this issue also is closed by #9141 🙂

**Comment by larsoner** [comment]
Indeed, thanks!
