### ISSUE TITLE
Contour Plot of RAW EEG data

### ISSUE THREAD

**Issue by mianjalal786** [mne-tools/mne-python#8152]
Hey

Is there any way to make contour plot of raw eeg data?

Thanls

**Comment by agramfort** [comment]
This appears to be a question about usage, not a bug report or a new feature request. Please use the [MNE mailing list](http://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis) or the [gitter channel](https://gitter.im/mne-tools/mne-python) for usage questions.
