### ISSUE TITLE
How to throw a animate plot to html page

### ISSUE THREAD

**Issue by 5dh15** [mne-tools/mne-python#8158]
Hello!
I'm writing the .fif format file viewer (the graph) on the server environment.
Recently putted out the dynamic real-time brainwave graph on python with mne,
but I want let the graph viewing on the Internet browser.

Is there anyway to figure it out?
Thank you!

**Comment by agramfort** [comment]
This appears to be a question about usage, not a bug report or a new feature request. Please use the [MNE mailing list](http://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis) or the [gitter channel](https://gitter.im/mne-tools/mne-python) for usage questions.
