### ISSUE TITLE
bad eog channel

### ISSUE THREAD

**Issue by guishuyunye-lyw** [mne-tools/mne-python#8163]
Dear MNE group
I got some problem when I process my data with a bad eog channel.
If I mark the eog channel as a bad one, does MNE will interpolate it with prefrontal sensors?
If not, what should I do for that, considering I just have some of datas with bad eog.
THX!

**Comment by agramfort** [comment]
This appears to be a question about usage, not a bug report or a new feature request. Please use the [MNE mailing list](http://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis) or the [gitter channel](https://gitter.im/mne-tools/mne-python) for usage questions.
