### ISSUE TITLE
Reading in Persyst (.lay/.dat) files into Raw

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-python#8173]
#### Describe the problem
I have some files that were output from the Persyst system, which are text-readable .lay/.dat file combination. I would like to read them into MNE Python Raw.

This would be useful since I think it's a major "EEG" software processing system, which many clinical centers have. In addition, it is text-readable, so nothing hard about it. 

#### Describe your solution
A `read_raw_persyst` function that takes in a `lay_fname` and reads in data into a `Raw` object. The `.dat` filename is usually encoded in the `lay_fname`. 

The first solution won't be "perfect", but some more iterations from Persyst users might be warranted.

#### Describe possible alternatives
There is an initial start I found on Github: https://github.com/epiSurg/python-layread/blob/master/layread.py

but they do not read it into a `Raw` object, which I think would be more desirable for robust data flow.

#### Additional context
I have some example files added here.
[Archive.zip](https://github.com/mne-tools/mne-python/files/5146962/Archive.zip)

I can help implement it if perhaps @agramfort  or @larsoner can point me in the right direction? I'm assuming it's just that one function `read_raw_persyst`.

**Comment by agramfort** [comment]
seems indeed easy to add.

you should add these testing files in the mne-testing-data repo and then
add the reader in PR to mne-python

you can look at brainvision or nicolet readers for inspiration

>

**Comment by larsoner** [comment]
I would look at https://github.com/mne-tools/mne-python/pull/6674 to see the list of files you might need to change. If there are no new channel types, you probably only need to change half as many (or even fewer).
