### ISSUE TITLE
Should Handedness Unknown have a value of 0?

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-python#8186]
I am working on a PR that can read in some basic metadata on subject, such as handedness. However, if handedness is unknown, I would've presumed there was a `FIFF.FIFFV_SUBJ_HAND_UNKNOWN` varaible?

But currently in `constants.py`, there is no value for unknown.
```
FIFF.FIFFV_SUBJ_HAND_RIGHT  = 1    # Righthanded
FIFF.FIFFV_SUBJ_HAND_LEFT   = 2    # Lefthanded
FIFF.FIFFV_SUBJ_HAND_AMBI   = 3    # Ambidextrous

FIFF.FIFFV_SUBJ_SEX_UNKNOWN = 0    # Unknown gender
FIFF.FIFFV_SUBJ_SEX_MALE    = 1    # Male
FIFF.FIFFV_SUBJ_SEX_FEMALE  = 2    # Female
```

Is this intended?

**Comment by agramfort** [comment]
unknown should correspond to the absence of this tag in the file
