### ISSUE TITLE
BUG: Arrows gone in mixed norm plotting

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#8192]
Glyph in glass brain in : 

https://mne.tools/dev/auto_examples/inverse/plot_time_frequency_mixed_norm_inverse.html#sphx-glr-auto-examples-inverse-plot-time-frequency-mixed-norm-inverse-py

do not show up. I should see 2 sources.

_Originally posted by @agramfort in https://github.com/mne-tools/mne-python/pull/8188#issuecomment-685065216_

**Comment by larsoner** [comment]
This has been incorrect going back to 0.18:

https://mne.tools/0.18/auto_examples/inverse/plot_time_frequency_mixed_norm_inverse.html#sphx-glr-auto-examples-inverse-plot-time-frequency-mixed-norm-inverse-py

**Comment by larsoner** [comment]
It was broken by 78561338b1ffe376455e8a1324f55e2833979ce1, I'll try to figure out what the problem is...

**Comment by agramfort** [comment]
:'(
