### ISSUE TITLE
Continuous head movement KIT/Ricoh? systems

### ISSUE THREAD

**Issue by paulsowman** [mne-tools/mne-python#8205]
Hi @larsoner, further to our recent exchange I would like to implement the Maxwell filter correction for head movement in MNE. Our KIT125 system records continuous head position in the .con file. What might be required to develop as API to read your head position information / get it to the correct format?

Regards, P

**Comment by paulsowman** [comment]
No problem. I will do this ASAP. P

**Comment by larsoner** [comment]
Ping @paulsowman a gentle reminder to record some continuous-movement data at some point

**Comment by larsoner** [comment]
I think this is now working, it would be great to have a nice example at some point though!
