### ISSUE TITLE
ENH: Try fastcore to reduce boilerplate

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#8213]
From @agramfort , see [here](https://twitter.com/hamelhusain/status/1301575601497624577?s=11)

**Comment by agramfort** [comment]
well I suggested to have a look but not to put this as an MNE dep :)

**Comment by drammock** [comment]
Interesting. I've been wondering if `functools.singledispatch` would be good for our functions that take `inst`. A different problem, but one that fastcore seems to also have a solution for.

**Comment by larsoner** [comment]
Maybe it's something we can vendor? Will have to look into it

**Comment by agramfort** [comment]
slow down :)

sleep over it for some time first

>

**Comment by cbrnr** [comment]
😄 - I saw that on Twitter too and although this certainly looks good, I'd rather not add it as a dependency. I also thought that Julia has multiple dispatch (not limited to two args) by default, but hey.

**Comment by larsoner** [comment]
Closing, let's use if we need it someday
