### ISSUE TITLE
mne-edf2fiff does not exist

### ISSUE THREAD

**Issue by ometett** [mne-tools/mne-python#8233]
Dear mne team,

I am a bioengineering student who is working on a project that involves bringing eeg channels&data into meg(.fif) file. I have my EEG data in .edf format and I want to convert it to .fif so that I can append those two files together. I have been searching for mne_edf2fiff but I could not find it anywhere. I successfully downloaded mne-python and have been using but I am guessing the utility function is not included. Where can I obtain it? I would very much appreciate it if you could help. 

Thank you,
Omer

**Comment by larsoner** [comment]
mne_edf2fiff is part of MNE-C:

- https://mne.tools/stable/install/mne_c.html
- https://mne.tools/mne-c-manual/MNE-manual-2.7.3.pdf

In mne-python the equivalent would be something like:
```
raw = mne.io.read_raw_edf(...)
raw.save(...)
```
