### ISSUE TITLE
Automatic ICA component rejection?

### ISSUE THREAD

**Issue by XPeriment2** [mne-tools/mne-python#8236]
Is there any solution for something like MARA (eeglab) for ICA components automatic rejection?

thank you

**Comment by agramfort** [comment]
This appears to be a question about usage, not a bug report or a new feature request. Please use the [MNE mailing list](http://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis) or the [gitter channel](https://gitter.im/mne-tools/mne-python) for usage questions.
