### ISSUE TITLE
BUG: VTK/PyVista not freeing memory with multiple figures

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#8241]
A lot of our `master` builds have failed lately, like:

https://app.circleci.com/pipelines/github/mne-tools/mne-python/3597/workflows/fcb12f01-1f51-4d87-8697-5ac9e30f9411/jobs/22228

@GuillaumeFavelier I suspect it could be some recent-ish (within the last 2 months?) viz update. It was happening before the PyVista 0.26 release. Can you look to see if code from a month or two ago uses the same memory as it does now? Often it's `plot_visualize_stc.py` that breaks things, but in the example above it's `plot_forward.py`.

**Comment by GuillaumeFavelier** [comment]
It's an item of #7162

**Comment by larsoner** [comment]
Turns out this seems to be related to bad garbage collection. See investigations in https://github.com/mne-tools/mne-python/pull/8266#issuecomment-694561692 and report in https://github.com/pyvista/pyvistaqt/issues/57. It would be good if we could figure out where this is coming from. In the meantime, plotting so many montages is not going to be safe :(

**Comment by larsoner** [comment]
@GuillaumeFavelier interestingly enough this does not seem to happen on https://github.com/mne-tools/mne-python/blob/master/examples/visualization/plot_meg_sensors.py#L40-L47, but it does in https://github.com/mne-tools/mne-python/blob/master/examples/visualization/montage.py#L46-L60. Maybe this can help us narrow down where the problem is.

On/after #8379 and https://github.com/sphinx-gallery/sphinx-gallery/pull/759 we can iterate and test hopefully fairly easily using `PATTERN=... make html_dev-pattern-memory`

**Comment by larsoner** [comment]
Never mind, it does happen on `plot_meg_sensors.py`...

**Comment by larsoner** [comment]
This is an upstream issue so I'll close at our end
