### ISSUE TITLE
Tuple as default parameter in function signature is not rendered correctly in the documentation

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#8247]
For example, the signature of `Epochs.apply_baseline()` is:

```python
    def apply_baseline(self, baseline=(None, 0), verbose=None):
```

yet, [in the documentation](https://mne.tools/dev/generated/mne.Epochs.html?highlight=epochs#mne.Epochs.apply_baseline) this is rendered as:

```python
apply_baseline(baseline=None, 0, verbose=None)
```

**Comment by larsoner** [comment]
Upstream bug https://github.com/sphinx-doc/sphinx/issues/8052 https://github.com/sphinx-doc/sphinx/pull/8053
