### ISSUE TITLE
3D Mayavi - Mac Os X problems

### ISSUE THREAD

**Issue by RickLicona** [mne-tools/mne-python#8277]
Hi,

The Mayavi tool is too slow In Mac Os X. I am programming some MNE examples (head model and forward computation), and some times the 3D models does not appear (TVTK white window). Also, when the 3D model appears, it is impossible to interact with the models. 

The fast code solution to see at least a image of the 3D simulation is: 

```
from mayavi import mlab 
#mlab.options.offscreen = True
mlab.init_notebook() 

# The transformation file obtained by coregistration
trans = data_path + '/MEG/sample/sample_audvis_raw-trans.fif'

info = mne.io.read_info(raw_fname)
# Here we look at the dense head, which isn't used for BEM computations but
# is useful for coregistration.
coregistration = mne.viz.plot_alignment(info, trans, subject=subject, dig=True,
                       meg=["helmet", "sensors"], subjects_dir=subjects_dir,
                       surfaces='head-dense')
coregistration
```
 I would like to have a solution for this issue. 

Some recommendations? 

Best.

**Comment by larsoner** [comment]
What is `mne.sys_info()`? I wonder if your OpenGL support is too old.

You could try wrapping the `plot_alignment` call in a `with mne.viz.use_3d_backend('pyvista')` to see if PyVista does any better, but these both use VTK under the hood so I'd be suprised.

**Comment by RickLicona** [comment]
> What is `mne.sys_info()`? I wonder if your OpenGL support is too old.
> 
> You could try wrapping the `plot_alignment` call in a `with mne.viz.use_3d_backend('pyvista')` to see if PyVista does any better, but these both use VTK under the hood so I'd be suprised.

Platform:      Darwin-19.6.0-x86_64-i386-64bit
Python:        3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13)  [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
Executable:    /Users/ricklicona/PycharmProjects/RExam/bin/python
CPU:           i386: 8 cores
Memory:        Unavailable (requires "psutil" package)
mne:           0.20.8
numpy:         1.15.2 {blas=openblas, lapack=openblas}
scipy:         1.5.2
matplotlib:    3.0.2 {backend=module://ipykernel.pylab.backend_inline}

sklearn:       0.21.3
numba:         0.43.1
nibabel:       3.1.1
cupy:          Not found
pandas:        0.25.1
dipy:          Not found
mayavi:        4.7.2 {qt_api=pyqt5, PyQt5=5.15.1}
pyvista:       0.26.0
vtk:           8.1.0

**Comment by agramfort** [comment]
+1 to try using pyvista

>

**Comment by hoechenberger** [comment]
I also wonder if VTK 9 would improve things here? We're going to release MNE-Python 0.21 very soon hopefully, with support for VTK 9.

**Comment by RickLicona** [comment]
I tried this:
```
# The transformation file obtained by coregistration
trans = data_path + '/MEG/sample/sample_audvis_raw-trans.fif'

info = mne.io.read_info(raw_fname)
# Here we look at the dense head, which isn't used for BEM computations but
# is useful for coregistration.
with mne.viz.use_3d_backend('pyvista'):

        mne.viz.plot_alignment(info, trans, subject=subject, dig=True,
                       meg=["helmet", "sensors"], subjects_dir=subjects_dir,
                       surfaces='head-dense')
```

**Out:**

Read a total of 3 projection items:
        PCA-v1 (1 x 102)  idle
        PCA-v2 (1 x 102)  idle
        PCA-v3 (1 x 102)  idle
Using pyvista 3d backend.

Using lh.seghead for head surface.
Getting helmet for system 306m
Using mayavi 3d backend.

**However, I got the next error message:**

QtDeprecationError: `BackgroundPlotter` has moved to pyvistaqt.
    You can install this from PyPI with: `pip install pyvistaqt`
    See https://github.com/pyvista/pyvistaqt 

It seems that the solution is here:  QtDeprecationError is unclear #826 (https://github.com/pyvista/pyvista/issues/826), but it is not a MNE case.  

Also I tried a Eric's code:
```

import mne
from pyvistaqt import BackgroundPlotter
fname = mne.datasets.sample.data_path() + '/MEG/sample/sample_audvis_raw.fif'
raw = mne.io.read_raw_fif(fname)
with mne.viz.use_3d_backend('pyvista'):
    mne.viz.plot_alignment(raw.info, show_axes=True, eeg=False, surfaces=[])
```
I got the same error message.

**Comment by larsoner** [comment]
Did you try the solution suggested by the error, namely `pip install pyvistaqt`? It should install, then it should not error on these lines (that way at least) anymore.

**Comment by hoechenberger** [comment]
Hello @RickLicona, have you been able to resolve this?

**Comment by RickLicona** [comment]
> Hello @RickLicona, have you been able to resolve this?

Hi,

Thanks for the interest!. Unfortunately, I cannot resolve this issue, despite the error suggest of install pyvistaqt (0.2.0). I added this tool in my Pycharm IDE, however, the error remains equal. When I come back again to this part of MNE tutorial and found the solution, I will publish it ;). 

![imagen](https://user-images.githubusercontent.com/22995049/94358325-c747cb00-0065-11eb-96b6-99c1ff453358.png)

Best.

**Comment by RickLicona** [comment]
Dear all, 

This part of the code (**Visualizing the coregistration**) from the tutorial named **Head model and forward computation** does no longer generate any error messages.  Now I have the correct 3D simulations :-).

![imagen](https://user-images.githubusercontent.com/22995049/95120480-3e8af800-0713-11eb-884a-f57f200fd796.png)
![imagen](https://user-images.githubusercontent.com/22995049/95120543-5a8e9980-0713-11eb-87b7-70661821ba37.png)


On the other hand, it seems that is not appropiate the next code for the future, the 3D simulation is wrong. 
![imagen](https://user-images.githubusercontent.com/22995049/95120867-cb35b600-0713-11eb-9071-ca53201eac99.png)
![imagen](https://user-images.githubusercontent.com/22995049/95120893-db4d9580-0713-11eb-9cef-048f6c43b323.png)


Here is another example with correct 3D simulation:
![imagen](https://user-images.githubusercontent.com/22995049/95121864-4c417d00-0715-11eb-8409-c233ff71e5c6.png)
![imagen](https://user-images.githubusercontent.com/22995049/95121924-5d8a8980-0715-11eb-8691-97c4de09643a.png)


This is my` mne.sys_info()`:
![imagen](https://user-images.githubusercontent.com/22995049/95121072-1fd93100-0714-11eb-884d-12a099656db2.png)

 **Also, I have installed pvistaqt (0.2.0), FreeSurfer 6.0 and the Mac OS X patch for 6.0 version (https://drive.google.com/file/d/1ezjiNIbGNrNAiYD5ciYxMO2SK-R5vz9A/view)**

**OS version: macOS Catalina 10.15.7 (the last version)**

THANKS FOR THE HELP AND UPDATE :-) !!

Best wishes,
Ricardo.

**Comment by larsoner** [comment]
> On the other hand, it seems that is not appropiate the next code for the future, the 3D simulation is wrong.

What's wrong with that image?

**Comment by RickLicona** [comment]
> > On the other hand, it seems that is not appropiate the next code for the future, the 3D simulation is wrong.
> 
> What's wrong with that image?

It does not generate the image as the original MNE tutorial (https://mne.tools/dev/auto_tutorials/source-modeling/plot_forward.html, , see the below image). In resume, the code from the original tutorial (**visualizing the coregistration** ) is enough, there is not more error messages as I had before.  

![Captura de Pantalla 2020-10-05 a la(s) 15 26 06](https://user-images.githubusercontent.com/22995049/95128956-d2fb5780-071f-11eb-8408-d8242d1b1c95.png)

**Comment by larsoner** [comment]
That example code has `surfaces=['head-dense']`, the code that precedes the image below has `surfaces=[]`, so it should not show any surfaces (i.e., it looks correct)
