### ISSUE TITLE
MAINT: CircleCI builds take 2h

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#8284]
This is just for the "build" step. Installation plus artifacts and the like make it take about 2.5 hours total.

We should look into streamlining some examples. Maybe some can also be combined and turned into tutorials (many machine learning ones?).

**Comment by agramfort** [comment]
+1000

>

**Comment by hoechenberger** [comment]
Can we not split testing into several, independent, parallel jobs?

**Comment by agramfort** [comment]
here it's not for testing but generating the documentation. We have too
many examples generated by sphinx gallery

>

**Comment by hoechenberger** [comment]
Thanks for the clarification!
Sounds good to me we seem to have such extensive documentation ;)
