### ISSUE TITLE
MNE Python Plotting for Time Series Data: Issue with mne.read_epochs_eeglab

### ISSUE THREAD

**Issue by agquinn** [mne-tools/mne-python#8290]
#### Describe the bug
〈There seems to be an issue with mne.read_epochs_eeglab modifying data slightly. When using MNE to plot time series data for the purpose of comparison to time series data in Matlab, the underlying data used in MNE is different than the actual data in Matlab. I plotted my time series data using Matplotlib, and was able to successfully reproduce the time series plot for my data in Matlab, but could not do so using MNE python, due to this issue.〉

#### Steps to reproduce
〈In Matlab, to plot the time series data for analysis:

(Google drive links to Subject1-csd_epo.set and Subject1-csd_epo.fdt files) 
https://drive.google.com/file/d/1DmPQ_jSFkK2gnkMpz17ieitZjYhWSTe6/view?usp=sharing
https://drive.google.com/file/d/1qkvSuqNyTrj-6yhaXXP-iL3d6qI3gZIM/view?usp=sharing

`EEG = pop_loadset('Subject1-csd_epo.set');`
`plot(EEG.times, EEG.data(5, :, 1));`

In MNE Python to plot the time series data:
`import mne`
`import matplotlib.pyplot as plt`
`epochs = mne.read_epochs_eeglab('Subject1-csd_epo.set')`
`epochs.load_data()`
`plt.plot(epochs.times, epochs._data[0, 4])`
`plt.show()`
 
In Matplotlib:
`plt.plot(epochs._data[0, 0, :])`
`plt.show()`
 〉

[MWE]: https://en.wikipedia.org/wiki/Minimal_Working_Example
[built-in datasets]: https://mne.tools/dev/overview/datasets_index.html
[sample]: https://mne.tools/dev/overview/datasets_index.html#sample

#### Expected results
〈I expected the time series data plotted in Matlab, for subject 1, channel 5 (the C3 electrode channel), and epoch 1 to match the time series data plotted using MNE Python.〉

#### Actual results
〈I had the following time series plots using Matlab, Matplotlib and MNE Python, and they do not match. There is an issue between the underlying data MNE python used to create the time series plots, and the underlying data used in Matlab and in Matplotlib:

This is the plot using matlab:
![matlab_time_series_subj_1](https://user-images.githubusercontent.com/68566436/93926453-62d6e580-fccc-11ea-9e45-72c1966461d4.jpg)
This is the plot using matplotlib:
![matplotlib_time_series_subj_1](https://user-images.githubusercontent.com/68566436/93926567-8568fe80-fccc-11ea-841e-4eac85379b02.png)
)

#### Additional information
〈Replace this text with the output of `mne.sys_info()`.〉

**Comment by agquinn** [comment]
@alexrockhill

**Comment by agramfort** [comment]
if you want channel 5 in python you need to do:

plt.plot(epochs.times, epochs._data[0, 4])

not

plt.plot(epochs.times, epochs._data[0, 5])

>

**Comment by agquinn** [comment]
Thank you; I missed that earlier. I think that might be the issue I was actually having.
