### ISSUE TITLE
Is it a correct definition of PLV?

### ISSUE THREAD

**Issue by dahaiyu** [mne-tools/mne-python#8305]
In the following page, I found the PLV definition is given as follows: PLV = |E[Sxy/|Sxy|]|. It is different from the definition in the reference. Are these two equivalent?

[https://mne.tools/stable/generated/mne.connectivity.spectral_connectivity.html?highlight=spectral_connectivity#mne.connectivity.spectral_connectivity](url)

reference: Lachaux et al. “Measuring phase synchrony in brain signals” Human brain mapping, vol. 8, no. 4, pp. 194-208, Jan. 1999.

**Comment by agramfort** [comment]
yes it is equilavent

>

**Comment by agramfort** [comment]
This appears to be a question about usage, not a bug report or a new feature request. Please use the [MNE mailing list](http://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis) or the [gitter channel](https://gitter.im/mne-tools/mne-python) for usage questions.
