### ISSUE TITLE
Nihon Kohden Description of Data Files 

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-python#8319]
#### Problem
In https://github.com/mne-tools/mne-python/pull/6017/files# this was an initial add to mne python that allows reading in of NK files, which is awesome! 

I'm a relatively novice user to NK since mne never had a python reader for it, but now that it does, I'm interested in using it more on NK raw data. However, I noticed that all the other readers have an entry here https://mne.tools/dev/auto_tutorials/io/plot_20_reading_eeg_data.html

Is it possible to add a documentation entry there to describe the different files for NK and how they're used in mne?

#### Possible Solutions
A description at https://mne.tools/dev/auto_tutorials/io/plot_20_reading_eeg_data.html to describe all the file inputs and what they contain for users that are about to use the NK files but not totally familiar with the file formats.

I can add this if someone just points me in the right direction because I wanted to learn the nuances of the NK file format :).

**Comment by larsoner** [comment]
> I can add this if someone just points me in the right direction because I wanted to learn the nuances of the NK file format :).

PR welcome! I would start with at least some stub saying that it's possible to read data in that format *at all*. We just forgot to add it in #6017
