### ISSUE TITLE
ICA should not touch init parameter n_pca_components during fit

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#8327]
This is what currently happens in `ICA._fit()`, which is invoked by `ICA.fit()`:
https://github.com/mne-tools/mne-python/blob/4270859dc3ba2208bb3eed4f73403b5de26125b8/mne/preprocessing/ica.py#L737-L739

We should have `ICA.n_pca_components_` instead (currently doesn't exist).

**Comment by larsoner** [comment]
Agreed this is a bug
