### ISSUE TITLE
viz.plot_ica_overlay needs an n_pca_components kwarg

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#8342]
While `ICA.apply()` does have `n_pca_components`, `ICA.plot_overlay()` does not, making it more difficult to interactively explore the effect of using different numbers of components for signal reconstruction.

**Comment by hoechenberger** [comment]
cc @drammock @cbrnr

**Comment by agramfort** [comment]
indeed it would be very helpful to add it.

>

**Comment by drammock** [comment]
I'm off this week (moving house) but will take a look next week. Thanks for flagging it for me @hoechenberger

**Comment by hoechenberger** [comment]
@drammock No worries, I will probably address this myself within the next couple of days. Just tagged you to hear your opinion (approval or objection, but I take this as a +1 from your side :))
