### ISSUE TITLE
method like 'resample' for mne.io.BaseRaw

### ISSUE THREAD

**Issue by BarryLiu-97** [mne-tools/mne-python#8347]
When I use the method, for example, resampled_data = data.resample(200), I found the original variable 'data' is changed as well. What should I do if I want only the variable **resampled_data**  is the data that got resampled, and the variable **data** stay still.

**Comment by cbrnr** [comment]
First copy your data and then resample, e.g. `raw.copy().resample(200)`.

**Comment by BarryLiu-97** [comment]
> First copy your data and then resample, e.g. `raw.copy().resample(200)`.

Thank u so much!
