### ISSUE TITLE
BUG: 1. and 1 treated differently in ICA

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#8353]
From #8351.

My proposed solution is to disallow `1.`. We have `None` for "select all components", so we don't actually need `1.`.

**Comment by larsoner** [comment]
cc @hoechenberger @cbrnr

**Comment by agramfort** [comment]
+1 to disallow 1.

>

**Comment by hoechenberger** [comment]
+1 to disallow

**Comment by hoechenberger** [comment]
To be more precise, I think we should disallow 1 as int, and allow 1.0 as float. 

If we decide to keep allowing 1 as int, 1.0 float should not be allowed.

**Comment by larsoner** [comment]
I don't think we should allow `1.` (float), I'm okay with `1` as an int -- maybe there is some use case for it

**Comment by larsoner** [comment]
Okay let's just disallow both. ICA is a no-op when you set `n_components=1` so it doesn't really make sense

**Comment by agramfort** [comment]
using 1 component does not make sense ! the mixing matrix is a float and
scale is not "estimable" in ICA so....

>

**Comment by cbrnr** [comment]
Yes, let's either disallow both or allow both (and then both 1 and 1.0 refer to all components because one component doesn't make sense).

**Comment by hoechenberger** [comment]
Uh please don't allow both then, for the sake of API consistency

**Comment by cbrnr** [comment]
I'm fine with disallowing both, but IMO `1 == 1.0` is consistent.
