### ISSUE TITLE
Issues on events of EEG data

### ISSUE THREAD

**Issue by BarryLiu-97** [mne-tools/mne-python#8369]
My EEG Data's marker directly got from the machine is wrong, which we knew already, while we have some marker channels, aka the stimulus electrodes, to calculate the markers. Here are my  two questions:
1. How do I not import the default events got from the machine in this data, for example, in **eeglab**, we can set _importevent_ as off so we won't import the events. Then we add the events manually. Or, how do I delete all the information about events and then add events manually?
2. How do I get epoched data with markers(or events) into a 3_d tensor.

**Comment by BarryLiu-97** [comment]
About the events calculated manually, I got the event latency and the value of the event.

**Comment by agramfort** [comment]
This appears to be a question about usage, not a bug report or a new feature request. Please use the [MNE mailing list](http://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis) or the [gitter channel](https://gitter.im/mne-tools/mne-python) for usage questions.
