### ISSUE TITLE
"Sorted by RT" erpimage in examples clearly isn't sorted by RT

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#8370]
<img width="1010" alt="Screenshot 2020-10-15 at 10 34 04" src="https://user-images.githubusercontent.com/4321826/96098149-14cf8f00-0ed2-11eb-96e0-85a1db0f9d99.png">

This has been broken since 0.18: https://mne.tools/0.18/auto_examples/visualization/plot_roi_erpimage_by_rt.html#sphx-glr-auto-examples-visualization-plot-roi-erpimage-by-rt-py

**Comment by larsoner** [comment]
@drammock do you want to take a look?

**Comment by drammock** [comment]
I'll take a look today
