### ISSUE TITLE
mne.Epochs documentation around baseline is unclear

### ISSUE THREAD

**Issue by colinquirk** [mne-tools/mne-python#8386]
It looks like there is no baseline by default as baseline defaults to None, but there is a note that says "Defaults to (None, 0), i.e. beginning of the the data until time point zero."

**Comment by agramfort** [comment]
PR welcome to fix the docstring

thanks

>

**Comment by colinquirk** [comment]
If that comment should just be removed, will do

**Comment by drammock** [comment]
> It looks like there is no baseline by default as baseline defaults to None

This is incorrect. `baseline` defaults to `(None, 0)`, the documentation is correct. see here, the line in current master:

https://github.com/mne-tools/mne-python/blob/864426c4839bab05fd0d142ee20938c336c0b78e/mne/epochs.py#L2055

**Comment by colinquirk** [comment]
My mistake, the parens are dropped in the signature so it looked like baseline=None to me

**Comment by drammock** [comment]
ah, OK.  That is good to know. Probably a bug in Sphinx (the software that renders our docs to HTML).

**Comment by larsoner** [comment]
Yep it's #8247, currently blocked from being fixed actually by #8375
