### ISSUE TITLE
A question about "-trans.fif"

### ISSUE THREAD

**Issue by zhchsh19** [mne-tools/mne-python#8387]
Sorry to bother all of you , but I have a big question.

![2020-10-19 22-46-03屏幕截图](https://user-images.githubusercontent.com/51749581/96467550-9bcb9100-125d-11eb-874e-840414d0aa37.png)

but I can't find the file in 'bem' file. and I also get this error:
![2020-10-19 22-54-56屏幕截图](https://user-images.githubusercontent.com/51749581/96467990-244a3180-125e-11eb-8546-ba55bacf294d.png)

This is my code to get 'bem'

export FREESURFER_HOME=/home/zhanglingxi/freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh
 export SUBJECTS_DIR=/home/zhanglingxi/freesurfer2/subjects
my_subject=subdw
my_NifTI=/media/zhanglingxi/zlx-1/SMRI/NIF/s20180417_T09_LongZYL_ZHN_DaiWei-0002-00001-000144-01.nii.gz
recon-all -i $my_NIfTI -s $my_subject -all
subjects_dir=/home/zhanglingxi/freesurfer2/subjects
 mne watershed_bem -s subdw

And I used to get a ' fsaverage' in '/freesurfer2/subjects/sub' ,then I don't have the question above, but now I can't get it 
![2020-10-19 22-59-58屏幕截图](https://user-images.githubusercontent.com/51749581/96468562-d681f900-125e-11eb-8a46-2025b41db9a0.png)

![2020-10-19 23-01-04屏幕截图](https://user-images.githubusercontent.com/51749581/96468705-faddd580-125e-11eb-98b8-1825653650a5.png)

![2020-10-19 23-03-29屏幕截图](https://user-images.githubusercontent.com/51749581/96469014-51e3aa80-125f-11eb-84fe-8531ff9ba2d6.png)

**Comment by zhchsh19** [comment]
[s20180417_T09_LongZYL_ZHN_DaiWei-0002-00001-000144-01.nii.gz](https://github.com/mne-tools/mne-python/files/5402840/s20180417_T09_LongZYL_ZHN_DaiWei-0002-00001-000144-01.nii.gz)


This is my data

**Comment by larsoner** [comment]
> And I used to get a ' fsaverage' in '/freesurfer2/subjects/sub' ,then I don't have the question above, but now I can't get it

You should not put `fsaverage` in `/home/zhanglingxi/freesurfer2/subjects/sub/fsaverage` -- if your `subjects_dir` is `/home/zhanglingxi/freesurfer2/subjects`, you should put it in `/home/zhanglingxi/freesurfer2/subjects/fsaverage`. `fsaverage` is a subject, it should be directly in your SUBJECTS_DIR, not in a subdirectory.

> and I also get this error:

The error message recommends running `mne make_scalp_surfaces` for your subject. Did you do this? If you did, you should have `SUBJECTS_DIR/SUBJECT/surf/lh.seghead` and `SUBJECTS_DIR/SUBJECT/bem/SUBJECT-head.fif`.

**Comment by zhchsh19** [comment]
yes, I have done it, and I also have SUBJECTS_DIR/SUBJECT/surf/lh.seghead and SUBJECTS_DIR/SUBJECT/bem/SUBJECT-head.fif ,but there is still the same question

**Comment by larsoner** [comment]
The coreg error image says it's trying to use `/home/zhanglingxi/freesurfer2/subjects/subdw` as the SUBJECTS_DIR, which is incorrect -- it should be `/home/zhanglingxi/freesurfer2/subjects/`. Can you try `mne coreg -d /home/zhanglingxi/freesurfer2/subjects`, or set `export SUBJECTS_DIR=/home/zhanglingxi/freesurfer2/subjects` and then run `mne coreg` and see if it works? Do you get the same error message as before but then with `/home/zhanglingxi/freesurfer2/subjects` as the path?

**Comment by zhchsh19** [comment]
It works, I didn't set the path before, thanks very much
