### ISSUE TITLE
Default topomap interpolation a bit uglier than some time before

### ISSUE THREAD

**Issue by mmagnuski** [mne-tools/mne-python#8425]
I noticed that current topomap interpolation with `extrapolate='head'` produces more artifacts at the edges than in the previous version. Take a look at this:
### before
![image](https://user-images.githubusercontent.com/8452354/97121321-b7cba880-171d-11eb-9030-45863668659e.png)

### now
![image](https://user-images.githubusercontent.com/8452354/97121378-0711d900-171e-11eb-9e1c-d88ed2d6b53c.png)

Now the topos look ok only in `extrapolate='local'` mode (so I've learnt to like the non-circular convex hull mask).
I think I may be partly responsible for this. I have a vague memory of adding more extrapolation points some time ago to `extrapolate='head'`, but I can't find the PR now.
I'll try to take a look at this in the upcoming week.

**Comment by larsoner** [comment]
@mmagnuski we're making a push to release in a couple of weeks, do you have time to look into this in that time?

**Comment by mmagnuski** [comment]
I might have some time for this next week, I'll try to look into it!

**Comment by mmagnuski** [comment]
I still remember about this issue, I might find some time for it tomorrow.

**Comment by mmagnuski** [comment]
I finally got to it. It turns out my intuition was correct, plot_topomap creates too many extrapolation points:
<img src=https://user-images.githubusercontent.com/8452354/101838954-cb05cc80-3b41-11eb-8543-4a29ba18bca8.PNG width="300pix">
you can also see that the whole circle was not divided evenly (the red arrow), which was the cause of the funny extrapolation artifacts on the right side of the topos.
I reduced the number of points in the PR (#8645) and fixed the uneven circle division:
<img src=https://user-images.githubusercontent.com/8452354/101839206-3fd90680-3b42-11eb-8cd2-df8b96f040fe.PNG width="300pix">

It is better, but still could be improved (left: master, right: PR)
<img src=https://user-images.githubusercontent.com/8452354/101839330-77e04980-3b42-11eb-931f-58faf3e39e73.PNG width="800pix">

I'll see how increasing the distance of extrapolation points and further reducing their number helps, but I would prefer not to overfit to my specific cap layout :), so I would appreciate if other EEG users that experienced this problem let me know.

`extrapolate='box'` works good in these cases so increasing the distance between the extrapolation points and channels positions should help.

**Comment by agramfort** [comment]
PR on the way?

I would be great if the default could be the best option... just saying

>

**Comment by mmagnuski** [comment]
@agramfort Yes, its in progress, I linked it in the post above (#8645).
