### ISSUE TITLE
"If comment is empty, a 1-based index is assigned by Richard Höchenberger" – What's New entries

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#8436]
Hello, I just wanted to inquire if we could, maybe, agree to always add a comma before the contributors' names in our changelogs? Otherwise we keep producing sometimes confusing, sometimes rather hilarious lines like the one in the title.

The latest changelog(s) have been rather inconsistent in that manner, although my impression is that more and more of those commas have made it through the review process.

So what I'm proposing is that instead of:

> If comment is empty, a 1-based index is assigned by Richard Höchenberger

we'd add an entry

> If comment is empty, a 1-based index is assigned, by Richard Höchenberger

WDYT?

cc @cbrnr @agramfort @sappelhoff @larsoner @drammock

**Comment by agramfort** [comment]
+1 for ,

>

**Comment by sappelhoff** [comment]
> +1 for ,

agreed

**Comment by larsoner** [comment]
I'm happy with that, or switch to `(by whoever, :gh:whatever)`

**Comment by drammock** [comment]
I am also pro-comma, and have recently been asked (though I forget by who) to remove them in my PRs for the sake of consistency. So I would like this policy change to be documented somewhere.

**Comment by hoechenberger** [comment]
> and have recently been asked (though I forget by who) to remove them in my PRs for the sake of consistency with other people's entries.

Might have been me 😁

**Comment by cbrnr** [comment]
I'm 👍 for `(by whoever, :gh:whatever)` - it is easier to see the contributor when there are parens.

**Comment by hoechenberger** [comment]
> I'm 👍 for `(by whoever, :gh:whatever)` - it is easier to see the contributor when there are parens.

I like this proposal too, but would prefer it without the `by`. I'm +1 for `,` and +1.75 for `(My Name, #foo)`

**Comment by larsoner** [comment]
Works for me

**Comment by drammock** [comment]
me too. But again, please document the new standard in our contributing docs.  Since the `latest.inc` gets reset every release, it's too easy for the first couple of PRs to do it their own way and set a precedent for the remainder of the release cycle.

**Comment by cbrnr** [comment]
Yes, I like it!

**Comment by hoechenberger** [comment]
So... Which one now? Comma? Or the parentheses? I'm confused, and it's my own fault haha

**Comment by drammock** [comment]
let's go with
```
(`Contributor Name`_, `Second Contributor`_ and `Third Contributor`_, :gh:`0000`)
```

**Comment by cbrnr** [comment]
Yes, but let's use an Oxford comma please.
