### ISSUE TITLE
Raw.plot() issue

### ISSUE THREAD

**Issue by BarryLiu-97** [mne-tools/mne-python#8441]
I found something maybe a bug.
Now I used the master branch in GitHub.  I use Pycharm and terminal to run codes. One of my examples uses **raw.plot()** to plot raw data.  While I ran codes in Pycharm's console, **raw.plot()** went well, a figure showed up. While I ran .py in terminal like **python test.py**, no figure showed up. And if I type **python** in the terminal and type the codes in this way, also no figures showed up. But if I used the stable mne, everything was OK.

**Comment by cbrnr** [comment]
Can you provide a minimal example (ideally using a sample dataset shipped with MNE) that demonstrates the issue?

**Comment by BarryLiu-97** [comment]
Now I use https://mne.tools/stable/auto_tutorials/raw/plot_40_visualize_raw.html#sphx-glr-auto-tutorials-raw-plot-40-visualize-raw-py to plot raw data run by the terminal in win10. When I ran raw.plot(), nothing showed up.

**Comment by BarryLiu-97** [comment]
my mne version is 0.22.dev0

**Comment by hoechenberger** [comment]
> While I ran .py in terminal like **python test.py**, no figure showed up.

Can you try running in the terminal with

```
python -i test.py
```

**Comment by BarryLiu-97** [comment]
> > While I ran .py in terminal like **python test.py**, no figure showed up.
> 
> Can you try running in the terminal with
> 
> ```
> python -i test.py
> ```

I did that, it was the same. no figure.

**Comment by BarryLiu-97** [comment]
import os
import mne

sample_data_folder = mne.datasets.sample.data_path()
sample_data_raw_file = os.path.join(sample_data_folder, 'MEG', 'sample',
                                    'sample_audvis_raw.fif')
raw = mne.io.read_raw_fif(sample_data_raw_file)
raw.crop(tmax=60).load_data()

raw.plot()

**Comment by BarryLiu-97** [comment]
In the stable version, it went well.

**Comment by BarryLiu-97** [comment]
The interesting thing is, if I run the codes, the figure will show up.

**Comment by hoechenberger** [comment]
@drammock You think this could be related somehow to the new figure class?

**Comment by hoechenberger** [comment]
Can reproduce on macOS with `master`.

**Comment by hoechenberger** [comment]
@BarryLiu-97 
I worked around this problem by adding
```python
import matplotlib.pyplot as plt
plt.show()
```
at the end of your script

**Comment by BarryLiu-97** [comment]
> @BarryLiu-97
> I worked around this problem by adding
> 
> ```python
> import matplotlib.pyplot as plt
> plt.show()
> ```
> 
> at the end of your script

Yeah, that's right. Me too.

**Comment by BarryLiu-97** [comment]
> > @BarryLiu-97
> > I worked around this problem by adding
> > ```python
> > import matplotlib.pyplot as plt
> > plt.show()
> > ```
> > 
> > 
> > at the end of your script
> 
It reminds me that Pycharm console is like jupyter notebook, don't need plt.show and the figure still shows up.

**Comment by BarryLiu-97** [comment]
> > > @BarryLiu-97
> > > I worked around this problem by adding
> > > ```python
> > > import matplotlib.pyplot as plt
> > > plt.show()
> > > ```
> > > 
> > > 
> > > at the end of your script
> 
> It reminds me that Pycharm console is like jupyter notebook, don't need plt.show and the figure still shows up.

Seems that I still have a lot to learn. I didn't connect my experience to this issue.

**Comment by hoechenberger** [comment]
> Seems that I still have a lot to learn. I didn't connect my experience to this issue.

That may be true, but you actually discovered a bug in MNE, so it's great you reported it! It should've worked the way you tried to do it.

**Comment by BarryLiu-97** [comment]
> > Seems that I still have a lot to learn. I didn't connect my experience to this issue.
> 
> That may be true, but you actually discovered a bug in MNE, so it's great you reported it! It should've worked the way you tried to do it. We'll see how we can fix this.

All right. Looking forward to it.
