### ISSUE TITLE
Some advice on processing sEEG and ECoG data

### ISSUE THREAD

**Issue by BarryLiu-97** [mne-tools/mne-python#8443]
I noticed that recently you guys are working on the iEEG process. Recently I found a paper called **Multi-Modal Neuroimaging Analysis and Visualization Tool (MMVT)** on arxiv. Here is its official website https://mmvt.mgh.harvard.edu/preprocessing. I think this may provide some inspiration for the process of the iEEG data.

**Comment by larsoner** [comment]
Oddly enough [here](https://github.com/pelednoam/mmvt) it says:

> The project’s code is still under active development, but temporarily going off-grid. 

But in any case, feel free to list concrete ideas here. I don't think we plan to support everything that MMVT does (it has quite a feature list!) so we should focus on just what people need most urgently.

**Comment by BarryLiu-97** [comment]
> 
> 
> Oddly enough [here](https://github.com/pelednoam/mmvt) it says:
> 
> > The project’s code is still under active development, but temporarily going off-grid.
> 
> But in any case, feel free to list concrete ideas here. I don't think we plan to support everything that MMVT does (it has quite a feature list!) so we should focus on just what people need most urgently.

Can't argue with that.
