### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#8456]
Python 3.9 has been released. We need to ensure MNE works with it.

https://docs.python.org/3/whatsnew/3.9.html

**Comment by cbrnr** [comment]
NumPy has just released binary wheels, still waiting for SciPy and Matplotlib.

**Comment by GuillaumeFavelier** [comment]
> There are no wheels available for VTK on Python 3.9

Reference: https://github.com/pyvista/pyvista-support/issues/263#issuecomment-709690569
