### ISSUE TITLE
stc_near_sensors mode has incongruent docstring

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-python#8479]
#### Proposed documentation ehancement
I think(?) `stc_near_sensors` only enables nearest, single and sum, but it also says there is a "zero" and "weighted" option? 

Once it's cleared up what sort of activation `mode`s are available and when, I can make a PR to fix up the docstring.

Reference: https://mne.tools/dev/generated/mne.stc_near_sensors.html?highlight=stc_near#mne.stc_near_sensors

**Comment by larsoner** [comment]
It's likely that the docstring is outdated -- let's update it to do what the code actually does/has

**Comment by eort** [comment]
I'll have a go

**Comment by eort** [comment]
renders fine: https://26258-1301584-gh.circle-artifacts.com/0/dev/generated/mne.stc_near_sensors.html
