### ISSUE TITLE
Dynamic frequency connectivity measures

### ISSUE THREAD

**Issue by balandongiv** [mne-tools/mne-python#8480]
Currently mne support for static connectivity measures via [spectral_connectivity](https://github.com/mne-tools/mne-python/blob/0e080a5a645b5934445ef4da6da744d7dfa7f68d/mne/connectivity/spectral.py#L549). But I notice there is no direct module for Dynamic frequency connectivity measures (Please correct just in case I miss about the existence of such module). 

One approach that I can think in order to achieve this is simply by looping the `spectral_connectivity` over the desired time span.. Say for example, the sliding window is of 2sec width, the code below perhaps can do the task.

```

import mne
from mne import io
from mne.connectivity import spectral_connectivity
from mne.datasets import sample

data_path = sample.data_path()
raw_fname = data_path + '/MEG/sample/sample_audvis_filt-0-40_raw.fif'
event_fname = data_path + '/MEG/sample/sample_audvis_filt-0-40_raw-eve.fif'
raw = io.read_raw_fif(raw_fname)
events = mne.read_events(event_fname)
ch_names = raw.info['ch_names']
picks = mne.pick_channels(ch_names=ch_names,include=['EEG 001','EEG 002','EEG 003'])
event_id, tmin, tmax = 1, -10, 0
epochs = mne.Epochs(raw, events, event_id, tmin, tmax, picks=picks)
fmin, fmax = 11.,16.
sfreq = raw.info['sfreq']  # the sampling frequency
tmin = 0  # exclude the baseline period
tmax=2
window_time=[-10,-8,-6,-4,-2]

epochs.load_data()
pli_list=[]
for i in window_time:
    epochs_win = epochs.copy ().crop ( tmin=i, tmax=i+2, include_tmax=True )
    con, freqs, times, n_epochs, n_tapers = spectral_connectivity(
        epochs_win, method='pli', mode='multitaper', sfreq=sfreq, fmin=fmin, fmax=fmax,
        faverage=True,mt_adaptive=False, n_jobs=1)
    pli_list.append(con)
```

But Im curious whether there are mne ways that is much more efficient than the above proposed code, or even better if there is specific mne module that I might be miss out during my search?

**Comment by larsoner** [comment]
Looks like this is the same as #8729 so I'll close this one
