### ISSUE TITLE
Why does read_evokeds() have an allow_maxshield param, while read_epochs() doesn't?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#8487]
Evoked data is further down in the processing stream than Epochs, so if `read_evokeds()` has `allow_maxshield`, `read_epochs()` should have it too, no?

**Comment by larsoner** [comment]
We only need this parameter for types that get written as having maxshield/IAS applied. MEGIN writes raw and evoked this way. We keep this information for raw, but not epochs or evoked.

**Comment by hoechenberger** [comment]
Thanks for the clarification!
