### ISSUE TITLE
What can be done to overcome the drift that occurs in EEG

### ISSUE THREAD

**Issue by ometett** [mne-tools/mne-python#8497]
Dear MNE team,

I am an enthusiastic bioengineering student who is writing a program that synchronizes MEG with HD-EEG. I received serious help from you guys when I asked about importing EEG channels into the MEG file so here I am. My current code is able to synchronize HD-EEG with MEG based on the triggers that are sent from national instruments trigger box to both HD-EEG and MEG. Both recordings seem identical in the beginning. However, the HD-EEG slowly starts to drift away from MEG and that is the case for all of the EEG recordings I have which makes me think that this is a hardware(EGI) problem. My question is that what can I do to overcome the drift? I am currently using heartbeats as a biomarker and in the beginning the drift starts as 10 mili seconds but towards the end it becomes as big as 100 mili seconds. I would appreciate any kind of help/advice! 

Regards,

**Comment by cbrnr** [comment]
This is a usage question, please use our Gitter channel to ask usage questions: https://gitter.im/mne-tools/mne-python
