### ISSUE TITLE
Excluding channels fails in GDF files

### ISSUE THREAD

**Issue by Teteros** [mne-tools/mne-python#8511]
#### Describe the bug
`exclude()` doesn't seem to exclude the specified channels when reading GDF files (`mne.io.read_raw_gdf`)

#### Steps to reproduce
```python
>>> from mne import io
>>> io.read_raw_gdf("test.gdf", exclude=['Switches']).ch_names
Extracting EDF parameters from /tmp/test.gdf...
GDF file detected
Setting channel info structure...
Creating raw.info structure...
['Switches', 'ModEeg1', 'ModEeg2']
```

#### Expected results
```python
['ModEeg1', 'ModEeg2']
```

#### Additional information
Python 3.8.6 [GCC 10.2.0] on linux x64
mne 0.21.1

Test file used (created with [modeeg2ft_2chn](https://www.fieldtriptoolbox.org/development/realtime/modulareeg/)):
[test.gdf.zip](https://github.com/mne-tools/mne-python/files/5536270/test.gdf.zip)

**Comment by larsoner** [comment]
@cbrnr do you want to take a look?

**Comment by cbrnr** [comment]
Yes, will do.
