### ISSUE TITLE
BUG: Big Sur compat

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#8525]
More of an FYI than anything else -- PyQt5 appears not to work on Big Sur. I've tried 5.12 and 5.15.1, and both basically hang as soon as you make a mayavi, PyVista, or matplotlib Qt5Agg window.

So those thinking about upgrading, don't do so if you want to be able to use Python. For matplotlib at least we can use the MacOSX backend in the meantime, but 3D plotting is now (hopefully temporarily) totally broken for people who have upgraded. :(

Or maybe I'm the only one with this issue. If someone else upgrades, feel free to try it out and let me know!

**Comment by larsoner** [comment]
Closing because there isn't really anything for us to do. But we can keep any discussion about this here as things progress

**Comment by cbrnr** [comment]
Thanks for the heads up. I think this time I will upgrade as late as possible (this is the first time I haven't upgraded on day 1, and just like the new CPUs the macOS update doesn't really hype me).

**Comment by christianbrodbeck** [comment]
`os.environ['QT_MAC_WANTS_LAYER'] = '1'` ([stackoverflow](https://stackoverflow.com/a/64856281/166700)) at least gets the GUIs to open, will do some more testing.

**Comment by cbrnr** [comment]
I've done the upgrade and of course things don't work.
https://github.com/numpy/numpy/issues/17784

**Comment by hoechenberger** [comment]
I have been running Big Sur for over a week or so and no problems besides the Qt this be. I'm using conda-forge.

**Comment by cbrnr** [comment]
Yes, it's a pip issue. I know we recommend/support conda, but pip is still the default package manager and currently that doesn't work.

**Comment by hoechenberger** [comment]
Yep. Didn't mean to suggest otherwise, just wanted to share that it works well for me with `conda-forge` :)

**Comment by cbrnr** [comment]
The latest releases of pip and Homebrew fixed all issue, so everything is working on macOS/Homebrew.

**Comment by hoechenberger** [comment]
I'm constantly running into this issue if I forget to update my VS Code Run/Debug configuration accordingly. I **thought** we had added a workaound (setting the variable on macOS automatically) a while back, but cannot find any reference anymore?

**Comment by hoechenberger** [comment]
Never mind, it's mentioned right above:
https://github.com/mne-tools/mne-python/pull/8554

But like I said, this apparently doesn't fix the problem for me.

**Comment by larsoner** [comment]
> But like I said, this apparently doesn't fix the problem for me. Only setting the variable manually has helped so far.

That PR only fixed it for `mne coreg` and related GUIs that use traits+mayavi, not for code that uses matplotlib. For that, people should look to a matplotlib-generic solution such as setting this env var in their dev environment.

**Comment by cbrnr** [comment]
@hoechenberger are you using an old PyQt5 version? This has been fixed in 5.15.2.
