### ISSUE TITLE
ENH: Adjust simultaneous recordings time bases/starts/stops

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#8531]
@ometett on Gitter had a use case that we also have at UW: MEG (Neuromag) recorded simultaneously with data from another system (EGI/MFF). They both record at 1000 Hz, but clock drift (and start/stop times) need to be corrected to be able to analyze them together. I created a [gist](https://gist.github.com/larsoner/400b8b07cc89ad96fc2c02d0c3fa254b) to fix these issues, and it seems to work:
```
Drift rate computed to be 495.0 μs/sec (total drift over 398.0 sec recording: 197.0 ms)
```
And the STIM channels after `raw.add_channels`'ing match nicely. @ometett feel free to try it to see if it makes sense!

It would be nice to have a public API for this like:
```
mne.preprocessing.realign_recordings(raw, other, t_raw, t_other)
```
It has to operate in-place because `raw` and `other` can both be cropped depending on when their recordings started and stopped, and `other` will be resampled as necessary. This API seems pretty simple, for @ometett's data, where the STIM channels record the same events, the code would become just:
```
raw = mne.io.read_raw_fif('CC_CP004_PN_L_RUN01_tsss.fif')
other = mne.io.read_raw_egi('CC_CP004_PN_L_Run01_20201016_110457.mff')
t_raw = (mne.find_events(raw)[:, 0] - raw.first_samp) / raw.info['sfreq']
t_other = (mne.find_events(other)[:, 0] - other.first_samp) / other.info['sfreq']
# this will crop raw and other, and resample other in place
mne.preprocessing.realign_recordings(raw, other, t_raw, t_other)
```
The code to do this is mostly in the gist, so really we just need to decide if this is a suitable API and if the names are good.

**Comment by larsoner** [comment]
cc @cbrnr and @NeuroLaunch since we have had discussions about this before

**Comment by cbrnr** [comment]
Very nice! So the assumption is that you have the same set of events in both time domains? Could this be used for XDF streams that have a common time basis, but in general different sampling frequencies, to create a `Raw` object with all streams? Currently, MNELAB can only load one stream (and associated events) because resampling is not implemented.

How would you handle the case when two signals have vastly different sampling frequencies (e.g. EEG 512Hz and audio 44.1kHz)? Would it make sense to add an option to select a new sampling frequency for both signals (instead of requiring identical sampling frequencies)? #5180 is the corresponding issue.

**Comment by larsoner** [comment]
> So the assumption is that you have the same set of events in both time domains?

Yes and the user can do this however they want depending on their dataset

> Could this be used for XDF streams that have a common time basis, but in general different sampling frequencies, to create a Raw object with all streams?

In principle this approach could be used, but I would say it's out of scope for the first PR to fix the Neuromag+EGI case (and cases like it)

> How would you handle the case when two signals have vastly different sampling frequencies (e.g. EEG 512Hz and audio 44.1kHz)?

I would `raw.resample` one or both, then maybe use this function. But really for audio data I wouldn't really do this, cortical EEG responses won't track that fast so you're better off processing the envelope or otherwise downsampling the audio data to the physiological data. (If you're talking ABR hopefully you're sampling faster than 512 Hz.)

For the first version of this function I'd rather specify that it's designed primarily for data acquired at the same putative sampling rate to deal with start/stop/clock drift, and later we can expand functionality if need be. I think the current API is future compatible  with the two use cases listed above at least.

**Comment by cbrnr** [comment]
Sounds good!

**Comment by ometett** [comment]
@larsoner it works in my code too. Thank you very much Eric for the insight, I knew that the drift is linear but could not really figure out how I could manipulate the data where both recordings share the sampling rate. The names are looking good to me, a public API would really help the medical community!
