### ISSUE TITLE
Why mne.decode.CSP error after artifact removal with ICA? & How to normalize EEG data by using MNE? 

### ISSUE THREAD

**Issue by palm-audtachai** [mne-tools/mne-python#8555]
I have 2 question.
1. Why mne.decode.CSP error after artifact removal with ICA? 
I know process of EEG processing that we need to remove artifact before feature extraction so I do follow with BCI competition V dataset. after I remove artifact with ICA and use mne.decode.CSP. it has an error like this

![image](https://user-images.githubusercontent.com/57890260/99935985-926da100-2d94-11eb-8ba9-b8b996604281.png)
![image](https://user-images.githubusercontent.com/57890260/99936011-a87b6180-2d94-11eb-8dd8-566c45704fae.png)

but if I delete or comment codes of artifact removal with ICA and run again. it hasn't an error anymore. so I want to know why.

2. How to normalise EEG data by using MNE?
Is it has codes for normalise data? If it hasn't, Does it has other ways? 

Thank you for all answers.

**Comment by agramfort** [comment]
if you ICA clean your data you reduce their rank making covariance matrices
not full rank (they have some eigenvalues which are 0).
This is the error you see. What you could do is apply a PCA step before CSP
to reduce the dimension of the data so the covariances
become full rank.

>

**Comment by palm-audtachai** [comment]
> if you ICA clean your data you reduce their rank making covariance matrices not full rank (they have some eigenvalues which are 0). This is the error you see. What you could do is apply a PCA step before CSP to reduce the dimension of the data so the covariances become full rank.
> […](#)

How can I apply a PCA? & Which line that I need to apply PCA? Do they have example codes?
 this is my codes. 
![image](https://user-images.githubusercontent.com/57890260/99958840-a0371c80-2dbc-11eb-864d-03d960616f23.png)
![image](https://user-images.githubusercontent.com/57890260/99958871-ae853880-2dbc-11eb-9c7d-aefc58ac367a.png)

**Comment by agramfort** [comment]
see if you can insert in your Pipeline a PCA estimator

>

**Comment by palm-audtachai** [comment]
> see if you can insert in your Pipeline a PCA estimator
> […](#)

I try to apply PCA and it doesn't have error anymore.
![image](https://user-images.githubusercontent.com/57890260/100057167-813a9800-2e59-11eb-843e-310fd1f7b63f.png)

but output still reduce data rank from 22 to 19. Is this correct or not?
![image](https://user-images.githubusercontent.com/57890260/100057224-9b747600-2e59-11eb-8c58-79a6333023f5.png)

**Comment by agramfort** [comment]
yes ICA cleaning and PCA does reduce the rank of the data. It's expected.
