### ISSUE TITLE
TOPOs appear circular for MEG 

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#8563]
now in a number of plots we have MEG topos that appear circular instead of following the helmet shape.

See for example:

https://mne.tools/dev/_images/sphx_glr_plot_20_visualize_epochs_008.png

in

https://mne.tools/dev/auto_tutorials/epochs/plot_20_visualize_epochs.html#sphx-glr-auto-tutorials-epochs-plot-20-visualize-epochs-py

I don't know if it's a problem of defaults but I also see around me a lot of people showing me MEG topos with circular shapes and I feel it should not happen.

**Comment by larsoner** [comment]
@drammock do you want to look / add it to your queue somewhere?

**Comment by drammock** [comment]
sure; topos are coming soon on my list

**Comment by larsoner** [comment]
@drammock this one would be nice to fix for 0.22
