### ISSUE TITLE
Website doesn't allow you to view v0.20 docs

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-python#8565]
#### Describe the bug
When I try and view v0.20 docs on the website it takes me to 0.21

#### Steps to reproduce
Click the button on top right of MNE website

#### Expected results
See docs for v20

#### Actual results
See docs for v21

#### Additional information
Trying to view earlier docs such as v19 works

**Comment by larsoner** [comment]
Fixed by https://github.com/mne-tools/mne-tools.github.io/commit/e12a188be4543dfdcafa5284aff56ecfd002a242

https://mne.tools/0.20/
