### ISSUE TITLE
fNIR signal priors to EEG source reconstruction

### ISSUE THREAD

**Issue by LF9076** [mne-tools/mne-python#8571]
#### Describe the new feature or enhancement
*Please provide a clear and concise description of what you want to add or
change.*
what can i do if i want to use the fNIR signals to be a spatial priors in the source estimates functions? Actually i think it need to change the Source covariance matrix.The matrix is a Is an identity matrix in the L2 norm formula.

#### Describe your proposed implementation
*Describe how you think the feature or improvement should be implemented (e.g., 
as a new method on an existing class? as new capability added to an existing
method?) If you're not sure, please delete this section and the next section.*

#### Describe possible alternatives
*If you've suggested an implementation above, list here any alternative
implementations you can think of, and brief comments explaining why the chosen
implementation is better.*

#### Additional comments
*Add any other context or screenshots about the feature request here.*

**Comment by agramfort** [comment]
Please use the [MNE mailing list](http://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis) or the [gitter channel](https://gitter.im/mne-tools/mne-python) for usage questions.

**Comment by agramfort** [comment]
or at least provide a detailed description of the ENH you want

**Comment by LF9076** [comment]
The question is that i want to use the fNIR signal information to be a&nbsp;Spatial prior in EEG source reconstruction proceduce. some source reconstruction software can use fMRI information.Does MNE can do this?or in the future MNE can achieve it?Thanks a lot.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alexandre Gramfort"<notifications@github.com&gt;; 
发送时间: 2020年11月25日(星期三) 下午3:33
收件人: "mne-tools/mne-python"<mne-python@noreply.github.com&gt;; 
抄送: "Sunnia"<907625420@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mne-tools/mne-python] fNIR signal priors to EEG source reconstruction (#8571)





 
or at least provide a detailed description of the ENH you want
