### ISSUE TITLE
CSP.plot_filters() is actually plotting the transpose of filters

### ISSUE THREAD

**Issue by rubyyhj** [mne-tools/mne-python#8579]
#### Describe the bug
The `plot_filters()` method of `mne.decoding.CSP` is not plotting filters, but actually plotting the transpose of filters.
Using version `0.21.2`.

#### Steps to reproduce
Use the code from [Motor imagery decoding from EEG data using the Common Spatial Pattern (CSP)](https://mne.tools/stable/auto_examples/decoding/plot_decoding_csp_eeg.html?highlight=csp) and change the last line of the second code block `csp.plot_patterns` to `csp.plot_filters`, and the result is:

![Current plot_filters result](https://i.loli.net/2020/11/29/8jalSeG9WxDhrfo.png)

And in `mne.decoding.CSP`, the each row of `filters_` attribute is one CSP filter, see: https://github.com/mne-tools/mne-python/blob/maint/0.21/mne/decoding/csp.py#L184. But if we set the second row of `filters_` to be all zeros, the figure almost has no change:
```python
csp.filters_[1, :] = 0  # the coeffs in the second filter(row) are all 0 
csp.plot_filters(epochs.info, ch_type='eeg', units='Patterns (AU)', size=1.5)
```
![Not expected result](https://i.loli.net/2020/11/29/PEf6X8imKL37blv.png)

Instead, if we set the second column of `filters_` to be all zeros, then the "second filter" CSP1 becomes empty:
```python
csp.filters_[:, 1] = 0  # the second column of filters_
csp.plot_filters(epochs.info, ch_type='eeg', units='Patterns (AU)', size=1.5)
```
![empty](https://i.loli.net/2020/11/30/5KxoQnrIR6q7ubw.png)

So `plot_filters` is actually plotting the transpose of filters (the columns of `filters_`), not the csp filters (the rows of `filters_`).

#### To fix it
I think just change this line of code https://github.com/mne-tools/mne-python/blob/maint/0.21/mne/decoding/csp.py#L479 to 
`filters = EvokedArray(self.filters_.T, info, tmin=0)` could fix this issue. I tried the following code and the figure looks more reasonable to be CSP filters:
```
csp.filters_ = csp.filters_.T
csp.plot_filters(epochs.info, ch_type='eeg', units='Patterns (AU)', size=1.5)
```
![result](https://i.loli.net/2020/11/30/a3h1xUiJyQ4PGLE.png)

BTW, the figure from `plot_patterns` method is correct.

**Comment by cbrnr** [comment]
LGTM. Can you submit a PR?

**Comment by rubyyhj** [comment]
Submitted: #8580. @cbrnr
