### ISSUE TITLE
Issue when using reorder_channels

### ISSUE THREAD

**Issue by hvannieuwenh** [mne-tools/mne-python#8613]
I am plotting correlation matrices, and wanted to see the effect on the heatmap when I shuffle up the channel order, but raw.reorder_channels is not working. Below is my code:

```
import mne
import random

eeg_raw = mne.io.read_raw_eeglab('test.set')
channels = eeg_raw.ch_names
random.shuffle(channels)
eeg_raw_shuffled = eeg_raw.copy().reorder_channels(channels)
```

I get the following error pointing to the last line: 
"RuntimeError: info channel name inconsistency detected, please notify mne-python developers"

I have tried other variations of the last line: 
`eeg_raw = eeg_raw.reorder_channels(channels)` 
or
`eeg_raw.reorder_channels(channels)` 
but am getting the same error.

**Comment by hoechenberger** [comment]
The issue is that `random.shuffle()` modifies the input list in-place. So you're modifying `eeg_raw.ch_names`.

The solution is to replace
```python
channels = eeg_raw.ch_names
```
with
```python
channels = eeg_raw.ch_names.copy()
```
so you operate on a copy.

**Comment by hvannieuwenh** [comment]
Thank you!
