### ISSUE TITLE
Can MNE plot power on channel-vs-time axises for a certain frequency range?

### ISSUE THREAD

**Issue by xiaolongwu1987** [mne-tools/mne-python#8614]
Dear experts,
I can see MNE does a good job on plotting power for a certain channel(or sensor). But I think a power plot of a certain frequency range, like 70-80HZ, on a channel-vs-time axises should be equal informative.  But I can't find how, could you please help me out?

For example, examples in this page, https://mne.tools/stable/auto_examples/time_frequency/plot_time_frequency_simulated.html#sphx-glr-auto-examples-time-frequency-plot-time-frequency-simulated-py . The x-axis is time, y-axis is frequency and plotted for a certain channel. I want to plot against frequency from 78-80HZ,  the x-axis remains, y-axis is channels. 

How to do it?

**Comment by agramfort** [comment]
This appears to be a question about usage, not a bug report or a new feature request. Please use the [MNE mailing list](http://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis) or the [gitter channel](https://gitter.im/mne-tools/mne-python) for usage questions.
