### ISSUE TITLE
plot_sensor_connectivity

### ISSUE THREAD

**Issue by BarryLiu-97** [mne-tools/mne-python#8625]
When I ran plot_sensor_connectivity.py in cmd, the figure just appeared less than 1 sec, then it was gone.

**Comment by agramfort** [comment]
matplotlib figures are non blocking by default so it appears and closes.

you need to use block parameter in matplotlib

**Comment by GuillaumeFavelier** [comment]
Also, can you give more details on how you start the script? Because AFAIK, the 3d plots require an interactive python environment.

So `python -i ./examples/connectivity/plot_sensor_connectivity.py` or `run ./examples/connectivity/plot_sensor_connectivity.py` inside `ipython` works for me.

**Comment by BarryLiu-97** [comment]
> Also, can you give more details on how you start the script? Because AFAIK, the 3d plots require an interactive python environment.
> 
> So `python -i ./examples/connectivity/plot_sensor_connectivity.py` or `run ./examples/connectivity/plot_sensor_connectivity.py` inside `ipython` works for me.

just type 'python plot_sensor_connectivity.py'

**Comment by BarryLiu-97** [comment]
Ok, it works when I added -i

**Comment by BarryLiu-97** [comment]
What does the -i mean?

**Comment by BarryLiu-97** [comment]
And is there any way that we can see the channels' name in 3d?

**Comment by BarryLiu-97** [comment]
OK, it shows the chan name when I use mayavi

**Comment by GuillaumeFavelier** [comment]
From `python --help`:

```
-i     : inspect interactively after running script; forces a prompt even
         if stdin does not appear to be a terminal; also PYTHONINSPECT=x
```

It's normally enabled by default but there seems to be a regression for the `pyvista` 3d backend on the `master` branch. I'll fix it soon :)

**Comment by BarryLiu-97** [comment]
Can Miyavi make respond to the mouse click? Like only when I click on the electrode, the name shows up.

**Comment by GuillaumeFavelier** [comment]
This feature is not currently implemented.

**Comment by BarryLiu-97** [comment]
But could Miyavi support this? Recently I was trying to do a similar task but don't know how to start.

**Comment by GuillaumeFavelier** [comment]
You can try opening an issue on [mayavi](https://github.com/enthought/mayavi) to ask directly?

We are transitioning out from `mayavi` in favor of `pyvista` so I doubt such a feature will be added for the `mayavi` 3d backend.

**Comment by BarryLiu-97** [comment]
Thanks!

**Comment by larsoner** [comment]
I think this should be part of https://github.com/mne-tools/mne-python/issues/8382 -- once we add sensors to the Brain plot, they should be pickable and when you pick them their information + trace can show up in the `show_traces` area.
