### ISSUE TITLE
BUG: plot_psd_topomap

### ISSUE THREAD

**Issue by SuperX-666** [mne-tools/mne-python#8628]
#### Describe the bug
`epochs.plot_psd_topomap(
    bands=None,
    vmin=None,
    vmax=None,
    tmin=None,
    tmax=None,
    proj=False,
    bandwidth=None,
    adaptive=False,
    low_bias=True,
    normalization='length',
    ch_type=None,
    cmap=None,
    agg_fun=None,
    dB=True,
    n_jobs=1,
    normalize=False,
    cbar_fmt='auto',
    outlines='head',
    axes=None,
    show=True,
    sphere=None,
    vlim=(None, None),
    verbose=None,
)`

In the Docstring, it says:
```
dB : bool
    If ``True``, transform data to decibels (with ``10 * np.log10(data)``)
    following the application of ``agg_fun``. Ignored if ``normalize=True``.
```
the ignored dB it's likely a bug.

**Comment by mmagnuski** [comment]
Thanks for the bug report @YouyanLee,
could you be a little more specific in describing what you consider to be a bug?
Currently I am not  sure what you mean by "the ignored dB it's likely a bug."
