### ISSUE TITLE
still some circular topos for MEG data

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#8634]
see:

https://24010-1301584-gh.circle-artifacts.com/0/dev/auto_examples/visualization/plot_evoked_topomap.html#animating-the-topomap

https://24010-1301584-gh.circle-artifacts.com/0/dev/auto_examples/preprocessing/plot_run_ica.html#compute-ica-components-on-epochs

we should not use circular topos for MEG

**Comment by larsoner** [comment]
On it...
