### ISSUE TITLE
Tutorial figure is cropped

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#8640]
I have not checked if I'd get the same results running this locally, but in our rendered docs, I just came across one figure (but there's probably more than this one?) which appears to be cropped:

<img width="872" alt="Screen Shot 2020-12-10 at 10 25 36" src="https://user-images.githubusercontent.com/2046265/101752666-0cf72a00-3ad2-11eb-93cf-7859221c8859.png">

(Tutorial: https://mne.tools/dev/auto_tutorials/preprocessing/plot_50_artifact_correction_ssp.html#repairing-ecg-artifacts-with-ssp)

I think this is something we should aim to get fixed before the next release.

compulsory ping @drammock 😅😁

**Comment by hoechenberger** [comment]
Also we probably should ensure there's no line break in "PCA" 👌 Not sure if there's an easy way to do this though

**Comment by mmagnuski** [comment]
Oh, and the EEG head is huge compared to the MEG heads. :smile:

**Comment by hoechenberger** [comment]
> Oh, and the EEG head is huge compared to the MEG heads. 😄

![image](https://user-images.githubusercontent.com/2046265/101844065-dfe75d80-3b4b-11eb-9d0f-767c12a8d75f.png)

**Comment by larsoner** [comment]
I think we got this in #8651, but if not feel free to reopen

**Comment by mmagnuski** [comment]
@larsoner I think this PR fixed the head size inconsistency between MEG and EEG, but not the title being cropped.

**Comment by larsoner** [comment]
Ahh okay, I'll reopen. Setting the milestone to 0.23 because I don't think it's a blocker for release
