### ISSUE TITLE
BUG: stc plot color limits

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#8642]
@larsoner 000dac95c0f7a4439ee60fb92f1007fd288f9611 introduced a color limit bug in the stc plot

```python
import numpy as np
from pathlib import Path
from mayavi import mlab
import matplotlib.pyplot as plt

import mne

data_path = Path(mne.datasets.sample.data_path())
fname = data_path / 'MEG' / 'sample' / 'sample_audvis-meg'

# Read stc from file
stc = mne.read_source_estimate(fname, subject='sample')
stc.data[:, :] = np.random.rand(*stc.data.shape) # some positive data


fig_size = (300, 300)
fig = mlab.figure(size=fig_size)

brain = stc.plot(
    hemi='lh',
    views='lat',
    colormap='coolwarm',
    subjects_dir=data_path / 'subjects',
    clim=dict(kind='value', pos_lims=[0, .2, .5]),  # <-------------------- this what breaks
    backend='mayavi',
    figure=fig,
)

img = mlab.screenshot(figure=fig, mode='rgba', antialiased=True)
plt.imshow(img)
```

before:
![image](https://user-images.githubusercontent.com/4881164/101778595-5a848e80-3af4-11eb-84d6-dcbc7de8ed75.png)

after:
![image](https://user-images.githubusercontent.com/4881164/101778610-5fe1d900-3af4-11eb-9ee7-9d6ce46600e2.png)

**Comment by kingjr** [comment]
cc @GuillaumeFavelier who probably know intimately the intricate 3d plotting functions

**Comment by larsoner** [comment]
I can replicate on latest `master`, @GuillaumeFavelier I can make a quick PR for this since I just dumped https://github.com/mne-tools/mne-python/pull/8335#issuecomment-742531087 on you :)

**Comment by NeuroLaunch** [comment]
Nice catch, as I was just encountering this bug.
