### ISSUE TITLE
RFC, MAINT: use pooch for download management?

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#8674]
#### Describe the new feature or enhancement

Scikit-image recently switched to using [pooch](https://pypi.org/project/pooch/) for dataset download management. Let's see if it works well enough that we could eliminate our dataset downloading code.  WDYT?

**Comment by larsoner** [comment]
+1 for me. See also some discussion in https://github.com/sphinx-gallery/sample-project/issues/3

**Comment by adam2392** [comment]
FYI this is now closed by #9742
