### ISSUE TITLE
ENH: integration with NEO

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#870]
(Not for 0.7)

The NEO project does lots of IO and time series processing 

https://github.com/NeuralEnsemble/python-neo

We should explore with the NEO authors how we could work together / make the packages more interoperable if they aren't already / explore where combining functionality might yield interesting perspectives / etc.

cc @samuelgarcia

**Comment by Eric89GXL** [comment]
I think we have decent integration via the `*Array` classes, feel free to reopen if people have further needs
