### ISSUE TITLE
Enable weights to be applied correctly on RMS values for contrast plotting using plot_topomap.

### ISSUE THREAD

**Issue by AaronAngJW** [mne-tools/mne-python#8701]
#### Describe the new feature or enhancement

Currently, merging of gradiometers (pair) reading results in absolute RMS value. When two conditions are combined to form a contrast plot, the contrasts can only be plotted in positive values despite applying opposite weights to the conditions. It will be nice to have the RMS values rectified so contrast plots using 'grad' type sensors will be more meaningful.

![contrast issue](https://user-images.githubusercontent.com/16894133/103768773-125a7c80-505e-11eb-8de5-d3b624683012.png)
In the above figure, the centre plot is formed using:

contrast = mne.combine_evoked([condition_vol6, condition_blank5], [1.0, -1.0])
contrast.plot_topomap(ch_type='grad')

.. whereas the top and bottom plots are the evoked data of the individual conditions. Note that the centre plot seemed to be showing the combined strength of both the conditions rather than the contrast (which should be shown in negative to positive values corresponding to the weights).

#### Describe your proposed implementation
Enable weights to be applied correctly on 'grad' type comparison plots.

**Comment by agramfort** [comment]
what plot_topomap function are you taking about? the one in
evoked.plot_topomap does merge automatically.

please be more descriptive

>

**Comment by AaronAngJW** [comment]
Hi Alex, apologies as I got mixed up with the technicality regarding how RMS works. Therefore, I am amending the initial issue drastically to address what I can ideally get. Please do refer to the edited text in the first post above.

**Comment by dengemann** [comment]
This looks like a good idea. It could be nice to pull out the computation in plot_topomap to facilitate custom processing (I agree, currently "Ninja mode" is required for that).

**Comment by agramfort** [comment]
here is a ugly (yet working hack)

```
import os
import numpy as np
import mne

data_path = mne.datasets.sample.data_path()
sample_data_raw_file = os.path.join(data_path, 'MEG', 'sample',
                                    'sample_audvis_filt-0-40_raw.fif')
raw = mne.io.read_raw_fif(sample_data_raw_file)

event_dict = {'auditory/left': 1, 'auditory/right': 2, 'visual/left': 3,
              'visual/right': 4, 'smiley': 5, 'buttonpress': 32}

events = mne.find_events(raw, stim_channel='STI 014')

epochs = mne.Epochs(raw, events, event_id=event_dict, tmin=-0.2, tmax=0.3)

evoked1 = epochs['auditory/left'].average().pick('grad')
evoked2 = epochs['auditory/right'].average().pick('grad')


def hack_evoked(evoked):
    data = evoked.data
    data = data.reshape((len(data) // 2, 2, -1))
    data = np.sqrt(np.mean(data ** 2, axis=1))
    evoked = evoked.copy().pick(np.arange(0, 2*len(data), 2))
    evoked.data = data
    return evoked


evoked1 = hack_evoked(evoked1)
evoked2 = hack_evoked(evoked2)

contrast = mne.combine_evoked([evoked1, evoked2], [1.0, -1.0])

# Drop bad channel

contrast.drop_channels(['MEG 2442'])

contrast.plot()
times = np.linspace(0, 0.2, 10)
contrast.plot_topomap(times=times, ch_type='planar1')
```

**Comment by AaronAngJW** [comment]
Works like a charm on the sample audio data. On my side though, it collapses when I have only 203 gradiometer measurements in the data. I got a ValueError, which I am guessing, is the result of that? On the sample audio data, `data.shape = (204, 76)`. 

I assume 204 is the number of grads. When it is an odd number, `data.reshape((len(data) // 2, 2, -1))` fails.

**Comment by agramfort** [comment]
yes you need to be smarter by dropping the pair of grads

>

**Comment by AaronAngJW** [comment]
Thanks Alex! This was helpful.

**Comment by AaronAngJW** [comment]
Hi again,

Sorry to keep this going but I just spotted something unusual.

![sample_merge](https://user-images.githubusercontent.com/16894133/105140390-961e6980-5b32-11eb-82d7-2b27b5b0ff64.png)

The final contrast plot seems to be oscillating between the weights as shown. How do I go about remedying this?

**Comment by agramfort** [comment]
sorry I don't get your concern. Maybe I don't see what you want me to see

>

**Comment by AaronAngJW** [comment]
So for the top left arrows, the -0.100s and 0.000s contrast (middle plots) are likely to be driven by condition sponblinks/3 (eye blink) activity. But this is reflected as blue at -0.100s and red at 0.000s, when it is supposed to be red at both times.

**Comment by agramfort** [comment]
@AaronAngJW you should compute the hack_evoked at the very end. For example interpolation of hack evoked will do terrible things. MEG interpolation is not like splines for EEG it's using the channels orientations for example.

**Comment by AaronAngJW** [comment]
Oh great, that resolved the issue. Thanks Alex!

**Comment by drammock** [comment]
closing: seems to be resolved, and > 1 year of inactivity.
