### ISSUE TITLE
Trouble with ICA, find_bads_eog

### ISSUE THREAD

**Issue by moonj94** [mne-tools/mne-python#8703]
I am trying to create a preprocessing pipeline in python as opposed to matlab. And I need a bit of help.
When I run ICA, and then run find_bads_eog, and finally do `ICA.apply()`, I get the following figure:

![Screen Shot 2021-01-06 at 2 49 42 PM](https://user-images.githubusercontent.com/53019885/103818782-c2b08c80-502e-11eb-9444-c8ba9e8525a6.png)

As you can see for some reason many of the channels' values are significantly diminished. 

Here is the code:
the object `epochs_clean_ar` is a result of epoching, resampling, filtering, and using `AutoReject`. And the eog channels were previously set to Fp1 and Fp2 when loading files.

 ```
randomstate=101
 reject = dict(mag=5e-12, grad=4000e-13)
        ica=ICA(n_components=62,method='fastica',random_state=randomstate).fit(epochs_clean_ar,picks=picks_eeg)#,reject=reject)
 ica.plot_components()


        eog_inds,scores=ica.find_bads_eog(inst=epochs_clean_ar,threshold=3.0,reject_by_annotation=False)
        ica.exclude=eog_inds
        ica.plot_scores(scores,exclude=eog_inds)

        ica.plot_properties(epochs_clean_ar, picks=eog_inds)   

        copy=epochs_clean_ar.copy();
        epochs_ica=ica.apply(copy,start=0,stop=1)
        x=epochs_clean_ar.get_data()
        y=epochs_ica.get_data();
        t=np.arange(x.shape[2])
        
        plt.plot(t,x[1,2,:],t,y[1,2,:])
````

I also want to say that the ICA components are very one sided (left hemisphere) and look very similar. I am new to using python preprocessing tools so verbose explanations would be appreciated.

**Comment by agramfort** [comment]
please use https://mne.discourse.group/ for usage questions.
