### ISSUE TITLE
ENH: Notebook 3d backend improvements (ipyvtklink)

### ISSUE THREAD

**Issue by GuillaumeFavelier** [mne-tools/mne-python#8704]
I open this issue following https://github.com/mne-tools/mne-python/pull/8503#issuecomment-748859979 to keep track of the missing features or anything that could be improved.

**Feature status**

- [ ] Test integration with Google Colab following https://github.com/mne-tools/mne-python/issues/8080#issuecomment-911720213
- [ ] HiDPI rendering of 3D and mpl widget (see https://github.com/mne-tools/mne-python/pull/8708#discussion_r561283667)
- [ ] Screenshot w/time_viewer is off in the vertical direction (https://github.com/mne-tools/mne-python/pull/8708/files/5d34669c5ea051b1c08dfda19cb1ddf0ba727945#diff-a6e2fc2fab82c1377cb29516fc0a7aed813ee4273daad18cf002e7302a331770)
- [x] Update to `ipyvtklink` (https://github.com/Kitware/ipyvtklink/pull/30, https://github.com/mne-tools/mne-python/pull/9341)
- [x] Button/shortcut for autoplay (https://github.com/mne-tools/mne-python/pull/8741)
- [x] Button/shortcut to take a screenshot (https://github.com/mne-tools/mne-python/pull/8708)
- [x] Button/shortcut to save a movie (https://github.com/mne-tools/mne-python/pull/9190)
- [x] Button/shortcut to display help (https://github.com/mne-tools/mne-python/pull/9123)
- [x] Label time course mode (https://github.com/mne-tools/mne-python/pull/9016)

**Design/UX**

- [ ] big square button (asked in https://github.com/mne-tools/mne-python/pull/8503#issuecomment-749411804)

---

**Known issues**

<details>
<summary><b>Resolved</b></summary>

- [x] [Does not play well with Firefox](https://github.com/mne-tools/mne-python/pull/8503#issuecomment-750940795) (see https://github.com/mne-tools/mne-python/issues/8704#issuecomment-819447117 and https://github.com/mne-tools/mne-python/issues/8704#issuecomment-819458470)

</details>

**JupyterLab**
* matplotlib is not interactive `Javascript Error: IPython is not defined`
* The mesh is translucent 
* A VTK window opens on local instance

**Google Colab**
* It is not supported yet (asked in https://github.com/mne-tools/mne-python/pull/8503#issuecomment-751272941, standby in https://github.com/mne-tools/mne-python/issues/8704#issuecomment-756120645)

---

A testing notebook is available on [gist.github.com](https://gist.github.com/GuillaumeFavelier/b470330fa71cfdef4c7be94b966ef49b).

**Comment by GuillaumeFavelier** [comment]
About Google Colab, I made some research @agramfort.

Considering that [`ipyvtk_simple`](https://github.com/Kitware/ipyvtk-simple)'s main viewer class, [`ViewInteractiveWidget`](https://github.com/Kitware/ipyvtk-simple/blob/master/ipyvtk_simple/viewer.py#L30), is based on [`ipycanvas`](https://github.com/martinRenou/ipycanvas)'s [`Canvas`](https://github.com/martinRenou/ipycanvas/blob/master/ipycanvas/canvas.py#L245) widget, I found that [it is a known issue](https://github.com/martinRenou/ipycanvas/issues/170). The short answer is (and I quote [Martin Renou](https://github.com/martinRenou/ipycanvas/issues/170#issuecomment-755171874)):

> Custom widgets libraries are not supported by Google colab yet

We could track the progress on this matter on https://github.com/martinRenou/ipycanvas/issues/170 or more directly in https://github.com/googlecolab/colabtools/issues/498.

Anyway, I think those need to be resolved before more can be expected from `ipyvtk_simple` and finally `mne-python`.

**Comment by GuillaumeFavelier** [comment]
Exactly what I was looking for, thank you @larsoner :+1:

**Comment by GuillaumeFavelier** [comment]
The mouse events on Firefox might be fixed by https://github.com/Kitware/ipyvtklink/pull/25. I'll open a PR and give it a try.

**Comment by GuillaumeFavelier** [comment]
It might not be necessary, I don't have those issues anymore on Firefox 87.0

**Comment by GuillaumeFavelier** [comment]
For `Jupyter Lab` integration it might worth trying again once https://github.com/pyvista/pyvista/issues/1116 is fixed.

**Comment by GuillaumeFavelier** [comment]
Quick update: `ipycanvas` now works on Google Colab. It's a big milestone for the `notebook` 3d backend.

https://github.com/martinRenou/ipycanvas/issues/170#issuecomment-1062071346

I'll check `ipyvtklink` and report back in here.

**Comment by agramfort** [comment]
this would be a game changer !

**Comment by GuillaumeFavelier** [comment]
Although now `ipycanvas` is supported on Google Colab, `vtk`, even on notebook, still requires a running X server.

My testing workflow is: `ipycanvas` :heavy_check_mark: -> `ipyvtklink` :heavy_check_mark: -> `pyvista (ipyvtklink)` -> `mne (notebook)`

It's a work in progress but I managed get it working at low resolution, which is already amazing IMO.
Here is a modified version of [`ipyvtklink`'s default example](https://github.com/Kitware/ipyvtklink#python-vtk):

https://user-images.githubusercontent.com/18143289/157433174-fa8e5a99-83b6-46c6-89b3-aa1f116d92db.mp4

---

The important points:
1) setting the custom widget manager

```
from google.colab import output
output.enable_custom_widget_manager()
```

2) setting up `xvfb`

```
!sudo apt update
!sudo apt-get install libgl1-mesa-dev xvfb
!sudo apt install -yqq libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 libopengl0
```

3) start `xvfb` with the correct `DISPLAY` variable at the beginning of the cell

```
!/sbin/start-stop-daemon --start --quiet --background --exec /usr/bin/Xvfb -- :99 -screen 0 800x600x24 -ac +extension GLX +render -noreset

import os
os.environ['DISPLAY'] = ':99'
```

**Comment by larsoner** [comment]
I think we can close this now that the notebook seems to be working correctly (even nowadays with `trame`)
