### ISSUE TITLE
mne make_scalp_surfaces throws unexpected error

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-python#8715]
When you run [mne make_scalp_surfaces](https://github.com/mne-tools/mne-python/blob/master/mne/commands/mne_make_scalp_surfaces.py#L134) with `--overwrite` parameter, it throws an unexpected error if the BEM directory already exists.

The reason is that the `overwrite` parameter is not passed here:

https://github.com/mne-tools/mne-python/blob/01b8b364698f86630d22fad573058233ab6a58a5/mne/commands/mne_make_scalp_surfaces.py#L134

**Comment by agramfort** [comment]
it seems the right fix.

can you open the PR for this @jasmainak? thanks a lot

>

**Comment by jasmainak** [comment]
closed by #8800
