### ISSUE TITLE
Directionality in spectral connectivity 

### ISSUE THREAD

**Issue by BarryLiu97** [mne-tools/mne-python#8732]
Recently, I was trying different spectral connectivity methods, and I didn't find any directional method in MNE, such as cross-correlation(time domain), Granger causality, and phase slope index. And as I know, the Phase lag index has two versions: directional and functional. I have two questions:
1. Does mne have any plan to add these functions?
2. How do we visualize the directional methods?

**Comment by agramfort** [comment]
see https://mne.discourse.group/t/causal-spectral-connectivity-measures-per-8691/2434/1
