### ISSUE TITLE
IndexError: list index out of range    in   mne.io.read_epochs_eeglab

### ISSUE THREAD

**Issue by BarryLiu97** [mne-tools/mne-python#8766]
Here is my coe:
```
import mne
fpath = 'fear.set'
epoch = mne.io.read_epochs_eeglab(fpath)
```
Then an error occurred:
```
  File "<input>", line 1, in <module>
  File "D:\SEEG_Cognition\SEEG\lib\site-packages\mne\io\eeglab\eeglab.py", line 279, in read_epochs_eeglab
    uint16_codec=uint16_codec)
  File "<decorator-gen-223>", line 24, in __init__
  File "D:\SEEG_Cognition\SEEG\lib\site-packages\mne\io\eeglab\eeglab.py", line 471, in __init__
    event_latencies.append(events[ev_idx].latency)
IndexError: list index out of range
```
Here is my data https://drive.google.com/file/d/1F7NczB4gjqdcX-1wf705Dm7Z8BXYmdV0/view?usp=sharing

**Comment by guoyongjian111** [comment]
How did you solve it? I met the same problem，thanks

**Comment by BarryLiu97** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    My problem comes from wrong operation in eeglab
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                3273376560
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 11/24/2021 ***@***.***> wrote： 




How did you solve it? I met the same problem，thanks



—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
