### ISSUE TITLE
Codecov coverage

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#8776]
I noticed that Codecov frequently reports very low coverage (e.g. #8760 currently shows Codecov jobs in red). Often, when I push additional (minor) changes, coverage suddenly increases although almost nothing changed. Therefore, I normally ignore Codecov reports, but this is of course not the idea of this action. Is there anything we can do to make Codecov more reliable? Or am I doing something wrong?

**Comment by agramfort** [comment]
same feeling here. I tend to ignore often...

>

**Comment by hoechenberger** [comment]
cc @olafhauk
