### ISSUE TITLE
MNE Gallery

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#8785]
This morning after my presentation on latest MNE developments it was suggested to create some sort of gallery of cool-looking, interest-provoking plots that were generated with MNE. I think this is a great idea, and maybe not too much work either: we could just hand-select the most amazing figures from the tutorials and examples. WDYT?

**Comment by larsoner** [comment]
This is more or less what the front-page carousel is meant to do, draw people in with some pretty plots that people might typically want to make.

This is probably not what you mean in some way, can you elaborate on where your proposal differs and where you see it fitting in the narrative tutorials/docs so @drammock can comment?
