### ISSUE TITLE
MNE website down?

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#8786]
I hope this isn't related to our recent renaming of master -> main, but our website at https://mne.tools is currently down. Any ideas? @hoechenberger @drammock

**Comment by hoechenberger** [comment]
Have you tried reloading? I witnessed it only showing content upon the second losing attempt. Thought this was an issue got me locally only

**Comment by hoechenberger** [comment]
Oh it's a 404. Boni did not have this until a few hours ago (last time I checked)

**Comment by cbrnr** [comment]
😱 at least we didn't break it, but still... 😥

**Comment by hoechenberger** [comment]
> 😱 at least we didn't break it, but still... 😥 

Or maybe we did and there's some kind of hysteresis due to caching somewhere 😅🤯

**Comment by larsoner** [comment]
I had to rename `master` to `main` for the `mne-tools.github.io` repo, and this broke things temporarily probably due to some GitHub bug. Pushing an empty commit after the last `deploy` step seems to have fixed it.

**Comment by hoechenberger** [comment]
Thanks for the swift action, @larsoner!!
