### ISSUE TITLE
How can I get source spaces data from curry('.cdt.dpa') or cnt('.cnt.dpa')?

### ISSUE THREAD

**Issue by YeZiyi1998** [mne-tools/mne-python#8788]
If your issue is a usage question, you should ask for help on the
[MNE Forum](https://mne.discourse.group).

Our GitHub issue tracker is only used to report bugs and suggest improvements
to MNE-Python. For any other questions, please use the forum.

**Comment by agramfort** [comment]
@YeZiyi1998 please read what is written just above.
