### ISSUE TITLE
Confusion around "resp" channel type

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#8853]
In `channels.py`, it is claimed that the `resp` channel type is for certain response triggers:

https://github.com/mne-tools/mne-python/blob/19fb479de44865d5ce79ad5af539a06081fae0c5/mne/channels/channels.py#L704-L706

This seems to be supported by code treating BTi data:
https://github.com/mne-tools/mne-python/blob/19fb479de44865d5ce79ad5af539a06081fae0c5/mne/io/bti/bti.py#L1188-L1189

But the following comment in `constants.py` suggests it's a resp-iratory, not a resp-onse channel:
https://github.com/mne-tools/mne-python/blob/19fb479de44865d5ce79ad5af539a06081fae0c5/mne/io/constants.py#L177

Now … what gives?

x-ref https://github.com/mne-tools/mne-bids/issues/700

cc @agramfort

**Comment by larsoner** [comment]
The authority should be fiff-constants

https://github.com/mne-tools/fiff-constants/blob/master/DictionaryTypes.txt#L257

**Comment by hoechenberger** [comment]
So… it's our BTi code that needs fixing, not the comment in `constants.py`?

**Comment by larsoner** [comment]
Yes I think so

**Comment by sappelhoff** [comment]
awesome, thanks for digging this out @hoechenberger ... this is good for MNE-BIDS :)
