### ISSUE TITLE
mne.read_selection() returning funny channels

### ISSUE THREAD

**Issue by dnacombo** [mne-tools/mne-python#8865]
#### Describe the bug

trying to select channels from an EEG dataset.

#### Steps to reproduce

```
l = ['Vertex', 'temporal', 'parietal', 'occipital', 'frontal']

ll = mne.read_selection(name=l, info=r.info)
```
returns a list with **Neuromag** channels although there are only EEG channels (EGI) in the dataset.

@hoechenberger

**Comment by hoechenberger** [comment]
`mne.read_selection()` shouldn't return channels that don't appear in `info`, so I'd consider this a bug

**Comment by larsoner** [comment]
IIRC `read_selection` is only meant to be used with Neuromag MEG channels. We should probably also update the docstring to say this in addition to raising an error

**Comment by cbrnr** [comment]
👍 - I've never heard of that function, and after reading its docs I couldn't figure out what exactly it should be used for.

**Comment by agramfort** [comment]
I was written in a time where MNE could only process neuromag data....

>

**Comment by drammock** [comment]
Maybe worth a deprecation and a name change to `read_neuromag_selection`?

**Comment by cbrnr** [comment]
👍 for deprecating and renaming, and maybe also moving to the `channels` module?

**Comment by hoechenberger** [comment]
I will look into this.
