### ISSUE TITLE
Inaccurate iEEG electrode positions on 3d/2d plots

### ISSUE THREAD

**Issue by Immiora** [mne-tools/mne-python#8868]
Originally posted here: https://mne.discourse.group/t/ieeg-electrode-positions-on-3d-2d-plots/2687

The electrode positions I am getting from the mayavi plot look inaccurate.

The issue is well visible in the tutorial as well: [Working with ECoG data](https://mne.tools/dev/auto_tutorials/misc/plot_ecog.html#sphx-glr-auto-tutorials-misc-plot-ecog-py):
![Example1](https://aws1.discourse-cdn.com/free1/uploads/mne/original/1X/ce01e0041af17be9ddfd51a6711e36faf532879c.png)

The electrodes plotted with `scatter` (colored blobs) are off compared to the ones made with `plot_alignment` (white spheres underneath). Reducing the radius of the scatter plot reveals how inaccurate it is:

![Example2](https://aws1.discourse-cdn.com/free1/uploads/mne/original/1X/17ab5e455b0fe5c66e058f19d7665bc7d936fcd9.png)

I understand that these positions depend on the view, but both plots are made using the same viewpoint:

```
fig = plot_alignment(raw_car.info, subject=subject, subjects_dir=subjects_dir, surfaces=['pial'], coord_frame='mri')
mne.viz.set_3d_view(fig, 200, 70)
xy, im = snapshot_brain_montage(fig, montage)
xy_pts = np.vstack([xy[ch] for ch in raw_car.info['ch_names']])

fig, ax = plt.subplots(figsize=(5, 5))
ax.imshow(im)
ax.set_axis_off()
sc = ax.scatter(*xy_pts.T, c=ts, vmin=10, vmax=100)
```

**Comment by Immiora** [comment]
Any chance someone is looking at this yet?

**Comment by larsoner** [comment]
Can you try #8983?
