### ISSUE TITLE
CI: pyvista QT error on Azure

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#8873]
#### Describe the bug
`test_layered_mesh()` is failing on CI (azure py 3.8 pip pre):
```
TypeError: Expected type for ``window_size`` is (<class 'tuple'>, <class 'NoneType'>) but <class 'list'> was given.
```
https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=11625&view=logs&j=a017e066-62ca-5289-ad0b-8f57c84a089f&t=de70cabd-1dad-599c-0751-4f1f50c17e0f&l=2959

cc @GuillaumeFavelier

**Comment by GuillaumeFavelier** [comment]
It's fixed in https://github.com/mne-tools/mne-python/commit/bac0bf536c2c65bc00bc2dc9ddbbf113308bf992 but I will port the fix since the PR won't be merged soon.
