### ISSUE TITLE
epochs.plot_image(evoked=False) doesn't show time in seconds

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#8887]
`epochs.plot_image(evoked=False)` doesn't show time in seconds on the x-axis but samples. If `evoked=True` (default), the x-axis of the evoked response is used, which is in seconds.

**Comment by cbrnr** [comment]
Apparently, the x-axis shows time in milliseconds (and not samples).

**Comment by agramfort** [comment]
it's consistent with evoked.plot then no?

**Comment by cbrnr** [comment]
The x-axis scaling depends on the `evoked` argument though. If `evoked=True`, it is in seconds, but if `evoked=False` it is in milliseconds. I think it is more important to be consistent within this function than to another function.

**Comment by agramfort** [comment]
ok fair enough. Seems like a good task for the sprint

>

**Comment by matteoanelli** [comment]
I can do it!
