### ISSUE TITLE
Clicking in overview bar does not draw annotations in raw.plot

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#8893]
If plotting a `Raw` object with annotations, these are not drawn in the main window when navigating through the data by clicking on the little overview bar. It's probably just an `update()` call that's missing. For a MWE, the example in from #8686 can be used. @drammock do you have time to look?

**Comment by drammock** [comment]
Yes, I'll look. I actually noticed this myself late on Friday so it was already on my to-do list for today 🙂
