### ISSUE TITLE
use bibtex in spectral.py

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#8914]
convert references in `mne/connectivity/spectral.py` to use footcite / footbibliography

**Comment by apoorva6262** [comment]
I'll take this one !

**Comment by cmista** [comment]
I'll work on this

**Comment by NeuroLaunch** [comment]
@cmista and I are backing off of this, as @apoorva6262 claimed it first.  Good luck!

**Comment by drammock** [comment]
this was addressed in #9153
