### ISSUE TITLE
Add "copy" button to code blocks

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#8957]
Code blocks, at least in the tutorials, should come with a "copy" button, allowing users to conveniently copy code snippets to the clipboard.

Not sure if this is something that needs to be addressed upstream?

**Comment by sappelhoff** [comment]
I recently added sphinx-copybutton to mne-bids and several other repos, and it does the job very well: https://github.com/executablebooks/sphinx-copybutton

**Comment by ramkpari** [comment]
Hey, I'm working on this!
