### ISSUE TITLE
Justify content of center column

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#8958]
When reading through longer tutorials, sometimes the left-aligned text in the center column makes for a rather unpleasant visual appearance:
<img width="776" alt="Screen Shot 2021-02-25 at 09 41 14" src="https://user-images.githubusercontent.com/2046265/109126509-9c18f300-774d-11eb-86de-e0295ed7396a.png">

By adding Bootstrap's `text-justify` class to the respective container, one can enable justified alignment; however it's still lacking proper hyphenation:

<img width="776" alt="Screen Shot 2021-02-25 at 09 44 28" src="https://user-images.githubusercontent.com/2046265/109126871-0fbb0000-774e-11eb-9f12-e76ecdf583fc.png">

Adding the following CSS enables hyphenation across different browsers:

```css
  word-break: break-word;  /* Chrome */
  -webkit-hyphens: auto;
  -moz-hyphens: auto;
  -ms-hyphens: auto;
  -o-hyphens: auto;
  hyphens: auto;
```

<img width="776" alt="Screen Shot 2021-02-25 at 09 49 24" src="https://user-images.githubusercontent.com/2046265/109127470-c0c19a80-774e-11eb-9a07-83511243984b.png">

One would need to ensure that this is not applied to `DataFrame` renderings and headlines.

Again, I'm not sure whether such a change should be made here or upstream?

**Comment by drammock** [comment]
-1 for this change. Although justification looks nice to some people, studies show that it actually slows down reading.

**Comment by hoechenberger** [comment]
@drammock is right: It appears that for LTR languages, left alignment is to be preferred, as it provided better accessibility. 

https://webaim.org/techniques/textlayout/
