### ISSUE TITLE
Add example for make_fixed_length_epochs()

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#8968]
Currently, there is neither a tiny example in the docstring, nor is there a working example in our examples or tutorials galleries for [`mne.make_fixed_length_epochs()`](https://mne.tools/dev/generated/mne.make_fixed_length_epochs.html). It would be nice to add one.

**Comment by vpeterson** [comment]
I would like to take this one too

**Comment by nordme** [comment]
I will work on this tutorial.

**Comment by drammock** [comment]
closed by #9156
