### ISSUE TITLE
Add HED to glossary

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#8974]
In MNE, we can describe events using hierarchical event descriptors (HED), such as `stim/a`, `stim/b` etc. They should be mentioned in the glossary and potentially a reference to the original publication should be added to an Epochs/events tutorial

Publication:
http://sccn.ucsd.edu/~nima/downloads/HED_globalsip_paper.pdf

**Comment by sappelhoff** [comment]
:+1: 

There is also a more recent paper: https://osf.io/5fg73/

the initial paper talks about "first generation HED", but the standard is planning to release the third generation in 2021.

**Comment by hoechenberger** [comment]
Yes but I don't think we currently support anything beyond HED "1.0", do we?

**Comment by sappelhoff** [comment]
> Yes but I don't think we currently support anything beyond HED "1.0", do we?

I am not sure that MNE supports HED 1.0 fully :thinking: it looks to me more like some (more or less coincidental) overlap between features, but I may be wrong.

**Comment by anaradanovic** [comment]
I can work on this one! :)

**Comment by hoechenberger** [comment]
@anaradanovic This sounds great!

**Comment by anaradanovic** [comment]
Would you like me to include examples in the description?

**Comment by hoechenberger** [comment]
@anaradanovic Yes why not!
