### ISSUE TITLE
Add add_reference_channels() method to Raw, Epochs, and Evoked

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#8979]
Currently there's `mne.add_reference_channels()`, which takes an instance of `Raw`, `Epochs`, or `Evoked`, and adds reference channels.

It would be great to have this functionality exposed as a **method** too, i.e., `Raw.add_reference_channels()`, `Epochs.add_reference_channels()`, and `Evoked.add_reference_channels()`, just as is the case e.g. with `set_eeg_reference()`

The respective `Raw`/`Epochs`/`Evoked` instance should be modified in-place, and the modified instance should be returned to allow for method chaining.

This would need to be added to `UpdateChannelsMixin` in `mne/channels/channels.py`

Overlapping parts of the method and  `mne.add_reference_channels()` docstrings should be added to the `docdict` to avoid duplication.

**Comment by agramfort** [comment]
no objection

>

**Comment by Falach** [comment]
I'll take this one :)
