### ISSUE TITLE
Set ICA's max_iter to a higher default

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#8982]
Currently, `ICA.max_iter` is set to 200 by default. This is one of the few MNE defaults I **always** change when working with data from our lab, and I've seen quite a few support requests indicating that ICA didn't converge within those 200 iterations too, the most recent one here: https://mne.discourse.group/t/cannot-find-ecg-artifacts-during-ica/2778/11?u=richard

I'd like to suggest to increase the `max_iter` default to 1000 to ensure that non-convergence will really be a rather rare exception for most users. I don't think there's many valid use cases for working with non-converged ICA decompositions anyway, or are there? Every time I've encountered the warning about non-converged ICA, the decomposition looked … flaky.

WDYT?

cc @cbrnr

**Comment by agramfort** [comment]
how is it done in other software packages?

>

**Comment by hoechenberger** [comment]
> how is it done in other software packages?

EEGLAB uses

[500 for picard](https://github.com/sccn/eeglab/blob/96f5b56adec802ea3fc296085f17d3f21c204942/functions/popfunc/pop_runica.m#L167)
[1000 for pearson ICA](https://github.com/sccn/eeglab/blob/96f5b56adec802ea3fc296085f17d3f21c204942/functions/popfunc/pop_runica.m#L487)

For Infomax, AMICA and FastICA I couldn't find any defaults set in the EEGLAB sources – they're probably relying on the respective defaults of the binaries they're calling..?

**Comment by agramfort** [comment]
let's try to stick to the same defautls

>

**Comment by hoechenberger** [comment]
Ok it seems to be
[1000 for FastICA](https://github.com/davidkun/FastICA/blob/df9dbda6a50161285afd6933b04241f974c6e377/fastica.m#L94-L95)
[2000 for AMICA](https://github.com/japalmer29/amica/blob/008abb83a98ed34c0c57785804ee34ec52a59c4b/pop_runamica.m#L10)

Infomax I still couldn't find.

**Comment by hoechenberger** [comment]
[512 for (extended) Infomax](https://github.com/sccn/eeglab/blob/96f5b56adec802ea3fc296085f17d3f21c204942/functions/sigprocfunc/binica.m#L29)

**Comment by hoechenberger** [comment]
--> My proosal:

- Change the signature of `ICA(..., max_iter=200)` to `... max_iter=None`
- fill in the default based on the used algorithm:
    - Infomax & picard -> 500
    - fastica -> 1000

Would also be suitable as a task for the sprint if we agree this is a change we'd like to have.

**Comment by agramfort** [comment]
ok for a sprint issue

>

**Comment by kimcoco** [comment]
I will take this one, and then move on to other ICA issues w/ Tutorial, Example

**Comment by hoechenberger** [comment]
Perfect!
