### ISSUE TITLE
User confused by using code snippets from TFR tutorial

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#8990]
See https://mne.discourse.group/t/tfr-morlet-temporal-resolution/2785

The user simply copied the code block with `decim=3` and was surprised the data got decimated. I think the tutorial should be more explicit about this, WDYT?

**Comment by drammock** [comment]
yes, in general we should always call out anything we do in the tutorials (for sake of build efficiency) that you wouldn't normally do locally.

**Comment by ramkpari** [comment]
Working on this!
