### ISSUE TITLE
RuntimeWarning: Channel locations not available. Disabling spatial colors.

### ISSUE THREAD

**Issue by ws17863276480** [mne-tools/mne-python#8992]
/home/wyw/ws/location/venv/demo.py:13: RuntimeWarning: Channel locations not available. Disabling spatial colors.
  raw.plot_psd(fmax = 5,picks = 'misc')
/home/wyw/anaconda3/lib/python3.6/site-packages/mne/viz/evoked.py:510: UserWarning: Attempting to set identical left == right == 0.0 results in singular transformations; automatically expanding.
  ax.set_xlim(xlim)
/home/wyw/anaconda3/lib/python3.6/site-packages/mne/viz/utils.py:2200: UserWarning: Attempting to set identical left == right == 0.0 results in singular transformations; automatically expanding.
  ax.set(xlim=(freqs[0], freqs[-1]))

**Comment by drammock** [comment]
We will need more information to be able to help you: version info, the code you tried to run, what data you were analyzing, etc. Please open a new bug report and read the pre-filled instructions that appear, and edit this post following those instructions.
