### ISSUE TITLE
set_bipolar_reference is not present in the doc or any example

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#8993]
we should add

https://mne.tools/stable/generated/mne.set_bipolar_reference.html

to the some example and documentation.

**Comment by drammock** [comment]
some options are:

1. add it in [this section](https://mne.tools/dev/auto_tutorials/preprocessing/plot_55_setting_eeg_reference.html#setting-or-changing-the-reference-channel) or in a new section right after it.  
2. make a short how-to example that just illustrates bipolar referencing
3. both 1 and 2

**Comment by agramfort** [comment]
a good sprint TODO I think

>

**Comment by ramkpari** [comment]
Working on this!
