### ISSUE TITLE
using picks with ica.plot_sources breaks interactive properties plot

### ISSUE THREAD

**Issue by bloyl** [mne-tools/mne-python#8995]
If i specify `picks` to `ica.plot_sources` If I then click on the ica_name to see the properties the indexing is incorrect and the properties for the wrong IC is plotted

For example in the image below I am not plotting **ICA001**, now if I right click on the **ICA004** to plot it's properties I get a window with the correct IC name however the topo and presumably the rest of the the properties plot is for the wrong IC (ICA003) in this case.

<img width="849" alt="image" src="https://user-images.githubusercontent.com/5585821/110039739-b3d51600-7d0f-11eb-9dd8-3a9b93ae7793.png">

cc @drammock

**Comment by drammock** [comment]
I can reproduce, and yes, the data is for the wrong IC (i.e., it's not just the subplot title that is wrong)
