### ISSUE TITLE
combine ICA example into ICA tutorial

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#9003]
merge `examples/preprocessing/plot_run_ica.py` into `tutorials/preprocessing/plot_40_artifact_correction_ica.py`

probably easiest to add a new section to the end of the tutorial, saying something like "By the way, we've been doing ICA on raw, but FYI you can do it on Epochs too...".  Try to re-use whatever objects have already been created by the earlier steps of the tutorial, to minimize run time.

**Comment by rob-luke** [comment]
@neurogima

**Comment by neurogima** [comment]
yep I take this one
