### ISSUE TITLE
split code block in examples/preprocessing/plot_virtual_evoked

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#9004]
right now, because all plots come from a single code block, they are plotted at the top of the example in a group of 4 (and consequently the plots are really small).  By splitting the 4 plotting calls into different code blocks, they will plot larger / be easier to see & compare, without increasing run time of the example.  Code blocks can be split with a line of 79 `#` marks (adding a bit of explanatory text too is usually a good idea)

**Comment by eort** [comment]
I would like to take care of this one

**Comment by eort** [comment]
File name (plot_evoked) and title (Remap mag channels) of this example are different. Not sure how important it is to you that they match?
In my opinion, the title seems to be more appropriate than the file name, but changing file names is probably more troublesome than changing a title.
