### ISSUE TITLE
clean up XDAWN example

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#9005]
in `examples/preprocessing/plot_xdawn_denoising.py` the references are printed at the top; move them to the bottom like they are in most other examples/tutorials.

While you're in there, read through the example and make sure you understand it; improve the wording/explanation of any parts that are awkward or unclear. How-to examples should be fairly short, but if adding a little something (a few extra sentences, one more plot, etc) would make it more informative or clear, add it.

**Comment by catalinamagalvan** [comment]
I'm on this!
