### ISSUE TITLE
Fix corrupted figures in plot_background_freesurfer_mne

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#9007]
Several plots in `tutorials/source-modeling/plot_background_freesurfer_mne.py` are messed up (inverted, misaligned, or corrupted).  See if you can fix them. Check with @larsoner or @GuillaumeFavelier before you start; some of them might be due to 3D viz bugs that aren't fixed yet.

**Comment by larsoner** [comment]
I think this has to do with a change related to whether the camera's focal point is at 0, 0, 0 (new behavior) or center of the bounding box of all objects in the scene (old behavior). @GuillaumeFavelier I think we should make sure that there is some option like `focalpoint='bounds'` or so (and focalpoint=None should mean "use existing focal point"), and maybe set "bounds" (back) to the default. WDYT?

**Comment by GuillaumeFavelier** [comment]
>  this has to do with a change related to whether the camera's focal point is at 0, 0, 0 (new behavior) or center of the bounding box of all objects in the scene (old behavior)

Agreed, the behaviour of the focal point should be clarified and maybe even tested (to avoid this out of focus brain regression) ?

**Comment by larsoner** [comment]
A simple test would be to compute the center of mass based on non-background-color pixels. Do you want to try @GuillaumeFavelier ?

**Comment by GuillaumeFavelier** [comment]
bounds are given by VTK's `ComputeVisiblePropBounds` right?

**Comment by larsoner** [comment]
[Looks like it, yeah](https://github.com/mne-tools/mne-python/blob/main/mne/viz/backends/_pyvista.py#L989).

**Comment by GuillaumeFavelier** [comment]
I'm on it

**Comment by drammock** [comment]
Just found another corrupted 3D plot: https://mne.tools/dev/auto_tutorials/evoked/plot_20_visualize_evoked.html#d-field-maps
