### ISSUE TITLE
viz.plot_compare_evokeds() calculates RMS for all channel types, but claims to be calculating GFP

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#9022]
This is a similar issue to the one fixed via #8775

Currently, `viz.plot_compare_evokeds()`'s `combine='gfp'` argument makes it compute RMS, not GFP.

However, it should calculate GFP for EEG and RMS for MEG data. The `combine='gfp'` option should remain unchanged and simply pick the correct calculation depending on the channel type(s). This means that in case of M/EEG data, we'd have to apply different `combine` functions per subplot, so this is not a totally non-trivial change as far as I can tell (but might be wrong).

**Comment by matteoanelli** [comment]
I can work on this!

**Comment by hoechenberger** [comment]
This is actually not a super trivial issue and might require a bit of refactoring the current plotting code. I can give you a brief summary hopefully later today
