### ISSUE TITLE
Report.include should be a dict, so elements can later be removed if need be

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#9038]
As suggested by @jasmainak:

Currently, `Report.include` is simply a string, and for each new `<head>` element, we append to this string. This, however makes it difficult to reference to existing elements later on, e.g. if one decides to remove them. Therefore, it would be a good idea to turn `Report.include` into a `dict` (Py 3.7+) or `OrderedDict` (Py 3.6+)

**Comment by marsipu** [comment]
I'd like to work on this

**Comment by hoechenberger** [comment]
Perfect!

**Comment by hoechenberger** [comment]
It was decided in #9113 that we don't want this, after all!
