### ISSUE TITLE
Restructure Machine Learning Examples

### ISSUE THREAD

**Issue by FinLouarn** [mne-tools/mne-python#9086]
There is many examples of decoding with machine learning approaches but does it make sense to have all these separate examples, which are showing more or less the same things?
It might make sense to group some of them together, and make a more structured set of examples, illustrating fondamental concepts, in stead of a list of examples with some of them showing similar concepts.

**Comment by agramfort** [comment]
can you describe the order in which you would introduce the concepts
and how you would organize things?

**Comment by larsoner** [comment]
No response and we have newer doc/tutorial restructuring issues, let's discuss there if needed!
