### ISSUE TITLE
ENH: Add montage for Artinis OctaMon and Brite23

### ISSUE THREAD

**Issue by HanBnrd** [mne-tools/mne-python#9093]
#### Describe the new feature or enhancement
We would like to add a default montage for the Artinis OctaMon fNIRS device. This would enable to have spacial locations useful for some pre-processing functions (such as the modified Beer Lamber law) and having visualization on a brain map.

![octamon](https://user-images.githubusercontent.com/32393169/111283357-f0214400-8636-11eb-9c85-ace5acbdb2c6.jpg)

#### Describe your proposed implementation
Adding a file in [mne/channels/data/montages/](https://github.com/mne-tools/mne-python/tree/main/mne/channels/data/montages), modifying [`set_montage()`](https://mne.tools/stable/generated/mne.io.Raw.html#mne.io.Raw.set_montage) (in Raw but also other data types) as and probably the loading functions.

#### Additional comments
Not sure what file format is best to use (csd/sfp/txt/elc), would you have recommendations?

**Comment by HanBnrd** [comment]
We discussed it with @rob-luke and I would be happy to work on a PR for this if you are okay with it.

**Comment by agramfort** [comment]
no objection

is there such a standard montage file available somewhere?

our montage files are shared between packages.

>

**Comment by HanBnrd** [comment]
I don't think there is a standard montage file with 3D coordinates, will try to see if I can adapt the montage template the Artinis software has.

**Comment by agramfort** [comment]
sounds good

>

**Comment by rob-luke** [comment]
@HanBnrd has received the locations in MNI ICBM 152 space. The file format provided by the vendor looks custom. Rather than writing another custom file format reader, I suggest we manually convert these to one of the existing formats perhaps sfp. Would this be acceptable @agramfort @drammock @larsoner

**Comment by rob-luke** [comment]
We will need to edit: https://github.com/mne-tools/mne-python/blob/c638f74ac727aeaca3b9616e56115b990a84c7ba/mne/channels/_standard_montage_utils.py#L108

https://github.com/mne-tools/mne-python/blob/c638f74ac727aeaca3b9616e56115b990a84c7ba/mne/channels/montage.py#L1226-L1306

**Comment by larsoner** [comment]
Yes that sounds reasonable. If the format is not complicated (e.g., some text file that can be easily parsed by eye) I would just add a quick reader for it rather than convert.

**Comment by agramfort** [comment]
ok for me

**Comment by HanBnrd** [comment]
> If the format is not complicated (e.g., some text file that can be easily parsed by eye) I would just add a quick reader for it rather than convert.

We were planning to use the elc structure as the original files are quite similar, even though we have optodes and not electrodes:
- [original txt file sent by Artinis](https://github.com/mne-tools/mne-python/compare/main...HanBnrd:artinis-montages#diff-fa76b4fa1b84fdedc992433dec624eeb2ab5566d9b98f9463f704504ef4b9073)
- [the same montage converted into elc](https://github.com/mne-tools/mne-python/compare/main...HanBnrd:artinis-montages#diff-9ba80d9351b39faa894513f96f4c92a7ab509a6878e71072ca217324c53adf1d)

Would that be okay?

**Comment by agramfort** [comment]
so far so good

>
