### ISSUE TITLE
Migrating from other analysis software- EEGLAB- Adding more info

### ISSUE THREAD

**Issue by apoorva6262** [mne-tools/mne-python#9107]
Wanted to add more info to this document about preprocessing tools such as running types of ICA,removing ICA components , filtering data, channel locations, average referencing, high pass filter to remove drifts.

https://mne.tools/stable/overview/migrating.html?highlight=eeglab

**Comment by larsoner** [comment]
That would be great!

**Comment by drammock** [comment]
closed by #9169
