### ISSUE TITLE
Make an interactive ERP subplot for an ICA component 

### ISSUE THREAD

**Issue by apoorva6262** [mne-tools/mne-python#9108]
#### Describe the new feature or enhancement
Currently, when displaying the individual ICA component, the ERP subplot is not interactive. We want to make this subplot interactive .

#### Describe your proposed implementation
Implement a rectangle selector to zoom in and out for this plot.

**Comment by apoorva6262** [comment]
@mdclarke

**Comment by larsoner** [comment]
Sounds like this has been discussed with @drammock already, looking forward to a PR!
