### ISSUE TITLE
BUG/API with filtering

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#912]
@jdammers just demonstrated to me how to silently produce nans with our band pass filter.

https://gist.github.com/dengemann/7580547

Or old non-Python routines default to order 16 butterworth band pass filters 
(FFT implementation) ...
If you go for lower orders, in certain application evil filter artifacts would occur.

I think we should 

1) add a clear RuntimeError if NaNs are returned by scipy.signal.filtfilt

2) @jdammers suggested to port his IDL fft code, currently we don't support order type construction for fft filters.

WDYT?

**Comment by Eric89GXL** [comment]
We have a check for poles outside the unit circle already, closing this one
