### ISSUE TITLE
new contributor process in changelog is unnecessarily complicated

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#9131]
It is really easy for folks to miss this requirement and easy for devs to forget to mention it when reviewing PRs or asking for changelog entries.  After talking with @larsoner I'm wondering if we can create a sphinx role `:newcontrib:` or similar, that eliminates the need for an extra replacement line at the top of the file.

**Comment by sappelhoff** [comment]
I believe this was closed in #10134
