### ISSUE TITLE
Jupyter Notebook representations of MNE objects

### ISSUE THREAD

**Issue by vagechirkov** [mne-tools/mne-python#9177]
Add HTML rendering of the MNE objects using `_repr_html_` method.

TODO list:

- [x] `Info` #6846 #9161
        
    <details>

    ![image](https://user-images.githubusercontent.com/42982039/111919350-d7c38600-8a89-11eb-8198-02c228652748.png)

    </details>

- [x] `BaseRaw` #9161 #9172 

    <details>

    ![image](https://user-images.githubusercontent.com/42982039/111919303-9d59e900-8a89-11eb-80d9-2730cdd69e03.png)

    </details>

- [x] `Epochs` #9189 

    <details>

    ![image](https://user-images.githubusercontent.com/42982039/112514530-b4545000-8d95-11eb-90de-f4c6892a126f.png)

    </details>

- [ ] `Evoked`
- [ ] `SourceEstimate`

**Comment by hoechenberger** [comment]
I took the liberty to add `SourceEstimate` to the list, too :)

**Comment by mmagnuski** [comment]
This is cool! :)
