### ISSUE TITLE
Reading EDF file yields incorrect scaling

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#9186]
Reported on the forum:
https://mne.discourse.group/t/eeg-data-in-edf-not-converting-in-volt/

The user provided an EDF file which specifies in its header that the data is in µV. When reading this file with MNE-Python, the data is treated as V.

**Comment by cbrnr** [comment]
Opening the file linked in the discussion thread in a hex editor shows that the units are declared as `.V` - so this is clearly an invalid EDF file.

**Comment by drammock** [comment]
invalid file → `wontfix`?

**Comment by cbrnr** [comment]
Yes. MNE has never been super strict, but we should not try to interpret `.V` as `µV`.

**Comment by cbrnr** [comment]
Which raises the question: since we do load the file, should we perhaps be stricter and raise an error? I've always argued not to do that, because having incorrectly scaled data is better than having no data.

**Comment by larsoner** [comment]
I agree, +1 for a warning when we can't safely interpret the units. Then the user can fix their file or adjust their processing as necessary

**Comment by hoechenberger** [comment]
> Which raises the question: since we do load the file, should we perhaps be stricter and raise an error? I've always argued not to do that, because having incorrectly scaled data is better than having no data.

My personal feeling is we should throw an error. I feel that incorrectly scaled data is **worse** than no data ;)

**Comment by hoechenberger** [comment]
Ok, a warning it is!

**Comment by Sumalyo** [comment]
I have tried to address the issue, showing a warning if the unit read is in Volts
