### ISSUE TITLE
MAINT: don't skip CIs when merging to main?

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#9188]
as I write this, the most recent merged PR was #9185 which had all-green CIs.  The commit message for the squashed commit (70709f5069ddb413c2719f4d2b41fd6bfea2349a) does not say "ci skip" or use any other of our skip codes, and yet, all the GitHub CIs are showing as "cancelled" (click the red X at the top of the repo homepage where it shows "most recent commit").  Questions:

1. why?
2. is this what is causing CodeCov badge to show 15% coverage?
3. is it possible to change the skip behavior so that skips can occur in open PRs, but never occur on commits to main?

**Comment by larsoner** [comment]
I'm guessing it's due to the new Cancel job being configured incorrectly. Some digging through the logs in https://github.com/mne-tools/mne-python/actions might shed some light on it
