### ISSUE TITLE
Per channel annotation is too slow

### ISSUE THREAD

**Issue by mehdikuchi** [mne-tools/mne-python#9199]
#### Per channel annotation with clear visual appearance 
The Per channel annotation already developed in the dev version of the MNE, highlights the whole span of the data under view. This makes  event localization visually too difficult. 

#### What I have tried: 

*I have changed the mne/viz/_figure.py code so that I could get the following annotation per channel: 
![image](https://user-images.githubusercontent.com/43707267/112652537-cc87a600-8e4d-11eb-9a0c-e8c9a691ca9c.png)
The problem is scanning the window becomes too slow. 
*

Is there anything that can be added to speed up the scanning of the data?

**Comment by larsoner** [comment]
> Is there anything that can be added to speed up the scanning of the data?

Is it faster if you don't add the text objects? If so, we could make it so that the text just shows up on a mouseover for example

**Comment by drammock** [comment]
it is on our roadmap to have per-channel annotations show up as highlighted regions (rather than text) which I think will be faster to draw.  cf #8946.  It's milestoned for the next release so hopefully you won't have to wait too long for it.

**Comment by mehdikuchi** [comment]
Thanks for your replies. 
That is good news. So I wait for the new release.

**Comment by larsoner** [comment]
#8946 landed so hopefully this was fixed!
