### ISSUE TITLE
Add Raw, Epochs, and Evoked method to fire up MNE Coreg GUI

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#9209]
I'd love to do one of:

```python
epochs.mri_coreg(...)
epochs.coreg_mri(...)
epochs.coregistration(...)
```
to bring up `mne.gui.coregistration()` with some of its parameters automatically filled in based on the respective `Raw/Epochs/Evoked` instance.

Strong feelings against this?

**Comment by larsoner** [comment]
Currently we have `mne.gui.coregistration`. I guess its API is limited by having to pass filenames rather than instances themselves, but that's easy enough to change. I'd rather just update this function.

**Comment by agramfort** [comment]
>
> Currently we have mne.gui.coregistration. I guess its API is limited by
> having to pass filenames rather than instances themselves, but that's easy
> enough to change. I'd rather just update this function.
>

+1
