### ISSUE TITLE
Some trouble with version control tools for data

### ISSUE THREAD

**Issue by adswa** [mne-tools/mne-python#9221]
This is in part a request for better integration between two tools, and in part an FYI.

We are developing datalad (www.datalad.org), a tool to version control and share not only code, but also data and software environments. Internally, datalad uses [git-annex](https://git-annex.branchable.com/) to version control  data. The version control mechanism that git-annex uses is clever, but it prevents mne-python from automatically reading in split data files even if they are correctly named. As more and more MEG dataset are shared openly, and portals that host or analyze these datasets such as OpenNeuro or brainlife.io use DataLad as a backend or frontend, I wanted to raise awareness of the problem, and ask whether its possible to integrate better.
Scripts and datasets that rely on conforming to BIDS standards or mne filenaming standards will fail to read in split files correctly by default.

When a file is version controlled, it is transformed into a symlink with the original file name that points to a path in the "annex" (an internal, non-human readable representation from which for example file transport is managed). This path consists of a hash build from the file content.  
Here is a typical example from a public, BIDS conforming dataset - small files are "as is", larger files are symlinked:

```
 ls -l sub-01/ses-day1/meg 
total 39
-rw-rw---- 1 adina BnB  1211 Mar 30 17:51 sub-01_ses-day1_coordsystem.json
-rw-rw---- 1 adina BnB 25565 Mar 30 17:51 sub-01_ses-day1_task-AVLearn_run-01_channels.tsv
-rw-rw---- 1 adina BnB 34145 Mar 30 17:51 sub-01_ses-day1_task-AVLearn_run-01_events.tsv
-rw-rw---- 1 adina BnB   539 Mar 30 17:51 sub-01_ses-day1_task-AVLearn_run-01_meg.json
lrwxrwxrwx 1 adina BnB   143 Mar 30 17:51 sub-01_ses-day1_task-AVLearn_run-01_part-01_meg.fif -> ../../../.git/annex/objects/Xz/5P/MD5E-s2146079382--dca9c1e4ee05b6b32bdcd4b5aef8c9bb.fif/MD5E-s2146079382--dca9c1e4ee05b6b32bdcd4b5aef8c9bb.fif
lrwxrwxrwx 1 adina BnB   143 Mar 30 17:51 sub-01_ses-day1_task-AVLearn_run-01_part-02_meg.fif -> ../../../.git/annex/objects/1F/4J/MD5E-s1231308362--bd7d70c27e61d20e79466544e8873954.fif/MD5E-s1231308362--bd7d70c27e61d20e79466544e8873954.fif
```
The symlink is committed into Git, allowing to version control data of arbitrary size. As  the symlink contains precise file identity information (the hash), a content change of the file results in a change of this symlink and in turn transparently into a "modification" that can be committed. 

Internally, mne-python resolves the symlink to read the file (cool!), but then uses only the realpath to construct consecutive splits. This fails, as it searches in the internal data annex (where files are named based on their content, not based on standards) instead of the human readable symlink names.

Here is a reproducer:

```
# get public data from openneuro
$ datalad install https://github.com/OpenNeuroDatasets/ds002598.git
$ cd ds002598/
# retrieve some relevant files (here: two fif files of one subject)
$ datalad get  sub-01/ses-day1/meg/sub-01_ses-day1_task-AVLearn_run-01_part-*.fif

# try to open the first split:
$ ipython
>>> import mne
>>> raw =  mne.io.read_raw_fif('sub-01/ses-day1/meg/sub-01_ses-day1_task-AVLearn_run-01_part-01_meg.fif')
Opening raw data file sub-01/ses-day1/meg/sub-01_ses-day1_task-AVLearn_run-01_part-01_meg.fif...
    Read a total of 13 projection items:
        generated with autossp-1.0.1 (1 x 306)  idle
        generated with autossp-1.0.1 (1 x 306)  idle
        generated with autossp-1.0.1 (1 x 306)  idle
        generated with autossp-1.0.1 (1 x 306)  idle
        generated with autossp-1.0.1 (1 x 306)  idle
        generated with autossp-1.0.1 (1 x 306)  idle
        generated with autossp-1.0.1 (1 x 306)  idle
        generated with autossp-1.0.1 (1 x 306)  idle
        generated with autossp-1.0.1 (1 x 306)  idle
        generated with autossp-1.0.1 (1 x 306)  idle
        generated with autossp-1.0.1 (1 x 306)  idle
        generated with autossp-1.0.1 (1 x 306)  idle
        generated with autossp-1.0.1 (1 x 306)  idle
    Range : 27000 ... 2060999 =     27.000 ...  2060.999 secs
Ready.
<ipython-input-2-cb1c10b217d7>:1: DeprecationWarning: The default for on_split_missing is "warn" in 0.22 but will change to "raise" in 0.23, set it explicitly to avoid this message
  raw = mne.io.read_raw_fif('sub-01/ses-day1/meg/sub-01_ses-day1_task-AVLearn_run-01_part-01_meg.fif')
<ipython-input-2-cb1c10b217d7>:1: RuntimeWarning: Split raw file detected but next file /home/adina/scratch/ds002598/.git/annex/objects/Xz/5P/MD5E-s2146079382--dca9c1e4ee05b6b32bdcd4b5aef8c9bb.fif/sub-01_ses-day1_task-AVLearn_run-01_part-02_meg.fif does not exist. Ensure all files were transferred properly and that split and original files were not manually renamed on disk (split files should be renamed by loading and re-saving with MNE-Python to preserve proper filename linkage).
  raw = mne.io.read_raw_fif('sub-01/ses-day1/meg/sub-01_ses-day1_task-AVLearn_run-01_part-01_meg.fif')
```

**Comment by drammock** [comment]
Thanks for the reproducible example!  I'll go have lunch while the large files download, and will take a look this afternoon 🥪
