### ISSUE TITLE
mne.preprocessing.find_ecg_events has a non-descript error when it can't detect ecg events

### ISSUE THREAD

**Issue by CJ-Wave** [mne-tools/mne-python#9225]
#### Describe the bug
mne.preprocessing.find_ecg_events has a non-descript error when it can't detect ecg events

#### Steps to reproduce
Should work with just a straight line or zeros in an ECG channel. 

#### Expected results
Either return an empty array or generate a more descriptive error message

#### Actual results
line 230, in find_ecg_events
    ecg_events = remap[ecg_events]
IndexError: arrays used as indices must be of integer (or boolean) type

(This is because ecg_events is None)
#### Additional information
Platform:      Windows-10-10.0.19041-SP0
Python:        3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
Executable:   ...python.exe
CPU:           Intel64 Family 6 Model 158 Stepping 13, GenuineIntel: 8 cores
Memory:        Unavailable (requires "psutil" package)
mne:           0.22.0
numpy:         1.19.2 {blas=mkl_rt, lapack=mkl_rt}
scipy:         1.5.2
matplotlib:    3.3.2 {backend=Qt5Agg}
sklearn:       0.24.1
numba:         0.52.0
nibabel:       Not found
nilearn:       Not found
dipy:          Not found
cupy:          Not found
pandas:        1.1.5
mayavi:        Not found
pyvista:       Not found
vtk:           Not found

**Comment by agramfort** [comment]
can you send a PR?

thx

>
