### ISSUE TITLE
FTP protocol download support

### ISSUE THREAD

**Issue by v-goncharenko** [mne-tools/mne-python#9226]
#### Describe the new feature or enhancement
[`moabb`](https://github.com/NeuroTechX/moabb) heavily uses `mne` for processing data.
Also all downloads are performed via `mne.utils._fetch_file`: [see usage here](https://github.com/NeuroTechX/moabb/blob/d9334f5c64d10e2c0a2512124cd3fb2ecf682bd3/moabb/datasets/download.py#L61)

Currently `moabb` has a dataset which files are stored on FTP server and available over this protocol.
But `_fetch_file` fails with an error ([see it here](https://github.com/NeuroTechX/moabb/issues/77#issuecomment-809696126)) because `moabb` passes [this `ftp` url](https://github.com/NeuroTechX/moabb/blob/d9334f5c64d10e2c0a2512124cd3fb2ecf682bd3/moabb/datasets/gigadb.py#L18)

#### Describe your proposed implementation
Add `ftp` protocol support to `_fetch_file`

#### Describe possible alternatives
`moabb` writes it's own download function (but it's nice to use existing one in `mne`)

#### Additional comments
Is it okay to use a function starting with underscore (`_`) in external code? Afaik no =)
Maybe you have a public interface for this functionality?

**Comment by drammock** [comment]
@v-goncharenko we are already considering maybe getting rid of a lot of our file fetching code, and depending instead on [pooch](https://pypi.org/project/pooch/).  Pooch supports FTP already.  It might be worth seeing how easy it is to use `pooch.retrieve()` and `pooch.FTPDownloader()` for your needs rather than relying on an MNE-Python function that isn't part of our public API.

**Comment by adam2392** [comment]
FYI @v-goncharenko with #9742, we are moving forward with the creation of a general-MNE-purpose dataset fetcher that could be used by downstream packages potentially.

**Comment by larsoner** [comment]
Closing since this hopefully is now supported by `fetch_dataset` by using `pooch` under the hood
