### ISSUE TITLE
Image title of spectal connectivity

### ISSUE THREAD

**Issue by isabelceo-dot** [mne-tools/mne-python#9228]
There is a bug on the title of spectral connectivity the colorbar (always shows PLI method). Probably this is a relic of a time when phase lag index was the only measure you offered. See discussion here: https://mne.discourse.group/t/image-title-of-spectal-connectivity/2905

**Comment by agramfort** [comment]
@isabelceo-dot we need to add a title parameter in plot_sensors_connectivity and I would consider it a bug fix
