### ISSUE TITLE
BUG: apply_function arg/kwarg handling

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#9234]
`raw/epochs/evoked.apply_function` all have an `*args, **kwargs` in their signatures. But they don't work the way I think they should / the docs are rather misleading. Preparation:

```py
import os
import mne
from scipy.ndimage import gaussian_filter

sample_data_folder = mne.datasets.sample.data_path()
sample_data_raw_file = os.path.join(sample_data_folder, 'MEG', 'sample',
                                    'sample_audvis_raw.fif')
raw = mne.io.read_raw_fif(sample_data_raw_file, verbose=False, preload=False)
raw.crop(tmax=5).load_data()
```

`gaussian_filter1d` requires a `sigma` parameter in addition to the data. This works as expected:
```py
raw.apply_function(gaussian_filter1d, sigma=4)
```
This also works:
```py
kwargs = dict(sigma=4)
raw.apply_function(gaussian_filter1d, **kwargs)
```

This next one is expected to fail **if you already know how argument unpacking works**, and does fail (`4.` is passed as `picks` param of `apply_function`, so you get `picks must be a list of int or list of str, got a data type of float64`):
```py
args = (4.,)
raw.apply_function(gaussian_filter1d, *args)
```
But note that if `args = (4,)` (int instead of float) you get a different error, that `gaussian_filter1d` is missing required argument `sigma`).  From the perspective of a new user, this is really bad: `*args` is in the docstring, so I pass in `*args` and it fails, in 2 different ways depending on what seems like a trivial difference in input.

This also fails (`gaussian_filter1d() got an unexpected keyword argument 'args'`) though might have been expected/tried by a new user:
```py
args = (4.,)
raw.apply_function(gaussian_filter1d, args=args)
```

This also fails due to python syntax restrictions, but might have been expected to work based on the docstring:
```py
raw.apply_function(gaussian_filter1d, verbose=None, *args)
```

So in sum we don't actually support passing `args` to the applied function.  Possible solutions:

1. change function signature from `*args, *kwargs` to `args, kwargs`, and accept only tuples for `args` and only dicts for `kwargs`
2. drop `*args` from the function signature, leave kwarg handling as it is

**Comment by agramfort** [comment]
I would use functools.partial but I understand if you say it's too
complicated...

or maybe we document it clearly in the docstring?

>

**Comment by drammock** [comment]
> I would use functools.partial but I understand if you say it's too complicated...

I would say the safest / easiest-to-maintain option is not to accept args/kwargs at all, and advise people to use `functools.partial`. This would require a deprecation cycle for sure; people's code would break.

I would say the most minimal change (not requiring deprecation, because it never worked) is to eliminate `*args` and keep `**kwargs`.

I lean toward the second option, it's less work for us now and also less work for users, and `**kwargs` already works so it's not that much burden to keep it around because it's not that complicated.

**Comment by larsoner** [comment]
Agreed `**kwargs` is painless enough to keep supporting, and we should kill `*args` as a bugfix

**Comment by agramfort** [comment]
Ok

**Comment by hoechenberger** [comment]
+1 for keeping kwargs and dropping args
