### ISSUE TITLE
ENH: Add evoked.get_data

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#9244]
In #9241 there are lines like:
```
evoked_eeg_interp.data[evoked_eeg_interp.ch_names.index('EEG 004'), :]
```
We should have `evoked.get_data` like we have for epochs and raw so this can just become:
```
evoked_eeg_interp.get_data('EEG 004')
```
and become more API-consistent.

**Comment by agramfort** [comment]
+1
