### ISSUE TITLE
Removal of muscle artifacts

### ISSUE THREAD

**Issue by Mirrabella** [mne-tools/mne-python#9304]
Hello, 
I have a very simple question, but I just can't find a clear answer for it. 
I am exercising to cleanse the muscle signal with the function annotate_muscle_zscore() .
As I understand, the function creates an annotation with which we can then mark the found muscle artifacts as "bad". And then, when we write the annotation to the raw data using the

raw.set_annotations (annot_muscle) function,

these tagged muscle artifact data segments will be automatically deleted when epochs are created. I understand correctly?

I was guided by this fragment (from the description of the function to mne.Annotations)
![q](https://user-images.githubusercontent.com/33099309/115013356-991ec100-9eb9-11eb-81b2-ef2bbb2ad069.jpeg)

And what time interval of data will be cut when removing muscle artifacts? I did not really understand this point from the description of the function.:( 

Thank you in advance :)

**Comment by hoechenberger** [comment]
Hello @Mirrabella!

> these tagged muscle artifact data segments will be automatically deleted when epochs are created. I understand correctly?

Yes, segments annotated with `bad_*` will be excluded when creating epochs.


> And what time interval of data will be cut when removing muscle artifacts?

I've never worked with this code myself, but after setting the annotations via `raw.set_annotations()`, you can visually inspect the data via `raw.plot()`; you will be able to see the annotated segments.

**Comment by drammock** [comment]
usage questions are generally more appropriate on our forum (https://mne.discourse.group).  If there are any follow-up questions, please post them there.
