### ISSUE TITLE
Support any elc file with set_montage

### ISSUE THREAD

**Issue by HanBnrd** [mne-tools/mne-python#9309]
#### Describe the new feature or enhancement
As discussed with @rob-luke, we think it could be interesting to have the possibility to set a montage with any elc file with MNI coordinates.

#### Describe your proposed implementation
Given a custom elc montage file *my-montage.elc* with MNI coordinates standardised the same way as [other existing elc files](https://github.com/mne-tools/mne-python/tree/main/mne/channels/data/montages), it would be great to have an API like this:
```python
# Detailed implementation
my_montage = mne.channels.make_standard_montage('path/to/my-montage.elc')
raw.set_montage(my_montage)

# With also the possibility to use it in one step
raw.set_montage('path/to/my-montage.elc')
```

#### Describe possible alternatives
Alternatives include having a separate function *set_custom_elc_montage* which takes the raw or epochs or evoked object and the montage path as arguments.

**Comment by agramfort** [comment]
raw.set_montage

https://mne.tools/dev/generated/mne.io.Raw.html#mne.io.Raw.set_montage

can already take a string as parameter. Does it do what you want?

**Comment by HanBnrd** [comment]
> raw.set_montage can already take a string as parameter. Does it do what you want?

At the moment the string argument is only working with a [list of predefined montages](https://github.com/mne-tools/mne-python/blob/main/mne/channels/montage.py#L45-L56), so it could be useful to have also a way to provide a custom montage file.

**Comment by agramfort** [comment]
you don't foresee a clash in API?

>

**Comment by HanBnrd** [comment]
> you don't foresee a clash in API?

It could maybe check if there is a file with the name being the string argument and if not check in the built in montages or the other way around. But maybe a separate function could be a safer option.

**Comment by larsoner** [comment]
I'm not worried about the extremely rare corner case where someone has a filename that matches one of our extensionless built-in names. If someone ever hits this the workaround is easy, just pass './whatever' instead of 'whatever'.

**Comment by agramfort** [comment]
ok why not then. PR welcome

>

**Comment by HanBnrd** [comment]
Hi, after diving deeper into this I realised that there is already the function [*read_custom_montage*](https://mne.tools/stable/generated/mne.channels.read_custom_montage.html#mne.channels.read_custom_montage) doing this, sorry for not seeing this earlier.

It is not working directly with `set_montage('path/to/file.elc')` but like this:
```python
montage = mne.channels.read_custom_montage('path/to/file.elc')
raw.set_montage(montage)
```
which is good enough I think. So I'm closing this issue.

**Comment by rob-luke** [comment]
Great catch. Maybe worth adding to the new tutorial too?
