### ISSUE TITLE
Cutting a new release

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#9312]
Hello all,

it's been 4 months since the release of MNE-Python 0.22.0, and we've had super busy contributors submitting a large stream of changes, producing a big list of enhancements and bug fixes:

https://mne.tools/dev/whats_new.html

Many of these will make the lives of our users more pleasant 😁 so I suggest we should consider making a new release soon. The currently set due date of the 0.23 milestone is in approx. 4 weeks, and I believe we should aim to really meet the deadline this time.

What's your opinion?

**Comment by larsoner** [comment]
Agreed we should have that deadline as an upper bound. I think folks should go through open issues and PRs and mark what needs to be done. I can probably make some bugfix PRs this week

**Comment by agramfort** [comment]
+1 I don't know if we have current blockers. If not I don't see a reason to
wait more.

>

**Comment by drammock** [comment]
there are several blockers I think.  Most prominent in my mind is that many of the 3D plots in the current dev docs have really messed up rendering (#9007 / #9010).  It would also be nice to get the PR that renames all the examples/tutorials finalized first (#9292), as well as the current website changes (#9288).

**Comment by larsoner** [comment]
I went through and marked issues and PRs I see as blockers. I don't think it should take too long to take care of them

**Comment by larsoner** [comment]
FYI based on the remaining 0.23-marked issues and PRs I plan to cut a release tomorrow

**Comment by larsoner** [comment]
Closing, starting the process once CircleCI comes back green from the latest PR
