### ISSUE TITLE
Documentation for copy parameter in CSD inaccurate

### ISSUE THREAD

**Issue by fbaumgardt** [mne-tools/mne-python#9319]
It appears that this line in the CSD documentation is not accurate:
https://github.com/mne-tools/mne-python/blob/93359566261be5c3fe7ceef8cb1fefce910cca52/mne/preprocessing/_csd.py#L88

I.e. I don't see any code for re-referencing based on the parameter. Also, the type validation happens after its use.

**Comment by agramfort** [comment]
maybe for @alexrockhill or @dengemann ?

**Comment by alexrockhill** [comment]
I think the note is for the code as it was previously and then the average reference got taken out. I don't think it should have, that was with mine and @larsoner's last PR fixing the CSD. I'll look at the old, not fixed version and see if the line that re-references should be put back in.

**Comment by fbaumgardt** [comment]
Yeah, I'm just scanning through https://psychophysiology.cpmc.columbia.edu/Software/CSDtoolbox/faq.html to figure out if it's required. I had to remove an implicit reference but I'm still parsing out whether mastoid references are okay.

Thanks for the code and for dealing with the issue!

**Comment by alexrockhill** [comment]
Hmm okay so maybe the note should be changed then...

**Comment by alexrockhill** [comment]
Great, so I think the function works as is (besides the copy type validation but that doesn't really effect the output) but the documentation will be clarified when https://github.com/mne-tools/mne-python/pull/9320 merges and the validation will also be in the right order.

**Comment by alexrockhill** [comment]
PR merged, I think this is good to be closed 👍
