### ISSUE TITLE
ENH: Add data reader for Hitachi NIRS files

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#9355]
@rob-luke I got some Hitachi NIRS data files from a collaborator, do you think it's worth writing a proper reader for them? They appear to be a CSV with some header information so it shouldn't be too difficult in principle, though I think in practice it might be a pain to acquire proper test data for it. I can look into it if you think it's worth having in MNE, though.

**Comment by rob-luke** [comment]
This would be fantastic to have! Hitachi is one of the popular vendors and would therefore be commonly used. Within the auditory field several of the prominent labs use hitachi including Nottingham/Hartley and UCL.

If I remember correctly these devices have a fixed set of optode positions. If my memory is correct, we could have these as pre saved montages like we just did with the Artinis fixed arrays if that information is not in the headers. I've heard of some people 3d printing custom array holders, but they would then have to specify positions manually.

I also have some hitachi experiment files so I could test locally. But I dont have access to a machine to collect test data.
