### ISSUE TITLE
ENH/DOC: trouble shooting guide

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-python#937]
My idea was to set up list of things to check + rule out before filing a bug report.

Inspired by https://github.com/mxcl/homebrew/wiki/Troubleshooting

We could even refer to it in our Error messages ;-)

**Comment by Eric89GXL** [comment]
Moving this to 0.10 unless someone has some free time

**Comment by Eric89GXL** [comment]
Closing for #1495
