### ISSUE TITLE
mne.io.read_raw_curry() cannot read the event file end with '.cdt.ceo'

### ISSUE THREAD

**Issue by dddd1007** [mne-tools/mne-python#9380]
#### Describe the bug
I have tried to use `mne.io.read_raw_curry()` to read my data created by Curry 8, but there were no annotations in the Raw object. But EEGLAB can import the data and show the annotations correctly.

#### Steps to reproduce
I read the source code of [curry.py](https://github.com/mne-tools/mne-python/blob/maint/0.23/mne/io/curry/curry.py), and I found this function cannot handle the ".cdt.ceo" file. 

So I change the file extension of my file from ".cdt.ceo" to "cdt.cef", and the function works smoothly.

#### Expected results
`mne.io.read_raw_curry()` can read cef file too, or it will make some users confused.

#### Additional information
I am sorry for my weak program skill. I have tried to fix this bug.

**Comment by drammock** [comment]
Can you share the original file (Dropbox, Google drive link, etc) so we can test?

**Comment by dddd1007** [comment]
> Can you share the original file (Dropbox, Google drive link, etc) so we can test?

Definitely yes. Here is the original file.

https://www.dropbox.com/s/d41yfv7ik0ldzpv/eeg_raw.zip?dl=0

**Comment by dddd1007** [comment]
This bug is fixed by @drammock .

**Comment by drammock** [comment]
FYI, normally we leave issues open until the fixing pull request has been merged, in case during review the solution is found to be incorrect or incomplete.

**Comment by dddd1007** [comment]
I am sorry for my brusque being.

**Comment by drammock** [comment]
> I am sorry for my brusque being.

no problem!  Different software projects handle issues/PRs differently.  Thanks for reporting this bug and helping to fix it.
