### ISSUE TITLE
Add option to save Annotions as `.tsv`

### ISSUE THREAD

**Issue by eort** [mne-tools/mne-python#9395]
#### Describe the new feature or enhancement
The BIDS specification requires `.tsv` rather than `.csv`  files for tabular data. Currently, annotations can only be written to `fif`, `txt`, and `csv`. So it would be nice to add `tsv` support to that list. 

#### Describe your proposed implementation
Should be easy enough by adding a separate call to `read/write_annotations.py` for `tsv` file, and calling internally read/write_csv with `sep='\t'`.

**Comment by agramfort** [comment]
Sounds like a good idea

**Comment by sappelhoff** [comment]
agreed! convenience link to api: https://mne.tools/dev/generated/mne.Annotations.html?highlight=annotations#mne.Annotations.save
