### ISSUE TITLE
Importing .SET Files returns Errors within Library Line 24

### ISSUE THREAD

**Issue by Thomasvandang** [mne-tools/mne-python#9409]
Hi I'm trying to import my set file for analysis of erp and p300, but when reading the files, it returns these errors. 

Does anyone know what I'm doing wrong?

Code:
```python
import mne
data_path = r"C:/Users/thoma/Desktop/EEG/session/1";
fname = data_path + '/EEG1.set'
mydata = mne.io.read_raw_eeglab(fname)
```

Error:

![image](https://user-images.githubusercontent.com/82453316/118867110-b8da4800-b8b0-11eb-8225-afe7087e9645.png)

**Comment by agramfort** [comment]
can you read the file with another  reader ?

https://pypi.org/project/pyEDFlib/

maybe in matlab? if not it's a like a pb of the file.

if mne is the pb please the file with me.

>

**Comment by hoechenberger** [comment]
friendly ping @Thomasvandang, does the problem persist?

**Comment by sappelhoff** [comment]
Closing, because there is too little information/data to know whether this is an MNE-Python problem. Please feel free to reopen this once you are available to share more information and the broken data file @Thomasvandang
