### ISSUE TITLE
doc: In changelog, add release date after "version heading"

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-python#9439]
My analysis pipeline yields a slightly different result ... I updated MNE in the meantime, so now I investigate the changelog for potential culprits (functions that might have changed, or bugs that were squashed, etc.).

Having the release date next to each version in the changelog would help me with "debugging" this situation, as I know when I last ran the pipeline. I can dig out that information from pypi, or the github releases page, but it would be much more convenient to have it directly in the changelog.

My proposal is to change these lines: https://github.com/mne-tools/mne-python/blob/e6a029802bb2174eaee21f0ab544b4b64c71c1da/doc/changes/0.21.inc#L11-L13

to something like:

```
Version 0.21 (2021-04-02)
```

What do you think?

**Comment by larsoner** [comment]
Yes please open a PR to add these based on https://pypi.org/project/mne/#history, then edit wiki to update "How to make a release" to mention this
