### ISSUE TITLE
Plot all channels with raw.plot_psd

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#9441]
We have already discussed and fixed the problem that it was impossible to plot the PSD of bad channels (#6637, #6678). However, I find the solution still not ideal. I frequently need to plot PSDs of all channels, and the only way to do that is to pass all channel indices or names to `picks`. I'd prefer a string value, but unfortunately `"all"` and `"data"` are already taken and just include good channels. There's also the default third option (`None`), which seems to be equal to `"all"`.

Does anyone have a good suggestion how to solve this issue?

**Comment by agramfort** [comment]
I would do it such that:

raw.plot_psd(spatial_colors=False, exclude=None)

plots all channels including bads. Woudl you also plot simple with different line style or color?

**Comment by cbrnr** [comment]
> I would do it such that:
>
> `raw.plot_psd(spatial_colors=False, exclude=None)`

I guess you mean `raw.plot_psd(spatial_colors=False, picks=None)`? Yes, this would work, but then we need to change the default to `picks="all"` in order not to break current behavior.

> Woudl you also plot simple with different line style or color?

Not sure what you mean, but usually I use the default `spatial_colors=True` but with `average=False` (otherwise I'd get an average over all channels).

**Comment by agramfort** [comment]
>
> I guess you mean raw.plot_psd(spatial_colors=False, picks=None)? Yes,
> this would work, but then we need to change the default to picks="all" in
> order not to break current behavior.
>

presently the default is picks=None and this plots all good channels. I
propose to add an exclude param
that would default to 'bads' and that would not change the default
behavior. So when you change
the default with

 raw.plot_psd(spatial_colors=False, picks=None, exclude=[])

it would plot the bads. This is consistent with evoked.plot for example.

> Woudl you also plot simple with different line style or color?
>
> Not sure what you mean, but usually I use the default spatial_colors=True
> but with average=False (otherwise I'd get an average over all channels).
>

I would copy the behavior of evoked.plot (colors when exclude is [])

makes sense?

**Comment by cbrnr** [comment]
Sounds good. Any objections? Otherwise I'll make a PR.

**Comment by larsoner** [comment]
Sounds reasonable to me

**Comment by drammock** [comment]
+1 from me anytime we're make API + behavior more consistent between different plotting functions :)
