### ISSUE TITLE
Add info about reading in Polhemus head scan file into raw instance

### ISSUE THREAD

**Issue by rylaw** [mne-tools/mne-python#9452]
Currently, there is no documentation that says that the Polhemus head scan `.pos` file can be read into a `Raw` instance via `mne.io.read_raw_ctf` when the `.pos` file is placed in the CTF directory.

#### Proposal
Include this piece of information in the Notes of the [`mne.io.read_raw_ctf` doc](https://mne.tools/stable/generated/mne.io.read_raw_ctf.html?highlight=read_raw#mne.io.read_raw_ctf).

**Comment by drammock** [comment]
good idea!  Could you make a PR?  I would also suggest adding a short sentence to the CTF tutorial, saying something like "notice also that the digitized electrode positions (stored in `whatever.pos`) were automatically loaded and added to the `~mne.io.Raw` object."  I'd probably put it somewhere around here: 

https://github.com/mne-tools/mne-python/blob/0d5068dbbce76598c9c6433e1ace1265e1955564/tutorials/io/60_ctf_bst_auditory.py#L77-L89

**Comment by rylaw** [comment]
Yeap, just created one over at #9460!
