### ISSUE TITLE
ENH: Speed up TimeDelayingRidge prediction

### ISSUE THREAD

**Issue by rkmaddox** [mne-tools/mne-python#9455]
Have been using `mne.decoding.time_delaying_ridge.TimeDelayingRidge` and noticed that its `fit` function is faster than its `predict` function, because only the former takes advantage of frequency domain computations. Fixing it might be as simple as changing the `np.convolve` to an FFT-based convolution function such as `scipy.signal.fftconvolve`. I have not done this because it is quite possible that there are other places in the `decoding` module that could benefit from the same (basically, any predictor that relies on a series of adjacent lags as features).

**Comment by agramfort** [comment]
I think that TimeDelayingRidge is pretty unique. It's safe to open a PR to
just fix this estimator.

thx @rkmaddox

>
