### ISSUE TITLE
BUG: weird CNT reading

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#9482]
Tried on both stable and dev.

I'm trying to read a [.cnt  file](https://osf.io/xq5pd/). 

MNE indicates no error or warnings.

However, the raw (or epoched data, based on the annotations) looks very weird: 

* every other channels alternate between a small set of discrete values: ```list(map(lambda x: len(np.unique(x)), raw._data[:, :1000]))``` => ```[[994, 8, 992, 7, 996, 6, 996, 7, 992, 6 ...]]```
* the data within a given raw channels is discontinuous and does not show the classic 1/f dynamics:
![image](https://user-images.githubusercontent.com/4881164/122220107-51fc7e80-ceb0-11eb-9cec-c2e10b544115.png)
* the epoched data based on the annotation does not look any kind of ERP: 
![image](https://user-images.githubusercontent.com/4881164/122220200-66407b80-ceb0-11eb-948f-36e8745e6ff4.png)

I suspect there is something wrong in how the data chunks are read and assembled, but I don't really understand the mne.io.cnt parser to help :/

**Comment by larsoner** [comment]
Indeed it seems like a likely datatype or order problem, I'll take a look in the coming days

**Comment by kingjr** [comment]
thanks!

**Comment by larsoner** [comment]
CNT does not reliably store how many bytes per sample, and we do warn during runtime:
```
/Users/larsoner/opt/miniconda3/bin/mne:33: RuntimeWarning: Could not define the number of bytes automatically. Defaulting to 2.
```
Using `data_format='int32'` things look okay:
```
$ python -ic "import mne; raw = mne.io.read_raw_cnt('STIR1.cnt', data_format='int32'); raw.plot()"
```
<img width="810" alt="Screen Shot 2021-06-28 at 4 57 12 PM" src="https://user-images.githubusercontent.com/2365790/123703076-ec09e280-d831-11eb-8280-f4f54115534f.png">


Closing as I'm not sure any fix is needed at the MNE end. Maybe a doc update with a warning (?), but to me the runtime warning was clear enough to work around the format limitation.

**Comment by kingjr** [comment]
awesome, thanks @larsoner !
