### ISSUE TITLE
permutation test and t-max trick

### ISSUE THREAD

**Issue by nastia-lado** [mne-tools/mne-python#9492]
Hi!

It's unclear from the documentation how do you use t-max trick for multiple comparisons correction.
The documentation says that the function permutation_t_test returns:
p_values : array of shape [n_tests]        P-values for all the tests (a.k.a. variables). 
H0 : array of shape [n_permutations]        T-statistic obtained by permutations and t-max trick for multiple comparison.

Are these p-values already corrected for multiple comparisons or should we use H0 output and perform the t-max correction ourselves?

I saw similar questions on the forum:
https://mne.discourse.group/t/permutation-t-test-multiple-comparison-correction/2729

Maybe you can update the documentation in order to make it clear.

Thanks!

**Comment by agramfort** [comment]
@nastia-lado can you use the forum https://mne.discourse.group/ to ask users questions unless you think it's a bug?
