### ISSUE TITLE
Plotting 20 ICA topomaps, makes the ica name appear on the topomap above in small screens

### ISSUE THREAD

**Issue by pooyaEst** [mne-tools/mne-python#9495]
#### Describe the bug
Plotting 20 ICA topomaps, makes the ica name appear on the topomap above in small screens and clicking on the name to remove it, also opens the page related to topomap above.

![69100ff39cb5f224dce0e19a0d23de580fad49b9_2_1380x862](https://user-images.githubusercontent.com/426713/122905350-6f6a9600-d351-11eb-913c-95a1220f0c19.jpeg)

#### Expected results
 being able to either reduce size of topomaps or number of them appearing in a single page or both.

**Comment by cbrnr** [comment]
What happens if you resize the window, e.g. make it really small and then enlarge it again? Does it change anything?

**Comment by pooyaEst** [comment]
if i change the size to around half in my 13" display, it works but still that would be nice to have an option to modify number of components present or their size.

**Comment by cbrnr** [comment]
You can set the number of components with the `picks` argument (https://mne.tools/stable/generated/mne.preprocessing.ICA.html#mne.preprocessing.ICA.plot_components).
