### ISSUE TITLE
Enable exporting EDF files

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-python#9566]
#### Describe the new feature or enhancement
There are gists available for using PyEDFlib to write EDF files, and pyedflib seems to be relatively well maintained and used.

This proposal is to enable exporting EDF files, with a warning of course that there maybe loss of data in the `info` object. This would also enable mne-bids to perform writing EDF file datasets, which is a RECOMMENDED file format for storage of EEG/iEEG data.

In addition, this would enable writing to an open-access file format that is heavily interfaced in EEG industry. For example, Persyst, an EEG-analytics company can only read in manufacturing formats (natus/NK/etc.) and EDF. It cannot read fiff, BrainVision, or other open source formats.

#### Describe your proposed implementation
This would extend https://github.com/mne-tools/mne-python/pull/9192 to add EDF file exporting. This would add an optional dependency with `pyedflib` (https://github.com/holgern/pyedflib).

#### Additional comments
Related issue in `mne-bids`: https://github.com/mne-tools/mne-bids/issues/840

**Comment by larsoner** [comment]
Sounds reasonable to me

**Comment by sappelhoff** [comment]
Just so that this doesn't get lost, @teuniz has chimed in in https://github.com/mne-tools/mne-bids/issues/840#issuecomment-879635128 and suggested https://gitlab.com/Teuniz/EDFlib-Python as an alternative.

Pros over `PyEDFlib`:
- developed/maintained by the same person who develops EDFlib (which pyEDFlib uses)

Cons: 
- no pypi package?
- documentation/tests not very mature (no info on supported py versions, no CI, no API docs)
- smaller user base (maybe hard to judge, I just see the GitLab stars)

Finally, I think both packages have an edge over https://github.com/bids-standard/pyedf which is a separate package independent of EDFlib, ... but it never took off.

**Comment by cbrnr** [comment]
Thanks for the heads up @sappelhoff! IMO PyPI availability (pyEDFlib) trumps pure Python (EDFlib-Python) in this case, also because it is an optional dependency. Another issue might be the [custom license](https://gitlab.com/Teuniz/EDFlib-Python/-/blob/master/LICENSE), which is probably compatible with BSD, but I'm not sure. However, it shouldn't be too difficult to switch to a different EDF writer if the situation changes.

**Comment by agramfort** [comment]
honestly it's really a bummer that there is 3 EDF libraries in Python. Can
we make these people
collaborate so there is one good, well maintained and well tested library
with a permissive BSD/MIT license?
I think it's necessary for the community to consolidate and the python
ecosystem has understood this for years
(contrarily to C++ or Javascripts world which are a lot more messy to
navigate).

my 2c

>

**Comment by cbrnr** [comment]
If you count our own reader and [Biosig](https://pypi.org/project/Biosig/) there are even more. I completely agree that there should only be one well maintained EDF package in pure Python licensed under BSD/MIT.

I just noticed that [EDFlib-Python](https://www.teuniz.net/edflib_python/) is advertised as licensed under BSD-3 (in contrast to the `LICENSE` file in the repo). So maybe that's a good starting point? How would you proceed @agramfort?

**Comment by Teuniz** [comment]
> If you count our own reader and [Biosig](https://pypi.org/project/Biosig/) there are even more. I completely agree that there should only be one well maintained EDF package in pure Python licensed under BSD/MIT.
> 
> I just noticed that [EDFlib-Python](https://www.teuniz.net/edflib_python/) is advertised as licensed under BSD-3 (in contrast to the `LICENSE` file in the repo).

Correct me if I'm wrong but the license file at https://gitlab.com/Teuniz/EDFlib-Python/-/blob/master/LICENSE has the same text as here: https://opensource.org/licenses/BSD-3-Clause

**Comment by Teuniz** [comment]
> honestly it's really a bummer that there is 3 EDF libraries in Python. Can we make these people collaborate so there is one good, well maintained and well tested library with a permissive BSD/MIT license?

There can be many reasons why people sometimes don't want to collaborate.
One example: how strict should an EDF-reader be in (dis)allowing to read from a not 100% compliant EDF file?
EDFlib and EDFbrowser are very strict. Not everybody likes that.
For me, the longterm future of the EDF format is more important than trying to please angry or disappointed users who have a database full of non-compliant files.

**Comment by cbrnr** [comment]
> Correct me if I'm wrong but the license file at https://gitlab.com/Teuniz/EDFlib-Python/-/blob/master/LICENSE has the same text as here: https://opensource.org/licenses/BSD-3-Clause

You're right, I didn't read the text but assumed because it is classified as "Other" that it is not any of the popular licenses (maybe it is possible to change this setting in GitLab somewhere?).

**Comment by cbrnr** [comment]
> There can be many reasons why people sometimes don't want to collaborate.
One example: how strict should an EDF-reader be in (dis)allowing to read from a not 100% compliant EDF file?
EDFlib and EDFbrowser are very strict. Not everybody likes that.
For me, the longterm future of the EDF format is more important than trying to please angry or disappointed users who have a database full of non-compliant files.

Good example, we regularly deal with non-compliant files. I agree that it is important to enforce the file format, but often it's just tiny inconsistencies (such as different encodings) that are pretty easy to fix. This allows people to access their data, whereas the alternative is to have no data at all.

I think a good solution is to enforce strict mode by default, but allow some minor deviations optionally.

Regarding EDFlib-Python, would you be up for a PyPI release?

**Comment by agramfort** [comment]
I would favor a strict support of the standard (whatever it means...)
otherwise you put the burden on yourself and not on the users who are often
very creative....

>

**Comment by adam2392** [comment]
> Regarding EDFlib-Python, would you be up for a PyPI release?

+1 for using @Teuniz 's "strict" EDFlib-Python library. I'd rather have an EDF file that can be read by EDFBrowser, then just "EDF by name" and can only be read by MNE/EEGlab functions.

**Comment by cbrnr** [comment]
An EDF writer should definitely be super strict. My comments on relaxing some restrictions a little apply only to a reader.

**Comment by Teuniz** [comment]
> An EDF writer should definitely be super strict. My comments on relaxing some restrictions a little apply only to a reader.

That's not going to happen. EDFlib is finished and offered "as is". Consider it an LTS release.  
Any bugs wiil be fixed ofcourse. New function calls will be taken into consideration if it makes sense.  
API breakage is not going to happen though.  
Ofcourse, there's always the option to clone & fork and turn it into a "community project" but my support will be limited  
to the vanilla EDFlib.

**Comment by cbrnr** [comment]
I think we were mostly talking about the writer component, because we already have our own reader which is not that strict.

**Comment by Teuniz** [comment]
Understood and no problem. The Python version of EDFlib is split into a reader and a writer part  
(they are different files) and you can simply grab the writer only and don't bother with the reader if you wish.

**Comment by adam2392** [comment]
Awesome!

What would be the next best course of action here if EDFlib isn't pypi released?

**Comment by drammock** [comment]
@Teuniz would you be open to doing a PyPi release of python EDFlib?  One of us could help out with the changes needed for packaging, if that makes a difference.  If not, I think our only option for using EDFlib is incoporating the writer into our `externals/` (which we tend to be hesitant to add things to)

**Comment by Teuniz** [comment]
> @Teuniz would you be open to doing a PyPi release of python EDFlib? One of us could help out with the changes needed for packaging, if that makes a difference. If not, I think our only option for using EDFlib is incoporating the writer into our `externals/` (which we tend to be hesitant to add things to)
I'll look into it, I have never done it before but I have a colleague with lots of Python experience.
It's just that we are entering the holiday period here, so it will take some time.

**Comment by adam2392** [comment]
I took a stab at sketching out the export functionality. The barebones works (with some details not matching up).

Just a friendly ping to see if there was any update on getting a PyPi release? I can help with it if needed?

**Comment by Teuniz** [comment]
> Just a friendly ping to see if there was any update on getting a PyPi release?

It's done, you can find it here: https://pypi.org/project/EDFlib-Python/
