### ISSUE TITLE
How to use visualize channel data features using mne.viz.plot_topomap

### ISSUE THREAD

**Issue by zewangnew** [mne-tools/mne-python#9573]
I have calculated some data features from the time series of each channel. The measure is saved in an data array. How to visualize them on top of the topmap or how to project them back to a brain template so I can visualize them in brain cortex?
Below is the example code I used. The last line reported an error of "Multiple channel types in Info structure. Pick Info with e.g. mne.pick_info and mne.io.pick.channel_indices_by_type"

import os
import numpy as np
import mne
sample_data_folder = mne.datasets.sample.data_path()
sample_data_raw_file = os.path.join(sample_data_folder, ‘MEG’, ‘sample’,
‘sample_audvis_filt-0-40_raw.fif’)
raw = mne.io.read_raw_fif(sample_data_raw_file)
ica = mne.preprocessing.ICA(n_components=20, random_state=97, max_iter=800)
ica.fit(raw)
ica.exclude = [1, 2] # details on how we picked these are omitted here
ica.plot_properties(raw, picks=ica.exclude)

entr = np.zeros([dat.shape[0],1])
N=10000 # take 10000 as a quick test
for i in range(dat.shape[0]):
print(i)
ts=dat[i,:N]
#en = entropy(ts) # entropy is my code
entr[i]=en
meginfo=mne.pick_info(raw.info, meg_channel_indices)
meginfo
#print(entr.shape)
mne.viz.plot_topomap(entr, meginfo, ch_type='meg')

**Comment by agramfort** [comment]
This appears to be a question about usage, not a bug report or a new feature request. Please use the [MNE forum](https://mne.discourse.group/) for usage questions.
