### ISSUE TITLE
write an mneinstaller.py script inspired by fslinstaller.py

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#960]
just to avoid the issues we had on wednesday in Paris.

the script would:
- assume scientific python is there (eg anaconda)
- download the MNE-C code nightly adapted to the system
- update the .bashrc 
- download mne-python and install it (optionally in user home)
- raise warning if mayavi, pysurfer are not installed.

any volunteer?

**Comment by Eric89GXL** [comment]
@agramfort do you still want this?

**Comment by agramfort** [comment]
keep this open. I think it would still be useful as we still recommend
mne_analyze and mne_browse_raw

**Comment by Eric89GXL** [comment]
I don't think we need this anymore because our MNE-C dependency has been lifted. @agramfort agreed?
