### ISSUE TITLE
Better error message for 3D plots when pyvistaqt is missing

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#9606]
When creating a 3D plot with e.g. `mne.viz.plot_alignment` (not sure if there are any additional similar functions), I get an error if `pyvistaqt` is not installed:

```
RuntimeError: Could not load any valid 3D backend: pyvista, mayavi, notebook
```

Note that I actually have `pyvista` installed, but it seems like `pyvistaqt` is *also* required. A simple solution would be to update the error message like this (since `pyvistaqt` depends on `pyvista`):

```
RuntimeError: Could not load any valid 3D backend: pyvistaqt, mayavi, notebook
```

**Comment by hoechenberger** [comment]
cc @GuillaumeFavelier

**Comment by GuillaumeFavelier** [comment]
Hm... I agree it's better.

**Comment by GuillaumeFavelier** [comment]
I'll open a PR to rename the backend
