### ISSUE TITLE
viz.plot_alignment() window should have participant name / ID in its title

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#9615]
Currently, the figures I get via `viz.plot_alignment()` are titled `PyVista Scene`, which isn't very helpful when you want to ensure you're looking at the correct participant. Would it be possible to have a title like, `f'Sensor Alignment: {subject}'`?

**Comment by GuillaumeFavelier** [comment]
Indeed `PyVista Scene` is the default name for the window. It's possible to change it by setting a different value for the `name` parameter of the `_get_renderer()` function. 

For `plot_alignment` on `main` (f73907c01ce6a18e4941969d3491cc561617c32d), it should be around here:

https://github.com/mne-tools/mne-python/blob/f73907c01ce6a18e4941969d3491cc561617c32d/mne/viz/_3d.py#L946
