### ISSUE TITLE
[BUG] Coordinate Frame not Saved

### ISSUE THREAD

**Issue by alexrockhill** [mne-tools/mne-python#9635]
I'm not sure if I'm missing something obvious but it looks like the coordinate frame doesn't survive the round trip to and from disk. I'm not sure why that is.

```
import numpy as np
import mne

for ch_type in ('eeg', 'seeg', 'ecog', 'dbs'):
    raw = mne.io.RawArray(
        np.random.random((10, 1000)),
        mne.create_info([f'ch{i}' for i in range(1, 11)],  1000, [ch_type] * 10))
    montage = mne.channels.make_dig_montage(
        {ch: np.random.random((3,)) for ch in raw.ch_names}, lpa=[1, 0, 0], nasion=[0, 0.1, 0], rpa=[-1, 0, 0],
        coord_frame='mri')
    raw.set_montage(montage)
    raw.save('tmp-raw.fif', overwrite=True, verbose=False)
    print(ch_type)
    print('Before: ', raw.info['chs'][0]['coord_frame'])
    info = mne.io.read_info('tmp-raw.fif')
    print('After : ', info['chs'][0]['coord_frame'])
```

Note, it appears this is specific to `seeg`, `ecog` and `dbs`, it works for `eeg`.

**Comment by alexrockhill** [comment]
To update, it looks like this was on purpose but I think it would be better to assume that `seeg`, `ecog` or `dbs` channel positions are in head coordinate frames because if they are set using `inst.set_montage(montage)` they will be converted. To my knowledge, there are no other public APIs to set the channel positions so it seems like they should be assumed to be in head if read from a disk.

**Comment by alexrockhill** [comment]
@larsoner, this is in https://github.com/mne-tools/mne-python/pull/9585/, just wanted to make sure you were aware and thought this was reasonable

**Comment by larsoner** [comment]
Yeah I think it's just an oversight that we never added these channel types to the inferred-coord-frame list

**Comment by alexrockhill** [comment]
Great, just making sure it wasn't for a reason I wasn't thinking of
