### ISSUE TITLE
MAINT, CI: pyvista and scipy deprecation warnings

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#9649]
https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=14743&view=logs&j=fa98c7b3-575e-55b6-6946-22dea6f6daf8&t=c0866e65-eed5-5461-eadc-f0ff150eefd8&l=3422

> DeprecationWarning: rcParams is deprecated.  Please use ``pyvista.global_theme``

The CI installed pyvista 0.31.3 (latest release, from 23 June)

Note that there are also SciPy deprecation warnings appearing for `pinvh` and `pinv2`:

https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=14743&view=logs&j=fa98c7b3-575e-55b6-6946-22dea6f6daf8&t=c0866e65-eed5-5461-eadc-f0ff150eefd8&l=3154

> DeprecationWarning: Use of the "cond" and "rcond" keywords are deprecated and will be removed in future versions of SciPy. Use "atol" and "rtol" keywords instead

https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=14743&view=logs&j=fa98c7b3-575e-55b6-6946-22dea6f6daf8&t=c0866e65-eed5-5461-eadc-f0ff150eefd8&l=3039

> DeprecationWarning: scipy.linalg.pinv2 is deprecated since SciPy 1.7.0, use scipy.linalg.pinv instead

also in `mffpy`:

https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=14743&view=logs&j=fa98c7b3-575e-55b6-6946-22dea6f6daf8&t=c0866e65-eed5-5461-eadc-f0ff150eefd8&l=3085

> DeprecationWarning: Call to deprecated function (or staticmethod) flavor. (Use ".mff_flavor" instead) -- Deprecated since version 0.6.3.

cc @GuillaumeFavelier  do you know the right fix for the pyvista one off the top of your head?  If not I can try to sort out all of these tomorrow (unless someone else beats me to it).

**Comment by GuillaumeFavelier** [comment]
Is it an old version of mne?

This is fixed in `main` by the new version of `_disabled_depth_peeling()`:

https://github.com/mne-tools/mne-python/blob/c9752455b79de10fac672d3ed25911f2618f71cc/mne/viz/backends/_pyvista.py#L1128-L1141

**Comment by drammock** [comment]
> Is it an old version of mne?

it's in the windows 3.7 conda build, but it installs current `main`
