### ISSUE TITLE
Montage correction for misplaced cap

### ISSUE THREAD

**Issue by lokinou** [mne-tools/mne-python#9655]
#### Describe the new feature or enhancement
I have several hours of EEG recording where a mistake was made: **the cap was shifted down** such that Cz channel was instead located over CPz location. **I would like to correct for this misplaced cap**

The measurement has 128 channels and thus I'd like to correct the montage and perhaps later use inverse methods on this corrected data rather than discarding it.

Is there any elegant solution for this? Such as shifting all electrodes locations in the montage by an angle?
I'm not very comfortable with the underlying geometry and a bit scared to make mistakes in this regard

**Comment by mmagnuski** [comment]
Hi @lokinou 
I think this question is better suited for our discussion forum: https://mne.discourse.group/
I have written a response to your question, so I could paste it here, but I think it will be better if I reply once you post your question to the dicsussion forum. :)
