### ISSUE TITLE
Typo in preprocessing example 15 - Handling bad channels

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-python#9675]
Maybe I am mistaken, but this looks like a typo: https://mne.tools/stable/auto_tutorials/preprocessing/15_handling_bad_channels.html#when-to-look-for-bad-channels

> After the data has been collected, you can do a more thorough check for bad channels by browsing the raw data using 
> mne.io.Raw.plot(), with any projectors or ICA applied. Finally, you can compute offline averages (again with projectors, 
> ICA, and EEG referencing disabled) to look for channels with unusual properties.

First sentence should be:

> [...] without any projectors or ICA applied.

**Comment by agramfort** [comment]
agreed !

can you send a PR?

>

**Comment by mscheltienne** [comment]
Will do.
