### ISSUE TITLE
MAINT: plot_alignment newly failing examples

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#9680]
@alexrockhill can you take a look at these CI failures from `plot_alignment`?  Looks related to your recent work.

`ValueError: A head->mri transformation matrix is required to plot pial surfaces, `trans=None` is not allowed`

https://app.circleci.com/pipelines/github/mne-tools/mne-python/9716/workflows/54dba24d-162b-43ba-87ba-3884689e8574/jobs/33025

**Comment by alexrockhill** [comment]
Fixing it now
