### ISSUE TITLE
Colorbar does not plot for viz.topoplot

### ISSUE THREAD

**Issue by moonj94** [mne-tools/mne-python#9683]
I am trying to visualize a topography with a colorbar, but I cannot for the life of me get the colorbar to show. I am using MNE 0.23.0.

Here is my code:

```
fig,ax=plt.subplots(1,1,figsize=(6,6),dpi=1200)
clim = dict(kind='value', lims=[4, 8, 12])

im,cm=mne.viz.plot_topomap(dist[0,:],raw_concat.info,contours=5,axes=ax,cmap='viridis',vmin=np.min(dist),vmax=np.max(dist))
ax_x_start = 0.95
ax_x_width = 0.04
ax_y_start = 0.1
ax_y_height = 0.9
cbar_ax = fig.add_axes([ax_x_start, ax_y_start, ax_x_width, ax_y_height])
# clb = plt.colorbar(cm, cax=cbar_ax,ax=ax)
unit_label='MDS distance'
# plt.colorbar(cm)
clb = fig.colorbar(cm, cax=cbar_ax,ax=ax)
clb.ax.set_title(unit_label,fontsize=14) # title on top of colorbar
plt.show()
```

I have also tried (following matplotlib example):
```
fig,ax=plt.subplots(1,1,figsize=(6,6),dpi=1200)
clim = dict(kind='value', lims=[4, 8, 12])

im,cm=mne.viz.plot_topomap(dist[0,:],raw_concat.info,contours=5,axes=ax,cmap='viridis',vmin=np.min(dist),vmax=np.max(dist))

divider = make_axes_locatable(ax)
cax = divider.append_axes("right", size="5%", pad=0.05)
plt.colorbar(im,cax=cax,ax=ax)
```

Your help is very much appreciated!

**Comment by agramfort** [comment]
```
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import mne

sample_dir = Path(mne.datasets.sample.data_path())
sample_fname = sample_dir / 'MEG' / 'sample' / 'sample_audvis_raw.fif'

raw = mne.io.read_raw_fif(sample_fname)
raw.crop(tmax=60)
raw.pick('eeg')

fig, (ax, cbar_ax) = plt.subplots(1, 2, figsize=(6, 4), gridspec_kw=dict(width_ratios=[6, 1]))
clim = dict(kind="value", lims=[4, 8, 12])

dist = 10e-6 * np.random.randn(1, len(raw.ch_names))

im, cm = mne.viz.plot_topomap(
    dist[0, :],
    raw.info,
    contours=5,
    axes=ax,
    cmap="viridis",
    vmin=np.min(dist),
    vmax=np.max(dist),
)
unit_label = "MDS distance"
clb = fig.colorbar(im, cax=cbar_ax, ax=ax)
clb.ax.set_title(unit_label, fontsize=14)  # title on top of colorbar
plt.show()
```
this should work.

close the issue if so.

**Comment by moonj94** [comment]
Hi Alexandre, thanks for the help. Your code helped me put the colorbar axes in the same figure, but I am not able to plot the colors themselves on the axes. How can I achieve this?

**Comment by agramfort** [comment]
sorry I don't get what you mean

>

**Comment by moonj94** [comment]
When I use the code you wrote, this is the product:
![image](https://user-images.githubusercontent.com/53019885/130463406-0a215165-08c6-4955-999e-586e0cab5e0e.png)

I can't get any colors on the colorbar itself. and the colorbar title also does not show

**Comment by agramfort** [comment]
my code gives me this:

![figure_1](https://user-images.githubusercontent.com/161052/130463826-0065ded8-afbe-491b-9e1f-a2c7e224125e.png)

**Comment by moonj94** [comment]
thats odd, how can I troubleshoot this issue? Do you think it could be an issue with Spyder? I should say that I am using spyder 4.2.1. I can't seem to download any version higher than that because of dependency conflicts

**Comment by drammock** [comment]
> Do you think it could be an issue with Spyder?

try it in a system console with Python or IPython; if it works there and fails from within Spyder, then it's almost surely an issue with Spyder

Other things to try (in order):

1. see whether running `import matplotlib.pyplot as plt; plt.ion()` first fixes it; if so, one of the earlier lines was blocking execution of the later lines, so they weren't taking effect
2. *in the terminal where the plot is failing*, run `mne.sys_info()` and report the results here.

**Comment by agramfort** [comment]
can you try directly from python or a notebook and not from spyder?

>

**Comment by moonj94** [comment]
@drammock I tried plt.ion and it didn't make a difference.

I also tried updating every package including spyder and matplotlib and the issue still persists.

@agramfort I tried running the script in python3 terminal/bash and i still do not get any colors.

**Comment by drammock** [comment]
> 2. _in the terminal where the plot is failing_, run `mne.sys_info()` and report the results here.

**Comment by moonj94** [comment]
@drammock I updated my previous comment

**Comment by drammock** [comment]
I can reproduce your error.  But I can also fix it by adding `plt.ion()` to @agramfort's code example (after the `import` statements).  Are you *sure* you tried including `plt.ion()` *before* the figure was created?

**Comment by moonj94** [comment]
@drammock I tried putting plt.ion() right after importing and before the figure was generated. This is the script:

```
import scipy.io
import os
import numpy as np
# from mapping.barplot_annotate_brackets import barplot_annotate_brackets
import mne
from mne import io
import matplotlib.pyplot as plt
plt.ion()
mat=scipy.io.loadmat('/Volumes/tempdata/Study2/MDS/dist.mat')
dist=mat['dist']
pval=mat['pval']
#  topoplot

pvalpass=pval>0.05
dist[pvalpass]=0
# from mpl_toolkits.axes_grid1 import make_axes_locatable

data_path2='/Volumes/data2/Study2/Raw/P98/S02'
# data_path2='/Volumes/data2/Study1/Raw/P{0:02d}'.format(ps[participant])+'/S02'
for file in os.listdir(data_path2):
    if file.endswith('.vhdr'):
        data_path2=os.path.join(data_path2,file)
    # for file in os.listdir(data_path2):
    #     if file.endswith('.vhdr'):
    #         data_path2=os.path.join(data_path2,file)

raw_concat=io.read_raw_brainvision(vhdr_fname=data_path2,preload=True)   
# actual topoplot

# dist = 10e-6 * np.random.randn(1, len(raw.ch_names))
fig, (ax, cbar_ax) = plt.subplots(1, 2, figsize=(6, 4), gridspec_kw=dict(width_ratios=[6, 1]))
clim = dict(kind="value", lims=[4, 8, 12])
plt.ion()
im, cm = mne.viz.plot_topomap(
    dist[0, :],
    raw_concat.info,
    contours=5,
    axes=ax,
    cmap="viridis",
    vmin=np.min(dist),
    vmax=np.max(dist),
)
unit_label = "MDS distance"
# plt.colorbar()
clb = fig.colorbar(cm, cax=cbar_ax, ax=ax)
clb.ax.set_title(unit_label, fontsize=14)  # title on top of colorbar
plt.show(block=True)
```

This is the figure I keep getting:
![Figure_1](https://user-images.githubusercontent.com/53019885/130484001-fa034190-ca8f-4adc-882f-f318e22b83a4.png)

**Comment by drammock** [comment]
It's difficult to debug when your script references paths and data objects that I can't access.  Here is @agramfort's script again, with `plt.ion()` added in the latest possible place (just to emphasize where it needs to go).  Can you please test **this script** instead of the one using your own data, and tell us if it works?

```
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import mne

sample_dir = Path(mne.datasets.sample.data_path())
sample_fname = sample_dir / 'MEG' / 'sample' / 'sample_audvis_raw.fif'

raw = mne.io.read_raw_fif(sample_fname)
raw.crop(tmax=60)
raw.pick('eeg')
plt.ion()  # <<<<<< this needs to happen **before** you create the figure!!
fig, (ax, cbar_ax) = plt.subplots(1, 2, figsize=(6, 4), gridspec_kw=dict(width_ratios=[6, 1]))
clim = dict(kind="value", lims=[4, 8, 12])

dist = 10e-6 * np.random.randn(1, len(raw.ch_names))

im, cm = mne.viz.plot_topomap(
    dist[0, :],
    raw.info,
    contours=5,
    axes=ax,
    cmap="viridis",
    vmin=np.min(dist),
    vmax=np.max(dist),
)
unit_label = "MDS distance"
clb = fig.colorbar(im, cax=cbar_ax, ax=ax)
clb.ax.set_title(unit_label, fontsize=14)  # title on top of colorbar
plt.show()
```

**Comment by moonj94** [comment]
I am still getting the same result, with plt.ion placed before plt.subplots

**Comment by moonj94** [comment]
I tried fig.colorbar (im, cax=cbar_ax,ax=ax) in bash and it seems to have worked (used cm previously). Not sure why it is not working on spyder, however.

Thanks @agramfort @drammock

**Comment by drammock** [comment]
FYI, I just had a chance to test in spyder.  If you add `show=False` to the `plot_topomap` call, then it works with the inline backend too.
