### ISSUE TITLE
_repr_html_ of Info missing many data channels

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-python#9707]
the _repr_html_ from Info class only shows a subset of channels eg misses iEEG and ECoG. The logic here https://github.com/mne-tools/mne-python/blob/main/mne/io/meas_info.py#L822 should be changed to get all data channels (even all channels) and show the counts.

**Comment by hoechenberger** [comment]
@vagechirkov Wanna take a stab at this?
