### ISSUE TITLE
ICA 'ValueError: array must not contain infs or NaNs' when using all channels (included marked bads)

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-python#9716]
#### Describe the bug

I have a dataset where I mark bad channels and then interpolate them. To keep track of which channel has been interpolated, I do not reset `raw.info['bads']`, and instead I prefer to pass `exclude=[]` to other MNE functions.
However, this leads to something that looks like a bug to me.

#### Steps to reproduce

Load sample dataset:
```
import mne
from pathlib import Path

data_folder = Path(mne.datasets.sample.data_path())
raw_file = data_folder / 'MEG' / 'sample' / 'sample_audvis_filt-0-40_raw.fif'
raw = mne.io.read_raw_fif(raw_file, preload=True)
raw.pick_types(eeg=True)
raw.info['bads'] = ['EEG 002', 'EEG 012', 'EEG 015']
raw.interpolate_bads(reset_bads=False, mode='accurate')
```

Pick all EEG channels including bads and fit ICA:

```
picks = mne.pick_types(raw.info, eeg=True, exclude=[])
ica = mne.preprocessing.ICA(n_components=0.99, max_iter='auto')
ica.fit(raw, picks=picks, reject_by_annotation=True)
```

This code above fails with the traceback below.

However, resetting the list of bads and fitting the ICA does work, which in practice should be the same as in both case I'm picking all channels:

```
raw.info['bads'] = list()
ica = mne.preprocessing.ICA(n_components=0.99, max_iter='auto')
ica.fit(raw, picks='eeg', reject_by_annotation=True)
```

Traceback:

> /Users/scheltie/Documents/pyvenv/neurotin/lib/python3.8/site-packages/mne/preprocessing/ica.py:694: RuntimeWarning: overflow encountered in true_divide
>   data /= self.pre_whitener_
> Traceback (most recent call last):
> 
>   File "/var/folders/b1/kx2x00x95ls80zzkct4647sh0000gn/T/ipykernel_9109/2823392955.py", line 15, in <module>
>     ica.fit(raw, picks=picks, reject_by_annotation=True)
> 
>   File "<decorator-gen-420>", line 24, in fit
> 
>   File "/Users/scheltie/Documents/pyvenv/neurotin/lib/python3.8/site-packages/mne/preprocessing/ica.py", line 570, in fit
>     self._fit_raw(inst, picks, start, stop, decim, reject, flat,
> 
>   File "/Users/scheltie/Documents/pyvenv/neurotin/lib/python3.8/site-packages/mne/preprocessing/ica.py", line 614, in _fit_raw
>     self._fit(data, 'raw')
> 
>   File "/Users/scheltie/Documents/pyvenv/neurotin/lib/python3.8/site-packages/mne/preprocessing/ica.py", line 707, in _fit
>     data = pca.fit_transform(data.T)
> 
>   File "/Users/scheltie/Documents/pyvenv/neurotin/lib/python3.8/site-packages/mne/utils/numerics.py", line 817, in fit_transform
>     U, S, _ = self._fit(X)
> 
>   File "/Users/scheltie/Documents/pyvenv/neurotin/lib/python3.8/site-packages/mne/utils/numerics.py", line 855, in _fit
>     U, S, V = _safe_svd(X, full_matrices=False)
> 
>   File "/Users/scheltie/Documents/pyvenv/neurotin/lib/python3.8/site-packages/mne/fixes.py", line 69, in _safe_svd
>     return linalg.svd(A, **kwargs)
> 
>   File "/Users/scheltie/Documents/pyvenv/neurotin/lib/python3.8/site-packages/scipy/linalg/decomp_svd.py", line 108, in svd
>     a1 = _asarray_validated(a, check_finite=check_finite)
> 
>   File "/Users/scheltie/Documents/pyvenv/neurotin/lib/python3.8/site-packages/scipy/_lib/_util.py", line 293, in _asarray_validated
>     a = toarray(a)
> 
>   File "/Users/scheltie/Documents/pyvenv/neurotin/lib/python3.8/site-packages/numpy/lib/function_base.py", line 488, in asarray_chkfinite
>     raise ValueError(
> 
> ValueError: array must not contain infs or NaNs

#### Additional information

Platform:      macOS-10.16-x86_64-i386-64bit
Python:        3.8.10 (v3.8.10:3d8993a744, May  3 2021, 08:55:58)  [Clang 6.0 (clang-600.0.57)]
Executable:    /Users/scheltie/Documents/pyvenv/neurotin/bin/python3
CPU:           i386: 12 cores
Memory:        32.0 GB

mne:           0.23.0
numpy:         1.21.2 {blas=openblas, lapack=openblas}
scipy:         1.7.1
matplotlib:    3.4.3 {backend=Qt5Agg}

sklearn:       0.24.2
numba:         0.53.1
nibabel:       3.2.1
nilearn:       0.8.0
dipy:          1.4.1
cupy:          Not found
pandas:        1.3.1
mayavi:        4.7.3
pyvista:       0.31.3 {pyvistaqt=0.5.0, OpenGL 4.1 ATI-4.6.20 via AMD Radeon Pro 555X OpenGL Engine}
vtk:           9.0.1
PyQt5:         5.15.4

**Comment by agramfort** [comment]
so the problem is the following. The picks that you pass is ignored by the whitening code (see _compute_pre_whitener method).

it's not so easy to fix as we scale the data per channel types and not channel by channel...

basically the logic need to be changed so _compute_pre_whitener takes into account the picks that you pass in fit.

anyone wants to gives this fix a try?

**Comment by mscheltienne** [comment]
So probably something along the lines of passing the argument `picks` from `_fit_raw` and `_fit_epochs` to `_fit`; and from `_fit` to `_compute_pre_whitener`. I'll open the PR with this proposition tomorrow, some iteration will probably be needed to figure out what to do about this long list of `if/elif/else` statements.
