### ISSUE TITLE
Is the stc.plot hemi parameter broken?

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-python#9720]
#### Describe the bug
For my own code plotting source estimates only the right hemisphere is no showing, even if I set `hemi="both`

#### Steps to reproduce
I think this may also be evident in the examples like

https://mne.tools/dev/auto_tutorials/inverse/40_mne_fixed_free.html#fixed-orientation

which had code
```python
snr = 3.0
lambda2 = 1.0 / snr ** 2
kwargs = dict(initial_time=0.08, hemi='both', subjects_dir=subjects_dir,
              size=(600, 600))

stc = abs(apply_inverse(evoked, inv, lambda2, 'MNE', verbose=True))
brain = stc.plot(figure=1, **kwargs)
brain.add_text(0.1, 0.9, 'MNE', 'title', font_size=14)
```

#### Expected results (docs from 0.23)

![](https://mne.tools/stable/_images/sphx_glr_40_mne_fixed_free_001.png)

#### Actual results (docs from 0.24-dev)

![](https://mne.tools/dev/_images/sphx_glr_40_mne_fixed_free_001.png)

**Comment by agramfort** [comment]
it seems so...

>

**Comment by larsoner** [comment]
I can look into this today hopefully

**Comment by rob-luke** [comment]
Thanks, that was quick!
