### ISSUE TITLE
Plot sensors is broken, not showing sensors in rendered docs.

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-python#9744]
#### Describe the bug
The plot sensors function is not plotting sensors on the fNIRS tutorial (I haven't checked other tutorials, may be general too).

#### Steps to reproduce / Actual results

See dev docs https://mne.tools/dev/auto_tutorials/preprocessing/70_fnirs_processing.html#view-location-of-sensors-over-brain-surface

#### Expected results
See stable docs https://mne.tools/stable/auto_tutorials/preprocessing/70_fnirs_processing.html#sphx-glr-auto-tutorials-preprocessing-70-fnirs-processing-py

#### Additional information
I have seen lots of activity with the 3D brain visualisation lately, so I am not sure who to ping, so everyone related gets a ping! @agramfort @larsoner @GuillaumeFavelier @alexrockhill

**Comment by larsoner** [comment]
Can you try locally on latest `main`? The fixes from #9741 have not landed in `mne.tools` yet (should be in 2h hopefully now that #9743 is in)

**Comment by larsoner** [comment]
... if not, then this might be due to #9737 or something similar

**Comment by rob-luke** [comment]
> should be in 2h 

I may have some programming time this afternoon, so more than 2h from now, so I will report back later today if this gets fixed by the new PRs :)

**Comment by rob-luke** [comment]
Just checked, it's not fixed.
