### ISSUE TITLE
Raw plotting using vispy

### ISSUE THREAD

**Issue by mluessi** [mne-tools/mne-python#975]
It would be nice to have more efficient hardware-accelerated raw data plotting, e.g., using https://github.com/vispy/vispy

**Comment by jona-sassenhagen** [comment]
Is there a long-term timeline for this? I hate having to switch back to py2 for mayavi stuff.

**Comment by Eric89GXL** [comment]
vispy development has slowed substantially unfortunately

**Comment by Eric89GXL** [comment]
Closing as WONTFIX :(

**Comment by mmagnuski** [comment]
:(
I have been trying out pyqtgraph for raw signal plotting lately and it works really well (scrolling is fast and smooth) - and pyqtgraph is a pure python package. I was thinking of mirroring the current raw.plot() and epochs.plot() API and gui, but I'll open a separate issue for this once I have something useful.

**Comment by Eric89GXL** [comment]
AFAIK `pyqtgraph` is no longer under active development

**Comment by mmagnuski** [comment]
activity graph doesn't suggest that: https://github.com/pyqtgraph/pyqtgraph/graphs/contributors
it seems to have a slow but steady pace :)

**Comment by Eric89GXL** [comment]
Ahh, in that case yeah give it a try
