### ISSUE TITLE
Muse data

### ISSUE THREAD

**Issue by mebi01** [mne-tools/mne-python#9775]
#### Describe the new feature or enhancement
*Please provide a clear and concise description of what you want to add or
change.*

Hi, thank you for this great library. I am working with Muse and Emotive Epoc X data. Muse has 4 EEG channels and Epoc X has 16. I am wondering if the outputs from these hardwares are supported by MNE. If yes, can you please let me know where is the starting points? if, no, is there any possibilities we have this type of data be supported by MNE?

**Comment by agramfort** [comment]
This appears to be a question about usage, not a bug report or a new feature request. Please use the [MNE forum](https://mne.discourse.group/) for usage questions.
