### ISSUE TITLE
Cannot manually select tracing on the plotted source space estimate (plotted stc object)!

### ISSUE THREAD

**Issue by izadysadr** [mne-tools/mne-python#9786]
MNE-Python version: 0.23.4
operating system: MS Windows 10

Hello,

I have some trouble manually inserting traces on my plotted source space estimate. First, when I plot my source space estimate, I get the following error in my console:

`QWindowsWindow::setGeometry: Unable to set geometry 1131x1216+640+276 (frame: 1149x1261+631+240) on QWidgetWindow/"MainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1131x1057+640+276 (frame: 1149x1102+631+240) margins: 9, 36, 9, 9 minimum size: 394x210 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=412,255 maxtrack=0,0) QWindowsWindow::setGeometry: Unable to set geometry 1131x1216+640+276 (frame: 1149x1261+631+240) on QWidgetWindow/"MainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1131x1057+640+276 (frame: 1149x1102+631+240) margins: 9, 36, 9, 9 minimum size: 394x210 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=412,255 maxtrack=0,0)`

and when I click on my plotted source space estimate to set my traces manually, I get this error:

```
File "C:\Users\Aqil\anaconda3\envs\mne\lib\site-packages\mne\viz\_brain\_brain.py", line 1348, in _on_button_release
    self.picked_renderer = self.plotter.iren.FindPokedRenderer(x, y)
AttributeError: 'RenderWindowInteractor' object has no attribute 'FindPokedRenderer'
```

I also cannot erase the automatically generated traces on my plotted source space estimate no matter how many times I click on the plot. I can only clear them by pressing ‘c’. I had no trouble placing traces on my stc plots in older versions of MNE.

Here is my code:

```
surfer_kwargs = dict(
    hemi='lh', subjects_dir=subjects,
    views='lateral')

brain = stc.plot(**surfer_kwargs)
```

You can access the Python script snippet in the link below:
https://drive.google.com/file/d/1O1m2UfDGxfVvtWgKfEUqN5NKzjT_pPL3/view?usp=sharing

Thank you!

Aqil

**Comment by rob-luke** [comment]
Hi Aqil @izadysadr,

Thanks for reporting this issue. I have moved the issue from the MNE-NIRS repository to the MNE-Python repository because I think/guess that this is due to the underlying MNE-Python code, also there are more eyes here to help you out.

Regarding the issue you face, could you please provide the system info that was requested in the issue template.

**Comment by izadysadr** [comment]
Hello Robert,  Thank you for your email! My system info that was requested in the issue template is as follows: Platform:      Windows-10-10.0.19043-SP0Python:        3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]Executable:    C:\Users\Aqil\anaconda3\envs\mne\python.exeCPU:           Intel64 Family 6 Model 158 Stepping 10, GenuineIntel: 12 coresMemory:        15.9 GB mne:           0.23.4numpy:         1.20.3 {blas=mkl_rt, lapack=mkl_rt}scipy:         1.7.1matplotlib:    3.4.2 {backend=Qt5Agg} sklearn:       0.24.2numba:         Not foundnibabel:       3.2.1nilearn:       0.8.1dipy:          1.3.0cupy:          Not foundpandas:        1.3.2mayavi:        Not foundpyvista:       0.32.1 {pyvistaqt=0.5.0, OpenGL 4.5.0 NVIDIA 471.96 via NVIDIA GeForce GTX 1070/PCIe/SSE2}vtk:           9.0.1PyQt5:         5.12.3 Please, let me know if more information is required.  Looking forward to hearing from you. Thank you! Aqil From: Robert LukeSent: Monday, September 27, 2021 7:40 PMTo: mne-tools/mne-pythonCc: izadysadr; MentionSubject: Re: [mne-tools/mne-python] Cannot manually select tracing on the plotted source space estimate (plotted stc object)! (#9786) Hi Aqil @izadysadr,Thanks for reporting this issue. I have moved the issue from the MNE-NIRS repository to the MNE-Python repository because I think/guess that this is due to the underlying MNE-Python code, also there are more eyes here to help you out.Regarding the issue you face, could you please provide the system info that was requested in the issue template.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by larsoner** [comment]
You can either change the line [to this](https://github.com/mne-tools/mne-python/blob/9c7e837f59e480fff1b6ea5841630e089aa5a235/mne/viz/_brain/_brain.py#L1415-L1416), downgrade to PyVista < 0.30, or upgrade MNE-Python to latest `main`. I wonder if we should backport this fix since we don't release for another month-ish.

**Comment by izadysadr** [comment]
Thank you for your email. I applied the suggested changes to the code, and now tracing works! Great job! However, I still receive the following errors in my Spyder console when I plot the stc object: Using control points [1.74975597 1.92527842 3.13917643]C:\Users\Aqil\anaconda3\envs\mne\lib\site-packages\pyvista\core\dataset.py:1192: PyvistaDeprecationWarning: Use of `point_arrays` is deprecated. Use `point_data` instead.  warnings.warn(C:\Users\Aqil\anaconda3\envs\mne\lib\site-packages\pyvista\core\dataset.py:1192: PyvistaDeprecationWarning: Use of `point_arrays` is deprecated. Use `point_data` instead.  warnings.warn( QWindowsWindow::setGeometry: Unable to set geometry 1131x1216+640+276 (frame: 1149x1261+631+240) on QWidgetWindow/"MainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1131x1057+640+276 (frame: 1149x1102+631+240) margins: 9, 36, 9, 9 minimum size: 394x210 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=412,255 maxtrack=0,0)C:\Users\Aqil\anaconda3\envs\mne\lib\site-packages\pyvista\core\dataset.py:1192: PyvistaDeprecationWarning: Use of `point_arrays` is deprecated. Use `point_data` instead.  warnings.warn( Thank you! Best,Aqil From: Eric LarsonSent: Tuesday, September 28, 2021 10:04 AMTo: mne-tools/mne-pythonCc: izadysadr; MentionSubject: Re: [mne-tools/mne-python] Cannot manually select tracing on the plotted source space estimate (plotted stc object)! (#9786) You can either change the line to this, downgrade to PyVista < 0.30, or upgrade MNE-Python to latest main. I wonder if we should backport this fix since we don't release for another month-ish.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
