### ISSUE TITLE
Averaging across frequencies - frequency band representation

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-python#9793]
#### Describe the new feature or enhancement
In `EpochsTFR` and `AverageTFR`, it would be nice to be able to average across frequencies and store the frequency band set name.

Taking the average over the frequency axis within a frequency band (e.g. delta would average power in frequencies 1-4 Hz) is a common workflow taken on by researchers.

#### Describe your proposed implementation
In the [current implementation](https://mne.tools/dev/generated/mne.time_frequency.AverageTFR.html), we would have to add:

- `average_freq(band_name)` function, which then assigns a `band_name` property
- `n_ave_freqs` which denotes the number of frequencies averaged. Analagous to `nave` for number of epochs averaging.
- `band_name` property storing the frequency band name

#### Describe possible alternatives
I currently do all this with custom numpy code, but it's very messy after awhile. + You can't really leverage the `AverageTFR.save()` functionalities, or have to hack around it.

#### Additional Information
https://mne.tools/dev/overview/roadmap.html seems to also point in the same direction where TFR analysis and data structures are still lacking in certain flexibility.

A workflow that I'm using rn is:
- use `make_fixed_length_epochs` to form an Epochs data structure
- compute `EpochsTFR` (e.g. using `tfr_multitaper`)
- save it for downstream processing
- read it back in with `read_tfrs`, and then format it back into a `(channels, freqs, times)` array, where the `times` axis is governed by the start time of each Epoch (stored in the `events` property). I then average across frequencies for e.g. the delta band.
- Now I can plot a spectrogram. 

By allowing averaging across frequencies, I can get rid of some intermediate storage.

**Comment by larsoner** [comment]
Introducing a new `band_name` just in the case of averaging I'm not sure about -- classes having properties (or not) based on what methods have been makes everything more difficult. Instead, at least to start, can we just reassign `frequencies` to be the center of the band, and replace the entries of the frequencies averaged over with a single one for the average? So for example if you have 1, 2, 3, 4, ... Hz TFR data and you average over the frequencies from 1-4 you now get a single row in the data now at frequency 2.5 that replaces the rows and `frequencies` entries from 1-4?
