### ISSUE TITLE
Synchronize `__repr__()` and `_repr_html_()`

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#9830]
TIL that `Info` has a dedicated HTML representation, which is 🔥. However, I don't like that it doesn't show the same information as the standard text representation, for example:
![Screen Shot 2021-10-11 at 15 50 49](https://user-images.githubusercontent.com/4377312/136801666-319df910-f6c7-4497-94e8-085f5f35334e.png)
Specifically, I really miss the channel names and I don't like that MEG types are always listed, but ideally there should be no differences at all except for a nicer rendering in HTML. WDYT?

**Comment by agramfort** [comment]
I am just +0.5 on add a key column to html repr

>

**Comment by cbrnr** [comment]
BTW, the same applies to `Raw` and `Epochs`. I think that the two reprs should contains the same pieces of information.

**Comment by cbrnr** [comment]
I find it very strange to show different pieces of information depending on which backend is used. What exactly is the reason why showing exactly the same information is not feasible? The HTML repr is also just text which should easily fit in a terminal. This should not just synced for `Info`, but also for `Raw`, `Epochs`, and `ICA`(I don't think we have more).

**Comment by hoechenberger** [comment]
That said, +1 on ensuring they're more synchronous, but please don't make the HTML repr just an ugly HTML-ified copy of the text repr. It can do much better than that.

**Comment by cbrnr** [comment]
I'm still -1 on using different reprs. I can already imagine the confusion when people notice that the output (repr) of an object in the interactive interpreter is widely different from inside a notebook. If you want to add nice HTML summaries I'd really prefer if that had its own dedicated method (e.g. `raw.print_html()` or even `raw.print()`). Changing the default repr is asking for trouble.

**Comment by cbrnr** [comment]
I would like to res this issue because I think the current dissociation between the two reprs can be very confusing. Specifically, when writing some tutorial in a notebook-like environment, people should see the exact same output whether they are in a REPL or a notebook. In general, I prefer the REPL, but I write my tutorial with Quarto (which uses Jupyter notebook under the hood), so when I tell people to run e.g.

```
raw.info
```

I would like to see the REPL `__repr__()` and not `_repr_html_()`.

Could we add a config option to disable all `_repr_html_()`?

**Comment by hoechenberger** [comment]
@cbrnr +1 for adding a configuration option if Jupyter doesn't support this. The default should IMHO still be to use HTML repr in a Jupyter environment.

**Comment by cbrnr** [comment]
This would be great! And yes, HTML can remain the default for notebook envs.

Does anyone have an idea how to implement this technically? I briefly looked at how it's done in Scikit-learn, but couldn't really figure it out so I guess this will be a larger change.

I will also ask the IPython devs if they think this could be added on their end. Doesn't make a lot of sense that every package has to implement that.

**Comment by hoechenberger** [comment]
> Does anyone have an idea how to implement this technically? I briefly looked at how it's done in Scikit-learn, but couldn't really figure it out so I guess this will be a larger change.

Could you not simply do something like this:
```python
def _repr_html_(self):
    if config.no_html_repr:
        return repr(self)
```
?

**Comment by cbrnr** [comment]
Unfortunately, this doesn't work (nothing gets printed). It seems like it's not just the returned value that's needed by the notebook.

**Comment by hoechenberger** [comment]
This works for me in the VS Code Python Interactive Jupyter thingy:

```python
# %%
class Test:
    def __repr__(self) -> str:
        return 'foobar'

    def _repr_html_(self) -> str:
        return repr(self)


test = Test()
test
```
<img width="599" alt="Screen Shot 2022-09-13 at 13 43 41" src="https://user-images.githubusercontent.com/2046265/189892404-85d9ea0b-a0f6-4a0d-91ae-bceba4bfe1b5.png">

**Comment by hoechenberger** [comment]
@cbrnr I assume you'll have to encode the `<` etc symbols

**Comment by hoechenberger** [comment]
> @cbrnr I assume you'll have to escape the `<` etc symbols

Yep.

```python
# %%
class Test:
    def __repr__(self) -> str:
        return '<foobar>'

    def _repr_html_(self) -> str:
        return repr(self)


test = Test()
test
``` 
prints nothing.

But this works:
```python
# %%
import html

class Test:
    def __repr__(self) -> str:
        return '<foobar>'

    def _repr_html_(self) -> str:
        return html.escape(
            repr(self)
        )


test = Test()
test
```
<img width="478" alt="Screen Shot 2022-09-13 at 13 46 27" src="https://user-images.githubusercontent.com/2046265/189892895-2b2c7642-66e1-4f75-8fd4-7f14c39b11b8.png">

**Comment by cbrnr** [comment]
Line breaks `\n` should not be escaped though – is this possible?

**Comment by cbrnr** [comment]
The font is also not a fixed-width font, which ideally would be nice to have as well...

**Comment by cbrnr** [comment]
This should do it:

```python
import html

class Test:
    def __repr__(self) -> str:
        return '<foo>\n<bar>'

    def _repr_html_(self) -> str:
        r = "<pre>" + html.escape(repr(self)) + "</pre"
        return r.replace("\n", "<br/>")


test = Test()
test
```
