### ISSUE TITLE
Figures show up twice in notebooks

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#9832]
Figures in a notebook show up twice, for example:
<img width="658" alt="Screen Shot 2021-10-12 at 10 22 52" src="https://user-images.githubusercontent.com/4377312/136942665-82385dc5-47d8-4fe4-9417-ad8eb19f504b.png">

It looks like setting `show=False` does not have any effect here. Any ideas why this is the case and how to fix that?

**Comment by agramfort** [comment]
end the line with a semi-colon ";" to avoid seeing it twice

**Comment by larsoner** [comment]
Closing as an upstream bug / wontfix here
