### ISSUE TITLE
ICA tutorial text is out-of-sync with the figures/output

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#9836]
I noticed today that in the `corrmap` section of the ICA tutorial, the results have changed such that the text is no longer accurate.

- here is [the relevant section in version 0.22](https://mne.tools/0.22/auto_tutorials/preprocessing/plot_40_artifact_correction_ica.html#selecting-ica-components-using-template-matching) where the intial call to `corrmap` misses finding a component for one subject
- here is [the same section on current stable](https://mne.tools/stable/auto_tutorials/preprocessing/40_artifact_correction_ica.html#selecting-ica-components-using-template-matching) where a component is found for all 4 subjects, making the text inaccurate.

I have no idea what could have caused the corrmap results to change, but I think @hoechenberger and maybe @cbrnr worked on some changes to the ICA defaults in the last year that might be the cause?  Can either of you think offhand why this happened, or have a suggestion as to what to do to fix it?  The basic options seem to be

1. update the tutorial to just state what the new results show, and remove the subsequent section where we tweak the corrmap parameters until we get a component for all subjs
2. pass different params to ICA (?) in the tutorial such that we get the old results back, and otherwise leave the tutorial unchanged

I lean toward option 1 because the first-pass results now are actually better than they used to be... however I also thought the param-tweaking part of the tutorial was instructive in a nice way that our tutorials often aren't (i.e., too often everything works and looks beautiful with no tweaking); hence I'm reluctant to delete it.

**Comment by hoechenberger** [comment]
@larsoner had also fixed some issues related to algebraic stability when using rank-deficient data. Could also have had an impact.
