### ISSUE TITLE
Problems of ploting ERPs of different groups with different subject numbers

### ISSUE THREAD

**Issue by vincent5290** [mne-tools/mne-python#9854]
Dear all,
Now, I met a problems, that in my study, I have two conditions: 1 is within subject and 1 is between subject factor. Now I want to plot the ERPs with group comparsion, so how to do it? I know how to do in within subject.
I would appreciate it a lot if anyone can suggest.
*Please make the issue title a succinct description of your proposed change.
For example: "add 'foo' to the glossary" or "add my favorite visualization to
the ERP tutorial".*

#### Proposed documentation ehancement
*Describe your proposed enhancement in detail. If you are requesting a new
glossary term, please include a proposed definition.*

**Comment by hoechenberger** [comment]
This question has been cross-posted on the forum and will be addressed there:
https://mne.discourse.group/t/how-to-plot-erp-results-of-comparing-groups-with-different-subject-numbers/3818
