### ISSUE TITLE
Allow making evokeds per event type

### ISSUE THREAD

**Issue by wmvanvliet** [mne-tools/mne-python#9856]
#### Describe the new feature or enhancement
It is very common that you want Evokeds for each event type, for example:
```python
epochs = mne.Epochs(raw, events, {'left': 1, 'right': 2})
evokeds = [epochs['left'].average(), epochs['right'].average()]  # <-- Make this easier
```

#### Describe your proposed implementation
Add a parameter to the `Epochs.average` method:
```python
evokeds = epochs.average(per_event_type=True)
```

Furthermore, the `.comment` attribute should be set to the event type.

#### Describe possible alternatives
Keep the following list comprehension as canonical solution:
```python
evokeds = [epochs[cond] for cond in epochs.event_id.keys()]
for ev, cond in zip(evokeds, epochs.event_id.keys()): 
    ev.comment = cond
```

**Comment by larsoner** [comment]
I guess we could keep the API `per_event_id=False (default) | True` then later add support for `per_event_id=<list of list>` if we want it. It makes it a little bit of a misnomer but it seems easier than `event_id='all' (default) | 'separate'` or something. Maybe there is a better name that allows us to keep `bool` but later add `list of list`, or maybe `'all' | 'separate'` is good enough to start...?
