### ISSUE TITLE
Bug in _repr_html_ for raw objects generated with RawArray

### ISSUE THREAD

**Issue by christian-oreilly** [mne-tools/mne-python#9865]
#### Describe the bug
`Raw` objects generated by `RawArray` calls have `raw._filenames` initiated to `[None]` which causes MNE to crash when calling `_repr_html_` on such Raw objects. Using `""` instead of `None` would solve this issue (not sure if that might not create other side effects, but setting `raw._filenames = [""]` explicitly works for me.

#### Steps to reproduce
In a notebook:

```python
import mne
import numpy as np

samp_freq = 500  # Hz
duration = 10  # s
nb_channels = 128
fake_eeg = np.random.rand(nb_channels, samp_freq*duration)  # fake data
ch_channels = [f"E{no_ch}" for no_ch in range(128)]
info = mne.create_info(ch_channels, samp_freq, ch_types='eeg')
raw = mne.io.RawArray(fake_eeg, info)
print(raw._filenames)
raw
```
 (Can also be reproduced outside of a notebook context by calling explicitly `raw._repr_html_()`)

#### Actual results
```
Creating RawArray with float64 data, n_channels=128, n_times=5000
    Range : 0 ... 4999 =      0.000 ...     9.998 secs
Ready.
[None]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/opt/anaconda3/lib/python3.8/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~/opt/anaconda3/lib/python3.8/site-packages/mne/io/base.py in _repr_html_(self, caption)
   1761 
   1762     def _repr_html_(self, caption=None):
-> 1763         basenames = [os.path.basename(f) for f in self._filenames]
   1764         m, s = divmod(self._last_time - self.first_time, 60)
   1765         h, m = divmod(m, 60)

~/opt/anaconda3/lib/python3.8/site-packages/mne/io/base.py in <listcomp>(.0)
   1761 
   1762     def _repr_html_(self, caption=None):
-> 1763         basenames = [os.path.basename(f) for f in self._filenames]
   1764         m, s = divmod(self._last_time - self.first_time, 60)
   1765         h, m = divmod(m, 60)

~/opt/anaconda3/lib/python3.8/posixpath.py in basename(p)
    140 def basename(p):
    141     """Returns the final component of a pathname"""
--> 142     p = os.fspath(p)
    143     sep = _get_sep(p)
    144     i = p.rfind(sep) + 1

TypeError: expected str, bytes or os.PathLike object, not NoneType
```

#### Additional information

Platform:      macOS-10.16-x86_64-i386-64bit
Python:        3.8.8 (default, Apr 13 2021, 12:59:45)  [Clang 10.0.0 ]
Executable:    /Users/christianoreilly/opt/anaconda3/bin/python
CPU:           i386: 16 cores
Memory:        64.0 GB

mne:           0.23.4
numpy:         1.19.2 {blas=mkl_rt, lapack=mkl_rt}
scipy:         1.6.2
matplotlib:    3.4.2 {backend=module://matplotlib_inline.backend_inline}

sklearn:       0.24.2
numba:         0.53.0
nibabel:       3.2.1
nilearn:       Not found
dipy:          Not found
cupy:          Not found
pandas:        1.3.2
mayavi:        Not found
pyvista:       Not found
vtk:           Not found

**Comment by larsoner** [comment]
This was fixed back in May in https://github.com/mne-tools/mne-python/pull/9404, but we never backported. Given that we've had a couple of duplicate issues about this in the meantime, I'm inclined to backport and push out 0.23.5, even though we're releasing 0.24 in a few weeks. In the meantime @christian-oreilly you can use latest `main` if you're feeling brave

Thoughts about a quick 0.23.5 @agramfort ?

**Comment by christian-oreilly** [comment]
Noted. Sorry for the duplicate report then!

Le sam. 16 oct. 2021 à 16:08, Eric Larson ***@***.***> a
écrit :
