### ISSUE TITLE
Epochs.plot_psd_topomap() doesn't apply unit scaling

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#9870]
`Epochs.plot_psd` does scale the measurement units while `Epochs.plot_psd_topomap` doesn't, [causing confusion](https://mne.discourse.group/t/psd-different-units/3809/15)

```python
import os.path as op
import mne
from mne.datasets import somato

data_path = somato.data_path()
subject = '01'
task = 'somato'
raw_fname = op.join(data_path, 'sub-{}'.format(subject), 'meg',
                    'sub-{}_task-{}_meg.fif'.format(subject, task))

raw = mne.io.read_raw_fif(raw_fname)
events = mne.find_events(raw, stim_channel='STI 014')

picks = mne.pick_types(raw.info, meg='grad', eeg=False, eog=True, stim=False)
event_id, tmin, tmax = 1, -1., 3.
baseline = (None, 0)
epochs = mne.Epochs(raw, events, event_id, tmin, tmax, picks=picks,
                    baseline=baseline, reject=dict(grad=4000e-13, eog=350e-6),
                    preload=True)

epochs.resample(200., npad='auto')  # resample to reduce computation time

fmin = 0.1
fmax = 40

epochs.plot_psd(fmin=fmin, fmax=fmax, average=True, dB=True, area_mode=None)
epochs.plot_psd_topomap(dB=True)
```

![a](https://user-images.githubusercontent.com/2046265/137897334-aa71a546-e7b2-4086-9d7c-d516b4b0f4ec.png)

![b](https://user-images.githubusercontent.com/2046265/137897379-9d64af29-1670-4201-9624-db696d707739.png)

The displayed data  have a scale difference of precisely 13 orders of magnitude.

cc @cbrnr @guiomar

**Comment by hoechenberger** [comment]
> Currently we only show (fT/cm)^2/Hz,

No, we show `(fT/cm)^2/Hz (dB)` 😅

**Comment by agramfort** [comment]
👍

**Comment by hoechenberger** [comment]
@cbrnr Would you like to take a stab at a PR to adjust the y-axis labels?
