### ISSUE TITLE
Output data in plot functions

### ISSUE THREAD

**Issue by guiomar** [mne-tools/mne-python#9872]
#### Describe the new feature or enhancement
Currently, plot funtions just make some computations and plot the results. But users aren't able to retrieve this data.
For example, in `plot_psd()` function, the psd is computed and the plotted, but there's no way of accessing the data arrays and channels of plotted data.

I think that plotting functions should return the output arrays of data plotted, in order to promote transparency and facilitate the tool usage. There are equivalent functions for a few of these functions (eg. psd_welch()), but still I don't feel comfortable of computing some values and then representing others with the plot functions, without the certainty that both are the same (and there's not actual way of determining if they are the same other than plotting). Since mne plots are very beautiful, I think it would be a waste of time having to re implement them just to visualize results obtained with equivalent functions.

#### Describe your proposed implementation
The implementation of this change shouldn't be difficult, since the values are actually there for being plotted.

Thanks once more for all the effort put in this awesome toolbox!!

**Comment by drammock** [comment]
> is it available now?

Sort of. There is indeed now [a Spectrum class](https://mne.tools/stable/generated/mne.time_frequency.Spectrum.html#mne.time_frequency.Spectrum) and methods [Raw.compute_psd](https://mne.tools/stable/generated/mne.io.Raw.html#mne.io.Raw.compute_psd), [Epochs.compute_psd](https://mne.tools/stable/generated/mne.Epochs.html#mne.Epochs.compute_psd) and [Evoked.compute_psd](https://mne.tools/stable/generated/mne.Evoked.html#mne.Evoked.compute_psd) to create Spectrum (or EpochsSpectrum) instances. However, the Spectrum instances will always store the estimates as power (not amplitude, and not dB scaled). So you'd need to do something like

```py
power_spectrum = raw.compute_psd()
ampl_spectrum = np.sqrt(power_spectrum.get_data())
dB_power_spectrum = 10 * np.log10(power_spectrum.get_data())
dB_ampl_spectrum = 20 * np.log10(np.sqrt(power_spectrum.get_data()))
```
