### ISSUE TITLE
Support STIM channels in EDF export

### ISSUE THREAD

**Issue by cbrnr** [mne-tools/mne-python#9883]
I found some issues with our recently added EDF export that we might want to fix before the next release:

1. The error if `EDFlib-Python` is not installed is misleading, because it says `RuntimeError: For exporting to EDF to work, the EDFlib module is needed, but it could not be imported`. However, although the import name is `EDFlib`, the PyPI name is actually `EDFlib-Python` and `EDFlib` is a different PyPI package (which requires Cython etc.).
2. `EDFlib-Python` is super slow compared to `pyEDFlib` (which uses the C implementation). I tested exporting with one of our BDF files from our lab (425MB), and it took `EDFlib-Python` 1 minute and 52 seconds to export. For comparison, `pyEDFlib` took only 6 seconds.
3. Analog stim channels are not exported. This is essential in BDF files, because Biosemi amplifiers do not have discrete triggers and instead always write an analog stim channel. There is no technical reason to not export stim channels in addition to EEG (other than carefully setting the scaling, unit, and physical min/max). I've fixed this in my EDF/BDF export implementation in MNELAB recently (today) in https://github.com/cbrnr/mnelab/pull/230.

The first issue is probably easy to fix. The second issue is pretty serious, we can't expect that users wait almost 2 minutes for something that can be done in 6 seconds. I'd consider switching to `pyEDFlib` instead (they have binary wheels and AFAIR the restriction to use pure Python applies only to our project but not external dependencies). The third issue requires some work, but this is important for BDF files.

**Comment by cbrnr** [comment]
And by "just" I thought that it was going to be as easy as using my existing function, but I don't have the time to adapt all the tests and whatnot (I just tried). The export module is so convoluted that I can't "just" use my existing function. So if anyone wants to take this over please knock yourself out.

**Comment by withmywoessner** [comment]
@cbrnr Do you still have your function? I could try adapting the tests to it.

**Comment by cbrnr** [comment]
Yes, it's here: https://github.com/cbrnr/mnelab/blob/main/mnelab/io/writers.py#L57

Since it's been 1.5 years since I last tried to work on that, it might be worth checking how much functionality has been added to EDF export in MNE which is not present in my implementation.

**Comment by withmywoessner** [comment]
@cbrnr I wrote something that works using pyedflib. The only problem is that the final output differs more than the test allows:
```
absolute tolerance: 0.01

Not equal to tolerance rtol=0, atol=0.01

Mismatched elements: 8540 / 14400 (59.3%)
Max absolute difference: 0.02457271
Max relative difference: 0.00102393
 x: array([0.000000e+00, 1.664960e-03, 3.329920e-03, ..., 2.397043e+01,
       2.397210e+01, 2.397376e+01])
 y: array([0.000000e+00, 1.666667e-03, 3.333333e-03, ..., 2.399500e+01,
       2.399667e+01, 2.399833e+01])

absolute tolerance: 0.1
Success!
```
Is a tolerance of .1 enough? It might have to do with the fact that the testing data has a non integer sampling rate and the physical maxes and mins are of high precision (pyedflib only accepts up to 4 decimal places).

**Comment by cbrnr** [comment]
Which test is this? It depends on the scale of the data, but even if that's µV, I think a tolerance of 0.1 is not ... tolerable 😄.

**Comment by withmywoessner** [comment]
It is `test_export_raw_edf`. I saw in your code you used `writeSamples`. In mine, I replace the current write function with [writePhysicalSamples](writePhysicalSamples). I am not sure why there is such a large difference in values...

**Comment by cbrnr** [comment]
Yes, please submit a PR and we can discuss the tolerance issue there!

**Comment by withmywoessner** [comment]
@cbrnr I made a PR whenever you have a change to look :)

**Comment by cbrnr** [comment]
The first two issues have been fixed by switching to edfio. Now there's only one issue left, namely exporting STIM channels (I think MISC channels are already supported).
