### ISSUE TITLE
coreg gui: Expand tooltip for "Copy FsAverage to Subjects Folder"

### ISSUE THREAD

**Issue by TalLinzen** [mne-tools/mne-python#989]
The new coregistration GUI by @christianmbrodbeck has a somewhat mysterious button labeled "Copy FsAverage to Subjects Folder", that's apparently greyed out unless you've set the environment variables FREESURFER_HOME and MNE_ROOT, but the tooltip doesn't indicate that (had to look at the source to learn that). Also, it's not entirely clear when you'd want to use this button. Perhaps the tooltip for this button could be expanded?

**Comment by Eric89GXL** [comment]
I *think* this issue has been mostly fixed -- the tooltip seems okay/functional. But maybe @christianbrodbeck we should change the tooltip to mention why the button is grayed out when it's grayed out? Is that easy?

**Comment by christianbrodbeck** [comment]
I added a corresponding comment in my other PR: https://github.com/mne-tools/mne-python/pull/3948/commits/580029296ba85635ecf0d5b02ce20b034b01a45c
