### ISSUE TITLE
viz.plot_compare_evokeds incorrect axis labels

### ISSUE THREAD

**Issue by c-torre** [mne-tools/mne-python#9923]
Hi, I've started a discussion in the forum that turned out to be a bug.

Please see: https://mne.discourse.group/t/misaligned-viz-plot-compare-evokeds/3834

In short, as last answer by @drammock summarizes:  "`plot_compare_evokeds(..., axes='topo')` tries to create an extra axis that shows only the axis spines, ticklabels, and axis labels. It looks like that “legend axis” is getting plotted on top of the axis for P8"

**Comment by drammock** [comment]
code to reproduce with sample dataset:

```py
import os
import mne
sample_data_folder = mne.datasets.sample.data_path()
sample_data_evoked_file = os.path.join(
    sample_data_folder, 'MEG', 'sample', 'sample_audvis-ave.fif')
evoked_list = mne.read_evokeds(sample_data_evoked_file)
picks = [f'EEG {n:03}' for n in (30, 31, 40)]
fig = mne.viz.plot_compare_evokeds(evoked_list, picks=picks, axes='topo')
```

looking into this now
