### ISSUE TITLE
BUG: Tags with spaces are broken

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#9965]
This:
```
import mne
import matplotlib.pyplot as plt
report = mne.Report()
figs, captions = list(), list()
for n in range(2):
    fig, ax = plt.subplots()
    ax.text(0, 0, str(n))
    figs.append(fig)
    captions.append(str(n))
report.add_figure(figs, 'numbers', caption=captions, tags=['My numbers'])
report.save('rep.html', overwrite=True)
```
is broken -- the top bar covers content, and the sliders do not work:

![Screenshot from 2021-11-05 10-43-33](https://user-images.githubusercontent.com/2365790/140529033-4b36e284-edf8-4311-a532-63319e39bac8.png)

If I change it to `tags['My_numbers']` it works fine:

![Screenshot from 2021-11-05 10-43-49](https://user-images.githubusercontent.com/2365790/140529045-95106962-eb90-4cbb-b0e8-08c15d517aad.png)

@hoechenberger can you look?

**Comment by hoechenberger** [comment]
Looks like insufficient tag sanitization, they must not contain any spaces. Will have a look.

**Comment by larsoner** [comment]
A nice solution would be to replace spaces with underscores just in the CSS and such and still display visually with spaces, but if that's not possible or too hard, then just raising an error when people have spaces in their tags is okay, too
