### ISSUE TITLE
Typo in argument `pad` docstring for resample.

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-python#9983]
Example:
- https://mne.tools/stable/generated/mne.filter.resample.html?highlight=resample#mne.filter.resample
- https://mne.tools/stable/generated/mne.io.Raw.html#mne.io.Raw.resample

Argument `pad`:

> The type of padding to use. Supports all numpy.pad() mode options. Can also be “reflect_limited”, which pads with a reflected version of each vector mirrored on the first and last values of the vector, followed by zeros. Only used for method='fir'. The default is 'reflect_limited'.

-> `Only used for method='fir'`. There is no argument `method`, I guess it was deprecated?

**Comment by larsoner** [comment]
It's just a carryover from the fact that this docstring is shared between `resample` and `filter`. For `filter` it makes sense to talk about `method='fir'` versus `method='iir'` because `method` does exist there. For `resample` it does not. So these docs need to be refactored
